Repository home-assistant/home-assistant.io, pull requests merged in 2018-03, with the labels that each got.

#4730 documentation for synology chat as a notification platform
  source/_components/notify.synology_chat.markdown
Labels: New-component/platform

#4543 Add UpCloud platform
  source/_components/binary_sensor.upcloud.markdown
  source/_components/switch.upcloud.markdown
  source/_components/upcloud.markdown
  source/images/supported_brands/upcloud.png
Labels: New-component/platform

#4397 Sense monitor documentation
  source/_components/sensor.sense.markdown
  source/images/supported_brands/sense.png
Labels: New-component/platform

#4839 updated dead link
  source/_cookbook/configuration_yaml_by_greenturtwig.markdown
Labels: Fix/Formatting/Language/Spelling

#4841 Fix sunrise example
  source/_docs/ecosystem/appdaemon/tutorial.markdown
Labels: Fix/Formatting/Language/Spelling

#4832 Update documentation to reflect correct radius measurement
  source/_components/sensor.spotcrime.markdown
Labels: Fix/Formatting/Language/Spelling

#4821 Changed the PSU link to be to the power reqs
  source/getting-started/index.markdown
Labels: Fix/Formatting/Language/Spelling

#4820 Added PSU warning
  source/_docs/installation/raspberry-pi.markdown
Labels: Enhancement

#4764 fixed version smappee component was added in
  source/_components/sensor.smappee.markdown
  source/_components/smappee.markdown
  source/_components/switch.smappee.markdown
Labels: Fix/Formatting/Language/Spelling

#4760 re-adding that the add-on makes use of port 80
  source/_addons/lets_encrypt.markdown
Labels: Enhancement

#4847 Fixes link to submit page in states documentation
  source/developers/development_states.markdown
Labels: Fix/Formatting/Language/Spelling

#4845 Update Synology installation instructions
  source/_docs/installation/synology.markdown
Labels: Fix/Formatting/Language/Spelling

#4804 Changed example to ACM from USB
  source/_docs/z-wave/installation.markdown
Labels: Fix/Formatting/Language/Spelling

#4837 Change wording to locate logs
  source/hassio/installing_third_party_addons.markdown
Labels: Fix/Formatting/Language/Spelling

#4815 Update docker.markdown
  source/_docs/installation/docker.markdown
Labels: Enhancement

#4761 Fix MQTT discovery object_id docs
  source/_docs/mqtt/discovery.markdown
Labels: Fix/Formatting/Language/Spelling

#4849 nginx rev proxy minimal version 1.3.13
  source/_docs/ecosystem/nginx.markdown
Labels: Enhancement

#4828 nginx proxy config updates
  source/_addons/nginx_proxy.markdown
Labels: Enhancement

#4851 Update index.markdown
  source/hassio/index.markdown
Labels: Fix/Formatting/Language/Spelling

#4781 Xiaomi MiIO Components: Format of the services updated
  source/_components/fan.xiaomi_miio.markdown
  source/_components/light.xiaomi_miio.markdown
  source/_components/vacuum.xiaomi_miio.markdown
Labels: Fix/Formatting/Language/Spelling

#4779 Add docs for optional words in conversation utterances
  source/_components/conversation.markdown
  source/images/screenshots/voice-commands.png
Labels: Enhancement

#4833 adding a method to Recovery the token
  source/_components/vacuum.xiaomi_miio.markdown
Labels: Enhancement

#4812 Create sensor.zestimate.markdown
  source/_components/sensor.zestimate.markdown
Labels: New-component/platform

#4751 Update ubus documentation for optional DHCP name resolution
  source/_components/device_tracker.ubus.markdown
Labels: Enhancement

#4816 Update docker compose examples
  source/_docs/installation/docker.markdown
Labels: Enhancement

#4755 MQTT Sensor - JSON attributes example
  source/_components/sensor.mqtt.markdown
Labels: Enhancement

#4680 updated documentation: show on map
  source/_components/sensor.luftdaten.markdown
Labels: New-feature

#4782 Xiaomi MiIO Switch: Unavailable state introduced if the device isn't reachable
  source/_components/switch.xiaomi_miio.markdown
Labels: New-feature

#4602 Documenting additional Tesla functionality
  source/_components/tesla.markdown
Labels: New-feature

#4843 Added instructions for magisk based root
  source/_components/vacuum.xiaomi_miio.markdown
Labels: Enhancement

#4844 Current Mi-Home app does not store the token with the db
  source/_components/vacuum.xiaomi_miio.markdown
Labels: Enhancement

#4838 Added new supported devices
  source/_components/homekit.markdown
Labels: New-feature

#4854 Current
  source/developers/architecture.markdown
  source/images/architecture/ha_architecture.svg
Labels: Enhancement

#4739 Add light.group platform docs
  source/_components/light.group.markdown
  source/images/components/light/group.png
Labels: New-component/platform

#4469 Add ‘unit_system’ configuration variable
  source/_components/sensor.fitbit.markdown
Labels: New-feature

#4445 Added support for multiple onvif profiles
  source/_components/camera.onvif.markdown
Labels: New-feature

#4570 Add sony songpal docs
  source/_components/media_player.songpal.markdown
  source/images/supported_brands/sony.png
Labels: New-component/platform

#4873 Glances Docker Sensors
  source/_components/sensor.glances.markdown
Labels: New-feature

#4861 Added icon property to one of the examples
  source/_components/weblink.markdown
Labels: Enhancement

#4877 Updated git diff statement
  source/developers/development_testing.markdown
Labels: Fix/Formatting/Language/Spelling

#4875 Update persistent_notification.markdown
  source/_components/persistent_notification.markdown
Labels: Fix/Formatting/Language/Spelling

#4900 Added version note
  source/_docs/installation/synology.markdown
Labels: Enhancement

#4888 Bumped version to be explicitly 3.5.3
  source/_docs/installation.markdown
Labels: Fix/Formatting/Language/Spelling

#4890 Bumped version to be explicitly 3.5.3
  source/_docs/installation/macos.markdown
Labels: Enhancement

#4891 Bumped to Python 3.6 from 3.4
  source/_docs/installation/centos.markdown
Labels: Enhancement

#4887 Minimum Python version requirements
  source/_docs/installation/raspberry-pi.markdown
Labels: Enhancement

#4892 Provided note about python versions
  source/_docs/installation/synology.markdown
Labels: Enhancement

#4903 Added instructions for custom UIs to show up in the HA dev info panel
  source/developers/frontend_creating_custom_ui.markdown
Labels: Fix/Formatting/Language/Spelling

#4905 Update (fixes #4868)
  source/_docs/installation/archlinux.markdown
Labels: Fix/Formatting/Language/Spelling

#4867 Added info on AND condition
  source/_docs/scripts/conditions.markdown
Labels: Enhancement

#4902 Update the hassbian image file size
  source/_docs/installation/hassbian/installation.markdown
Labels: Fix/Formatting/Language/Spelling

#4634 Update backup_usb.markdown
  source/_docs/ecosystem/backup/backup_usb.markdown
Labels: Enhancement

#4749 Remove Z-Wave old entity IDs
  source/_docs/z-wave/control-panel.markdown
  source/_docs/z-wave/installation.markdown
Labels: New-feature

#4914 Update documentation for Speedtest Sensor
  source/_components/sensor.speedtest.markdown
Labels: Enhancement

#4766 Update USPS docs to include required driver declaration
  source/_components/usps.markdown
Labels: Enhancement

#4811 Added theme colour
  .themes/classic/source/_includes/head.html
Labels: Enhancement

#4912 Updated SCL command to Python 3.6 instead of 3.5
  source/_docs/installation/centos.markdown
Labels: Enhancement

#4840 Update sensor.spotcrime.markdown
  source/_components/sensor.spotcrime.markdown
Labels: New-feature

#4859 Vectorize architecture #2
  source/developers/architecture.markdown
  source/images/architecture/home_automation_landscape.svg
Labels: Enhancement

#4864 Add VeSync documentation and image
  source/_components/switch.vesync.markdown
  source/images/supported_brands/vesync.png
Labels: New-component/platform

#4856 Explain workaround for limitlessled assumed_state
  source/_components/light.limitlessled.markdown
  source/images/screenshots/limitlessled_assumed_state.png
Labels: Enhancement

#4916 Update downloader.markdown
  source/_components/downloader.markdown
Labels: New-feature

#4915 Homekit: Updated docs for Restructure PR
  source/_components/homekit.markdown
Labels: New-feature, Ready for review

#4638 Added cover group platform
  source/_components/cover.group.markdown
Labels: New-component/platform

#4557 Changed note about base url
  source/_components/tts.markdown
Labels: Enhancement

#4918 Adds rel nofollow to external links
  Gemfile
  Gemfile.lock
  plugins/no_follow.rb
  source/_layouts/default.html
Labels: Enhancement

#4733 Documentation for extra sensors BMW Connected Drive
  source/_components/binary_sensor.bmw_connected_drive.markdown
  source/_components/lock.bmw_connected_drive.markdown
Labels: New-component/platform

#4670 Foobot
  source/_components/sensor.foobot.markdown
  source/images/supported_brands/foobot.png
Labels: New-component/platform

#4921 Added Stride notification component
  source/_components/notify.stride.markdown
  source/images/supported_brands/stride.png
Labels: New-component/platform

#4925 HomeKit: Added additional supported devices
  source/_components/homekit.markdown
Labels: New-feature, Ready for review

#4929 Update configuration.markdown's addon store image
  source/getting-started/configuration.markdown
Labels: Fix/Formatting/Language/Spelling

#4930 Update addon_tutorial.markdown's addon store image
  source/developers/hassio/addon_tutorial.markdown
Labels: Fix/Formatting/Language/Spelling

#4928 Xiaomi Miio Fan: Undocumented service (fan.set_speed) added
  source/_components/fan.xiaomi_miio.markdown
Labels: Enhancement, Fix/Formatting/Language/Spelling

#4935 Raspberry Pi 3 B+ note
  source/hassio/installation.markdown
Labels: Enhancement

#4934 Raspberry Pi 3 B+ note
  source/getting-started/index.markdown
Labels: Enhancement, Fix/Formatting/Language/Spelling

#4937 sun trigger - Link fix, wording tweak
  source/_docs/scripts/conditions.markdown
Labels: Enhancement, Fix/Formatting/Language/Spelling

#4940 Add information about Hassbian being available for the Raspberry Pi 3B+
  source/_docs/installation/hassbian.markdown
  source/_docs/installation/hassbian/installation.markdown
  source/getting-started/index.markdown
Labels: Enhancement

#4941 Update sensor.miflora.markdown
  source/_components/sensor.miflora.markdown
Labels: Fix/Formatting/Language/Spelling

#4931 Xiaomi MiIO Switch: Power Strip support improved
  source/_components/switch.xiaomi_miio.markdown
Labels: New-feature

#4780 Xiaomi MiIO Sensor: Xiaomi Air Quality Monitor (PM2.5) integration
  source/_components/sensor.xiaomi_miio.markdown
Labels: New-component/platform

#4825 Xiaomi MiIO light: Philips Eyecare Smart Lamp 2 integration
  source/_components/light.xiaomi_miio.markdown
Labels: New-feature

#4626 add doc for zha fans
  source/_components/fan.zha.markdown
  source/_components/zha.markdown
Labels: New-component/platform

#4878 Documentation for IFTTT alarm control panel
  source/_components/alarm_control_panel.ifttt.markdown
Labels: New-component/platform

#4850 Add initial support fo HomematicIP components
  source/_components/homematicip.markdown
Labels: New-component/platform

#4936 Small comment added to expose_by_default
  source/_components/google_assistant.markdown
Labels: Enhancement

#4926 Added Time SMA
  source/_components/sensor.filter.markdown
Labels: New-feature

#4946 Fix Duck DNS configuration example
  source/_addons/duckdns.markdown
Labels: Fix/Formatting/Language/Spelling

#4949 Added note to Owntracks about mqtt_topic parameter requirement for Zanzito usage
  source/_components/device_tracker.owntracks.markdown
Labels: Enhancement

#4957 Updated with new path.
  source/_components/feedreader.markdown
Labels: Fix/Formatting/Language/Spelling

#4956 Updated addon_communication.markdown to remove gender
  source/developers/hassio/addon_communication.markdown
Labels: Fix/Formatting/Language/Spelling

#4954 Tweaked automation
  source/_docs/scripts.markdown
Labels: Enhancement

#4953 Tweaked automation
  source/_docs/automation/condition.markdown
Labels: Enhancement

#4951 Tweaked automations
  source/_docs/automation/examples.markdown
Labels: Enhancement

#4952 Updated GPS tracker list
  source/_docs/automation/trigger.markdown
Labels: Enhancement

#4950 Updated the note about initial_state
  source/_docs/automation.markdown
Labels: Enhancement, Fix/Formatting/Language/Spelling

#4881 New hue/sat field on light.turn_on schema
  source/_components/light.markdown
Labels: New-feature

#4707 Syncthru Printer description
  source/_components/sensor.syncthru.markdown
Labels: New-component/platform

#4562 Add Trafikverket WeatherStation documentation
  source/_components/sensor.trafikverket_weatherstation.markdown
  source/images/screenshots/get_trafikverket_weather_station_example.png
  source/images/supported_brands/trafikverket.png
Labels: New-component/platform

#4907 Add Documentation for plex client cleanup options
  source/_components/media_player.plex.markdown
Labels: New-feature

#4948 Update sensor.tibber.markdown
  source/_components/sensor.tibber.markdown
Labels: New-feature

#4962 Update lets_encrypt.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: Enhancement

#4980 Link to DuckDNS not working.
  source/_addons/duckdns.markdown
Labels: Fix/Formatting/Language/Spelling

#4975 Xiaomi MiIO Switch: Typo fixed
  source/_components/switch.xiaomi_miio.markdown
Labels: Fix/Formatting/Language/Spelling

#4971 MQTT JSON docs - esphomelib now supports ESP8266
  source/_components/light.mqtt_json.markdown
Labels: Enhancement

#4955 Add language parameter to darksky sensor.
  source/_components/sensor.darksky.markdown
Labels: New-feature

#4992 Changes to Hassbian documentation
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/installation/hassbian/common-tasks.markdown
  source/_docs/installation/hassbian/customization.markdown
  source/_docs/installation/hassbian/installation.markdown
  source/_docs/installation/hassbian/upgrading.markdown
Labels: Enhancement

#4993 automations file has fixed name and location
  source/_docs/automation/editor.markdown
Labels: Fix/Formatting/Language/Spelling

#4991 Add example configuration from Gummientchen to cookbook
  source/_cookbook/configuration_yaml_by_gummientchen.markdown
Labels: Enhancement

#4968 Update sensor.mqtt.markdown
  source/_components/sensor.mqtt.markdown
Labels: Enhancement

#4969 Update switch.mqtt.markdown
  source/_components/switch.mqtt.markdown
Labels: Enhancement

#4994 More changes to Hassbian documentation.
  source/_docs/installation/hassbian.markdown
  source/_docs/installation/hassbian/common-tasks.markdown
  source/_docs/installation/updating.markdown
Labels: Fix/Formatting/Language/Spelling

#4995 Fix incorrect syntax
  source/_docs/scripts.markdown
Labels: Fix/Formatting/Language/Spelling

#4996 Add send_sticker and update the existing content
  source/_components/telegram_bot.markdown
Labels: New-feature

#4945 Fix code for custom UI version
  source/developers/frontend_creating_custom_ui.markdown
Labels: New-feature

#4943 Update list of sensors for Android IP Webcam
  source/_components/android_ip_webcam.markdown
Labels: Enhancement

#4922 Fix default values in REST switch
  source/_components/switch.rest.markdown
Labels: Enhancement, Fix/Formatting/Language/Spelling

#4883 Improves documentation with better example and link to algorithm
  source/_components/sensor.filter.markdown
Labels: Enhancement

#4965 Xiaomi Mijia LED Desk Lamp added to the list of supported yeelights
  source/_components/light.yeelight.markdown
Labels: Enhancement

#4987 Reworded for Rename Node
  source/_docs/z-wave/control-panel.markdown
Labels: Enhancement

#4986 Update sensor.vasttrafik.markdown
  source/_components/sensor.vasttrafik.markdown
Labels: New-feature

#4989 Update snips.markdown for HassIO addon
  source/_addons/snips.markdown
Labels: Enhancement

#4976 Update default Pilight port number
  source/_components/pilight.markdown
Labels: Fix/Formatting/Language/Spelling

#5003 Fixed invalid YAML example
  source/_components/sensor.nederlandse_spoorwegen.markdown
Labels: Fix/Formatting/Language/Spelling

#5001 Rewording, adding links
  source/getting-started/presence-detection.markdown
Labels: Enhancement

#5004 light.group: Added example for usage in scripts.
  source/_components/light.group.markdown
Labels: Enhancement

#4947 bmw connected drive
  source/_components/bmw_connected_drive.markdown
Labels: New-feature

#5008 Homekit: Added dependency note warning
  source/_components/homekit.markdown
Labels: Enhancement

#4829 Xiaomi MiIO Fan: Xiaomi Air Humidifier integration
  source/_components/fan.xiaomi_miio.markdown
Labels: New-feature

#5000 nginx_proxy: Document hsts config variable
  source/_addons/nginx_proxy.markdown
Labels: New-feature

#5017 Clarity updates
  source/_docs/configuration.markdown
Labels: Enhancement

#5015 Highlighting the hosting of files
  source/_components/http.markdown
Labels: Enhancement

#5022 Improve documentation about Mediaroom
  source/_components/media_player.mediaroom.markdown
Labels: Enhancement

#5024 Added another implementation of MQTT JSON Lights: AiLight
  source/_components/light.mqtt_json.markdown
Labels: Enhancement

#4964 Yeelight power mode service
  source/_components/light.yeelight.markdown
Labels: New-feature

#4981 Template function state_attr to get attribute from a state
  source/_docs/configuration/templating.markdown
Labels: New-feature

#5038 Make edit links GitHub aware
  plugins/environment_variables.rb
  source/_includes/edit_github.html
Labels: Enhancement

#5039 Add details for values if the user should replace it (fixes #4999)
  source/developers/documentation/standards.markdown
Labels: Enhancement

#5025 Add details for reporting issues
  source/help/index.markdown
  source/help/reporting_issues.markdown
Labels: Enhancement

#5043 Fixed minor typo in the description of 'max'.
  source/_docs/configuration/templating.markdown
Labels: Fix/Formatting/Language/Spelling

#5021 clarify default db_url
  source/_components/sensor.sql.md
Labels: Enhancement

#5030 Added note about venv upgrade
  source/_docs/installation/virtualenv.markdown
Labels: Enhancement

#5027 Add instructions on running MQTT ssl/nonssl simultaneously
  source/_addons/mosquitto.markdown
Labels: Enhancement

#5032 sensor.command_line: Round example CPU temperature value
  source/_components/sensor.command_line.markdown
Labels: Fix/Formatting/Language/Spelling

#5031 Spelling and grammar fixes
  source/_addons/nginx_proxy.markdown
  source/_addons/samba.markdown
  source/_components/binary_sensor.hikvision.markdown
  source/_components/foursquare.markdown
  source/_components/frontend.markdown
  source/_components/google_assistant.markdown
  source/_components/image_processing.dlib_face_identify.markdown
  source/_components/knx.markdown
  source/_components/media_player.firetv.markdown
  source/_components/melissa.markdown
  source/_components/notify.gntp.markdown
  source/_components/sensor.rest.markdown
  source/_components/switch.fritzdect.markdown
  source/_components/switch.kankun.markdown
  source/_components/tellstick.markdown
  source/_cookbook/custom_panel_using_react.markdown
  source/_docs/installation/docker.markdown
  source/_posts/2018-03-24-new-release-schedule.markdown
Labels: Fix/Formatting/Language/Spelling

#5036 Fixing service name pt2
  source/_components/media_player.markdown
Labels: Fix/Formatting/Language/Spelling

#5042 Fix ON/OFF being interpreted in binary_sensor.mqtt
  source/_components/binary_sensor.mqtt.markdown
Labels: Fix/Formatting/Language/Spelling

#5040 Update style and fix formatting
  source/_components/calendar.google.markdown
Labels: Fix/Formatting/Language/Spelling

#5026 deCONZ debug information
  source/_components/deconz.markdown
Labels: Enhancement

#5041 Update configuration samples
  source/_components/amcrest.markdown
  source/_components/arlo.markdown
  source/_components/august.markdown
  source/_components/camera.foscam.markdown
  source/_components/camera.synology.markdown
  source/_components/canary.markdown
  source/_components/cover.garadget.markdown
  source/_components/cover.myq.markdown
  source/_components/device_tracker.huawei_router.markdown
  source/_components/device_tracker.trackr.markdown
  source/_components/doorbird.markdown
  source/_components/dyson.markdown
  source/_components/eight_sleep.markdown
  source/_components/goalfeed.markdown
  source/_components/light.avion.markdown
  source/_components/light.decora_wifi.markdown
  source/_components/lock.nello.markdown
  source/_components/lock.sesame.markdown
  source/_components/lutron.markdown
  source/_components/media_player.cmus.markdown
  source/_components/media_player.ue_smart_radio.markdown
  source/_components/melissa.markdown
  source/_components/mercedesme.markdown
  source/_components/mqtt_eventstream.markdown
  source/_components/mqtt_statestream.markdown
  source/_components/mychevy.markdown
  source/_components/neato.markdown
  source/_components/notify.matrix.markdown
  source/_components/notify.rocketchat.markdown
  source/_components/nuheat.markdown
  source/_components/rainbird.markdown
  source/_components/raincloud.markdown
  source/_components/ring.markdown
  source/_components/sensor.hp_ilo.markdown
  source/_components/sensor.imap.markdown
  source/_components/sensor.mfi.markdown
  source/_components/sensor.mopar.markdown
  source/_components/sensor.random.markdown
  source/_components/sensor.sma.markdown
  source/_components/sensor.synologydsm.markdown
  source/_components/shiftr.markdown
  source/_components/skybell.markdown
  source/_components/sleepiq.markdown
  source/_components/switch.hook.markdown
  source/_components/switch.mfi.markdown
  source/_components/switch.rainmachine.markdown
  source/_components/tesla.markdown
  source/_components/volvooncall.markdown
  source/_components/waterfurnace.markdown
  source/_components/zoneminder.markdown
Labels: Fix/Formatting/Language/Spelling

#5052 Arlo Q not supported
  source/_components/sensor.arlo.markdown
Labels: Enhancement
