Repository home-assistant/home-assistant.io, pull requests merged in 2018-12, with the labels that each got.

#7693 Update tibber.markdown
  source/_components/tibber.markdown
Labels: ready-for-review

#7699 Added new filters for templates
  source/_docs/configuration/templating.markdown
Labels: ready-for-review

#7700 Update sensor.nederlandse_spoorwegen.markdown to fix typo
  source/_components/sensor.nederlandse_spoorwegen.markdown
Labels: to-do

#7697 Aqara Gateway is not supported
  source/_components/xiaomi_aqara.markdown
Labels: to-do

#7690 Updated Markdown to include SSL support in NVC camera plugin
  source/_components/camera.uvc.markdown
Labels: ready-for-review

#7683 Update to reflect new Modes trait.
  source/_components/google_assistant.markdown
Labels: to-do

#7701 Making owntracks breaking change clearer
  source/_posts/2018-11-28-release-83.markdown
Labels: ready-for-review

#7708 Add missing code block backtick
  source/_components/cloud.markdown
Labels: to-do

#7706 add fibaro to the list of supported hubs
  source/_docs/z-wave/controllers.markdown
Labels: to-do

#7705 Fixed off typo in alert documentation
  source/_components/alert.markdown
Labels: to-do

#7724 [your user] to YOUR_USER
  source/_docs/autostart/systemd.markdown
Labels: to-do

#7250 New component hlk_sw16 relay module
  source/_components/hlk_sw16.markdown
  source/_components/switch.hlk_sw16.markdown
  source/images/supported_brands/hlktech.jpg
Labels: Hacktoberfest, has-parent, new-component, next, ready-for-review

#7718 Align example with documentation by using dark sky in both locations
  source/_lovelace/weather-forecast.markdown
Labels: to-do

#7727 Add 'Device Tracker' to Tado device tracker title
  source/_components/device_tracker.tado.markdown
Labels: to-do

#7725 Fixed some typos in sensor.launch_library.markdown
  source/_components/sensor.launch_library.markdown
Labels: to-do

#7716 Add name template example
  source/_components/alert.markdown
Labels: to-do

#7730 "zone:" option is missing
  source/_components/proximity.markdown
Labels: to-do

#7726 Added command to run on docker for windows.
  source/_docs/installation/docker.markdown
Labels: to-do

#6652 Update docs for new state restore without recorder
  source/_components/counter.markdown
  source/_components/input_boolean.markdown
  source/_components/input_datetime.markdown
  source/_components/input_number.markdown
  source/_components/input_select.markdown
  source/_components/input_text.markdown
  source/_components/recorder.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next, parent-merged

#7419 Add the service `lock.open` to the docs
  source/_components/lock.markdown
Labels: current, enhancement, ready-for-review

#7451 Change parameter from token to webhook
  source/_components/camera.push.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#7460 Converted HTML5 Push Notifications JSON examples to YAML
  source/_components/notify.html5.markdown
Labels: current, enhancement, ready-for-review

#7395 Update lovelace ID status + include and secret support
  source/lovelace/index.markdown
  source/lovelace/tips.markdown
Labels: current, has-parent, parent-merged, ready-for-review

#7497 Add sensors
  source/_components/waterfurnace.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#7649 Update evohome, honeywell markdown with latest changes
  source/_components/climate.evohome.markdown
  source/_components/climate.honeywell.markdown
  source/_components/evohome.markdown
Labels: has-parent, new-feature, next, parent-merged

#7491 Extended documentation for proxy camera to include PR 18431
  source/_components/camera.proxy.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#7302 Ihc with two controllers
  source/_components/binary_sensor.ihc.markdown
  source/_components/ihc.markdown
  source/_components/light.ihc.markdown
  source/_components/sensor.ihc.markdown
  source/_components/switch.ihc.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged, ready-for-review

#7585 Cleanup descriptions for template sensor/binary_sensor
  source/_components/binary_sensor.template.markdown
  source/_components/sensor.template.markdown
Labels: current, enhancement, has-parent, parent-merged, ready-for-review

#7737 Note about long-press on light card
  source/_lovelace/light.markdown
Labels: ready-for-review

#7688 Internal DNS notes
  source/_components/tts.markdown
Labels: current, enhancement

#7703 Device impersination
  source/_components/hangouts.markdown
Labels: current, enhancement

#7733 capital letters in booleans
  source/_components/device_tracker.markdown
Labels: current, enhancement

#7719 Add config options
  source/_lovelace/picture-entity.markdown
Labels: has-parent, new-feature, next, ready-for-review

#7710 Remove unsupported strong mode of the Xiaomi Air Humidifier CA1
  source/_components/fan.xiaomi_miio.markdown
Labels: awaits-parent, has-parent, new-feature, next

#7749 Remove Instapush docs
  source/_components/notify.instapush.markdown
  source/images/supported_brands/instapush.png
Labels: ready-for-review

#7748 Fix issue with proximity configuration
  source/_components/proximity.markdown
Labels: ready-for-review

#7744 drop unit parameter from waterfurnace docs
  source/_components/waterfurnace.markdown
Labels: ready-for-review

#7741 Add pulse effect mode descriptions
  source/_components/lifx.markdown
Labels: to-do

#7745 update mychevy component docs
  source/_components/mychevy.markdown
Labels: ready-for-review

#7738 Update zha.markdown to clearify use of zigpy and support for multiple…
  source/_components/zha.markdown
Labels: ready-for-review

#7720 Added explanation to docker command config
  source/_docs/installation/docker.markdown
Labels: ready-for-review

#7704 Making instructions a little more precise
  source/getting-started/configuration.markdown
Labels: ready-for-review

#7758 Update notify.html5 example
  source/_components/notify.html5.markdown
Labels: to-do

#7761 Update binary_sensor.mqtt.markdown
  source/_components/binary_sensor.mqtt.markdown
Labels: ready-for-review

#7766 edited to follow documentation standards
  source/_docs/installation/docker.markdown
Labels: to-do

#7760 Support next generation of the Xiaomi Mi Smart Plug
  source/_components/switch.xiaomi_miio.markdown
Labels: ready-for-review

#7589 Add Philips Moonlight Bedside Lamp support
  source/_components/light.xiaomi_miio.markdown
Labels: awaits-parent, has-parent, new-feature, next

#7774 Fedora improvements
  source/_docs/installation/fedora.markdown
Labels: to-do

#7776 Add code optional parameter on iAlarm
  source/_components/alarm_control_panel.ialarm.markdown
Labels: to-do

#7777 Fix example for the Gauge card
  source/_lovelace/gauge.markdown
Labels: to-do

#7784 updated the examples to be usable with appdaemon 3.0
  source/_docs/ecosystem/appdaemon.markdown
Labels: to-do

#7791 Update Lovelace docs
  source/_includes/asides/lovelace_navigation.html
  source/lovelace/how-it-works.markdown
  source/lovelace/index.markdown
  source/lovelace/tips.markdown
  source/lovelace/yaml-mode.markdown
Labels: ready-for-review

#7750 Update documentation for HomeMatic
  source/_components/homematic.markdown
Labels: ready-for-review

#7794 Add password caveat to 17track.net docs
  source/_components/sensor.seventeentrack.markdown
Labels: ready-for-review

#7797 Lovelace view update ID -> Path
  source/lovelace/views.markdown
Labels: ready-for-review

#7796 Update yaml-mode.markdown
  source/lovelace/yaml-mode.markdown
Labels: ready-for-review

#7513 Alarmdecoder doc updates for new zone loop parameter
  source/_components/alarmdecoder.markdown
Labels: awaits-parent, has-parent, new-feature, next

#7800 Update device_tracker.markdown
  source/_components/device_tracker.markdown
Labels: to-do

#7799 Removed the venv link from the sidebar
  source/_includes/asides/docs_navigation.html
Labels: ready-for-review

#7792 Update device_tracker.googlehome.markdown
  source/_components/device_tracker.googlehome.markdown
Labels: ready-for-review

#7798 Lovelace: Remove ID from card
  source/lovelace/yaml-mode.markdown
Labels: ready-for-review

#7752 Upcoming 0.84 LL changelog and cleanup
  source/lovelace/changelog.markdown
Labels: in-progress, ready-for-review

#7751 Update tap/hold actions to objects
  source/_lovelace/entity-button.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
  source/_lovelace/picture.markdown
Labels: ready-for-review

#7600 Add documentation for Lightwave lights and switches
  source/_components/light.lightwave.markdown
  source/_components/lightwave.markdown
  source/_components/switch.lightwave.markdown
  source/images/supported_brands/lightwave.png
Labels: has-parent, in-progress, new-component, next, parent-merged

#7807 Update switch.tplink.markdown - Typo fix on template
  source/_components/switch.tplink.markdown
Labels: to-do

#7809 radiotherm: Update supported models
  source/_components/climate.radiotherm.markdown
Labels: to-do

#7810 Add KS8500 to supported SamsungTV models
  source/_components/media_player.samsungtv.markdown
Labels: to-do

#7812 Update changelog.markdown
  source/lovelace/changelog.markdown
Labels: ready-for-review

#7813 Update matrix.markdown
  source/_components/matrix.markdown
Labels: ready-for-review

#7818 Update 0.84 release notes
  source/_posts/2018-12-12-release-84.markdown
Labels: to-do

#7820 Update the LL changelog link
  source/_posts/2018-12-12-release-84.markdown
Labels: ready-for-review

#7819 Revert "Update 0.84 release notes (#7818)"
  source/_posts/2018-12-12-release-84.markdown
Labels: ready-for-review

#7811 Likely copy/paste error
  source/_components/light.mqtt.markdown
Labels: to-do

#7581 Documentation for the Harman Kardon media player
  source/_components/media_player.harman_kardon_avr.markdown
  source/images/supported_brands/harman_kardon.png
Labels: has-parent, new-component, next, ready-for-review

#7831 note about `!include` and `!secret` for storage
  source/_posts/2018-12-12-release-84.markdown
Labels: ready-for-review

#7721 Add documentation for multiple RainMachine controllers
  source/_components/rainmachine.markdown
Labels: has-parent, new-feature, next, ready-for-review

#7834 Update sensor.markdown
  source/_lovelace/sensor.markdown
Labels: ready-for-review

#7835 Update picture-elements.markdown
  source/_lovelace/picture-elements.markdown
Labels: to-do

#7772 Update light.markdown - Clarify that `brigthness` controls the light's brigthness
  source/_components/light.markdown
Labels: ready-for-review

#7836 Update picture.markdown
  source/_lovelace/picture.markdown
Labels: to-do

#7795 Upgrade Jekyll
  Gemfile
  Gemfile.lock
  sass/custom/_syntax.scss
Labels: ready-for-review

#7840 Add note about entity_namespace deprecation
  source/_docs/configuration/platform_options.markdown
Labels: ready-for-review

#7622 Add docs for NMBS sensor
  source/_components/sensor.nmbs.markdown
  source/images/supported_brands/sncb_nmbs.gif
Labels: has-parent, new-component, next, ready-for-review

#7841 Fix installation requirements
  source/_components/mychevy.markdown
Labels: to-do

#7830 Fix example config
  source/_lovelace/gauge.markdown
Labels: to-do

#7839 Clarification on base_url format
  source/_components/http.markdown
Labels: ready-for-review

#7845 Update light.mqtt.markdown
  source/_components/light.mqtt.markdown
Labels: ready-for-review

#7853 Fixing the numeric state examples
  source/_docs/scripts/conditions.markdown
Labels: ready-for-review

#7854 Fix w800rf32.png 404 error
  source/images/supported_brands/w800rf32.png
Labels: to-do

#7855 Move switch.linode.markdown
  source/_components/switch.linode.markdown
Labels: to-do

#7808 Update ZHA docs for quirks mode flag
  source/_components/zha.markdown
Labels: parent-merged, ready-for-review

#7645 Add Air Pollutants docs
  source/_components/air_pollutants.markdown
  source/_components/demo.markdown
Labels: awaits-parent, has-parent, new-feature, next

#7870 Grammar fixes: google_assistant.markdown
  source/_components/google_assistant.markdown
Labels: to-do

#7869 Update switch.fritzdect.markdown
  source/_components/switch.fritzdect.markdown
Labels: to-do

#7731 Add docs for Brottsplatskartan sensor
  source/_components/sensor.brottsplatskartan.markdown
  source/images/supported_brands/brottsplatskartan.png
Labels: to-do

#7874 Add note for purge service to explain behaviour
  source/_components/recorder.markdown
Labels: to-do

#7858 Fix Liquid Warning for climate.evohome.markdown
  source/_components/climate.evohome.markdown
Labels: to-do

#7878 Improper English
  source/_components/google_assistant.markdown
Labels: to-do

#7883 Update installation.markdown
  source/_docs/z-wave/installation.markdown
Labels: to-do

#7851 Update sensor.mqtt.markdown for JSON attributes topic
  source/_components/sensor.mqtt.markdown
Labels: ready-for-review

#7886 :warning: breaking change on views id -> path
  source/lovelace/changelog.markdown
Labels: ready-for-review

#7888 Lazy image load logo
  source/components/index.html
Labels: ready-for-review

#7785 Updated information about outputs support.
  source/_components/satel_integra.markdown
Labels: to-do

#7849 Document new skybell camera options
  source/_components/camera.skybell.markdown
Labels: to-do

#7504 Added GTT Sensor documentation
  source/_components/sensor.gtt.markdown
  source/images/supported_brands/gtt.png
Labels: has-parent, new-component, next, ready-for-review

#7890 Fix example
  source/_lovelace/entity-button.markdown
Labels: ready-for-review

#7892 Update tts.markdown
  source/_components/tts.markdown
Labels: to-do

#7843 Add prezzibenzina documentation
  source/_components/sensor.prezzibenzina.markdown
  source/images/supported_brands/prezzibenzina.png
Labels: ready-for-review

#7896 Clarify `sensor_data` change for tap/hold actions
  source/lovelace/changelog.markdown
Labels: ready-for-review

#7898 Keep getting questions about this
  source/lovelace/yaml-mode.markdown
Labels: ready-for-review

#7899 Updated docs of climate.knx
  source/_components/climate.knx.markdown
Labels: to-do

#7837 Add verify_ssl configuration to camera.mjpeg
  source/_components/camera.mjpeg.markdown
Labels: to-do

#7904 Fix typo in configuration.markdown
  source/getting-started/configuration.markdown
Labels: to-do

#7903 Include missing default values
  source/_components/camera.onvif.markdown
Labels: to-do

#7905 Catchup
  source/_docs/configuration/events.markdown
Labels: ready-for-review

#7900 Update Radius
  source/_components/geo_location.usgs_earthquakes_feed.markdown
Labels: to-do

#7902 More accurate description of component
  source/_components/media_player.plex.markdown
Labels: to-do

#7860 Update light.mqtt.markdown - Document white_value_scale
  source/_components/light.mqtt.markdown
Labels: ready-for-review

#7847 iFrame card -> Iframe card
  source/_lovelace/iframe.markdown
Labels: to-do

#7848 Adds battery_percent to sensor.netatmo.markdown
  source/_components/sensor.netatmo.markdown
Labels: to-do

#7909 Add cookbook configuration example by renemarc
  source/_cookbook/configuration_yaml_by_renemarc.markdown
Labels: to-do

#7881 Added more details for attributes
  source/_components/sensor.dwd_weather_warnings.markdown
Labels: to-do

#7913 Fix IHC config schema
  source/_components/binary_sensor.ihc.markdown
  source/_components/light.ihc.markdown
  source/_components/sensor.ihc.markdown
  source/_components/switch.ihc.markdown
Labels: to-do

#7912 Add Zigbee2mqtt to list of software that supports MQTT discovery.
  source/_docs/mqtt/discovery.markdown
Labels: to-do

#7916 Clarify device description
  source/_components/media_player.dlna_dmr.markdown
Labels: to-do

#7918 Correct tap/hold action options and default
  source/_lovelace/picture.markdown
Labels: ready-for-review

#7921 Fixed example of how to add secrets
  source/_docs/tools/credstash.markdown
Labels: to-do

#7924 Add deprecation warning.
  source/_components/sensor.ruter.markdown
Labels: ready-for-review

#7917 Add sunset and sunrise
  source/_components/sensor.darksky.markdown
Labels: ready-for-review

#7927 Add documentation for Aqara Wireless Switch (Single) (2nd gen)
  source/_components/binary_sensor.xiaomi_aqara.markdown
Labels: to-do

#7915 Add Path to Tautulli documentation
  source/_components/sensor.tautulli.markdown
Labels: to-do

#7928 Update homematic.markdown
  source/_components/homematic.markdown
Labels: ready-for-review

#7783 Add docs for islamic_prayer_times sensor platform
  source/_components/sensor.islamic_prayer_times.markdown
Labels: to-do

#7931 Discovery is not supported for Octoprint
  source/_components/discovery.markdown
Labels: to-do

#7929 Update sensor.twitch.markdown
  source/_components/sensor.twitch.markdown
Labels: to-do

#7930 zha.permit clarification
  source/_components/zha.markdown
Labels: to-do

#7938 Update homematic.markdown
  source/_components/homematic.markdown
Labels: ready-for-review

#7933 Update iPhone app version
  source/_components/vacuum.xiaomi_miio.markdown
Labels: to-do

#7943 Update MJPEG docs to include Blue Iris integration
  source/_components/camera.mjpeg.markdown
Labels: ready-for-review

#7944 Update light.mqtt.markdown
  source/_components/light.mqtt.markdown
Labels: to-do

#7941 Add HA configuration when using NGINX
  source/_docs/ecosystem/nginx.markdown
Labels: to-do

#7560 Add device_id to device_tracker.bluetooth configuration
  source/_components/device_tracker.bluetooth_tracker.markdown
Labels: has-parent, new-feature, next, ready-for-review

#7946 Update fritzbox.markdown
  source/_components/fritzbox.markdown
Labels: bug, current

#7619 Revert "MyTotalConnectComfort.com Compatibility (#5771)"
  source/_components/climate.honeywell.markdown
Labels: current, enhancement, ready-for-review

#7932 Updated entur platform with line_whitelist and faq
  source/_components/sensor.entur_public_transport.markdown
Labels: to-do

#7950 Spelling
  source/_components/lifx.markdown
Labels: current, spelling

#7948 Reverts #7945
  source/hassio/installation.markdown
Labels: bug, current, ready-for-review

#7678 Clarify install of docker
  source/hassio/installation.markdown
Labels: current, enhancement, ready-for-review

#7951 Improves Docker-CE wording.
  source/hassio/installation.markdown
Labels: current, enhancement, ready-for-review

#7949 Add documentation for Aqara Wireless Switch (Double) (2nd gen)
  source/_components/binary_sensor.xiaomi_aqara.markdown
Labels: awaits-parent, has-parent, new-feature, next
