Repository home-assistant/home-assistant.io, pull requests merged in 2018-06, with the labels that each got.

#5450 Add support for outlets in HomeKit
  source/_components/homekit.markdown
Labels: New-feature

#5473 Fixed incorrect description in sensor list
  source/_components/spaceapi.markdown
Labels: Fix/Formatting/Language/Spelling

#5472 Add rfkill details (fixes #5471)
  source/_docs/installation/hassbian.markdown
  source/_docs/installation/hassbian/installation.markdown
Labels: Enhancement

#5476 Password Quotes and and correct button names
  source/getting-started/configuration.markdown
Labels: Enhancement

#5478 Adding FAQ about tabs
  source/_faq/character_t.markdown
Labels: Enhancement

#5480 Update layout
  source/_components/sensor.simulated.markdown
Labels: Fix/Formatting/Language/Spelling

#5481 Fix MyQ doc typo
  source/_components/cover.myq.markdown
Labels: Fix/Formatting/Language/Spelling

#5488 Update Zabbix Typeo
  source/_components/sensor.zabbix.markdown
Labels: Fix/Formatting/Language/Spelling

#5490 Added instructions for Fibaro Keyfob FGKF-601
  source/_docs/z-wave/device-specific.markdown
Labels: Enhancement

#5489 Adding warning about backups
  source/getting-started/index.markdown
Labels: Enhancement

#5492 Add new condition and update style for pi-hole
  source/_components/sensor.pi_hole.markdown
Labels: New-feature

#5498 Update Ph logo
  source/_components/sensor.pi_hole.markdown
  source/images/supported_brands/pi_hole.png
Labels: Enhancement

#5503 Unifi video component: Improved documentation
  source/_components/camera.uvc.markdown
Labels: Enhancement

#5264 Add LW-12 documentation
  source/_components/light.lw12wifi.markdown
  source/images/supported_brands/lagute.png
Labels: New-component/platform

#5443 Add device_descriptor and device_name to keyboard event
  source/_components/keyboard_remote.markdown
Labels: New-feature

#5516 Fix MTA link
  source/_components/sensor.gtfs.markdown
Labels: Fix/Formatting/Language/Spelling

#5511 Update sensor.mitemp_bt.markdown
  source/_components/sensor.mitemp_bt.markdown
Labels: Enhancement

#5510 Added daily and hourly modes to OpenWeatherMap
  source/_components/weather.openweathermap.markdown
Labels: New-feature

#5513 Required / recommended generic Linux packages
  source/hassio/installation.markdown
Labels: Enhancement

#5526 Missing a bracket in one of the examples
  source/_docs/automation/trigger.markdown
Labels: Fix/Formatting/Language/Spelling

#5523 Fixed broken link in weather.markdown
  source/_components/weather.markdown
Labels: Fix/Formatting/Language/Spelling

#5522 Tested JS8005
  source/_components/media_player.samsungtv.markdown
Labels: Enhancement

#5528 Add more details for the setup
  source/_components/sensor.netdata.markdown
  source/images/components/netdata/details.png
Labels: Enhancement

#5537 Correct cache_value
  source/_components/sensor.mitemp_bt.markdown
Labels: Fix/Formatting/Language/Spelling

#5005 Documentation for Epson projector support in HA
  source/_components/media_player.epson.markdown
  source/images/supported_brands/epson.png
Labels: New-component/platform

#5531 Update image_processing.facebox.markdown
  source/_components/image_processing.facebox.markdown
Labels: Enhancement

#5539 HASS.io image changed...
  source/hassio/installation.markdown
Labels: Fix/Formatting/Language/Spelling

#5536 Update climate.modbus.markdown
  source/_components/climate.modbus.markdown
Labels: Fix/Formatting/Language/Spelling

#5542 Add section on Mosquitto ACLs
  source/_addons/mosquitto.markdown
Labels: Enhancement

#5477 NSW Fuel Station Price Sensor
  source/_components/sensor.nsw_fuel_station.markdown
Labels: New-component/platform

#5461 Add entity support to Waze Travel Time
  source/_components/sensor.waze_travel_time.markdown
Labels: New-feature

#5554 Fix minor grammar mistake
  source/getting-started/configuration.markdown
Labels: Fix/Formatting/Language/Spelling

#5552 Promoting timezone issue to warning
  source/_components/alert.markdown
Labels: Fix/Formatting/Language/Spelling

#5534 Add documentation updates for upcoming AirVisual changes.
  source/_components/sensor.airvisual.markdown
Labels: Enhancement

#5514 Added notification example
  source/_components/sensor.opensky.markdown
Labels: Enhancement

#5556 Limit the default to one sensor
  source/_components/sensor.pi_hole.markdown
Labels: Fix/Formatting/Language/Spelling

#5035 Wireless tags platform
  source/_components/binary_sensor.wirelesstag.markdown
  source/_components/sensor.wirelesstag.markdown
  source/_components/switch.wirelesstag.markdown
  source/_components/wirelesstag.markdown
  source/images/supported_brands/wirelesstag.png
Labels: New-component/platform

#5465 Added weather.IPMA
  source/_components/weather.ipma.markdown
  source/images/supported_brands/ipma.png
Labels: New-component/platform, Ready for review

#5563 Current
  source/_components/binary_sensor.mychevy.markdown
  source/_components/sensor.mychevy.markdown
Labels: Fix/Formatting/Language/Spelling

#5560 Fix spelling mistake
  source/_docs/installation/hassbian/installation.markdown
Labels: Fix/Formatting/Language/Spelling

#5559 Fixes capatalization of Home Assistant.
  source/_components/matrix.markdown
Labels: Fix/Formatting/Language/Spelling

#5565 Simple typo correction for spelling
  source/_components/vacuum.roomba.markdown
Labels: Fix/Formatting/Language/Spelling

#5561 Fix filename of netgear_lte logo
  source/_components/netgear_lte.markdown
  source/_components/sensor.netgear_lte.markdown
Labels: Fix/Formatting/Language/Spelling

#5568 Add redirect
  source/_components/sensor.loopenergy.markdown
Labels: Fix/Formatting/Language/Spelling

#5569 Fix typos and style
  source/_docs/asterisk_mbox.markdown
Labels: Fix/Formatting/Language/Spelling

#5558 Updated the templates
  source/_docs/z-wave/entities.markdown
Labels: Enhancement

#5579 MAC Address only works when both quoted and separated with hythens
  source/_components/media_player.webostv.markdown
Labels: Fix/Formatting/Language/Spelling

#5100 Add documentation for the new watson_iot component
  source/_components/watson_iot.markdown
  source/images/supported_brands/ibm.png
Labels: New-component/platform

#5455 Update documentation for MQTT climate device
  source/_components/climate.mqtt.markdown
Labels: New-feature

#5460 Add set_default_level documentation
  source/_components/logger.markdown
Labels: Enhancement, New-feature

#5381 Add documentation for KIWI.KI smartlock
  source/_components/lock.kiwi.markdown
  source/images/supported_brands/kiwi.png
Labels: New-component/platform

#5290 Added Documentation for Xiaomi Cameras
  source/_components/camera.xiaofang.markdown
Labels: New-component/platform

#5587 Explain PostNL sensor value
  source/_components/sensor.postnl.markdown
Labels: Enhancement

#5562 Update light.limitlessled.markdown
  source/_components/light.limitlessled.markdown
Labels: Enhancement

#5580 Removing dead video link
  source/_components/snips.markdown
Labels: Fix/Formatting/Language/Spelling

#5596 Update Restore State language
  source/_components/input_datetime.markdown
Labels: Fix/Formatting/Language/Spelling

#5597 Update Restore State language
  source/_components/input_boolean.markdown
Labels: Fix/Formatting/Language/Spelling

#5595 Update Restore State language
  source/_components/input_number.markdown
Labels: Fix/Formatting/Language/Spelling

#5594 Update Restore State language
  source/_components/input_select.markdown
Labels: Fix/Formatting/Language/Spelling

#5593 Update Restore State language
  source/_components/input_text.markdown
Labels: Fix/Formatting/Language/Spelling

#5592 Reflect limitlessled.com being down in documentation
  source/_components/light.limitlessled.markdown
Labels: Enhancement, Fix/Formatting/Language/Spelling

#5575 Updated docs for Homekit controller climate
  source/_components/climate.homekit_controller.markdown
  source/_components/homekit_controller.markdown
Labels: New-feature

#5600 Fix typo
  source/_components/sonos.markdown
Labels: Fix/Formatting/Language/Spelling

#5588 Skip nest security state sensor if no Nest Cam exists
  source/_components/sensor.nest.markdown
Labels: New-feature

#5532 Update sensor.miflora.markdown
  source/_components/sensor.miflora.markdown
Labels: Enhancement

#5581 Add JSON port to Homematic interface configuration
  source/_components/homematic.markdown
Labels: New-feature

#5602 Fix incorrect path in Group Visibility example
  source/_docs/configuration/group_visibility.markdown
Labels: Fix/Formatting/Language/Spelling

#5362 Update media_player.samsungtv.markdown
  source/_components/media_player.samsungtv.markdown
Labels: New-feature

#5566 Extend documentation with ssl_peer_certificate option
  source/_components/http.markdown
Labels: New-feature

#5470 Add white mode for Flux LED
  source/_components/light.flux_led.markdown
Labels: Enhancement, New-feature

#5463 Include Weather Underground
  source/_docs/configuration/entity-registry.markdown
Labels: Enhancement

#5615 Update sensor.rest.markdown
  source/_components/sensor.rest.markdown
Labels: Fix/Formatting/Language/Spelling

#5617 Clarify potential security issues; use safer example config
  source/_components/http.markdown
Labels: Enhancement

#5618 Document X-Forwarded-For behavior changes
  source/_components/http.markdown
Labels: enhancement, has-parent, next, ready-for-review

#5152 Add information for the namespace option
  source/_components/prometheus.markdown
Labels: New-feature, has-parent, next, ready-for-review

#5612 Adding details on activating the venv
  source/_docs/installation/raspberry-pi.markdown
Labels: current, enhancement, ready-for-review

#5611 Adding details on activating the venv
  source/_docs/installation/hassbian.markdown
Labels: current, enhancement, ready-for-review

#5309 Additional troubleshooting step to fix PIN error
  source/_components/homekit.markdown
Labels: current, enhancement, in-progress

#5605 UVC updated configuration example
  source/_components/camera.uvc.markdown
Labels: current, enhancement, in-progress

#5384 According to the matrix documentation the `name` field is required.
  source/_components/matrix.markdown
Labels: current, enhancement, ready-for-review

#5413 Update light.deconz.markdown
  source/_components/light.deconz.markdown
Labels: current, in-progress

#5622 Inovelli Wall Switches
  source/_docs/z-wave/device-specific.markdown
Labels: current, enhancement, in-progress

#5609 Versions updated and note on GATE-02 integration added
  source/_components/egardia.markdown
Labels: current, enhancement, ready-for-review

#5388 Add support to ignore a specific Xiaomi gateway
  source/_components/xiaomi_aqara.markdown
Labels: New-feature, current, has-parent, ready-for-review

#5631 Added details about emulated_hue_hidden
  source/_docs/configuration/customizing-devices.markdown
Labels: current, enhancement, ready-for-review

#5629 Add note about syncing devices
  source/cloud/google_assistant.markdown
Labels: current, enhancement, ready-for-review

#5466 Wether Underground clarification
  source/_components/sensor.wunderground.markdown
Labels: current, enhancement, ready-for-review

#5625 Added Smart Meter
  source/_components/sensor.dsmr.markdown
Labels: current, enhancement, ready-for-review

#5624 Document the new http.trusted_proxies setting
  source/_components/http.markdown
Labels: New-feature, has-parent, next, ready-for-review

#5623 new NUT sensor 'output' variables
  source/_components/sensor.nut.markdown
Labels: New-feature, has-parent, in-progress, next

#5635 Update Hikvision camera list
  source/_components/binary_sensor.hikvision.markdown
Labels: current, enhancement, ready-for-review
