Repository home-assistant/home-assistant.io, pull requests merged in 2018-08, with the labels that each got.

#5937 Documentation for deCONZ switch platform
  source/_components/switch.deconz.markdown
Labels: ready-for-review

#5549 Add RitAssist support page
  source/_components/device_tracker.ritassist.markdown
  source/images/supported_brands/ritassist.png
Labels: awaits-parent, has-parent, new-component, next

#5940 Adds docs for OpenUV
  source/_components/binary_sensor.openuv.markdown
  source/_components/openuv.markdown
  source/_components/sensor.openuv.markdown
  source/images/supported_brands/openuv.jpg
Labels: has-parent, new-component, next, ready-for-review

#5943 Update rainbird.markdown
  source/_components/rainbird.markdown
Labels: to-do

#5638 Add documentation for new Enphase Envoy platform
  source/_components/sensor.enphase_envoy.markdown
  source/images/supported_brands/enphase-logo.svg
Labels: awaits-parent, has-parent, new-component, next

#5927 Update control-panel.markdown
  source/_docs/z-wave/control-panel.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5950 Lovelace changelog updates
  source/lovelace/changelog.markdown
Labels: ready-for-review

#5951 Remove old commands
  source/hassio/commandline.markdown
Labels: to-do

#5946 Moon sensor localization update
  source/_components/sensor.moon.markdown
Labels: ready-for-review

#5801 Updated documentation for configurator addon
  source/_addons/configurator.markdown
Labels: current, has-parent, new-feature, ready-for-review

#5952 Update Android tip to mac address discovery
  source/_components/sensor.miflora.markdown
Labels: ready-for-review

#5132 Add velbus auto-discovery
  source/_components/binary_sensor.velbus.markdown
  source/_components/fan.velbus.markdown
  source/_components/light.velbus.markdown
  source/_components/switch.velbus.markdown
Labels: has-parent, in-progress, new-feature, next

#5474 Add dlna_dmr component
  source/_components/discovery.markdown
  source/_components/media_player.dlna_dmr.markdown
  source/images/supported_brands/dlna.png
Labels: awaits-parent, has-parent, new-component, next

#5955 Updated sensor.dsmr.markdown with two minor improvements
  source/_components/sensor.dsmr.markdown
Labels: bug, current, ready-for-review

#5956 Update indentation in alpha_vantage config
  source/_components/sensor.alpha_vantage.markdown
Labels: current, formatting, ready-for-review

#5963 new lovelace config generator addition
  _config.yml
  source/_addons/configurator.markdown
  source/_components/sensor.alpha_vantage.markdown
  source/_components/sensor.dsmr.markdown
  source/_components/sensor.miflora.markdown
  source/_components/sensor.moon.markdown
  source/_components/telegram_bot.markdown
  source/_components/tuya.markdown
  source/_docs/z-wave/services.markdown
  source/_posts/2018-08-03-release-75.markdown
  source/hassio/commandline.markdown
  source/hassio/installation.markdown
  source/lovelace/tips.markdown
Labels: ready-for-review

#5945 Added in Facebook group community.
  source/help/index.markdown
Labels: current, enhancement, ready-for-review

#5953 Add gps_max_accuracy option
  source/_components/device_tracker.google_maps.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5961 Added model UE40KU6400U as working
  source/_components/media_player.samsungtv.markdown
Labels: current, enhancement, ready-for-review

#5808 tplink device tracker documentation update
  source/_components/device_tracker.tplink.markdown
Labels: current, has-parent, in-progress, new-feature

#5962 Minor gramatical fix
  source/_docs/installation/raspberry-pi.markdown
Labels: current, ready-for-review, spelling

#5969 Update rpi_pfio.markdown
  source/_components/rpi_pfio.markdown
Labels: ready-for-review

#5971 Fixing formatting goof
  source/_components/calendar.google.markdown
Labels: ready-for-review

#5970 Adding user details
  source/_docs/installation/fedora.markdown
Labels: ready-for-review

#5789 Add Facebox auth
  source/_components/image_processing.facebox.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5972 Magicseaweed requested update to 1 free spot.
  source/_components/sensor.magicseaweed.markdown
Labels: to-do

#5975 Add info on teaching automations
  source/_components/image_processing.facebox.markdown
Labels: ready-for-review

#5981 Typo in lovelace docs secial -> special
  source/_lovelace/entities.markdown
Labels: current, ready-for-review, spelling

#5983 Update climate.generic_thermostat.markdown
  source/_components/climate.generic_thermostat.markdown
Labels: current, ready-for-review, spelling

#5976 Remove rename functions from control panel
  source/_docs/z-wave/control-panel.markdown
Labels: has-parent, next, ready-for-review

#5964 Updated BT Home Hub 5 Device Tracker Documentation
  source/_components/device_tracker.bt_home_hub_5.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5652 Updated docs to add altitude changes
  source/_components/sensor.opensky.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5634 Add Waze realtime documentation
  source/_components/sensor.waze_travel_time.markdown
Labels: awaits-parent, has-parent, next

#5966 Update HomematicIP Next
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5985 trigger.entity_id should not be quoted
  source/_docs/scripts.markdown
Labels: bug, current, ready-for-review

#5585 Add documentation for pjlink media player component
  source/_components/media_player.pjlink.markdown
  source/images/supported_brands/pjlink.png
Labels: awaits-parent, has-parent, new-component, next

#5925 Update media_player.webostv.markdown
  source/_components/media_player.webostv.markdown
Labels: current, enhancement, ready-for-review

#5990 Minor changes
  source/_docs/configuration/entity-registry.markdown
Labels: ready-for-review

#5989 Update device-specific.markdown
  source/_docs/z-wave/device-specific.markdown
Labels: ready-for-review

#5995 Adding warning here about the use of now()
  source/_docs/automation/trigger.markdown
Labels: ready-for-review

#5994 Making the warning clearer, and linkable
  source/_docs/configuration/templating.markdown
Labels: ready-for-review

#5999 Fixing the example
  source/_lovelace/map.markdown
Labels: ready-for-review

#6000 Adding details of merging trackers
  source/_components/device_tracker.markdown
Labels: ready-for-review

#6003 Update raspberry-pi.markdown
  source/_docs/installation/raspberry-pi.markdown
Labels: ready-for-review

#5216 Update amcrest.markdown
  source/_components/amcrest.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5217 Update to reflect new pull under review
  source/_components/switch.amcrest.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5993 Embedded MQTT broker needs setup its own password
  source/_docs/mqtt/broker.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5947 Add documentation for new RMV public transport sensor
  source/_components/sensor.rmvtransport.markdown
  source/images/supported_brands/RMV.png
Labels: awaits-parent, has-parent, new-component, next

#5967 Update EphEmber to show new operations modes
  source/_components/climate.ephember.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5997 Added link to the FAQ at the top
  source/lovelace/index.markdown
Labels: current, enhancement, ready-for-review

#5996 Making it clearer what column_width does
  source/_lovelace/glance.markdown
Labels: current, enhancement, ready-for-review

#6011 Change section (fixes #5987)
  source/_components/notify.telegram.markdown
Labels: current, ready-for-review

#5986 Improve deCONZ switch platform documentation
  source/_components/switch.deconz.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5992 Fix typos in Homematic documentation
  source/_addons/homematic.markdown
Labels: current, ready-for-review, spelling

#6010 Minor changes (style fixes, links and typos)
  source/_addons/bluetooth_bcm43xx.markdown
  source/_addons/check_config.markdown
  source/_addons/google_assistant.markdown
  source/_addons/mariadb.markdown
  source/_addons/rpc_shutdown.markdown
  source/_addons/samba.markdown
  source/_addons/tellstick.markdown
Labels: current, formatting, ready-for-review, spelling

#5902 Xiaomi Vacuum: Updated to reflect that it is no longer a toggle
  source/_components/vacuum.xiaomi_miio.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5893 Add documentation for netatmo public component
  source/_components/sensor.netatmo_public.markdown
Labels: awaits-parent, has-parent, new-component, next

#5938 Added docs for state attributes in Dyson fan
  source/_components/fan.dyson.markdown
Labels: awaits-parent, has-parent, new-feature, next

#5979 Update media_player.panasonic_viera.markdown
  source/_components/media_player.panasonic_viera.markdown
Labels: current, enhancement, ready-for-review

#6014 Add setup section
  source/_components/sensor.worldtidesinfo.markdown
Labels: current, enhancement, ready-for-review

#6018 Adding link to Hassbian scripts
  source/_docs/ecosystem/hadashboard.markdown
Labels: current, enhancement, ready-for-review

#6017 Adding link to Hassbian scripts
  source/_docs/ecosystem/appdaemon.markdown
Labels: current, enhancement, ready-for-review

#6016 add support for Konnected momentary beep/blink configuration options
  source/_components/konnected.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6020 Embedded MQTT password change backport to 0.76
  source/_docs/mqtt/broker.markdown
Labels: ready-for-review

#6019 Add new option
  source/_components/sensor.glances.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6015 Update panasonic_viera markdown
  source/_components/media_player.panasonic_viera.markdown
Labels: current, enhancement, in-progress, ready-for-review

#6022 Fixes minor bug in dyson configuration example
  source/_components/dyson.markdown
Labels: to-do

#5978 Add examples for whitelist_external_dirs
  source/_docs/configuration/basic.markdown
Labels: current, enhancement, ready-for-review

#6027 Lovelace: Update description about frontend latest
  source/lovelace/index.markdown
Labels: ready-for-review

#6028 Fix DLNA discovery entry
  source/_components/discovery.markdown
Labels: enhancement, has-parent, next, ready-for-review

#5980 Expand ecobee documentation for set_hold_mode
  source/_components/climate.ecobee.markdown
Labels: current, enhancement, ready-for-review

#6029 Added details
  source/_addons/bluetooth_bcm43xx.markdown
Labels: current, enhancement, ready-for-review

#6024 Update bmw_connected_drive.markdown
  source/_components/bmw_connected_drive.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5831 Caseta 1804
  source/_components/lutron_caseta.markdown
  source/assets/get_lutron_cert.zip
Labels: current, has-parent, ready-for-review

#6043 Update openuv.markdown
  source/_components/openuv.markdown
Labels: to-do

#6042 Updated template condition
  source/_docs/scripts/conditions.markdown
Labels: ready-for-review

#6039 Small error in http component doc
  source/_components/http.markdown
Labels: to-do

#5922 Add documentation for the new Ecovacs (Deebot) component and vacuum
  source/_components/ecovacs.markdown
  source/_components/vacuum.ecovacs.markdown
  source/images/supported_brands/ecovacs.png
Labels: has-parent, new-component, next, ready-for-review

#6052 Update sensor.iperf3.markdown
  source/_components/sensor.iperf3.markdown
Labels: to-do

#6051 Link has changed
  source/_components/tts.google.markdown
Labels: ready-for-review

#6060 Remove RPI variants
  source/getting-started/index.markdown
Labels: ready-for-review

#6059 Update Xiaomi Aqara Button documentation
  source/_components/xiaomi_aqara.markdown
Labels: to-do

#6057 Insteon merge
  source/_components/binary_sensor.insteon.markdown
  source/_components/binary_sensor.insteon_plm.markdown
  source/_components/fan.insteon.markdown
  source/_components/fan.insteon_local.markdown
  source/_components/fan.insteon_plm.markdown
  source/_components/insteon.markdown
  source/_components/insteon_local.markdown
  source/_components/insteon_plm.markdown
  source/_components/light.insteon.markdown
  source/_components/light.insteon_local.markdown
  source/_components/light.insteon_plm.markdown
  source/_components/sensor.insteon.markdown
  source/_components/sensor.insteon_plm.markdown
  source/_components/switch.insteon.markdown
  source/_components/switch.insteon_local.markdown
  source/_components/switch.insteon_plm.markdown
Labels: to-do

#6062 Fixed links to Dyson sub components.
  source/_components/dyson.markdown
Labels: bug, current, ready-for-review

#6030 Remove entity registry docs
  source/_docs/configuration/entity-registry.markdown
  source/_docs/z-wave/control-panel.markdown
  source/_includes/asides/docs_navigation.html
  source/_posts/2018-03-30-release-66.markdown
Labels: awaits-parent, has-parent, next

#6056 Add documentation for js_is_module in panel_custom
  source/_components/panel_custom.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6067 deCONZ - Smaller changes as previously requested
  source/_components/binary_sensor.deconz.markdown
  source/_components/light.deconz.markdown
  source/_components/scene.deconz.markdown
  source/_components/sensor.deconz.markdown
  source/_components/switch.deconz.markdown
Labels: enhancement, next, ready-for-review

#6065 Update wording for Arch Linux
  source/_docs/installation/archlinux.markdown
Labels: current, enhancement, ready-for-review

#6064 include required "sensor_type:" in example - remove duplicate total_rain
  source/_components/sensor.rflink.markdown
Labels: current, enhancement, ready-for-review

#6068 Add auth docs
  source/_docs/authentication.markdown
  source/_docs/authentication/multi-factor-auth.markdown
  source/_docs/authentication/providers.markdown
  source/_includes/asides/docs_navigation.html
  source/images/docs/authentication/login.png
  source/images/docs/authentication/profile.png
Labels: current, new-feature, ready-for-review

#6071 Minor fix
  source/_docs/z-wave/entities.markdown
Labels: ready-for-review

#6072 Added some details
  source/_docs/configuration/templating.markdown
Labels: ready-for-review

#5507 Added verify_ssl option
  source/_components/zoneminder.markdown
Labels: ready-for-review

#6076 Add 'moon_phase' to Dark Sky sensor
  source/_components/sensor.darksky.markdown
Labels: ready-for-review

#6077 Update sensor.noaa_tides.markdown
  source/_components/sensor.noaa_tides.markdown
Labels: to-do

#6079 Update snips.markdown
  source/_components/snips.markdown
Labels: to-do

#6083 fix documents related with xiaoyi xiaofang camera
  source/_components/camera.xiaofang.markdown
  source/_components/camera.xiaomi.markdown
Labels: to-do

#6082 Make configuration example simpler
  source/_components/sensor.sql.markdown
Labels: ready-for-review

#6080 Rewording
  source/_docs/z-wave/control-panel.markdown
Labels: ready-for-review

#6085 Velbus temperature sensors
  source/_components/sensor.velbus.markdown
Labels: to-do

#6044 Add documentation for hangouts and notify.hangouts components
  source/_components/hangouts.markdown
  source/_components/notify.hangouts.markdown
  source/images/supported_brands/hangouts.png
Labels: has-parent, new-component, next, ready-for-review

#6091 Update providers.markdown
  source/_docs/authentication/providers.markdown
Labels: ready-for-review

#6087 Update raspberry pi docker instructions
  source/_docs/installation/docker.markdown
Labels: to-do

#6093 pi_hole sensor also supports a list for monitored_conditions
  source/_components/sensor.pi_hole.markdown
Labels: ready-for-review

#6081 Add Volkszaehler docs
  source/_components/sensor.volkszaehler.markdown
  source/images/supported_brands/volkszaehler.png
Labels: ready-for-review

#6006 Add multiple sensor types for Trafikverket
  source/_components/sensor.trafikverket_weatherstation.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6096 rewrite the doc for hangouts with intents instead of commands
  source/_components/hangouts.markdown
Labels: ready-for-review

#6099 Adding more detail on .gitignore
  source/_docs/ecosystem/backup/backup_github.markdown
Labels: to-do

#6095 Fix SQL command to extract token on iOS
  source/_components/vacuum.xiaomi_miio.markdown
Labels: to-do

#6100 Added default update
  source/_components/tellduslive.markdown
Labels: ready-for-review

#6098 Should be step 3 on
  source/_components/google_assistant.markdown
Labels: ready-for-review

#6097 Update download links for 2.2
  source/hassio/installation.markdown
Labels: ready-for-review

#6105 Update hangouts.markdown
  source/_components/hangouts.markdown
Labels: ready-for-review

#6106 Fix a link
  source/_docs/authentication/providers.markdown
Labels: ready-for-review

#6108 Corrected spelling error
  source/_docs/authentication.markdown
Labels: to-do

#6104 Update fail2ban.markdown
  source/_cookbook/fail2ban.markdown
Labels: to-do

#6114 Fix style issues
  source/_cookbook/fail2ban.markdown
Labels: ready-for-review

#6112 Small correction from home to base
  source/_components/vacuum.neato.markdown
Labels: to-do

#6111 Update xiaomi incorrect service return call
  source/_components/vacuum.xiaomi_miio.markdown
Labels: to-do

#6094 New geo location component with demo platform
  source/_components/demo.markdown
  source/_components/geo_location.markdown
Labels: to-do

#6122 Update sensor.fritzbox_callmonitor.markdown
  source/_components/sensor.fritzbox_callmonitor.markdown
Labels: to-do

#6120 Remove getting started info on creating an api_password
  source/_docs/configuration/basic.markdown
Labels: to-do

#6119 Create configuration_yaml_by_mcaminiti.markdown
  source/_cookbook/configuration_yaml_by_mcaminiti.markdown
Labels: to-do

#6113 Add default_zoom to map card docs.
  source/_lovelace/map.markdown
Labels: ready-for-review

#6124 Adding troubleshooting section
  source/_docs/authentication.markdown
Labels: ready-for-review
