Repository home-assistant/home-assistant.io, pull requests merged in 2018-02, with the labels that each got.

#4609 Added single quotes around format value
  source/_components/tts.voicerss.markdown
Labels: Fix/Formatting/Language/Spelling

#4607 Add sharing images between HASS instances
  source/_components/camera.generic.markdown
Labels: Enhancement

#4611 updated developer tools icon
  source/images/screenshots/developer-tools.png
Labels: Fix/Formatting/Language/Spelling

#4540 Incorrect event name
  source/_docs/scripts.markdown
Labels: Fix/Formatting/Language/Spelling

#4612 added developer-tools-mqtt-icon.png
  source/images/screenshots/developer-tool-mqtt-icon.png
Labels: Enhancement

#4569 SQL Sensor
  source/_components/sensor.sql.md
  source/images/supported_brands/sql.png
Labels: New-component/platform

#4582 Updated Canary camera configuration
  source/_components/camera.canary.markdown
Labels: New-feature

#4558 Added force_update option
  source/_components/binary_sensor.mqtt.markdown
Labels: New-feature

#4586 Add zha radio_type
  source/_components/zha.markdown
Labels: New-feature

#4606 added service call example
  source/_components/python_script.markdown
Labels: Enhancement

#4633 Update history.markdown
  source/_components/history.markdown
Labels: Fix/Formatting/Language/Spelling

#4632 Update sensor.steam_online.markdown
  source/_components/sensor.steam_online.markdown
Labels: Fix/Formatting/Language/Spelling

#4625 Fix URL in Mercedes me binary sensor documentation
  source/_components/binary_sensor.mercedesme.markdown
Labels: Fix/Formatting/Language/Spelling

#4627 Update samba.markdown
  source/_addons/samba.markdown
Labels: Fix/Formatting/Language/Spelling

#4628 Update input_number.markdown
  source/_components/input_number.markdown
Labels: Enhancement

#4489 Added documentation for password mode in input_text
  source/_components/input_text.markdown
Labels: New-feature

#4637 Update dead links in hass-configurator.markdown
  source/_docs/ecosystem/hass-configurator.markdown
Labels: Fix/Formatting/Language/Spelling

#4629 Update logbook.markdown
  source/_components/logbook.markdown
Labels: Fix/Formatting/Language/Spelling

#4618 sensor.alpha_vantage: removed Google as default stock
  source/_components/sensor.alpha_vantage.markdown
Labels: Fix/Formatting/Language/Spelling

#4645 Update TekSavvy sendor documentation.
  source/_components/sensor.teksavvy.markdown
Labels: Enhancement

#4642 Update Postgresql example
  source/_components/sensor.sql.md
Labels: Enhancement

#4655 Fix typo
  source/_docs/scripts/conditions.markdown
Labels: Fix/Formatting/Language/Spelling

#4649 Added Example for 2 STB
  source/_components/media_player.mediaroom.markdown
Labels: Enhancement

#4656 Fix typo
  source/_docs/ecosystem/appdaemon.markdown
Labels: Fix/Formatting/Language/Spelling

#4657 Add Home Assistant vs. Hass.io entry
  source/_faq/ha-vs-hassio.markdown
  source/faq/index.markdown
Labels: Enhancement

#4659 Various spelling, wording and grammar fixes
  source/hassio/run_local.markdown
Labels: Fix/Formatting/Language/Spelling

#4661 Update installation.markdown
  source/_docs/z-wave/installation.markdown
Labels: Fix/Formatting/Language/Spelling

#4651 Update MercedesMe - Add lxml requirement note related to #12320
  source/_components/mercedesme.markdown
Labels: Enhancement

#4662 Update discovery.markdown
  source/_docs/mqtt/discovery.markdown
Labels: Enhancement

#4667 Add missing breaking changes in 0.63 release notes
  source/_posts/2018-02-10-release-63.markdown
Labels: Enhancement

#4664 Make TekSavvy Sensor API a Link
  source/_components/sensor.teksavvy.markdown
Labels: Fix/Formatting/Language/Spelling

#4614 Clarify distribution of random values
  source/_components/sensor.random.markdown
Labels: Enhancement

#4679 Update tls_self_signed_certificate.markdown
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
Labels: Fix/Formatting/Language/Spelling

#4678 Added note calling out Hass.io only
  source/addons/index.html
Labels: Enhancement

#4677 Added note about add-ons
  source/_faq/ha-vs-hassio.markdown
Labels: Enhancement

#4674 Added FAQ link
  source/getting-started/index.markdown
Labels: Enhancement

#4673 Fix Tahoma documentation
  source/_components/cover.tahoma.markdown
  source/_components/sensor.tahoma.markdown
Labels: Fix/Formatting/Language/Spelling

#4675 Update to remove Python 3.4 reference
  source/_faq/pip3.markdown
Labels: Fix/Formatting/Language/Spelling

#4666 Fix MQTT tls_version docs
  source/_docs/mqtt/broker.markdown
Labels: Fix/Formatting/Language/Spelling

#4630 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: Fix/Formatting/Language/Spelling

#4619 Add a Python program to print the correct code sequence for compliant devices
  source/_docs/z-wave/control-panel.markdown
Labels: Enhancement

#4621 Updated Google calendar documentation
  source/_components/calendar.google.markdown
Labels: Enhancement

#4594 Updated xiaomi vacuum instruction for obtaining token from android devices
  source/_components/vacuum.xiaomi_miio.markdown
Labels: Fix/Formatting/Language/Spelling

#4605 Update media_player.vlc.markdown
  source/_components/media_player.vlc.markdown
Labels: Enhancement

#4576 Update homematic.markdown
  source/_components/homematic.markdown
Labels: Enhancement

#4686 Fix demo links
  source/demo/frontend.html
Labels: Fix/Formatting/Language/Spelling

#4672 Specify color temperature ranges and type
  source/_components/switch.flux.markdown
Labels: Enhancement

#4681 Improve MQTT Light docs
  source/_components/light.mqtt.markdown
Labels: Fix/Formatting/Language/Spelling

#4354 added smappee documentation
  source/_components/sensor.smappee.markdown
  source/_components/smappee.markdown
  source/_components/switch.smappee.markdown
  source/images/supported_brands/smappee.png
Labels: New-component/platform

#4693 Added port clarity
  source/_components/google_assistant.markdown
Labels: Enhancement

#4716 Pushed towards SSL, and clarity wording
  source/_components/device_tracker.gpslogger.markdown
Labels: Enhancement

#4650 Small changes to RPi Camera documentation
  source/_components/camera.rpi_camera.markdown
Labels: Enhancement

#4340 New service methods for the Bluesound component
  source/_components/media_player.bluesound.markdown
Labels: New-feature

#4589 Adds file size sensor
  source/_components/sensor.filesize.markdown
Labels: New-component/platform

#4409 Support for PTZ in Onvif cameras
  source/_components/camera.onvif.markdown
Labels: New-feature

#4742 Update venv link to python 3
  source/developers/development_environment.markdown
Labels: Fix/Formatting/Language/Spelling

#4690 Added how to find the web UI.
  source/_docs/configuration.markdown
Labels: Enhancement

#4737 New tested version, Add note about dedicated user
  source/_components/switch.fritzdect.markdown
Labels: Enhancement

#4696 Added documentation for august component
  source/_components/august.markdown
  source/_components/binary_sensor.august.markdown
  source/_components/camera.august.markdown
  source/_components/lock.august.markdown
  source/images/supported_brands/august.png
Labels: New-component/platform

#4588 Adds folder sensor
  source/_components/sensor.folder.markdown
Labels: New-component/platform

#4617 documentation for new component bmw_connected_drive
  source/_components/bmw_connected_drive.markdown
  source/_components/device_tracker.bmw_connected_drive.markdown
  source/_components/sensor.bmw_connected_drive.markdown
Labels: New-component/platform

#4748 Added redirect_from for /components/ios/
  source/_docs/ecosystem/ios.markdown
Labels: Fix/Formatting/Language/Spelling

#4745 Fixed template
  source/_docs/configuration/templating.markdown
Labels: Fix/Formatting/Language/Spelling

#4746 Tested my K5579 and it worked with port 8001
  source/_components/media_player.samsungtv.markdown
Labels: Enhancement

#4417 Add 'lock' device class
  source/_components/binary_sensor.markdown
Labels: New-feature

#4759 Remove reference to web interface
  source/_components/influxdb.markdown
Labels: Fix/Formatting/Language/Spelling
