Repository home-assistant/home-assistant.io, pull requests merged in 2018-09, with the labels that each got.

#6126 new changelog in lovelance
  source/lovelace/changelog.markdown
Labels: to-do

#6128 Update multi-factor-auth.markdown
  source/_docs/authentication/multi-factor-auth.markdown
Labels: ready-for-review

#6133 Appdaemon example for deCONZ to control Sonos
  source/_components/deconz.markdown
Labels: ready-for-review

#6125 Update sensor.google_travel_time.markdown
  source/_components/sensor.google_travel_time.markdown
Labels: ready-for-review

#6066 update Konnected configuration example for device id format validation
  source/_components/konnected.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6090 Add Cover platform to Insteon component
  source/_components/cover.insteon.markdown
  source/_components/insteon_local.markdown
  source/_components/insteon_plm.markdown
Labels: to-do

#6140 Added details about console access
  source/hassio/commandline.markdown
Labels: ready-for-review

#6139 Explicitly list available train attributes
  source/_components/sensor.uk_transport.markdown
Labels: to-do

#6136 Images for the user profile menu
  source/images/frontend/user-language.png
  source/images/frontend/user-theme.png
Labels: ready-for-review

#6137 Updated wording and images
  source/_components/frontend.markdown
Labels: ready-for-review

#6121 Add unique_id to MQTT Light
  source/_components/light.mqtt.markdown
Labels: to-do

#6116 Removed automation: line
  source/_components/input_number.markdown
Labels: ready-for-review

#6102 General updates for formatting & structure
  source/_cookbook/track_battery_level.markdown
Labels: ready-for-review

#6073 Update addon/git_pull for PR home-assistant/hassio-addons#386
  source/_addons/git_pull.markdown
Labels: to-do

#6088 IP address is no longer required for Enphase Envoy component
  source/_components/sensor.enphase_envoy.markdown
Labels: ready-for-review

#6078 Added session_id and slotname_raw values
  source/_components/snips.markdown
Labels: awaits-parent

#6141 Tschmidty69 patch 2
  source/_components/snips.markdown
Labels: ready-for-review

#6145 Update sensor.tibber.markdown
  source/_components/sensor.tibber.markdown
Labels: to-do

#6144 Update sensor.systemmonitor.markdown
  source/_components/sensor.systemmonitor.markdown
Labels: to-do

#6143 Update mailgun.markdown
  source/_components/mailgun.markdown
Labels: to-do

#6138 Standardised entity name throughout page
  source/_components/counter.markdown
Labels: to-do

#6146 Clarification
  source/_docs/z-wave/installation.markdown
Labels: ready-for-review

#6148 Update sensor.rainbird.markdown
  source/_components/sensor.rainbird.markdown
Labels: to-do

#6149 Update switch.rainbird.markdown
  source/_components/switch.rainbird.markdown
Labels: to-do

#6150 Update sensor.ted5000.markdown
  source/_components/sensor.ted5000.markdown
Labels: to-do

#6151 Update switch.homekit_controller.markdown
  source/_components/switch.homekit_controller.markdown
Labels: to-do

#6159 Update APCUPSd docs
  source/_components/apcupsd.markdown
  source/_components/binary_sensor.apcupsd.markdown
  source/_components/sensor.apcupsd.markdown
Labels: ready-for-review

#6157 Update binary_sensor.rachio.markdown
  source/_components/binary_sensor.rachio.markdown
Labels: to-do

#6155 Update sensor.trafikverket_weatherstation.markdown
  source/_components/sensor.trafikverket_weatherstation.markdown
Labels: to-do

#6160 List all available options for method.
  source/_components/notify.rest.markdown
Labels: ready-for-review

#6162 added more detailed instructions for razberry
  source/_docs/z-wave/device-specific.markdown
Labels: ready-for-review

#6165 Fixing formatting
  source/_docs/installation/hassbian.markdown
Labels: ready-for-review

#6135 Added image attachment example for discord component
  source/_components/notify.discord.markdown
Labels: ready-for-review

#6142 Update notify.mailgun.markdown
  source/_components/notify.mailgun.markdown
Labels: ready-for-review

#6154 Update tesla.markdown
  source/_components/tesla.markdown
Labels: to-do

#6153 Update volvooncall.markdown
  source/_components/volvooncall.markdown
Labels: to-do

#6152 Update bmw_connected_drive.markdown
  source/_components/bmw_connected_drive.markdown
Labels: to-do

#6166 Move all parts to the car category
  source/_components/binary_sensor.bmw_connected_drive.markdown
  source/_components/binary_sensor.tesla.markdown
  source/_components/bmw_connected_drive.markdown
  source/_components/climate.tesla.markdown
  source/_components/device_tracker.bmw_connected_drive.markdown
  source/_components/device_tracker.tesla.markdown
  source/_components/device_tracker.volvooncall.markdown
  source/_components/lock.bmw_connected_drive.markdown
  source/_components/lock.tesla.markdown
  source/_components/sensor.bmw_connected_drive.markdown
  source/_components/sensor.tesla.markdown
  source/_components/switch.tesla.markdown
  source/_components/switch.volvooncall.markdown
  source/_components/volvooncall.markdown
Labels: ready-for-review

#6169 Improve warning for yi-hack-v3 versions
  source/_components/camera.yi.markdown
Labels: to-do

#6170 Move to Car category
  source/_components/binary_sensor.mercedesme.markdown
  source/_components/binary_sensor.mychevy.markdown
  source/_components/device_tracker.mercedesme.markdown
  source/_components/mercedesme.markdown
  source/_components/mychevy.markdown
  source/_components/sensor.mercedesme.markdown
  source/_components/sensor.mychevy.markdown
  source/_components/sensor.torque.markdown
Labels: ready-for-review

#6171 Update Mycroft documentation
  source/_components/mycroft.markdown
  source/_components/notify.mycroft.markdown
Labels: ready-for-review

#6173 Move to DIY category
  source/_components/binary_sensor.raspihats.markdown
  source/_components/binary_sensor.rpi_gpio.markdown
  source/_components/binary_sensor.rpi_pfio.markdown
  source/_components/camera.rpi_camera.markdown
  source/_components/cover.rpi_gpio.markdown
  source/_components/light.rpi_gpio_pwm.markdown
  source/_components/switch.raspihats.markdown
  source/_components/switch.rpi_gpio.markdown
  source/_components/switch.rpi_pfio.markdown
  source/_components/switch.rpi_rf.markdown
Labels: ready-for-review

#6174 Move to DIY category
  source/_components/binary_sensor.mysensors.markdown
  source/_components/climate.mysensors.markdown
  source/_components/cover.mysensors.markdown
  source/_components/device_tracker.mysensors.markdown
  source/_components/light.blinksticklight.markdown
  source/_components/light.blinkt.markdown
  source/_components/light.mysensors.markdown
  source/_components/light.sensehat.markdown
  source/_components/mysensors.markdown
  source/_components/notify.mysensors.markdown
  source/_components/sensor.mysensors.markdown
  source/_components/sensor.sense.markdown
  source/_components/sensor.sensehat.markdown
  source/_components/switch.mysensors.markdown
Labels: ready-for-review

#6175 Move to System Monitor category
  source/_components/binary_sensor.digital_ocean.markdown
  source/_components/binary_sensor.linode.markdown
  source/_components/digital_ocean.markdown
  source/_components/linode.markdown
  source/_components/switch.digital_ocean.markdown
  source/_components/switch.digitalloggers.markdown
  source/_components/switch.vultr.markdown
  source/_components/vultr.markdown
Labels: ready-for-review

#6178 Move to DIY category
  source/_components/binary_sensor.pilight.markdown
  source/_components/light.piglow.markdown
  source/_components/pilight.markdown
  source/_components/sensor.pilight.markdown
  source/_components/switch.pilight.markdown
Labels: ready-for-review

#6179 Move to Mailbox category
  source/_components/asterisk_mbox.markdown
  source/_components/sensor.imap_email_content.markdown
Labels: ready-for-review

#6180 Move to Irrigation category
  source/_components/binary_sensor.hydrawise.markdown
  source/_components/binary_sensor.raincloud.markdown
  source/_components/binary_sensor.rainmachine.markdown
  source/_components/hydrawise.markdown
  source/_components/rainbird.markdown
  source/_components/raincloud.markdown
  source/_components/rainmachine.markdown
  source/_components/sensor.hydrawise.markdown
  source/_components/sensor.rainbird.markdown
  source/_components/sensor.raincloud.markdown
  source/_components/sensor.rainmachine.markdown
  source/_components/switch.hydrawise.markdown
  source/_components/switch.rainbird.markdown
  source/_components/switch.raincloud.markdown
  source/_components/switch.rainmachine.markdown
  source/_components/waterfurnace.markdown
Labels: ready-for-review

#6181 Move to Network category
  source/_components/binary_sensor.bayesian.markdown
  source/_components/binary_sensor.ping.markdown
  source/_components/binary_sensor.random.markdown
  source/_components/binary_sensor.threshold.markdown
  source/_components/binary_sensor.trend.markdown
  source/_components/binary_sensor.uptimerobot.markdown
  source/_components/binary_sensor.workday.markdown
  source/_components/cloudflare.markdown
  source/_components/cover.template.markdown
  source/_components/device_tracker.ping.markdown
  source/_components/duckdns.markdown
  source/_components/folder_watcher.markdown
  source/_components/freedns.markdown
  source/_components/google_domains.markdown
  source/_components/namecheapdns.markdown
  source/_components/no_ip.markdown
  source/_components/sensor.api_stream.markdown
  source/_components/sensor.crimereports.markdown
  source/_components/sensor.discogs.markdown
  source/_components/sensor.dnsip.markdown
  source/_components/sensor.duke_energy.markdown
  source/_components/sensor.ebox.markdown
  source/_components/sensor.fail2ban.markdown
  source/_components/sensor.file.markdown
  source/_components/sensor.filesize.markdown
  source/_components/sensor.filter.markdown
  source/_components/sensor.folder.markdown
  source/_components/sensor.history_stats.markdown
  source/_components/sensor.magicseaweed.markdown
  source/_components/sensor.mfi.markdown
  source/_components/sensor.min_max.markdown
  source/_components/sensor.mold_indicator.markdown
  source/_components/sensor.otp.markdown
  source/_components/sensor.pocketcasts.markdown
  source/_components/sensor.qnap.markdown
  source/_components/sensor.random.markdown
  source/_components/sensor.season.markdown
  source/_components/sensor.simulated.markdown
  source/_components/sensor.startca.markdown
  source/_components/sensor.statistics.markdown
  source/_components/sensor.uptime.markdown
  source/_components/sensor.version.markdown
  source/_components/sensor.whois.markdown
Labels: ready-for-review

#6183 Update category
  source/_components/august.markdown
  source/_components/binary_sensor.august.markdown
  source/_components/binary_sensor.ecobee.markdown
  source/_components/binary_sensor.ring.markdown
  source/_components/binary_sensor.skybell.markdown
  source/_components/binary_sensor.wemo.markdown
  source/_components/camera.ring.markdown
  source/_components/camera.skybell.markdown
  source/_components/light.skybell.markdown
  source/_components/ring.markdown
  source/_components/sensor.bbox.markdown
  source/_components/sensor.canary.markdown
  source/_components/sensor.ecobee.markdown
  source/_components/sensor.moon.markdown
  source/_components/sensor.ring.markdown
  source/_components/sensor.skybell.markdown
  source/_components/sensor.teksavvy.markdown
  source/_components/skybell.markdown
  source/_components/sun.markdown
  source/_components/switch.skybell.markdown
Labels: ready-for-review

#6193 Added Razberry Board to supported Z-Wave devices table
  source/_docs/z-wave/controllers.markdown
Labels: to-do

#6192 Clarify MQTT Advanced Configuration
  source/_addons/mosquitto.markdown
Labels: to-do

#6188 For the updates to the customize docs
  source/images/frontend/entity_box.png
Labels: ready-for-review

#6189 Reworking the customize docs
  source/_docs/configuration/customizing-devices.markdown
Labels: ready-for-review

#6194 Add missing color_state_address
  source/_components/light.knx.markdown
Labels: to-do

#6195 Clarify what components work with weather-card
  source/_lovelace/weather-forecast.markdown
Labels: ready-for-review

#6198 Making title linkable
  source/_docs/autostart/systemd.markdown
Labels: ready-for-review

#6197 Trying to direct people away from this
  source/_docs/installation/python.markdown
Labels: ready-for-review

#6199 Fixed branches definition in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#6163 Update Miflora documentation
  source/_components/sensor.miflora.markdown
Labels: to-do

#6186 Create switch.switchbot.markdown
  source/_components/switch.switchbot.markdown
  source/images/supported_brands/switchbot.png
Labels: ready-for-review

#6201 Update sensor.twitch.markdown
  source/_components/sensor.twitch.markdown
Labels: ready-for-review

#6212 Minor fix in switchbot doc
  source/_components/switch.switchbot.markdown
Labels: ready-for-review

#6208 Word fix
  source/_components/vacuum.neato.markdown
Labels: ready-for-review

#6209 Word fix
  source/_components/vacuum.xiaomi_miio.markdown
Labels: ready-for-review

#6210 Clarity updates
  source/_components/vacuum.markdown
Labels: ready-for-review

#6213 Update deconz.markdown
  source/_components/deconz.markdown
Labels: to-do

#5483 Update switch.snmp.markdown
  source/_components/switch.snmp.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5484 Update sensor.snmp.markdown
  source/_components/sensor.snmp.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6118 Documentation for OpenTherm Gateway climate platform
  source/_components/climate.opentherm_gw.markdown
  source/images/supported_brands/opentherm.png
Labels: ready-for-review

#6034 Update statistics sensor
  source/_components/sensor.statistics.markdown
Labels: has-parent, new-feature, next, ready-for-review

#5923 Docs for Habitica component
  source/_components/habitica.markdown
  source/_components/sensor.habitica.markdown
  source/images/screenshots/habitica_new_task.png
  source/images/supported_brands/habitica.png
Labels: has-parent, new-component, next, ready-for-review

#6224 Demonstrate that complex templates can be used for script delays
  source/_docs/scripts.markdown
Labels: ready-for-review

#6132 Documentation for new refresh deCONZ device service
  source/_components/deconz.markdown
Labels: parent-merged

#6147 Clarify and make sure users add config entry.
  source/_docs/z-wave/installation.markdown
Labels: ready-for-review

#6228 Adding some titles and details
  source/_docs/configuration.markdown
Labels: ready-for-review

#6227 Adding WiFi note
  source/_components/device_tracker.nmap_tracker.markdown
Labels: ready-for-review

#6226 Adding WiFi note
  source/_components/device_tracker.ping.markdown
Labels: ready-for-review

#6230 Add note to OpenTherm Gateway documentation
  source/_components/climate.opentherm_gw.markdown
Labels: to-do

#6234 Alter monitored_conditions list
  source/_components/sensor.bom.markdown
Labels: to-do

#6237 :pencil2: Fixes typo configuration.yml -> configuration.yaml
  source/_components/konnected.markdown
Labels: current, ready-for-review, spelling

#6235 Added the list of supported domains
  source/cloud/google_assistant.markdown
Labels: current, enhancement, ready-for-review

#6238 Fix file extension of configuration file
  source/_components/binary_sensor.pilight.markdown
  source/_components/cover.aladdin_connect.markdown
  source/_components/lock.mqtt.markdown
  source/_components/sensor.pilight.markdown
  source/_components/sensor.radarr.markdown
  source/_components/sensor.sonarr.markdown
Labels: ready-for-review

#6217 Adding link to auth docs
  source/_components/auth.markdown
Labels: current, enhancement, ready-for-review

#6241 correct typo (hassbian-sctipts -> hassbian-scripts)
  source/_docs/installation/hassbian/customization.markdown
Labels: current, ready-for-review, spelling

#6247 Change IOT Class to Local Polling
  source/_components/rainmachine.markdown
Labels: current

#6248 Remove .gz from URI for HASSOS OVA.
  source/hassio/installation.markdown
Labels: current

#6242 Fixing formatting
  source/_components/recorder.markdown
Labels: current, formatting, ready-for-review

#6240 Updated setup steps and added testing steps notify.html5.markdown
  source/_components/notify.html5.markdown
Labels: current, enhancement, ready-for-review

#6244 Add troubleshooting for invalid client id error
  source/_docs/authentication.markdown
  source/_docs/configuration/remote.markdown
  source/images/docs/authentication/error-invalid-client-id.png
Labels: current, enhancement, ready-for-review

#6223 Update sensor.wunderground.markdown - WeatherUnderground ends their API and keys
  source/_components/sensor.wunderground.markdown
Labels: current, enhancement, ready-for-review

#6005 Add verify_ssl option to generic camera docs
  source/_components/camera.generic.markdown
Labels: awaits-parent, current, has-parent, new-feature, parent-merged

#6026 update geizhals doc
  source/_components/sensor.geizhals.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#6215 Note about bearer tokens
  source/_docs/authentication.markdown
Labels: current, enhancement, ready-for-review

#6204 Component media_player.spotify doenst support sonos device
  source/_components/media_player.spotify.markdown
Labels: current, enhancement, ready-for-review

#6031 Adds Switchmate documentation
  source/_components/switch.switchmate.markdown
  source/images/supported_brands/switchmate-logo-rgb.png
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#6049 add new Pushsafer Parameter
  source/_components/notify.pushsafer.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#6253 Fix a typo in date which hide configuration page
  source/_docs/configuration.markdown
Labels: ready-for-review

#6130 Adds token parameter to Camera.Push
  source/_components/camera.push.markdown
Labels: awaits-parent, has-parent, new-feature, next

#6256 Fix a link in lets_encrypt howto re: password
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: to-do

#6251 Note about data logging.
  source/_components/android_ip_webcam.markdown
Labels: current, enhancement, ready-for-review

#6260 Spelling mistake?
  source/_components/tradfri.markdown
Labels: current, ready-for-review, spelling

#6220 document option added to konnected binary sensors
  source/_components/konnected.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6259 Update docs for nfandroid notify platform
  source/_components/notify.nfandroidtv.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#6246 Nimbus doc
  source/_components/wink.markdown
Labels: has-parent, new-feature, next, ready-for-review

#6272 Added the usage of PostgreSQL unix sockets
  source/_components/recorder.markdown
Labels: to-do

#6271 Automation to Script in script editor docs
  source/_docs/scripts/editor.markdown
Labels: to-do

#6266 Clarify conditional card docs
  source/_lovelace/conditional.markdown
Labels: to-do

#6277 Update link to Google TTS Supported Languages
  source/_components/tts.google.markdown
Labels: to-do

#6275 Update switch.switchmate.markdown
  source/_components/switch.switchmate.markdown
Labels: ready-for-review

#6273 Fix stuff for new bluetooth LE
  source/_components/device_tracker.bluetooth_le_tracker.markdown
Labels: ready-for-review

#6283 Add note on yeelight music mode
  source/_components/light.yeelight.markdown
Labels: to-do

#6281 Changes for 0.78
  source/_docs/z-wave/control-panel.markdown
Labels: ready-for-review

#6290 Add new HomematicIP Cloud devices
  source/_components/homematicip_cloud.markdown
Labels: to-do

#6289 Update device_tracker.snmp.markdown
  source/_components/device_tracker.snmp.markdown
Labels: to-do

#6286 Making the titles linkable
  source/hassio/commandline.markdown
Labels: ready-for-review

#6285 Update discovery.markdown
  source/_components/discovery.markdown
Labels: to-do

#6291 Fixed MariaDB example
  source/_components/sensor.sql.markdown
Labels: to-do

#6292 Update switch.switchmate.markdown
  source/_components/switch.switchmate.markdown
Labels: ready-for-review

#6302 Clarity edit
  source/_docs/installation/raspberry-pi.markdown
Labels: ready-for-review

#6301 Add aspect_ratio documentation
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
Labels: to-do

#6265 Jewish calendar component documentation
  source/_components/sensor.jewish_calendar.markdown
Labels: ready-for-review

#6298 Add additional working brands to iAlarm page
  source/_components/alarm_control_panel.ialarm.markdown
Labels: ready-for-review

#6304 Fixing formatting
  source/_docs/installation/raspberry-pi.markdown
Labels: ready-for-review

#6306 Add command with LC_ALL=C (fixes #6270)
  source/_docs/z-wave/adding.markdown
Labels: ready-for-review

#6305 KNX Scene needs to be zero-indexed
  source/_components/scene.knx.markdown
Labels: to-do

#6293 Update sensor.template.markdown
  source/_components/sensor.template.markdown
Labels: ready-for-review

#6279 Adding migration note
  source/_docs/authentication.markdown
Labels: ready-for-review

#6236 Added Component Page for Starling Bank Platform
  source/_components/sensor.starlingbank.markdown
  source/images/supported_brands/starlingbank.png
Labels: has-parent, new-component, next, ready-for-review

#6310 Add details about enabling the REST API
  source/_components/switch.mystrom.markdown
  source/images/components/mystrom/switch-advanced.png
Labels: ready-for-review

#6296 New netdata config syntax to allow for multiple elements per group
  source/_components/sensor.netdata.markdown
Labels: to-do

#6312 Adding a linkable title
  source/_docs/automation.markdown
Labels: ready-for-review

#6295 Add missing platforms supported by MQTT discovery
  source/_docs/mqtt/discovery.markdown
Labels: to-do

#6314 Added timed lights with multiple triggers
  source/_cookbook/turn_on_light_for_10_minutes_when_motion_detected.markdown
Labels: to-do

#6315 Correct title on climate modbus
  source/_components/climate.modbus.markdown
Labels: ready-for-review

#6319 Add unique_id to mqtt_json light
  source/_components/light.mqtt_json.markdown
Labels: to-do

#6318 Clarification of Slack integration setup
  source/_components/notify.slack.markdown
Labels: ready-for-review

#6320 Adding links to the graphing options
  source/_docs/z-wave.markdown
Labels: ready-for-review

#6287 Met.no weather platform
  source/_components/weather.met.markdown
  source/images/supported_brands/metno.png
Labels: ready-for-review

#6264 Add asterisk_cdr platform
  source/_components/mailbox.asterisk_cdr.markdown
  source/_docs/asterisk_mbox.markdown
Labels: to-do

#6249 Add Logi Circle component, camera and sensor platform documentation
  source/_components/camera.logi_circle.markdown
  source/_components/logi_circle.markdown
  source/_components/sensor.logi_circle.markdown
  source/images/supported_brands/logi_circle.png
Labels: has-parent, new-component, next, ready-for-review

#6280 YLDP05YL Add
  source/_components/light.yeelight.markdown
Labels: current, enhancement, ready-for-review

#6262 Add unique_id to mqtt camera
  source/_components/camera.mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#6300 Add CO Sensor support for HomeKit
  source/_components/homekit.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#6326 Typo correction in the 'set_fanspeed' params
  source/_components/vacuum.markdown
Labels: bug, current, ready-for-review

#6323 Clarity update
  source/_components/recorder.markdown
Labels: current, enhancement, ready-for-review

#6329 Updated configuration examples
  source/_components/sensor.trafikverket_weatherstation.markdown
Labels: current, enhancement, ready-for-review

#6332 More titles
  source/_components/device_tracker.nmap_tracker.markdown
Labels: ready-for-review

#6316 GeoJSON platform
  source/_components/geo_location.geo_json_events.markdown
  source/_components/geo_location.markdown
  source/images/supported_brands/geo_location.png
Labels: has-parent, new-component, next, ready-for-review

#6335 Typo fix
  source/_docs/installation/virtualenv.markdown
Labels: current, spelling

#6338 Highlighting need to config check
  source/_docs/configuration.markdown
Labels: current, enhancement, ready-for-review
