Repository home-assistant/home-assistant.io, pull requests merged in 2018-10, with the labels that each got.

#6394 Update upgrading.markdown
  source/_docs/installation/hassbian/upgrading.markdown
Labels: Hacktoberfest, to-do

#6398 Add docu for new device attributes
  source/_components/climate.fritzbox.markdown
Labels: Hacktoberfest, to-do

#6405 fixing a bit i forgot when i added altitude
  source/_components/sensor.opensky.markdown
Labels: Hacktoberfest, to-do

#6403 Convert blockquote into note for betters looks
  source/_components/google_assistant.markdown
Labels: Hacktoberfest, to-do

#6401 Update camera.uvc.markdown
  source/_components/camera.uvc.markdown
Labels: Hacktoberfest, to-do

#6400 Update deconz.markdown
  source/_components/deconz.markdown
Labels: Hacktoberfest, to-do

#6406 Add breaking change
  source/_posts/2018-10-01-release-79.markdown
Labels: ready-for-review

#6410 Update with grouping of notifications
  source/_docs/ecosystem/ios/notifications/basic.markdown
Labels: Hacktoberfest, ready-for-review

#6409 Improve Enphase Envoy documentation
  source/_components/sensor.enphase_envoy.markdown
Labels: Hacktoberfest, to-do

#6408 Add IoT class to Unifi device trackers
  source/_components/device_tracker.unifi.markdown
  source/_components/device_tracker.unifi_direct.markdown
Labels: Hacktoberfest, to-do

#6411 Update google_assistant.markdown
  source/_components/google_assistant.markdown
Labels: Hacktoberfest, to-do

#6407 Made the hangouts documentation go into more detail about the covo id
  source/_components/notify.hangouts.markdown
Labels: Hacktoberfest, to-do

#6413 Update variables section format for aREST Binary Sensor
  source/_components/binary_sensor.arest.markdown
Labels: Hacktoberfest, ready-for-review

#6415 Remove note about mjpeg camera errors
  source/_components/camera.mjpeg.markdown
Labels: Hacktoberfest, ready-for-review

#6416 Update configuration variables description
  source/_components/binary_sensor.wirelesstag.markdown
  source/_components/sensor.wirelesstag.markdown
  source/_components/switch.wirelesstag.markdown
Labels: ready-for-review

#6417 Add IQS 'internal'
  source/_components/alert.markdown
  source/_components/api.markdown
  source/_components/auth.markdown
  source/_components/binary_sensor.random.markdown
  source/_components/binary_sensor.trend.markdown
  source/_components/config.markdown
  source/_components/configurator.markdown
  source/_components/counter.markdown
  source/_components/discovery.markdown
  source/_components/frontend.markdown
  source/_components/input_boolean.markdown
  source/_components/input_datetime.markdown
  source/_components/input_number.markdown
  source/_components/input_select.markdown
  source/_components/input_text.markdown
  source/_components/introduction.markdown
  source/_components/map.markdown
  source/_components/persistent_notification.markdown
  source/_components/sensor.filter.markdown
  source/_components/sensor.random.markdown
  source/_components/sensor.statistics.markdown
  source/_components/timer.markdown
  source/_components/updater.markdown
  source/_components/zone.markdown
  source/_docs/quality_scale.markdown
  source/_includes/asides/component_navigation.html
Labels: Hacktoberfest, ready-for-review

#6425 Improve wording in binary sensor
  source/_components/binary_sensor.http.markdown
Labels: Hacktoberfest, to-do

#6418 Improve flic sensor documentation
  source/_components/binary_sensor.flic.markdown
Labels: Hacktoberfest, to-do

#6426 Fix grammar error (allows vs allow)
  source/_docs/mqtt/logging.markdown
Labels: Hacktoberfest, to-do

#6419 Hue configuration variable style
  source/_components/hue.markdown
Labels: to-do

#6422 Added Transporter digital input
  source/_components/media_player.squeezebox.markdown
Labels: to-do

#6424 Axis - troubleshooting bad IPs from discovery
  source/_components/axis.markdown
Labels: Hacktoberfest, ready-for-review

#6430 Update kodi configuration variable style.
  source/_components/media_player.kodi.markdown
Labels: Hacktoberfest, to-do

#6431 Documentation for home-assistant/home-assistant#17065
  source/_components/camera.onvif.markdown
Labels: to-do

#6446 Configuration Variables Lifx light
  source/_components/light.lifx.markdown
Labels: Hacktoberfest, to-do

#6445 Enhance description and usage examples
  source/_components/lock.markdown
Labels: Hacktoberfest, to-do

#6444 Use the new style for configuration variables description
  source/_components/notify.free_mobile.markdown
Labels: Hacktoberfest, to-do

#6442 Added a line clarifying One switch control
  source/_components/climate.generic_thermostat.markdown
Labels: Hacktoberfest, to-do

#6414 Vasttrafik sensor configuration variable style
  source/_components/sensor.vasttrafik.markdown
Labels: ready-for-review

#6437 Added camera
  source/_components/octoprint.markdown
Labels: Hacktoberfest, to-do

#6436 Added example of pushbullet target
  source/_components/notify.pushbullet.markdown
Labels: Hacktoberfest, to-do

#6435 Added example based on event platform
  source/_components/persistent_notification.markdown
Labels: Hacktoberfest, ready-for-review

#6443 Add warning about recovery model with MSSQL Server
  source/_components/recorder.markdown
Labels: Hacktoberfest, ready-for-review

#6438 Added list of routers that is known to work with the libary
  source/_components/huawei_lte.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6450 Add IQS Internal to several components
  source/_components/automation.markdown
  source/_components/demo.markdown
  source/_components/emulated_hue.markdown
  source/_components/panel_custom.markdown
  source/_components/panel_iframe.markdown
  source/_components/proximity.markdown
  source/_components/python_script.markdown
  source/_components/rss_feed_template.markdown
  source/_components/script.markdown
  source/_components/shell_command.markdown
  source/_components/system_log.markdown
  source/_components/weblink.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6449 Ping Sensor configuration variable style
  source/_components/device_tracker.ping.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6440 Add comment about alarm_type versions
  source/_docs/z-wave/entities.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6429 Update emulated_hue configuration variable style
  source/_components/emulated_hue.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6421 deCONZ - Clean up configuration instructions
  source/_components/deconz.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6451 Update simplisafe configuration to new format
  source/_components/alarm_control_panel.simplisafe.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6428 Improve wording, put important info in note block
  source/_components/hangouts.markdown
Labels: Hacktoberfest, current, enhancement, in-progress

#6453 service call typo
  source/_components/vacuum.markdown
Labels: Hacktoberfest, current, enhancement

#6456 Update camera mqtt configuration
  source/_components/camera.mqtt.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6460 Grammar update
  source/_components/binary_sensor.deconz.markdown
Labels: Hacktoberfest, current, ready-for-review, spelling

#6458 Convert Abode to new config style
  source/_components/abode.markdown
Labels: Hacktoberfest, current, enhancement

#6457 Update xiaomi vacuum configuration
  source/_components/vacuum.xiaomi_miio.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6461 Related #6385.
  source/_components/camera.local_file.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6462 Related #6385
  source/_components/foursquare.markdown
Labels: Hacktoberfest, current, enhancement, in-progress

#6463 Update sensor.zabbix.markdown related to #6385
  source/_components/sensor.zabbix.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6455 Update docs for scrape component to add optional headers
  source/_components/sensor.scrape.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, ready-for-review

#6466 Update sensor.zabbix.markdown related to #6385
  source/_components/sensor.zabbix.markdown
Labels: Hacktoberfest, current, spelling

#6468 Add new monitored condition "weather_code"
  source/_components/sensor.openweathermap.markdown
Labels: to-do

#6470 Device comparability notes / how to activate
  source/_docs/ecosystem/ios/notifications/actions.markdown
Labels: Hacktoberfest, to-do

#6327 Added docs for AquaLogic component.
  source/_components/aqualogic.markdown
  source/_components/sensor.aqualogic.markdown
  source/_components/switch.aqualogic.markdown
  source/images/supported_brands/hayward.png
Labels: has-parent, in-progress, new-component, next, parent-merged

#6471 Add 'ha_qa_scale'
  source/_components/alarm_control_panel.manual.markdown
  source/_components/binary_sensor.bayesian.markdown
  source/_components/binary_sensor.ping.markdown
  source/_components/binary_sensor.template.markdown
  source/_components/binary_sensor.threshold.markdown
  source/_components/binary_sensor.workday.markdown
  source/_components/browser.markdown
  source/_components/conversation.markdown
  source/_components/cover.group.markdown
  source/_components/cover.template.markdown
  source/_components/device_sun_light_trigger.markdown
  source/_components/device_tracker.ping.markdown
  source/_components/downloader.markdown
  source/_components/fan.template.markdown
  source/_components/folder_watcher.markdown
  source/_components/group.markdown
  source/_components/history.markdown
  source/_components/history_graph.markdown
  source/_components/intent_script.markdown
  source/_components/light.group.markdown
  source/_components/light.template.markdown
  source/_components/logger.markdown
  source/_components/media_extractor.markdown
  source/_components/media_player.universal.markdown
  source/_components/notify.group.markdown
  source/_components/plant.markdown
  source/_components/recorder.markdown
  source/_components/scene.markdown
  source/_components/sensor.api_stream.markdown
  source/_components/sensor.history_stats.markdown
  source/_components/sensor.min_max.markdown
  source/_components/sensor.mold_indicator.markdown
  source/_components/sensor.moon.markdown
  source/_components/sensor.otp.markdown
  source/_components/sensor.season.markdown
  source/_components/sensor.simulated.markdown
  source/_components/sensor.template.markdown
  source/_components/sensor.time_date.markdown
  source/_components/sensor.uptime.markdown
  source/_components/sensor.version.markdown
  source/_components/sensor.worldclock.markdown
  source/_components/shopping_list.markdown
  source/_components/sun.markdown
  source/_components/switch.flux.markdown
  source/_components/switch.template.markdown
  source/_components/tts.picotts.markdown
  source/_components/websocket_api.markdown
Labels: Hacktoberfest, current, enhancement

#6477 Fix typo as mentioned by @dshanske: diaspora not disapora
  source/_components/sensor.jewish_calendar.markdown
Labels: Hacktoberfest, to-do

#6475 Adding detail about initial state
  source/_docs/automation.markdown
Labels: Hacktoberfest, ready-for-review

#6473 Fixing edit rot
  source/_components/google_assistant.markdown
Labels: Hacktoberfest, bug, current, enhancement, ready-for-review

#6472 Example and tip for automation usage
  source/_components/remote.harmony.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6478 Add second computer and setup note
  source/_addons/rpc_shutdown.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6465 Update Xiaomi devices for Configuration variables
  source/_components/camera.xiaomi.markdown
  source/_components/device_tracker.xiaomi.markdown
  source/_components/media_player.xiaomi_tv.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6480 Fixes motion_enabled spelling
  source/_components/blink.markdown
Labels: Hacktoberfest, next, ready-for-review, spelling

#6481 Port using for MariaDB 10
  source/_components/recorder.markdown
Labels: Hacktoberfest, current, enhancement

#6441 Formatted according to documentation standards
  source/_components/light.hyperion.markdown
Labels: Hacktoberfest, current, enhancement, in-progress

#5885 Update the instructions for location of dropbox_uplodaer.sh
  source/_docs/ecosystem/backup/backup_dropbox.markdown
Labels: current, enhancement

#6479 Update counter docs to reflect restore config option.
  source/_components/counter.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next

#6490 Removed optional configuration setting
  source/_components/weblink.markdown
Labels: Hacktoberfest, to-do

#6494 Add warning about hassio incompatibility
  source/_components/usps.markdown
Labels: Hacktoberfest, ready-for-review

#6495 Add icon
  plugins/configuration.rb
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6464 Use the new style for configuration variables description for Plex pl…
  source/_components/media_player.plex.markdown
Labels: Hacktoberfest, current, enhancement, in-progress

#6492 Update counter component docs
  source/_components/counter.markdown
Labels: Hacktoberfest, enhancement, next

#6489 Update switch Wake on Lan configuration variable
  source/_components/switch.wake_on_lan.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6496 Update screenshot
  source/images/screenshots/configuration-validation.png
Labels: Hacktoberfest, current, enhancement

#6423 Add docu for new fritzbox binary_sensor
  source/_components/binary_sensor.fritzbox.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-component, next

#6502 Update icon entry
  source/_components/input_boolean.markdown
  source/_components/input_number.markdown
  source/_components/input_select.markdown
  source/_components/notify.webostv.markdown
  source/_components/panel_iframe.markdown
  source/_components/sensor.mqtt.markdown
  source/_components/sensor.netdata.markdown
  source/_components/switch.mqtt.markdown
  source/_components/weblink.markdown
Labels: ready-for-review

#6505 Update screenshot to match current version
  source/images/screenshots/server-management.png
Labels: Hacktoberfest, to-do

#6474 Add instructions for updating Google Travel Sensor using service call
  source/_components/sensor.google_travel_time.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next

#6501 Tips for using calendar component in automation
  source/_components/calendar.google.markdown
Labels: Hacktoberfest, to-do

#6508 Update PM Sensor documentation to standards
  source/_components/sensor.serial_pm.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6503 Updated all Telegram component files configuration variable
  source/_components/telegram_bot.broadcast.markdown
  source/_components/telegram_bot.polling.markdown
  source/_components/telegram_bot.webhooks.markdown
Labels: Hacktoberfest, current, enhancement

#6498 Update Alarm.com Alarm Control Panel configuration variable
  source/_components/alarm_control_panel.alarmdotcom.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6500 Update Concord232 Alarm Control Panel configuration variable
  source/_components/alarm_control_panel.concord232.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6511 Add note about containers
  source/_components/sensor.cpuspeed.markdown
Labels: Hacktoberfest, ready-for-review

#6512 Enhance motion sensor lighting cookbook example
  source/_cookbook/turn_on_light_for_10_minutes_when_motion_detected.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6510 "Advanced" example using dynamic destination
  source/_components/sensor.waze_travel_time.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6482 Add documentation for current_temperature_template in climate.mqtt
  source/_components/climate.mqtt.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6497 Update Notify Telegram configuration variable
  source/_components/notify.telegram.markdown
Labels: current, enhancement, in-progress

#6483 device_tracker/tile: add multiple account docs
  source/_components/device_tracker.tile.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, ready-for-review

#6324 Updates after upnp-component rewrite.
  source/_components/upnp.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#6517 expanding documentation for KNX Sensor
  source/_components/sensor.knx.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6101 Update rflink.markdown
  source/_components/rflink.markdown
Labels: bug, current, ready-for-review

#6516 Update verisure.markdown
  source/_components/verisure.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next

#6504 Tibber component
  source/_components/notify.tibber.markdown
  source/_components/sensor.tibber.markdown
  source/_components/tibber.markdown
Labels: Hacktoberfest, new-component, next, parent-merged, ready-for-review

#6527 Ping sensor with new style for configuration variables descritpion
  source/_components/binary_sensor.ping.markdown
Labels: Hacktoberfest, current, enhancement

#6526 Use proper case for Home Assistant
  source/_addons/snips.markdown
  source/_components/rss_feed_template.markdown
  source/_components/sensor.nest.markdown
  source/_docs/ecosystem/appdaemon/api.markdown
  source/_docs/security/porosity.markdown
  source/_posts/2016-04-30-ibeacons-part-1-making-presence-detection-work-better.markdown
  source/_posts/2018-07-06-release-73.markdown
  source/lovelace/index.markdown
Labels: Hacktoberfest, current, ready-for-review

#6525 Host is required in tomato configuration
  source/_components/device_tracker.tomato.markdown
Labels: Hacktoberfest, bug, current

#6522 Clarify the component type of Volvo On Call Device Tracker
  source/_components/device_tracker.volvooncall.markdown
Labels: Hacktoberfest, current, enhancement

#6523 Clarify the component type of Volvo On Call Switch
  source/_components/switch.volvooncall.markdown
Labels: Hacktoberfest, current, enhancement

#6520 Remove duplicate text in multi-factor-auth page
  source/_docs/authentication/multi-factor-auth.markdown
Labels: Hacktoberfest, current, enhancement

#6514 Updated all Zigbee configuration variable
  source/_components/binary_sensor.zigbee.markdown
  source/_components/light.zigbee.markdown
  source/_components/sensor.zigbee.markdown
  source/_components/switch.zigbee.markdown
  source/_components/zigbee.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6515 Added new switch types homekit
  source/_components/homekit.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next

#6530 Fix mixed up description
  source/_components/switch.zigbee.markdown
Labels: Hacktoberfest, current, spelling

#6447 document new behavior
  source/_components/notify.yessssms.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next

#6532 Update Velux component configuration variable
  source/_components/velux.markdown
Labels: Hacktoberfest, current, enhancement

#6533 Update Tesla component configuration variable
  source/_components/tesla.markdown
Labels: Hacktoberfest, current, enhancement

#6538 change diaspora: True capital letter to lower case true
  source/_components/sensor.jewish_calendar.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6545 Update Tado component configuration variable
  source/_components/device_tracker.tado.markdown
  source/_components/tado.markdown
Labels: Hacktoberfest, current, enhancement

#6547 Update Smappee component configuration variable
  source/_components/smappee.markdown
Labels: Hacktoberfest, current, enhancement

#6546 Update Datadog component configuration variable
  source/_components/datadog.markdown
Labels: Hacktoberfest, current, enhancement

#6542 Change True/False Capital letters to lower case true/false
  source/_components/media_player.plex.markdown
Labels: Hacktoberfest, current, enhancement

#6541 Change True/False Capital letters to lower case true/false
  source/_components/device_tracker.owntracks.markdown
Labels: Hacktoberfest, current, enhancement

#6540 Change True/False Capital letters to lower case true/false
  source/_components/calendar.google.markdown
Labels: Hacktoberfest, current, enhancement

#6539 change Captial letters True to lower case true
  source/_components/climate.opentherm_gw.markdown
Labels: Hacktoberfest, current, enhancement

#5458 Improving the Securing docs
  source/_docs/configuration/securing.markdown
Labels: current, enhancement, ready-for-review

#6534 command_line sensor with new style for configuration variables
  source/_components/sensor.command_line.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6531 Update sensors.mitemp_bt configuration variables
  source/_components/sensor.mitemp_bt.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6536 Install guide tweaks
  source/hassio/installation.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6551 Added the Microsoft Bluetooth LE Explorer app as scanner
  source/_components/sensor.miflora.markdown
Labels: Hacktoberfest, current, enhancement

#6552 Minor tweaks
  source/getting-started/index.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6553 Install guide tweak
  source/_docs/installation.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6554 Added info about templates
  source/_components/alert.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6558 Update verisure.markdown
  source/_components/verisure.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged, ready-for-review

#6567 Update Yweather component configuration variable
  source/_components/weather.yweather.markdown
Labels: Hacktoberfest, to-do

#6570 Update Spc component configuration variable
  source/_components/spc.markdown
Labels: Hacktoberfest, to-do

#6569 Update Tellduslive component configuration variable
  source/_components/tellduslive.markdown
Labels: Hacktoberfest, to-do

#6568 Update Thingspeak component configuration variable
  source/_components/thingspeak.markdown
Labels: Hacktoberfest, to-do

#6566 Update Zone component configuration variable
  source/_components/zone.markdown
Labels: ready-for-review

#6563 Add Dockerfile
  Dockerfile
  README.markdown
Labels: Hacktoberfest, enhancement, hugo

#6573 2 for 1: configuration markdown & usage sample
  source/_components/climate.sensibo.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6577 Replaced examples
  source/_components/notify.pushsafer.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6576 Updating examples
  source/_components/notify.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6575 Little note that triggers are or
  source/_docs/automation/trigger.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6574 Add KU6100K Samsung TV to supported models list
  source/_components/media_player.samsungtv.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#6579 Configuration ezfix
  source/_components/device_tracker.actiontec.markdown
Labels: Hacktoberfest, current, enhancement

#6582 typos fixed
  source/_addons/lets_encrypt.markdown
  source/_addons/samba.markdown
  source/_addons/snips.markdown
  source/_addons/ssh.markdown
  source/_cookbook/fail2ban.markdown
  source/_cookbook/google_maps_card.markdown
  source/_cookbook/owntracks_two_mqtt_broker.markdown
  source/_cookbook/perform_actions_based_on_input_select.markdown
  source/_docs/asterisk_mbox.markdown
  source/_docs/configuration/events.markdown
  source/_docs/configuration/group_visibility.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/yaml.markdown
  source/_docs/ecosystem/appdaemon/api.markdown
  source/_docs/ecosystem/appdaemon/running.markdown
  source/_docs/ecosystem/appdaemon/tutorial.markdown
  source/_docs/ecosystem/appdaemon/updating.markdown
  source/_docs/ecosystem/backup/backup_github.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/ecosystem/certificates/tls_domain_certificate.markdown
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
  source/_docs/ecosystem/scenegen.markdown
  source/_docs/frontend/browsers.markdown
  source/_docs/installation/docker.markdown
  source/_docs/installation/freenas.markdown
  source/_docs/installation/hassbian/installation.markdown
  source/_docs/installation/virtualenv.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/z-wave/adding.markdown
  source/_docs/z-wave/control-panel.markdown
  source/_docs/z-wave/device-specific.markdown
  source/_docs/z-wave/installation.markdown
  source/_docs/z-wave/services.markdown
  source/ios/beta.markdown
  source/lovelace/views.markdown
Labels: Hacktoberfest, to-do

#6581 Fixed typo in sensor.starlingbank.markdown
  source/_components/sensor.starlingbank.markdown
Labels: Hacktoberfest, current, spelling

#6583 Update apple TV configuration variables
  source/_components/apple_tv.markdown
Labels: Hacktoberfest, current, enhancement

#6578 Configuration ezfix
  source/_components/switch.acer_projector.markdown
Labels: Hacktoberfest, current, enhancement

#6587 Add Elk-M1
  source/_components/alarm_control_panel.elkm1.markdown
  source/_components/elkm1.markdown
  source/images/supported_brands/elkproducts.png
Labels: to-do

#6599 Update FFMPEG component configuration variable
  source/_components/binary_sensor.ffmpeg_motion.markdown
  source/_components/binary_sensor.ffmpeg_noise.markdown
  source/_components/camera.ffmpeg.markdown
  source/_components/ffmpeg.markdown
Labels: Hacktoberfest, current, enhancement

#6595 Update Axis component configuration variable
  source/_components/axis.markdown
Labels: Hacktoberfest, current, enhancement

#6600 Add documentation for Xiaomi Vibration Sensor
  source/_components/binary_sensor.xiaomi_aqara.markdown
  source/_components/xiaomi_aqara.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next

#6594 Update IFTTT docs
  source/_components/ifttt.markdown
  source/images/components/ifttt/IFTTT_to_HA.png
Labels: Hacktoberfest, has-parent, next, parent-merged, ready-for-review

#6609 Add sensor card docs
  source/_lovelace/sensor.markdown
  source/images/lovelace/lovelace_sensor.png
Labels: to-do

#6590 Add Elk light doc
  source/_components/light.elkm1.markdown
Labels: to-do

#6605 Add device registry to MQTT binary sensor
  source/_components/binary_sensor.mqtt.markdown
Labels: Hacktoberfest, awaits-parent, has-parent

#6611 Add device registry to MQTT fan
  source/_components/fan.mqtt.markdown
Labels: Hacktoberfest, ready-for-review

#6591 Add Device Tracker to Mercedes me page
  source/_components/device_tracker.mercedesme.markdown
Labels: Hacktoberfest, current, enhancement

#6588 Fixes multiple typos on the multi-factor authentication page
  source/_docs/authentication/multi-factor-auth.markdown
Labels: Hacktoberfest, current, spelling

#6596 Update Aurora binary sensor component configuration variable
  source/_components/binary_sensor.aurora.markdown
Labels: Hacktoberfest, current, enhancement
