Repository home-assistant/home-assistant.io, pull requests merged in 2019-03, with the labels that each got.

#8218 Document on_in and off_id
  source/_components/light.ihc.markdown
  source/_components/switch.ihc.markdown
Labels: awaits-parent, has-parent, new-feature, next

#8789 Fix a few links so that they are clickable
  source/_docs/installation/docker.markdown
Labels: current, enhancement

#8787 model MJDP02YL
  source/_components/light.yeelight.markdown
Labels: current, enhancement

#8781 Add support for homekit controller sensors
  source/_components/homekit_controller.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8793 Update discovery.markdown with missing abbreviations
  source/_docs/mqtt/discovery.markdown
Labels: current, has-parent, new-feature, ready-for-review

#8792 Update cover.mqtt.markdown with device_class config
  source/_components/cover.mqtt.markdown
Labels: current, enhancement, ready-for-review

#8786 Add info regarding charset for Mariadb addon
  source/_addons/mariadb.markdown
Labels: current, enhancement, ready-for-review

#7884 Supporting for multiple Netatmo thermostates/valves
  source/_components/climate.netatmo.markdown
Labels: awaits-parent, has-parent, new-feature, next

#8803 🚜 Merges/Redirect SPC component pages
  source/_components/alarm_control_panel.spc.markdown
  source/_components/binary_sensor.spc.markdown
  source/_components/spc.markdown
Labels: current, enhancement, ready-for-review

#8799 Adds throughput_network_in/out to sensor.systemmonitor
  source/_components/sensor.systemmonitor.markdown
Labels: awaits-parent, has-parent, new-feature, next

#8808 Update history_graph.markdown
  source/_components/history_graph.markdown
Labels: to-do

#8807 add optional sender name to sendgrid
  source/_components/notify.sendgrid.markdown
Labels: awaits-parent, has-parent, new-feature, next

#8722 Document 'firetv.adb_command' service
  source/_components/media_player.firetv.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8788 Add pause/unpause service descriptions for RainMachine
  source/_components/rainmachine.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8806 Add 'apps' config entry to Fire TV
  source/_components/media_player.firetv.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8812 🚜 Merges/Redirect Pilight component pages
  source/_components/binary_sensor.pilight.markdown
  source/_components/pilight.markdown
  source/_components/sensor.pilight.markdown
  source/_components/switch.pilight.markdown
Labels: current, enhancement, ready-for-review

#8813 Small corretions
  source/_docs/mqtt/discovery.markdown
Labels: to-do

#8817 virtualenv -> venv
  source/_docs/installation.markdown
Labels: ready-for-review

#8720 Allow configuration of update_interval
  source/_components/ness_alarm.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8805 🚜 Merges/Redirect Asterisk component pages
  source/_components/asterisk_mbox.markdown
  source/_components/mailbox.asterisk_mbox.markdown
Labels: current, enhancement, ready-for-review

#8820 git_pull note
  source/_addons/git_pull.markdown
Labels: current, enhancement, ready-for-review

#8800 Updating rotted URL for certbot guide
  source/_docs/ecosystem/haproxy.markdown
Labels: current, enhancement, ready-for-review

#8778 Update automation.markdown
  source/_docs/automation.markdown
Labels: current, enhancement, ready-for-review

#8819 Added documentation for the Remotec ZRC-90
  source/_docs/z-wave/device-specific.markdown
Labels: current, enhancement, ready-for-review

#8804 🚜 Merges/Redirect Zwave component pages
  source/_components/binary_sensor.zwave.markdown
  source/_components/climate.zwave.markdown
  source/_components/cover.zwave.markdown
  source/_components/fan.zwave.markdown
  source/_components/light.zwave.markdown
  source/_components/lock.zwave.markdown
  source/_components/sensor.zwave.markdown
  source/_components/switch.zwave.markdown
  source/_components/zwave.markdown
Labels: current, enhancement, ready-for-review

#8798 Expand Google pub/sub topic config description
  source/_components/google_pubsub.markdown
Labels: current, enhancement, ready-for-review

#8801 Add nissan_leaf.start_charge service and doc fixes.
  source/_components/nissan_leaf.markdown
Labels: has-parent, next, parent-merged

#8626 Add temperature sensor config documentation for Konnected
  source/_components/konnected.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8795 Added conditional element documentation
  source/_lovelace/picture-elements.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8791 Update camera.mqtt.markdown to document device registry configuration
  source/_components/camera.mqtt.markdown
Labels: current, enhancement, ready-for-review

#8535 Xfinity gateway device_tracker documentation and logo
  source/_components/device_tracker.xfinity.markdown
  source/images/supported_brands/xfinity.svg
Labels: has-parent, in-progress, new-component, next

#8779 Add example of choice of sources for Person
  source/_components/person.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8834 Update entities.markdown
  source/_lovelace/entities.markdown
Labels: to-do

#8459 Change type of offset in utility_meter
  source/_components/utility_meter.markdown
Labels: awaits-parent, has-parent, new-feature, next

#8837 update of breaking change paragraphs
  source/_posts/2019-03-13-release-89.markdown
Labels: ready-for-review

#8841 Adding warning about below Pi2
  source/hassio/installation.markdown
Labels: current, enhancement, ready-for-review

#8679 Add multiple device support in docs
  source/_components/media_player.ps4.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#8746 Include support for new etekcity vesync outlet and switches
  source/_components/switch.vesync.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8810 Update HomematicIP overview
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8833 port number typo on sesame sample URL
  source/_addons/configurator.markdown
Labels: current, enhancement, ready-for-review

#8772 Room/Area support documentation.
  source/_components/google_assistant.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8797 Document dlna_dmr.callback_url_override option
  source/_components/media_player.dlna_dmr.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8822 Mqtt alarm code_arm_required
  source/_components/alarm_control_panel.mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8828 Added documentation for the Aeotec NanoMote Quad
  source/_docs/z-wave/device-specific.markdown
Labels: current, enhancement, ready-for-review

#8598 Provide clearer explanation of the sensor.random
  source/getting-started/configuration.markdown
Labels: current, enhancement, ready-for-review

#8380 Update sensor.yr.markdown
  source/_components/sensor.yr.markdown
Labels: current, enhancement, ready-for-review

#8751 Support multiple keys in ifttt triggers
  source/_components/ifttt.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8853 remove obsolete tplink platform documentations
  source/_components/light.tplink.markdown
  source/_components/switch.tplink.markdown
Labels: ready-for-review

#8851 fix automate command by adding dash
  source/_docs/installation/hassbian/upgrading.markdown
Labels: to-do

#8849 Add notes about using User ID
  source/_components/notify.discord.markdown
Labels: current, enhancement, ready-for-review

#8846 Note how !include_dir* funcs do not support .yml extension
  source/_docs/configuration/splitting_configuration.markdown
Labels: needs-rebase

#8842 Update tibber.markdown
  source/_components/tibber.markdown
Labels: current, enhancement, ready-for-review

#8844 Updated with 0.88 changes referenced in home-assistant/home-assistant/issues/20420
  source/_components/cover.garadget.markdown
Labels: to-do

#8854 Point does not support Arm_Home
  source/_components/point.markdown
Labels: to-do

#8612 Allow light.toggle service to accept all service light turn on params
  source/_components/light.markdown
Labels: has-parent, next, ready-for-review

#8856 Fix PhantomJS typo
  source/_components/usps.markdown
Labels: current, enhancement

#8863 Update for 3+ models (fixes #8821)
  source/_components/speedtestdotnet.markdown
Labels: ready-for-review

#8776 Adding enigma2 media player
  source/_components/discovery.markdown
  source/_components/media_player.enigma2.markdown
  source/images/supported_brands/openwebif.png
Labels: has-parent, new-component, next

#8865 Fix release and add OpenWebif to title
  source/_components/media_player.enigma2.markdown
Labels: to-do

#8869 extra " after message was messing up the format
  source/_docs/ecosystem/ios/notifications/attachments.markdown
Labels: to-do

#8868 Update details about MAC address (fixes #8862)
  source/_components/switch.switchbot.markdown
Labels: ready-for-review

#8859 Provide better instructions for virtual appliance
  source/hassio/installation.markdown
Labels: to-do

#8857 Added example configuration using absolute times
  source/_components/binary_sensor.tod.markdown
Labels: to-do

#8858 Correction for Carwings cutover point
  source/_components/nissan_leaf.markdown
Labels: ready-for-review

#8875 Change of thermostat states for Toon component
  source/_components/toon.markdown
Labels: to-do

#8873 Change the service for Google Travel Time
  source/_components/sensor.google_travel_time.markdown
Labels: to-do

#8777 Add device tracker support for Cisco Mobility Express
  source/_components/device_tracker.cisco_mobility_express.markdown
Labels: has-parent, new-component, next, ready-for-review

#8881 Fix typo in mastodon docs
  source/_components/notify.mastodon.markdown
Labels: to-do

#8876 Tweak for the template
  source/_docs/scripts/conditions.markdown
Labels: ready-for-review

#8889 Update docs for show/hide name/icon
  source/_lovelace/entity-button.markdown
Labels: ready-for-review

#8887 Add custom holidays to workday sensor
  source/_components/binary_sensor.workday.markdown
Labels: ready-for-review

#8898 Spelling of person in first paragraph
  source/_components/person.markdown
Labels: to-do

#8883 Add invert to netdata documentation
  source/_components/sensor.netdata.markdown
Labels: ready-for-review

#8826 Add use_https configuration option to quantum_gateway component
  source/_components/device_tracker.quantum_gateway.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8905 Doc: Add as_timestamp as a Jinja filter.
  source/_docs/configuration/templating.markdown
Labels: to-do

#8903 KNX Cookbook deleted (moved to forum)
  source/_cookbook/automation_knx.markdown
Labels: to-do

#8902 SmartThings cloudhook support docs
  source/_components/smartthings.markdown
Labels: awaits-parent, has-parent, next, ready-for-review

#8909 iperf3 configuration example updated
  source/_components/iperf3.markdown
Labels: current, enhancement, ready-for-review

#8906 Changed from nanoleaf_aurora to nanoleaf
  source/_components/light.nanoleaf.markdown
  source/images/supported_brands/nanoleaf_light.png
Labels: has-parent, next, ready-for-review

#8882 Generate Let's Encrypt certificate for Duck DNS sub sub domains
  source/_addons/duckdns.markdown
Labels: current, enhancement, ready-for-review

#7985 Add press hold for send command
  source/_components/harmony.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#8894 Deprecated http.api_password
  source/_components/http.markdown
  source/_docs/authentication/providers.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#8855 add person device tracking
  source/_components/sensor.google_travel_time.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8814 Update modbus.markdown
  source/_components/modbus.markdown
Labels: has-parent, new-feature, next, parent-merged

#8911 Adding some missing config options for Enigma2 media_player.
  source/_components/media_player.enigma2.markdown
Labels: has-parent, new-component, new-feature, next, parent-merged, ready-for-review

#8879 Add SmartThings sensor support for Three Axis
  source/_components/smartthings.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#8832 Add cppm tracker markdown
  source/_components/cppm.markdown
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#8785 KNX: Update docs - added rate_limit and target_temperature_state_address
  source/_components/climate.knx.markdown
  source/_components/knx.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8878 Add SmartThings climate support for Air Conditioners
  source/_components/smartthings.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#8904 Update person.markdown
  source/_components/person.markdown
Labels: current, enhancement, ready-for-review

#8672 Create sensor.tof
  source/_components/tof.markdown
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#8900 Additional clarification
  source/_components/tts.markdown
Labels: current, enhancement, ready-for-review

#8916 Markdown fixes
  source/_components/sensor.hydroquebec.markdown
  source/_components/sensor.imap.markdown
  source/_components/sensor.influxdb.markdown
  source/_components/sensor.knx.markdown
  source/_components/sensor.kwb.markdown
  source/_components/sensor.lacrosse.markdown
  source/_components/sensor.lastfm.markdown
  source/_components/sensor.linky.markdown
  source/_components/sensor.london_air.markdown
  source/_components/sensor.london_underground.markdown
  source/_components/sensor.magicseaweed.markdown
  source/_components/sensor.markdown
  source/_components/sensor.mfi.markdown
  source/_components/sensor.mitemp_bt.markdown
  source/_components/sensor.modbus.markdown
  source/_components/sensor.modem_callerid.markdown
  source/_components/sensor.moon.markdown
  source/_components/sensor.mqtt.markdown
  source/_components/sensor.mysensors.markdown
  source/_components/sensor.netatmo.markdown
  source/_components/sensor.netdata.markdown
  source/_components/sensor.neurio_energy.markdown
  source/_components/sensor.noaa_tides.markdown
  source/_components/sensor.nut.markdown
  source/_components/sensor.ohmconnect.markdown
  source/_components/sensor.onewire.markdown
  source/_components/sensor.openevse.markdown
  source/_components/sensor.openexchangerates.markdown
  source/_components/sensor.openhardwaremonitor.markdown
  source/_components/sensor.openweathermap.markdown
  source/_components/sensor.pi_hole.markdown
  source/_components/sensor.pollen.markdown
  source/_components/sensor.pvoutput.markdown
  source/_components/sensor.radarr.markdown
  source/_components/sensor.random.markdown
  source/_components/sensor.rest.markdown
  source/_components/sensor.rflink.markdown
  source/_components/sensor.ripple.markdown
  source/_components/smartthings.markdown
  source/_components/switch.danfoss_air.markdown
  source/_components/system_log.markdown
  source/_components/tplink.markdown
  source/_components/unifi.markdown
  source/_components/vacuum.xiaomi_miio.markdown
  source/_components/xs1.markdown
  source/_components/zoneminder.markdown
Labels: current, enhancement, ready-for-review

#8918 Update media_player.markdown
  source/_components/media_player.markdown
Labels: current, enhancement, ready-for-review

#8838 Add documentation for stream component
  source/_components/camera.markdown
  source/_components/stream.markdown
Labels: awaits-parent, has-parent, new-component, new-feature, next, parent-merged

#8923 Update initial_states
  source/_components/automation.markdown
Labels: current, enhancement, ready-for-review

#8896 Add weather sensors to Homematic IP
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next, parent-merged

#8913 Document 'firetv' -> 'androidtv' renaming and added Android TV functionality
  source/_components/androidtv.markdown
  source/_components/media_player.firetv.markdown
  source/images/supported_brands/androidtv.png
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8716 Update tellstick to match with new sensor configuration
  source/_components/tellstick.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8790 Update templating.markdown with time pattern trigger data
  source/_docs/automation/templating.markdown
Labels: current, enhancement, ready-for-review

#8860 Add service updates to RainMachine docs
  source/_components/rainmachine.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8874 Update trusted_networks
  source/_components/http.markdown
Labels: current, enhancement, in-progress

#8931 wrong service name
  source/_components/sensor.google_travel_time.markdown
Labels: to-do

#8929 Update sensor.mhz19.markdown to reflect new version of sensor and HASS.IO specifics
  source/_components/sensor.mhz19.markdown
Labels: ready-for-review

#8932 Update python_component_mqtt_basic.markdown with new callback
  source/_cookbook/python_component_mqtt_basic.markdown
Labels: ready-for-review

#8938 Netlify upgrades (Ruby & Bundler)
  .ruby-version
  Gemfile.lock
Labels: ready-for-review

#8940 Add troubleshooting section
  source/_components/stream.markdown
Labels: to-do

#8936 🚜 Merges/Redirect Zigbee component pages
  source/_components/binary_sensor.zigbee.markdown
  source/_components/light.zigbee.markdown
  source/_components/sensor.zigbee.markdown
  source/_components/switch.zigbee.markdown
  source/_components/zigbee.markdown
Labels: current, enhancement, ready-for-review

#8934 Hardware guidance
  source/_docs/installation.markdown
Labels: current, enhancement, ready-for-review

#8933 Adding minimum disk space note
  source/hassio/installation.markdown
Labels: current, enhancement, ready-for-review

#8935 describe new attributes for rest notify
  source/_components/notify.rest.markdown
Labels: to-do

#8927 Additional info for when template triggers fire
  source/_docs/automation/trigger.markdown
Labels: to-do

#8948 🚜 Merges/Redirect Simplisafe component pages
  source/_components/alarm_control_panel.simplisafe.markdown
  source/_components/simplisafe.markdown
Labels: current, enhancement, ready-for-review

#8951 Added an exclusion for group.all_automations
  source/_components/google_assistant.markdown
Labels: current, enhancement

#8947 🚜 Merges/Redirect Mycroft component pages
  source/_components/mycroft.markdown
  source/_components/notify.mycroft.markdown
Labels: current, enhancement, ready-for-review

#8946 🚜 Merges/Redirect upnp component pages
  source/_components/sensor.upnp.markdown
  source/_components/upnp.markdown
Labels: current, enhancement, ready-for-review

#8950 Telegram_bot: Add option to allow fetching data from unverified SSL e…
  source/_components/notify.telegram.markdown
  source/_components/telegram_bot.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8959 Update command to upgrade via hassbian-config
  source/_docs/installation/hassbian/upgrading.markdown
Labels: to-do

#8964 🚜 Merges/Redirect Ecovacs component pages
  source/_components/ecovacs.markdown
  source/_components/vacuum.ecovacs.markdown
Labels: current, enhancement, ready-for-review

#8963 🚜 Merges/Redirect Hydrawise component pages
  source/_components/binary_sensor.hydrawise.markdown
  source/_components/hydrawise.markdown
  source/_components/sensor.hydrawise.markdown
  source/_components/switch.hydrawise.markdown
Labels: current, enhancement, ready-for-review

#8962 🚜 Merges/Redirect Raincloud component pages
  source/_components/binary_sensor.raincloud.markdown
  source/_components/raincloud.markdown
  source/_components/sensor.raincloud.markdown
  source/_components/switch.raincloud.markdown
Labels: current, enhancement, ready-for-review

#8953 Update media_player.panasonic_viera.markdown
  source/_components/media_player.panasonic_viera.markdown
Labels: needs-rebase

#8960 Update device_tracker.mikrotik.markdown
  source/_components/device_tracker.mikrotik.markdown
Labels: current, enhancement, ready-for-review

#8966 Remove hass.config from aws_lambda notify payload
  source/_components/notify.aws_lambda.markdown
Labels: ready-for-review

#8961 Additional info on enabling GDM on Plex Server
  source/_components/media_player.plex.markdown
Labels: current, enhancement, ready-for-review

#8956 Update generic ip cam docs for stream component
  source/_components/camera.generic.markdown
Labels: has-parent, new-feature, next

#8949 🚜 Merges/Redirect Danfoss_air component pages
  source/_components/danfoss_air.markdown
  source/_components/switch.danfoss_air.markdown
Labels: current, enhancement, ready-for-review

#8954 Added instructions to retrieve zone coordinates using Android app
  source/_components/vacuum.xiaomi_miio.markdown
Labels: current, enhancement, ready-for-review

#8965 Explain an explicit ACL is now required; update example.
  source/_addons/mosquitto.markdown
Labels: ready-for-review

#8957 removing group from default domains and add a warning
  source/_components/google_assistant.markdown
Labels: current, enhancement, ready-for-review

#8967 Update light docs to clarify brightness 0 means light is off
  source/_components/light.markdown
Labels: current, enhancement, ready-for-review

#8970 Added information about additional sensors
  source/_components/sensor.trafikverket_weatherstation.markdown
Labels: to-do

#8977 Remove Iliad Italy
  source/_components/sensor.iliad_italy.markdown
  source/images/supported_brands/iliad.png
Labels: parent-merged, ready-for-review

#8988 Changed a word to clarify
  source/_docs/z-wave/control-panel.markdown
Labels: to-do

#8993 Spelling
  source/_docs/authentication/providers.markdown
Labels: to-do

#8990 Update sensor.pocketcasts.markdown
  source/_components/sensor.pocketcasts.markdown
Labels: to-do

#8985 Update sensor.crimereports.markdown
  source/_components/sensor.crimereports.markdown
Labels: current, enhancement

#8980 Note for iOS 10 Devices
  source/_docs/ecosystem/ios/notifications/content_extensions.markdown
Labels: current, enhancement, ready-for-review

#8994 Small typo 'Srdaerr' to 'Stderr'
  source/_docs/authentication/providers.markdown
Labels: to-do

#8995 add doc for date_time_iso to time_date component
  source/_components/sensor.time_date.markdown
Labels: to-do

#8981 Add some minor changes of python-miio 0.4.5
  source/_components/fan.xiaomi_miio.markdown
  source/_components/light.xiaomi_miio.markdown
Labels: ready-for-review

#8992 Update binary_sensor.xiaomi_aqara.markdown
  source/_components/binary_sensor.xiaomi_aqara.markdown
Labels: current, enhancement, ready-for-review

#8997 remove motion sensor, update binary_sensor state
  source/_components/point.markdown
Labels: to-do

#9003 Update splitting_configuration.markdown
  source/_docs/configuration/splitting_configuration.markdown
Labels: to-do

#8984 Renamed api_streams to websocket_api
  source/_components/sensor.api_streams.markdown
  source/_components/sensor.websocket_api.markdown
Labels: has-parent, next, ready-for-review

#8952 added docs for reddit sort_by config
  source/_components/sensor.reddit.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9000 Consolidate the netgear_lte configuration
  source/_components/netgear_lte.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#9006 Update vacuum.mqtt.markdown
  source/_components/vacuum.mqtt.markdown
Labels: current, enhancement, ready-for-review

#8845 Update docs with yeelight component
  source/_components/yeelight.markdown
Labels: has-parent, new-component, next, ready-for-review

#8864 Update homematicip_cloud.markdown
  source/_components/homematicip_cloud.markdown
Labels: current, enhancement, ready-for-review
