Repository home-assistant/home-assistant.io, pull requests merged in 2019-06, with the labels that each got.

#9516 Add documentation for LCN service calls
  source/_components/lcn.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9542 Clarify that the free tier is limited
  source/_components/pushbullet.markdown
Labels: current, enhancement

#9279 Adding Watson TTS (IBM Cloud)
  source/_components/watson_tts.markdown
  source/images/screenshots/watson_tts_screen.png
  source/images/supported_brands/watson_tts.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#9462 Created the Azure EH docs
  source/_components/azure_event_hub.markdown
  source/images/supported_brands/azure_event_hub.svg
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#9540 Add Z-Wave device model and bold shutdown directions for readability
  source/_docs/z-wave/device-specific.markdown
Labels: current, enhancement, ready-for-review

#9546 Fix 404 link for react example
  source/_cookbook/custom_panel_using_react.markdown
Labels: current, enhancement

#9543 🔨 Add Logo and Quality scale
  source/_components/alarm_control_panel.markdown
  source/_components/binary_sensor.markdown
  source/_components/camera.markdown
  source/_components/climate.markdown
  source/_components/cover.markdown
  source/_components/device_tracker.markdown
  source/_components/fan.markdown
  source/_components/light.markdown
  source/_components/lock.markdown
  source/_components/media_player.markdown
  source/_components/notify.markdown
  source/_components/sensor.markdown
  source/_components/switch.markdown
Labels: current, enhancement, ready-for-review

#9538 Adds AdGuard Home integration
  source/_components/adguard.markdown
  source/images/supported_brands/adguard.png
Labels: awaits-parent, has-parent, new-integration, next

#9553 ✏️ Fix broken link in configurator component
  source/_components/configurator.markdown
Labels: current, enhancement, ready-for-review

#9544 🔨 Change the device class description
  source/_components/ads.markdown
  source/_components/binary_sensor.knx.markdown
  source/_components/binary_sensor.mqtt.markdown
  source/_components/binary_sensor.rest.markdown
  source/_components/binary_sensor.rflink.markdown
  source/_components/binary_sensor.rfxtrx.markdown
  source/_components/binary_sensor.template.markdown
  source/_components/command_line.markdown
  source/_components/cover.mqtt.markdown
  source/_components/cover.template.markdown
  source/_components/enocean.markdown
  source/_components/raspihats.markdown
  source/_components/rest.markdown
  source/_components/trend.markdown
  source/_components/w800rf32.markdown
Labels: current, enhancement, ready-for-review

#9560 ⏪ Put the device classes back
  source/_components/binary_sensor.markdown
  source/_components/cover.markdown
  source/_components/sensor.markdown
Labels: current, enhancement

#9550 Fix ipv6 issue with Nginx not redirecting to ipv4 instance of Hass
  source/_docs/ecosystem/nginx.markdown
Labels: current, enhancement, ready-for-review

#9565 Correct misspelled install
  source/hassio/installation.markdown
Labels: current, enhancement

#9566 🌱 Correct misspelled install (#9565)
  source/hassio/installation.markdown
Labels: cherry-picked, current, enhancement

#9575 Remote rpi gpio: address -> host
  source/_components/remote_rpi_gpio.markdown
Labels: current, enhancement, ready-for-review

#9574 Correct copy/paste error on zeroconf
  source/_components/zeroconf.markdown
Labels: current, enhancement, ready-for-review

#9573 Add abbreviation for light template variable names
  source/_docs/mqtt/discovery.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8733 Add documentation for streamlabswater component
  source/_components/streamlabswater.markdown
  source/images/supported_brands/streamlabswater.png
Labels: has-parent, new-integration, next, ready-for-review

#9578 Add templating to MQTT Cover tilt_status_topic
  source/_components/cover.mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9570 Updated Homematic IP alarm_control_panel description
  source/_components/homematicip_cloud.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#9585 Automations: Corrects documentation to match codebase
  source/_components/automation.markdown
  source/_docs/automation.markdown
Labels: current, has-parent, parent-merged, ready-for-review

#9599 Update guidance on using HA with Docker on synology
  source/_docs/installation/docker.markdown
Labels: current, enhancement, ready-for-review

#9582 Update watson_tts.markdown
  source/_components/watson_tts.markdown
Labels: current, enhancement, ready-for-review

#9586 Moving outdated information
  source/_components/group.markdown
Labels: current, enhancement, ready-for-review

#9618 Version bump for Python
  source/_docs/installation.markdown
Labels: current, enhancement

#9620 Added note about `known_devices.yaml`
  source/_components/device_tracker.markdown
Labels: current, enhancement

#9621 Drop reference to `known_devices.yaml`
  source/_components/gpslogger.markdown
Labels: current, enhancement

#9619 Version bumb
  source/_docs/installation/virtualenv.markdown
Labels: current, enhancement

#9622 No more `known_devices.yaml`
  source/_components/locative.md
Labels: current, enhancement

#9593 Clarify how the integration sensor works
  source/_components/integration.markdown
Labels: current, enhancement, ready-for-review

#9614 Adding a big warning
  source/hassio/installation.markdown
Labels: current, enhancement, ready-for-review

#9628 Added note on remotely powering on Marantz receivers
  source/_components/denonavr.markdown
Labels: current, enhancement, ready-for-review

#9634 Fix typo in autostart directions
  source/_docs/autostart/init.d.markdown
Labels: current, enhancement

#9631 Update synologydsm.markdown
  source/_components/synologydsm.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9639 adding Simple Service Discovery Protocol
  source/_components/ssdp.markdown
Labels: current, enhancement

#9604 Update homematicip_cloud.markdown
  source/_components/homematicip_cloud.markdown
Labels: current, enhancement

#9638 Adding the warnings here
  source/_docs/z-wave/installation.markdown
Labels: current, enhancement

#9606 Updated Netdata documentation
  source/_components/netdata.markdown
Labels: current, enhancement, ready-for-review

#9643 Fix a typo
  source/_docs/z-wave/installation.markdown
Labels: current, enhancement

#9216 Added documentation for invert_percent configuration for zwave roller…
  source/_components/zwave.markdown
  source/_docs/z-wave/installation.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9646 Fix `set_cover_tilt_position` position attribute
  source/_components/cover.markdown
Labels: bug, current

#9645 Adding a big warning
  source/_posts/2017-05-01-home-assistant-on-raspberry-pi-zero-in-30-minutes.markdown
Labels: current, enhancement, ready-for-review

#9057 Add docs for new google service
  source/_components/calendar.google.markdown
Labels: has-parent, new-feature, next, parent-merged

#9580 Newer Android Mi Home App doesn't store token anymore
  source/_components/vacuum.xiaomi_miio.markdown
Labels: current, enhancement, ready-for-review

#9087 add code_arm_required to manual alarm with mqtt
  source/_components/manual_mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9640 Add switcher kis auto off service
  source/_components/switcher_kis.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9539 Life360 integration
  source/_components/life360.markdown
  source/images/supported_brands/life360.png
Labels: has-parent, new-integration, next, parent-merged

#9398 Adds documentation for Plaato Airlock
  source/_components/plaato.markdown
  source/images/supported_brands/plaato.png
Labels: has-parent, new-integration, next, parent-merged

#8761 Smarty component documentation
  source/_components/smarty.markdown
  source/images/supported_brands/salda.png
Labels: has-parent, new-integration, next, parent-merged

#9367 Google Cloud Platform Documentation
  source/_components/google_cloud.markdown
  source/images/supported_brands/google_cloud.png
Labels: has-parent, new-integration, next, parent-merged

#9522 Add Lock device type to zha.markdown
  source/_components/zha.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9555 Add DD-WRT device tracker wireless_only option
  source/_components/ddwrt.markdown
Labels: has-parent, new-feature, next

#9554 Improve amcrest error handling
  source/_components/amcrest.markdown
Labels: has-parent, new-feature, next

#9347 Adding accuracy filter feature
  source/_components/traccar.markdown
Labels: has-parent, new-feature, next

#9490 Solaredge local
  source/_components/solaredge_local.markdown
Labels: has-parent, new-integration, next, parent-merged

#9486 Add control of Amcrest indicator light
  source/_components/amcrest.markdown
Labels: has-parent, new-feature, next, parent-merged

#9245 Added toggle services
  source/_components/cover.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9275 Note that changing automations via editor reformats templates
  source/_docs/automation/editor.markdown
Labels: current, enhancement, ready-for-review

#9056 Add APRS device tracker documentation
  source/_components/device_tracker.aprs.markdown
  source/images/supported_brands/aprs.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#9456 Add Sensor, BinarySensor to geniushub
  source/_components/geniushub.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#9587 honeywell - Fix issue 18932 & clean up the mess
  source/_components/honeywell.markdown
Labels: has-parent, new-feature, parent-merged, ready-for-review

#8604 Add Environment Canada weather, sensor, and camera platforms
  source/_components/environment_canada.markdown
  source/images/supported_brands/environment_canada.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#9088 add code_arm_required to manual alarm
  source/_components/manual.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9506 Update discovery and zeroconf documentation
  source/_components/discovery.markdown
  source/_components/zeroconf.markdown
Labels: has-parent, new-feature, next

#9545 Add documentation for LCN scene platform
  source/_components/lcn.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9102 Clarification regarding last_xxx being in UTC
  source/_docs/configuration/state_object.markdown
Labels: current, enhancement, ready-for-review

#9625 Somfy open api
  source/_components/somfy.markdown
  source/images/supported_brands/somfy.png
Labels: has-parent, new-integration, next

#9234 Remove invalid example
  source/_components/alert.markdown
Labels: bug, current

#9416 Newer MDI icons not immediately available
  source/_docs/configuration/customizing-devices.markdown
Labels: current, enhancement

#9485 edited hold modes for clarity
  source/_components/ecobee.markdown
Labels: current, enhancement

#9442 Remove documentation on removed `excluded_entities` key
  source/lovelace/yaml-mode.markdown
Labels: current, enhancement

#9422 Add Linky sensors : yesterday + months + years
  source/_components/linky.markdown
Labels: has-parent, new-feature, next, parent-merged

#9491 Deleting config/emulated_hue_ids.json to reset
  source/_components/emulated_hue.markdown
Labels: current, enhancement

#9567 Fix logger examples (great migration)
  source/_components/logger.markdown
Labels: current, enhancement

#9598 Document the default for with_group option
  source/_components/sonos.markdown
Labels: current, enhancement

#9650 Get stale bot of the PRs that have parents
  .github/stale.yml
Labels: current, enhancement

#9651 🔨 Integrations are the new components
  source/_includes/asides/component_navigation.html
  source/_includes/custom/navigation.html
  source/components/index.html
Labels: current, ready-for-review

#9602 [Utility Meter] Add template sensors to DSMR example
  source/_components/utility_meter.markdown
Labels: current, enhancement, ready-for-review

#9652 minior gramatical fix
  source/_components/mastodon.markdown
Labels: current, spelling

#9656 Component(s) -> Integration(s)
  source/_addons/snips.markdown
  source/_cookbook/custom_panel_using_react.markdown
  source/_cookbook/notify_if__new_ha_release.markdown
  source/_cookbook/python_component_automation.markdown
  source/_cookbook/python_component_mqtt_basic.markdown
  source/_cookbook/python_component_simple_alarm.markdown
  source/_cookbook/track_battery_level.markdown
  source/_docs/authentication.markdown
  source/_docs/automation/editor.markdown
  source/_docs/automation/trigger.markdown
  source/_docs/automation/troubleshooting.markdown
  source/_docs/backend/updater.markdown
  source/_docs/configuration.markdown
  source/_docs/configuration/events.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/configuration/platform_options.markdown
  source/_docs/configuration/securing.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/state_object.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/configuration/yaml.markdown
  source/_docs/ecosystem/appdaemon/api.markdown
  source/_docs/ecosystem/appdaemon/operation.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/ecosystem/ios.markdown
  source/_docs/ecosystem/ios/notifications.markdown
  source/_docs/installation.markdown
  source/_docs/installation/docker.markdown
  source/_docs/installation/hassbian/integrations.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/mqtt/discovery.markdown
  source/_docs/mqtt/logging.markdown
  source/_docs/mqtt/service.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/editor.markdown
  source/_docs/scripts/service-calls.markdown
  source/_docs/security.markdown
  source/_docs/tools/dev-tools.markdown
  source/_docs/z-wave/devices.markdown
  source/_docs/z-wave/installation.markdown
  source/_docs/z-wave/services.markdown
  source/_faq/component.markdown
  source/_faq/problems-with-dependencies.markdown
  source/components/index.html
  source/cookbook/index.markdown
  source/developers/architecture_components.markdown
  source/developers/component_discovery.markdown
  source/developers/component_loading.markdown
  source/developers/creating_components.markdown
  source/developers/internationalization/custom_component_localization.markdown
  source/hassio/run_local.markdown
  source/help/reporting_issues.markdown
  source/lovelace/yaml-mode.markdown
  source/privacy/index.markdown
Labels: current, ready-for-review, spelling

#9623 Queensland bushfire alert feed platform
  source/_components/geo_location.markdown
  source/_components/qld_bushfire.markdown
  source/images/screenshots/qld-bushfire-feed-map.png
Labels: has-parent, new-integration, next

#9530 Update multi-factor-auth.markdown
  source/_docs/authentication/multi-factor-auth.markdown
Labels: current, enhancement

#9641 Update hyperion.markdown
  source/_components/hyperion.markdown
Labels: current, enhancement

#9659 Update hyperion.markdown
  source/_components/hyperion.markdown
Labels: current, enhancement

#9513 Added possibility to define the data type for set_device_value
  source/_components/homematic.markdown
Labels: current, has-parent, new-feature, parent-merged

#9654 Add incomfort climate, sensor and binary_sensor
  source/_components/incomfort.markdown
Labels: has-parent, new-feature, next

#9661 Add tolerance to dlib face identify
  source/_components/dlib_face_identify.markdown
Labels: awaits-parent, has-parent, new-feature, next

#8717 Added documentation for the ELV PCA 301 smart emeter switch
  source/_components/switch.pca.markdown
  source/images/supported_brands/elv.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#9239 Update Météo France component documentation
  source/_components/meteo_france.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#9666 Update about Google Home
  source/_components/emulated_hue.markdown
Labels: current, enhancement

#9612 Update zwave.markdown
  source/hassio/zwave.markdown
Labels: current, enhancement, ready-for-review

#9613 Update installation.markdown
  source/_docs/z-wave/installation.markdown
Labels: current, enhancement, ready-for-review

#9662 Update to the macOS guide
  source/_docs/installation/macos.markdown
Labels: current, enhancement, ready-for-review

#9669 Add note on conditions not working without forecast
  source/_components/darksky.markdown
Labels: current, enhancement

#9676 Added ES5700
  source/_components/samsungtv.markdown
Labels: current, enhancement

#9394 Documentation for template expand
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, has-parent, new-feature, next

#9681 Minimal fix of typo
  source/_components/emulated_hue.markdown
Labels: current, enhancement

#9685 Small fix + grammar improvement
  source/getting-started/automation.markdown
Labels: current, enhancement, spelling

#9679 Additional instructions for Mariadb 10.3
  source/_components/recorder.markdown
Labels: current, enhancement

#9684 Add show_as_state options to Life360
  source/_components/life360.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9690 Add support for IPP Printers to CUPS integration
  source/_components/cups.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9558 vlc-telnet component documentation added
  source/_components/vlc-telnet.markdown
Labels: has-parent, new-integration, next, ready-for-review

#9694 Small tweaks, spelling & grammer improvements to 0.95 blog post
  source/_posts/2019-06-26-release-95.markdown
Labels: blog, enhancement, rc, spelling

#9695 Update lets_encrypt.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: current, enhancement, ready-for-review

#9698 Fixed typos
  source/_components/google_cloud.markdown
Labels: current, enhancement

#9708 a space to many corrupted the equilibrium
  source/_components/google_cloud.markdown
Labels: current, enhancement

#9706 add icon_template to configuration options
  source/_components/light.template.markdown
Labels: current, enhancement, ready-for-review

#9704 Updated default_encoder to mp3
  source/_components/google_cloud.markdown
Labels: has-parent, next, parent-merged

#9707 Removing integration instead of .tradfri_psk.conf
  source/_components/tradfri.markdown
Labels: current, enhancement, ready-for-review

#9701 Update mqtt_room markdown
  source/_components/mqtt_room.markdown
Labels: current, enhancement, ready-for-review

#9176 Update docs to reflect multiple devices support in opentherm_gw
  source/_components/opentherm_gw.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9333 Add documentation for trafikverket_train
  source/_components/trafikverket_train.markdown
Labels: has-parent, new-integration, next, parent-merged

#9668 Add documentation for integration of Vallox ventilation units
  source/_components/vallox.markdown
Labels: has-parent, in-progress, new-integration, next, parent-merged

#9496 Add Template vacuum documentation
  source/_components/vacuum.template.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9647 Add offset option (#24600)
  source/_components/deutsche_bahn.markdown
Labels: has-parent, new-feature, next, parent-merged

#9716 Update map for 'dark_mode' property
  source/_lovelace/map.markdown
Labels: current, enhancement

#9715 More detailed description of js imports
  source/_components/frontend.markdown
Labels: current, enhancement, ready-for-review

#9717 🎨 Adds Vallox logo to integration
  source/_components/vallox.markdown
  source/images/supported_brands/vallox.png
Labels: enhancement, next, ready-for-review

#9672 Examples for LCN service calls in yaml
  source/_components/lcn.markdown
Labels: current, enhancement, ready-for-review

#9687 notes on using states(xxx) vs states.xxx
  source/_docs/configuration/templating.markdown
Labels: current, enhancement, in-progress

#9720 Additional YAML Example
  source/_components/pi_hole.markdown
Labels: current, enhancement, ready-for-review

#9726 Adds support for VS Code Remote Development
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/cSpell.json
  .vscode/extensions.json
  .vscode/tasks.json
Labels: current, ready-for-review

#9728 Delete bluetooth_bcm43xx page
  source/_addons/bluetooth_bcm43xx.markdown
Labels: current, enhancement, ready-for-review

#9725 Adds MarkdownLint configuration
  .markdownlint.json
Labels: current, ready-for-review

#9724 Update for Pi4 and A2
  source/_docs/installation.markdown
Labels: current, enhancement, ready-for-review

#9689 Updating tplink docs to include missing dimmer option.
  source/_components/tplink.markdown
Labels: has-parent, new-feature, next

#9714 Add template support to template trigger's for option
  source/_docs/automation/trigger.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9517 Update totalconnect.markdown
  source/_components/totalconnect.markdown
Labels: in-progress, needs-rebase, parent-merged

#9727 Adds support for Gitpod.io
  .gitpod.yml
  .theia/tasks.json
Labels: current, enhancement, ready-for-review

#9731 added i2c group to homeassistant user
  source/_docs/installation/raspberry-pi.markdown
Labels: current, enhancement, ready-for-review

#9734 Show whats loaded with links to the integrations
  source/_components/default_config.markdown
Labels: current, enhancement, ready-for-review

#9735 Fix typo
  source/_components/switch.markdown
Labels: current, enhancement

#9738 Adjust stalebot to ignore 'Help wanted'
  .github/stale.yml
Labels: current, ready-for-review

#9739 Adjust Gitpod to run Jekyll generate in pre-build
  .gitpod.yml
Labels: current, enhancement, ready-for-review

#9736 Rewrites states.xxx -> states('xxx') (and similar)
  source/_components/alert.markdown
  source/_components/binary_sensor.template.markdown
  source/_components/binary_sensor.xiaomi_aqara.markdown
  source/_components/calendar.google.markdown
  source/_components/cover.template.markdown
  source/_components/deconz.markdown
  source/_components/deutsche_bahn.markdown
  source/_components/fritzbox_callmonitor.markdown
  source/_components/garadget.markdown
  source/_components/hangouts.markdown
  source/_components/harmony.markdown
  source/_components/homematic.markdown
  source/_components/input_datetime.markdown
  source/_components/input_number.markdown
  source/_components/iss.markdown
  source/_components/light.template.markdown
  source/_components/lock.template.markdown
  source/_components/london_air.markdown
  source/_components/min_max.markdown
  source/_components/modem_callerid.markdown
  source/_components/mvglive.markdown
  source/_components/mystrom.markdown
  source/_components/opengarage.markdown
  source/_components/pvoutput.markdown
  source/_components/rest.markdown
  source/_components/ring.markdown
  source/_components/rmvtransport.markdown
  source/_components/rova.markdown
  source/_components/rss_feed_template.markdown
  source/_components/script.markdown
  source/_components/sensehat.markdown
  source/_components/sensor.command_line.markdown
  source/_components/seven_segments.markdown
  source/_components/shell_command.markdown
  source/_components/solaredge.markdown
  source/_components/solaredge_local.markdown
  source/_components/switch.rest.markdown
  source/_components/switch.template.markdown
  source/_components/template.markdown
  source/_components/threshold.markdown
  source/_components/tibber.markdown
  source/_components/transport_nsw.markdown
  source/_components/uk_transport.markdown
  source/_components/vacuum.xiaomi_miio.markdown
  source/_components/webostv.markdown
  source/_cookbook/automation_first_light.markdown
  source/_cookbook/dim_and_brighten_lights.markdown
  source/_cookbook/google_maps_card.markdown
  source/_cookbook/notify_if__new_ha_release.markdown
  source/_cookbook/notify_if_over_threshold.markdown
  source/_cookbook/track_battery_level.markdown
  source/_docs/automation/action.markdown
  source/_docs/automation/condition.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
  source/_docs/scripts/service-calls.markdown
Labels: current, enhancement, ready-for-review

#9746 Mention website analytics platform in privacy policy
  source/privacy/index.markdown
Labels: current, enhancement

#9742 Added Covers to the velbus docu
  source/_components/velbus.markdown
Labels: awaits-parent, has-parent, new-feature, next

#9744 Collection of small technical cleanups
  .gitignore
  .project
  .travis.yml
  README.md
Labels: current, ready-for-review
