Repository home-assistant/home-assistant.io, pull requests merged in 2019-09, with the labels that each got.

#10195 Update docs for new alarmdecoder keypress feature
  source/_components/alarmdecoder.markdown
Labels: has-parent, new-feature, next, parent-merged

#10259 new media_player media_content_type
  source/_cookbook/perform_actions_based_on_input_select.markdown
Labels: current

#10261 Added an extra note regarding data consumption
  source/_components/fastdotcom.markdown
Labels: current, enhancement, ready-for-review

#10267 Fixing errors
  source/_docs/configuration/templating.markdown
Labels: current, enhancement

#10268 Quick typo "id" -> "is"
  source/_docs/mqtt/discovery.markdown
Labels: current, ready-for-review, spelling

#10273 Update counter.markdown
  source/_components/counter.markdown
Labels: current, enhancement, ready-for-review

#10266 Update documentation for Configuration UI
  source/_components/config.markdown
Labels: current, enhancement, ready-for-review

#10204 New template sensor attributes docs
  source/_components/template.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10222 Add BeeWi SmartClim BLE sensor documentation
  source/_components/beewi_smartclim.markdown
  source/images/supported_brands/beewi_by_otio.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#10177 Add inverted RFLink cover description
  source/_components/cover.rflink.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10265 Update Supla's page with switch devices now supported
  source/_components/supla.markdown
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#10278 Fixes updater notification template
  source/_components/updater.markdown
Labels: bug, current

#10276 Removes linkable_title occurance
  source/_components/cups.markdown
Labels: current, enhancement

#10262 MQTT Sensor: Warn about synchronization/double trigger issues.
  source/_components/sensor.mqtt.markdown
Labels: current, enhancement, has-parent, ready-for-review

#10280 Update ifttt.markdown
  source/_components/ifttt.markdown
Labels: current

#10279 Update google_maps.markdown
  source/_components/google_maps.markdown
Labels: awaits-parent, has-parent, next

#10275 Switch to full commonmark + general upgrades
  Gemfile
  Gemfile.lock
  _config.yml
Labels: current, enhancement

#10274 Update remote_rpi_gpio.markdown
  source/_components/remote_rpi_gpio.markdown
Labels: current, enhancement

#10241 Cert expiry documentation for config entries
  source/_components/cert_expiry.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10235 Add documentation for two new service methods
  source/_components/openuv.markdown
Labels: has-parent, new-feature, next, parent-merged

#9372 Add nws weather.
  source/_components/nws.markdown
Labels: has-parent, in-progress, new-integration, next, parent-merged

#10281 Adds logo to NWS
  source/_components/nws.markdown
  source/images/supported_brands/nws.png
Labels: enhancement, next

#10283 Lovelace background theme
  source/lovelace/views.markdown
  source/lovelace/yaml-mode.markdown
Labels: has-parent, next

#10282 Removes NOOP linkable_title plugin
  plugins/linkable_title.rb
Labels: current, enhancement, ready-for-review

#10229 GeoNet NZ Quakes Sensor
  source/_components/geonetnz_quakes.markdown
  source/images/screenshots/geonetnz-quakes-sensor.png
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10127 Added documentation for new Slide cover integration
  source/_components/slide.markdown
  source/images/supported_brands/slide.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10287 Update glance.markdown
  source/_lovelace/glance.markdown
Labels: has-parent, next

#10291 typo in persistent_notification.markdown
  source/_components/persistent_notification.markdown
Labels: current, ready-for-review, spelling

#10284 Add config flow to linky
  source/_components/linky.markdown
Labels: has-parent, new-feature, next, parent-merged

#10097 Updates pi_hole component documentation
  source/_components/pi_hole.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#10294 UpCloud URL tweaks
  source/_components/upcloud.markdown
Labels: next

#10237 Update device_sun_light_trigger.markdown - add person
  source/_components/device_sun_light_trigger.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10301 Correct grammar and improve clarity
  source/_docs/ecosystem/hass-configurator.markdown
Labels: current

#10242 Add info about nightlight switch
  source/_components/yeelight.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10298 fixed templates
  source/_components/template.markdown
Labels: bug, current

#10196 Update tellstick.markdown
  source/_components/tellstick.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10211 Add ViCare component documentation
  source/_components/vicare.markdown
  source/images/supported_brands/viessmann.png
Labels: has-parent, new-integration, next, parent-merged

#10113 Updated documentation for hostname template
  source/_components/xiaomi.markdown
Labels: has-parent, next, parent-merged

#10319 Fix example spacing
  source/_components/iss.markdown
Labels: current, formatting, ready-for-review

#10256 Solaredge documentation for #26282
  source/_components/solaredge.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10231 Updates docs for Jewish calendar
  source/_components/jewish_calendar.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10189 Add vivotek.markdown
  source/_components/vivotek.markdown
  source/images/supported_brands/vivotek.jpg
Labels: has-parent, new-integration, next

#8816 Adding withings sensor platform documentation.
  source/_components/withings.markdown
  source/images/supported_brands/withings.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10248 Add documentation for new yeelight services
  source/_components/yeelight.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10172 Added doc for Atome sensor
  source/_components/atome.markdown
  source/images/supported_brands/total_direct_energie.png
Labels: has-parent, new-integration, next, parent-merged

#10321 Update attribute names for statistics sensor
  source/_components/statistics.markdown
Labels: current, enhancement, ready-for-review

#10327 Streamline securing page
  source/_docs/configuration/securing.markdown
Labels: current, enhancement, ready-for-review

#10325 Add HmIP-SPDR
  source/_components/homematicip_cloud.markdown
Labels: has-parent, next, parent-merged

#10330 Update glance.markdown
  source/_lovelace/glance.markdown
Labels: has-parent, next

#10165 Add documentation for Jandy iAqualink component.
  source/_components/iaqualink.markdown
  source/images/supported_brands/iaqualink.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#10032 Added documentation for growatt server integration.
  source/_components/growatt_server.markdown
  source/images/supported_brands/growatt.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10334 Document sensor platform for iaqualink integration
  source/_components/iaqualink.markdown
Labels: has-parent, next, parent-merged

#10297 Plex remove username/password/servername
  source/_components/plex.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#10303 Plex add media_player server config
  source/_components/plex.markdown
Labels: has-parent, next, parent-merged

#10333 Correct discord notification service call example
  source/_components/discord.markdown
Labels: current, enhancement

#10316 Corrected example and scan interval info
  source/_components/switch.modbus.markdown
Labels: current, enhancement, ready-for-review

#10332 Fix example in Template Cover considerations
  source/_components/cover.template.markdown
Labels: current, enhancement, ready-for-review

#10331 fix hmip script name
  source/_components/homematicip_cloud.markdown
Labels: current, enhancement, ready-for-review

#10322 Updating confusing/incorrect information
  source/_components/meteoalarm.markdown
Labels: current, enhancement, ready-for-review

#10328 Plex common config
  source/_components/plex.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10340 Add password for upc connect
  source/_components/upc_connect.markdown
Labels: has-parent, new-feature, next

#10335 Document switch platform for iaqualink integration
  source/_components/iaqualink.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10324 Add Obihai Integration
  source/_components/obihai.markdown
  source/images/supported_brands/obitalk.png
Labels: awaits-parent, has-parent, new-integration, next

#10342 Plex config changes
  source/_components/plex.markdown
Labels: has-parent, next, parent-merged

#10341 Fix NM
  source/hassio/installation.markdown
Labels: current

#10228 Added doods component documentation
  source/_components/doods.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10346 Update ha_release
  source/_components/doods.markdown
Labels: next

#10345 UniFi - Remove references to legacy configuration method
  source/_components/unifi.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10358 ✏️ Fix Binary Sensor category problem
  source/_components/updater.markdown
Labels: current, enhancement, ready-for-review

#10357 The lack of reload is gone
  source/_docs/configuration/packages.markdown
Labels: current, enhancement, ready-for-review

#10360 Update controllers.markdown
  source/_docs/z-wave/controllers.markdown
Labels: current, enhancement

#10351 Update bluetooth_le_tracker.markdown
  source/_components/bluetooth_le_tracker.markdown
Labels: current, enhancement

#10354 Document binary_sensor platform for iaqualink integration
  source/_components/iaqualink.markdown
Labels: has-parent, next, parent-merged

#10363 Fix typo in installation.markdown
  source/hassio/installation.markdown
Labels: current, spelling

#10362 Correct the example on templates
  source/_components/template.markdown
Labels: current, enhancement

#10353 Use inverted commas for a number in a string
  source/_components/tuya.markdown
Labels: current, enhancement

#10352 Clarify Plex config options
  source/_components/plex.markdown
Labels: enhancement, next

#10367 Include port number in 'adb connect' command
  source/_components/androidtv.markdown
Labels: current, enhancement, ready-for-review

#10300 Change nzbget to full component
  source/_components/nzbget.markdown
Labels: has-parent, new-feature, next, parent-merged

#10371 adds missing headings
  source/_docs/tools/dev-tools.markdown
Labels: current, enhancement, ready-for-review

#10378 Enphase envoy Add optional name field
  source/_components/enphase_envoy.markdown
Labels: has-parent, new-feature, next, parent-merged

#10379 Update onkyo.markdown
  source/_components/onkyo.markdown
Labels: current, enhancement, ready-for-review

#10361 List of expected sensors and their states for Obihai
  source/_components/obihai.markdown
Labels: has-parent, next, parent-merged

#10365 Add icon_code sensor to Environment Canada
  source/_components/environment_canada.markdown
Labels: has-parent, next, parent-merged

#10286 Add options to badges
  source/lovelace/views.markdown
Labels: has-parent, new-feature, next, parent-merged

#10388 Fix typo
  source/_posts/2019-09-18-release-99.markdown
Labels: rc, spelling

#10387 Fix incorrect warning
  source/_addons/mosquitto.markdown
Labels: current

#10344 Update changelog.markdown
  source/lovelace/changelog.markdown
Labels: next

#10339 Add Home Assistant Cast service docs
  source/_components/cast.markdown
  source/_posts/2019-08-06-home-assistant-cast.markdown
Labels: has-parent, new-feature, next

#10394 wrong example config (older)
  source/_components/pi_hole.markdown
Labels: current, enhancement

#10401 Minor grammar fix.
  source/_components/google_translate.markdown
Labels: current, ready-for-review, spelling

#10389 Update Plex for config flow
  source/_components/plex.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10385 Document port number
  source/_components/solax.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10406 Additions, removals, and update
  source/_data/glossary.yml
Labels: current, enhancement, ready-for-review

#10397 Update bmw_connected_drive.markdown
  source/_components/bmw_connected_drive.markdown
Labels: current, enhancement, ready-for-review

#10405 Update changes to whitelisting local ips
  source/_components/wirelesstag.markdown
Labels: current, enhancement

#10404 Additional troubleshooting for Google Assistant
  source/_components/google_assistant.markdown
Labels: current, enhancement, ready-for-review

#10396 Clarify differences between user and admin accounts for Obihai
  source/_components/obihai.markdown
Labels: current, enhancement, ready-for-review

#10402 correct templating example
  source/_components/light.template.markdown
Labels: current

#10408 Correct jewish_calendar full configuration example
  source/_components/jewish_calendar.markdown
Labels: current, enhancement

#10409 Fixing the indenting
  source/_components/plex.markdown
Labels: current, enhancement

#10203 Add documentation for expire_after configuration
  source/_components/binary_sensor.mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10375 adding documentation for the yandex_transport component
  source/_components/yandex_transport.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#9635 Docs for iZone component.
  source/_components/pizone.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10296 Fix spaceapi
  source/_components/spaceapi.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10418 Match cheatsheet version with package currently used
  source/_docs/configuration/customizing-devices.markdown
Labels: current, has-parent

#10424 Add details about ping
  source/_components/wake_on_lan.markdown
Labels: current

#10415 Update pi_hole docs for 0.99
  source/_components/pi_hole.markdown
Labels: current, enhancement, has-parent

#10426 Update commandline.markdown
  source/hassio/commandline.markdown
Labels: current, enhancement

#10373 Update tradfri.markdown
  source/_components/tradfri.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10412 Plex manual config flow
  source/_components/plex.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10431 Corrected math in description of twilight.
  source/_docs/automation/trigger.markdown
Labels: current, enhancement

#10400 Add Ombi integration
  source/_components/ombi.markdown
  source/images/supported_brands/ombi.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#10374 Add Kaiterra integration
  source/_components/kaiterra.markdown
  source/images/supported_brands/kaiterra.svg
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10433 Changed syntax to eliminate error
  source/_components/opengarage.markdown
Labels: current, enhancement

#10425 Remove deprecated srp_energy integration (ADR-0004)
  source/_components/srp_energy.markdown
  source/_posts/2018-11-28-release-83.markdown
  source/_posts/2019-04-03-release-91.markdown
  source/_posts/2019-08-28-release-98.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10419 Remove deprecated sytadin integration (ADR-0004)
  source/_components/sytadin.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2018-08-03-release-75.markdown
  source/_posts/2018-08-29-release-77.markdown
  source/_posts/2019-07-17-release-96.markdown
  source/_posts/2019-08-28-release-98.markdown
  source/images/supported_brands/sytadin.png
Labels: has-parent, next, parent-merged, ready-for-review

#10413 add url action
  source/_lovelace/entity-button.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
  source/_lovelace/picture.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10439 Update daikin.markdown
  source/_components/daikin.markdown
Labels: current

#10441 Add details about iFrame
  source/_components/waze_travel_time.markdown
Labels: current

#10445 Adds key codes to emulated Roku documentation
  source/_components/emulated_roku.markdown
Labels: current, enhancement

#10444 Update vesync.markdown
  source/_components/vesync.markdown
Labels: current, enhancement

#10453 Clarity on enabling MQTT TLS
  source/_docs/mqtt/certificate.markdown
Labels: current

#10434 Remove deprecated linksys_ap integration (ADR-0004)
  source/_components/linksys_ap.markdown
  source/_posts/2017-01-28-face-coffee-wink.markdown
  source/_posts/2017-05-20-automation-editor-zwave-panel-ocr.markdown
  source/_posts/2017-12-03-release-59.markdown
  source/_posts/2019-08-28-release-98.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10250 Add Alarm Control Panel to secure devices
  source/_components/google_assistant.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#9648 Add documentation for here_travel_time
  source/_components/here_travel_time.markdown
  source/images/supported_brands/HERE_logo.svg
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10308 Added 'availability_template' to Template Sensor platform
  source/_components/template.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10423 Remove deprecated ups integration (ADR-0004)
  source/_components/ups.markdown
  source/_posts/2017-02-25-config-panel-and-state-restoration.markdown
  source/_posts/2017-04-22-ikea-tradfri--spotify.markdown
  source/_posts/2017-06-17-release-47.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-10-07-release-55.markdown
  source/_posts/2019-08-28-release-98.markdown
  source/images/supported_brands/ups.png
Labels: has-parent, next, parent-merged, ready-for-review

#10349 Expand entity-filter options
  source/_lovelace/entity-filter.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10422 Remove deprecated usps integration (ADR-0004)
  source/_components/usps.markdown
  source/_posts/2017-01-14-iss-usps-images-packages.markdown
  source/_posts/2017-04-22-ikea-tradfri--spotify.markdown
  source/_posts/2017-06-04-release-46.markdown
  source/_posts/2017-06-17-release-47.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/_posts/2017-10-07-release-55.markdown
  source/_posts/2018-02-26-release-64.markdown
  source/_posts/2019-08-28-release-98.markdown
  source/images/supported_brands/usps.png
Labels: has-parent, next, parent-merged, ready-for-review

#10420 Remove deprecated fedex integration (ADR-0004)
  source/_components/fedex.markdown
  source/_posts/2017-02-25-config-panel-and-state-restoration.markdown
  source/_posts/2017-04-22-ikea-tradfri--spotify.markdown
  source/_posts/2017-06-04-release-46.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/_posts/2017-10-07-release-55.markdown
  source/_posts/2018-02-26-release-64.markdown
  source/_posts/2019-08-28-release-98.markdown
  source/images/supported_brands/fedex.png
Labels: has-parent, next, parent-merged, ready-for-review

#10448 update locative.md
  source/_components/locative.md
Labels: current, enhancement, ready-for-review

#10449 Update emulated_hue.markdown
  source/_components/emulated_hue.markdown
Labels: current, enhancement, ready-for-review

#10437 Add a way to retrieve battery level via HTTP
  source/_cookbook/track_battery_level.markdown
Labels: current, enhancement, ready-for-review

#10399 Newer Alexa devices require port 80
  source/_components/emulated_hue.markdown
Labels: current, enhancement, ready-for-review

#10428 Update ecobee to include config flow instructions
  source/_components/ecobee.markdown
Labels: has-parent, new-feature, next, parent-merged

#10450 Describe Plex config options
  source/_components/plex.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10466 Correct Port 4685 to 4865
  source/_components/pi_hole.markdown
Labels: current, enhancement, ready-for-review

#10398 Added more ebusd sensors.
  source/_components/ebusd.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10461 Clarified the behavior of conditions.
  source/_docs/automation/condition.markdown
  source/_docs/scripts/conditions.markdown
Labels: current, enhancement

#10468 Update homekit.markdown
  source/_components/homekit.markdown
Labels: current, spelling

#10314 Added 'availability_template' to Template Cover platform
  source/_components/cover.template.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10313 Added 'availability_template' to Template Binary Sensor platform
  source/_components/binary_sensor.template.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10312 Added 'availability_template' to all Template Fan platform
  source/_components/fan.template.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10311 Added 'availability_template' to all Template Light platform
  source/_components/light.template.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10309 Added 'availability_template' to Template Vacuum platform
  source/_components/vacuum.template.markdown
Labels: awaits-parent, has-parent, new-feature, next

#10470 Add hint about Homematic IP device create and remove
  source/_components/homematicip_cloud.markdown
Labels: has-parent, next, parent-merged

#10475 Adds GitHub Action for Remark, fixes code flag on fences
  .github/workflows/markdown.yml
  .nvmrc
  .remarkrc.js
  LICENSE.md
  package-lock.json
  package.json
  source/_addons/snips.markdown
  source/_components/binary_sensor.mqtt.markdown
  source/_components/bom.markdown
  source/_components/command_line.markdown
  source/_components/envirophat.markdown
  source/_components/fail2ban.markdown
  source/_components/ffmpeg.markdown
  source/_components/foursquare.markdown
  source/_components/habitica.markdown
  source/_components/hyperion.markdown
  source/_components/knx.markdown
  source/_components/lcn.markdown
  source/_components/meteoalarm.markdown
  source/_components/mystrom.markdown
  source/_components/orangepi_gpio.markdown
  source/_components/plex.markdown
  source/_components/recorder.markdown
  source/_components/roku.markdown
  source/_components/route53.markdown
  source/_components/tikteck.markdown
  source/_components/ubus.markdown
  source/_components/vacuum.mqtt.markdown
  source/_components/vizio.markdown
  source/_cookbook/sonos_say.markdown
  source/_docs/authentication/providers.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/configuration/yaml.markdown
  source/_docs/ecosystem/appdaemon/running.markdown
  source/_docs/ecosystem/backup/backup_dropbox.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/ecosystem/ios/notifications/sounds.markdown
  source/_docs/installation/centos.markdown
  source/_docs/installation/virtualenv.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/mqtt/discovery.markdown
  source/_docs/z-wave/installation.markdown
  source/_posts/2017-02-04-babyphone.markdown
  source/_posts/2017-03-22-broken-dependencies.markdown
  source/_posts/2017-04-25-influxdb-grafana-docker.markdown
  source/_posts/2017-05-01-home-assistant-on-raspberry-pi-zero-in-30-minutes.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-09-09-release-53.markdown
  source/_posts/2017-09-25-new-hassio-build-system.markdown
  source/_posts/2017-11-10-ttn-with-mqtt.markdown
  source/_posts/2017-11-18-release-58.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2019-05-16-release-93.markdown
  source/_posts/2019-06-05-release-94.markdown
  source/developers/cla.markdown
  source/developers/license.markdown
  source/hassio/enable_i2c.markdown
  source/hassio/zwave.markdown
Labels: current, enhancement, ready-for-review

#10479 Add white line to comply with markdown rules.
  source/_components/homematicip_cloud.markdown
Labels: next

#10477 No dollar signs in shell code
  .remarkrc.js
  package-lock.json
  package.json
  source/_components/bluetooth_le_tracker.markdown
  source/_components/eddystone_temperature.markdown
  source/_components/ffmpeg.markdown
  source/_components/hdmi_cec.markdown
  source/_components/pandora.markdown
  source/_components/recorder.markdown
  source/_components/samsungtv.markdown
  source/_components/seven_segments.markdown
  source/_components/snips.markdown
  source/_cookbook/fail2ban.markdown
  source/_cookbook/owntracks_two_mqtt_broker.markdown
  source/_docs/asterisk_mbox.markdown
  source/_docs/autostart/upstart.markdown
  source/_docs/ecosystem/backup/backup_dropbox.markdown
  source/_docs/ecosystem/backup/backup_github.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/ecosystem/certificates/tls_domain_certificate.markdown
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
  source/_docs/ecosystem/nginx.markdown
  source/_docs/installation/armbian.markdown
  source/_docs/installation/centos.markdown
  source/_docs/installation/fedora.markdown
  source/_docs/installation/hassbian.markdown
  source/_docs/installation/hassbian/common-tasks.markdown
  source/_docs/installation/hassbian/upgrading.markdown
  source/_docs/installation/macos.markdown
  source/_docs/installation/python.markdown
  source/_docs/installation/raspberry-pi.markdown
  source/_docs/installation/troubleshooting.markdown
  source/_docs/installation/virtualenv.markdown
  source/_docs/z-wave/installation.markdown
  source/_posts/2015-09-18-monitoring-with-glances-and-home-assistant.markdown
  source/_posts/2015-12-07-influxdb-and-grafana.markdown
  source/_posts/2016-07-06-pocketchip-running-home-assistant.markdown
  source/_posts/2016-07-16-sqlalchemy-knx-join-simplisafe.markdown
  source/_posts/2017-02-03-hassbian-toybox.markdown
  source/_posts/2017-02-04-babyphone.markdown
  source/_posts/2017-05-01-home-assistant-on-raspberry-pi-zero-in-30-minutes.markdown
  source/_posts/2018-03-29-fedora-atomic.markdown
  source/hassio/commandline.markdown
Labels: current, ready-for-review
