Repository home-assistant/home-assistant.io, pull requests merged in 2019-10, with the labels that each got.

#10507 Update ubee.markdown
  source/_components/ubee.markdown
Labels: Hacktoberfest, bug, current

#10508 Update spaceapi.markdown
  source/_components/spaceapi.markdown
Labels: Hacktoberfest, bug, current

#10460 Added documentation page for Soma
  source/_components/soma.markdown
  source/images/supported_brands/soma.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#10520 Fix notebook link
  source/_docs/ecosystem/notebooks/installation.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10521 Fixes mailto link for Security email
  source/security/index.markdown
Labels: Hacktoberfest, bug, current

#10442 state_filter for picture cards
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10447 add more providers, update yessssms docs for YesssSMS v0.4.1
  source/_components/yessssms.markdown
  source/images/screenshots/yessssms_brands.png
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10293 Transmission config flow
  source/_components/transmission.markdown
Labels: has-parent, new-feature, next, parent-merged

#10457 ecobee: Add services to create and delete vacations
  source/_components/ecobee.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10326 New version of rainbird component
  source/_components/rainbird.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#10474 Add Hive Services
  source/_components/hive.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10516 Rename page/file for Generic IP camera
  source/_components/generic_ip_camera.markdown
  source/_posts/2019-04-03-release-91.markdown
  source/_redirects
Labels: Hacktoberfest, current, enhancement

#10523 Fixes code fencing in DeConz documentation
  source/_components/deconz.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10524 Updated head.html with Accessibility improvements
  source/_includes/site/head.html
Labels: Hacktoberfest, current, enhancement

#10494 minor tweaks to incomfort docs
  source/_components/incomfort.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#10525 Fixed broken link components/ubee/
  source/_components/ubee.markdown
Labels: Hacktoberfest, bug, current

#10527 Minor corrections to Android TV documentation
  source/_components/androidtv.markdown
Labels: Hacktoberfest, enhancement, has-parent, next

#10528 Update Weather Forecast screenshot (fixes #10290)
  source/images/lovelace/lovelace_weather.png
Labels: Hacktoberfest, current, enhancement

#10455 Add saj component to docs
  source/_components/saj.markdown
  source/images/supported_brands/saj.png
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#10534 Update stats.markdown
  source/_docs/ecosystem/notebooks/stats.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10533 Update graph.markdown
  source/_docs/ecosystem/notebooks/graph.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10454 Adding NZBGet queue control services
  source/_integrations/nzbget.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10543 Creates redirect for /components -> /integrations
  source/_redirects
Labels: Hacktoberfest, bug, current

#10542 Update slightly outdated Dev Tools instructions
  source/_docs/scripts/service-calls.markdown
Labels: Hacktoberfest, current

#10536 Update entities.markdown
  source/_lovelace/entities.markdown
Labels: Hacktoberfest, current

#10545 Bring up to date with Developer Tools changes
  source/_docs/configuration/customizing-devices.markdown
Labels: Hacktoberfest, current

#10541 Update counter instructions for Dev Tools redesign in 0.96
  source/_integrations/counter.markdown
Labels: Hacktoberfest, current

#10549 Fixes images folder name for integrations
  source/images/integrations/alexa/account_linking.png
  source/images/integrations/alexa/alexa-108x108.png
  source/images/integrations/alexa/alexa-512x512.png
  source/images/integrations/alexa/create_a_new_skill.png
  source/images/integrations/alexa/create_iam_role_attach_permission.png
  source/images/integrations/alexa/lambda_function_env_var.png
  source/images/integrations/alexa/scene_slot.png
  source/images/integrations/alexa/scene_slot_synonyms.png
  source/images/integrations/alexa/script_slot.png
  source/images/integrations/apple_tv/auth_pin.jpg
  source/images/integrations/apple_tv/auth_start.jpg
  source/images/integrations/apple_tv/authenticate.png
  source/images/integrations/apple_tv/credentials.png
  source/images/integrations/apple_tv/scan_result.jpg
  source/images/integrations/apple_tv/scan_start.jpg
  source/images/integrations/automation/logbook.png
  source/images/integrations/calendar/todoist-108x108.png
  source/images/integrations/calendar/todoist-512x512.png
  source/images/integrations/camera/generic-google-maps.png
  source/images/integrations/camera/preload-stream.png
  source/images/integrations/cisco_webex_teams/rich_formatting.png
  source/images/integrations/flock/flock-webhook.png
  source/images/integrations/flock/new-webhook.png
  source/images/integrations/free_mobile/token.png
  source/images/integrations/garadget/cover_garadget_details.png
  source/images/integrations/google_assistant/accountlinking.png
  source/images/integrations/gpslogger/custom-url.png
  source/images/integrations/gpslogger/logging-details.png
  source/images/integrations/gpslogger/performance.png
  source/images/integrations/gpslogger/settings.png
  source/images/integrations/haveibeenpwned/sensor.png
  source/images/integrations/ifttt/IFTTT_manything_trigger.png
  source/images/integrations/ifttt/finding_key.png
  source/images/integrations/ifttt/setup_service.png
  source/images/integrations/ifttt/setup_trigger.png
  source/images/integrations/ifttt/testing_service.png
  source/images/integrations/light/group.png
  source/images/integrations/mystrom/switch-advanced.png
  source/images/integrations/netdata/details.png
  source/images/integrations/opengarage/cover_opengarage_details.jpg
  source/images/integrations/pyload/pyload_speed.png
  source/images/integrations/rfxtrx/sensor.png
  source/images/integrations/rfxtrx/switch.png
  source/images/integrations/thethingsnetwork/access_key.png
  source/images/integrations/thethingsnetwork/add_integration.png
  source/images/integrations/thethingsnetwork/applications.png
  source/images/integrations/thethingsnetwork/choose_integration.png
  source/images/integrations/thethingsnetwork/confirm_integration.png
  source/images/integrations/thethingsnetwork/devices.png
  source/images/integrations/thethingsnetwork/storage_integration.png
  source/images/integrations/transmission/transmission.png
  source/images/integrations/transmission/transmission_perf.png
  source/images/integrations/zestimate/zestimateexample.png
Labels: Hacktoberfest, bug, current

#10550 Fixes sidebar on integration pages
  source/_includes/site/sidebar.html
Labels: Hacktoberfest, bug, current

#10544 📚Fixing broken URL's
  source/_cookbook/google_maps_card.markdown
  source/_integrations/aquostv.markdown
  source/_integrations/panasonic_bluray.markdown
Labels: Hacktoberfest, bug, current, ready-for-review

#10558 Broken link fix for alexa.flash_briefings.markdown
  source/_integrations/alexa.flash_briefings.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10557 Broken link fix for htu21d.markdown
  source/_integrations/htu21d.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10556 Broken link fix for 2017-01-18-numbers.markdown
  source/_posts/2017-01-18-numbers.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10307 Added 'availability_template' to all Template Lock platform
  source/_integrations/lock.template.markdown
Labels: awaits-parent, has-parent, in-progress, new-feature, next, parent-merged

#10462 Plex external auth description
  source/_integrations/plex.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged, ready-for-review

#10548 neural engine to polly
  source/_integrations/amazon_polly.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged, ready-for-review

#10498 add actions to picture-glance entities
  source/_lovelace/picture-glance.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged, ready-for-review

#10532 Update automation_sun.markdown
  source/_cookbook/automation_sun.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10535 Fixes link to Asterisk Voicemail page
  source/_integrations/mailbox.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10537 Add info about call direction sensor
  source/_integrations/obihai.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged

#10540 Update Lutron Caseta documentation
  source/_integrations/lutron_caseta.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10546 📚Update pushbullet link in /configuration/yaml, fix linting errors
  source/_docs/configuration/yaml.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10551 Fix broken link Elgato Avea
  source/_integrations/avea.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10554 Fix broken link 2016-04-04-your-hub-should-be-local-and-open.markdown
  source/_posts/2016-04-04-your-hub-should-be-local-and-open.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10555 Broken links fix for tellstick.markdown
  source/_addons/tellstick.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10564 Fix typo from #10485
  source/_integrations/pi_hole.markdown
Labels: Hacktoberfest, has-parent, next, spelling

#10552 Added discontinue note like with Hipchat
  source/_integrations/stride.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10538 Changed broken link to Mi Flora product page
  source/_integrations/miflora.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10561 Fix crimereports documentation
  source/_integrations/crimereports.markdown
Labels: Hacktoberfest, bug, current

#10573 Update link to firmware download
  source/_integrations/rflink.markdown
Labels: Hacktoberfest, bug, current

#10559 📚Update URL's with sensor in docs folder
  source/_docs/automation/editor.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/mqtt/discovery.markdown
  source/_docs/scripts/service-calls.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10562 🔗Update links in Samsung/Panasonic MD
  source/_integrations/panasonic_viera.markdown
  source/_integrations/samsungtv.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10575 Fixes GitHub source links on integration pages
  source/_includes/asides/component_navigation.html
Labels: Hacktoberfest, bug, current

#10567 Clarify netgear_lte SMS limits
  source/_integrations/netgear_lte.markdown
Labels: Hacktoberfest, current, enhancement, has-parent

#10563 Add documentation for action topic of MQTT HVAC
  source/_integrations/climate.mqtt.markdown
Labels: Hacktoberfest, current, has-parent, new-feature, parent-merged, ready-for-review

#10568 Clarify lifx_cloud usage
  source/_integrations/lifx_cloud.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10565 Update to reflect that Pi-hole is now an integration, not just a sensor
  source/_integrations/pi_hole.markdown
Labels: Hacktoberfest, has-parent, next, ready-for-review

#10569 Clarify Sonos manual configuration
  source/_integrations/sonos.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10570 Update Sonos introduction
  source/_integrations/sonos.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10571 Update google_assistant.markdown per new Google UI changes
  source/_integrations/google_assistant.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10443 update geniushub docs
  source/_integrations/geniushub.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#10576 Add link to white list documentation
  source/_integrations/transmission.markdown
Labels: Hacktoberfest, current, enhancement

#10577 Link correction to ESPHome API
  source/_integrations/esphome.markdown
Labels: Hacktoberfest, bug, current

#9771 Mosquitto 5.1 udpate
  source/_addons/mosquitto.markdown
Labels: has-parent, needs-rebase, new-feature, next, parent-merged, ready-for-review

#10572 deCONZ - Device triggers and how to request support for new ones
  source/_integrations/deconz.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10366 Allow code elements to wrap if necessary
  sass/custom/_paulus.scss
Labels: current, enhancement, ready-for-review

#10376 Improve header alignment and logo
  sass/custom/_paulus.scss
  sass/oscailte/base/_navigation.scss
  source/_includes/site/header.html
  source/images/home-assistant-logo.svg
Labels: current, enhancement, ready-for-review

#10414 Update ifttt.markdown
  source/_integrations/ifttt.markdown
Labels: current, enhancement, ready-for-review

#10465 Added link to Material Design Icons page
  source/lovelace/index.markdown
Labels: current, enhancement, in-progress

#10579 🔗 Fix broken links (part 6)
  source/_docs/automation/editor.markdown
  source/_docs/automation/trigger.markdown
  source/_docs/scripts/conditions.markdown
  source/_includes/custom/grid_item_left.html
  source/_posts/2016-10-02-hacktoberfest.markdown
  source/_posts/2017-09-29-hacktoberfest.markdown
  source/_posts/2018-02-10-release-63.markdown
  source/_posts/2018-04-14-release-67.markdown
  source/_posts/2018-06-10-release-71.markdown
  source/_posts/2018-09-30-hacktoberfest.markdown
  source/_posts/2019-03-13-release-89.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10578 KNX add new sensor type from xknx 0.11.2
  source/_integrations/sensor.knx.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next, parent-merged

#10368 emulated_hue note for sleep cycle and sleep as android
  source/_integrations/emulated_hue.markdown
Labels: has-parent, in-progress, new-feature, next

#10589 Update changelog.markdown
  source/lovelace/changelog.markdown
Labels: Hacktoberfest, has-parent, new-feature, next

#10592 Fix links to `device_class` for MQTT binary_sensor
  source/_integrations/binary_sensor.mqtt.markdown
Labels: Hacktoberfest, bug, current

#10594 alarmdecoder relay config is also used for zone expanders
  source/_integrations/alarmdecoder.markdown
Labels: has-parent, next, parent-merged

#10599 Nello Insolvency
  source/_integrations/nello.markdown
Labels: Hacktoberfest, current, enhancement

#10602 Add HMIP-SAM to Homematic IP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: has-parent, next, parent-merged

#10609 Update index.markdown
  source/lovelace/index.markdown
Labels: Hacktoberfest, current, enhancement

#10593 Fix links to `device_class` for MQTT sensor
  source/_integrations/sensor.mqtt.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10600 Fix links in 4 blog posts
  source/_posts/2016-01-29-insteon-lifx-twitter-and-zigbee.markdown
  source/_posts/2017-06-20-things-you-should-know-about-senic-covi.markdown
  source/_posts/2017-11-05-frontend-translations.markdown
  source/_posts/2019-02-04-introducing-home-assistant-cli.markdown
Labels: Hacktoberfest, bug, current

#10285 Add Airly documentation
  source/_components/airly.markdown
  source/images/supported_brands/airly.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#10598 Clarify the behavior of the updater component
  source/_integrations/updater.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10601 Add frontend release notes
  source/_posts/2019-10-09-release-100.markdown
Labels: rc

#10607 Add trv support
  source/_integrations/hive.markdown
Labels: has-parent, new-feature, next, parent-merged

#10618 icon configuration variable: unification
  source/_integrations/input_boolean.markdown
  source/_integrations/input_datetime.markdown
  source/_integrations/input_number.markdown
  source/_integrations/input_select.markdown
  source/_integrations/input_text.markdown
Labels: Hacktoberfest, current

#10603 Update zwave devices page
  source/_docs/z-wave/devices.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#10620 Fixes GitHub repository link
  plugins/environment_variables.rb
  source/_integrations/dialogflow.markdown
  source/_integrations/samsungtv.markdown
  source/_posts/2016-10-02-hacktoberfest.markdown
  source/_posts/2016-10-22-flash-briefing-updater-hacktoberfest.markdown
  source/_posts/2017-02-25-config-panel-and-state-restoration.markdown
  source/_posts/2017-09-29-hacktoberfest.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/cookbook/index.markdown
Labels: Hacktoberfest, current

#10629 Adding more to the glossary
  source/_data/glossary.yml
Labels: Hacktoberfest, current

#10626 Update switch documentation for all entities
  source/_integrations/switch.markdown
Labels: Hacktoberfest, current, has-parent

#10617 Fix broken links
  source/_docs/scripts/conditions.markdown
  source/_integrations/configurator.markdown
  source/_integrations/light.markdown
  source/_integrations/todoist.markdown
Labels: Hacktoberfest, current

#10638 fix link
  source/_docs/mqtt/broker.markdown
Labels: Hacktoberfest, current

#10640 fix link
  source/_integrations/configurator.markdown
Labels: Hacktoberfest, current

#10639 Fix the plural in titles
  source/_integrations/light.markdown
  source/_integrations/switch.markdown
Labels: Hacktoberfest, current

#10641 Update google_maps.markdown
  source/_integrations/google_maps.markdown
Labels: Hacktoberfest, current

#10636 🔗 Fix broken links (part 7)
  source/_posts/2016-02-28-steam-d-link-smart-plugs-and-neurio-energy-sensors.markdown
  source/_posts/2016-05-21-release-020.markdown
  source/_posts/2016-09-29-async-sleepiq-emoncms-stocks.markdown
  source/_posts/2017-01-14-iss-usps-images-packages.markdown
  source/_posts/2017-05-20-automation-editor-zwave-panel-ocr.markdown
  source/_posts/2017-06-04-release-46.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-08-12-release-51.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/_posts/2017-09-09-release-53.markdown
  source/_posts/2017-10-07-release-55.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2018-02-10-release-63.markdown
  source/_posts/2018-03-09-release-65.markdown
  source/_posts/2018-04-14-release-67.markdown
  source/_posts/2018-05-11-release-69.markdown
  source/_posts/2018-05-18-release-70.markdown
  source/_posts/2018-06-22-release-72.markdown
  source/_posts/2018-07-06-release-73.markdown
  source/_posts/2018-07-16-release-73-2.markdown
  source/_posts/2018-07-21-release-74.markdown
  source/_posts/2018-08-03-release-75.markdown
  source/_posts/2018-08-29-release-77.markdown
  source/_posts/2018-10-12-release-80.markdown
  source/_posts/2018-11-28-release-83.markdown
  source/_posts/2019-01-09-release-85.markdown
  source/_posts/2019-02-20-release-88.markdown
  source/_posts/2019-04-24-release-92.markdown
  source/_posts/2019-08-28-release-98.markdown
Labels: Hacktoberfest, current

#10635 Bump Python version in Travis CI example
  source/_docs/ecosystem/backup/backup_github.markdown
Labels: Hacktoberfest, current

#10611 Update SolarEdge_local documentation
  source/_integrations/solaredge_local.markdown
Labels: Hacktoberfest, current, ready-for-review

#10356 Neato config flow
  source/_integrations/neato.markdown
Labels: has-parent, new-feature, next, parent-merged

#10633 Require the entity_id for all Xiaomi miIO services
  source/_integrations/fan.xiaomi_miio.markdown
  source/_integrations/light.xiaomi_miio.markdown
  source/_integrations/switch.xiaomi_miio.markdown
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: Hacktoberfest, current, has-parent

#10647 clarify how the advanced options need to be added
  source/_integrations/life360.markdown
Labels: Hacktoberfest, current

#10646 Added links to Anthem products
  source/_integrations/anthemav.markdown
Labels: Hacktoberfest, current, ready-for-review

#10645 Added links to receivers
  source/_integrations/yamaha.markdown
Labels: Hacktoberfest, current, ready-for-review

#10644 speedtest port 8080
  source/_integrations/speedtestdotnet.markdown
Labels: Hacktoberfest, current, ready-for-review

#10628 Add Netlify header control to improve CouldFlare caching behavior
  _config.yml
  source/_headers
  source/_includes/javascripts/scripts.html
  source/_includes/site/head.html
Labels: Hacktoberfest, current, ready-for-review

#10652 Add neato battery sensor docs
  source/_integrations/neato.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#10655 Remove Plex manual config flow
  source/_integrations/plex.markdown
Labels: Hacktoberfest, has-parent, next

#10619 Update instructions for using Check Config Tool
  source/_docs/automation/troubleshooting.markdown
  source/_integrations/withings.markdown
  source/getting-started/configuration.markdown
Labels: Hacktoberfest, current, ready-for-review

#10659 Added note for users of earlier versions than 0.97
  source/_integrations/google_maps.markdown
Labels: Hacktoberfest, current

#10663 Update with working instructions
  source/_docs/installation/freenas.markdown
Labels: Hacktoberfest, current

#10664 Airly move
  source/_integrations/airly.markdown
Labels: Hacktoberfest, next

#10657 Add scene apply docs
  source/_integrations/scene.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next

#10666 Update frontend release notes
  source/_posts/2019-10-09-release-100.markdown
Labels: Hacktoberfest, rc

#10670 Add descriptions to breaking changes
  source/_posts/2019-10-09-release-100.markdown
Labels: Hacktoberfest, rc

#10671 Removed reference to input_slider
  source/_integrations/input_number.markdown
Labels: Hacktoberfest, current

#10669 Fixed generic.camera links #10491
  source/_posts/2018-05-18-release-70.markdown
  source/_posts/2018-07-16-release-73-2.markdown
  source/_posts/2018-08-29-release-77.markdown
  source/_posts/2019-03-20-release-90.markdown
Labels: Hacktoberfest, current

#10612 Update link to speedtestservers
  source/_integrations/speedtestdotnet.markdown
Labels: Hacktoberfest, current

#10673 Hint that problems with °-symbol is caused by configuration not saved as UTF-8
  source/_integrations/sensor.command_line.markdown
Labels: Hacktoberfest, current

#10674 Update troubleshooting.markdown
  source/_docs/configuration/troubleshooting.markdown
Labels: Hacktoberfest, current

#10672 Clarity edit
  source/_integrations/input_number.markdown
Labels: Hacktoberfest, current

#10658 Hostname updated
  source/_addons/mariadb.markdown
Labels: Hacktoberfest, current

#10683 🚑 Referrer-Policy: no-referrer-when-downgrade, fix s-maxage
  source/_headers
Labels: Hacktoberfest, bug, current

#10681 Update microsoft.markdown
  source/_integrations/microsoft.markdown
Labels: Hacktoberfest, current

#10677 Small documentation fix for history_graph
  source/_integrations/history_graph.markdown
Labels: Hacktoberfest, current

#10676 Correct minor grammar/clarity issues
  source/_integrations/adguard.markdown
Labels: Hacktoberfest, current

#10682 small changes to Google Calendar - Prerequisites instructions
  source/_integrations/calendar.google.markdown
Labels: Hacktoberfest, current

#10679 Removed missing link, updated future to past tense
  source/_integrations/hipchat.markdown
Labels: Hacktoberfest, next

#10610 CentOS boot script update
  source/_docs/installation/centos.markdown
Labels: Hacktoberfest, current

#10685 Revert "Small documentation fix for history_graph"
  source/_integrations/history_graph.markdown
Labels: Hacktoberfest, current

#10688 Inserted a note about using the correct TLD
  source/_integrations/google_maps.markdown
Labels: Hacktoberfest, current

#10686 Sorted yaml for automation
  source/_integrations/ifttt.markdown
Labels: Hacktoberfest, current

#10687 Grammar updates
  source/_integrations/waze_travel_time.markdown
Labels: Hacktoberfest, current

#10693 Correct minor grammar issues and improve clarity
  source/_integrations/hue.markdown
Labels: Hacktoberfest, current

#10692 Remove hipchat
  source/_integrations/hipchat.markdown
  source/_redirects
  source/images/supported_brands/hipchat.png
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#10690 Add heading
  source/_integrations/google_maps.markdown
Labels: Hacktoberfest, current

#10695 Update updater.markdown
  source/_integrations/updater.markdown
Labels: Hacktoberfest, current

#10694 Improve clarity and correct minor grammar issues
  source/_integrations/tradfri.markdown
Labels: Hacktoberfest, current

#10675 Correct some minor typos
  source/_integrations/ecobee.markdown
Labels: Hacktoberfest, current

#10701 Reddit integration doesn't support two-factor auth
  source/_integrations/reddit.markdown
Labels: Hacktoberfest, current

#10702 Improve clarity and add a note
  source/_integrations/homekit_controller.markdown
Labels: Hacktoberfest, current

#10700 Remove hydroquebec integration (ADR-0004)
  source/_integrations/hydroquebec.markdown
  source/_posts/2017-01-14-iss-usps-images-packages.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-07-29-release-50.markdown
  source/_posts/2017-11-18-release-58.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2018-04-14-release-67.markdown
  source/_posts/2018-04-27-release-68.markdown
  source/_posts/2018-07-16-release-73-2.markdown
  source/_redirects
  source/images/supported_brands/hydroquebec.svg
Labels: Hacktoberfest, has-parent, next, parent-merged

#10463 Add documentation about new key: time_format
  source/_integrations/jewish_calendar.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10616 document scene action for scripts (#27223)
  source/_docs/scripts.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged, ready-for-review

#10708 Update bom.markdown
  source/_integrations/bom.markdown
Labels: Hacktoberfest, current

#10709 Update watson_iot.markdown
  source/_integrations/watson_iot.markdown
Labels: Hacktoberfest, current

#10706 Add info about images to Discord documentation
  source/_integrations/discord.markdown
Labels: Hacktoberfest, current, has-parent

#10512 add title option to stack cards
  source/_lovelace/horizontal-stack.markdown
  source/_lovelace/vertical-stack.markdown
Labels: Hacktoberfest, has-parent, in-progress, new-feature, next, parent-merged

#10717 fix_typo
  source/_integrations/yandex_transport.markdown
Labels: Hacktoberfest, next

#10719 Docs: Explain Markdown card renderer and supported specs
  source/_lovelace/markdown.markdown
Labels: Hacktoberfest, current

#10718 Update discogs.markdown
  source/_integrations/discogs.markdown
Labels: Hacktoberfest, current

#10723 Spelling fixes
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/ecosystem/synology.markdown
  source/_docs/security.markdown
  source/_docs/z-wave/device-specific.markdown
  source/_integrations/alexa.smart_home.markdown
  source/_integrations/aws.markdown
  source/_integrations/binary_sensor.template.markdown
  source/_integrations/hyperion.markdown
  source/_integrations/rejseplanen.markdown
  source/_integrations/waze_travel_time.markdown
  source/_integrations/yessssms.markdown
Labels: Hacktoberfest, current
