Repository home-assistant/home-assistant.io, pull requests merged in 2019-02, with the labels that each got.

#8363 Rename Etcher to balenaEtcher
  source/_docs/installation/hassbian/installation.markdown
  source/_posts/2017-05-01-home-assistant-on-raspberry-pi-zero-in-30-minutes.markdown
  source/_posts/2017-05-13-home-assistant-on-orange-pi-zero.markdown
  source/_posts/2018-07-11-hassio-images.markdown
  source/getting-started/index.markdown
  source/hassio/installation.markdown
Labels: current, enhancement, ready-for-review

#8369 Explicit scan_interval unit
  source/_components/sensor.airvisual.markdown
Labels: to-do

#8371 Add note that port should be HTTP port
  source/_components/camera.onvif.markdown
Labels: current, enhancement, ready-for-review

#8370 Update sensor.imap_email_content.markdown
  source/_components/sensor.imap_email_content.markdown
Labels: current, enhancement, ready-for-review

#8368 Remove unneeded configuration.yaml changes from locative
  source/_components/locative.md
Labels: ready-for-review

#8346 Change documentation for googlehome
  source/_components/device_tracker.googlehome.markdown
  source/_components/googlehome.markdown
Labels: awaits-parent, has-parent, new-feature, next

#7934 Add Huawei LTE Notify docs
  source/_components/notify.huawei_lte.markdown
Labels: has-parent, new-component, next, ready-for-review

#7200 RFLink devices documentation
  source/_components/binary_sensor.rflink.markdown
  source/_components/cover.rflink.markdown
  source/_components/light.rflink.markdown
  source/_components/sensor.rflink.markdown
  source/_components/switch.rflink.markdown
Labels: Hacktoberfest, current, enhancement, ready-for-review

#7352 Reorganise and fix some errors in the Templating docs.
  source/_docs/configuration/templating.markdown
Labels: current, enhancement, ready-for-review

#8024 Include an example for serial usage
  source/_components/elkm1.markdown
Labels: current, enhancement, ready-for-review

#8335 Update tellduslive.markdown
  source/_components/tellduslive.markdown
Labels: current, enhancement, ready-for-review

#8382 Wording tweak
  source/hassio/zwave.markdown
Labels: ready-for-review

#8375 Fix copy&paste error of raspyrfm docs that mixed up host and port
  source/_components/switch.raspyrfm.markdown
Labels: to-do

#8379 Fix platform links when using embedded components
  source/_includes/asides/component_navigation.html
Labels: next, ready-for-review

#8365 Add SmartThings Light platform
  source/_components/smartthings.light.markdown
  source/_components/smartthings.markdown
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#8386 fix some typos
  source/_components/emulated_roku.markdown
Labels: current, enhancement, ready-for-review

#8402 Update homekit.markdown
  source/_components/homekit.markdown
Labels: current, enhancement, ready-for-review

#8403 Turned CLick to Click
  source/_components/owntracks.markdown
Labels: current, enhancement, ready-for-review, spelling

#8400 Added JU6800 to non working models
  source/_components/media_player.samsungtv.markdown
Labels: current, enhancement, ready-for-review

#8405 🚜 Merges/Redirect Blink component pages
  source/_components/alarm_control_panel.blink.markdown
  source/_components/binary_sensor.blink.markdown
  source/_components/blink.markdown
  source/_components/camera.blink.markdown
  source/_components/sensor.blink.markdown
Labels: current, enhancement, ready-for-review

#8401 Update Air visual doc to include API key expiry
  source/_components/sensor.airvisual.markdown
Labels: current, enhancement, ready-for-review

#8407 Fixed symlink in cec documentation
  source/_components/hdmi_cec.markdown
Labels: current, enhancement, ready-for-review

#8409 Update utility_meter.markdown
  source/_components/utility_meter.markdown
Labels: enhancement, next

#8392 Add SmartThings event and platform docs
  source/_components/smartthings.light.markdown
  source/_components/smartthings.markdown
Labels: new-component, next, ready-for-review

#8413 ✏️ Change to the correct alarm category
  source/_components/homekit_controller.markdown
Labels: current, enhancement, ready-for-review

#8416 Simplifying the `for:` section
  source/_docs/automation/trigger.markdown
Labels: ready-for-review

#8398 blog: introduce hass-cli
  source/_posts/2019-02-04-introducing-home-assistant-cli.markdown
Labels: to-do

#8418 Added note about compilation issues
  source/_components/tradfri.markdown
Labels: ready-for-review

#7816 Add documentation for Transmission component
  source/_components/sensor.transmission.markdown
  source/_components/switch.transmission.markdown
  source/_components/transmission.markdown
Labels: awaits-parent, has-parent, new-component, next, parent-merged

#8427 🚜 Merges/Redirect Wink component pages
  source/_components/alarm_control_panel.wink.markdown
  source/_components/binary_sensor.wink.markdown
  source/_components/climate.wink.markdown
  source/_components/cover.wink.markdown
  source/_components/fan.wink.markdown
  source/_components/light.wink.markdown
  source/_components/lock.wink.markdown
  source/_components/scene.wink.markdown
  source/_components/sensor.wink.markdown
  source/_components/switch.wink.markdown
  source/_components/water_heater.wink.markdown
  source/_components/wink.markdown
Labels: current, enhancement, ready-for-review

#8423 🚜 Merges/Redirect Android IP Webcam component pages
  source/_components/android_ip_webcam.markdown
  source/_components/binary_sensor.android_ip_webcam.markdown
  source/_components/camera.android_ip_webcam.markdown
  source/_components/sensor.android_ip_webcam.markdown
  source/_components/switch.android_ip_webcam.markdown
Labels: current, enhancement, ready-for-review

#8321 Added docs for command line auth provider
  source/_docs/authentication/providers.markdown
Labels: awaits-parent, has-parent, new-component, next

#8434 Update system_health.markdown
  source/_components/system_health.markdown
Labels: current, enhancement, ready-for-review

#8436 Update sensor.miflora.markdown
  source/_components/sensor.miflora.markdown
Labels: current, enhancement, ready-for-review

#8437 not valid config yaml
  source/_components/transmission.markdown
Labels: current, enhancement, ready-for-review

#8438 Added components to Homematic IP Overview
  source/_components/homematicip_cloud.markdown
Labels: to-do

#8435 Fix octoprint number_of_tools default value
  source/_components/octoprint.markdown
Labels: current, enhancement

#8440 Fix Typo
  source/_docs/installation/hassbian/common-tasks.markdown
Labels: current, enhancement, ready-for-review

#8396 Added Google home alarm sensor
  source/_components/googlehome.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#8444 Added required option to Utility Meter sample config
  source/_components/utility_meter.markdown
Labels: to-do

#8446 Update light.yeelight.markdown
  source/_components/light.yeelight.markdown
Labels: to-do

#8449 Update device_tracker.markdown
  source/_components/device_tracker.markdown
Labels: current, enhancement, ready-for-review

#8451 Missed one ;)
  source/_components/sensor.waze_travel_time.markdown
Labels: current, enhancement, ready-for-review

#8439 Added configuration when using separate sensors per tariff
  source/_components/utility_meter.markdown
Labels: current, enhancement, ready-for-review

#8406 Update lets_encrypt.markdown
  source/_addons/lets_encrypt.markdown
Labels: current, enhancement, ready-for-review

#8455 Update sensor.darksky.markdown
  source/_components/sensor.darksky.markdown
Labels: to-do

#8452 Update image_processing.qrcode.markdown
  source/_components/image_processing.qrcode.markdown
Labels: current, enhancement, ready-for-review

#8044 Add support for fan speed to HomeKit
  source/_components/homekit.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8462 Fixing typo
  source/_components/gpslogger.md
Labels: current, enhancement, ready-for-review

#8458 Add person component
  source/_components/person.markdown
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#8404 Add info about reloading buttons to packages docs
  source/_docs/configuration/packages.markdown
Labels: current, enhancement, ready-for-review

#8443 Add SmartThings Sensor platform docs
  source/_components/smartthings.markdown
Labels: has-parent, parent-merged, ready-for-review

#8453 Add missing link to hass-cli blog post
  source/_posts/2019-02-04-introducing-home-assistant-cli.markdown
Labels: needs-rebase

#8461 Clarify homekit pin location
  source/_components/homekit.markdown
Labels: current, enhancement, ready-for-review

#8445 Correct device_id name for GPSLogger
  source/_components/gpslogger.md
Labels: current, enhancement, ready-for-review

#8422 CoolMasterNet integration documentation
  source/_components/climate.coolmaster.markdown
  source/images/supported_brands/coolautomation.png
Labels: has-parent, new-component, next, ready-for-review

#8448 Add HmIP-BSL to Overview for homematicip cloud
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next, ready-for-review

#8464 added new Model (UE49KU6470)
  source/_components/media_player.samsungtv.markdown
Labels: to-do

#8460 Replace target with recipient in tplink_lte config
  source/_components/tplink_lte.markdown
Labels: has-parent, next, ready-for-review

#7961 Ebusd integration
  source/_components/ebusd.markdown
Labels: awaits-parent, has-parent, new-component, next

#8465 Add instructions for connecting to hidden SSIDs
  source/_docs/installation/hassbian/installation.markdown
Labels: ready-for-review

#8441 Recommendations on lost connection detection
  source/_components/homematic.markdown
Labels: to-do

#8425 Restructuring for clarity
  source/_docs/z-wave/installation.markdown
Labels: current, enhancement, ready-for-review

#8456 added fan support for spider
  source/_components/climate.spider.markdown
Labels: has-parent, new-feature, next, parent-merged

#8430 Update input_datetime format description
  source/_components/input_datetime.markdown
Labels: current, enhancement, ready-for-review

#8470 hass-cli 0.5 release
  source/_posts/2019-02-11-hass-cli-0-dot-5-area-entity-registry-and-event-cli.markdown
Labels: ready-for-review

#8474 Update nest.markdown final step for clarity
  source/_components/nest.markdown
Labels: to-do

#8432 Added docs for new Ambient PWS fields
  source/_components/ambient_station.markdown
Labels: awaits-parent, has-parent, new-feature, next, ready-for-review

#8476 Fix typo in blog title
  source/_posts/2019-02-11-hass-cli-0-dot-5-area-entity-registry-and-event-cli.markdown
Labels: current, enhancement

#8410 Update scene.markdown to match new functionality
  source/_components/scene.markdown
Labels: has-parent, new-feature, next, parent-merged

#7942 GitHub Sensor
  source/_components/sensor.github.markdown
Labels: awaits-parent, has-parent, new-component, next, parent-merged

#7755 Update Flux Led documentation
  source/_components/light.flux_led.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#8479 fix bad links
  source/_posts/2019-02-11-hass-cli-0-dot-5-area-entity-registry-and-event-cli.markdown
Labels: bug, current

#7826 Update doorbird events to include URLs on event_data
  source/_components/doorbird.markdown
Labels: has-parent, new-feature, next, parent-merged

#8153 Google pubsub
  source/_components/google_pubsub.markdown
  source/images/supported_brands/google-pubsub.png
Labels: has-parent, new-component, next, parent-merged

#8279 html5 notification VAPID support
  source/_components/notify.html5.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#8481 Update tellduslive
  source/_components/tellduslive.markdown
  source/images/supported_brands/telldus.png
Labels: to-do

#8467 Update OpenHardwareMonitor documentation (How to open port on host)
  source/_components/sensor.openhardwaremonitor.markdown
Labels: current, enhancement, ready-for-review

#8431 Adding example for doing a search
  source/_components/sensor.imap.markdown
Labels: ready-for-review

#8486 🚜 Merges Velux component + Add cover support
  source/_components/velux.markdown
Labels: next, ready-for-review

#8489 Making things a bit clearer
  source/_components/ifttt.markdown
Labels: ready-for-review

#8487 Fix Ring sensor docs
  source/_components/sensor.ring.markdown
Labels: current, enhancement, ready-for-review

#8488 Fixed e.g., in the docs
  source/_components/aqualogic.markdown
  source/_components/asuswrt.markdown
  source/_components/camera.generic.markdown
  source/_components/camera.mjpeg.markdown
  source/_components/cover.rfxtrx.markdown
  source/_components/device_tracker.actiontec.markdown
  source/_components/dialogflow.markdown
  source/_components/dyson.markdown
  source/_components/hue.markdown
  source/_components/isy994.markdown
  source/_components/light.opple.markdown
  source/_components/light.tplink.markdown
  source/_components/media_player.aquostv.markdown
  source/_components/media_player.samsungtv.markdown
  source/_components/media_player.squeezebox.markdown
  source/_components/mysensors.markdown
  source/_components/notify.smtp.markdown
  source/_components/octoprint.markdown
  source/_components/point.markdown
  source/_components/scene.hunterdouglas_powerview.markdown
  source/_components/sensor.bitcoin.markdown
  source/_components/sensor.deutsche_bahn.markdown
  source/_components/sensor.dwd_weather_warnings.markdown
  source/_components/sensor.openweathermap.markdown
  source/_components/sensor.snmp.markdown
  source/_components/sensor.systemmonitor.markdown
  source/_components/sensor.worldclock.markdown
  source/_components/switch.deluge.markdown
  source/_components/switch.pilight.markdown
  source/_components/switch.tplink.markdown
Labels: current, enhancement, ready-for-review

#8027 Add support for multiple modbus hubs.
  source/_components/binary_sensor.modbus.markdown
  source/_components/climate.flexit.markdown
  source/_components/climate.modbus.markdown
  source/_components/modbus.markdown
  source/_components/sensor.modbus.markdown
  source/_components/switch.modbus.markdown
Labels: has-parent, in-progress, new-feature, ready-for-review

#8492 New working device
  source/_components/media_player.panasonic_viera.markdown
Labels: to-do

#8484 Updated TelldusLive logo
  source/_components/tellduslive.markdown
  source/images/supported_brands/telldus.png
  source/images/supported_brands/tellduslive.svg
Labels: to-do

#8482 Add missing config documentation for Spotify
  source/_components/media_player.spotify.markdown
Labels: current, enhancement, ready-for-review

#8485 Update sensor.synologydsm.markdown
  source/_components/sensor.synologydsm.markdown
Labels: current, enhancement, ready-for-review

#8377 Split out fastdotcom into a sensor and component
  source/_components/fastdotcom.markdown
  source/_components/sensor.fastdotcom.markdown
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#7979 update light.knx for xknx 0.9.4
  source/_components/light.knx.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#7771 XS1 component
  source/_components/xs1.markdown
  source/images/supported_brands/xs1.jpg
Labels: has-parent, new-component, next, parent-merged

#7957 Added notifications on changed status of the alarm
  source/_components/alarm_control_panel.manual.markdown
Labels: current, enhancement, ready-for-review

#8026 Add HAProxy remote access example
  source/_docs/ecosystem/haproxy.markdown
  source/_includes/asides/docs_navigation.html
Labels: current, enhancement, ready-for-review

#8466 Update NGINX proxy documentation
  source/_docs/ecosystem/nginx.markdown
Labels: current, enhancement, ready-for-review

#8394 Update tts.markdown
  source/_components/tts.markdown
Labels: current, enhancement, ready-for-review

#8366 Add webhook example to trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: current, enhancement, ready-for-review

#8334 Update asuswrt.markdown
  source/_components/asuswrt.markdown
Labels: current, enhancement, ready-for-review

#8494 Fix fastdotcom redirect_from param
  source/_components/fastdotcom.markdown
Labels: next, ready-for-review

#8378 Split out speedtestdotnet into a sensor and component
  source/_components/speedtestdotnet.markdown
Labels: has-parent, new-component, next, parent-merged

#8473 Add SmartThings Climate platform docs
  source/_components/smartthings.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#8109 Add documentation for Rejseplanen public transport sensor component
  source/_components/sensor.rejseplanen.markdown
  source/images/supported_brands/rejseplanen.png
Labels: new-component, next, parent-merged

#8483 Add a note for using http-only cameras
  source/_components/camera.generic.markdown
Labels: current, enhancement, ready-for-review

#8503 remove double `list`
  source/_posts/2019-02-11-hass-cli-0-dot-5-area-entity-registry-and-event-cli.markdown
Labels: current, enhancement, ready-for-review

#8512 🚜 Merges/Redirect qwikswitch component pages
  source/_components/binary_sensor.qwikswitch.markdown
  source/_components/light.qwikswitch.markdown
  source/_components/qwikswitch.markdown
  source/_components/sensor.qwikswitch.markdown
  source/_components/switch.qwikswitch.markdown
Labels: current, enhancement, ready-for-review

#8511 🚜 Merges/Redirect Konnected component pages
  source/_components/binary_sensor.konnected.markdown
  source/_components/konnected.markdown
  source/_components/switch.konnected.markdown
Labels: current, enhancement, ready-for-review

#8510 🚜 Merges/Redirect Kira component pages
  source/_components/kira.markdown
  source/_components/remote.kira.markdown
  source/_components/sensor.kira.markdown
Labels: current, enhancement, ready-for-review

#8509 🚜 Merges/Redirect August component pages
  source/_components/august.markdown
  source/_components/binary_sensor.august.markdown
  source/_components/camera.august.markdown
  source/_components/lock.august.markdown
Labels: current, enhancement, ready-for-review

#8513 🚜 Merges/Redirect Eight_sleep component pages
  source/_components/binary_sensor.eight_sleep.markdown
  source/_components/eight_sleep.markdown
  source/_components/sensor.eight_sleep.markdown
Labels: current, enhancement, ready-for-review

#8508 🚜 Merges/Redirect Velbus component pages
  source/_components/binary_sensor.velbus.markdown
  source/_components/climate.velbus.markdown
  source/_components/sensor.velbus.markdown
  source/_components/switch.velbus.markdown
  source/_components/velbus.markdown
Labels: current, enhancement, ready-for-review

#8514 Home-assistant presentation at PyConFR 2018
  source/help/index.markdown
Labels: ready-for-review

#8516 Update condition by adding check
  source/_components/sensor.rova.markdown
Labels: current, enhancement, ready-for-review

#8524 🚜 Merges/Redirect Mercedes Me component pages
  source/_components/binary_sensor.mercedesme.markdown
  source/_components/device_tracker.mercedesme.markdown
  source/_components/mercedesme.markdown
  source/_components/sensor.mercedesme.markdown
Labels: current, enhancement, ready-for-review

#8523 🚜 Merges/Redirect Tesla component pages
  source/_components/binary_sensor.tesla.markdown
  source/_components/climate.tesla.markdown
  source/_components/device_tracker.tesla.markdown
  source/_components/lock.tesla.markdown
  source/_components/sensor.tesla.markdown
  source/_components/switch.tesla.markdown
  source/_components/tesla.markdown
Labels: current, enhancement, ready-for-review

#8522 🚜 Merges/Redirect Dyson component pages
  source/_components/climate.dyson.markdown
  source/_components/dyson.markdown
  source/_components/fan.dyson.markdown
  source/_components/sensor.dyson.markdown
  source/_components/vacuum.dyson.markdown
Labels: current, enhancement, ready-for-review

#8521 🚜 Merges/Redirect Axis component pages
  source/_components/axis.markdown
  source/_components/binary_sensor.axis.markdown
  source/_components/camera.axis.markdown
Labels: current, enhancement, ready-for-review

#8520 🚜 Merges/Redirect Greeneye_monitor component pages
  source/_components/greeneye_monitor.markdown
  source/_components/sensor.greeneye_monitor.markdown
Labels: current, enhancement, ready-for-review

#8518 🚜 Merges/Redirect Vera component pages
  source/_components/binary_sensor.vera.markdown
  source/_components/climate.vera.markdown
  source/_components/cover.vera.markdown
  source/_components/light.vera.markdown
  source/_components/lock.vera.markdown
  source/_components/scene.vera.markdown
  source/_components/sensor.vera.markdown
  source/_components/switch.vera.markdown
  source/_components/vera.markdown
Labels: current, enhancement, ready-for-review

#8532 🚜 Merges/Redirect SCSGate component pages
  source/_components/cover.scsgate.markdown
  source/_components/light.scsgate.markdown
  source/_components/scsgate.markdown
  source/_components/switch.scsgate.markdown
Labels: current, enhancement, ready-for-review

#8540 Update system_health.markdown
  source/_components/system_health.markdown
Labels: current, enhancement

#8542 🚜 Merges/Redirect Spider component pages
  source/_components/climate.spider.markdown
  source/_components/spider.markdown
  source/_components/switch.spider.markdown
Labels: current, enhancement, ready-for-review

#8525 🚜 Merges/Redirect BMW Connected component pages
  source/_components/binary_sensor.bmw_connected_drive.markdown
  source/_components/bmw_connected_drive.markdown
  source/_components/device_tracker.bmw_connected_drive.markdown
  source/_components/lock.bmw_connected_drive.markdown
  source/_components/sensor.bmw_connected_drive.markdown
Labels: current, enhancement, ready-for-review

#8527 🚜 Merges/Redirect Luftdaten component pages
  source/_components/luftdaten.markdown
  source/_components/sensor.luftdaten.markdown
Labels: current, enhancement, ready-for-review

#8528 🚜 Merges/Redirect SABnzbd component pages
  source/_components/sabnzbd.markdown
  source/_components/sensor.sabnzbd.markdown
Labels: current, enhancement, ready-for-review

#8529 🚜 Merges/Redirect Abode component pages
  source/_components/abode.markdown
  source/_components/alarm_control_panel.abode.markdown
  source/_components/binary_sensor.abode.markdown
  source/_components/camera.abode.markdown
  source/_components/cover.abode.markdown
  source/_components/light.abode.markdown
  source/_components/lock.abode.markdown
  source/_components/sensor.abode.markdown
  source/_components/switch.abode.markdown
Labels: current, enhancement, ready-for-review

#8533 🚜 Merges/Redirect Skybell component pages
  source/_components/binary_sensor.skybell.markdown
  source/_components/camera.skybell.markdown
  source/_components/light.skybell.markdown
  source/_components/sensor.skybell.markdown
  source/_components/skybell.markdown
  source/_components/switch.skybell.markdown
Labels: current, enhancement, ready-for-review

#8534 🚜 Merges/Redirect HLK-SW16 component pages
  source/_components/hlk_sw16.markdown
  source/_components/switch.hlk_sw16.markdown
Labels: current, enhancement, ready-for-review

#8537 🚜 Merges/Redirect Ness Alarm component pages
  source/_components/alarm_control_panel.ness_alarm.markdown
  source/_components/binary_sensor.ness_alarm.markdown
  source/_components/ness_alarm.markdown
Labels: current, enhancement, ready-for-review

#8538 🚜 Merges/Redirect Deconz component pages
  source/_components/binary_sensor.deconz.markdown
  source/_components/cover.deconz.markdown
  source/_components/deconz.markdown
  source/_components/light.deconz.markdown
  source/_components/scene.deconz.markdown
  source/_components/sensor.deconz.markdown
  source/_components/switch.deconz.markdown
Labels: current, enhancement, ready-for-review

#8539 🚜 Merges/Redirect Digital Ocean component pages
  source/_components/binary_sensor.digital_ocean.markdown
  source/_components/digital_ocean.markdown
  source/_components/switch.digital_ocean.markdown
Labels: current, enhancement, ready-for-review

#8543 🚜 Merges/Redirect Dovado component pages
  source/_components/dovado.markdown
  source/_components/notify.dovado.markdown
  source/_components/sensor.dovado.markdown
Labels: current, enhancement, ready-for-review

#8541 Documentation for home-assistant/home-assistant-polymer#2489
  source/_lovelace/map.markdown
Labels: current, enhancement, ready-for-review

#8531 👋 Google Plus
  .themes/classic/sass/partials/_sidebar.scss
  .themes/classic/sass/partials/sidebar/_googleplus.scss
  .themes/classic/source/_includes/asides/googleplus.html
  _config.yml
  sass/partials/_sidebar.scss
  sass/partials/sidebar/_googleplus.scss
  source/_includes/custom/footer.html
  source/_posts/2018-07-21-release-74.markdown
  source/help/index.markdown
Labels: current, enhancement, ready-for-review

#8526 🚜 Merges/Redirect Egardia component pages
  source/_components/alarm_control_panel.egardia.markdown
  source/_components/binary_sensor.egardia.markdown
  source/_components/egardia.markdown
Labels: current, enhancement, ready-for-review

#8530 ✏️ Change ha_category for some component
  source/_components/ecobee.markdown
  source/_components/homematic.markdown
  source/_components/joaoapps_join.markdown
  source/_components/sensor.iliad_italy.markdown
Labels: current, enhancement, ready-for-review

#8546 🚜 Merges/Redirect TP-Link LTE component pages
  source/_components/notify.tplink_lte.markdown
  source/_components/tplink_lte.markdown
Labels: current, enhancement, ready-for-review

#8545 🚜 Merges/Redirect Insteon component pages
  source/_components/binary_sensor.insteon.markdown
  source/_components/cover.insteon.markdown
  source/_components/fan.insteon.markdown
  source/_components/insteon.markdown
  source/_components/insteon_local.markdown
  source/_components/insteon_plm.markdown
  source/_components/light.insteon.markdown
  source/_components/sensor.insteon.markdown
  source/_components/switch.insteon.markdown
Labels: current, enhancement, ready-for-review

#8547 🚜 Merges/Redirect Arlo component pages
  source/_components/alarm_control_panel.arlo.markdown
  source/_components/arlo.markdown
  source/_components/camera.arlo.markdown
  source/_components/sensor.arlo.markdown
Labels: current, enhancement, ready-for-review

#8544 🚜 Merges/Redirect Satel Integra component pages
  source/_components/alarm_control_panel.satel_integra.markdown
  source/_components/binary_sensor.satel_integra.markdown
  source/_components/satel_integra.markdown
Labels: current, enhancement, ready-for-review

#8505 Update service-calls.markdown
  source/_docs/scripts/service-calls.markdown
Labels: current, enhancement, ready-for-review

#8469 Update homematicip_cloud.markdown
  source/_components/homematicip_cloud.markdown
Labels: current, enhancement, ready-for-review

#8433 phue.conf is not used anymore
  source/_components/hue.markdown
Labels: current, enhancement

#8548 🚜 Merges/Redirect ADS component pages
  source/_components/ads.markdown
  source/_components/binary_sensor.ads.markdown
  source/_components/light.ads.markdown
  source/_components/sensor.ads.markdown
  source/_components/switch.ads.markdown
Labels: current, enhancement, ready-for-review

#8550 🚜 Merges/Redirect HomematicIP Cloud component pages
  source/_components/alarm_control_panel.homematicip_cloud.markdown
  source/_components/binary_sensor.homematicip_cloud.markdown
  source/_components/climate.homematicip_cloud.markdown
  source/_components/cover.homematicip_cloud.markdown
  source/_components/homematicip_cloud.markdown
  source/_components/light.homematicip_cloud.markdown
  source/_components/sensor.homematicip_cloud.markdown
  source/_components/switch.homematicip_cloud.markdown
Labels: current, enhancement, ready-for-review

#8551 🚜 Merges/Redirect Envisalink component pages
  source/_components/alarm_control_panel.envisalink.markdown
  source/_components/binary_sensor.envisalink.markdown
  source/_components/envisalink.markdown
  source/_components/sensor.envisalink.markdown
Labels: current, enhancement, ready-for-review

#8552 🚜 Merges/Redirect Canary component pages
  source/_components/alarm_control_panel.canary.markdown
  source/_components/camera.canary.markdown
  source/_components/canary.markdown
  source/_components/sensor.canary.markdown
Labels: current, enhancement, ready-for-review

#8553 🎨 Added logo to Yale component
  source/_components/alarm_control_panel.yale_smart_alarm.markdown
  source/images/supported_brands/yale.png
Labels: current, enhancement, ready-for-review

#8555 🎨 Added logo to APNS component
  source/_components/notify.apns.markdown
Labels: current, enhancement, ready-for-review

#8507 Update timer.markdown
  source/_components/timer.markdown
Labels: enhancement, next, parent-merged, ready-for-review

#8381 Create norway_air.markdown
  source/_components/norway_air.markdown
Labels: has-parent, new-component, next, parent-merged, ready-for-review

#8556 🎨 Exchange logo for Monoprice component
  source/images/supported_brands/monoprice.svg
Labels: current, enhancement, ready-for-review
