Repository home-assistant/home-assistant.io, pull requests merged in 2019-07, with the labels that each got.

#9737 No longer valid
  source/_includes/asides/hassio_navigation.html
  source/hassio/external_storage.markdown
Labels: current, enhancement

#9748 No longer required
  source/_includes/asides/hassio_navigation.html
  source/hassio/run_local.markdown
Labels: current, enhancement

#9751 Revert "Update lets_encrypt.markdown"
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: current, enhancement

#9750 Add deprecation warning to MQTT page for embedded broker
  source/_components/mqtt.markdown
Labels: current, enhancement, ready-for-review

#9741 Fix daemon script
  source/_docs/autostart/init.d.markdown
Labels: current, enhancement, ready-for-review

#9755 Fixed Hassbian 404 URLs
  source/_docs/installation/hassbian/customization.markdown
Labels: bug, current, enhancement, ready-for-review

#9758 ✏️ Fix urls and follow markdown rules
  source/_docs/installation/hassbian/common-tasks.markdown
  source/_docs/installation/hassbian/customization.markdown
  source/_docs/installation/hassbian/integrations.markdown
  source/_docs/installation/hassbian/upgrading.markdown
Labels: current, enhancement

#9766 Added warning_types
  source/_components/dwd_weather_warnings.markdown
Labels: current, enhancement

#9760 ✏️ The great integration migration - part 2
  source/_addons/snips.markdown
  source/_components/air_quality.markdown
  source/_components/alarm_control_panel.ifttt.markdown
  source/_components/alarmdecoder.markdown
  source/_components/alert.markdown
  source/_components/alexa.intent.markdown
  source/_components/alexa.markdown
  source/_components/alexa.smart_home.markdown
  source/_components/api.markdown
  source/_components/asterisk_cdr.markdown
  source/_components/binary_sensor.knx.markdown
  source/_components/binary_sensor.markdown
  source/_components/binary_sensor.xiaomi_aqara.markdown
  source/_components/blink.markdown
  source/_components/bme680.markdown
  source/_components/camera.ffmpeg.markdown
  source/_components/canary.markdown
  source/_components/cast.markdown
  source/_components/climate.knx.markdown
  source/_components/configurator.markdown
  source/_components/conversation.markdown
  source/_components/cover.knx.markdown
  source/_components/daikin.markdown
  source/_components/deconz.markdown
  source/_components/device_sun_light_trigger.markdown
  source/_components/dialogflow.markdown
  source/_components/directv.markdown
  source/_components/dlib_face_detect.markdown
  source/_components/dlib_face_identify.markdown
  source/_cookbook/automation_telegram_presence_alert.markdown
  source/_cookbook/dim_lights_when_playing_media.markdown
  source/_cookbook/python_component_mqtt_basic.markdown
  source/_cookbook/python_component_simple_alarm.markdown
  source/_docs/authentication.markdown
  source/_docs/security.markdown
  source/_docs/z-wave.markdown
  source/_lovelace/alarm-panel.markdown
  source/cloud/alexa.markdown
  source/hassio/installation.markdown
  source/help/reporting_issues.markdown
  source/help/trivia.markdown
  source/lovelace/index.markdown
Labels: current, enhancement, ready-for-review

#9769 Linked to Shopping List component
  source/_addons/snips.markdown
Labels: current, enhancement, ready-for-review

#9768 Update met.markdown
  source/_components/met.markdown
Labels: current, enhancement, ready-for-review

#9773 link on tahoma does not work
  source/_components/somfy.markdown
Labels: bug, current

#9783 Minor errors & style improvements in grammar on the welcome page.
  source/getting-started/index.markdown
Labels: current, enhancement

#9776 Snips.ai corrections
  source/_addons/snips.markdown
Labels: current, enhancement, ready-for-review

#9777 Update yeelight.markdown
  source/_components/yeelight.markdown
Labels: current, enhancement

#9785 Updated broken links
  source/_components/arwn.markdown
  source/_components/sensor.rflink.markdown
Labels: current, enhancement

#9786 Remove OS specific mentions from virtualenv guide
  source/_docs/installation/virtualenv.markdown
Labels: current, enhancement, ready-for-review

#9789 Remove monitored conditions config
  source/_components/netatmo.markdown
Labels: has-parent, next, parent-merged

#9752 Add missing trigger.for variable to template trigger
  source/_docs/automation/templating.markdown
Labels: has-parent, new-feature, next

#9753 Google Cloud TTS extra languages
  source/_components/google_cloud.markdown
Labels: has-parent, new-feature, next

#9778 Ruby deps upgrades and cleanup
  Gemfile
  Gemfile.lock
  plugins/category_generator.rb
Labels: current

#9787 Replaces all internal full URL links
  source/_components/blink.markdown
  source/_components/daikin.markdown
  source/_components/ecobee.markdown
  source/_components/emulated_hue.markdown
  source/_components/http.markdown
  source/_components/life360.markdown
  source/_components/netatmo.markdown
  source/_components/osramlightify.markdown
  source/_components/person.markdown
  source/_components/point.markdown
  source/_components/ps4.markdown
  source/_components/utility_meter.markdown
  source/_docs/ecosystem/haproxy.markdown
  source/_lovelace/picture-entity.markdown
  source/_posts/2018-07-16-release-73-2.markdown
  source/_posts/2018-09-17-thinking-big.markdown
  source/_posts/2018-09-30-hacktoberfest.markdown
  source/_posts/2018-10-12-release-80.markdown
  source/_posts/2018-10-29-release-81.markdown
  source/_posts/2018-12-17-logitech-harmony-removes-local-api.markdown
  source/_posts/2019-01-23-lovelace-released.markdown
  source/_posts/2019-02-11-hass-cli-0-dot-5-area-entity-registry-and-event-cli.markdown
  source/_posts/2019-03-20-release-90.markdown
  source/_posts/2019-04-01-android.markdown
  source/_posts/2019-04-03-release-91.markdown
  source/_posts/2019-04-15-hassio-ingress.markdown
  source/_posts/2019-04-24-release-92.markdown
  source/_posts/2019-05-03-update-from-the-field.markdown
  source/_posts/2019-06-26-release-95.markdown
Labels: current, enhancement, ready-for-review

#9784 Updated release cycle information
  source/_faq/release.markdown
Labels: current, enhancement, ready-for-review

#9795 Quick removal of links to setting the password
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: current, enhancement

#9796 Update mosquitto.markdown
  source/_addons/mosquitto.markdown
Labels: current, enhancement

#9790 Add documentation for new service sonos.play_queue
  source/_components/sonos.markdown
Labels: has-parent, new-feature, next

#9800 Add new supported models
  source/_components/samsungtv.markdown
Labels: current, enhancement, ready-for-review

#9803 Fix formatting of installation commands
  source/hassio/installation.markdown
Labels: current, enhancement

#9805 🔨 Fix broken links (part 1)
  source/_posts/2015-05-14-release-notes.markdown
  source/_posts/2015-06-10-release-notes.markdown
  source/_posts/2015-08-09-mqtt-raspberry-pi-squeezebox-asuswrt-support.markdown
  source/_posts/2015-08-31-version-7-revamped-ui-and-improved-distribution.markdown
  source/_posts/2015-10-26-firetv-and-radiotherm-now-supported.markdown
  source/_posts/2015-12-06-locks-rollershutters-binary-sensors-and-influxdb-support.markdown
  source/_posts/2015-12-20-amazon-echo-icloud-and-templates.markdown
  source/_posts/2016-01-17-extended-support-for-diy-solutions.markdown
  source/_posts/2016-01-29-insteon-lifx-twitter-and-zigbee.markdown
  source/_posts/2016-03-26-embedded-mqtt-broker-uber-yamaha-growl.markdown
  source/_posts/2016-05-21-release-020.markdown
  source/_posts/2016-07-16-sqlalchemy-knx-join-simplisafe.markdown
  source/_posts/2016-07-30-custom-frontend-panels--jupyter-notebooks--directv.markdown
  source/_posts/2016-08-13-foursquare-fast-com-ffmpeg-gpsd.markdown
  source/_posts/2016-08-27-notifications-hue-fake-unification.markdown
  source/_posts/2016-09-29-async-sleepiq-emoncms-stocks.markdown
  source/_posts/2016-11-05-hacktoberfest-influxdb-weather.markdown
  source/_posts/2017-01-14-iss-usps-images-packages.markdown
  source/_posts/2017-01-28-face-coffee-wink.markdown
  source/_posts/2017-02-11-alert-appletv-mqtt-yeelight.markdown
  source/_posts/2017-02-25-config-panel-and-state-restoration.markdown
  source/_posts/2017-03-11-repurpose-any-android-phone-as-ip-camera.markdown
  source/_posts/2017-03-25-todo-volumio-workday.markdown
  source/_posts/2017-04-22-ikea-tradfri--spotify.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-08-26-release-0-52.markdown
Labels: current, enhancement

#9806 🔨 Fix broken links (part 2)
  source/_components/dominos.markdown
  source/_components/dsmr.markdown
  source/_components/flic.markdown
  source/_components/locative.md
  source/_components/miflora.markdown
  source/_posts/2016-03-26-embedded-mqtt-broker-uber-yamaha-growl.markdown
  source/_posts/2016-05-21-release-020.markdown
  source/_posts/2016-10-01-we-have-raspberry-image-now.markdown
  source/_posts/2016-12-03-remote-websockets-sonarr.markdown
  source/_posts/2017-01-14-iss-usps-images-packages.markdown
  source/_posts/2017-01-28-face-coffee-wink.markdown
  source/_posts/2017-02-03-hassbian-toybox.markdown
  source/_posts/2017-03-11-repurpose-any-android-phone-as-ip-camera.markdown
  source/_posts/2017-03-25-todo-volumio-workday.markdown
  source/_posts/2017-04-08-eddystone-beacons--lockitron-locks--total-connect.markdown
  source/_posts/2017-04-22-ikea-tradfri--spotify.markdown
  source/_posts/2017-04-30-hassbian-1.21-its-about-time.markdown
  source/_posts/2017-05-01-home-assistant-on-raspberry-pi-zero-in-30-minutes.markdown
  source/_posts/2017-05-20-automation-editor-zwave-panel-ocr.markdown
  source/_posts/2017-06-04-release-46.markdown
  source/_posts/2017-07-16-release-49.markdown
  source/_posts/2017-07-29-release-50.markdown
  source/_posts/2017-08-12-release-51.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/_posts/2017-09-09-release-53.markdown
  source/_posts/2017-09-23-release-54.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2017-11-18-release-58.markdown
  source/_posts/2017-12-03-release-59.markdown
  source/_posts/2017-12-17-release-60.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2018-01-27-release-62.markdown
  source/_posts/2018-02-10-release-63.markdown
  source/_posts/2018-02-26-release-64.markdown
  source/_posts/2018-03-09-release-65.markdown
  source/_posts/2018-03-30-release-66.markdown
  source/_posts/2018-04-14-release-67.markdown
  source/_posts/2018-04-27-release-68.markdown
  source/_posts/2018-05-11-release-69.markdown
  source/_posts/2018-05-18-release-70.markdown
  source/_posts/2018-06-10-release-71.markdown
  source/_posts/2018-08-29-release-77.markdown
  source/_posts/2018-10-12-release-80.markdown
  source/_posts/2018-10-29-release-81.markdown
  source/_posts/2019-01-09-release-85.markdown
  source/_posts/2019-02-20-release-88.markdown
  source/developers/credits.markdown
Labels: current, enhancement, ready-for-review

#9810 Update deconz.markdown
  source/_components/deconz.markdown
Labels: current, enhancement

#9809 ✏️ Wink: Make link to platform sections
  source/_components/wink.markdown
Labels: current, enhancement, ready-for-review

#9811 🎨 Added missing logo's
  source/_components/ecoal_boiler.markdown
  source/_components/frontier_silicon.markdown
  source/_components/litejet.markdown
  source/_components/niko_home_control.markdown
  source/images/supported_brands/centralite.svg
  source/images/supported_brands/ciscospark.png
  source/images/supported_brands/frontier.png
  source/images/supported_brands/niko.png
Labels: current, enhancement, ready-for-review

#9791 Add datetime option to input_datetime.set_datetime service
  source/_components/input_datetime.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9762 Add template support to state trigger's for option
  source/_docs/automation/trigger.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9815 Clarify cast preview blog
  source/_posts/2019-07-09-home-assistant-cast-preview.markdown
Labels: current, enhancement, spelling

#9814 Add omer_count docs to jewish_calendar
  source/_components/jewish_calendar.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9821 Fix opentherm_gw reverted updates
  source/_components/opentherm_gw.markdown
Labels: enhancement, next

#9816 [climate] Migrate honeywell docs for climate-1.0
  source/_components/honeywell.markdown
Labels: has-parent, new-feature, next

#9665 Add docs for Notion
  source/_components/notion.markdown
  source/images/supported_brands/notion.png
Labels: has-parent, new-integration, next, parent-merged

#9703 Create aurora_abb_powerone.markdown
  source/_components/aurora_abb_powerone.markdown
  source/images/supported_brands/powerone.png
Labels: has-parent, new-integration, next, parent-merged

#9692 Insteon Scene Automation
  source/_components/insteon.markdown
Labels: has-parent, new-feature, next, parent-merged

#9792 Add Twilio SMS media_url docs
  source/_components/twilio_sms.markdown
Labels: has-parent, new-feature, next, parent-merged

#9600 Enphase envoy production from individual inverters
  source/_components/enphase_envoy.markdown
Labels: has-parent, new-feature, next, parent-merged

#9817 [climate] Migrate incomfort docs for climate-1.0
  source/_components/incomfort.markdown
Labels: has-parent, new-feature, next

#9808 🔨 Fix broken links (part 3)
  source/_components/locative.md
  source/_posts/2015-01-04-hey-pushbullet-nice-talking-to-you.markdown
  source/_posts/2015-02-24-streaming-updates.markdown
  source/_posts/2015-10-26-firetv-and-radiotherm-now-supported.markdown
  source/_posts/2015-11-16-zwave-switches-lights-and-honeywell-thermostats-now-supported.markdown
  source/_posts/2015-12-06-locks-rollershutters-binary-sensors-and-influxdb-support.markdown
  source/_posts/2016-01-17-extended-support-for-diy-solutions.markdown
  source/_posts/2016-01-29-insteon-lifx-twitter-and-zigbee.markdown
  source/_posts/2016-02-13-speedtest-bloomsky-splunk-and-garage-doors.markdown
  source/_posts/2016-04-09-onkyo-panasonic-gtfs-and-config-validation.markdown
  source/_posts/2016-04-21-bluetooth-lg-webos-tvs-and-roombas.markdown
  source/_posts/2016-05-07-empowering-scripts-and-alexa.markdown
  source/_posts/2016-05-21-release-020.markdown
  source/_posts/2016-05-22-get-started-with-all-in-one-installer.markdown
  source/_posts/2016-06-08-super-fast-web-enocean-lirc.markdown
  source/_posts/2016-06-13-home-assistant-at-pycon-2016.markdown
  source/_posts/2016-06-18-pandora-bt-home-hub-5-and-local-file-camera.markdown
  source/_posts/2016-07-01-envisalink-homematic-hdmi-cec-and-sony-bravia-tv.markdown
  source/_posts/2016-07-16-sqlalchemy-knx-join-simplisafe.markdown
  source/_posts/2016-07-30-custom-frontend-panels--jupyter-notebooks--directv.markdown
  source/_posts/2016-08-07-optimizing-the-home-assistant-mobile-web-app.markdown
  source/_posts/2016-08-13-foursquare-fast-com-ffmpeg-gpsd.markdown
  source/_posts/2016-09-29-async-sleepiq-emoncms-stocks.markdown
  source/_posts/2016-11-05-hacktoberfest-influxdb-weather.markdown
  source/_posts/2017-04-22-ikea-tradfri--spotify.markdown
  source/_posts/2017-05-06-zigbee-opencv-dlib.markdown
  source/_posts/2017-05-20-automation-editor-zwave-panel-ocr.markdown
  source/_posts/2017-06-04-release-46.markdown
  source/_posts/2017-06-17-release-47.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-07-16-release-49.markdown
  source/_posts/2017-07-29-release-50.markdown
  source/_posts/2017-08-12-release-51.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/_posts/2017-09-09-release-53.markdown
  source/_posts/2017-09-23-release-54.markdown
  source/_posts/2017-09-25-new-hassio-build-system.markdown
  source/_posts/2017-10-21-release-56.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2017-11-18-release-58.markdown
  source/_posts/2017-12-03-release-59.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2018-02-10-release-63.markdown
  source/_posts/2018-03-09-release-65.markdown
  source/_posts/2018-05-11-release-69.markdown
  source/_posts/2018-08-17-release-76.markdown
  source/_posts/2018-11-08-release-82.markdown
  source/_posts/2019-04-24-release-92.markdown
  source/_posts/2019-05-16-release-93.markdown
  source/help/index.markdown
Labels: current, enhancement

#9819 [climate] Migrate evohome docs for climate-1.0
  source/_components/evohome.markdown
Labels: has-parent, new-feature, next

#9824 Update emulated_hue.markdown
  source/_components/emulated_hue.markdown
Labels: current, enhancement

#9823 Slight process change
  source/_components/calendar.google.markdown
Labels: current, enhancement, ready-for-review

#9804 Added info on how to launch specific Roku channel via automation.
  source/_components/roku.markdown
Labels: current, enhancement, ready-for-review

#9660 Add arcam_fmj media player
  source/_components/arcam_fmj.markdown
  source/images/supported_brands/arcam.svg
Labels: has-parent, new-integration, next, parent-merged

#9781 Add template support to numeric_state trigger's for option
  source/_docs/automation/templating.markdown
  source/_docs/automation/trigger.markdown
Labels: has-parent, new-feature, next

#9818 [climate] Migrate geniushub docs for climate-1.0
  source/_components/geniushub.markdown
Labels: has-parent, new-feature, next

#9820 Add marker sensor to CUPS
  source/_components/cups.markdown
Labels: has-parent, new-feature, next

#9829 media_player volume control
  source/_components/google_assistant.markdown
Labels: current, enhancement

#9799 Climate 1.0
  source/_components/climate.knx.markdown
  source/_components/climate.markdown
  source/_components/climate.mqtt.markdown
  source/_components/climate.mysensors.markdown
  source/_components/daikin.markdown
  source/_components/dyson.markdown
  source/_components/ecobee.markdown
  source/_components/generic_thermostat.markdown
  source/_components/geniushub.markdown
  source/_components/google_assistant.markdown
  source/_components/hive.markdown
  source/_components/incomfort.markdown
  source/_components/knx.markdown
  source/_components/nest.markdown
  source/_components/nuheat.markdown
  source/_components/oem.markdown
  source/_components/radiotherm.markdown
  source/_components/sensibo.markdown
  source/_components/smartthings.markdown
  source/_components/stiebel_eltron.markdown
  source/_components/toon.markdown
  source/_components/venstar.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9827 Update alexa.smart_home.markdown
  source/_components/alexa.smart_home.markdown
Labels: current, enhancement, ready-for-review

#9488 [Toon] New scan_interval on integration level
  source/_components/toon.markdown
Labels: has-parent, new-feature, next

#9802 Add WWLLN docs
  source/_components/wwlln.markdown
  source/images/screenshots/wwlln-feed-map.png
  source/images/supported_brands/wwlln.jpg
Labels: has-parent, new-integration, next

#9837 Fix Google Assistant docs horizontal scroll
  source/_components/google_assistant.markdown
Labels: current, enhancement, ready-for-review

#9833 Update Raspberry Pi specific
  source/_docs/z-wave/installation.markdown
Labels: current, enhancement, ready-for-review

#9846 Correct ' and " in the sun template example
  source/_docs/scripts/conditions.markdown
Labels: current, enhancement

#9825 Remove monitored conditions in syncthru component
  source/_components/syncthru.markdown
Labels: has-parent, next, parent-merged, ready-for-review

#9836 Add Apache Kafka docs
  source/_components/apache_kafka.markdown
  source/images/supported_brands/apache_kafka.png
Labels: has-parent, new-integration, parent-merged

#9577 Added config for multiple accounts - N26
  source/_components/n26.markdown
Labels: has-parent, new-feature, next

#9831 Add documentation for Splunk Component entity filter support
  source/_components/splunk.markdown
Labels: has-parent, new-feature, next, parent-merged

#9832 Add climate services to Homematic IP Cloud
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next

#9849 Update azure_event_hub.markdown
  source/_components/azure_event_hub.markdown
Labels: current, enhancement

#9851 Add Twente Milieu integration
  source/_components/twentemilieu.markdown
  source/images/supported_brands/twentemilieu.png
Labels: has-parent, new-integration, next, parent-merged

#9850 state trigger - entity_id details
  source/_docs/automation/trigger.markdown
Labels: current, enhancement

#9862 Highlight that live view isn't possible.
  source/_components/ring.markdown
Labels: current, enhancement

#9866 🚑 Fixes javascript error by removing unused GitHub extension
  _config.yml
  source/_includes/javascripts/scripts.html
  source/javascripts/github.js
  source/javascripts/libs/jXHR.js
Labels: bug, current, ready-for-review

#9867 Fix atom.xml Issue #9861
  source/atom.xml
Labels: current, enhancement, ready-for-review

#9865 Fix typo in Glances doc
  source/_components/glances.markdown
Labels: current, spelling

#9869 Update hvac_mode attributes
  source/_components/climate.knx.markdown
Labels: parent-merged, rc, ready-for-review

#9856 Added Hive Water Heater
  source/_components/hive.markdown
Labels: has-parent, needs-rebase, new-feature, next, parent-merged

#9860 Add homekit reset accessory
  source/_components/homekit.markdown
Labels: has-parent, new-feature, next

#9847 UniFi device tracker part of config entry
  source/_components/unifi.markdown
Labels: has-parent, next

#9283 Fronius component documentation
  source/_components/fronius.markdown
  source/images/supported_brands/fronius.png
Labels: has-parent, new-integration, next

#9870 Fix OID table
  source/_components/snmp.markdown
Labels: current, enhancement, ready-for-review

#9747 Add French support and two sensors to Environment Canada.
  source/_components/environment_canada.markdown
Labels: has-parent, new-feature, next

#9857 Simplify Social Blade sensor instructions
  source/_components/socialblade.markdown
Labels: current, enhancement, ready-for-review

#9845 serial_sensor Added splitting string example, fixed Arduino ex
  source/_components/serial.markdown
Labels: current, enhancement

#9859 Update mitemp_bt component documentation
  source/_components/mitemp_bt.markdown
Labels: current, enhancement

#9858 Update Homekit Docs
  source/_components/homekit_controller.markdown
Labels: current, enhancement

#9807 Added the Fortigate component documentation
  source/_components/fortigate.markdown
  source/images/supported_brands/fortinet.jpg
Labels: has-parent, in-progress, new-integration, next

#9129 Add severe weather sensor to Dark Sky
  source/_components/darksky.markdown
Labels: has-parent, new-feature, next, parent-merged

#9872 FortiGate: Fixes release, spelling & front matter
  source/_components/fortigate.markdown
Labels: enhancement, next, ready-for-review

#9876 Added Zwave2Mqtt to hass mqtt discovery third-party tools
  source/_docs/mqtt/discovery.markdown
Labels: current, enhancement

#9875 Corrected template example
  source/_components/switch.template.markdown
Labels: current, enhancement

#9798 Add documentation for custom spotify service play_playlist
  source/_components/spotify.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#9881 Add documentation of new login_method config option
  source/_components/mikrotik.markdown
Labels: has-parent, new-feature, next

#9883 Add HmIP-PCBS, HmIP-PCBS2, HmIP-PCBS-Bat to Homematic IP Cloud
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next

#9878 Update solaredge_local.markdown
  source/_components/solaredge_local.markdown
Labels: current, enhancement

#9890 Add info about concurrent use of data and data_template
  source/_docs/automation/templating.markdown
Labels: current, enhancement

#9889 Add info about concurrent use of data and data_template
  source/_docs/scripts/service-calls.markdown
Labels: current, enhancement

#9892 Collection of configuration block fixes
  source/_components/arcam_fmj.markdown
  source/_components/climate.mqtt.markdown
  source/_components/vacuum.template.markdown
  source/_components/wwlln.markdown
Labels: current, enhancement

#9894 Update climate.markdown
  source/_components/climate.markdown
Labels: current, enhancement

#9893 Mode `on` is now `heat`
  source/_components/climate.mqtt.markdown
Labels: current, enhancement

#9899 Fixed Sensibo switch example
  source/_components/sensibo.markdown
Labels: current, enhancement

#9886 Adds config validation to configuration plugin
  plugins/configuration.rb
Labels: current, enhancement, ready-for-review

#9896 Add MQTT climate precision
  source/_components/climate.mqtt.markdown
Labels: has-parent, new-feature, next, ready-for-review

#9761 Add documentation for new Rainforest Eagle-200 platform
  source/_components/rainforest_eagle.markdown
  source/images/supported_brands/rainforest_automation_logo.png
Labels: has-parent, new-integration, next, parent-merged

#9882 Update neato configuration to include vendor support
  source/_components/neato.markdown
Labels: has-parent, new-feature, next, parent-merged

#9873 add HmIP-FCI1, HmIP-BBL, HmIP-FBL to Homematic IP Cloud
  source/_components/homematicip_cloud.markdown
Labels: has-parent, new-feature, next

#9589 Update totalconnect.markdown
  source/_components/totalconnect.markdown
Labels: has-parent, new-feature, next

#9902 Removes absolete code from Markdown files
  source/_components/arcam_fmj.markdown
  source/_components/aurora_abb_powerone.markdown
  source/_components/notion.markdown
  source/_components/trafikverket_train.markdown
  source/_components/vacuum.template.markdown
  source/_components/vallox.markdown
  source/_components/wwlln.markdown
  source/_docs/configuration/templating.markdown
  source/_posts/2019-07-17-release-96.markdown
Labels: current

#9905 Minor - Clarify Services
  source/_components/ecobee.markdown
Labels: current, enhancement

#9915 Add blogpost about piwheel issue
  source/_posts/2019-07-19-piwheels.markdown
Labels: blog, current

#9920 Fixes running Jekyll preview in devcontainer
  .devcontainer/Dockerfile
  Rakefile
Labels: current, enhancement, ready-for-review

#9924 Clarify weblink differences under States & Lovelace
  source/_components/weblink.markdown
Labels: current, enhancement

#9911 Fix configuration example for input date time
  source/_components/input_datetime.markdown
Labels: current, enhancement

#9910 "off" mode missing in initial_hvac_mode:
  source/_components/generic_thermostat.markdown
Labels: current, enhancement

#9906 Update IFTTT instructions for 0.96 developer tools UI changes
  source/_components/ifttt.markdown
Labels: current, enhancement

#9921 Add WWLLN to list of geolocation triggers
  source/_components/geo_location.markdown
Labels: current, enhancement

#9914 Update APRS username documentation
  source/_components/aprs.markdown
Labels: current, enhancement

#9505 Updating snapcast documentation
  source/_components/snapcast.markdown
Labels: has-parent, new-feature, next

#9927 Converting JSON to YAML
  source/_components/discord.markdown
Labels: current, enhancement

#9887 Add docs for new SimpliSafe PIN services
  source/_components/simplisafe.markdown
Labels: has-parent, new-feature, next, parent-merged, ready-for-review

#9926 Added infos about the windows parameter
  source/_components/wwlln.markdown
Labels: current, enhancement

#9925 Update mvglive.markdown
  source/_components/mvglive.markdown
Labels: has-parent, new-feature, next

#9929 Fix incorrect timing statement on WWLLN docs
  source/_components/wwlln.markdown
Labels: current, enhancement, ready-for-review

#9928 Remove CONF_MONITORED_CONDITIONS from Ambient PWS docs
  source/_components/ambient_station.markdown
Labels: has-parent, next, parent-merged

#9932 Add window update docs to WWLLN
  source/_components/wwlln.markdown
Labels: has-parent, new-feature, next

#9930 Add ctags file to .gitignore
  .gitignore
Labels: current, enhancement, ready-for-review

#9934 Removes archlinux package instructions
  source/_docs/installation/archlinux.markdown
Labels: current, enhancement

#9938 Fix deprecated link
  source/hassio/installation.markdown
Labels: current, enhancement

#9936 Correct incorrect YAML in Discord example
  source/_components/discord.markdown
Labels: current, enhancement

#9942 Spelling fixes
  source/_components/cover.mqtt.markdown
  source/_components/cups.markdown
  source/_components/danfoss_air.markdown
  source/_components/discord.markdown
  source/_components/ebusd.markdown
  source/_components/elkm1.markdown
  source/_components/entur_public_transport.markdown
  source/_components/freebox.markdown
  source/_components/google_assistant.markdown
  source/_components/gtt.markdown
  source/_components/heos.markdown
  source/_components/hlk_sw16.markdown
  source/_components/lcn.markdown
  source/_components/mhz19.markdown
  source/_components/nilu.markdown
  source/_components/nissan_leaf.markdown
  source/_components/orangepi_gpio.markdown
  source/_components/point.markdown
  source/_components/ps4.markdown
  source/_components/ptvsd.markdown
  source/_components/scrape.markdown
  source/_components/smartthings.markdown
  source/_components/switcher_kis.markdown
  source/_components/tensorflow.markdown
  source/_components/traccar.markdown
  source/_components/utility_meter.markdown
Labels: current, enhancement

#9941 Spell categories in title case
  source/_components/config.markdown
  source/_components/ecoal_boiler.markdown
  source/_components/econet.markdown
  source/_components/geniushub.markdown
  source/_components/incomfort.markdown
  source/_components/panel_custom.markdown
  source/_components/panel_iframe.markdown
  source/_components/rss_feed_template.markdown
  source/_components/weblink.markdown
  source/_components/wink.markdown
Labels: current, spelling

#9945 Add note about manual config and discovery
  source/_components/netatmo.markdown
Labels: current, enhancement

#9954 Correct service calls on persistent_notification page
  source/_components/persistent_notification.markdown
Labels: current, enhancement

#9952 Remove link from Logbook introduction
  source/_components/logbook.markdown
Labels: current, enhancement

#9591 Rename RitAssist component to FleetGO
  source/_components/fleetgo.markdown
  source/_components/ritassist.markdown
  source/images/supported_brands/fleetgo.png
  source/images/supported_brands/ritassist.png
Labels: has-parent, next

#9953 Recorder page - rename component to integration
  source/_components/recorder.markdown
Labels: current, enhancement

#9951 Add note on prerequisites to Environment Canada
  source/_components/environment_canada.markdown
Labels: current, enhancement

#9960 Adding warning
  source/_docs/z-wave/controllers.markdown
Labels: current, enhancement

#9961 Update link to the full list of ADB key commands
  source/_components/androidtv.markdown
Labels: current, enhancement

#9959 Fix Markdown link
  source/_components/cast.markdown
Labels: bug, current

#9576 Suez Water sensor documentation
  source/_components/suez.markdown
  source/images/supported_brands/suez.png
Labels: has-parent, new-integration, next, parent-merged

#9044 Create fortios.markdown
  source/_components/fortios.markdown
Labels: has-parent, in-progress, new-integration, next, parent-merged

#9931 add contact sensor to homekit_controller docs
  source/_components/homekit_controller.markdown
Labels: has-parent, new-feature, next

#9854 Add add_torrent service to Transmission
  source/_components/transmission.markdown
Labels: has-parent, new-feature, next

#9559 Adds Elgato Avea integration
  source/_components/avea.markdown
  source/images/supported_brands/avea.png
Labels: has-parent, new-integration, next

#9958 Update yi.markdown / solution for Pure-FTPd
  source/_components/yi.markdown
Labels: current, enhancement

#9963 Fix links appearance
  source/_docs/installation/virtualenv.markdown
Labels: current, enhancement

#9966 🚑 Fixes issue in version.json
  source/version.json
Labels: bug, current

#9968 Fixes type links in configuration blocks
  plugins/configuration.rb
Labels: bug, current

#9967 Update attribute of input_datetime with icon:
  source/_components/input_datetime.markdown
Labels: current, enhancement

#9965 Add support for turn_on/off, add note on Away mode
  source/_components/daikin.markdown
Labels: current, enhancement
