Repository home-assistant/home-assistant.io, pull requests merged in 2019-11, with the labels that each got.

#11067 Python 3.7
  source/_docs/installation.markdown
Labels: current

#11068 Python 3.7
  source/_docs/installation/raspberry-pi.markdown
Labels: current

#11069 Python 3.7
  source/_docs/installation/macos.markdown
Labels: current

#11070 Python 3.7 again
  source/_docs/installation/virtualenv.markdown
Labels: current

#11014 update facebox docs
  source/_integrations/facebox.markdown
Labels: Hacktoberfest, current

#11064 Update remote.xiaomi_miio.markdown
  source/_integrations/remote.xiaomi_miio.markdown
Labels: Hacktoberfest, current

#11052 Update python logger link
  source/_integrations/python_script.markdown
Labels: Hacktoberfest, current

#11051 Fixed and Updated decora switch documentation
  source/_integrations/decora.markdown
Labels: Hacktoberfest, has-parent, next, parent-merged

#11073 Add heading
  source/_integrations/remote.xiaomi_miio.markdown
Labels: current

#11074 Delete double entry
  source/_posts/2019-10-20-release-101.markdown
Labels: current

#10840 Update the callback url for Somfy
  source/_integrations/somfy.markdown
Labels: Hacktoberfest, current, has-parent

#11077 add link to lovelace changelog
  source/_posts/2019-10-20-release-101.markdown
Labels: current

#11078 Replace api_password with a generic example
  source/_docs/tools/keyring.markdown
Labels: current

#11080 Updated example scene
  source/_integrations/scene.markdown
Labels: current

#11088 Update backup_github.markdown
  source/_docs/ecosystem/backup/backup_github.markdown
Labels: current

#11084 Update ios.markdown
  source/_docs/ecosystem/ios.markdown
Labels: current

#11087 Clarify supported devices
  source/_integrations/lg_soundbar.markdown
Labels: current

#11086 Update based on latest lovelace UI
  source/_integrations/homekit.markdown
Labels: current

#11089 Fixed misplaced double quotation.
  source/_integrations/snmp.markdown
Labels: current

#11090 Revert "Update ios.markdown"
  source/_docs/ecosystem/ios.markdown
Labels: current

#11092 Fix a couple typos
  source/_integrations/google_assistant.markdown
Labels: current

#10999 Add dump config service to HomematicIP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: Hacktoberfest, has-parent, next, parent-merged

#11094 Add two missing fields to events in Abode
  source/_integrations/abode.markdown
Labels: current, has-parent

#11011 Slightly restructure page and improve grammar
  source/_docs/configuration/yaml.markdown
Labels: Hacktoberfest, current

#10899 Update Vivotek integration
  source/_integrations/vivotek.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next, parent-merged

#11091 Improved doorbird setup documentation
  source/_integrations/doorbird.markdown
Labels: current

#11030 Add scene.create service
  source/_integrations/scene.markdown
Labels: Hacktoberfest, has-parent, next, parent-merged

#11056 Update ps4 docs
  source/_integrations/ps4.markdown
Labels: Hacktoberfest, current

#11025 Edit nomenclature
  source/getting-started/index.markdown
Labels: Hacktoberfest, current

#11098 Fix list indentation
  source/_integrations/google_assistant.markdown
Labels: current

#10380 Modernize Huawei LTE, add UI config, unauthenticated mode, switch
  source/_integrations/device_tracker.markdown
  source/_integrations/huawei_lte.markdown
  source/_integrations/ssdp.markdown
Labels: has-parent, new-feature, next, parent-merged

#10838 Nzbget download event
  source/_integrations/nzbget.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#10656 Add ViCare heating_type
  source/_integrations/vicare.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#11101 Adding a small tip about DNS propagation.
  source/_integrations/google_assistant.markdown
Labels: current

#10917 Update juicenet docs with switch
  source/_integrations/juicenet.markdown
Labels: Hacktoberfest, has-parent, new-feature, next

#11063 Improve scene docs
  source/_integrations/scene.markdown
Labels: Hacktoberfest, current, has-parent, parent-merged

#11111 Add meet-up Rhein-Main area
  source/state-of-the-union/index.markdown
Labels: current

#11072 fix missing climate temperature_low/high_state_tpl
  source/_integrations/climate.mqtt.markdown
Labels: awaits-parent, has-parent, next

#11113 Add livestream meetup in Berlin to state of the union page
  source/state-of-the-union/index.markdown
Labels: current

#10574 Add info about torrents that is accessible with templating
  source/_integrations/transmission.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged

#10836 Update with added options for multiple event types and emulated key hold events.
  source/_integrations/keyboard_remote.markdown
Labels: Hacktoberfest, has-parent, next, parent-merged

#10839 Update the stop attribute type to string
  source/_integrations/nextbus.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#10720 Add documentation for Unifi LED integration
  source/_integrations/unifiled.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-integration, next, parent-merged

#10907 Add Presence Netatmo Camera services (set_light_auto, set_light_on, s…
  source/_integrations/netatmo.markdown
Labels: Hacktoberfest, has-parent, new-feature, next, parent-merged

#11103 Add WLED integration
  source/_integrations/wled.markdown
  source/images/supported_brands/wled.png
Labels: has-parent, new-integration, next, parent-merged

#11115 Automation example for Lutron integration
  source/_integrations/lutron.markdown
Labels: current

#10998 Precise some config details for HomematicIP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: Hacktoberfest, current

#11105 Update automation.markdown
  source/getting-started/automation.markdown
Labels: current

#11095 Add switches (on/off) for geniushub outlets
  source/_integrations/geniushub.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#11099 Improve scene.create service
  source/_integrations/scene.markdown
Labels: has-parent, next, parent-merged

#11004 Plugwise docs updated to match pull-request #28237
  source/_integrations/plugwise.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next, parent-merged

#10604 Clarify how to connect to Elk over serial port
  source/_integrations/elkm1.markdown
Labels: Hacktoberfest, current, ready-for-review

#10531 Updates proximity documentation
  source/_integrations/proximity.markdown
Labels: Hacktoberfest, current, ready-for-review

#11125 Fix Owntracks link
  source/_integrations/device_tracker.markdown
Labels: current

#11127 Fix quoting in examples
  source/_integrations/harmony.markdown
Labels: current

#11126 Update shell_command.markdown
  source/_integrations/shell_command.markdown
Labels: current

#10852 Update for new veto_files option
  source/_addons/samba.markdown
Labels: Hacktoberfest, current, in-progress

#11120 Add switch platform to WLED integration
  source/_integrations/wled.markdown
Labels: has-parent, new-feature, next, parent-merged

#11129 Fix `nmap` command to scan UDP port.
  source/_integrations/xiaomi_aqara.markdown
Labels: current

#11138 change packages to monofont
  source/hassio/installation.markdown
Labels: current

#11128 Add sensor platform to WLED integration
  source/_integrations/wled.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11146 Add SotU 2019 YouTube details
  source/state-of-the-union/index.markdown
Labels: current

#11145 Update samsungtv.markdown to add a device to the list of those that don't work
  source/_integrations/samsungtv.markdown
Labels: next

#11121 Add optional name for clarity when using multiple SAJ solar inverters
  source/_integrations/saj.markdown
Labels: has-parent, next, parent-merged

#10336 new component: pcal9535a
  source/_components/pcal9535a.markdown
Labels: has-parent, in-progress, new-integration, next, parent-merged

#11148 Add location of installed macos configs
  source/_docs/autostart/macos.markdown
Labels: current

#11143 Update slack.markdown
  source/_integrations/slack.markdown
Labels: current

#11144 Update testing.markdown
  source/_docs/mqtt/testing.markdown
Labels: current

#11141 Add another custom state detection example
  source/_integrations/androidtv.markdown
Labels: current

#11136 MODBUS Component: Fix write_register service attribute (name -> hub)
  source/_integrations/modbus.markdown
Labels: current

#11134 Update deconz.markdown
  source/_integrations/deconz.markdown
Labels: current

#11140 direct link to api_version
  source/_integrations/freebox.markdown
Labels: current

#11131 clarified setup instructions for Spotify
  source/_integrations/spotify.markdown
Labels: current

#10580 fix: allow docs to build on Win platform
  Gemfile
  Gemfile.lock
  sass/oscailte/_oscailte.scss
  sass/oscailte/custom/_README.scss
Labels: Hacktoberfest, current

#10703 Add service documentation for verisure
  source/_integrations/verisure.markdown
Labels: Hacktoberfest, has-parent, needs-rebase, next, parent-merged

#11133 Remove host/netsh commands from docker directives
  source/_docs/installation/docker.markdown
Labels: current, in-progress

#11150 Fix custom state detection example
  source/_integrations/androidtv.markdown
Labels: current

#11154 pcal9535a: move to integrations
  source/_integrations/pcal9535a.markdown
Labels: next

#11157 Add iOS/macOS certificate requirements
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
Labels: current

#11161 Minimize configuration sample
  source/_integrations/season.markdown
Labels: current

#10756 Add azure servicebus documentation
  source/_integrations/azure_service_bus.markdown
  source/images/supported_brands/azure_service_bus.svg
Labels: Hacktoberfest, has-parent, new-integration, next, parent-merged

#11173 Include link to pre-configured app names
  source/_integrations/androidtv.markdown
Labels: current

#11167 PEP8: fix style
  source/_docs/ecosystem/appdaemon.markdown
Labels: current

#11165 small syntax style fix
  source/_docs/configuration/templating.markdown
Labels: current

#11166 Add description for Update Switch
  source/_integrations/tesla.markdown
Labels: current

#11172 small rephrase
  source/_integrations/emulated_hue.markdown
Labels: current

#11171 Provide examples of location and station for waqi
  source/_integrations/waqi.markdown
Labels: current

#11182 Neato: added IoT class
  source/_integrations/neato.markdown
Labels: current

#11179 Add headings
  source/_integrations/waqi.markdown
Labels: current

#11183 PCAL9535A typo correction: binary_sensors are inputs
  source/_integrations/pcal9535a.markdown
Labels: next

#11177 typo error
  source/_docs/configuration/templating.markdown
Labels: current

#11197 Updated link to mvg-live
  source/_integrations/mvglive.markdown
Labels: current

#11198 Add how XBox Live sensors are named.
  source/_integrations/xbox_live.markdown
Labels: current

#11199 Add note for disco lights when HA is running
  source/_docs/z-wave/device-specific.markdown
Labels: current

#11050 Insolvency warning removed
  source/_integrations/nello.markdown
Labels: Hacktoberfest, current

#11193 Update lacrosse.markdown
  source/_integrations/lacrosse.markdown
Labels: current

#11192 Add remarks about floor heating actuators of HMIP
  source/_integrations/homematicip_cloud.markdown
Labels: current

#11190 `value_template` added to configuration
  source/_integrations/scrape.markdown
Labels: current

#11188 Update freebox documentation
  source/_integrations/freebox.markdown
Labels: current

#11185 Update wled.markdown
  source/_integrations/wled.markdown
Labels: next

#11178 Change in just a layout
  source/_docs/mqtt/discovery.markdown
Labels: current

#11204 Added new details
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#11175 Update zha.markdown - Suggest alternative ways of adding devices
  source/_integrations/zha.markdown
Labels: current

#11187 Update panasonic_viera to include broadcast_address
  source/_integrations/panasonic_viera.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#11130 Add support for Hisense AEH-W4A1
  source/_integrations/hisense_aehw4a1.markdown
  source/images/supported_brands/hisense.png
Labels: has-parent, in-progress, next, parent-merged

#11201 Add broadcast address for WOL and samsungtv
  source/_integrations/samsungtv.markdown
Labels: has-parent, next, parent-merged

#11208 No longer feature Arduino and Wemo
  source/_integrations/arduino.markdown
  source/_integrations/wemo.markdown
Labels: current

#10848 Working without entities: conversion example added
  source/_integrations/template.markdown
Labels: Hacktoberfest, current, in-progress

#11169 Update ombi.markdown
  source/_integrations/ombi.markdown
Labels: has-parent, next, parent-merged

#11159 Add docs for forthcoming SimpliSafe locks
  source/_integrations/simplisafe.markdown
Labels: has-parent, next, parent-merged

#11205 Rename configuration variable
  source/_integrations/wake_on_lan.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11181 Update to clarify path declaration in lovelace config
  source/_integrations/cast.markdown
Labels: current, in-progress

#11213 Fix a spelling error in container reference to avoid confusion.
  source/_docs/configuration/troubleshooting.markdown
Labels: current

#11214 fix copy switch example
  source/_integrations/switch.template.markdown
Labels: current

#11061 Lovelace: add visible example for views
  source/lovelace/views.markdown
Labels: Hacktoberfest, current

#11217 Update Vivotek camera
  source/_integrations/vivotek.markdown
Labels: has-parent, new-feature, next, parent-merged

#11216 Update comfoconnect.markdown
  source/_integrations/comfoconnect.markdown
Labels: has-parent, next, parent-merged

#11222 Add docs for scene editor
  source/_docs/ecosystem.markdown
  source/_docs/scene.markdown
  source/_docs/scene/editor.markdown
  source/_docs/scene/scenegen.markdown
  source/_includes/asides/docs_navigation.html
  source/images/docs/scenes/editor.png
Labels: has-parent, next, parent-merged

#11225 Remove warning about api_password
  source/_integrations/api.markdown
Labels: current

#11104 Added roomba delay configuration
  source/_integrations/roomba.markdown
Labels: has-parent, next, parent-merged

#11226 Update Hassio beta instructions
  source/hassio/installation.markdown
Labels: current

#11227 Update links for dresden elektronik ConBee/RaspBee
  source/_integrations/zha.markdown
Labels: current

#9658 Add documentation for VersaSense
  source/_integrations/versasense.markdown
  source/images/supported_brands/versasense.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11224 Pulseaudio: Changed default port from 4712 to 4713
  source/_integrations/pulseaudio_loopback.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11228 Update 'other machine types' section in docs
  source/hassio/installation.markdown
Labels: current

#11231 Clarify which are the global settings
  source/_integrations/device_tracker.markdown
Labels: current

#11236 Add breaking change descriptions
  source/_posts/2019-11-20-release-102.markdown
Labels: blog, rc

#11237 Frontend release notes
  source/_posts/2019-11-20-release-102.markdown
  source/images/blog/2019-11-0.102/thingtalk-automation.png
Labels: blog, rc

#11241 Update category to notifications
  source/_integrations/azure_service_bus.markdown
Labels: current

#11239 Service call works with additional panel(s)
  source/_integrations/envisalink.markdown
Labels: current

#11244 Update unifiled.markdown
  source/_integrations/unifiled.markdown
Labels: current

#11252 Fixed missing change from "automation" to "scene"
  source/_docs/scene/editor.markdown
Labels: current

#11257 clarification of round modes
  source/_docs/configuration/templating.markdown
Labels: has-parent, next, parent-merged

#11258 info about another supported device
  source/_integrations/upc_connect.markdown
Labels: current

#11256 get the state correctly
  source/_integrations/switch.template.markdown
Labels: current

#11255 Creating a scene by snapshotting entities
  source/_integrations/scene.markdown
Labels: has-parent, next, parent-merged

#11264 Clarify configuration element location
  source/_integrations/spotify.markdown
Labels: current

#11263 File name refactor and permissions revision
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
Labels: current

#11260 Update fan.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
Labels: current

#11262 update picotts installation for Buster
  source/_integrations/picotts.markdown
Labels: current, in-progress

#11265 Update mosquitto.markdown
  source/_addons/mosquitto.markdown
Labels: current

#11268 Add logo
  source/_integrations/gc100.markdown
  source/_integrations/orangepi_gpio.markdown
  source/_integrations/ssdp.markdown
  source/_integrations/zeroconf.markdown
  source/images/supported_brands/global-cache.png
  source/images/supported_brands/orange-pi.png
Labels: current

#11267 Fix yaml markdown
  source/_integrations/switcher_kis.markdown
Labels: current

#11278 Addition of MU6400 TV Testing
  source/_integrations/samsungtv.markdown
Labels: current

#11276 Update yi.markdown
  source/_integrations/yi.markdown
Labels: current

#11287 adds Raspberry Pi 4 images in the version integration
  source/_integrations/version.markdown
Labels: has-parent, next, parent-merged

#11285 Add ha_iot_class to comfoconnect
  source/_integrations/comfoconnect.markdown
Labels: current

#11280 clarify setup procedure
  source/_integrations/notify.markdown
Labels: current

#11270 Update snips installation command in documentation
  source/_integrations/snips.markdown
Labels: current

#11289 Update uptimerobot.markdown
  source/_integrations/uptimerobot.markdown
Labels: current
