Repository home-assistant/home-assistant.io, pull requests merged in 2020-07, with the labels that each got.

#13875 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#13874 0.112 Release notes
  _config.yml
  source/_posts/2020-07-01-release-112.markdown
  source/images/blog/2020-07-0.112/configure-mqtt.png
  source/images/blog/2020-07-0.112/datetime-picker.png
  source/images/blog/2020-07-0.112/logbook-who.png
  source/images/blog/2020-07-0.112/new-home.png
  source/images/blog/2020-07-0.112/social.png
  source/images/blog/2020-07-0.112/zha-device.png
Labels: in-progress, needs-rebase, rc

#13883 fix typo
  source/_integrations/hvv_departures.markdown
Labels: current

#13882 Added Marantz NR1602 to list of supported devices
  source/_integrations/denonavr.markdown
Labels: current

#13881 Point to new location of Logs in System Log docs
  source/_integrations/system_log.markdown
Labels: current, has-parent

#13880 Remove Logs and Info from Developer Tools docs
  source/_docs/tools/dev-tools.markdown
Labels: current, has-parent

#13879 Add M-CR511/M-CR611 to supported device list
  source/_integrations/denonavr.markdown
Labels: current

#13889 Fix typo condition examples in 0.112 release notes
  source/_posts/2020-07-01-release-112.markdown
Labels: blog, current

#13891 Add a new receiver that works
  source/_integrations/denonavr.markdown
Labels: current

#13895 Update smappee.markdown with missing subscription note
  source/_integrations/smappee.markdown
Labels: current

#13892 Add links to iOS and Android repos on Help page
  source/help/index.markdown
Labels: current

#13905 DenonAVR: Remove timeout wich is not configurable anymore
  source/_integrations/denonavr.markdown
Labels: current

#13851 Add humidifier support to emulated_hue
  source/_integrations/emulated_hue.markdown
Labels: has-parent, new-feature, next, parent-merged

#13893 Add join actions
  source/_integrations/joaoapps_join.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13873 Add humidifier support to homekit
  source/_integrations/homekit.markdown
Labels: has-parent, new-feature, next, parent-merged

#13855 Add humidifier support to google_assistant
  source/_integrations/google_assistant.markdown
Labels: has-parent, new-feature, next, parent-merged

#13798 Add legacy polling option for Amcrest motion detection
  source/_integrations/amcrest.markdown
Labels: has-parent, new-feature, next, parent-merged

#13689 Add water heater set timer service info
  source/_integrations/tado.markdown
Labels: has-parent, new-feature, next, parent-merged

#13465 Document the 'androidtv.learn_sendevent' service
  source/_integrations/androidtv.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13885 Add Hue manual bridge config flow + options flow
  source/_integrations/hue.markdown
Labels: has-parent, new-feature, next, parent-merged

#13911 Fix incomplete quotations in Vacuum.MQTT docs
  source/_integrations/vacuum.mqtt.markdown
Labels: current

#13910 Fix spelling in Sensor.MQTT docs
  source/_integrations/sensor.mqtt.markdown
Labels: current

#13909 Update ZHA docs with its new location under Integrations
  source/_integrations/zha.markdown
Labels: current

#13915 Update samsungtv.markdown
  source/_integrations/samsungtv.markdown
Labels: current

#13842 Added the documentation for a new component - poolsense
  source/_integrations/poolsense.markdown
Labels: has-parent, new-integration, next, parent-merged

#13901 Add new automation configuration options
  source/_docs/automation.markdown
Labels: has-parent, new-feature, next, parent-merged

#13913 Document UUID white list for cast integration
  source/_integrations/cast.markdown
Labels: has-parent, new-feature, next, parent-merged

#13900 Tado climate entity timer service
  source/_integrations/tado.markdown
Labels: has-parent, new-feature, next, parent-merged

#12777 Add Dexcom integration documentation
  source/_integrations/dexcom.markdown
Labels: has-parent, new-integration, next, parent-merged

#13903 Add documentation for new Bond integration
  source/_integrations/bond.markdown
Labels: has-parent, new-integration, next, parent-merged

#13868 Plugwise: include info w.r.t. Zeroconf discovery
  source/_integrations/plugwise.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13859 Add new script configuration options
  source/_integrations/script.markdown
  source/images/integrations/script/script_figures.pptx
  source/images/integrations/script/script_modes.jpg
  source/images/integrations/script/script_wait.jpg
Labels: has-parent, in-progress, next, parent-merged

#13926 Bump minimist to 1.2.5
  package-lock.json
  package.json
Labels: current, security

#13928 Update raspberry-pi.markdown
  source/_docs/installation/raspberry-pi.markdown
Labels: current

#13932 Add a working model to samsung TV integration
  source/_integrations/samsungtv.markdown
Labels: current

#13908 Document config flow for smarthab integration
  source/_integrations/smarthab.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13843 Add support for glob matching in InfluxDB filters
  source/_integrations/influxdb.markdown
Labels: has-parent, new-feature, next, parent-merged

#13936 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#13939 Clarification on internal_url
  source/_integrations/home_connect.markdown
Labels: current

#13953 Update iOS beta link
  source/ios/beta.markdown
Labels: current

#13950 OZW usercode documentation
  source/_integrations/ozw.markdown
Labels: has-parent, new-feature, next

#13957 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#13955 Update screenshots to match latest appearance
  source/images/screenshots/configuration-validation.png
  source/images/screenshots/developer-tools.png
Labels: current

#13934 Document new repeat script action
  source/_docs/scripts.markdown
Labels: has-parent, new-feature, next, parent-merged

#13971 Remove legacy script mode and simplify remaining modes
  source/_docs/automation.markdown
  source/_integrations/script.markdown
  source/images/integrations/script/script_figures.pptx
  source/images/integrations/script/script_modes.jpg
Labels: has-parent, next

#13974 Etekcity VeSync example code fix
  source/_integrations/vesync.markdown
Labels: current

#13982 Fix typo in Arcam docs
  source/_integrations/arcam_fmj.markdown
Labels: current

#13977 Remove "whitelist" term
  source/_integrations/cast.markdown
Labels: current

#13980 customize media player
  source/_docs/configuration/customizing-devices.markdown
Labels: current

#13979 added model RU7170
  source/_integrations/samsungtv.markdown
Labels: current

#13951 Update dialogflow.markdown
  source/_integrations/dialogflow.markdown
Labels: current

#13968 Remove old services icon
  source/_integrations/humidifier.markdown
Labels: current

#13978 Point users towards mysql without pymysql first.
  source/_integrations/recorder.markdown
Labels: current

#13912 Add missing `unique_id` part to Vacuum.MQTT docs
  source/_integrations/vacuum.mqtt.markdown
Labels: current

#13907 Add missing `unique_id` part to Switch MQTT docs
  source/_integrations/switch.mqtt.markdown
Labels: current

#13984 Resolve YAML error for media_player
  source/_docs/configuration/customizing-devices.markdown
Labels: current

#13985 Fix boolean vs string in scene YAML examples
  source/_docs/scene.markdown
  source/_integrations/scene.markdown
Labels: current

#13972 Reworded section on pulling attributes from JSON
  source/_integrations/rest.markdown
Labels: current

#13958 Fix doc style
  source/_integrations/google_assistant.markdown
Labels: current

#13860 Add docs for posting remote files to Slack
  source/_integrations/slack.markdown
Labels: has-parent, in-progress, next, parent-merged

#13993 🔨 Change url to other repository
  source/_cookbook/configuration_yaml_by_klaasnicolaas.markdown
Labels: current

#13992 Rename whitelist_external_dirs
  source/_docs/configuration/basic.markdown
  source/_integrations/blink.markdown
  source/_integrations/camera.markdown
  source/_integrations/file.markdown
  source/_integrations/filesize.markdown
  source/_integrations/folder.markdown
  source/_integrations/folder_watcher.markdown
  source/_integrations/logi_circle.markdown
  source/_integrations/minio.markdown
  source/_integrations/nfandroidtv.markdown
  source/_integrations/slack.markdown
  source/_integrations/stream.markdown
  source/_integrations/telegram.markdown
  source/_integrations/transmission.markdown
  source/_integrations/vivotek.markdown
  source/_lovelace/picture-entity.markdown
  source/_posts/2017-07-02-release-48.markdown
Labels: has-parent, next

#13983 Template urlencode
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13063 Add Netatmo public weather sensors documentation
  source/_integrations/netatmo.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13960 OZW usercode documentation revision
  source/_integrations/ozw.markdown
Labels: has-parent, new-feature, next, parent-merged

#13959 Updating to recent Appearances and Config Changes
  source/_docs/authentication.markdown
  source/_docs/tools/dev-tools.markdown
  source/getting-started/presence-detection.markdown
  source/images/docs/authentication/profile.png
Labels: current

#13956 Adjust documentation for change of event
  source/_integrations/binary_sensor.rfxtrx.markdown
  source/_integrations/cover.rfxtrx.markdown
  source/_integrations/light.rfxtrx.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/sensor.rfxtrx.markdown
  source/_integrations/switch.rfxtrx.markdown
Labels: has-parent, new-feature, next, parent-merged

#13870 Update plum_lightpad docs to mention flow config
  source/_integrations/plum_lightpad.markdown
Labels: current, has-parent, in-progress, new-feature, parent-merged

#13902 Add Amcrest audio_detected binary sensor
  source/_integrations/amcrest.markdown
Labels: has-parent, next, parent-merged

#13925 Add harmony remote example to universal media player
  source/_integrations/universal.markdown
Labels: has-parent, new-feature, next, parent-merged

#13894 Update calendar.google.markdown
  source/_integrations/calendar.google.markdown
Labels: current

#13890 Update "Info" location in Reporting Issues page
  source/help/reporting_issues.markdown
Labels: current, has-parent, in-progress, needs-rebase

#13897 trusted_network default auth_provider info
  source/_docs/authentication/providers.markdown
Labels: current

#13976 Rxftrx drop platform config
  source/_integrations/binary_sensor.rfxtrx.markdown
  source/_integrations/cover.rfxtrx.markdown
  source/_integrations/light.rfxtrx.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/sensor.rfxtrx.markdown
  source/_integrations/switch.rfxtrx.markdown
  source/_redirects
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13884 Add current temperature as seperate sensor in Toon
  source/_integrations/toon.markdown
Labels: has-parent, new-feature, next

#12020 Optimistic switch template
  source/_integrations/switch.template.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13931 MQTT birth and will messages are published by default
  source/_docs/mqtt/birth_will.markdown
Labels: has-parent, new-feature, next, parent-merged

#13994 Add script choose action
  source/_docs/scripts.markdown
Labels: has-parent, new-feature, next, parent-merged

#13929 Document MQTT availability list
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13724 Update syncthru for config flow
  source/_integrations/ssdp.markdown
  source/_integrations/syncthru.markdown
Labels: has-parent, in-progress, next, parent-merged

#13930 Support empty output of MQTT binary_sensor value_template
  source/_integrations/binary_sensor.mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged

#13997 Deprecate `extra_module_url` in frontend
  source/_integrations/frontend.markdown
Labels: awaits-parent, has-parent, next

#13853 Refactor Enocean part 1
  source/_integrations/enocean.markdown
Labels: has-parent, next, parent-merged

#13998 Add ozw.set_config_parameter service
  source/_integrations/ozw.markdown
Labels: has-parent, new-feature, next, parent-merged

#13999 Update cover.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
Labels: next

#13878 Add demo humidifier
  source/_integrations/demo.markdown
Labels: current, has-parent, in-progress, needs-rebase, parent-merged

#13919 Add missing Lovelace Humidifier card docs
  source/_lovelace/humidifier.markdown
  source/lovelace/index.markdown
Labels: current

#13636 Humidifier lovelace card
  source/_lovelace/humidifier.markdown
  source/images/lovelace/lovelace_humidifier_card.png
Labels: current, has-parent, new-feature, parent-merged

#13995 Always expose Toon gas sensors
  source/_integrations/toon.markdown
Labels: has-parent, new-feature, next, parent-merged

#13964 Add HmIP-FSI16 to HomematicIP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14003 Add warning about logbook entries created with logbook.log without a domain or entity_id being filtered
  source/_integrations/logbook.markdown
Labels: current

#14002 New button card option: show_state
  source/_lovelace/button.markdown
Labels: has-parent, new-feature, next, parent-merged

#14005 Correct how to disable MQTT birth and will messages
  source/_docs/mqtt/birth_will.markdown
Labels: next

#14007 Support for ipv6 being disabled in zeroconf
  source/_integrations/zeroconf.markdown
Labels: has-parent, next

#14009 Change default automation mode
  source/_docs/automation.markdown
Labels: has-parent, next

#14001 Beta release notes for 0.113
  _config.yml
  source/_posts/2020-07-01-release-113.markdown
  source/images/blog/2020-07-0.113/automation-modes.png
  source/images/blog/2020-07-0.113/script-name.png
Labels: blog, in-progress, rc

#14012 Update samsungtv.markdown
  source/_integrations/samsungtv.markdown
Labels: current

#13981 Add doc for new `ignore_attributes` option
  source/_integrations/influxdb.markdown
Labels: has-parent, new-feature, next, parent-merged

#14013 Uptime Robot offers a read-only API Key
  source/_integrations/uptimerobot.markdown
Labels: current

#14008 Configuration Variable Redesign
  plugins/configuration.rb
  sass/custom/_paulus.scss
Labels: current

#14015 Add Denon AVR-X1600H
  source/_integrations/denonavr.markdown
Labels: current

#14022 Add theme changes to release notes
  source/_posts/2020-07-01-release-113.markdown
Labels: rc

#14021 Add a Misssing 'A'
  source/_integrations/alexa.smart_home.markdown
Labels: current

#14023 Update sensor.command_line.markdown
  source/_integrations/sensor.command_line.markdown
Labels: current

#14019 Fix misspelled theme name in footer.
  source/_includes/site/footer.html
Labels: current

#14020 Update 2020-07-01-release-113.markdown
  source/_posts/2020-07-01-release-113.markdown
Labels: in-progress, needs-rebase, rc

#14016 Update upb.markdown
  source/_integrations/upb.markdown
Labels: current

#14010 Basic Configuration for Editors + Weather Card as example
  plugins/configuration_basic.rb
  source/_lovelace/weather-forecast.markdown
Labels: current

#13723 Adds median to min_max component
  source/_integrations/min_max.markdown
Labels: has-parent, new-feature, next

#14034 Update samsungtv.markdown with additional TV model
  source/_integrations/samsungtv.markdown
Labels: current

#14033 Update samsungtv.markdown
  source/_integrations/samsungtv.markdown
Labels: current

#14024 Add note about HassOS
  source/_integrations/hddtemp.markdown
Labels: current

#13941 Add documentation for Control4 integration
  source/_integrations/control4.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#13495 Change pi_hole services
  source/_integrations/pi_hole.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12917 Add WolfLink SmartSet documentation
  source/_integrations/wolflink.markdown
Labels: has-parent, new-integration, next, parent-merged

#14036 Add support for other miio device tokens
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#13508 Add Firmata integration docs
  source/_integrations/firmata.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#14041 Delete python.markdown
  source/_docs/installation/python.markdown
Labels: current

#14058 Fixed description of 'check_zone'
  source/_integrations/alarmdecoder.markdown
Labels: current

#13738 Update light.markdown with default transition
  source/_integrations/light.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14059 Explain what happens to calling script when called script has errors
  source/_integrations/script.markdown
Labels: in-progress, needs-rebase, next

#14056 Release blog post 0.113
  source/_posts/2020-07-01-release-113.markdown
  source/images/blog/2020-07-0.113/social.png
Labels: blog, in-progress, needs-rebase, rc

#14062 Typos release notes
  source/_posts/2020-07-01-release-113.markdown
Labels: current

#14028 Update Bond documentation to include all applicable categories
  source/_integrations/bond.markdown
Labels: current

#14063 Add info for creation codes which will behave as lights in the GUI
  source/_integrations/rfxtrx.markdown
Labels: current

#14064 Clarify where to get email address + short links + 1 grammar correction
  source/_integrations/html5.markdown
Labels: current, in-progress

#14071 Mention tensorflow breakage in 0.113
  source/_posts/2020-07-01-release-113.markdown
Labels: current

#13082 Add opentherm_gw.set_central_heating_ovrd documentation
  source/_integrations/opentherm_gw.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#14075 Improve examples in 0.113 blog post
  source/_posts/2020-07-01-release-113.markdown
Labels: current

#14074 Fix door, window and tyre names
  source/_integrations/volvooncall.markdown
Labels: current

#14068 Update dynalite.markdown
  source/_integrations/dynalite.markdown
Labels: current

#14069 Update starline.markdown
  source/_integrations/starline.markdown
Labels: current

#14066 One-sentence explanation with link to vendor site
  source/_integrations/bond.markdown
Labels: current

#14078 0.113.1
  _config.yml
  source/_posts/2020-07-01-release-113.markdown
Labels: blog, current

#14077 Change XboxAPI.com to xapi.us
  source/_integrations/xbox_live.markdown
Labels: current, has-parent, parent-merged

#14080 Fix repeat & choose action descriptions
  source/_docs/scripts.markdown
Labels: current

#14032 HomeKit now supports multiple camera streams
  source/_integrations/homekit.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14081 Update zwave installation network key information
  source/_docs/z-wave/installation.markdown
Labels: current

#13857 Add documentation for AccuWeather integration
  source/_integrations/accuweather.markdown
Labels: awaits-parent, has-parent, new-integration, next

#12755 Add Azure DevOps Integration
  source/_integrations/azure_devops.markdown
Labels: has-parent, new-integration, next, parent-merged

#14083 Add average_speed and doors_tailgate_open to voc resource list
  source/_integrations/volvooncall.markdown
Labels: has-parent, new-feature, next, parent-merged

#13324 Add Abode camera on and off support and remove old notes
  source/_integrations/abode.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14042 Add update available binary sensor to Tesla
  source/_integrations/tesla.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14088 fix typo in mg/dL unit
  source/_integrations/dexcom.markdown
Labels: current

#14087 Update discovery.markdown
  source/_docs/mqtt/discovery.markdown
Labels: current

#14082 Attempt to update documentation about how to setup lights vs switches
  source/_integrations/rfxtrx.markdown
Labels: current

#14079 Amcrest features need to be enabled in order for them to work properly.
  source/_integrations/amcrest.markdown
Labels: current

#14093 Update Volumio documentation with config flow
  source/_integrations/volumio.markdown
Labels: has-parent, new-feature, next, parent-merged

#14097 Adding new supported Freebox router
  source/_integrations/freebox.markdown
Labels: current

#14096 Update foscam_away_mode_PTZ.markdown
  source/_cookbook/foscam_away_mode_PTZ.markdown
Labels: current
