Repository home-assistant/home-assistant.io, pull requests merged in 2020-02, with the labels that each got.

#11943 Add Community Highlight suggest form
  source/_posts/2020-01-31-community-highlights.markdown
  source/_redirects
Labels: blog, current

#11953 🎨 Give Ecobee new logo
  source/images/supported_brands/ecobee.png
Labels: current

#11946 Just a couple of quick typos
  source/_integrations/fritzbox.markdown
Labels: current

#11945 Update air_quality.xiaomi_miio.markdown
  source/_integrations/air_quality.xiaomi_miio.markdown
Labels: has-parent, next, parent-merged

#11937 Update changelog.markdown
  source/lovelace/changelog.markdown
Labels: next

#11950 Adjust example
  source/_integrations/input_datetime.markdown
Labels: current

#11949 Added location where learned codes can be found
  source/_integrations/broadlink.markdown
Labels: current

#11942 Update nmap parameter to use -sn instead of -sP
  source/_integrations/nmap_tracker.markdown
Labels: current

#11941 Update sighthound.markdown
  source/_integrations/sighthound.markdown
Labels: next

#11939 move note about check config
  source/getting-started/configuration.markdown
Labels: current

#11925 Update tahoma documentation to add support for somfy's smart lock.
  source/_integrations/tahoma.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11905 Added opening and closing states to the MQTT cover
  source/_integrations/cover.mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged

#11883 Update new scan_interval default for Tesla
  source/_integrations/tesla.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11955 Add mqtt.dump docs
  source/_docs/mqtt/service.markdown
  source/_integrations/mqtt.markdown
Labels: has-parent, new-feature, next, parent-merged

#11957 Update mikrotik.markdown
  source/_integrations/mikrotik.markdown
Labels: next

#11863 Support multiple attachments in signal messenger integration
  source/_integrations/signal_messenger.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11235 Added parameter time to search for a specific trip time.
  source/_integrations/nederlandse_spoorwegen.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11811 Document salt device_tracker platform
  source/_integrations/salt.markdown
  source/images/supported_brands/salt.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11160 Add functions to TotalConnect
  source/_integrations/totalconnect.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#10427 Add documentation for new opnsense integration
  source/_integrations/opnsense.markdown
  source/images/supported_brands/opnsense.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11952 Added VSX-528 as a supported device
  source/_integrations/pioneer.markdown
Labels: has-parent, new-feature, next, parent-merged

#11948 Drop fritzdect integration
  source/_integrations/fritzdect.markdown
  source/_posts/2017-02-11-alert-appletv-mqtt-yeelight.markdown
  source/_posts/2017-07-29-release-50.markdown
  source/_posts/2017-10-21-release-56.markdown
  source/_posts/2018-01-27-release-62.markdown
  source/_posts/2018-08-29-release-77.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2020-01-15-release-104.markdown
  source/_redirects
Labels: next, parent-merged

#11959 Add missing sensors to list of supported sensors
  source/_integrations/danfoss_air.markdown
Labels: current, has-parent

#11935 Update Vizio docs to reflect improved discovery
  source/_integrations/vizio.markdown
Labels: current

#11964 Breaking change descriptions
  source/_posts/2020-02-05-release-105.markdown
Labels: rc

#11965 Update pvoutput.markdown
  source/_integrations/pvoutput.markdown
Labels: current

#11958 Add color to light template
  source/_integrations/light.template.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11944 Add telegram_chatbot `timeout` parametr.
  source/_integrations/telegram_chatbot.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11843 Fix the NS API and product name
  source/_integrations/nederlandse_spoorwegen.markdown
Labels: has-parent, next, parent-merged

#11963 Derivative component update, add time_window
  source/_integrations/derivative.markdown
Labels: has-parent, new-feature, next, parent-merged

#11967 Add missing icon option for light-card
  source/_lovelace/light.markdown
Labels: current, has-parent

#11974 fixed nginx configuration for subdomains
  source/_docs/ecosystem/nginx_subdomain.markdown
Labels: current

#11973 Document brightness step for light.turn_on
  source/_integrations/light.markdown
Labels: has-parent, new-feature, next

#11971 one more example of configuring packages folder
  source/_docs/configuration/packages.markdown
Labels: current

#11977 Adds safe_mode integration documentation
  source/_integrations/safe_mode.markdown
Labels: has-parent, new-integration, next

#11978 Adds search integration documentation
  source/_integrations/search.markdown
Labels: has-parent, new-integration, next

#11816 Document filtering of sources for Android TV
  source/_integrations/androidtv.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11980 Add closing backticks
  source/_posts/2020-02-05-release-105.markdown
Labels: rc

#11987 Update hue.markdown
  source/_integrations/hue.markdown
Labels: current

#11985 Add state_color option to entities card
  source/_lovelace/entities.markdown
Labels: current, has-parent

#11982 Remove false new netatmo platform item
  source/_posts/2020-02-05-release-105.markdown
Labels: current

#11981 duration is (supposedly) an optional attr
  source/_docs/mqtt/service.markdown
Labels: current

#11975 Add a dash before `platform:’ in sht31.markdown
  source/_integrations/sht31.markdown
Labels: current

#11970 added note about name variable
  source/_integrations/history_stats.markdown
Labels: current, in-progress

#11990 ssl: to verify_ssl:
  source/_integrations/mikrotik.markdown
Labels: current

#11996 typo SST STT
  source/_integrations/stt.markdown
Labels: current

#11994 fixed spelling error
  source/_integrations/marytts.markdown
Labels: current

#11983 Update streamlabswater.markdown
  source/_integrations/streamlabswater.markdown
Labels: current, in-progress

#11997 Minor typo in sms.markdown
  source/_integrations/sms.markdown
Labels: current

#11509 Add support for belgian meter and rename some sensors
  source/_integrations/dsmr.markdown
  source/_integrations/utility_meter.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11989 Remove the liveboxplaytv integration (ADR0004)
  CODEOWNERS
  source/_integrations/liveboxplaytv.markdown
  source/_posts/2017-02-11-alert-appletv-mqtt-yeelight.markdown
  source/_posts/2017-10-07-release-55.markdown
  source/_posts/2017-10-21-release-56.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2017-12-17-release-60.markdown
  source/_posts/2018-04-14-release-67.markdown
  source/_posts/2018-07-21-release-74.markdown
  source/_posts/2019-05-16-release-93.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2020-01-15-release-104.markdown
  source/_redirects
  source/images/supported_brands/orange.png
Labels: has-parent, next

#11995 Updated provider name in blockchain.markdown
  source/_integrations/blockchain.markdown
Labels: has-parent, next

#12000 Add link for manual installer
  source/_docs/installation.markdown
Labels: current

#12004 Fix typo in alarm control panel markdown
  source/_integrations/alarm_control_panel.markdown
Labels: current

#12001 Removed Samsung TV
  source/_integrations/discovery.markdown
Labels: current

#12010 Community Highlights, 2nd edition
  source/_posts/2020-02-07-community-highlights.markdown
  source/images/blog/2020-02-07-community-highlights/social.png
Labels: blog, current

#12009 Fixed incorrect type of `client_secret` in Netatmo docs.
  source/_integrations/netatmo.markdown
Labels: current

#12011 Change reference of hass.io to supervisor
  source/_docs/z-wave/installation.markdown
Labels: current

#12021 Correct MQTT Lock Default States
  source/_integrations/lock.mqtt.markdown
Labels: current, has-parent

#12033 Unfeature wink.
  source/_integrations/wink.markdown
Labels: current

#12034 Update yeelight.markdown
  source/_integrations/yeelight.markdown
Labels: current

#12029 Update discovery documentation for google cast
  source/_integrations/discovery.markdown
Labels: current, has-parent

#12026 Update lets_encrypt.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: current

#12018 Update synology.markdown
  source/_docs/installation/synology.markdown
Labels: current, in-progress

#12008 Added troubleshooting info
  source/_integrations/spotify.markdown
Labels: current, in-progress

#12041 Fix typo
  source/_docs/installation/synology.markdown
Labels: current

#12038 Updated remaining references to certbot-auto
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: current

#12017 Correct Evohome integration docs
  source/_integrations/evohome.markdown
Labels: current

#12042 Fixed URL Formatting
  source/_integrations/streamlabswater.markdown
Labels: current

#12035 Added instructions to pick qemu targets if no specific target
  source/hassio/installation.markdown
Labels: current

#12045 Fix incorrect description with Modbus switch example
  source/_integrations/switch.modbus.markdown
Labels: current

#12046 Change description double-tap
  source/lovelace/header-footer.markdown
Labels: current

#11474 Add config flow to Meteo-France
  source/_integrations/meteo_france.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11956 Add GDACS feed integration
  source/_integrations/gdacs.markdown
  source/_integrations/geo_location.markdown
  source/images/screenshots/gdacs-alerts-feed-map.png
  source/images/screenshots/gdacs-alerts-sensor.png
  source/images/supported_brands/gdacs.jpg
Labels: has-parent, new-integration, next, parent-merged

#11815 Documentation for Minecraft Server Integration
  source/_integrations/minecraft_server.markdown
  source/images/supported_brands/minecraft.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11954 Abode water valve support
  source/_integrations/abode.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12023 Add recorder vars db_max_retries and db_retry_wait
  source/_integrations/recorder.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#12025 Added technical sensors
  source/_integrations/spc.markdown
Labels: has-parent, next, parent-merged

#11962 Update configuration for Sure Petcare integration and add a new way to get the IDs
  source/_integrations/surepetcare.markdown
  source/images/integrations/surepetcare/spc_ids.png
Labels: has-parent, new-feature, next, parent-merged

#12013 Respiration type entities are disabled by default
  source/_integrations/garmin_connect.markdown
Labels: has-parent, next, parent-merged

#11930 Add documentation for MELCloud integration
  source/_integrations/melcloud.markdown
Labels: has-parent, new-integration, next, parent-merged

#10866 Dynalite Integration Documentation
  source/_integrations/dynalite.markdown
  source/images/supported_brands/dynalite.png
Labels: Hacktoberfest, has-parent, new-integration, next, parent-merged

#12036 Update Modbus binary sensor docs
  source/_integrations/binary_sensor.modbus.markdown
Labels: has-parent, new-feature, next, parent-merged

#12049 Update uk_transport.markdown
  source/_integrations/uk_transport.markdown
Labels: current

#12050 Update glances.markdown
  source/_integrations/glances.markdown
Labels: has-parent, new-feature, next, parent-merged

#12051 Add support for Texas Instruments CC to ZHA
  source/_integrations/zha.markdown
Labels: has-parent, new-feature, next, parent-merged

#11979 Time section: wording clarified, urls updated
  source/_docs/configuration/templating.markdown
Labels: current

#12054 🔨 disable_turn_off is a boolean
  source/_integrations/device_sun_light_trigger.markdown
Labels: current

#12059 Android 1.6 & 1.7 blog
  source/_posts/2020-02-11-android-16-17-release.markdown
  source/images/blog/2020-02-android-16-17-release/garage.png
Labels: current

#12058 Update tplink.markdown
  source/_integrations/tplink.markdown
Labels: current

#12057 Update binary sensor docs with icon coloring changes
  source/_integrations/binary_sensor.markdown
Labels: current, has-parent

#12055 Update python_script.markdown
  source/_integrations/python_script.markdown
Labels: current

#12053 Update sms.markdown
  source/_integrations/sms.markdown
Labels: current

#11986 Update installation.markdown
  source/hassio/installation.markdown
Labels: current

#12060 Document restrictions on allowed characters in MQTT discovery topics.
  source/_docs/mqtt/discovery.markdown
Labels: current

#11992 Multiple Tado accounts
  source/_integrations/tado.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12062 Small tweaks to Android release blog post
  source/_posts/2020-02-11-android-16-17-release.markdown
Labels: blog, current

#12061 Adds text linting, check & fix common misspellings
  .github/workflows/test.yml
  .textlintrc.json
  package-lock.json
  package.json
  source/_integrations/garmin_connect.markdown
  source/_integrations/marytts.markdown
  source/_integrations/openuv.markdown
Labels: current

#12063 Adds Terminology Textlint plugin, fixes use of Home Assistant
  .textlintrc.json
  package-lock.json
  package.json
  source/_cookbook/track_battery_level.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/ecosystem/notebooks/database.markdown
  source/_docs/installation/armbian.markdown
  source/_docs/installation/synology.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/z-wave/installation.markdown
  source/_integrations/bh1750.markdown
  source/_integrations/blink.markdown
  source/_integrations/bme280.markdown
  source/_integrations/bme680.markdown
  source/_integrations/climate.knx.markdown
  source/_integrations/cover.rfxtrx.markdown
  source/_integrations/environment_canada.markdown
  source/_integrations/hdmi_cec.markdown
  source/_integrations/history_stats.markdown
  source/_integrations/homematic.markdown
  source/_integrations/homematicip_cloud.markdown
  source/_integrations/htu21d.markdown
  source/_integrations/knx.markdown
  source/_integrations/light.knx.markdown
  source/_integrations/london_air.markdown
  source/_integrations/nad.markdown
  source/_integrations/proxmoxve.markdown
  source/_integrations/pushetta.markdown
  source/_integrations/raspihats.markdown
  source/_integrations/solax.markdown
  source/_integrations/stream.markdown
  source/_integrations/tof.markdown
  source/_integrations/wink.markdown
  source/_integrations/xmpp.markdown
  source/_integrations/zha.markdown
Labels: current

#12065 Extends textlint Terminology list
  .textlintrc.json
  source/_docs/asterisk_mbox.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/scripts/service-calls.markdown
  source/_integrations/aftership.markdown
  source/_integrations/airvisual.markdown
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/alarmdecoder.markdown
  source/_integrations/amcrest.markdown
  source/_integrations/arlo.markdown
  source/_integrations/camera.ffmpeg.markdown
  source/_integrations/darksky.markdown
  source/_integrations/deconz.markdown
  source/_integrations/ecobee.markdown
  source/_integrations/ffmpeg_motion.markdown
  source/_integrations/ffmpeg_noise.markdown
  source/_integrations/google_travel_time.markdown
  source/_integrations/pandora.markdown
  source/_integrations/panel_iframe.markdown
  source/_integrations/rflink.markdown
  source/_integrations/stream.markdown
  source/_integrations/zha.markdown
  source/_lovelace/picture-entity.markdown
  source/lovelace/changelog.markdown
  source/lovelace/index.markdown
Labels: current

#12069 Extends textlint Terminology list; part 3
  .textlintrc.json
  source/_docs/autostart/synology.markdown
  source/_docs/ecosystem/appdaemon/updating.markdown
  source/_docs/ecosystem/nginx.markdown
  source/_docs/installation/docker.markdown
  source/_docs/installation/synology.markdown
  source/_integrations/android_ip_webcam.markdown
  source/_integrations/apcupsd.markdown
  source/_integrations/aruba.markdown
  source/_integrations/asuswrt.markdown
  source/_integrations/aurora.markdown
  source/_integrations/avion.markdown
  source/_integrations/dlna_dmr.markdown
  source/_integrations/doods.markdown
  source/_integrations/emoncms.markdown
  source/_integrations/fail2ban.markdown
  source/_integrations/fritz.markdown
  source/_integrations/fritzbox.markdown
  source/_integrations/fritzbox_callmonitor.markdown
  source/_integrations/fritzbox_netmonitor.markdown
  source/_integrations/fritzdect.markdown
  source/_integrations/homekit.markdown
  source/_integrations/html5.markdown
  source/_integrations/iperf3.markdown
  source/_integrations/konnected.markdown
  source/_integrations/luci.markdown
  source/_integrations/nut.markdown
  source/_integrations/openwrt.markdown
  source/_integrations/recorder.markdown
  source/_integrations/recswitch.markdown
  source/_integrations/solax.markdown
  source/_integrations/soundtouch.markdown
  source/_integrations/ubus.markdown
  source/_integrations/zha.markdown
  source/hassio/installation.markdown
Labels: current

#12052 Options for header and footer moved to Card itself
  source/_lovelace/entities.markdown
Labels: current

#12070 Extends textlint Terminology list; part 4
  .textlintrc.json
  source/_docs/autostart/upstart.markdown
  source/_integrations/deconz.markdown
  source/_integrations/fan.xiaomi_miio.markdown
  source/_integrations/flux_led.markdown
  source/_integrations/lcn.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lirc.markdown
  source/_integrations/media_player.markdown
  source/_integrations/nad.markdown
  source/_integrations/picotts.markdown
  source/_integrations/plex.markdown
  source/_integrations/rpi_gpio_pwm.markdown
  source/_integrations/skybell.markdown
  source/_integrations/slack.markdown
  source/_integrations/streamlabswater.markdown
  source/_integrations/switch.xiaomi_miio.markdown
  source/_integrations/switchbot.markdown
  source/_integrations/twilio.markdown
  source/_integrations/unifi.markdown
  source/_integrations/unifi_direct.markdown
  source/_integrations/unifiled.markdown
  source/_integrations/uvc.markdown
  source/_integrations/versasense.markdown
  source/_integrations/vivotek.markdown
  source/_integrations/webostv.markdown
  source/_integrations/yamaha.markdown
  source/_integrations/yeelight.markdown
  source/_integrations/zha.markdown
Labels: current

#11993 Update index.markdown
  source/hassio/index.markdown
Labels: current, in-progress

#12077 time section: tweaks
  source/_docs/configuration/templating.markdown
Labels: current

#12066 Add comment about the somfy cover to work well.
  source/_integrations/cover.rfxtrx.markdown
Labels: current

#12078 Update docs for Modbus climate
  source/_integrations/climate.modbus.markdown
Labels: current

#12079 Adds locked_out.md
  source/_docs/locked_out.md
Labels: current, in-progress

#12080 Adds link to locked_out
  source/_docs/authentication.markdown
Labels: current

#12082 Extends textlint Terminology list; part 7
  .textlintrc.json
  source/_docs/installation/armbian.markdown
  source/_docs/locked_out.md
  source/_docs/mqtt/broker.markdown
  source/_integrations/androidtv.markdown
  source/_integrations/dialogflow.markdown
  source/_integrations/discovery.markdown
  source/_integrations/kodi.markdown
  source/_integrations/onkyo.markdown
  source/_integrations/squeezebox.markdown
  source/_integrations/universal.markdown
Labels: current

#12083 Update parameter name in Modbus climate
  source/_integrations/climate.modbus.markdown
Labels: current, has-parent

#12081 Add documentation for SimpliSafe events
  source/_integrations/simplisafe.markdown
Labels: awaits-parent, has-parent, new-feature, next

#12085 Mention the possibility of missing energy sensor
  source/_integrations/melcloud.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12088 Apple TV: Update link to pyatv documentation
  source/_integrations/apple_tv.markdown
Labels: current

#11809 Add "mode" attribute to IPMA
  source/_integrations/ipma.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12089 Update nuki.markdown
  source/_integrations/nuki.markdown
Labels: current

#12075 Add lg_netcast turn_on_action configuration variable
  source/_integrations/lg_netcast.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12087 Update fritzbox_netmonitor.markdown
  source/_integrations/fritzbox_netmonitor.markdown
Labels: current

#12095 Fixed a typo
  source/_integrations/recorder.markdown
Labels: current

#12107 Adjust working on Fast.com capabilities
  source/_integrations/fastdotcom.markdown
Labels: current

#12103 Minor spelling correction.
  source/_integrations/google_maps.markdown
Labels: current

#12102 Fix greeneye_monitor sample to match docs. Fixes #12099
  source/_integrations/greeneye_monitor.markdown
Labels: current

#12101 Link to companion docs
  source/_integrations/mobile_app.markdown
Labels: current

#12100 Update redirects for new Companion App structure
  source/_redirects
Labels: current

#12105 Eight Sleep, add POD support, sleep fitness sensor
  source/_integrations/eight_sleep.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11868 Added documentation for the Vilfo Router integration
  source/_integrations/vilfo.markdown
  source/images/supported_brands/vilfo.png
Labels: has-parent, new-integration, next, parent-merged

#12108 Extends textlint Terminology list; part 8
  .textlintrc.json
  source/_integrations/discovery.markdown
  source/_integrations/fritzbox_netmonitor.markdown
  source/_integrations/upnp.markdown
  source/_integrations/yamaha.markdown
Labels: current

#10642 Docs for tado water heater
  source/_integrations/tado.markdown
Labels: has-parent, new-feature, next, parent-merged

#10955 Add support for older models of Eagle
  source/_integrations/rainforest_eagle.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#11895 Update and rename entity-button.markdown to button.markdown
  source/_lovelace/button.markdown
  source/_redirects
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12071 Update onewire integration docs
  source/_integrations/onewire.markdown
Labels: has-parent, in-progress, next, parent-merged

#12110 Allow specifying icon for a script
  source/_integrations/script.markdown
Labels: has-parent, new-feature, next, parent-merged

#12111 Add a scene icon
  source/_integrations/scene.markdown
Labels: has-parent, new-feature, next, parent-merged

#12113 Add missing Zone to Default Configuration integration
  source/_integrations/default_config.markdown
Labels: current

#12114 Remove duke_energy integration (ADR-0004)
  source/_integrations/duke_energy.markdown
  source/_posts/2018-07-21-release-74.markdown
  source/_posts/2019-12-11-release-103.markdown
  source/_redirects
  source/images/supported_brands/duke_energy.png
Labels: has-parent, next

#12117 Release OS 3.11 & 4.3
  .textlintrc.json
  source/_integrations/automatic.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/getting-started/index.markdown
  source/hassio/installation.markdown
Labels: current

#12121 Added breaking change descriptions for 0.106.0
  source/_posts/2020-02-26-release-106.markdown
Labels: rc

#12123 Fix MFA notify subheading
  source/_docs/authentication/multi-factor-auth.markdown
Labels: current

#12115 Add docs for SimpliSafe system notifications
  source/_integrations/simplisafe.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12116 Add register type to Modbus climate docs
  source/_integrations/climate.modbus.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12028 Add host option for rpi_gpio_pwm component
  source/_integrations/rpi_gpio_pwm.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11853 Adjust twitch integration configuration
  source/_integrations/twitch.markdown
Labels: has-parent, new-feature, next, parent-merged

#11690 jewish_calendar component: Add support for displaying Daf Yomi
  source/_integrations/jewish_calendar.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12122 Frontend release notes for 0.106
  source/_posts/2020-02-26-release-106.markdown
  source/images/blog/2020-02-0.106/entities.png
  source/images/blog/2020-02-0.106/more-info-person.png
  source/images/blog/2020-02-0.106/sensor-card.png
Labels: rc

#12093 Fix Modbus climate example config
  source/_integrations/climate.modbus.markdown
Labels: current, has-parent

#11785 Konnected Pro Board support and config flow
  source/_integrations/konnected.markdown
Labels: has-parent, next, parent-merged

#12125 Add documentation for new option state_color
  source/_lovelace/button.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/picture-elements.markdown
Labels: has-parent, new-feature, next, parent-merged

#12127 Add community highlights 3rd edition
  source/_posts/2020-02-07-community-highlights.markdown
  source/_posts/2020-02-19-community-highlights.markdown
  source/images/blog/2020-02-19-community-highlights/social.png
  source/images/blog/2020-02-19-community-highlights/vscode.png
Labels: blog, current

#12128 Adding a note about states
  source/_docs/automation/trigger.markdown
Labels: current

#12136 Update 2020-02-26-release-106.markdown
  source/_posts/2020-02-26-release-106.markdown
Labels: rc
