Repository home-assistant/home-assistant.io, pull requests merged in 2020-03, with the labels that each got.

#12213 Fix MQTT trigger automation_type documentation.
  source/_integrations/device_trigger.mqtt.markdown
Labels: current

#12218 Corrected the typo of the example configuration
  source/_integrations/geonetnz_volcano.markdown
Labels: current

#12219 Update updater.markdown
  source/_integrations/updater.markdown
Labels: current

#12210 Add file.write and YAML information - Slack integration
  source/_integrations/slack.markdown
Labels: current

#12232 Updated the velbus logo
  source/images/supported_brands/velbus.png
Labels: current

#12228 Update supported devices in configuration example
  source/_integrations/zha.markdown
Labels: current

#12224 lights changed to light
  source/_docs/configuration/yaml.markdown
Labels: next

#12223 MQTT vacuum JSON template
  source/_integrations/vacuum.mqtt.markdown
Labels: current

#12215 Update ping.markdown
  source/_integrations/ping.markdown
Labels: current

#12209 added locations that are not supported
  source/_integrations/gdacs.markdown
Labels: current

#12211 Extra information added for the Slack notifyer
  source/_integrations/slack.markdown
Labels: current

#12212 Fix missing mqtt platform declaration in device tracker example
  source/_integrations/device_tracker.mqtt.markdown
Labels: current

#12198 Update release post to mention all breaking changes
  source/_posts/2020-02-26-release-106.markdown
Labels: current, has-parent

#12202 Rest sensors to support "text/xml" or "application/xml" per rfc2376
  source/_integrations/rest.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11137 Add tankerkoenig integration
  source/_integrations/tankerkoenig.markdown
  source/images/supported_brands/tankerkoenig.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#12019 Optimistic mode
  source/_integrations/somfy.markdown
Labels: has-parent, new-feature, next, parent-merged

#12166 Add docs for AirVisual config entry
  source/_integrations/airvisual.markdown
Labels: has-parent, new-feature, next, parent-merged

#11867 Add Avri documentation
  source/_integrations/sensor.avri.markdown
  source/images/supported_brands/avri.jpeg
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#12197 Update integration doc to mention all breaking changes
  source/_integrations/surepetcare.markdown
Labels: current, has-parent

#11988 Update docs with instructions on using config flow to pair vizio devices and update integration name
  source/_integrations/vizio.markdown
Labels: has-parent, new-feature, next, parent-merged

#12040 Updated markdown to use updated syntax
  source/_integrations/uk_transport.markdown
Labels: current, in-progress

#12235 Update ping.markdown
  source/_integrations/ping.markdown
Labels: current

#12236 add note about sun.before and after
  source/_docs/scripts/conditions.markdown
Labels: current

#12237 add notes about payload_xxx, state_xxx and value_template
  source/_integrations/switch.mqtt.markdown
Labels: current

#12229 Tap action page
  source/_includes/asides/lovelace_navigation.html
  source/_lovelace/button.markdown
  source/_lovelace/entities.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
  source/_lovelace/picture.markdown
  source/lovelace/actions.markdown
  source/lovelace/header-footer.markdown
Labels: current

#12243 Add 0.106.3 release blog + Coronavirus integration
  source/_integrations/coronavirus.markdown
  source/_posts/2020-02-26-release-106-3.markdown
  source/images/blog/2020-03-0.106.3/components.png
  source/images/blog/2020-03-0.106.3/screenshot.png
  source/images/blog/2020-03-0.106.3/social.png
  source/images/supported_brands/coronavirus.png
Labels: blog, current, has-parent, in-progress, new-integration

#12178 Update cert_expiry for #32066
  source/_integrations/cert_expiry.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12242 allow_unlock is deprecated
  source/_integrations/google_assistant.markdown
Labels: current

#12251 Remove double entry that is not a valid resource
  source/_integrations/nut.markdown
Labels: current

#12248 Update locked_out.md with a new solution
  source/_docs/locked_out.md
Labels: current

#12254 Add clarification about docker installation
  source/_docs/installation/docker.markdown
Labels: current

#12255 Temporary workaround to make last-release redirect work
  source/latest-release-notes/index.html
Labels: current

#12256 Fix spelling error in blog post title
  source/_posts/2020-02-26-release-106-3.markdown
Labels: current

#12263 Fix typo
  source/_integrations/safe_mode.markdown
Labels: current

#12260 Reduce weight of integrations page + list everything once
  sass/custom/_component_page.scss
  source/integrations/index.html
Labels: current

#12262 Update demo docs
  source/_integrations/demo.markdown
Labels: current

#12259 Update Card Descriptions - Current Branch
  source/_lovelace/alarm-panel.markdown
  source/_lovelace/button.markdown
  source/_lovelace/conditional.markdown
  source/_lovelace/entities.markdown
  source/_lovelace/entity-filter.markdown
  source/_lovelace/gauge.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/history-graph.markdown
  source/_lovelace/horizontal-stack.markdown
  source/_lovelace/iframe.markdown
  source/_lovelace/map.markdown
  source/_lovelace/markdown.markdown
  source/_lovelace/media-control.markdown
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
  source/_lovelace/picture.markdown
  source/_lovelace/plant-status.markdown
  source/_lovelace/sensor.markdown
  source/_lovelace/shopping-list.markdown
  source/_lovelace/thermostat.markdown
  source/_lovelace/vertical-stack.markdown
  source/_lovelace/weather-forecast.markdown
Labels: current, has-parent

#12258 Added SAN to the example openssl command
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
Labels: current

#12216 Table to better understand ZHA Radio Types & HW
  source/_integrations/zha.markdown
Labels: current, in-progress

#11877 QVR Pro documentation
  source/_integrations/qvr_pro.markdown
  source/images/supported_brands/qvr_pro.png
Labels: has-parent, new-integration, next, parent-merged

#12257 Remove obsolete mobile page
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/frontend/mobile.markdown
  source/_includes/asides/docs_navigation.html
  source/_redirects
  source/images/screenshots/android-homescreen-guide.gif
Labels: cleanup, current

#12267 corrected path to home-assistant repo
  source/_integrations/github.markdown
Labels: current

#12266 Add category Binary Sensor
  source/_integrations/command_line.markdown
Labels: current

#11325 New EDL21 integration
  source/_integrations/edl21.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#12214 add sms to pushbullet doc
  source/_integrations/pushbullet.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#12183 Update sighthound.markdown
  source/_integrations/sighthound.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12153 Emoncms API now provides a Unit of Measurement
  source/_integrations/emoncms.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12269 Remove option and update media player compatibility for Plex
  source/_integrations/plex.markdown
Labels: has-parent, next, parent-merged

#12227 Dynalite - addition of switch platform
  source/_integrations/dynalite.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11984 Add Abode CUE support
  source/_integrations/abode.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12281 Fix broken link
  source/hassio/index.markdown
Labels: current

#12271 Clarity edit
  source/_integrations/device_tracker.markdown
Labels: current

#12273 Update updating.markdown
  source/_docs/installation/updating.markdown
Labels: current

#12239 Add details around configuration and options flow
  source/_integrations/konnected.markdown
Labels: current

#12282 history_stats: update examples
  source/_integrations/history_stats.markdown
Labels: current

#12276 Add support for images from Brands
  source/_includes/asides/component_navigation.html
  source/integrations/index.html
Labels: current

#12285 Cleanup of orphan supported brand images
  source/images/supported_brands/Ryobi.png
  source/images/supported_brands/avahi.png
  source/images/supported_brands/conversation.png
  source/images/supported_brands/docker.png
  source/images/supported_brands/downloader.png
  source/images/supported_brands/eff.png
  source/images/supported_brands/heat-control.png
  source/images/supported_brands/iss.png
  source/images/supported_brands/python.svg
  source/images/supported_brands/updater.png
  source/images/supported_brands/verizon.png
  source/images/supported_brands/windows.png
  source/images/supported_brands/woonveilig.png
Labels: cleanup, current

#12290 New image for Media Player Lovelace Docs
  source/images/lovelace/lovelace_mediaplayer.png
Labels: has-parent, next

#12296 Migrate MQTT integration to brands + add ha_domain
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/notify.group.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: current

#12297 Fixed documentation for window_size parameter of filter sensor
  source/_integrations/filter.markdown
Labels: current

#12226 Add config_flow to shopping_list
  source/_integrations/shopping_list.markdown
Labels: awaits-parent, has-parent, new-feature, next

#12274 Remove discovery and legacy file for Plex
  source/_integrations/plex.markdown
Labels: has-parent, next, parent-merged

#10797 Adds information for OwnTracks friends via HTTP
  source/_integrations/owntracks.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, next, parent-merged

#12245 Update docs to include app related config changes for vizio integration
  source/_integrations/vizio.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12295 Migrate KNX integration to brands + add ha_domain
  source/_integrations/binary_sensor.knx.markdown
  source/_integrations/climate.knx.markdown
  source/_integrations/cover.knx.markdown
  source/_integrations/knx.markdown
  source/_integrations/light.knx.markdown
  source/_integrations/notify.knx.markdown
  source/_integrations/scene.knx.markdown
  source/_integrations/sensor.knx.markdown
  source/_integrations/switch.knx.markdown
  source/_posts/2016-07-16-sqlalchemy-knx-join-simplisafe.markdown
  source/images/supported_brands/knx.png
Labels: current

#12293 Migrate Xiaomi integrations to brands + add ha_domain
  source/_integrations/air_quality.xiaomi_miio.markdown
  source/_integrations/binary_sensor.xiaomi_aqara.markdown
  source/_integrations/cover.xiaomi_aqara.markdown
  source/_integrations/device_tracker.xiaomi.markdown
  source/_integrations/fan.xiaomi_miio.markdown
  source/_integrations/light.xiaomi_aqara.markdown
  source/_integrations/lock.xiaomi_aqara.markdown
  source/_integrations/remote.xiaomi_miio.markdown
  source/_integrations/sensor.xiaomi_aqara.markdown
  source/_integrations/sensor.xiaomi_miio.markdown
  source/_integrations/switch.xiaomi_aqara.markdown
  source/_integrations/switch.xiaomi_miio.markdown
  source/_integrations/vacuum.xiaomi_miio.markdown
  source/images/supported_brands/xiaomi.png
Labels: current

#12294 Migrate template integration to brands + add ha_domain
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/binary_sensor.template.markdown
  source/_integrations/cover.template.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/light.template.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/vacuum.template.markdown
Labels: current

#12298 Remove non-existing openwrt integration page
  source/_integrations/openwrt.markdown
Labels: cleanup, current

#12300 minor typo correction
  source/_integrations/alexa.smart_home.markdown
Labels: current

#12301 Link to source/alerts based on ha_domain
  source/_includes/asides/component_navigation.html
Labels: current

#12302 Text clamp integration cards
  sass/custom/_component_page.scss
Labels: current

#12306 Migrate Google integrations to brands
  source/_includes/custom/grid_item_left.html
  source/_integrations/androidtv.markdown
  source/_integrations/cast.markdown
  source/_integrations/google_domains.markdown
  source/_integrations/google_translate.markdown
  source/_posts/2016-05-21-release-020.markdown
  source/_posts/2016-11-05-hacktoberfest-influxdb-weather.markdown
  source/images/supported_brands/androidtv.png
  source/images/supported_brands/google.png
  source/images/supported_brands/google_calendar.png
  source/images/supported_brands/google_cast.png
  source/images/supported_brands/google_domains.png
  source/images/supported_brands/gpmdp.png
Labels: current

#12307 Update pair-finish to include required ch_type
  source/_integrations/vizio.markdown
Labels: current

#12309 Fix link for manual installer
  source/_docs/installation.markdown
Labels: current

#12310 Correct args for asterisk_mbox service
  source/_docs/asterisk_mbox.markdown
Labels: current

#12222 Document MQTT schemas
  source/_integrations/light.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: current, in-progress

#12313 Update CalDAV documentation
  source/_integrations/caldav.markdown
Labels: current

#12308 Update thinkingcleaner docs with static ip option
  source/_integrations/thinkingcleaner.markdown
Labels: awaits-parent, has-parent, new-feature, next

#12318 Typo in caldav
  source/_integrations/caldav.markdown
Labels: current

#12319 Migrate FFMPEG integrations to brands
  source/_posts/2016-08-13-foursquare-fast-com-ffmpeg-gpsd.markdown
  source/images/supported_brands/ffmpeg.png
Labels: current

#12320 Migrate Microsoft integrations to brands
  source/_integrations/microsoft.markdown
  source/_integrations/microsoft_face.markdown
  source/_integrations/microsoft_face_detect.markdown
  source/_integrations/microsoft_face_identify.markdown
  source/images/supported_brands/microsoft.png
Labels: current

#12323 Add frontend release notes
  source/_posts/2020-03-release-107.markdown
  source/images/blog/2020-03-0.107/helper-config-dialog.png
  source/images/blog/2020-03-0.107/lovelace-config-panel.png
  source/images/blog/2020-03-0.107/new-media-control-card.png
Labels: rc

#12247 Remove port from configuration
  source/_integrations/samsungtv.markdown
Labels: has-parent, next, parent-merged

#12278 Remove facebook broadcast api
  source/_integrations/facebook.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#12316 Docs for recorder commit_interval
  source/_integrations/recorder.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11557 Update onvif.markdown
  source/_integrations/onvif.markdown
Labels: has-parent, new-feature, next, parent-merged

#12321 Removed unnecessary punctuation.
  source/_integrations/utility_meter.markdown
Labels: current

#12124 Work day fix
  source/_integrations/workday.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12240 Add support for Ubee Router DVW32CB
  source/_integrations/ubee.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#11630 Docs for IAMMETER devices
  source/_integrations/iammeter.markdown
  source/images/supported_brands/iammeter-logo.png
Labels: has-parent, in-progress, new-integration, next, parent-merged

#12268 remove $ marks from code lines for copy/pasting
  source/_docs/autostart/systemd.markdown
Labels: current

#11596 New integration: Ezviz camera
  source/_integrations/ezviz.markdown
  source/images/supported_brands/ezviz.png
Labels: has-parent, new-integration, next, parent-merged

#12272 Update slack.markdown
  source/_integrations/slack.markdown
Labels: current, in-progress

#12032 Update sonos.markdown
  source/_integrations/sonos.markdown
Labels: current

#12284 Replace "docs" with "documentation"
  .textlintrc.json
  source/_docs/installation/docker.markdown
  source/_docs/installation/virtualenv.markdown
  source/_docs/tools/credstash.markdown
  source/_docs/z-wave/devices.markdown
  source/_faq/missing-documentation.markdown
  source/_includes/site/header.html
  source/_integrations/alarmdecoder.markdown
  source/_integrations/automation.markdown
  source/_integrations/aws.markdown
  source/_integrations/bom.markdown
  source/_integrations/dialogflow.markdown
  source/_integrations/envisalink.markdown
  source/_integrations/habitica.markdown
  source/_integrations/html5.markdown
  source/_integrations/hue.markdown
  source/_integrations/ifttt.markdown
  source/_integrations/mailgun.markdown
  source/_integrations/minio.markdown
  source/_integrations/rocketchat.markdown
  source/_integrations/twilio.markdown
  source/_integrations/xs1.markdown
  source/_lovelace/picture-elements.markdown
  source/lovelace/changelog.markdown
Labels: current

#12149 Integrations/Map - Added a note on how to hide certain entities.
  source/_integrations/map.markdown
Labels: current

#12315 Update ssdp.markdown to add "(UPnP)"
  source/_integrations/ssdp.markdown
Labels: current, in-progress

#12324 Updated google_assistant.markdown: added `/r/YOUR_PROJECT_ID` to redirect_uri
  source/_integrations/google_assistant.markdown
Labels: current

#12159 Add MELCloud Air-to-Water device documentation
  source/_integrations/melcloud.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12327 breaking change descriptions added
  source/_posts/2020-03-18-release-107.markdown
Labels: rc

#12329 Fix Hue documentation
  source/_integrations/hue.markdown
Labels: bug, current

#12314 Add Presence Detection example to august
  source/_integrations/august.markdown
Labels: has-parent, new-feature, next, parent-merged

#12326 add calibrate service
  source/_integrations/utility_meter.markdown
Labels: has-parent, next, parent-merged

#12151 Add attribute parameter to label-state
  source/_lovelace/picture-elements.markdown
Labels: has-parent, new-feature, next, parent-merged

#12312 Documentation for griddy integration
  source/_integrations/griddy.markdown
Labels: has-parent, new-integration, next, parent-merged

#12332 Add docs for multiple dashboard and resources in yaml mode
  source/lovelace/yaml-mode.markdown
Labels: has-parent, new-feature, next

#12181 directv config flow related changes
  source/_integrations/directv.markdown
  source/_integrations/ssdp.markdown
Labels: has-parent, new-feature, next, parent-merged

#12325 Fetch iCloud family devices only when wanted
  source/_integrations/icloud.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12334 Initial release blog post for 0.107
  source/_posts/2020-03-18-release-107.markdown
  source/images/blog/2020-03-0.107/components.png
  source/images/blog/2020-03-0.107/helper-config-dialog.png
  source/images/blog/2020-03-0.107/lovelace-config-panel.png
  source/images/blog/2020-03-0.107/lovelace-edit-improvements.gif
  source/images/blog/2020-03-0.107/new-media-control-card.png
Labels: blog, rc

#11712 Refactor Freebox : add config flow + temperature sensor + signal dispatch
  source/_integrations/freebox.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12340 📚 Remove Hass.io reference
  source/_integrations/tellstick.markdown
Labels: current

#12339 📚 Remove hass.io reference
  source/_integrations/influxdb.markdown
Labels: current

#12338 📚 Remove Hass.io reference
  source/_integrations/alexa.flash_briefings.markdown
Labels: current

#12337 📚 Update Hass.io references on addons page
  source/addons/index.html
Labels: current

#12336 📚 Rename Hass.io on main docs page
  source/docs/index.markdown
Labels: current

#12335 UniFi - Remove references to manual configuration
  source/_integrations/unifi.markdown
Labels: awaits-parent, has-parent, new-feature, next

#12346 Update Alexa Smart Home Timer to include start and cancel.
  source/_integrations/alexa.smart_home.markdown
Labels: has-parent, new-feature, next

#12345 Update Alexa Smart Home Light to include brightness, color, temperature
  source/_integrations/alexa.smart_home.markdown
Labels: current

#12348 📚 Remove Hass.io references
  source/_integrations/recorder.markdown
Labels: current

#12351 📚 Remove Hass.io reference - tradfri
  source/_integrations/tradfri.markdown
Labels: current

#12350 📚 Remove Hass.io references for http page
  source/_integrations/http.markdown
Labels: current

#12355 Cosmetic improvements and correction
  source/_integrations/hue.markdown
Labels: current, has-parent

#12358 📚 Remove Hass.io reference - Deconz
  source/_integrations/deconz.markdown
Labels: current

#12356 📚 Remove Hass.io Reference - Glossary
  source/_data/glossary.yml
Labels: current

#12252 Update rtorrent.markdown
  source/_integrations/rtorrent.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11892 Add service to Velbus
  source/_integrations/velbus.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12362 Update opnsense.markdown
  source/_integrations/opnsense.markdown
Labels: current

#12369 Update discovery.markdown
  source/_docs/mqtt/discovery.markdown
Labels: current

#12371 Added Logicgroup ZDB5100 Matrix
  source/_docs/z-wave/device-specific.markdown
Labels: current

#12361 Fix default tankerkoenig radius
  source/_integrations/tankerkoenig.markdown
Labels: in-progress, next

#12378 Community Highlights, 5th edition
  source/_posts/2020-03-15-community-highlights.markdown
  source/images/blog/2020-03-15-community-highlights/marine-aquariums.png
  source/images/blog/2020-03-15-community-highlights/social.png
Labels: blog, current

#12385 Open GitHub link in new tab
  source/_includes/edit_github.html
Labels: current

#12363 FIx typo in homematic.markdown
  source/_integrations/homematic.markdown
Labels: current

#12387 Sidebar
  source/_includes/asides/docs_navigation.html
  source/_includes/asides/hassio_navigation.html
Labels: current

#12367 Update Abode quality scale and minor clean up
  source/_integrations/abode.markdown
Labels: has-parent, next

#12384 example updated
  source/_docs/automation/trigger.markdown
Labels: current

#12231 Update AlarmDecoder Docs
  source/_integrations/alarmdecoder.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12292 Update roku for config flow
  source/_integrations/roku.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12354 Config flow for rachio
  source/_integrations/rachio.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#12388 Add 'Yeelight LED Ceiling Light' model
  source/_integrations/yeelight.markdown
Labels: awaits-parent, has-parent, new-feature, next

#12359 Remove emulated_hue_hidden from customizing devices as its deprecation is complete
  source/_docs/configuration/customizing-devices.markdown
Labels: has-parent, in-progress, next, parent-merged

#12377 Update instructions regarding Docker on Mac and USB passthrough
  source/_docs/installation/docker.markdown
Labels: current

#12400 update wording/terms
  source/_integrations/binary_sensor.mqtt.markdown
Labels: current

#12402 Increase prominence of whitelist_external_dirs note
  source/_integrations/filesize.markdown
Labels: current

#12409 Fix link to sensor templates in tplink documentation
  source/_integrations/tplink.markdown
Labels: current

#12412 Clarify supported systems for Supervised, improve installation instructions
  source/hassio/installation.markdown
Labels: cleanup, current

#12411 add note about time
  source/_docs/scripts/conditions.markdown
Labels: current

#12415 fix spelling appdeamon to Appdaemon
  source/_docs/ecosystem/appdaemon/tutorial.markdown
Labels: current

#12418 Migrate directv logo to brands.
  source/_integrations/directv.markdown
  source/images/supported_brands/directv.png
Labels: current

#12414 Migrate roku logo to brands
  source/_integrations/roku.markdown
  source/images/supported_brands/roku.png
Labels: has-parent, next
