Repository home-assistant/home-assistant.io, pull requests merged in 2020-10, with the labels that each got.

#14675 Add Denon AVR-X3700H
  source/_integrations/denonavr.markdown
Labels: Hacktoberfest, current

#14673 Updated markdown
  source/_docs/scripts.markdown
Labels: Hacktoberfest, current

#14672 Update discovery.markdown
  source/_docs/mqtt/discovery.markdown
Labels: current

#14674 Remove two broken links
  source/_includes/asides/docs_navigation.html
  source/help/index.markdown
Labels: Hacktoberfest, current

#14669 Fix broken links on website (part 1)
  source/_integrations/fail2ban.markdown
  source/_posts/2017-08-26-release-0-52.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2019-12-11-release-103.markdown
  source/_posts/2020-01-15-release-104.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14677 Remove broken url.
  source/_integrations/ifttt.markdown
Labels: Hacktoberfest, current

#14680 Update knx.markdown
  source/_integrations/knx.markdown
Labels: Hacktoberfest, current

#14681 Update broken link
  source/_integrations/vacuum.markdown
Labels: Hacktoberfest, current

#14678 Add context to event trigger documentation
  source/_docs/automation/trigger.markdown
Labels: Hacktoberfest, has-parent, next

#14686 Update braviatv.markdown
  source/_integrations/braviatv.markdown
Labels: Hacktoberfest, current

#14695 Blog: Hacktoberfest 2020
  source/_posts/2020-10-01-hacktoberfest-2020.markdown
  source/images/blog/2020-10-01-hacktoberfest-2020/social.png
Labels: Hacktoberfest, blog, current

#14631 Add explanation of the new template `rate_limit` directive.
  source/_docs/configuration/templating.markdown
  source/_integrations/binary_sensor.template.markdown
Labels: has-parent, next

#14708 Add Hacktoberfest to frontpage
  source/images/frontpage/hacktoberfest.png
  source/index.html
Labels: Hacktoberfest, current

#14701 Update spelling in Hacktoberfest Blog Post
  source/_posts/2020-10-01-hacktoberfest-2020.markdown
Labels: Hacktoberfest, current

#14754 Fix link to GPSLogger
  source/_integrations/gpslogger.markdown
Labels: Hacktoberfest, current

#14705 Update mqtt.markdown
  source/_docs/mqtt.markdown
Labels: Hacktoberfest, current

#14733 Fix broken markdown link
  source/_docs/mqtt.markdown
  source/cookbook/index.markdown
Labels: Hacktoberfest, current

#14688 Update opentherm_gw.markdown
  source/_integrations/opentherm_gw.markdown
Labels: Hacktoberfest, current

#14704 Update templating.markdown
  source/_docs/automation/templating.markdown
Labels: Hacktoberfest, current

#14755 Update dublin_bus_transport.markdown
  source/_integrations/dublin_bus_transport.markdown
Labels: Hacktoberfest, current

#14699 Update SSDP URL on Huawei LTE integraion page
  source/_integrations/huawei_lte.markdown
Labels: Hacktoberfest, current

#14744 move configuration redirects
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/customizing-devices.markdown
  source/_docs/configuration/devices.markdown
  source/_docs/configuration/events.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/configuration/platform_options.markdown
  source/_docs/configuration/secrets.markdown
  source/_docs/configuration/securing.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/state_object.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/configuration/yaml.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14684 Update alexa.intent.markdown
  source/_integrations/alexa.intent.markdown
Labels: Hacktoberfest, current

#14756 Fix the link to Dwains Theme
  source/_posts/2020-02-07-community-highlights.markdown
Labels: Hacktoberfest, current

#14757 Fixed broken link
  source/_docs/automation/trigger.markdown
Labels: Hacktoberfest, current

#14687 ✏️ Move installation redirects to file
  source/_docs/installation.markdown
  source/_docs/installation/docker.markdown
  source/_docs/installation/raspberry-pi.markdown
  source/_docs/installation/troubleshooting.markdown
  source/_docs/installation/updating.markdown
  source/_docs/installation/virtualenv.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14749 Fix HVV Departures elevators were added by someone else
  source/_posts/2020-10-07-release-116.markdown
Labels: Hacktoberfest, has-parent, in-progress, needs-rebase, rc

#14748 Updated GitHub URL in footer to home-assistant/core
  source/_includes/site/footer.html
Labels: Hacktoberfest, current

#14758 Update coinmarketcap.markdown
  source/_integrations/coinmarketcap.markdown
Labels: Hacktoberfest, current

#14742 Add IoT Class to Belkin Wemo Integration
  source/_integrations/wemo.markdown
Labels: Hacktoberfest, current

#14759 ✏️ Move automation and backend redirect to file
  source/_docs/automation/action.markdown
  source/_docs/automation/condition.markdown
  source/_docs/automation/examples.markdown
  source/_docs/automation/templating.markdown
  source/_docs/automation/trigger.markdown
  source/_docs/automation/troubleshooting.markdown
  source/_docs/backend/database.markdown
  source/_docs/backend/updater.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14760 Fix QVR Pro link
  source/_integrations/qvr_pro.markdown
Labels: Hacktoberfest, current

#14762 Fix Hyperion link
  source/_integrations/hyperion.markdown
Labels: Hacktoberfest, current

#14764 Updating the Midori URL
  source/_docs/frontend/browsers.markdown
Labels: Hacktoberfest, current

#14766 Removing link to the Snips Forum
  source/_integrations/snips.markdown
Labels: Hacktoberfest, current

#14763 Update heos.markdown
  source/_integrations/heos.markdown
Labels: Hacktoberfest, current

#14761 Update fritzbox.markdown
  source/_integrations/fritzbox.markdown
Labels: Hacktoberfest, current

#14765 ✏️ Move scripts and auth redirect to file
  source/_docs/authentication.markdown
  source/_docs/authentication/multi-factor-auth.markdown
  source/_docs/authentication/providers.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
  source/_docs/scripts/editor.markdown
  source/_docs/scripts/service-calls.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14740 Add IoT Class to NOAA Tides Integration
  source/_integrations/noaa_tides.markdown
Labels: Hacktoberfest, current

#14736 Add IoT class to Shelly integration
  source/_integrations/shelly.markdown
Labels: Hacktoberfest, current

#14735 Add IoT Class to Actiontec Integration
  source/_integrations/actiontec.markdown
Labels: Hacktoberfest, current

#14771 Add IOT class to Duck DNS integration
  source/_integrations/duckdns.markdown
Labels: Hacktoberfest, current

#14714 Add IoT Class for CityBikes integration
  source/_integrations/citybikes.markdown
Labels: Hacktoberfest, current

#14715 Add IoT class for Feedreader integration
  source/_integrations/feedreader.markdown
Labels: Hacktoberfest, current

#14716 Add IoT class for Aurora integration
  source/_integrations/aurora.markdown
Labels: Hacktoberfest, current

#14717 Add IoT class for HTML5 Push Notifications integration
  source/_integrations/html5.markdown
Labels: Hacktoberfest, current

#14719 Add IoT class for Shopping List integration
  source/_integrations/shopping_list.markdown
Labels: Hacktoberfest, current

#14773 Fix Voice RSS documentation link
  source/_integrations/voicerss.markdown
Labels: Hacktoberfest, current

#14772 Move redirects
  source/_cookbook/notify.mqtt.markdown
  source/_docs/frontend/browsers.markdown
  source/_docs/tools/scripts.markdown
  source/_posts/2019-06-05-release-94.markdown
  source/_posts/2019-11-22-state-of-the-union.markdown
  source/_redirects
  source/lovelace/index.markdown
Labels: Hacktoberfest, current

#14776 Tweak wording about rate limits
  source/_integrations/binary_sensor.template.markdown
Labels: Hacktoberfest, in-progress, needs-rebase, next

#14781 Change Material Design Icons URL
  source/_posts/2020-07-01-release-113.markdown
Labels: Hacktoberfest, current

#14779 Remove link to OSS Metrics
  source/_posts/2017-01-18-numbers.markdown
Labels: Hacktoberfest, current

#14720 Add IoT class for Automation integration
  source/_integrations/automation.markdown
Labels: Hacktoberfest, current, in-progress

#14778 Add IOT class for Google Assistant
  source/_integrations/google_assistant.markdown
Labels: Hacktoberfest, current

#14721 Adding IoT Class for Yale Smart Living Integration
  source/_integrations/yale_smart_alarm.markdown
Labels: Hacktoberfest, current

#14718 Adding IoT Class for Azure event hub Integration
  source/_integrations/azure_event_hub.markdown
Labels: Hacktoberfest, current

#14723 Add IoT class for Calendar integration
  source/_integrations/calendar.markdown
Labels: Hacktoberfest, current

#14783 Remove Lovelace branding on page
  source/docs/index.markdown
Labels: Hacktoberfest, current

#14724 Adding IoT Class for Vera Integration
  source/_integrations/vera.markdown
Labels: Hacktoberfest, current

#14725 Add IoT class for yandex transport integration
  source/_integrations/yandex_transport.markdown
Labels: Hacktoberfest, current

#14726 Adding IoT Class for Ubee Router Integration
  source/_integrations/ubee.markdown
Labels: Hacktoberfest, current

#14727 Adding IoT Class for VeSync Integration
  source/_integrations/vesync.markdown
Labels: Hacktoberfest, current

#14728 Adding IoT Class for World Tides Integration
  source/_integrations/worldtidesinfo.markdown
Labels: Hacktoberfest, current

#14729 Add IoT Class to Discord Documentation
  source/_integrations/discord.markdown
Labels: Hacktoberfest, current

#14700 Plural typo and reorder
  source/_integrations/rfxtrx.markdown
Labels: Hacktoberfest, current

#14730 Add IoT class to Shell Integration
  source/_integrations/shell_command.markdown
Labels: Hacktoberfest, current

#14731 Add IoT class to Gitter sensor
  source/_integrations/gitter.markdown
Labels: Hacktoberfest, current

#14782 Removing older Nest hyperlink
  source/_posts/2019-01-24-nest-cannot-access-data.markdown
Labels: Hacktoberfest, current

#14737 Add IoT class to sun integration
  source/_integrations/sun.markdown
Labels: Hacktoberfest, current

#14739 Add IoT class to zone integration
  source/_integrations/zone.markdown
Labels: Hacktoberfest, current

#14706 Adding IoT Class for Radarr Integration
  source/_integrations/radarr.markdown
Labels: Hacktoberfest, current

#14785 Add note about remote access to Rachio docs
  source/_integrations/rachio.markdown
Labels: Hacktoberfest, current

#14786 Updated Zamel link to Supla products
  source/_integrations/supla.markdown
Labels: Hacktoberfest, current

#14683 Fix broken links on website (part 2)
  source/_integrations/minecraft_server.markdown
  source/_posts/2016-02-28-steam-d-link-smart-plugs-and-neurio-energy-sensors.markdown
  source/_posts/2017-06-04-release-46.markdown
  source/_posts/2017-06-17-release-47.markdown
  source/_posts/2017-07-02-release-48.markdown
  source/_posts/2017-07-16-release-49.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2018-01-27-release-62.markdown
  source/_posts/2018-02-26-release-64.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14767 ✏️ Move z-wave redirects to file
  source/_docs/z-wave.markdown
  source/_docs/z-wave/control-panel.markdown
  source/_docs/z-wave/device-specific.markdown
  source/_docs/z-wave/devices.markdown
  source/_docs/z-wave/installation.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14770 Add IOT class to no-ip integration
  source/_integrations/no_ip.markdown
Labels: Hacktoberfest, current

#14685 Update ios integration to clarify what it does and when it is needed
  source/_integrations/ios.markdown
Labels: Hacktoberfest, current

#14789 Removed dead link to end of service page
  source/_integrations/wunderground.markdown
Labels: Hacktoberfest, current

#14788 Changed the Lannouncer link to point to Playstore
  source/_integrations/lannouncer.markdown
Labels: Hacktoberfest, current

#14774 Fix broken links on website (part 3)
  source/_integrations/http.markdown
  source/_posts/2016-07-30-custom-frontend-panels--jupyter-notebooks--directv.markdown
  source/_posts/2018-06-22-release-72.markdown
  source/_posts/2018-09-30-hacktoberfest.markdown
  source/_posts/2019-03-13-release-89.markdown
  source/_posts/2020-08-05-mobile-apps-new-features.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14698 Update Nginx URLs on HTML5 integration page
  source/_integrations/html5.markdown
Labels: Hacktoberfest, current, in-progress

#14787 Add IoT class to Dialogflow integration #14661
  source/_integrations/dialogflow.markdown
Labels: Hacktoberfest, current

#14775 Add IOT class for SQL
  source/_integrations/sql.markdown
Labels: Hacktoberfest, current

#14768 Removing reference to the Z-Wave public SDK
  source/_posts/2018-09-17-thinking-big.markdown
Labels: Hacktoberfest, current

#14734 Add IoT class to the Prometheus integration
  source/_integrations/prometheus.markdown
Labels: Hacktoberfest, current, in-progress

#14791 Rasplex link changed to github page.
  source/_integrations/command_line.markdown
Labels: Hacktoberfest, current

#14792 Updated link to plans
  source/_integrations/uk_transport.markdown
Labels: Hacktoberfest, current

#14790 Updated lift dev link
  source/_integrations/lyft.markdown
Labels: Hacktoberfest, current

#14682 Move frontmatter redirects to file
  source/_redirects
  source/cloud/alexa.markdown
  source/code_of_conduct/index.markdown
  source/getting-started/automation.markdown
  source/hassio/index.markdown
  source/lovelace/index.markdown
Labels: Hacktoberfest, current

#14711 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: Hacktoberfest, current

#14777 Add IoT class to Alexa integration
  source/_integrations/alexa.markdown
Labels: Hacktoberfest, current

#14794 Remove redirect-from Jekyll plugin
  Gemfile
  Gemfile.lock
  _config.yml
Labels: Hacktoberfest, cleanup, current

#14799 Fix broken links on website (part 4)
  source/_integrations/neato.markdown
  source/_posts/2015-10-11-rfxtrx-blinkstick-and-snmp-support.markdown
  source/_posts/2016-01-29-insteon-lifx-twitter-and-zigbee.markdown
  source/_posts/2017-02-11-alert-appletv-mqtt-yeelight.markdown
  source/_posts/2017-09-09-release-53.markdown
  source/_posts/2018-03-30-release-66.markdown
  source/_posts/2019-04-15-hassio-ingress.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_redirects
Labels: Hacktoberfest, current

#14802 Fix broken links on website (part 5)
  source/_integrations/knx.markdown
  source/_posts/2016-08-27-notifications-hue-fake-unification.markdown
  source/_posts/2019-01-09-release-85.markdown
  source/_posts/2019-01-23-release-86.markdown
  source/_posts/2019-10-10-release-100.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2019-11-20-release-102.markdown
  source/_posts/2019-12-11-release-103.markdown
  source/_posts/2020-02-05-release-105.markdown
Labels: Hacktoberfest, current

#14803 Remove dead link
  source/_integrations/kef.markdown
Labels: Hacktoberfest, current

#14810 Add IoT class for Alert
  source/_integrations/alert.markdown
Labels: Hacktoberfest, current

#14807 Fix Typo input_dateteime
  source/_integrations/input_datetime.markdown
Labels: Hacktoberfest, current

#14745 Styling changes
  source/_integrations/esphome.markdown
Labels: Hacktoberfest, current, in-progress

#14747 Styling and grammar fixes
  source/_integrations/spotify.markdown
Labels: Hacktoberfest, current

#14741 Grammar, spelling and styling edits
  source/_integrations/plex.markdown
Labels: Hacktoberfest, current

#14812 Updated menu item naming in Lovelace dashboards docs
  source/lovelace/dashboards-and-views.markdown
Labels: Hacktoberfest, current

#14813 Add IoT class to Group
  source/_integrations/group.markdown
Labels: Hacktoberfest, current, in-progress

#14806 Added details for how to obtain the Access Token
  source/_integrations/bond.markdown
Labels: Hacktoberfest, current

#14804 Remove outdated Developer Tools icon reference
  source/_docs/configuration/devices.markdown
Labels: Hacktoberfest, current

#14746 Grammar fixes
  source/_integrations/ecobee.markdown
Labels: Hacktoberfest, current, in-progress

#14796 Add IoT class to Aruba integration
  source/_integrations/aruba.markdown
Labels: Hacktoberfest, current

#14798 Add IoT class to Honeyw. Total Connect integration
  source/_integrations/totalconnect.markdown
Labels: Hacktoberfest, current

#14809 Add IoT class for Input Datetime
  source/_integrations/input_datetime.markdown
Labels: Hacktoberfest, current

#14808 Add IoT class for Input Number
  source/_integrations/input_number.markdown
Labels: Hacktoberfest, current, in-progress

#14703 Adding scan_interval and name to configuration documentation
  source/_integrations/ping.markdown
Labels: Hacktoberfest, current, in-progress

#14815 Add IoT class to Input Select
  source/_integrations/input_select.markdown
Labels: Hacktoberfest, current

#14818 Update yaml.markdown
  source/_docs/configuration/yaml.markdown
Labels: Hacktoberfest, current

#14819 Add IoT class to Input Text
  source/_integrations/input_text.markdown
Labels: Hacktoberfest, current

#14817 Update glossary.yml
  source/_data/glossary.yml
Labels: Hacktoberfest, current, in-progress

#14816 Add IoT class to Pushover integration
  source/_integrations/pushover.markdown
Labels: Hacktoberfest, current, in-progress

#14814 Add IoT class to Cloudflare integration
  source/_integrations/cloudflare.markdown
Labels: Hacktoberfest, current, in-progress

#14797 Add IoT class to RFLink integration
  source/_integrations/rflink.markdown
Labels: Hacktoberfest, current, in-progress

#14828 Add missing IoT classes to integration Counter
  source/_integrations/counter.markdown
Labels: Hacktoberfest, current

#14824 Adding IoT Class for Ping (ICMP) Integration
  source/_integrations/ping.markdown
Labels: Hacktoberfest, current

#14822 Add IoT class to Input Boolean
  source/_integrations/input_boolean.markdown
Labels: Hacktoberfest, current

#14821 Adding IoT Class for Cisco IOS Integration
  source/_integrations/cisco_ios.markdown
Labels: Hacktoberfest, current

#14823 Add IoT class to Edimax integration
  source/_integrations/edimax.markdown
Labels: Hacktoberfest, current

#14827 Add IoT class to Binary Sensor
  source/_integrations/binary_sensor.markdown
Labels: Hacktoberfest, current, in-progress

#14829 Add IoT class to RFLink devices
  source/_integrations/cover.rflink.markdown
  source/_integrations/light.rflink.markdown
  source/_integrations/sensor.rflink.markdown
  source/_integrations/switch.rflink.markdown
Labels: Hacktoberfest, current

#14831 Remove logo from ecovacs documentation
  source/_integrations/ecovacs.markdown
Labels: Hacktoberfest, current, has-parent

#14820 Add IoT class to Syslog Integration
  source/_integrations/syslog.markdown
Labels: Hacktoberfest, current, in-progress

#14825 Adding IoT Class for Cisco Mobility Express Integration
  source/_integrations/cisco_mobility_express.markdown
Labels: Hacktoberfest, current

#14832 add ha_iot_class to dd_wrt
  source/_integrations/ddwrt.markdown
Labels: Hacktoberfest, current

#14833 Fix broken links on website (part 6)
  source/_integrations/image_processing.markdown
  source/_posts/2016-09-10-notify-group-reload-api-pihole.markdown
  source/_posts/2017-05-20-automation-editor-zwave-panel-ocr.markdown
  source/_posts/2017-10-21-release-56.markdown
  source/_posts/2017-11-04-release-57.markdown
  source/_posts/2018-01-14-release-61.markdown
  source/_posts/2020-05-20-release-110.markdown
Labels: Hacktoberfest, current

#14834 ✏️ Add missing ha_category
  source/_integrations/geo_location.markdown
  source/_integrations/homeassistant.markdown
  source/_integrations/spotcrime.markdown
  source/_integrations/tts.markdown
Labels: Hacktoberfest, current

#14835 Add IoT class to Configurator
  source/_integrations/configurator.markdown
Labels: Hacktoberfest, current

#14836 missing parameter description for free mobile
  source/_integrations/free_mobile.markdown
Labels: Hacktoberfest, current

#14837 Developer Tools page updates
  source/_docs/tools/dev-tools.markdown
Labels: Hacktoberfest, current

#14839 Media Extractor page updates
  source/_integrations/media_extractor.markdown
Labels: Hacktoberfest, current

#14845 Update ecobee.markdown
  source/_integrations/ecobee.markdown
Labels: Hacktoberfest, current

#14844 Add IoT class for Keenetic NDMS2 Routers integration
  source/_integrations/keenetic_ndms2.markdown
Labels: Hacktoberfest, current

#14843 Add IoT class for Huawei Router integration
  source/_integrations/huawei_router.markdown
Labels: Hacktoberfest, current

#14846 Lutron Caseta: update supported features
  source/_integrations/lutron_caseta.markdown
Labels: Hacktoberfest, awaits-parent, has-parent, new-feature, next, parent-merged

#14865 Add IOT Class to Arris TG2492LG
  source/_integrations/arris_tg2492lg.markdown
Labels: Hacktoberfest, current

#14864 Add IOT class for BT Home Hub 5
  source/_integrations/bt_home_hub_5.markdown
Labels: Hacktoberfest, current

#14863 Adding IoT Class for Mikrotik
  source/_integrations/mikrotik.markdown
Labels: Hacktoberfest, current

#14861 Remove unused Dev Tools icon from Fan integration
  source/_integrations/fan.markdown
Labels: Hacktoberfest, current

#14847 Removed deprecated entity_id option
  source/_integrations/binary_sensor.template.markdown
Labels: Hacktoberfest, current

#14840 Add IoT class for Weather integration
  source/_integrations/weather.markdown
Labels: Hacktoberfest, current, in-progress

#14848 Remove logo from geizhals documentation
  source/_integrations/geizhals.markdown
Labels: Hacktoberfest, current, has-parent

#14849 add missing param description in various docs
  source/_integrations/mailgun.markdown
  source/_integrations/mastodon.markdown
  source/_integrations/yessssms.markdown
Labels: Hacktoberfest, current

#14850 Fix mistake in Caseta docs
  source/_integrations/lutron_caseta.markdown
Labels: Hacktoberfest, current

#14852 Add IoT class to Microsoft Teams integration
  source/_integrations/msteams.markdown
Labels: Hacktoberfest, current

#14857 Remove unused Dev Tools icon from Climate page
  source/_integrations/climate.markdown
Labels: Hacktoberfest, current

#14866 Add IoT Class to UPC Connect Box
  source/_integrations/upc_connect.markdown
Labels: Hacktoberfest, current
