Repository home-assistant/home-assistant.io, pull requests merged in 2020-08, with the labels that each got.

#14127 Release 113.3
  _config.yml
  source/_posts/2020-07-01-release-113.markdown
Labels: current, has-parent, in-progress, needs-rebase

#14136 [iOS] Add new team ID to apple-app-site-association
  source/.well-known/apple-app-site-association
Labels: current, has-parent, in-progress, needs-rebase

#14143 Better first sentence for HomeKit.markdown
  source/_integrations/homekit.markdown
Labels: current

#14140 Update documentation for HLK-SW16 config flow
  source/_integrations/hlk_sw16.markdown
Labels: has-parent, new-feature, next, parent-merged

#14138 Workday: update docs to call out using province option for states, too
  source/_integrations/workday.markdown
Labels: current

#14111 Update google_assistant.markdown - Account linking updated
  source/_integrations/google_assistant.markdown
Labels: current

#14137 MQTT Grammar
  source/_docs/mqtt/broker.markdown
Labels: current

#14135 Honeywell Grammar
  source/_integrations/honeywell.markdown
Labels: current

#14117 add link to nexttracks android fork of owntracks
  source/_integrations/owntracks.markdown
Labels: current, in-progress

#14133 Fix broken link in rfxtrx.markdown
  source/_integrations/rfxtrx.markdown
Labels: current

#14129 Update dsmr.markdown
  source/_integrations/dsmr.markdown
Labels: current

#14128 change 'image' config variable to required
  source/_lovelace/picture-elements.markdown
Labels: current

#14126 Update vacuum.xiaomi_miio.markdown
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#14112 Fix weather-forecast.markdown
  source/_lovelace/weather-forecast.markdown
Labels: current

#14035 Add support for multiple time triggers in automations
  source/_docs/automation/trigger.markdown
Labels: has-parent, new-feature, next, parent-merged

#13927 Add HassOS FAQ
  source/_includes/asides/hassio_navigation.html
  source/hassio/hassos_faq.markdown
Labels: current

#13667 Add demo link.
  source/_integrations/iammeter.markdown
  source/images/integrations/iammeter/demo.jpg
Labels: current, in-progress

#14134 Allow automation to be turned off without stopping actions
  source/_docs/automation.markdown
  source/_integrations/automation.markdown
Labels: has-parent, next, parent-merged

#14060 Add 'alarm_event_occurred' attribute definition to AlarmDecoder documentation
  source/_integrations/alarmdecoder.markdown
Labels: has-parent, new-feature, next, parent-merged

#13975 Update meteo_france documentation
  source/_integrations/meteo_france.markdown
Labels: has-parent, new-feature, next, parent-merged

#14052 Add documentation for unique_id on template platforms
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/binary_sensor.template.markdown
  source/_integrations/cover.template.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/light.template.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/template.markdown
  source/_integrations/vacuum.template.markdown
Labels: has-parent, new-feature, next, parent-merged

#14145 filename has to have .name in variable
  source/_integrations/camera.markdown
Labels: current

#14031 Update Xiaomi Miio documentation
  source/_integrations/air_quality.xiaomi_miio.markdown
  source/_integrations/alarm_control_panel.xiaomi_miio.markdown
  source/_integrations/fan.xiaomi_miio.markdown
  source/_integrations/light.xiaomi_miio.markdown
  source/_integrations/remote.xiaomi_miio.markdown
  source/_integrations/sensor.xiaomi_miio.markdown
  source/_integrations/switch.xiaomi_miio.markdown
  source/_integrations/vacuum.xiaomi_miio.markdown
  source/_integrations/xiaomi_miio.markdown
  source/_redirects
Labels: current, has-parent, in-progress, parent-merged

#14072 Remove deprecated Slack attachments documentation
  source/_integrations/slack.markdown
Labels: has-parent, next

#14073 Remove YAML docs for IQVIA
  source/_integrations/iqvia.markdown
Labels: has-parent, new-feature, next

#14146 Correct docs for disabling MQTT birth message
  source/_docs/mqtt/birth_will.markdown
Labels: current

#14147 fix yaml for input_number use in delay
  source/_integrations/input_number.markdown
Labels: current

#14154 fix typo in bravia docs
  source/_integrations/braviatv.markdown
Labels: current

#14125 Support string lists in http server_host and note new default (dual stack, IPv4 and IPv6)
  source/_integrations/http.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14151 Update camera.markdown
  source/_integrations/camera.markdown
Labels: current

#14150 Update synology.markdown
  source/_integrations/synology.markdown
Labels: current

#14148 Update ecovacs.markdown
  source/_integrations/ecovacs.markdown
Labels: current

#13720 update spider documentation
  source/_integrations/spider.markdown
Labels: has-parent, new-feature, next, parent-merged

#14006 Add Water Meter Sensor Entities
  source/_integrations/toon.markdown
Labels: has-parent, new-feature, next

#14141 Add missing timeout to command_line platforms: cover, notify, switch
  source/_integrations/cover.command_line.markdown
  source/_integrations/notify.command_line.markdown
  source/_integrations/switch.command_line.markdown
Labels: has-parent, new-feature, next

#14163 [iOS] app-site-association: change /nfc/ to /tag/
  source/.well-known/apple-app-site-association
Labels: current

#14164 Add instructions to enable entities
  source/_integrations/meteo_france.markdown
Labels: has-parent, next

#14156 Add some additional help on google assistant trouble shooting
  source/_integrations/google_assistant.markdown
Labels: current, in-progress

#14162 Nextcloud category update
  source/_integrations/nextcloud.markdown
Labels: current

#13970 Update Netatmo documentation to reflect the changes
  source/_integrations/netatmo.markdown
Labels: has-parent, new-feature, next, parent-merged

#14161 Update google_assistant.markdown - added Failed linking advise
  source/_integrations/google_assistant.markdown
Labels: current

#14144 Improvements to picture-elements.markdown
  source/_lovelace/picture-elements.markdown
Labels: current

#13583 Add OVO Energy Integration Docs
  source/_integrations/ovo_energy.markdown
Labels: awaits-parent, has-parent, new-integration, next

#14165 Documentation for new `frontend.set_theme` options
  source/_integrations/frontend.markdown
Labels: has-parent, next

#14159 Beta release notes for 0.114
  _config.yml
  source/_posts/2020-08-12-release-114.markdown
  source/images/blog/2020-08-0.114/dark-mode.png
  source/images/blog/2020-08-0.114/repeat-ui.png
Labels: blog, in-progress, needs-rebase, rc

#14167 Companion apps update blog post
  source/_posts/2020-08-05-mobile-apps-new-features.markdown
  source/images/blog/2020-08-05-mobile-apps-new-features/Companion-new-upcoming.png
  source/images/blog/2020-08-05-mobile-apps-new-features/biometric_unlock.png
  source/images/blog/2020-08-05-mobile-apps-new-features/geocoded_sensor.png
  source/images/blog/2020-08-05-mobile-apps-new-features/ios-notification-examples.png
Labels: current

#14169 Fix typo
  source/_posts/2020-08-05-mobile-apps-new-features.markdown
Labels: current

#14172 Correct minimal location and add entity state widget to blog post
  source/_posts/2020-08-05-mobile-apps-new-features.markdown
Labels: blog, current

#14166 Update docs for Philips Hue Smart Button support
  source/_integrations/deconz.markdown
  source/_integrations/hue.markdown
Labels: has-parent, in-progress, next, parent-merged

#13708 Update documentation for devolo Home Control integration
  source/_integrations/devolo_home_control.markdown
Labels: has-parent, new-feature, next, parent-merged

#14186 Update Wording for lovelace
  source/lovelace/index.markdown
Labels: has-parent, next

#14183 Clarify expire_after for MQTT sensor
  source/_integrations/sensor.mqtt.markdown
Labels: current

#14176 Correct documentation of MQTT binary_sensor expire_after
  source/_integrations/binary_sensor.mqtt.markdown
Labels: current

#14184 Fix broken amazon link
  source/_integrations/mitemp_bt.markdown
Labels: current

#14182 Update MQTT binary sensor example
  source/_integrations/binary_sensor.mqtt.markdown
Labels: current

#14181 Update enable_i2c.markdown
  source/hassio/enable_i2c.markdown
Labels: current

#14180 Update zwave.markdown
  source/hassio/zwave.markdown
Labels: current

#14179 Correct companion link
  source/_posts/2020-08-05-mobile-apps-new-features.markdown
Labels: current

#14178 Update hassos_faq.markdown
  source/hassio/hassos_faq.markdown
Labels: current

#14170 Update Material Design Icons link to 5.3.45
  source/_docs/configuration/customizing-devices.markdown
Labels: current

#14189 Update dynalite.markdown
  source/_integrations/dynalite.markdown
Labels: has-parent, new-feature, next, parent-merged

#14194 Update bom.markdown
  source/_integrations/bom.markdown
Labels: current

#14193 Logitech Harmony integration
  source/_integrations/emulated_hue.markdown
Labels: current

#14195 Update Bond documentation to specify minimum supported firmware
  source/_integrations/bond.markdown
Labels: current

#14175 Update index.html
  source/addons/index.html
Labels: current

#14171 Update history screenshot
  source/images/screenshots/component_history_24h.png
Labels: current, in-progress

#14199 Update http.markdown to include certificate location
  source/_integrations/http.markdown
Labels: current

#14217 Prepare for Android link handling
  source/.well-known/assetlinks.json
Labels: current, has-parent, in-progress, needs-rebase

#14215 Update formatting
  source/_integrations/person.markdown
Labels: current

#14211 Update zha.markdown with all TI CC1352x and CC2652x
  source/_integrations/zha.markdown
Labels: current

#14206 Add quotes to the payload_template example.
  source/_docs/mqtt/service.markdown
Labels: current

#14177 Update installation.markdown
  source/hassio/installation.markdown
Labels: current, in-progress

#14220 [iOS] Exclude /ios/beta from universal links
  source/.well-known/apple-app-site-association
Labels: current

#14224 Update device-specific.markdown
  source/_docs/z-wave/device-specific.markdown
Labels: current

#14222 Remove prezzibenzina
  source/_integrations/prezzibenzina.markdown
  source/_posts/2019-01-09-release-85.markdown
  source/_posts/2019-01-23-release-86.markdown
  source/_posts/2019-12-11-release-103.markdown
  source/_posts/2020-05-20-release-110.markdown
  source/_redirects
Labels: awaits-parent, cleanup, has-parent, next

#13989 Update smappee markdown with local option
  source/_integrations/smappee.markdown
Labels: has-parent, new-feature, next, parent-merged

#13736 Document new Vizio service
  source/_integrations/vizio.markdown
Labels: has-parent, new-feature, next, parent-merged

#13756 Add device classes for electrical measurement
  source/_integrations/sensor.markdown
Labels: has-parent, new-feature, next, parent-merged

#14185 Add doc for Nightscout integration
  source/_integrations/nightscout.markdown
Labels: has-parent, new-integration, next, parent-merged

#14201 Added service to Dynalite
  source/_integrations/dynalite.markdown
Labels: has-parent, new-feature, next, parent-merged

#14202 Add documentation for the Flo integration
  source/_integrations/flo.markdown
Labels: has-parent, new-integration, next, parent-merged

#14168 Remove Linky integration
  CODEOWNERS
  source/_integrations/linky.markdown
  source/_posts/2018-10-01-release-79.markdown
  source/_posts/2018-10-29-release-81.markdown
  source/_posts/2019-03-13-release-89.markdown
  source/_posts/2019-04-24-release-92.markdown
  source/_posts/2019-06-26-release-95.markdown
  source/_posts/2019-09-18-release-99.markdown
  source/_posts/2019-10-10-release-100.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2020-01-15-release-104.markdown
  source/_posts/2020-02-05-release-105.markdown
  source/_posts/2020-02-26-release-106.markdown
  source/_redirects
Labels: cleanup, has-parent, in-progress, next, parent-merged

#12120 Add docs for eafm
  source/_integrations/eafm.md
  source/images/supported_brands/environment_agency.jpg
Labels: has-parent, new-integration, next, parent-merged

#14114 Update TensorFlow docs
  source/_integrations/tensorflow.markdown
Labels: has-parent, new-feature, next, parent-merged

#14205 Update credits
  source/developers/credits.markdown
Labels: current

#14203 Add list of possible states to description about timers
  source/_integrations/timer.markdown
Labels: current

#14204 Fixed ambigouty about above/below for automation trigger numeric_state
  source/_docs/automation/trigger.markdown
Labels: current

#14228 Zone Trigger: changed entity_id from device_tracker to person
  source/_docs/automation/trigger.markdown
Labels: current

#14187 Update getting started Wi-Fi section
  source/getting-started/index.markdown
Labels: current, in-progress

#14226 Add Tag documentation
  source/_integrations/tag.markdown
Labels: has-parent, in-progress, new-feature, next

#14229 Add diagnostics to release post
  source/_posts/2020-08-12-release-114.markdown
Labels: blog, in-progress, rc

#14232 Removed the list of supported samsungtv devices
  source/_integrations/samsungtv.markdown
Labels: current, has-parent, in-progress, needs-rebase

#14236 Update updating.markdown
  source/_docs/installation/updating.markdown
Labels: current

#14227 dynalite - add service to request the channel level
  source/_integrations/dynalite.markdown
Labels: has-parent, new-feature, next, parent-merged

#14223 Added a more basic example as the template ones are tough to use as s…
  source/_integrations/rest_command.markdown
Labels: current, in-progress

#14243 Add note about alarm control panel
  source/_integrations/agent_dvr.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#14207 Time trigger can also accept an input_datetime Entity ID
  source/_docs/automation/trigger.markdown
Labels: has-parent, in-progress, needs-rebase, next, parent-merged

#14131 Add Roon media_player integration
  source/_integrations/roon.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#13918 Update dynalite.markdown
  source/_integrations/dynalite.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#14244 Update cast documentation
  source/_integrations/cast.markdown
Labels: current

#14242 Add /tag/* rewrite to serve instructions about NFC/QR/etc. tags
  source/_redirects
  source/tag/index.markdown
Labels: current

#14230 Update Ecobee documentation
  source/_integrations/ecobee.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#14239 Add Slack URL icon documentation
  source/_integrations/slack.markdown
Labels: has-parent, new-feature, next, parent-merged

#14248 Update conditions.markdown
  source/_docs/scripts/conditions.markdown
Labels: current

#14247 Update scripts.markdown
  source/_docs/scripts.markdown
Labels: current

#14249 Update smtp.markdown
  source/_integrations/smtp.markdown
Labels: current

#14253 Removes \ from URL
  source/_integrations/push.markdown
Labels: current

#14255 ✏️ Fix config format for Supla integration
  source/_integrations/supla.markdown
Labels: current

#14264 Fixed the typo
  source/_integrations/kankun.markdown
Labels: current

#14266 Add auth key to doods documentation
  source/_integrations/doods.markdown
Labels: current

#14267 Blog: Month of what the heck
  source/_posts/2020-08-18-the-month-of-what-the-heck.markdown
  source/images/blog/2020-08-18-the-month-of-what-the-heck/jackie-chan-what-the-heck.jpg
  source/images/blog/2020-08-18-the-month-of-what-the-heck/social.png
Labels: blog, current

#14270 Adding suggestion to put ',' between hex as well
  source/_docs/z-wave/installation.markdown
Labels: current

#14265 Add tested model modem and solution for RPI
  source/_integrations/sms.markdown
Labels: current

#14268 Upgrade yandex_transport.markdown
  source/_integrations/yandex_transport.markdown
Labels: has-parent, in-progress, needs-rebase, next

#14276 Update spaceapi documentation link
  source/_integrations/spaceapi.markdown
Labels: current

#14278 Sentry integration enhancements
  source/_integrations/sentry.markdown
Labels: has-parent, new-feature, next, parent-merged

#14300 Typo
  source/_integrations/snmp.markdown
Labels: current

#14296 Add Risco binary sensor to documentation
  source/_integrations/risco.markdown
Labels: has-parent, new-feature, next, parent-merged

#14302 Fix error in Rachio service description
  source/_integrations/rachio.markdown
Labels: has-parent, next

#14287 Enhance script choose action description
  source/_docs/scripts.markdown
Labels: current

#14301 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#14298 Bitron Video Zigbee Stick works very good with ZHA
  source/_integrations/zha.markdown
Labels: current

#13806 Update setup instructions for Broadlink devices
  source/_integrations/broadlink.markdown
Labels: has-parent, new-feature, next, parent-merged

#14196 Create variable with result of wait_template and accept template for timeout option
  source/_docs/scripts.markdown
Labels: has-parent, new-feature, next, parent-merged

#14271 Add support for attributes in (numeric) state conditions
  source/_docs/scripts/conditions.markdown
Labels: has-parent, new-feature, next, parent-merged

#14305 Document Risco options flow
  source/_integrations/risco.markdown
Labels: has-parent, in-progress, new-feature, next

#14306 Update VLC telnet documentation for issue with volume
  source/_integrations/vlc_telnet.markdown
Labels: current

#13203 Update to match Pull request "Move DwdWeatherWarningsAPI to a library…
  source/_integrations/dwd_weather_warnings.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#14308 Add timestamp option for input_datetime.set_datetime
  source/_integrations/input_datetime.markdown
Labels: has-parent, next, parent-merged

#14316 Fix divider row documenation
  source/_lovelace/entities.markdown
Labels: current

#14314 Link to Supervised in alternative installation methods
  source/_docs/installation.markdown
Labels: current

#14313 Removing quotes
  source/_integrations/cast.markdown
Labels: current

#14320 Add informations for z-push button 4
  source/_docs/z-wave/device-specific.markdown
Labels: current

#14321 Added new supported model
  source/_integrations/panasonic_viera.markdown
Labels: current

#14322 Add information on config check during restart
  source/_integrations/homeassistant.markdown
Labels: current

#14323 typo
  source/_integrations/binary_sensor.template.markdown
Labels: current

#14333 Update linksys_smart.markdown
  source/_integrations/linksys_smart.markdown
Labels: current

#14331 Update envisalink.markdown
  source/_integrations/envisalink.markdown
Labels: current

#14330 Added the new YLDP13YL Yeelight 1S Bulb Colour
  source/_integrations/yeelight.markdown
Labels: current

#14324 Add verify_ssl documentation
  source/_integrations/caldav.markdown
Labels: current, has-parent

#14319 opengarage docs - made the previously template sensor based garage_car_present a template binary_sensor
  source/_integrations/opengarage.markdown
Labels: current, in-progress

#14334 Android blog for release 2.3.0
  source/_posts/2020-08-28-android-230-release.markdown
  source/images/blog/2020-08-28-android-230-release/Companion.png
  source/images/blog/2020-08-28-android-230-release/app_theme.png
  source/images/blog/2020-08-28-android-230-release/manage_sensors.png
  source/images/blog/2020-08-28-android-230-release/nfc.png
  source/images/blog/2020-08-28-android-230-release/sensor_management.png
  source/images/blog/2020-08-28-android-230-release/template_widget.png
Labels: blog, current

#14338 Added matching quotation mark
  source/_integrations/integration.markdown
Labels: current

#14344 Fix typo in travis ci docs
  source/_integrations/travisci.markdown
Labels: current

#14299 Update documentation of KNX integration
  source/_integrations/binary_sensor.knx.markdown
  source/_integrations/climate.knx.markdown
  source/_integrations/cover.knx.markdown
  source/_integrations/knx.markdown
  source/_integrations/light.knx.markdown
  source/_integrations/notify.knx.markdown
  source/_integrations/scene.knx.markdown
  source/_integrations/sensor.knx.markdown
  source/_integrations/switch.knx.markdown
Labels: has-parent, in-progress, next, parent-merged

#14325 Adjust hangouts service description
  source/_integrations/hangouts.markdown
Labels: current, has-parent, in-progress, needs-rebase, parent-merged

#14354 Remove superfluous note box
  source/_integrations/octoprint.markdown
Labels: current

#14340 Add basic lock support for fibaro
  source/_integrations/fibaro.markdown
Labels: has-parent, next, parent-merged

#14315 Delete yr.markdown
  CODEOWNERS
  source/_integrations/yr.markdown
  source/_posts/2016-01-17-extended-support-for-diy-solutions.markdown
  source/_posts/2017-08-12-release-51.markdown
  source/_posts/2018-01-27-release-62.markdown
  source/_posts/2018-02-10-release-63.markdown
  source/_posts/2018-07-16-release-73-2.markdown
  source/_posts/2018-10-01-release-79.markdown
  source/_posts/2019-05-16-release-93.markdown
  source/_posts/2019-06-26-release-95.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2019-11-20-release-102.markdown
  source/_posts/2020-01-15-release-104.markdown
  source/_redirects
Labels: has-parent, next, parent-merged

#14017 Docs for progettihwsw integration
  source/_integrations/progettihwsw.markdown
Labels: has-parent, new-integration, next, parent-merged
