Repository home-assistant/home-assistant.io, pull requests merged in 2020-06, with the labels that each got.

#13633 Remove legacy platform config from doorbird
  source/_integrations/doorbird.markdown
Labels: current

#13634 Clarity edit
  source/_docs/configuration/troubleshooting.markdown
Labels: current

#13632 Add AVR-X2300W to list of supported devices of denonavr platform
  source/_integrations/denonavr.markdown
Labels: current

#13628 Gave an example for Nabu Casa because many of the examples given else…
  source/_integrations/withings.markdown
Labels: current, in-progress

#11855 Add service documentation for invoke_pin
  source/_integrations/openhome.markdown
Labels: has-parent, next, parent-merged

#13629 Update roku.markdown for Roku async update
  source/_integrations/roku.markdown
Labels: current, in-progress

#13178 Update Sonarr for Config Flow
  source/_integrations/sonarr.markdown
Labels: has-parent, new-feature, next, parent-merged

#12738 Update plugwise platform
  source/_integrations/plugwise.markdown
Labels: has-parent, in-progress, next, parent-merged

#13544 Remove WWLLN docs
  CODEOWNERS
  source/_integrations/geo_location.markdown
  source/_integrations/wwlln.markdown
  source/_posts/2019-07-17-release-96.markdown
  source/_posts/2019-08-07-release-97.markdown
  source/_posts/2019-09-18-release-99.markdown
  source/_posts/2019-10-10-release-100.markdown
  source/_posts/2020-02-26-release-106.markdown
  source/_posts/2020-03-18-release-107.markdown
  source/_redirects
  source/images/screenshots/wwlln-feed-map.png
Labels: has-parent, next, parent-merged

#13173 Update gogogate2 documentation
  source/_integrations/gogogate2.markdown
Labels: has-parent, new-feature, next, parent-merged

#13397 Add battery_track_interval to bluetooth_le_tracker
  source/_integrations/bluetooth_le_tracker.markdown
Labels: has-parent, new-feature, next, parent-merged

#13612 Remove alert detail from Environment Canada docs
  source/_integrations/environment_canada.markdown
Labels: current, in-progress

#13640 Amendment for plugwise platform update
  source/_integrations/plugwise.markdown
Labels: next

#13641 Remove gearbest integration (ADR-0004)
  CODEOWNERS
  source/_integrations/gearbest.markdown
  source/_posts/2017-12-17-release-60.markdown
  source/_posts/2018-06-22-release-72.markdown
  source/_posts/2019-12-11-release-103.markdown
  source/_redirects
Labels: cleanup, has-parent, next

#13128 Updated vacuum.xiaomi_miio.markdown to warn of access token method
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#13295 Add unique_id to the example of mqtt switch
  source/_integrations/switch.mqtt.markdown
Labels: current

#13289 Add a bit on device triggers in /automation/trigger
  source/_docs/automation/trigger.markdown
Labels: current

#13644 Add config reloaded events for automation and scene
  source/_docs/configuration/events.markdown
Labels: has-parent, new-feature, next

#13647 Fix Pi-hole brand capitalisation
  source/_integrations/pi_hole.markdown
Labels: current

#13653 Remove wunderlist, platform is decommissioned
  .textlintrc.json
  source/_integrations/wunderlist.markdown
  source/_posts/2018-12-12-release-84.markdown
  source/_posts/2019-10-30-release-101.markdown
Labels: cleanup, has-parent, next

#13650 Amendment comments for plugwise platform update
  source/_integrations/plugwise.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13536 Refactor Synology DSM
  source/_integrations/synology_dsm.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13655 Document DISABLE_JEMALLOC environmental variable,
  source/_docs/installation/docker.markdown
Labels: has-parent, new-feature, next, parent-merged

#12978 Add llamalab_automate message delivery priority
  source/_integrations/llamalab_automate.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13605 Add Insteon climate
  source/_integrations/insteon.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13646 updated docs for AEH
  source/_integrations/azure_event_hub.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13454 huawei_lte: added sensor indicating number of unread SMS
  source/_integrations/huawei_lte.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13643 Cleanup Withings documentation
  source/_integrations/withings.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13652 Add config flow to Dune HD
  source/_integrations/dunehd.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13623 homekit zeroconf default interface configuration comes from zeroconf
  source/_integrations/homekit.markdown
Labels: has-parent, new-feature, next, parent-merged

#13145 Update caldav.markdown
  source/_integrations/caldav.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13577 Add notifications to Keba EV chargers
  source/_integrations/keba.markdown
Labels: has-parent, new-feature, next, parent-merged

#13654 Release notes for 0.111.0
  _config.yml
  source/_posts/2020-06-03-release-111.markdown
  source/images/blog/2020-06-0.111/social.png
Labels: blog, in-progress, needs-rebase, rc

#13661 Typo and summarize plugwise changes
  source/_posts/2020-06-03-release-111.markdown
Labels: in-progress, needs-rebase, rc

#13672 Sonos will try port 1400 first and then increment if it is use
  source/_integrations/sonos.markdown
Labels: has-parent, next, parent-merged

#13668 Fixing broken "Picture Card" code example
  source/_lovelace/picture.markdown
Labels: current

#13571 Add notify_events notification component documentation
  source/_integrations/notify_events.markdown
Labels: has-parent, new-integration, next, parent-merged

#13680 Improve Troubleshooting steps for Cloud issue
  source/_integrations/broadlink.markdown
Labels: current

#13681 Update vacuum docs now that Roomba is a state vacuum
  source/_integrations/vacuum.markdown
Labels: current

#13690 Windows instructions "-net=host" does not work
  source/_docs/installation/docker.markdown
Labels: current

#13693 New tested tv qe55q90ratxzt
  source/_integrations/samsungtv.markdown
Labels: current, in-progress

#13695 Update radio types in zha.markdown to match ZHA core const
  source/_integrations/zha.markdown
Labels: current, has-parent

#13694 Remove obsolete warning for `api_password`
  source/_integrations/websocket_api.markdown
Labels: current

#13686 Fix WLED power and brightness with WLED 0.10+
  source/_integrations/wled.markdown
Labels: has-parent, next, parent-merged

#13496 Service goto added to vacuum.xiaomi_miio.markdown
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: has-parent, new-feature, next, parent-merged

#13008 Avri integration config flow
  source/_integrations/avri.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13669 Update documentation for devolo Home Control integration
  source/_integrations/devolo_home_control.markdown
Labels: has-parent, next, parent-merged

#13676 Update Tile docs
  source/_integrations/tile.markdown
Labels: has-parent, new-feature, next, parent-merged

#13056 Drop yaml config from arcam_fmj
  source/_integrations/arcam_fmj.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13674 panel_custom docs update
  source/_integrations/panel_custom.markdown
Labels: has-parent, next, parent-merged

#13696 Update retrieving gateway token for ios app
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#13685 Update nx584.markdown
  source/_integrations/nx584.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13699 [Bugfix] Update version.json layout
  source/version.json
Labels: bug, current

#13400 Add status_light option
  source/_integrations/sonos.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13703 Update _config.yml
  _config.yml
Labels: current

#13635 Remove timeout option from command learning service in the Broadlink integration
  source/_integrations/broadlink.markdown
Labels: has-parent, next, parent-merged

#13710 Fix version number to 0.110.7
  source/_posts/2020-05-20-release-110.markdown
Labels: current

#13705 Added the word "on"
  source/_integrations/unifi.markdown
Labels: current

#13711 [0.111.0] Fix Plugwise links
  source/_integrations/plugwise.markdown
Labels: in-progress, needs-rebase, rc

#13707 Added Jasco 37792 remote
  source/_docs/z-wave/device-specific.markdown
Labels: current

#13687 Update baidu tts supported voice
  source/_integrations/baidu.markdown
Labels: has-parent, new-feature, next, parent-merged

#13657 Adding instructions for various hypervisors
  source/hassio/installation.markdown
Labels: current

#13716 Compress the content
  source/hassio/installation.markdown
Labels: current

#13700 Add icon_type as configuration variable for LaMetric
  source/_integrations/lametric.markdown
Labels: has-parent, new-feature, next, parent-merged

#13717 Update full example for modbus binary_sensor
  source/_integrations/binary_sensor.modbus.markdown
Labels: current, has-parent

#13721 Update synology camera markdown
  source/_integrations/synology.markdown
Labels: current

#13722 Update plugwise.markdown
  source/_integrations/plugwise.markdown
Labels: current

#13727 Update Yeelight docs
  source/_integrations/yeelight.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13729 Add note that Raspberry Pi 4 - 8GB is not supported
  source/hassio/installation.markdown
Labels: current

#13678 Add documentation for google_assistant input select
  source/_integrations/google_assistant.markdown
Labels: has-parent, next

#13737 Fix ZHA docs link in release 0.111 blog post
  source/_posts/2020-06-10-release-111.markdown
Labels: current

#13730 Added alternative method for finding home_id
  source/_integrations/tado.markdown
Labels: current

#13741 Release 0.111.2
  _config.yml
  source/_posts/2020-06-10-release-111.markdown
Labels: blog, current

#13744 Revert "Fix ZHA docs link in release 0.111 blog post"
  source/_posts/2020-06-10-release-111.markdown
Labels: current

#13743 Small note which might save some time
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#13734 Remove duplicate
  source/hassio/installation.markdown
Labels: current

#13732 Update api.markdown
  source/_integrations/api.markdown
Labels: current

#13731 Add Sonarr to config flow
  source/_posts/2020-06-10-release-111.markdown
Labels: blog, current

#13745 Fix dead zigbee links in 0.111 release blog
  source/_posts/2020-06-10-release-111.markdown
Labels: blog, current

#13750 Remove Hass.io
  source/_integrations/cpuspeed.markdown
Labels: current

#13739 Add Name option to Media Control Card
  source/_lovelace/media-control.markdown
Labels: current

#13054 Add sensor platform to vicare
  source/_integrations/vicare.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13144 Add opentherm_gw.set_hot_water_setpoint service documentation
  source/_integrations/opentherm_gw.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13645 Honeywell cleanup
  source/_integrations/honeywell.markdown
Labels: has-parent, next, parent-merged

#12002 Add documentation for hvv_departures
  source/_integrations/hvv_departures.markdown
Labels: has-parent, new-integration, next, parent-merged

#13760 Add Denon AVR-X3300W to supported devices
  source/_integrations/denonavr.markdown
Labels: current

#13765 History link format + wording.
  source/_integrations/history_stats.markdown
Labels: current

#13767 Add link + integration reference
  source/_integrations/history.markdown
Labels: current

#13766 Fix link display
  source/_integrations/recorder.markdown
Labels: current

#13761 Add support for multiple entity_ids in conditions
  source/_docs/scripts/conditions.markdown
Labels: has-parent, new-feature, next

#13774 Update Environment Canada Sensor Names
  source/_integrations/environment_canada.markdown
Labels: current

#13773 Minor doc updates
  source/_integrations/alexa.smart_home.markdown
Labels: current

#13772 Adjustments to KNX entry page
  source/_integrations/knx.markdown
Labels: current

#13776 Fix warning note on KNX page
  source/_integrations/knx.markdown
Labels: current

#13780 Fix links to pull requests in release 0.111.3
  source/_posts/2020-06-10-release-111.markdown
Labels: current

#13782 Update utility_meter.markdown
  source/_integrations/utility_meter.markdown
Labels: current

#13781 Correct ZEN21 version#
  source/_docs/z-wave/device-specific.markdown
Labels: current

#13790 Update history.markdown doc - fixed link to recorder
  source/_integrations/history.markdown
Labels: current

#13788 EA8300 is supported by integration Linksys
  source/_integrations/linksys_smart.markdown
Labels: current

#13789 Sensors with units are excluded
  source/_integrations/logbook.markdown
Labels: current

#13792 "Https:" to "https:" on Nextcloud Integration
  source/_integrations/nextcloud.markdown
Labels: current

#13764 Update Smappee doc
  source/_integrations/smappee.markdown
Labels: has-parent, new-feature, next, parent-merged

#13796 fixed example formatting for Blink
  source/_integrations/blink.markdown
Labels: current

#13319 Docs DenonAVR Config Flow
  source/_integrations/denonavr.markdown
Labels: has-parent, new-feature, next, parent-merged

#13220 Changes from MetOffice moving to config_flow
  source/_integrations/metoffice.markdown
  source/_integrations/sensor.metoffice.markdown
Labels: has-parent, new-feature, next, parent-merged

#13725 Add AlarmDecoder Arming Key Sequences documentation
  source/_integrations/alarmdecoder.markdown
Labels: has-parent, next, parent-merged

#13784 Update database schema for v8 schema
  source/_docs/backend/database.markdown
Labels: has-parent, next, parent-merged

#13366 Adding docs for new Influx 2.0 capabilities
  source/_integrations/influxdb.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#13787 Update axis.markdown
  source/_integrations/axis.markdown
Labels: has-parent, new-feature, next, parent-merged

#13665 Add Cert Expiry timestamp
  source/_integrations/cert_expiry.markdown
Labels: has-parent, new-feature, next, parent-merged

#13803 Update weather-forecast.markdown
  source/_lovelace/weather-forecast.markdown
Labels: current

#13801 Typo fix
  source/_integrations/proxmoxve.markdown
Labels: current

#13116 Updating withings doc to use webhook feature
  source/_integrations/withings.markdown
Labels: has-parent, new-feature, next, parent-merged

#13794 Use Device ID as id in Konnected Alarm Panel Pro
  source/_integrations/konnected.markdown
Labels: has-parent, new-feature, next, parent-merged

#13093 Update for V1.4 API
  source/_integrations/hydrawise.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13059 Update documenation for Awair
  source/_integrations/awair.markdown
Labels: has-parent, new-feature, next, parent-merged

#13804 Add find_vehicle service
  source/_integrations/bmw_connected_drive.markdown
Labels: has-parent, new-feature, next, parent-merged

#13453 Docs Xiaomi Aqara Config Flow
  source/_integrations/xiaomi_aqara.markdown
Labels: has-parent, new-feature, next, parent-merged

#13809 Update daikin documentation (#36475)
  source/_integrations/daikin.markdown
Labels: has-parent, new-feature, next, parent-merged

#13754 Added info re command line sensors being a breaking change
  source/_posts/2020-06-10-release-111.markdown
Labels: current

#13216 Yeelight: Minimum brightness incorrect
  source/_integrations/yeelight.markdown
Labels: current, in-progress

#13268 Update prereq section for latest google cloud UI
  source/_integrations/calendar.google.markdown
Labels: current

#13800 Add new Remote Python Debugger integration
  source/_integrations/debugpy.markdown
Labels: has-parent, new-integration, next, parent-merged

#13621 Update zha.markdown with configuration for OTA firmware update in ZHA
  source/_integrations/zha.markdown
Labels: current

#13810 Remove period char from ZHA example YAML to make it valid
  source/_integrations/zha.markdown
Labels: current

#13811 Process late review comment on ZHA change
  source/_integrations/zha.markdown
Labels: current

#13752 Secondary_info_attribute default
  source/_lovelace/weather-forecast.markdown
Labels: current

#13785 Fix accounts type in steam docs
  source/_integrations/steam_online.markdown
Labels: current

#13777 Update providers.markdown
  source/_docs/authentication/providers.markdown
Labels: current, in-progress

#13747 Adding notes about how to edit the config
  source/_docs/configuration.markdown
Labels: current, in-progress

#13125 Add warning to SolarEdge local documentation
  source/_integrations/solaredge_local.markdown
Labels: current, in-progress

#13189 Updated Raspberry one wire configuration
  source/_integrations/onewire.markdown
Labels: current, in-progress

#13452 Update documentation for squeezebox integration for config flow
  source/_integrations/squeezebox.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13812 Extend triggers intro section
  source/_docs/automation/trigger.markdown
Labels: current, in-progress

#13753 Update Raspbian -> Raspberry Pi OS in installation docs
  source/_docs/configuration/securing.markdown
  source/_docs/installation/docker.markdown
  source/_docs/installation/raspberry-pi.markdown
  source/_docs/installation/troubleshooting.markdown
  source/_docs/installation/virtualenv.markdown
Labels: current

#13779 Updating docs to remove profiles config option.
  source/_integrations/withings.markdown
Labels: has-parent, new-feature, next, parent-merged

#13256 Update Bravia TV Integration (#33774)
  source/_integrations/braviatv.markdown
Labels: current, in-progress

#13132 add Dyson HP04 to list of supported devices
  source/_integrations/dyson.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13677 Documentation for google_assistant media controls
  source/_integrations/google_assistant.markdown
Labels: has-parent, next, parent-merged

#13757 Update automation.markdown
  source/_docs/automation.markdown
Labels: current, in-progress

#13768 Add support for multiple states/zones in conditions
  source/_docs/scripts/conditions.markdown
Labels: has-parent, new-feature, next, parent-merged

#13815 Remove lockitron integration
  source/_integrations/lockitron.markdown
  source/_redirects
Labels: cleanup, has-parent, next

#13814 Support config flow in SMS: Update docs
  source/_integrations/sms.markdown
Labels: has-parent, in-progress, new-feature, next

#13719 Make generic camera stream_source a template
  source/_integrations/generic_ip_camera.markdown
Labels: has-parent, new-feature, next

#13733 Add attribute templates to template vacuum
  source/_integrations/vacuum.template.markdown
Labels: has-parent, new-feature, next, parent-merged

#13746 Adds docs for recorder MySQL purge (PR #36762)
  source/_integrations/recorder.markdown
Labels: has-parent, new-feature, next, parent-merged

#11151 Humidifier: new domain
  source/_integrations/humidifier.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#13797 Rewrite of Toon integration
  source/_integrations/toon.markdown
Labels: has-parent, new-feature, next, parent-merged

#13751 Update alexa flash briefings for new console layout and password
  source/_integrations/alexa.flash_briefings.markdown
Labels: has-parent, next, parent-merged

#13819 Update of typo and wording
  source/_integrations/home_connect.markdown
Labels: current
