Repository home-assistant/home-assistant.io, pull requests merged in 2020-05, with the labels that each got.

#13221 Update Serial sensor platform : Add full options
  source/_integrations/serial.markdown
Labels: has-parent, new-feature, next

#13244 Release 109.2
  _config.yml
  source/_posts/2020-04-29-release-109.markdown
Labels: current, has-parent, in-progress, needs-rebase

#13217 Make user configuration for unifi-os clearer.
  source/_integrations/unifi.markdown
Labels: current, in-progress

#13227 Update ONVIF for Config Flow
  source/_integrations/onvif.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#13167 Add MELCloud zone flow temperature sensor docs
  source/_integrations/melcloud.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13140 Update homekit for config flow
  source/_integrations/homekit.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13153 Added PTZ GotoPreset support
  source/_integrations/onvif.markdown
Labels: has-parent, new-feature, next, parent-merged

#13211 Manual install troubleshooting step for stream
  source/_integrations/stream.markdown
Labels: has-parent, next, parent-merged

#13195 Update hunterdouglas_powerview for config flow
  source/_integrations/hunterdouglas_powerview.markdown
Labels: has-parent, new-feature, next, parent-merged

#12167 Add Xiaomi gateway alarm documentation
  source/_integrations/alarm_control_panel.xiaomi_miio.markdown
Labels: has-parent, new-feature, next, parent-merged

#12749 Document Numato integration
  source/_integrations/numato.markdown
  source/images/supported_brands/numato.png
Labels: has-parent, new-integration, next, parent-merged

#13248 add Yeelight ceiling10/YLDL01YL/meteorite
  source/_integrations/yeelight.markdown
Labels: awaits-parent, has-parent, new-feature, next

#13247 Explain host network mode is mandatory
  source/_docs/installation/docker.markdown
Labels: current, in-progress

#13245 mDNS requires HA to be on same network as devices
  source/_integrations/discovery.markdown
Labels: current, in-progress

#13246 Mention docker host network is required to use cast
  source/_integrations/cast.markdown
Labels: current, in-progress

#13259 Add scene to default_config
  source/_integrations/default_config.markdown
Labels: has-parent, new-feature, next

#13258 Remove logo ref. for Linksys Smart Wi-Fi int.
  source/_integrations/linksys_smart.markdown
Labels: current, has-parent

#13260 Update sms.markdown
  source/_integrations/sms.markdown
Labels: current

#13263 added abbreviation for temperature_unit
  source/_docs/mqtt/discovery.markdown
Labels: has-parent, next

#13250 Add more SNMP variable types to docs
  source/_integrations/snmp.markdown
Labels: has-parent, new-feature, next, parent-merged

#13266 Remove legacy warning from Google Translate
  source/_integrations/google_translate.markdown
Labels: cleanup, current

#13275 Update dyson.markdown
  source/_integrations/dyson.markdown
Labels: current

#13271 Clarify TotalConnect sensor event instructions
  source/_integrations/totalconnect.markdown
Labels: current

#13267 Instructions on how to add input booleans via UI
  source/_integrations/input_boolean.markdown
Labels: current

#13265 influxdb: add support for path parameter
  source/_integrations/influxdb.markdown
Labels: has-parent, next, parent-merged

#13257 Update pulseaudio_loopback pulsectl lib (#34965)
  source/_integrations/pulseaudio_loopback.markdown
Labels: has-parent, next, parent-merged

#13180 UPnP/IGD has been moved to ssdp
  source/_integrations/discovery.markdown
  source/_integrations/ssdp.markdown
Labels: has-parent, next, parent-merged

#13278 Loose some fat on the VSCode dev container
  .devcontainer/devcontainer.json
Labels: current

#13264 Update nginx.markdown
  source/_docs/ecosystem/nginx.markdown
Labels: current

#13283 Instructions on how to add input numbers via UI
  source/_integrations/input_number.markdown
Labels: current

#13281 Instructions on how to add input selects via UI
  source/_integrations/input_select.markdown
Labels: current

#13282 Instructions on how to add input texts via UI
  source/_integrations/input_text.markdown
Labels: current

#13280 Instructions on how to add input datetime via UI
  source/_integrations/input_datetime.markdown
Labels: current

#13290 Update samsungtv.markdown
  source/_integrations/samsungtv.markdown
Labels: current

#13301 0.109.4
  _config.yml
  source/_posts/2020-04-29-release-109.markdown
Labels: current, has-parent, in-progress, needs-rebase

#13299 Add supported Model
  source/_integrations/panasonic_viera.markdown
Labels: current

#13293 Added firewall setup
  source/_integrations/homekit.markdown
Labels: current

#13286 Removal of some stale Windows references
  source/_docs/authentication.markdown
  source/_docs/configuration.markdown
  source/_docs/installation/python.markdown
  source/_integrations/ffmpeg.markdown
  source/help/reporting_issues.markdown
Labels: cleanup, current

#13298 Update 2020-04-29-release-109.markdown
  source/_posts/2020-04-29-release-109.markdown
Labels: current

#13303 Adds note about Advanced Mode and add-ons
  source/addons/index.html
Labels: current

#13292 Minor edit to Lovelace intro page
  source/lovelace/index.markdown
Labels: current

#13291 Add more trouble shooting hints for mDNS
  source/_integrations/discovery.markdown
Labels: current

#13294 Updated list of Lovelace cards that support actions
  source/lovelace/actions.markdown
Labels: current

#13285 Remove `certificate` configuration variable from roomba
  source/_integrations/roomba.markdown
Labels: has-parent, next, parent-merged

#13255 Add zwave_mqtt base
  source/_integrations/zwave_mqtt.markdown
Labels: has-parent, new-integration, next, parent-merged

#13240 yandextts is only working with old API keys
  source/_integrations/yandextts.markdown
Labels: current

#13100 Update tibber.markdown
  source/_integrations/tibber.markdown
Labels: has-parent, new-feature, next, parent-merged

#13097 Document new wrapper for overlay options to rpi_camera
  source/_integrations/rpi_camera.markdown
Labels: has-parent, new-feature, next, parent-merged

#13197 deprecate fortigate integration
  source/_integrations/fortigate.markdown
Labels: current, has-parent, in-progress, parent-merged

#13179 Update tls_self_signed_certificate.markdown
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
Labels: current

#12657 Document name option for edl21
  source/_integrations/edl21.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13306 Fix remarks from PR 13291
  source/_integrations/discovery.markdown
Labels: current

#13304 Remove parts about port_mapping and optional sensors
  source/_integrations/upnp.markdown
Labels: has-parent, next, parent-merged

#12303 Add homekit camera docs
  source/_integrations/homekit.markdown
Labels: has-parent, new-feature, next, parent-merged

#13326 Add device class of garage to example YAML
  source/_integrations/cover.template.markdown
Labels: current

#13325 Adding TC-P55ST50 to the list of supported models
  source/_integrations/panasonic_viera.markdown
Labels: current

#13321 `autoconf` is needed to install the tradfri module
  source/_docs/installation/raspberry-pi.markdown
Labels: current

#13305 Remove `certificate` configuration variable from roomba (#13285 followup)
  source/_integrations/roomba.markdown
Labels: current, has-parent

#13323 Add config for Zooz Zen16
  source/_docs/z-wave/device-specific.markdown
Labels: current

#13317 Update documentation
  source/_integrations/rejseplanen.markdown
Labels: current

#13316 Change lutron_caseta to local push
  source/_integrations/lutron_caseta.markdown
Labels: current

#13314 Edit for clarity and grammar
  source/_integrations/synology_dsm.markdown
Labels: current

#13309 Update docs for pi4ioe5v9xxxx with correct URL to vendor
  source/_integrations/pi4ioe5v9xxxx.markdown
Labels: current

#13308 Fix link to qcow2 image
  source/hassio/installation.markdown
Labels: current

#13328 Small HomeKit doc tweaks
  source/_integrations/homekit.markdown
Labels: current

#13329 Fix YandexTTS layout, remove custom component
  source/_integrations/yandextts.markdown
Labels: current

#13330 Extend list of known supported models, TV Settings
  source/_integrations/panasonic_viera.markdown
Labels: current

#13073 Mycroft: update configuration.yaml
  source/_integrations/mycroft.markdown
Labels: current, in-progress

#13332 Homekit camera codecs support docs
  source/_integrations/homekit.markdown
Labels: has-parent, new-feature, next, parent-merged

#13334 Remove melnor logo in favor of brand
  source/_integrations/raincloud.markdown
Labels: current, has-parent

#13333 Update frontier_silicon.markdown
  source/_integrations/frontier_silicon.markdown
Labels: current

#13276 Add note to deCONZ docs about daylight sensor being disabled by default
  source/_integrations/deconz.markdown
Labels: current

#13337 add home as WorkingDirectory
  source/_docs/autostart/systemd.markdown
Labels: current

#13307 Remove base_url, add external_url & internal_url
  source/_docs/configuration/basic.markdown
  source/_docs/ecosystem/caddy.markdown
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
  source/_docs/ecosystem/certificates/tls_domain_certificate.markdown
  source/_docs/ecosystem/haproxy.markdown
  source/_docs/ecosystem/nginx.markdown
  source/_integrations/ambiclimate.markdown
  source/_integrations/cast.markdown
  source/_integrations/dialogflow.markdown
  source/_integrations/google_translate.markdown
  source/_integrations/http.markdown
  source/_integrations/ifttt.markdown
  source/_integrations/image_processing.markdown
  source/_integrations/konnected.markdown
  source/_integrations/mailgun.markdown
  source/_integrations/netatmo.markdown
  source/_integrations/point.markdown
  source/_integrations/smartthings.markdown
  source/_integrations/spotify.markdown
  source/_integrations/telegram_webhooks.markdown
  source/_integrations/tts.markdown
  source/_integrations/twilio.markdown
Labels: has-parent, new-feature, next

#13338 Working directory bis
  source/_docs/autostart/systemd.markdown
Labels: current

#12067 Add new service calls for Squeezebox
  source/_integrations/squeezebox.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13315 Add default_interface config to zeroconf
  source/_integrations/zeroconf.markdown
Labels: has-parent, new-feature, next, parent-merged

#13148 add docs for upcoming BleBox integration
  source/_integrations/blebox.markdown
Labels: has-parent, new-integration, next, parent-merged

#13183 Add Config Flow and SSDP to songpal
  source/_integrations/songpal.markdown
  source/_integrations/ssdp.markdown
Labels: has-parent, new-feature, next, parent-merged

#13051 Update JuiceNet docs for Config Flow
  source/_integrations/juicenet.markdown
Labels: has-parent, next, parent-merged

#13342 Cleanup of unused image in repository
  source/images/code_bg.png
  source/images/dotted-border.png
  source/images/email.png
  source/images/line-tile.png
  source/images/matrix.png
  source/images/noise.png
  source/images/rss.png
  source/images/supported_brands/linksys.png
  source/images/supported_brands/raincloud.jpg
Labels: cleanup, current

#12437 Add documentation for devolo Home Control integration
  source/_integrations/devolo_home_control.markdown
Labels: has-parent, new-integration, next, parent-merged

#13341 Cleanup AppDaemon documentation from Home Assistant documentation
  source/_docs/ecosystem/appdaemon.markdown
  source/_docs/ecosystem/appdaemon/api.markdown
  source/_docs/ecosystem/appdaemon/configuration.markdown
  source/_docs/ecosystem/appdaemon/example_apps.markdown
  source/_docs/ecosystem/appdaemon/installation.markdown
  source/_docs/ecosystem/appdaemon/operation.markdown
  source/_docs/ecosystem/appdaemon/reboot.markdown
  source/_docs/ecosystem/appdaemon/running.markdown
  source/_docs/ecosystem/appdaemon/tutorial.markdown
  source/_docs/ecosystem/appdaemon/updating.markdown
  source/_docs/ecosystem/appdaemon/windows.markdown
  source/_docs/ecosystem/hadashboard.markdown
  source/_includes/asides/docs_navigation.html
  source/_integrations/deconz.markdown
  source/_integrations/python_script.markdown
  source/_integrations/smtp.markdown
  source/_integrations/telegram_bot.markdown
  source/images/hadashboard/dash1.png
  source/images/hadashboard/dash2.png
  source/images/hadashboard/dash3.png
  source/images/hadashboard/dash4.png
  source/images/hadashboard/dash5.png
Labels: cleanup, current

#13117 Add description of manual config flow for Plex
  source/_integrations/plex.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13343 Updated Tasmota to current link and name
  source/_docs/mqtt/discovery.markdown
Labels: current

#13254 Added entity-filter operator options
  source/_lovelace/entity-filter.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13279 Update documentation for new ZHA config entry flow
  source/_integrations/zha.markdown
Labels: has-parent, new-feature, next, parent-merged

#13199 Updated Daikin documentation for pydaikin v2.0.0
  source/_integrations/daikin.markdown
Labels: has-parent, new-feature, next, parent-merged

#11336 Documentation for the Home Connect integration
  source/_integrations/homeconnect.markdown
  source/images/supported_brands/homeconnect.png
Labels: has-parent, next, parent-merged

#13210 Update Modbus write_register unit description
  source/_integrations/modbus.markdown
Labels: current

#13345 Remove GitPod support
  .gitpod.yml
  .theia/tasks.json
Labels: cleanup, current

#13346 Remove unused heroku deployment config file
  .slugignore
Labels: cleanup, current

#13340 Consecutive volume steps delay in webostv
  source/_integrations/webostv.markdown
Labels: current

#12098 Include Android
  source/docs/index.markdown
Labels: current

#13348 Removed reference to Supervised on Linux
  source/_docs/installation.markdown
Labels: current

#13350 Home connect
  source/_integrations/home_connect.markdown
Labels: next

#13352 Updated Daikin documentation for power sensors
  source/_integrations/daikin.markdown
Labels: has-parent, new-feature, next, parent-merged

#13166 UPB new integration docs
  source/_integrations/upb.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#13359 Added Roomba 960 as supported
  source/_integrations/roomba.markdown
Labels: current

#13351 Cleanup old references of Supervised
  source/_docs/installation.markdown
  source/_docs/installation/docker.markdown
Labels: current

#13336 ISY994 Update Documentation for Clarity and PyISYv2 Compatibility
  source/_integrations/isy994.markdown
Labels: has-parent, new-feature, next, parent-merged

#13242 Add complete Vizio configuration.yaml entry example
  source/_integrations/vizio.markdown
Labels: current

#13192 Update zha.markdown to clearify zigpy-cc & zigpy-zigate as experimental
  source/_integrations/zha.markdown
Labels: current

#13241 fixed broken(?) manual and made it overall easier
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#13012 Update Icon to Tab-Icon to avoid anchor duplication
  source/lovelace/dashboards-and-views.markdown
Labels: current, in-progress

#13364 Universal Powerline Bus - add scene support.
  source/_integrations/upb.markdown
Labels: has-parent, new-feature, next, parent-merged

#13365 Add directions to enable ZHA debug logging
  source/_integrations/zha.markdown
Labels: current

#12510 Describe new feature to turn on the device with a timer
  source/_integrations/switcher_kis.markdown
Labels: has-parent, new-feature, next, parent-merged

#13372 Add supervised blog
  source/_posts/2020-05-09-deprecating-home-assistant-supervised-on-generic-linux.markdown
  source/images/blog/2020-05-09-deprecating-supervised/installation-options.png
Labels: blog, current

#13375 Remove iOS from docs navigation tree
  source/_includes/asides/docs_navigation.html
Labels: cleanup, current

#13377 Remove ensure_config page
  source/_docs/tools/ensure_config.markdown
  source/_includes/asides/docs_navigation.html
Labels: cleanup, current

#12507 Add battery status to bluetooth_le tracker
  source/_integrations/bluetooth_le_tracker.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13385 Fix ASUSWRT link
  source/_integrations/asuswrt.markdown
Labels: current

#13387 Remove abundant word used twice
  source/_docs/installation/docker.markdown
Labels: current

#13378 Add Climate Support to ISY994
  source/_integrations/isy994.markdown
Labels: has-parent, new-feature, next, parent-merged

#13185 Add rain delay to Rachio
  source/_integrations/rachio.markdown
Labels: has-parent, new-feature, next, parent-merged

#11716 Add documentation for Flick Electric sensor
  source/_integrations/flick_electric.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#13369 Add config flow and restore_light_state to ISY994
  source/_integrations/isy994.markdown
Labels: has-parent, new-feature, next, parent-merged

#13273 Mill config flow
  source/_integrations/mill.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13383 Add support for ISY994 Variables as Sensors
  source/_integrations/isy994.markdown
Labels: has-parent, new-feature, next, parent-merged

#13347 Add description of Plex option to ignore web clients
  source/_integrations/plex.markdown
Labels: has-parent, new-feature, next, parent-merged

#12241 add bsblan documentation
  source/_integrations/bsblan.markdown
  source/images/supported_brands/bsblan.png
Labels: has-parent, new-integration, next, parent-merged

#12905 lutron_caseta: using multiple bridges
  source/_integrations/lutron_caseta.markdown
Labels: has-parent, new-feature, next, parent-merged

#13389 Add config flow and device registry to Tuya integration
  source/_integrations/tuya.markdown
Labels: has-parent, new-feature, next, parent-merged

#12333 add agent_dvr
  source/_integrations/agent_dvr.markdown
  source/images/screenshots/agent_dvr.jpg
Labels: has-parent, in-progress, new-integration, next, parent-merged

#13391 Update models
  source/_integrations/denonavr.markdown
Labels: current

#13393 Update sensor.websocket_api.markdown
  source/_integrations/sensor.websocket_api.markdown
Labels: current

#13394 Update proxmoxve.markdown
  source/_integrations/proxmoxve.markdown
Labels: current

#13396 SimpliSafe integration: Added clarifying statement about the `code` config option
  source/_integrations/simplisafe.markdown
Labels: current

#13405 New model tested & typos fixed
  source/_integrations/denonavr.markdown
Labels: current

#13403 Add link to Hosting documentation from Picture Element docs
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  source/_lovelace/picture-elements.markdown
Labels: current

#13404 Universal Powerline Bus -- Link Event
  source/_integrations/upb.markdown
Labels: has-parent, new-feature, next, parent-merged

#13379 ONVIF Event documentation
  source/_integrations/onvif.markdown
Labels: has-parent, new-feature, next, parent-merged

#13269 Update Google Cast integration
  source/_integrations/cast.markdown
Labels: has-parent, new-feature, next, parent-merged

#13262 Update Monoprice docs to reflect recent changes
  source/_integrations/monoprice.markdown
Labels: has-parent, new-feature, next, parent-merged

#13313 Add max_mireds and min_mireds
  source/_integrations/light.mqtt.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13327 Songpal code improvement
  source/_integrations/songpal.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#13395 Weather Card: Recent Updates
  source/_lovelace/weather-forecast.markdown
  source/images/lovelace/lovelace_weather.png
Labels: has-parent, new-feature, next, parent-merged

#13390 Add Services to ISY994
  source/_integrations/isy994.markdown
Labels: has-parent, new-feature, next, parent-merged

#13408 Correct ha_version & ha_domain for 0.110
  source/_integrations/blebox.markdown
  source/_integrations/bsblan.markdown
  source/_integrations/devolo_home_control.markdown
  source/_integrations/home_connect.markdown
  source/_integrations/upb.markdown
Labels: next

#13410 adding duckdns option
  source/_docs/configuration/securing.markdown
Labels: current

#13356 add BleBox sensor platform docs
  source/_integrations/blebox.markdown
Labels: has-parent, new-feature, next

#13413 Update homekit camera docs
  source/_integrations/homekit.markdown
Labels: new-feature, next

#13414 Add brightness as secondary_info option
  source/_lovelace/entities.markdown
Labels: has-parent, new-feature, next, parent-merged

#13407 Automatic zone detection in Monoprice
  source/_integrations/monoprice.markdown
Labels: has-parent, new-feature, next, parent-merged

#13417 Change warning link to Internet Archive link
  source/_integrations/snips.markdown
Labels: current

#13388 Add docs for the Zerproc integration
  source/_integrations/zerproc.markdown
Labels: has-parent, new-integration, next, parent-merged

#13419 Update hass command output
  source/_docs/tools/hass.markdown
Labels: current, has-parent

#13418 Remove legacy information from homekit bridge docs
  source/_integrations/homekit.markdown
Labels: next

#11748 Add documentation for wiffi integration
  source/_integrations/wiffi.markdown
  source/images/supported_brands/wiffi.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged
