Repository home-assistant/home-assistant.io, pull requests merged in 2020-09, with the labels that each got.

#14365 Corrected template example
  source/_docs/configuration/templating.markdown
Labels: current

#14362 Salex sun patch 1
  source/_docs/frontend/browsers.markdown
Labels: current

#14366 Add DGNWQ05LM model number
  source/_integrations/xiaomi_miio.markdown
Labels: current

#14360 Update flo docs
  source/_integrations/flo.markdown
Labels: has-parent, new-feature, next

#14367 Update nuki.markdown
  source/_integrations/nuki.markdown
Labels: current

#14371 Update discovery.markdown
  source/_docs/mqtt/discovery.markdown
Labels: current

#14353 Add max_exceeded log level option to automations & scripts
  source/_integrations/automation.markdown
  source/_integrations/script.markdown
Labels: has-parent, new-feature, next, parent-merged

#14373 Removing random spaces
  source/_integrations/opensky.markdown
Labels: current

#14379 WLED Correct disabled defaults
  source/_integrations/wled.markdown
Labels: current

#14370 Add iot class per #13933
  source/_integrations/simplisafe.markdown
Labels: current

#14381 Fix I2C documentation
  source/hassio/enable_i2c.markdown
Labels: current

#14374 Update zha.markdown remove specific firmware version for Sonoff ZBBridge
  source/_integrations/zha.markdown
Labels: current

#14369 clean_end to clean_stop per issue #14259
  source/_integrations/xiaomi_miio.markdown
Labels: current

#14377 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#14375 Add explanation of multiple entities for the same trigger
  source/_docs/automation/trigger.markdown
Labels: current

#14386 Remove dead link
  source/hassio/enable_i2c.markdown
Labels: current

#14388 xiaomi_aqara remove discovery_retry which is no longer configurable
  source/_integrations/xiaomi_aqara.markdown
Labels: current

#14343 Update template entity docs for entity_id removal and guidance on working without entities
  source/_docs/scripts.markdown
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/bayesian.markdown
  source/_integrations/binary_sensor.template.markdown
  source/_integrations/cover.template.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/light.template.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/template.markdown
  source/_integrations/universal.markdown
  source/_integrations/vacuum.template.markdown
Labels: has-parent, new-feature, next, parent-merged

#14014 Update attributes for Rejseplanen integration
  source/_integrations/rejseplanen.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#14380 Describe new plex.scan_for_clients service
  source/_integrations/plex.markdown
Labels: has-parent, new-feature, next, parent-merged

#14275 Add config flow to nzbget
  source/_integrations/nzbget.markdown
Labels: has-parent, new-feature, next, parent-merged

#14351 Document the recorder db_integrity_check option
  source/_integrations/recorder.markdown
Labels: has-parent, new-feature, next, parent-merged

#14349 Add Plex refresh_library service
  source/_integrations/plex.markdown
Labels: has-parent, new-feature, next, parent-merged

#14387 Add support for as_local as a global and a filter to jinja templates
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14389 Update template Working without entities examples to include as_local()
  source/_integrations/binary_sensor.template.markdown
Labels: has-parent, new-feature, next, parent-merged

#14390 Fix missing end of block in template binary sensor
  source/_integrations/binary_sensor.template.markdown
Labels: has-parent, next

#14378 Describe new Plex play_media syntax for movies
  source/_integrations/plex.markdown
Labels: has-parent, new-feature, next, parent-merged

#14174 Add devolo thermostat devices
  source/_integrations/devolo_home_control.markdown
Labels: has-parent, new-feature, next, parent-merged

#14393 CloudMqtt is no longer offering free plans
  source/_docs/mqtt/broker.markdown
Labels: current

#13590 Add support for VeSync Fans
  source/_integrations/vesync.markdown
Labels: has-parent, new-feature, next, parent-merged

#14395 Update proximity.markdown
  source/_integrations/proximity.markdown
Labels: current

#14394 Update sensor.buienradar.markdown
  source/_integrations/sensor.buienradar.markdown
Labels: current

#14396 Add docs for media_source
  source/_integrations/media_source.markdown
Labels: WTH, has-parent, next, parent-merged

#13625 Update systemmonitor.markdown
  source/_integrations/systemmonitor.markdown
Labels: current, has-parent, in-progress, needs-rebase, new-feature, parent-merged

#13318 OpenWeatherMap config_flow documentation
  source/_integrations/openweathermap.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#14397 Add Risco Event Sensor documentation
  source/_integrations/risco.markdown
Labels: has-parent, next, parent-merged

#14385 Add description for Apache Kafka Authentication configuration
  source/_integrations/apache_kafka.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14372 Change ip address to host for Yeelight
  source/_integrations/yeelight.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#14291 Add Rainbow to list of valid radar sites
  source/_integrations/bom.markdown
Labels: has-parent, new-feature, next, parent-merged

#14284 Update sun elevation example to Home Assistant Documentation standards
  source/_docs/scripts/conditions.markdown
Labels: current, in-progress

#14246 Note limited behaviors
  source/_integrations/konnected.markdown
Labels: current, in-progress

#14245 Update Daikin doc with a note on UDP flows as per issue #37844
  source/_integrations/daikin.markdown
Labels: current

#14213 Automation to update the input select widget
  source/_integrations/vallox.markdown
Labels: in-progress, needs-rebase, next

#14402 Add Epson EH-TW7000 to tested devices.
  source/_integrations/epson.markdown
Labels: current

#14273 Fix initial_state type
  source/_docs/configuration/customizing-devices.markdown
Labels: current

#14257 ozw_scene_activated
  source/_integrations/ozw.markdown
Labels: current

#14400 Clarification reg. disk sensors of systemmonitor
  source/_integrations/systemmonitor.markdown
Labels: next, parent-merged

#14405 Fix typo in volumio docs
  source/_integrations/volumio.markdown
Labels: current

#14391 Add Emulated Kasa
  source/_integrations/emulated_kasa.markdown
  source/_integrations/sense.markdown
Labels: has-parent, new-feature, next, parent-merged

#14348 Updating gogogate2 documentation to include ismartgate.
  source/_integrations/gogogate2.markdown
Labels: has-parent, new-feature, next, parent-merged

#14404 Time condition can also accept an input_datetime Entity ID
  source/_docs/scripts/conditions.markdown
Labels: has-parent, new-feature, next, parent-merged

#14413 Add shorthand notation for Template conditions
  source/_docs/automation/condition.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
Labels: has-parent, new-feature, next, parent-merged

#14357 Add Inclination and vibration Sensor HMIP-STV
  source/_integrations/homematicip_cloud.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#14403 Numeric state condition can also accept input_number entity ID
  source/_docs/scripts/conditions.markdown
Labels: has-parent, new-feature, next, parent-merged

#14411 Add sensor as a supported Risco platform
  source/_integrations/risco.markdown
Labels: has-parent, new-feature, next, parent-merged

#13940 Plugwise - describe how to use OPTIONS
  source/_integrations/plugwise.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14416 Clarifications for the Spotify integration
  source/_integrations/spotify.markdown
Labels: current

#14412 State condition can also accept an input_* Entity ID as state value
  source/_docs/scripts/conditions.markdown
Labels: awaits-parent, has-parent, new-feature, next

#14410 Update ZHA radio types
  source/_integrations/zha.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#14417 Update Logi Circle docs
  source/_integrations/logi_circle.markdown
Labels: current

#14288 Add devolo remote devices as binary sensors
  source/_integrations/devolo_home_control.markdown
Labels: has-parent, new-feature, next, parent-merged

#14363 Add state trigger examples with to/for and from/for
  source/_docs/automation/trigger.markdown
Labels: has-parent, new-feature, next

#14421 Update zha.markdown to clarify Z-Stack 3.x.x vs Z-Stack Home 1.2.x
  source/_integrations/zha.markdown
Labels: has-parent, next, parent-merged

#14423 Support 'for' without setting the 'to'-state in automation state trigger
  source/_docs/automation/trigger.markdown
Labels: has-parent, new-feature, next, parent-merged

#14425 Fix ha_release in KNX weather platform
  source/_integrations/weather.knx.markdown
Labels: next

#14420 add MENU as button option to webos.button service
  source/_integrations/webostv.markdown
Labels: current, has-parent, in-progress, needs-rebase

#14426 Clarify preload stream option
  source/_integrations/camera.markdown
Labels: current

#14415 Beta release notes for 0.115
  _config.yml
  source/_posts/2020-09-17-release-115.markdown
Labels: in-progress, needs-rebase, rc

#14433 Add note about using shorthand condition templates in script sequences
  source/_docs/scripts/conditions.markdown
Labels: next

#14431 Remove docs for HTML support in frontend/custom panel
  source/_integrations/frontend.markdown
  source/_integrations/panel_custom.markdown
Labels: has-parent, next

#14429 Update incorrect onewire documentation
  source/_integrations/onewire.markdown
Labels: current

#14437 fix typo: trough -> through
  source/_integrations/template.markdown
Labels: current

#14435 Jewish calendar docs
  source/_integrations/jewish_calendar.markdown
Labels: current, in-progress

#14440 Minor ZHA improvements
  source/_integrations/zha.markdown
Labels: current

#14444 Clarify state triggers holding using for, ignore attribute changes
  source/_docs/automation/trigger.markdown
Labels: next

#14445 Update 2020-09-17-release-115.markdown
  source/_posts/2020-09-17-release-115.markdown
Labels: in-progress, needs-rebase, rc

#14446 Adding FAQ entry about unique_id
  source/_faq/unique_id.markdown
Labels: current

#14436 Update unifi.markdown
  source/_integrations/unifi.markdown
Labels: current, in-progress

#14447 Config block styling & text selection fixes
  plugins/configuration.rb
  sass/custom/_paulus.scss
Labels: current

#14448 Instructions on adding Zones via GUI
  source/_integrations/zone.markdown
Labels: current

#14443 More info: No URL available
  source/more-info/no-url-available.markdown
Labels: has-parent, next

#14451 Shelly - cover (roller) is supported
  source/_integrations/shelly.markdown
Labels: has-parent, new-feature, next

#14453 Remove IFTTT from featured integrations
  source/_includes/custom/grid_item_left.html
  source/_integrations/ifttt.markdown
Labels: current

#14455 Add Carbon Monoxide binary sensor to Homekit Controller
  source/_integrations/homekit_controller.markdown
Labels: has-parent, new-feature, next, parent-merged

#14432 Add note to UPC Connect about single session
  source/_integrations/upc_connect.markdown
Labels: has-parent, next, parent-merged

#14461 Fix state trigger attribute example
  source/_docs/automation/trigger.markdown
Labels: next

#14458 Document variables for scripts/automations
  plugins/configuration.rb
  source/_docs/automation/action.markdown
  source/_integrations/script.markdown
Labels: has-parent, new-feature, next

#14459 Update ha_category to Energy
  source/_integrations/griddy.markdown
Labels: current, in-progress

#14462 Make shelly featured, updated homepage logos
  source/_includes/custom/grid_item_left.html
  source/_integrations/shelly.markdown
Labels: in-progress, needs-rebase, next

#14464 Cleanup unused images
  source/images/frontend/entity_box.png
  source/images/screenshots/ip-set.jpg
  source/images/screenshots/jupyter-new.png
  source/images/supported_brands/archlinux.png
  source/images/supported_brands/armbian.png
  source/images/supported_brands/centos.png
  source/images/supported_brands/fedora.png
  source/images/supported_brands/freenas.png
  source/images/supported_brands/hlktech.jpg
  source/images/supported_brands/sony.png
Labels: cleanup, current

#14465 Include Innr RB-265
  source/_integrations/deconz.markdown
Labels: current

#14467 Add camera support to synology_dsm
  source/_integrations/synology_dsm.markdown
Labels: has-parent, next, parent-merged

#14472 Fix shelly featured flag
  source/_integrations/shelly.markdown
Labels: next

#14470 Document setting variables in script.
  source/_docs/scripts.markdown
Labels: has-parent, next

#14384 add timedelta_seconds()
  source/_docs/configuration/templating.markdown
Labels: has-parent, new-feature, next, parent-merged

#14471 Fix overlaping click area's prevent text selection
  sass/custom/_paulus.scss
Labels: current

#14478 Update insteon.markdown
  source/_integrations/insteon.markdown
Labels: current

#14474 Android blog for release 2.4.0
  source/_posts/2020-09-12-android-240-release.markdown
  source/images/blog/2020-09-12-android-240-release/Companion.png
  source/images/blog/2020-09-12-android-240-release/doze_state.png
  source/images/blog/2020-09-12-android-240-release/foreground_service.png
Labels: blog, current

#14490 Add missing paren in glossary
  source/_data/glossary.yml
Labels: current

#14486 Update installation.markdown
  source/hassio/installation.markdown
Labels: current

#14489 Bring Huawei LTE features list up to date
  source/_integrations/huawei_lte.markdown
Labels: current

#14475 Add deprecated warning to synology integration
  source/_integrations/synology.markdown
Labels: has-parent, next, parent-merged

#14492 Add documentation for rpi_power
  source/_integrations/rpi_power.markdown
Labels: has-parent, new-integration, next, parent-merged

#14494 Add bday week post
  source/_posts/2020-09-14-birthday-week.markdown
  source/images/blog/2020-09-14-birthday-week/social.png
Labels: blog, current

#14503 Update zha.markdown with recommendation to upgrade EmberZNet firmware
  source/_integrations/zha.markdown
Labels: current

#14498 example of install code
  source/_integrations/rainforest_eagle.markdown
Labels: current, in-progress

#14495 Update alexa.smart_home.markdown
  source/_integrations/alexa.smart_home.markdown
Labels: current

#14504 Update season.markdown
  source/_integrations/season.markdown
Labels: current

#14507 Blog: Home Assistant Tags
  source/_integrations/tag.markdown
  source/_posts/2020-09-15-home-assistant-tags.markdown
  source/images/blog/2020-09-15-home-assistant-tags/cards.jpg
  source/images/blog/2020-09-15-home-assistant-tags/old-system.jpg
  source/images/blog/2020-09-15-home-assistant-tags/orange-reader.jpg
  source/images/blog/2020-09-15-home-assistant-tags/social.png
  source/images/blog/2020-09-15-home-assistant-tags/tag-reader.jpg
  source/images/blog/2020-09-15-home-assistant-tags/tag-ui.gif
  source/images/frontpage/tag-frontpage.jpg
  source/index.html
Labels: blog, current

#14469 Added bimonthly cycle Period for utility_meter component
  source/_integrations/utility_meter.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#14511 Add note about Kodi being on for import to work
  source/_integrations/kodi.markdown
Labels: next

#14513 Add documentation for media_dirs and new more-info messages
  source/_docs/configuration/basic.markdown
  source/more-info/local-media/add-media.markdown
  source/more-info/local-media/setup-media.markdown
Labels: has-parent, next

#14515 Add Supervisor blogpost
  source/_posts/2020-09-16-supervisor-joins-the-party.markdown
  source/images/blog/2020-09-16-supervisor-joins-the-party/audio.png
  source/images/blog/2020-09-16-supervisor-joins-the-party/diagnostics.png
  source/images/blog/2020-09-16-supervisor-joins-the-party/dialog.png
  source/images/blog/2020-09-16-supervisor-joins-the-party/observer.png
  source/images/blog/2020-09-16-supervisor-joins-the-party/social.png
  source/images/blog/2020-09-16-supervisor-joins-the-party/watchdog.png
Labels: blog, current

#14518 Update google_pubsub.markdown
  source/_integrations/google_pubsub.markdown
Labels: current

#14512 Update Kodi breaking changes note
  source/_posts/2020-09-17-release-115.markdown
Labels: blog, rc

#14506 Add notes about Netatmo updates
  source/_posts/2020-09-17-release-115.markdown
Labels: rc

#14509 Update troubleshooting.markdown
  source/_docs/configuration/troubleshooting.markdown
Labels: current

#14452 Add note about hiding mobile app entities
  source/_posts/2020-09-17-release-115.markdown
Labels: has-parent, rc

#14520 Extend media source integration page
  source/_integrations/media_source.markdown
Labels: in-progress, needs-rebase, next

#14521 Add missing integration page for the new Image integration
  source/_integrations/image.markdown
Labels: in-progress, needs-rebase, next

#14173 Update documentation of devolo Home Control integration
  source/_integrations/devolo_home_control.markdown
Labels: has-parent, new-feature, next, parent-merged

#14542 fix indentation error in variables action
  source/_posts/2020-09-17-release-115.markdown
Labels: current

#14545 Quotes around jinja templates
  source/_integrations/snips.markdown
Labels: current

#14544 Quotes around jinja templates
  source/_integrations/script.markdown
Labels: current

#14543 Quotes around jinja template
  source/_docs/automation/action.markdown
Labels: current

#14539 Add space
  source/_integrations/thethingsnetwork.markdown
Labels: current

#14538 Note about image uploader on Persons panel
  source/_integrations/person.markdown
Labels: current

#14535 Fixes HA version introduced emulated_kasa
  source/_integrations/emulated_kasa.markdown
Labels: current

#14530 Update default config page - 3 new integrations
  source/_integrations/default_config.markdown
Labels: current

#14533 Update shelly.markdown
  source/_integrations/shelly.markdown
Labels: current

#14546 Fix eafm integration name in configuration docs
  source/_integrations/eafm.md
Labels: current

#14537 Updated MQTT testing documentation
  source/_docs/mqtt/testing.markdown
Labels: current

#14549 Update shelly.markdown
  source/_integrations/shelly.markdown
Labels: current

#14540 Fixed a typo in 115 release notes 'shorthand notation for template conditions' section
  source/_posts/2020-09-17-release-115.markdown
Labels: current

#14517 Mac companion app blog post
  source/_posts/2020-09-18-mac-companion.markdown
  source/images/blog/2020-09-18-mac-companion/actions-widget.png
  source/images/blog/2020-09-18-mac-companion/multi_window.png
  source/images/blog/2020-09-18-mac-companion/render.png
  source/images/blog/2020-09-18-mac-companion/social.png
Labels: blog, current

#14554 Fix devolo Home Control ha_category
  source/_integrations/devolo_home_control.markdown
Labels: current

#14553 Calendar Card
  source/_lovelace/calendar-card.markdown
  source/images/lovelace/lovelace_calendar_card.png
Labels: current

#14560 Update number of Lovelace cards
  source/lovelace/index.markdown
Labels: current

#14552 Typo in alias description - Vaccum to Vacuum
  source/_integrations/xiaomi_miio.markdown
Labels: current

#14559 🚑 Fix ha_category for Smappee
  source/_integrations/smappee.markdown
Labels: current

#14561 Clarify Working without entities
  source/_integrations/binary_sensor.template.markdown
Labels: current

#14551 Update risco documentation
  source/_integrations/risco.markdown
Labels: current

#14550 power_factory should be power_factor
  source/_integrations/sensor.markdown
Labels: current

#14562 Update credits
  source/developers/credits.markdown
Labels: current

#14482 Update documentation of KNX sync_state and expected DPTs
  source/_integrations/binary_sensor.knx.markdown
  source/_integrations/climate.knx.markdown
  source/_integrations/cover.knx.markdown
  source/_integrations/knx.markdown
  source/_integrations/light.knx.markdown
  source/_integrations/notify.knx.markdown
  source/_integrations/scene.knx.markdown
  source/_integrations/sensor.knx.markdown
  source/_integrations/switch.knx.markdown
  source/_integrations/weather.knx.markdown
Labels: current, has-parent, in-progress, needs-rebase

#14529 Update google_assistant.markdown
  source/_integrations/google_assistant.markdown
Labels: current

#14528 Update calendar.google.markdown
  source/_integrations/calendar.google.markdown
Labels: current

#14505 Create /.well-known/security.txt
  source/.well-known/security.txt
Labels: current

#14527 Clearer instructions for google maps integration
  source/_integrations/google_maps.markdown
Labels: current

#14565 Rename calendar-card
  source/_lovelace/calendar.markdown
  source/_redirects
Labels: current
