Repository home-assistant/home-assistant.io, pull requests merged in 2020-11, with the labels that each got.

#15517 Move ZHA exception handling info to Troubleshooting in zha.markdown
  source/_integrations/zha.markdown
Labels: current, in-progress, needs-rebase

#15515 Update bluetooth_le_tracker.markdown
  source/_integrations/bluetooth_le_tracker.markdown
Labels: current

#15510 Change instances of "view" to "dashboard" where appropriate
  source/lovelace/dashboards-and-views.markdown
Labels: current

#15481 Add IOT class as per #14661
  source/_integrations/image_processing.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15479 Add IOT class as per #14661
  source/_integrations/conversation.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15480 Add IOT class as per #14661
  source/_integrations/image.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15523 Clarify Ruckus unleashed readme: "router" -> "access point"
  source/_integrations/ruckus_unleashed.markdown
Labels: current

#15519 Adding domain
  source/_data/glossary.yml
Labels: current

#15520 Remove opinionated wording
  source/_integrations/hue.markdown
Labels: current

#15518 Description of homeassistant.reload_core_config
  source/_integrations/homeassistant.markdown
Labels: current

#15522 Tweak MQTT discovery documentation
  source/_docs/mqtt/discovery.markdown
Labels: current

#15525 Add OpenMQTTGateway as a third party tool with built-in MQTT discover…
  source/_docs/mqtt/discovery.markdown
Labels: current

#15413 Add update available binary sensor and verify ssl for connection setup to synology_dsm
  source/_integrations/synology_dsm.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next, parent-merged

#15532 Tweak Network Key docs
  source/_docs/z-wave/adding.markdown
Labels: current

#15531 Add blog post for android release 3.0.0
  source/_posts/2020-11-06-android-300-release.markdown
  source/images/blog/2020-11-06-android-300-release/Companion.png
  source/images/blog/2020-11-06-android-300-release/location_sensor_settings.png
  source/images/blog/2020-11-06-android-300-release/media_player_widget.png
  source/images/blog/2020-11-06-android-300-release/onboarding.png
  source/images/blog/2020-11-06-android-300-release/power_menu.png
  source/images/blog/2020-11-06-android-300-release/settings.png
Labels: blog, current, has-parent, in-progress

#15539 Add HG8245W5 to the list of routers the integration has been tested with
  source/_integrations/huawei_router.markdown
Labels: current

#15543 Remove duplicate Z-Wave docs
  source/_includes/asides/hassio_navigation.html
  source/_redirects
  source/hassio/zwave.markdown
Labels: current

#15537 Fix out-of-date Rachio docs
  source/_integrations/rachio.markdown
Labels: current

#15548 Update thethingsnetwork.markdown
  source/_integrations/thethingsnetwork.markdown
Labels: current

#15396 Update statistics.markdown
  source/_integrations/statistics.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, in-progress

#15468 Adding note about cloud
  source/_integrations/xbox.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15494 Update weather.markdown
  source/_integrations/weather.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, in-progress

#15550 Added Denon AVR-X1100W as a supported device
  source/_integrations/denonavr.markdown
Labels: current

#15489 Add DPI Restriction switch to UniFi documentation
  source/_integrations/unifi.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, new-feature, next, parent-merged

#15535 Rewrite Z-Wave Adding and Removing Devices docs
  source/_docs/z-wave/adding.markdown
Labels: current, in-progress

#15533 Clarify Z-Wave control panel docs
  source/_docs/z-wave/control-panel.markdown
Labels: current, in-progress

#15488 RFXtrx debug log is case-sensitive
  source/_integrations/rfxtrx.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15478 Fix: camera feature isn't yet supported by Nest SDM
  source/_integrations/nest.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, has-parent, in-progress, needs-rebase

#15499 Grid Card: Fix Docs
  source/_lovelace/grid.markdown
  source/images/lovelace/lovelace_grid.png
Labels: Hacktoberfest, hacktoberfest-accepted, next

#15487 Update influxdb.markdown
  source/_integrations/influxdb.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15477 Update Docs - Update UniFi Product Name
  source/_integrations/unifi_direct.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15472 Update ohmconnect.markdown
  source/_integrations/ohmconnect.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, has-parent

#15471 Update pushsafer.markdown
  source/_integrations/pushsafer.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, has-parent

#15463 Added KP105 smart plug as supported Kasa device
  source/_integrations/tplink.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15484 Add additional Nest SDM API troubleshooting instructions
  source/_integrations/nest.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, in-progress

#15431 Changed "Conditional Messages" example
  source/_integrations/system_log.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15430 NSW Fuel Station alternative to find station ID
  source/_integrations/nsw_fuel_station.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15420 Add qos default value (0) to service mqtt.publish
  source/_docs/mqtt/service.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15419 Add IoT class to ONVIF integration
  source/_integrations/onvif.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted

#15562 Remove references to old Bing Speech API
  source/_integrations/microsoft.markdown
Labels: current

#15560 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#15559 Updated Inovelli Scene Capable switch instructions
  source/_docs/z-wave/device-specific.markdown
Labels: current

#15556 Update Google Assistant instructions
  source/_integrations/google_assistant.markdown
Labels: current

#15534 Add binary sensors platform to onewire
  source/_integrations/onewire.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#15464 Remove YAML documentation for Flu Near You
  source/_integrations/flunearyou.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next, parent-merged

#15423 Update velbus docu for signum
  source/_integrations/velbus.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next, parent-merged

#14434 Updated documentation for OpenWeatherMap alongside PR 39839
  source/_integrations/openweathermap.markdown
Labels: has-parent, new-feature, next, parent-merged

#15336 Simplify the Hyperion documentation to reflect the new configuration flow
  source/_integrations/hyperion.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, new-feature, next, parent-merged

#15483 Lovelace: Add last-updated option to secondary_info
  source/_lovelace/entities.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next, parent-merged

#15426 Changed Documentation for better comprehensibility
  source/_integrations/fritzbox.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, in-progress, needs-rebase, next, parent-merged

#14853 Feature telegram_sent
  source/_integrations/telegram_bot.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, new-feature, next, parent-merged

#15528 Add note regarding disabled sensors
  source/_integrations/onewire.markdown
Labels: has-parent, new-feature, next, parent-merged

#15395 Deprecate ptvsd integration
  source/_integrations/ptvsd.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next, parent-merged

#15569 Revert "Simplify the Hyperion documentation to reflect the new configuration flow"
  source/_integrations/hyperion.markdown
Labels: next

#15452 Update Docs - webOS Required Port for segmented Networks
  source/_integrations/webostv.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, in-progress

#15453 Update Docs - same subnet only
  source/_integrations/wake_on_lan.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, in-progress

#15195 Add support for Broadlink SP4 series
  source/_integrations/broadlink.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, new-feature, next, parent-merged

#15561 Add switch platform to onewire
  source/_integrations/onewire.markdown
Labels: has-parent, next, parent-merged

#15388 Tuya config options
  source/_integrations/tuya.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, in-progress, new-feature, next, parent-merged

#15512 Update nest documentation for sensor and camera, streamlined for new users of SDM API
  source/_integrations/nest.markdown
Labels: has-parent, in-progress, next, parent-merged

#15333 Add color_extractor service
  source/_integrations/color_extractor.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, in-progress, new-integration, next, parent-merged

#14508 Plugwise Stretch changes for #40108
  source/_integrations/plugwise.markdown
Labels: has-parent, new-feature, next, parent-merged

#15570 Update nest SDM documentation for climate support
  source/_integrations/nest.markdown
Labels: has-parent, new-feature, next, parent-merged

#15132 Jewish Calendar: remove timestamp attribute
  source/_integrations/jewish_calendar.markdown
Labels: Hacktoberfest, awaits-parent, hacktoberfest-accepted, has-parent, next

#15328 Update Neurio documentation
  source/_integrations/neurio_energy.markdown
Labels: Hacktoberfest, awaits-parent, hacktoberfest-accepted, has-parent, new-feature, next

#15573 Replace stale bot with GitHub Action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: current

#15575 Lock bot replacement in GitHub Actions
  .github/workflows/lock.yml
Labels: current

#15577 Disable debug mode on stale GitHub Action
  .github/workflows/stale.yml
Labels: current

#15578 Add yards to proximity integration
  source/_integrations/proximity.markdown
Labels: has-parent, new-feature, next

#15579 Update vasttrafik.markdown
  source/_integrations/vasttrafik.markdown
Labels: current

#15466 Remove YAML documentation for AirVisual
  source/_integrations/airvisual.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next

#15544 Document using sensor for time trigger
  source/_docs/automation/trigger.markdown
Labels: awaits-parent, has-parent, new-feature, next

#15582 Fixed after_offset description
  source/_integrations/tod.markdown
Labels: current

#15583 fix(homekit): typo in issues section
  source/_integrations/homekit.markdown
Labels: current

#14407 Add config entry option to Epson integration
  source/_integrations/epson.markdown
Labels: has-parent, in-progress, needs-rebase, next, parent-merged

#15585 Update panasonic_viera.markdown - added working model: `TX-65FX720W`
  source/_integrations/panasonic_viera.markdown
Labels: current

#15586 Add pyscript as an alternative to python_script
  source/_integrations/python_script.markdown
Labels: current

#15584 Remove iAlarm integration (ADR-0004)
  source/_integrations/ialarm.markdown
  source/_posts/2017-12-17-release-60.markdown
  source/_posts/2018-11-28-release-83.markdown
  source/_posts/2019-01-09-release-85.markdown
  source/_posts/2019-12-11-release-103.markdown
  source/_redirects
  source/images/supported_brands/antifurto365-ialarm.png
Labels: cleanup, has-parent, next

#15587 add much more convenient way to get a sure petcare api token
  source/_integrations/surepetcare.markdown
Labels: current

#15566 Add object logging services for investigating memory leaks
  source/_integrations/profiler.markdown
Labels: has-parent, new-feature, next, parent-merged

#15591 Tasmota 9.1 released
  source/_integrations/tasmota.markdown
Labels: current

#15590 Add docs for additional SimpliSafe sensors
  source/_integrations/simplisafe.markdown
Labels: has-parent, new-feature, next

#15593 Update decora_wifi.markdown
  source/_integrations/decora_wifi.markdown
Labels: current

#15589 Clarity edit for BLE tracker
  source/_integrations/bluetooth_le_tracker.markdown
Labels: current

#15592 Remove YAML documentation for Notion
  source/_integrations/notion.markdown
Labels: has-parent, next, parent-merged

#15580 Rename generic_ip_camera.markdown to generic.markdown
  source/_integrations/generic.markdown
  source/_redirects
Labels: current, has-parent, in-progress, needs-rebase

#15563 Update documentation for Dyson integration.
  source/_integrations/dyson.markdown
Labels: has-parent, new-feature, next, parent-merged

#14481 Clean up yaml config for all fritz integrations
  source/_integrations/fritz.markdown
  source/_integrations/fritzbox_callmonitor.markdown
Labels: has-parent, next

#15284 add variable to remove holidays from workday sensor
  source/_integrations/workday.markdown
Labels: Hacktoberfest, awaits-parent, hacktoberfest-accepted, has-parent, new-feature, next, parent-merged

#15597 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#15476 Update ruckus_unleashed.markdown
  source/_integrations/ruckus_unleashed.markdown
Labels: Hacktoberfest, current, hacktoberfest-accepted, in-progress

#15596 Update zha.markdown with Zigbee 3.0 support note
  source/_integrations/zha.markdown
Labels: current, in-progress

#15600 Update network_manager.markdown
  source/more-info/unsupported/network_manager.markdown
Labels: current

#15601 Add options flow information to dsmr integration
  source/_integrations/dsmr.markdown
Labels: has-parent, new-feature, next

#15599 Update credits
  source/developers/credits.markdown
Labels: current

#15607 Don't zeropad the release date
  source/index.html
Labels: current

#15608 Add missing tag trigger documentation
  source/_docs/automation/trigger.markdown
Labels: current

#15609 Update the conference page
  sass/custom/_paulus.scss
  sass/oscailte/helpers/_classes.scss
  source/_includes/asides/conference_navigation.html
  source/conference/index.markdown
Labels: current

#15610 add note on enabling remote features on Xbox
  source/_integrations/xbox.markdown
Labels: current

#15614 0.117.6
  _config.yml
  source/_posts/2020-10-28-release-117.markdown
Labels: blog, current, has-parent

#15511 Add reboot and shutdown service to synology_dsm
  source/_integrations/synology_dsm.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#15615 Fix synology_dsm typo
  source/_integrations/synology_dsm.markdown
Labels: next, ready-for-review

#15581 Beta release notes for 0.118
  _config.yml
  source/_posts/2020-11-18-release-118.markdown
  source/images/blog/2020-11-0.118/social.png
Labels: blog, in-progress, needs-rebase, rc

#15598 Updated Aurora documentation to reflect fixes and addition of config_flow.
  source/_integrations/aurora.markdown
Labels: has-parent, new-feature, next

#15352 Add rest query params documentation
  source/_integrations/rest.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, next, parent-merged

#15618 Small typo in beta release notes
  source/_posts/2020-11-18-release-118.markdown
Labels: in-progress, needs-rebase, rc

#15611 Add support for multiple event triggers in automation
  source/_docs/automation/trigger.markdown
Labels: awaits-parent, has-parent, new-feature, next

#15622 Update OS 4.16 / add Odroid C4 beta
  source/hassio/installation.markdown
Labels: current

#15630 fixing odroid-c4 image link
  source/hassio/installation.markdown
Labels: current

#15628 Update opensky.markdown
  source/_integrations/opensky.markdown
Labels: current, has-parent, in-progress, needs-rebase

#15632 Removed relative time sensor from description
  source/_integrations/cert_expiry.markdown
Labels: current

#15633 Revert "Removed relative time sensor from description"
  source/_integrations/cert_expiry.markdown
Labels: current, in-progress, needs-rebase

#15631 Add new article from Opensource.com and Thomas Krenn award 2020
  source/help/index.markdown
Labels: current

#15624 Update Recollect Waste configuration instructions
  source/_integrations/recollect_waste.markdown
Labels: has-parent, next, parent-merged

#15619 Fix broken url in Microsoft Text-to-Speech (TTS) docs
  source/_integrations/microsoft.markdown
Labels: current

#15644 Adjust supervisor settings for resolve mdns/llmnr
  source/more-info/unsupported/network_manager.markdown
Labels: current

#15384 Add quarter-hour support to utility meter
  source/_integrations/utility_meter.markdown
Labels: Hacktoberfest, awaits-parent, hacktoberfest-accepted, has-parent, new-feature, next

#15643 Update withings.markdown
  source/_integrations/withings.markdown
Labels: current

#15641 Update "moon" integration screenshot
  source/images/screenshots/more-info-dialog-moon.png
Labels: current

#15509 Support for Broadlink BG1 switches
  source/_integrations/broadlink.markdown
Labels: has-parent, new-feature, next, parent-merged

#15645 fix connection section
  source/more-info/unsupported/network_manager.markdown
Labels: current

#15647 Update alexa.smart_home.markdown
  source/_integrations/alexa.smart_home.markdown
Labels: current

#15387 Add humidifier support for HomeKit Controller
  source/_integrations/homekit_controller.markdown
Labels: Hacktoberfest, awaits-parent, hacktoberfest-accepted, has-parent, new-feature, next

#15636 Tasmota Integration update
  source/_integrations/tasmota.markdown
Labels: has-parent, in-progress, next, parent-merged

#15646 Update logbook.markdown
  source/_integrations/logbook.markdown
Labels: current

#15639 Update scripts.markdown
  source/_docs/scripts.markdown
Labels: current

#15640 updated yessssms documentation
  source/_integrations/yessssms.markdown
Labels: current

#15650 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#15658 Addition of correct link for recent yi-hack
  source/_integrations/xiaomi.markdown
Labels: current

#15659 Add Gas Meter sensor docs to SmartThings integration
  source/_integrations/smartthings.markdown
Labels: has-parent, new-feature, next, parent-merged

#15655 Update insteon.markdown
  source/_integrations/insteon.markdown
Labels: current

#15653 Force color or white mode exclusivity for MQTT lights
  source/_integrations/light.mqtt.markdown
Labels: has-parent, new-feature, next

#15652 Fix & improve documentation for Garadget integration variables
  source/_integrations/garadget.markdown
Labels: current

#15664 Fix jemalloc environment variable
  source/_docs/installation/docker.markdown
Labels: current

#13572 Add table of contents to the integrations pages
  Gemfile
  Gemfile.lock
  _config.yml
  sass/custom/_paulus.scss
  source/_includes/asides/component_navigation.html
Labels: current, in-progress

#15668 Replaced "USB drive" with "hassos-boot"
  source/hassio/enable_i2c.markdown
Labels: current

#15667 Feature-/Permissions-Policy HTTP header update
  source/_headers
Labels: current

#15660 Clarifying "Allow Other Users"
  source/_integrations/google_assistant.markdown
Labels: current, in-progress

#15654 Add docs for template delay in template binary sensor
  source/_integrations/binary_sensor.template.markdown
Labels: has-parent, new-feature, next

#15670 Add tvChannelName to sensor platform
  source/_integrations/smartthings.markdown
Labels: has-parent, new-feature, next, parent-merged

#15672 Supervisor Network / release notes
  source/_posts/2020-11-18-release-118.markdown
  source/images/blog/2020-11-0.118/supervisor-network.gif
Labels: in-progress, needs-rebase, rc

#15301 Update xknx to 0.15.3
  source/_integrations/knx.markdown
Labels: Hacktoberfest, awaits-parent, current, hacktoberfest-accepted, has-parent, in-progress, needs-rebase, new-feature, parent-merged

#15674 Remove hacktoberfest from frontpage
  source/index.html
Labels: current

#15498 Logbook Card
  source/_lovelace/logbook.markdown
  source/images/lovelace/lovelace_logbook.png
Labels: Hacktoberfest, current, hacktoberfest-accepted, has-parent, in-progress, needs-rebase, new-feature, parent-merged

#15683 Add detail to nest subscriber instructions
  source/_integrations/nest.markdown
Labels: current

#15682 proximity also supports persons
  source/_integrations/proximity.markdown
Labels: current

#15681 Fix typo in 0.118.0 blog post
  source/_posts/2020-11-18-release-118.markdown
Labels: current

#15689 Add link to Hopin schedule for conference
  source/conference/index.markdown
Labels: current

#15693 Fix release blog layout and redirect issue
  source/_posts/2020-11-18-release-118.markdown
Labels: current

#15698 Update sleepiq.markdown
  source/_integrations/sleepiq.markdown
Labels: current
