Repository home-assistant/home-assistant.io, pull requests merged in 2020-01, with the labels that each got.

#11588 Remove bash prompt from shell commands to copy
  source/_docs/installation/raspberry-pi.markdown
Labels: current

#11586 Update ha-vs-hassio.markdown
  source/_faq/ha-vs-hassio.markdown
Labels: current

#11583 Fix zwave control panel wiki
  source/_docs/z-wave/control-panel.markdown
Labels: current

#11599 Improved wording for ModemManager troubleshooting
  source/_docs/z-wave/installation.markdown
Labels: current

#11162 Add documentation for GIOS integration
  source/_integrations/gios.markdown
  source/images/supported_brands/gios.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11581 Add light to velbus integration
  source/_integrations/velbus.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11580 Added information to clarify options
  source/_integrations/synologydsm.markdown
Labels: current

#11592 example automation for hunter douglas scenes
  source/_integrations/hunterdouglas_powerview.markdown
Labels: current

#11527 Alert users pymysql is not required for external MariaDB
  source/_integrations/recorder.markdown
Labels: current

#11589 Update ZWave installation instructions
  source/_docs/installation/freenas.markdown
Labels: current

#11584 Update webostv documentation
  source/_integrations/webostv.markdown
Labels: has-parent, next, parent-merged

#11567 Add Tesla charging rate sensor.
  source/_integrations/tesla.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11466 Added local_ip integration
  source/_integrations/local_ip.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11598 Document denonavr generic commands
  source/_integrations/denonavr.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11612 Update stream.markdown
  source/_integrations/stream.markdown
Labels: current

#11609 entity_id is not optional anymore - Media_player services
  source/_integrations/media_player.markdown
Labels: current

#11600 Update google_assistant.markdown
  source/_addons/google_assistant.markdown
Labels: current

#11606 Update limitlessled.markdown
  source/_integrations/limitlessled.markdown
Labels: current

#11605 Update to suggest Companion app
  source/getting-started/presence-detection.markdown
Labels: current, in-progress

#11615 Fix remark linting warnings
  source/_integrations/picotts.markdown
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#11550 Update docs for telegram bot
  source/_integrations/telegram_chatbot.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11617 Clarify Hass.io ecosystem in glossary
  source/_data/glossary.yml
Labels: current

#11618 Spell Zigbee consistently, with lowercase "b"
  source/_integrations/tradfri.markdown
  source/_integrations/zha.markdown
Labels: current

#11607 Add service information to homeassistant integration
  source/_docs/scripts/service-calls.markdown
  source/_integrations/homeassistant.markdown
Labels: current

#11274 add KEF integration docs
  source/_integrations/kef.markdown
  source/images/supported_brands/kef.png
Labels: has-parent, new-integration, next, parent-merged

#11625 Add documentation for Sentry
  source/_integrations/sentry.markdown
  source/images/supported_brands/sentry.png
Labels: has-parent, new-integration, next, parent-merged

#11621 Improved & simplified documentation - Doorbird
  source/_integrations/doorbird.markdown
Labels: current

#11626 Removing reference to `api_password`
  source/_docs/ecosystem/certificates/lets_encrypt.markdown
Labels: current

#11624 Update example to show variable used in set_fan_speed template.
  source/_integrations/vacuum.template.markdown
Labels: current

#11420 separate cmd payloads to state values
  source/_integrations/lock.mqtt.markdown
Labels: has-parent, next, parent-merged

#11631 Point to Telegram chatbot page from Telegram config example
  source/_integrations/telegram.markdown
  source/_integrations/telegram_chatbot.markdown
Labels: current

#11622 Cleanup Rakefile by removing obsolete tasks
  Rakefile
Labels: current

#11634 Add troubleshooting solution for devices that drop off WiFi
  source/_integrations/androidtv.markdown
Labels: current

#11585 Update Freenas docs
  source/_docs/installation/freenas.markdown
Labels: current

#11635 Update tplink.markdown
  source/_integrations/tplink.markdown
Labels: current

#11633 Add person reload service
  source/_integrations/person.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11636 Fix typo
  source/_integrations/switch.rfxtrx.markdown
Labels: current

#11637 Home Assistant etc spelling consistency fixes
  .vscode/cSpell.json
  source/_addons/configurator.markdown
  source/_addons/snips.markdown
  source/_docs/authentication.markdown
  source/_docs/ecosystem/certificates/tls_self_signed_certificate.markdown
  source/_docs/ecosystem/hass-configurator.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/z-wave/controllers.markdown
  source/_docs/z-wave/installation.markdown
  source/_includes/asides/docs_navigation.html
  source/_integrations/apcupsd.markdown
  source/_integrations/dlna_dmr.markdown
  source/_integrations/elkm1.markdown
  source/_integrations/homekit.markdown
  source/_integrations/keba.markdown
  source/_integrations/openuv.markdown
  source/_integrations/owntracks.markdown
  source/_integrations/ptvsd.markdown
  source/_integrations/recorder.markdown
  source/_integrations/remote_rpi_gpio.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/rpi_gpio.markdown
  source/_integrations/sinch.markdown
  source/_integrations/smartthings.markdown
  source/_integrations/tts.markdown
  source/_integrations/unifiled.markdown
  source/_integrations/upnp.markdown
  source/_integrations/utility_meter.markdown
  source/_integrations/vlc_telnet.markdown
  source/_integrations/yeelight.markdown
  source/getting-started/configuration.markdown
  source/getting-started/index.markdown
  source/hassio/installation.markdown
Labels: current

#11639 Update samsungtv.markdown
  source/_integrations/samsungtv.markdown
Labels: current

#11638 Mention fan support
  source/_integrations/homekit_controller.markdown
Labels: has-parent, next, parent-merged

#11642 HS110 clarifications regarding sensors
  source/_integrations/tplink.markdown
Labels: current

#11640 Update of the Google assistant SDK manual
  source/_addons/google_assistant.markdown
Labels: current

#11623 Add automation example to Velbus integration
  source/_integrations/velbus.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11566 Add Alexa locale configuration
  source/_integrations/alexa.smart_home.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11644 Remove OrangePi Prime
  source/hassio/installation.markdown
Labels: current

#11645 Use explicit links inside configuration blocks
  source/_addons/google_assistant.markdown
  source/_integrations/alert.markdown
Labels: current

#11582 Add HmIP-WHS and HmIP-PMFS to HomematicIP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11647 Fix typo
  source/_integrations/dwd_weather_warnings.markdown
Labels: current

#11641 Mention homekit_controller air quality support
  source/_integrations/homekit_controller.markdown
Labels: has-parent, new-feature, next, parent-merged

#11531 Add documentation for pilight dimmer as light
  source/_integrations/pilight.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11470 Added documentation for "autobypass" option added to the AlarmDecoder integration
  source/_integrations/alarmdecoder.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11648 Code blocks
  source/_cookbook/python_component_automation.markdown
  source/_cookbook/python_component_mqtt_basic.markdown
  source/_cookbook/python_component_simple_alarm.markdown
  source/_docs/configuration/group_visibility.markdown
  source/_docs/ecosystem/appdaemon.markdown
  source/_docs/ecosystem/appdaemon/api.markdown
  source/_docs/ecosystem/appdaemon/tutorial.markdown
  source/_docs/z-wave/control-panel.markdown
  source/_integrations/deconz.markdown
  source/_integrations/history.markdown
  source/_integrations/http.markdown
  source/_integrations/python_script.markdown
  source/_integrations/ring.markdown
  source/_integrations/sensor.command_line.markdown
  source/_integrations/telegram.markdown
  source/_integrations/telegram_chatbot.markdown
  source/_integrations/worldclock.markdown
Labels: current

#11501 Document 'androidtv.download' and 'androidtv.upload' services
  source/_integrations/androidtv.markdown
Labels: awaits-parent, has-parent, next

#11595 Add documentation for Brother Printer integration
  source/_integrations/brother.markdown
  source/images/supported_brands/brother.png
Labels: has-parent, new-integration, next, parent-merged

#9590 add surepetcare doc
  source/_integrations/surepetcare.markdown
Labels: has-parent, new-integration, next, parent-merged, ready-for-review

#11650 remove suppress_warning from configuration definition of vizio component
  source/_integrations/vizio.markdown
Labels: has-parent, next, parent-merged

#11571 Add Documentation for PIN Feature
  source/_integrations/venstar.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11646 Adding definition of logfile variable to rc.d script
  source/_docs/installation/freenas.markdown
Labels: current

#11659 Sync title/names with codebase
  source/_integrations/brother.markdown
  source/_integrations/elgato.markdown
  source/_integrations/gios.markdown
  source/_integrations/icloud.markdown
  source/_integrations/intesishome.markdown
  source/_integrations/kef.markdown
  source/_integrations/local_ip.markdown
  source/_integrations/sentry.markdown
  source/_integrations/signal_messenger.markdown
  source/_integrations/surepetcare.markdown
  source/_integrations/velbus.markdown
Labels: next

#11661 Sync config flow with codebase
  source/_integrations/brother.markdown
  source/_integrations/elgato.markdown
  source/_integrations/gios.markdown
  source/_integrations/icloud.markdown
  source/_integrations/local_ip.markdown
  source/_integrations/sentry.markdown
  source/_integrations/tesla.markdown
Labels: next

#11553 Add reset_energy_counter service to Homematic IP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#10905 Add TMB sensor documentation
  source/_integrations/tmb.markdown
  source/images/supported_brands/tmb.png
Labels: Hacktoberfest, has-parent, new-integration, next, parent-merged

#11662 Entity Component to no longer generate automatic groups
  source/_cookbook/automation_for_rainy_days.markdown
  source/_cookbook/automation_sun.markdown
  source/_cookbook/ifttt.manything.markdown
  source/_docs/automation/examples.markdown
  source/_docs/ecosystem/appdaemon/api.markdown
  source/_integrations/blink.markdown
  source/_integrations/google_assistant.markdown
  source/_integrations/group.markdown
  source/_posts/2015-09-19-alarm-sonos-and-itunes-support.markdown
Labels: has-parent, next, parent-merged

#11653 Update Media Player Shuffle Set to include Sonos
  source/_integrations/media_player.markdown
Labels: current, has-parent

#11671 Added documentation gesture support Deconz
  source/_integrations/deconz.markdown
Labels: has-parent, new-feature, next, parent-merged

#11670 Add Device Class info for customization
  source/_integrations/media_player.markdown
Labels: current

#11669 Add Media Player as component with Device Classes
  source/_docs/configuration/customizing-devices.markdown
Labels: current

#11668 add testing notes for Q9F
  source/_integrations/samsungtv.markdown
Labels: current

#11674 Correct spelling of HDMI-CEC
  source/_addons/cec_scan.markdown
  source/_integrations/apple_tv.markdown
  source/_integrations/hdmi_cec.markdown
  source/_posts/2017-01-28-face-coffee-wink.markdown
  source/_posts/2017-02-03-hassbian-toybox.markdown
  source/_posts/2017-02-25-config-panel-and-state-restoration.markdown
  source/_posts/2017-04-30-hassbian-1.21-its-about-time.markdown
Labels: current

#11658 Switch order of Python and ADB server instructions
  source/_integrations/androidtv.markdown
Labels: current

#11675 Add link to Modbus Climate
  source/_integrations/modbus.markdown
Labels: current

#11572 Add Stookalert integration
  source/_integrations/stookalert.markdown
  source/images/supported_brands/stookalert.png
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#11685 Update input_datetime: reorder default values
  source/_integrations/input_datetime.markdown
Labels: current

#11680 remove api_password option from http: config
  source/_docs/ecosystem/certificates/tls_domain_certificate.markdown
Labels: current

#11676 Add docs in vaccum.xiaomi_miio.markdown with how to clean a specific room
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#11688 Update condition.markdown
  source/_docs/automation/condition.markdown
Labels: current

#11693 Update PiVPN URL
  source/_docs/configuration/securing.markdown
Labels: current

#11597 Update Misc Typos
  source/_docs/authentication/providers.markdown
  source/_docs/ecosystem/appdaemon/tutorial.markdown
  source/_integrations/aws.markdown
  source/_integrations/vera.markdown
Labels: current

#11523 New nomenclature for Roborock fan speeds
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11699 tts platform renamed
  source/_cookbook/sonos_say.markdown
Labels: current

#11679 Migrate Ring to config entry
  source/_integrations/ring.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11694 Remove nonexistent default value of "initial" configuration variable for input_text.
  source/_integrations/input_text.markdown
Labels: has-parent, next

#11689 Add TP06 model to dyson docs
  source/_integrations/dyson.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11666 Removing Windows
  source/_docs/installation.markdown
Labels: current

#11708 Add tunnel timeout to support websocket connections
  source/_docs/ecosystem/haproxy.markdown
Labels: current, has-parent

#11711 Fix broken link in html5.markdown
  source/_integrations/html5.markdown
Labels: current

#11710 Changed the temp and range options
  source/_integrations/enocean.markdown
Labels: current

#11695 Add cover to ZHA supported devices
  source/_integrations/zha.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11714 Update sensor.buienradar.markdown
  source/_integrations/sensor.buienradar.markdown
Labels: next

#11713 Add Proxmox Permissions Information
  source/_integrations/proxmoxve.markdown
Labels: current

#11696 Update solax.markdown
  source/_integrations/solax.markdown
Labels: current

#11705 Updated the appdaemon repository. The current version is not valid.
  source/_docs/ecosystem/appdaemon/running.markdown
Labels: current

#11686 Add Android example
  source/_cookbook/track_battery_level.markdown
Labels: current

#11667 Add docs for upcoming SimpliSafe changes
  source/_integrations/simplisafe.markdown
Labels: awaits-parent, has-parent, new-feature, next

#11717 Fixed ws-url and needed steps.
  source/_integrations/spc.markdown
Labels: current, has-parent, parent-merged

#11723 continue_on_timeout clarification
  source/_docs/scripts.markdown
Labels: current

#11721 On->on & Off->off
  source/_integrations/binary_sensor.markdown
Labels: current

#11700 Update nederlandse_spoorwegen.markdown
  source/_integrations/nederlandse_spoorwegen.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11718 Add another TV to Samsung TV supported devices
  source/_integrations/samsungtv.markdown
Labels: current

#11726 HassOS 3.8
  source/hassio/installation.markdown
Labels: current

#11725 Add handling of missing devices to HomematicIP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: current

#11709 Removing the windows guide
  source/_docs/installation/python.markdown
  source/_docs/installation/windows.markdown
Labels: current

#11727 Remove hidden property from xiaomi_miio.remote integration
  source/_integrations/remote.xiaomi_miio.markdown
Labels: has-parent, next, parent-merged

#11715 Clarify which name to put in devices
  source/_integrations/automatic.markdown
Labels: current

#11728 Remove auto_hide from emby integration
  source/_integrations/emby.markdown
Labels: has-parent, next, parent-merged

#9801 Documentation for template alarm_control_panel
  source/_integrations/alarm_control_panel.template.markdown
Labels: has-parent, new-feature, next, parent-merged

#11730 Removes Cisco Spark integration
  source/_integrations/ciscospark.markdown
  source/_posts/2019-04-24-release-92.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/images/supported_brands/ciscospark.png
Labels: has-parent, next, parent-merged

#11733 Remove references to 'template lock', add list of supported values in configuration
  source/_integrations/alarm_control_panel.template.markdown
Labels: next

#11734 Fix typo in Google Assistant add-on page
  source/_addons/google_assistant.markdown
Labels: current

#11732 Update docs to reflect changes in fritzbox integration
  source/_integrations/fritz.markdown
  source/_integrations/fritzbox_callmonitor.markdown
  source/_integrations/fritzbox_netmonitor.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11736 Update dsmr.markdown - fixed broken URL
  source/_integrations/dsmr.markdown
Labels: current

#11737 Add Odroid N2 beta
  source/hassio/installation.markdown
Labels: current

#11738 Frontend release notes
  source/_posts/2020-01-15-release-104.markdown
  source/images/blog/2020-01-0.104/add-device-lovelace.png
  source/images/blog/2020-01-0.104/entities-multi-select.png
  source/images/blog/2020-01-0.104/ignore-discovery.png
  source/images/blog/2020-01-0.104/lovelace-suggestion.png
  source/images/blog/2020-01-0.104/remove-lovelace-config.png
  source/images/blog/2020-01-0.104/zha-config-panel.png
Labels: blog, rc

#11741 No longer loaded by default
  source/_integrations/discovery.markdown
Labels: current

#11739 add breaking changes descriptions
  source/_posts/2020-01-15-release-104.markdown
Labels: rc

#11743 Add missing language tag to codeblock
  source/_integrations/webostv.markdown
Labels: rc

#11742 Add useful logging example
  source/_integrations/logger.markdown
Labels: current

#11632 Update greeneye_monitor for voltage addition
  source/_integrations/greeneye_monitor.markdown
Labels: awaits-parent, has-parent, new-feature, next, parent-merged

#11744 Fix ha_release for 2 new integrations
  source/_integrations/local_ip.markdown
  source/_integrations/surepetcare.markdown
Labels: rc

#11740 Add small note to alarmdotcom panel
  source/_integrations/alarmdotcom.markdown
Labels: current

#11745 Update Sentry logo to the black version
  source/_integrations/sentry.markdown
  source/images/supported_brands/sentry.png
  source/images/supported_brands/sentry.svg
Labels: rc

#11746 Adds logo for Sure Petcare
  source/_integrations/surepetcare.markdown
  source/images/supported_brands/sure_petcare.png
Labels: rc

#11750 Update of 0.104 release notes
  source/_posts/2020-01-15-release-104.markdown
  source/images/blog/2020-01-0.104/add-device-lovelace.png
  source/images/blog/2020-01-0.104/components.png
  source/images/blog/2020-01-0.104/entities-multi-select.png
  source/images/blog/2020-01-0.104/ignore-discovery.png
  source/images/blog/2020-01-0.104/lovelace-suggestion.png
  source/images/blog/2020-01-0.104/remove-entity.png
  source/images/blog/2020-01-0.104/remove-lovelace-config.png
  source/images/blog/2020-01-0.104/zha-config-panel.png
Labels: blog, rc

#11747 Logger available namespaces
  source/_integrations/logger.markdown
Labels: current

#11754 Remove deprecated hide_entity for automations
  source/_docs/automation/examples.markdown
  source/_integrations/automation.markdown
  source/_integrations/flic.markdown
  source/_integrations/rova.markdown
  source/_integrations/telegram_chatbot.markdown
  source/_posts/2016-09-29-async-sleepiq-emoncms-stocks.markdown
Labels: has-parent, next, parent-merged

#11755 Remove multiple login methods from mikrotik
  source/_integrations/mikrotik.markdown
Labels: has-parent, next, parent-merged

#11758 Sync current docs with codebase release 0.104.0
  CODEOWNERS
  source/_integrations/brother.markdown
  source/_integrations/elgato.markdown
  source/_integrations/evohome.markdown
  source/_integrations/gios.markdown
  source/_integrations/icloud.markdown
  source/_integrations/intesishome.markdown
  source/_integrations/kef.markdown
  source/_integrations/local_ip.markdown
  source/_integrations/onewire.markdown
  source/_integrations/pilight.markdown
  source/_integrations/ring.markdown
  source/_integrations/sentry.markdown
  source/_integrations/signal_messenger.markdown
  source/_integrations/stookalert.markdown
  source/_integrations/surepetcare.markdown
  source/_integrations/template.markdown
  source/_integrations/tesla.markdown
  source/_integrations/tmb.markdown
  source/_integrations/webostv.markdown
  source/_integrations/workday.markdown
Labels: current

#11757 Fixed sentence in acupsd.markdown
  source/_integrations/apcupsd.markdown
Labels: current

#11761 Update webostv.markdown
  source/_integrations/webostv.markdown
Labels: current

#11763 Remove legacy api_password occurances
  source/_docs/configuration/yaml.markdown
  source/_docs/tools/credstash.markdown
  source/_integrations/http.markdown
Labels: current

#11772 📝 Update Lovelace changelog for 0.104
  source/lovelace/changelog.markdown
Labels: current

#11767 Deprecate weblink integration
  source/_integrations/weblink.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11765 Remove states UI options in group integration
  source/_docs/configuration/group_visibility.markdown
  source/_includes/asides/docs_navigation.html
  source/_integrations/group.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11766 Remove hide_if_away from device_tracker
  source/_integrations/device_tracker.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11773 Add Hue to breaking changes
  source/_integrations/hue.markdown
  source/_posts/2020-01-15-release-104.markdown
Labels: awaits-parent, current, has-parent

#11783 Small typo in description Stookalert
  source/_integrations/stookalert.markdown
Labels: current

#11784 Mention deconz breaking change in blog post for 0.104
  source/_posts/2020-01-15-release-104.markdown
Labels: current

#11781 Fix spelling of iOS
  source/_integrations/signal_messenger.markdown
Labels: current

#11786 Update kef.markdown
  source/_integrations/kef.markdown
Labels: current

#11788 Update signal_messenger.markdown
  source/_integrations/signal_messenger.markdown
Labels: current

#11795 Updates vacuum.xioami_miio docs
  source/_integrations/vacuum.xiaomi_miio.markdown
Labels: current

#11797 Added how to get DSN to documentation
  source/_integrations/sentry.markdown
Labels: current

#11794 Update browser list with webos failure
  source/_docs/frontend/browsers.markdown
Labels: current

#11793 Update discovery page to add IOT Link
  source/_docs/mqtt/discovery.markdown
Labels: current

#11777 Add breaking change for google assistant
  source/_posts/2020-01-15-release-104.markdown
Labels: blog, current

#11775 Wording tweaks
  source/_integrations/alexa.markdown
Labels: current

#11801 Fixed header styling
  source/_docs/z-wave/installation.markdown
Labels: current

#11778 Add notes about deprecated api_key
  source/_integrations/google_assistant.markdown
Labels: current, has-parent

#11800 Fix can't add multiple iCloud accounts (remove account name)
  source/_integrations/icloud.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#11805 Update list of tp-link kasa supported devices
  source/_integrations/tplink.markdown
Labels: current
