Repository home-assistant/home-assistant.io, pull requests merged in 2021-10, with the labels that each got.

#19544 Fix dead link to pysma library
  source/_integrations/sma.markdown
Labels: Hacktoberfest, cla-signed, current

#19542 Correct typo/grammar for Trackr removal
  source/_posts/2021-10-06-release-202110.markdown
Labels: Hacktoberfest, cla-signed, rc

#19545 Update index.html
  source/blue/index.html
Labels: Hacktoberfest, cla-signed, current

#19415 Note last added item in Plex library sensor
  source/_integrations/plex.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#19551 Remove Linux Battery logo
  source/_integrations/linux_battery.markdown
  source/images/supported_brands/linux_battery.png
Labels: Hacktoberfest, cla-signed, awaits-parent, current, has-parent

#19546 Changed remaining adoptor's to adapter
  source/_integrations/aurora_abb_powerone.markdown
  source/_integrations/homeworks.markdown
Labels: Hacktoberfest, cla-signed, current

#19552 Remove lametric.png
  source/_integrations/lametric.markdown
  source/images/supported_brands/lametric.png
Labels: Hacktoberfest, cla-signed, current, has-parent

#19559 cron option is optional
  source/_integrations/utility_meter.markdown
Labels: Hacktoberfest, cla-signed, current

#19561 Fix grammar for Kodi
  source/_integrations/kodi.markdown
Labels: Hacktoberfest, cla-signed, current

#19580 Fix broken link on Denon AVR integration
  source/_integrations/denonavr.markdown
Labels: Hacktoberfest, cla-signed, current

#19579 Fix wrong URL on Z-Wave integration
  source/_integrations/zwave_js.markdown
Labels: Hacktoberfest, cla-signed, current

#19576 Update todoist.markdown
  source/_integrations/todoist.markdown
Labels: Hacktoberfest, cla-signed, current

#19562 Fix typos for Recorder
  source/_integrations/recorder.markdown
Labels: Hacktoberfest, cla-signed, current

#19584 Repair broken link in System Health
  source/_integrations/system_health.markdown
Labels: Hacktoberfest, cla-signed, current

#19577 Improve readability on the update URL of the Telegram integration
  source/_integrations/telegram.markdown
Labels: Hacktoberfest, cla-signed, current

#19560 Fix minor typos for 17Track
  source/_integrations/seventeentrack.markdown
Labels: Hacktoberfest, cla-signed, current

#19563 Fixing errors with Workday
  source/_integrations/workday.markdown
Labels: Hacktoberfest, cla-signed, current

#19585 Fix broken external link in Bosch BMP280 Environmental Sensor
  source/_integrations/bmp280.markdown
Labels: Hacktoberfest, cla-signed, current

#19578 Remove presure sensor
  source/_integrations/point.markdown
Labels: Hacktoberfest, cla-signed, next, has-parent

#19567 Various improvements to documentation for TP-Link LTE
  source/_integrations/tplink_lte.markdown
Labels: Hacktoberfest, cla-signed, current

#19565 Better alt text on Etcher screenshots
  source/_includes/installation/operating_system.md
Labels: Hacktoberfest, cla-signed, current

#19583 Add clarification on brand names
  source/_integrations/hunterdouglas_powerview.markdown
Labels: Hacktoberfest, cla-signed, current

#19574 Remove Essent integration
  source/_integrations/essent.markdown
  source/_redirects
Labels: Hacktoberfest, cla-signed, awaits-parent, in-progress, current, has-parent, cleanup

#19586 Fix broken link in TP-Link Kasa Smart
  source/_integrations/tplink.markdown
Labels: Hacktoberfest, cla-signed, current

#19597 Adjust documentation for config flow rewrite
  source/_integrations/tuya.markdown
  source/images/integrations/tuya/image_008.png
Labels: Hacktoberfest, cla-signed, next, has-parent

#19554 Improve deCONZ documentation
  source/_integrations/deconz.markdown
Labels: Hacktoberfest, cla-signed, in-progress, next, needs-rebase

#19591 Clarify Mullvad integration
  source/_integrations/mullvad.markdown
Labels: Hacktoberfest, cla-signed, in-progress, current

#19607 Use https for MaterialDesignIcons project links
  source/_docs/configuration/customizing-devices.markdown
  source/lovelace/badges.markdown
  source/lovelace/dashboards.markdown
  source/lovelace/header-footer.markdown
  source/lovelace/views.markdown
Labels: Hacktoberfest, cla-signed, current

#19599 Reflect Tuya IoT Platform changes to names and webpage structure
  source/_integrations/tuya.markdown
  source/images/integrations/tuya/image_001.png
  source/images/integrations/tuya/image_002.png
  source/images/integrations/tuya/image_003.png
  source/images/integrations/tuya/image_004.png
  source/images/integrations/tuya/image_005.png
  source/images/integrations/tuya/image_006.png
  source/images/integrations/tuya/image_007.png
  source/images/integrations/tuya/image_008.png
Labels: Hacktoberfest, cla-signed, next

#19609 Updating Bluesound documentation
  source/_integrations/bluesound.markdown
Labels: Hacktoberfest, cla-signed, current, has-parent

#19611 Updating EverLights documentation
  source/_integrations/everlights.markdown
Labels: Hacktoberfest, cla-signed, current, has-parent

#19612 Update documentation URLs for security and privacy
  source/_docs/backend/database.markdown
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/configuration/yaml.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/mqtt/testing.markdown
  source/_docs/tools/dev-tools.markdown
  source/_docs/z-wave/control-panel.markdown
  source/_includes/common-tasks/development_version.md
  source/_includes/installation/container/alternative.md
  source/developers/cla.markdown
  source/help/index.markdown
  source/help/trivia.markdown
Labels: Hacktoberfest, cla-signed, in-progress, current

#19614 Updating Graphite documentation
  source/_integrations/graphite.markdown
Labels: Hacktoberfest, cla-signed, awaits-parent, current, has-parent, needs-rebase

#19610 Fix broken links in documentation
  source/_integrations/universal.markdown
Labels: Hacktoberfest, cla-signed, cla-error, in-progress, current

#19623 Region -> Country and minor tweaks
  source/_integrations/tuya.markdown
Labels: Hacktoberfest, cla-signed, next, has-parent

#19570 Update iotawatt.markdown for using the new high accuracy sensors
  source/_integrations/iotawatt.markdown
Labels: Hacktoberfest, cla-signed, in-progress, next, needs-rebase

#19616 Updating Launch Library documentation
  source/_integrations/launch_library.markdown
  source/images/supported_brands/rocket.png
Labels: Hacktoberfest, cla-signed, in-progress, current, has-parent

#19629 Move template breaking change up
  source/_posts/2021-10-06-release-202110.markdown
Labels: Hacktoberfest, cla-signed, current

#20073 Change order of nest instructions in fewer steps
  source/_integrations/nest.markdown
Labels: Hacktoberfest, cla-signed, current

#20050 Update ecovacs template sensor & binary_sensor examples
  source/_integrations/ecovacs.markdown
Labels: Hacktoberfest, cla-signed, current

#20064 Update to Node.js 16, the latest LTS
  .github/workflows/test.yml
  .nvmrc
Labels: Hacktoberfest, cla-signed, current

#20054 Update imap_email_content template sensor examples
  source/_integrations/imap_email_content.markdown
Labels: Hacktoberfest, cla-signed, current

#20053 Update homematic templates examples
  source/_integrations/homematic.markdown
Labels: Hacktoberfest, cla-signed, in-progress, current

#20055 Correct template select docs
  source/_integrations/template.markdown
Labels: Hacktoberfest, cla-signed, current

#20056 Fix configuration block on the Scenes page
  source/_docs/scene.markdown
Labels: Hacktoberfest, cla-signed, current

#20095 Improve wording for android_ip_webcam
  source/_integrations/android_ip_webcam.markdown
Labels: Hacktoberfest, cla-signed, current

#20100 Clarify check_config script is only for Core installations
  source/_docs/configuration/secrets.markdown
Labels: Hacktoberfest, cla-signed, current

#20067 Update nest.markdown to define the expiry period
  source/_integrations/nest.markdown
Labels: Hacktoberfest, cla-signed, current
