Repository home-assistant/home-assistant.io, pull requests merged in 2021-08, with the labels that each got.

#18683 FIX: It's "trace:", not "traces:"
  source/_docs/automation/yaml.markdown
Labels: cla-signed, current

#18674 Clarify light `white` turn_on parameter has no corresponding state attribute
  source/_integrations/light.markdown
Labels: cla-signed, current

#18675 Update scene examples
  source/_integrations/scene.markdown
Labels: cla-signed, current

#18655 edl21: Add DZG DWS76 as tested smart meter
  source/_integrations/edl21.markdown
Labels: cla-signed, current

#18650 Document change to Lutron button events for un-named buttons
  source/_integrations/lutron.markdown
Labels: cla-signed, has-parent, next

#18691 Allow combinations write_coil/read_coils and write_coils/read_coil for modbus switch
  source/_integrations/modbus.markdown
Labels: cla-signed, has-parent, new-feature, next

#18693 Add energy analytics
  source/_integrations/analytics.markdown
Labels: cla-signed, has-parent, new-feature, next

#18695 New Lovelace element 2021.8
  source/_includes/asides/lovelace_navigation.html
  source/_lovelace/alarm-panel.markdown
  source/_lovelace/button.markdown
  source/_lovelace/calendar.markdown
  source/_lovelace/conditional.markdown
  source/_lovelace/energy.markdown
  source/_lovelace/entities.markdown
  source/_lovelace/entity-filter.markdown
  source/_lovelace/entity.markdown
  source/_lovelace/gauge.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/grid.markdown
  source/_lovelace/history-graph.markdown
  source/_lovelace/horizontal-stack.markdown
  source/_lovelace/humidifier.markdown
  source/_lovelace/iframe.markdown
  source/_lovelace/light.markdown
  source/_lovelace/logbook.markdown
  source/_lovelace/map.markdown
  source/_lovelace/markdown.markdown
  source/_lovelace/masonary.markdown
  source/_lovelace/media-control.markdown
  source/_lovelace/panel.markdown
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
  source/_lovelace/picture.markdown
  source/_lovelace/plant-status.markdown
  source/_lovelace/sensor.markdown
  source/_lovelace/shopping-list.markdown
  source/_lovelace/sidebar.markdown
  source/_lovelace/statistics-graph.markdown
  source/_lovelace/thermostat.markdown
  source/_lovelace/vertical-stack.markdown
  source/_lovelace/weather-forecast.markdown
  source/images/lovelace/energy/carbon-consumed-gauge.png
  source/images/lovelace/energy/devices-graph.png
  source/images/lovelace/energy/distribution.png
  source/images/lovelace/energy/grid-neutrality-gauge.png
  source/images/lovelace/energy/solar-consumed-gauge.png
  source/images/lovelace/energy/solar-graph.png
  source/images/lovelace/energy/sources-table.png
  source/images/lovelace/energy/usage-graph.png
  source/images/lovelace/lovelace_gauge_needle_card.png
  source/images/lovelace/lovelace_statistics_graph_bar.png
  source/images/lovelace/lovelace_statistics_graph_line.png
  source/lovelace/badges.markdown
  source/lovelace/cards.markdown
  source/lovelace/dashboards.markdown
  source/lovelace/views.markdown
Labels: cla-signed, in-progress, new-feature, next

#18678 Add support for MJJSQ humidifiers for Xiaomi MIIO integration
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18699 Masonry typo
  source/_lovelace/masonary.markdown
Labels: cla-signed, in-progress, needs-rebase, next

#18702 Update about section
  _config.yml
  source/_includes/asides/about.html
  source/_includes/custom/welcome.html
  source/index.html
Labels: cla-signed, current

#18711 Add Home Energy Management to features
  source/_includes/custom/features.html
Labels: cla-signed, in-progress, needs-rebase, next

#18682 extend fritz doc
  source/_integrations/fritz.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, next

#18709 Document date selector
  source/_lovelace/energy.markdown
  source/images/lovelace/energy/date-selection.png
Labels: cla-signed, in-progress, needs-rebase, next

#18703 Add note that only TTNv2 is supported
  source/_integrations/thethingsnetwork.markdown
Labels: cla-signed, current

#18708 Energy updates
  source/_docs/energy/electricity-grid.markdown
  source/_docs/energy/faq.markdown
  source/_docs/energy/individual-devices.markdown
  source/_docs/energy/solar-panels.markdown
  source/_includes/asides/docs_navigation.html
  source/images/docs/energy/home-assistant-glow.jpg
  source/images/docs/energy/slimmelezer.jpg
Labels: cla-signed, in-progress, needs-rebase, next

#18701 Correct statistics text
  source/_lovelace/masonry.markdown
  source/_lovelace/statistics-graph.markdown
Labels: cla-signed, in-progress, needs-rebase, next

#17558 Universal media player toggle
  source/_integrations/universal.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18603 System Bridge - Data from WebSocket - Docs Update
  source/_integrations/system_bridge.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18644 Move power and energy attributes to sensors
  source/_integrations/tplink.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next, parent-merged

#18694 Adds "limits" configuration to Lovelace sensor docs
  source/_lovelace/sensor.markdown
Labels: cla-signed, current

#18696 More numeric_state attribute/value_template docs
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current, in-progress

#18712 Lovelace typos
  source/_lovelace/energy.markdown
  source/_lovelace/panel.markdown
  source/lovelace/cards.markdown
Labels: cla-signed, in-progress, needs-rebase, next

#18700 Fixes to Energy related documentation
  source/_docs/energy/electricity-grid.markdown
  source/_docs/energy/faq.markdown
  source/_docs/energy/solar-panels.markdown
Labels: cla-signed, in-progress, needs-rebase, next

#18713 Update feedback card styling
  sass/custom/_paulus.scss
Labels: cla-signed, current

#18689 Add energy landingpage
  sass/custom/_landingpage.scss
  sass/custom/_paulus.scss
  sass/screen.scss
  source/_includes/custom/features.html
  source/_includes/feedback.html
  source/_layouts/default.html
  source/_layouts/landingpage.html
  source/_layouts/page.html
  source/_redirects
  source/blue/index.html
  source/home-energy-management/index.html
  source/images/energy/cost.png
  source/images/energy/distribution.png
  source/images/energy/hero.jpg
  source/images/energy/individual_devices.png
  source/images/energy/vector-connect.png
  source/images/energy/vector-graph.png
  source/images/energy/vector-money.png
  source/images/energy/vector-sun.png
  source/index.html
Labels: cla-signed, in-progress, needs-rebase, next

#18668 Add stop service to Rachio
  source/_integrations/rachio.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next, parent-merged

#18726 Add blog energy management
  source/_posts/2021-08-04-home-energy-management.markdown
  source/_posts/2021-08-04-release-20218.markdown
  source/images/blog/2021-08-energy/architecture.png
  source/images/blog/2021-08-energy/config-dialogs.png
  source/images/blog/2021-08-energy/energy-usage.png
  source/images/blog/2021-08-energy/klaas-prototype.png
  source/images/blog/2021-08-energy/sidebar-widgets.png
  source/images/blog/2021-08-energy/social.png
  source/images/blog/2021-08-energy/solar-production.png
Labels: blog, cla-signed, in-progress, needs-rebase, rc

#18727 Redirect energy integration to energy docs
  source/_redirects
Labels: cla-signed, current

#18729 typo
  source/_posts/2021-08-04-release-20218.markdown
Labels: cla-signed, current

#18732 Add energy to `default_config` list
  source/_integrations/default_config.markdown
Labels: cla-signed, current

#18734 Fixes the currency configuration to use ISO 4217
  source/_docs/configuration/basic.markdown
Labels: cla-signed, current

#14383 Add new component renault documentation
  source/_integrations/renault.markdown
Labels: awaits-parent, cla-signed, current, has-parent, in-progress, needs-rebase, new-integration

#18724 add lumi.gateway.aqhm01 support
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18728 Adjust documentation for config flow
  source/_integrations/uptimerobot.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18768 Update media_player.markdown
  source/_integrations/media_player.markdown
Labels: cla-needed, current

#18743 Typo in statistics-graph options
  source/_lovelace/statistics-graph.markdown
Labels: cla-signed, current

#18771 Remove comma
  source/_docs/configuration/basic.markdown
Labels: cla-signed, current

#18745 Add energy tag to solarlog docs
  source/_integrations/solarlog.markdown
Labels: cla-signed, current, in-progress

#17939 Add docs for Tractive
  source/_integrations/tractive.markdown
  source/images/integrations/tractive/device_tracker.png
Labels: cla-signed, has-parent, new-integration, next, parent-merged

#18715 [Fixer.io] Update rate limit
  source/_integrations/fixer.markdown
Labels: cla-signed, current

#18785 Fixes missing forward slash prefix on url
  source/_docs/automation/templating.markdown
Labels: cla-signed, current

#18792 Correct SMA energy meter entity descriptions
  source/_integrations/sma.markdown
Labels: cla-signed, current

#18807 Updated to correct indent
  source/_lovelace/picture-elements.markdown
Labels: cla-signed, current

#18806 Update pvoutput.markdown, corrected identation
  source/_integrations/pvoutput.markdown
Labels: cla-signed, current

#18810 Fix broken link in Tautulli integration docs
  source/_integrations/tautulli.markdown
Labels: cla-signed, current

#18813 Change "remove" to "delete" in zwave_js tutorial
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#18844 Update generic_hygrostat.markdown
  source/_integrations/generic_hygrostat.markdown
Labels: cla-signed, current

#18833 Fix broken url in docs
  source/_docs/configuration.markdown
Labels: cla-signed, current

#18826 Fixes link in scripts.markdown
  source/_docs/blueprint/schema.markdown
  source/_docs/scripts.markdown
Labels: cla-signed, current

#18797 Small error in grammar
  source/_integrations/integration.markdown
Labels: cla-signed, current

#18796 local_file: typo
  source/_integrations/local_file.markdown
Labels: cla-signed, current

#18845 Power vs Energy in sensor descriptions
  source/_integrations/sma.markdown
Labels: cla-signed, current

#18855 Tag doc typo
  source/_integrations/tag.markdown
Labels: cla-signed, current

#18858 Add changelog for 2021.8.4
  _config.yml
  source/_posts/2021-08-04-release-20218.markdown
Labels: cla-signed, current

#18750 Update tesla.markdown
  source/_integrations/tesla.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#18814 Remove broken ISS camera snippet
  source/_integrations/iss.markdown
Labels: cla-signed, current

#18812 Update electricity-grid.markdown
  source/_docs/energy/electricity-grid.markdown
Labels: cla-signed, current

#18811 Update dsmr.markdown
  source/_integrations/dsmr.markdown
Labels: cla-signed, current

#18808 Fixed typo and cleaned up language for Lovelace Card documentation
  source/lovelace/cards.markdown
Labels: cla-signed, current

#18805 Update modbus markdown typo
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#18801 Update forecast_solar.markdown
  source/_integrations/forecast_solar.markdown
Labels: cla-signed, current

#18818 Switcher KIS Documentation: Add clarification about old firmware versions.
  source/_integrations/switcher_kis.markdown
Labels: cla-signed, in-progress, current

#18776 Update humidifier.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
Labels: cla-signed, current

#18774 Smappee Integration - minor note re mDNS
  source/_integrations/smappee.markdown
Labels: cla-signed, current

#18867 Fix Xiaomi-miio humidifiers - correct modes and document attributes
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#18866 Clarify login credentials and prerequisites
  source/_integrations/dexcom.markdown
Labels: cla-signed, current

#18862 Add information about light transition for Shelly integration
  source/_integrations/shelly.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#18869 Add an example template to extract air quality
  source/_integrations/vesync.markdown
Labels: cla-signed, current

#18782 Add `state_class` to KNX sensor
  source/_integrations/knx.markdown
Labels: new-feature, cla-signed, next, has-parent

#18793 Add `binary_sensor` documentation for Xiaomi Miio integration
  source/_integrations/xiaomi_miio.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#18697 Add service homeassistant.save_persistent_states
  source/_integrations/homeassistant.markdown
Labels: new-feature, cla-signed, next, has-parent

#18873 Update Stiebel Eltron supported units
  source/_integrations/stiebel_eltron.markdown
Labels: cla-signed, current

#18872 Update Climacell rate limit
  source/_integrations/climacell.markdown
Labels: cla-signed, next, has-parent

#18821 Add message_wait_milliseconds for modbus
  source/_integrations/modbus.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#18856 Make note about new siren feature
  source/_integrations/siren.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#18880 Remove wink from Z-Wave guide
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, current

#18883 Update to Supported USB Sticks
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, current

#18884 Deprecate wink.
  source/_integrations/wink.markdown
Labels: cla-signed, next, has-parent

#18904 add iCloud example
  source/_integrations/caldav.markdown
Labels: cla-signed, current

#18893 Remove broken links from Serial Particulate Matter integration page
  source/_integrations/serial_pm.markdown
Labels: cla-signed, current

#18903 Update tplink.markdown include device KP40 support
  source/_integrations/tplink.markdown
Labels: cla-signed, current

#18909 Add number/siren category and platform to zwave_js page metadata
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#18923 Add Teleinfo Mqtt and What'sup Docker? to the list of the third-party…
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#18930 Remove intesishome logo after migrating logos to Brands repo
  source/_integrations/intesishome.markdown
Labels: cla-signed, current, has-parent

#18931 Small Nest docs tweaks/fixes
  source/_integrations/nest.markdown
Labels: cla-signed, current

#18937 correction on sensor name
  source/_integrations/flipr.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#18936 Remove alternatives from version
  source/_integrations/version.markdown
Labels: cla-signed, current

#18912 Add information about sensor platform for fan
  source/_integrations/xiaomi_miio.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#18934 Fix for Issure #18933: change "install media" to "boot media" and add more detailed descript…
  source/_includes/installation/operating_system.md
Labels: cla-signed, in-progress, current

#18956 Fixed minor grammer issue in electricity-grid.markdown
  source/_docs/energy/electricity-grid.markdown
Labels: cla-signed, current

#18915 Add select platform and category to zwave_js docs
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next, has-parent, parent-merged

#18955 Convert nmap_tracker to be a config flow
  source/_integrations/nmap_tracker.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#18957 Add new air quality device classes
  source/_integrations/sensor.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#18739 Change above/below confusion in clarification of example
  source/_docs/automation/trigger.markdown
Labels: current

#18733 Add device class update
  source/_integrations/binary_sensor.markdown
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged

#18964 Added ZIV as working with the DSMR integration
  source/_integrations/dsmr.markdown
Labels: cla-signed, current

#18926 Add documentation for new upnp binary sensor
  source/_integrations/upnp.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#18830 Removed now obsolete max_results
  source/_integrations/calendar.google.markdown
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged

#18976 Add Binary Sensor category for template integration doc
  source/_integrations/template.markdown
Labels: cla-signed, in-progress, current

#18966 Add information about `select` platform for Xiaomi Miio fans
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, next, has-parent, parent-merged

#18928 Add light to MyQ
  source/_integrations/myq.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#18970 Clarify which devices have been tested with the august integration
  source/_integrations/august.markdown
Labels: cla-signed, current

#18945 Add an example for calling the Pi-hole disable service
  source/_integrations/pi_hole.markdown
Labels: cla-signed, in-progress, current

#18994 Fix confusing typo in vicare
  source/_integrations/vicare.markdown
Labels: cla-signed, current

#18985 "iframe Panel" better example
  source/_integrations/panel_iframe.markdown
Labels: cla-signed, in-progress, current

#18996 Improve DSMR documentation and document support for Swedish meters
  source/_integrations/dsmr.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#19001 Fix formatting of numbers in prefix warning box
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#19003 Document Zigbee energy profile
  source/_docs/energy/electricity-grid.markdown
Labels: cla-signed, current

#19005 'Monetary' missing from list of Device Classes
  source/_integrations/sensor.markdown
Labels: cla-signed, current

#19000 Add docs for P1 Monitor integration
  source/_integrations/p1_monitor.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#19012 Add information about `switch` platform for Xiaomi Miio fans
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, next, has-parent, parent-merged

#18542 Add fjäråskupan documentation
  source/_integrations/fjaraskupan.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#19016 Document area_id as an input to zwave_js services
  source/_integrations/zwave_js.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19017 docs: update required paid plan for using this field
  source/_integrations/openexchangerates.markdown
Labels: cla-signed, current

#19023 Document known discoverable zwave_js devices
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next, has-parent

#19025 Add information about `number` platform for Xiaomi Miio fans
  source/_integrations/xiaomi_miio.markdown
Labels: new-feature, cla-signed, next, has-parent

#19028 Add ZWaveMe stick to zwave_js known discoverable devices
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next

#18878 Lazy error in modbus
  source/_integrations/modbus.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#19030 Update CT clamp docs
  source/_docs/energy/electricity-grid.markdown
Labels: cla-signed, current

#19022 Document known discoverable zha devices
  source/_integrations/zha.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#19015 Add Usb discovery
  source/_integrations/default_config.markdown
  source/_integrations/usb.markdown
Labels: new-integration, cla-signed, in-progress, next, has-parent, parent-merged

#15717 Airtouch4 integration
  CODEOWNERS
  source/_integrations/airtouch4.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#18802 You need a Pro subscription to access API
  source/_integrations/point.markdown
Labels: cla-signed, current

#18882 Fix broken code link, edit for clarity.
  source/_integrations/denonavr.markdown
Labels: cla-signed, in-progress, current

#19032 Update when usb devices are detected
  source/_integrations/usb.markdown
Labels: new-feature, cla-signed, next, has-parent

#19034 Small tweak to frontend integration page
  source/_integrations/frontend.markdown
Labels: cla-signed, current

#18995 Add documentation for play media in yamaha_musiccast
  source/_integrations/yamaha_musiccast.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#19008 Add documentation on zwave_js automations
  source/_integrations/zwave_js.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#18978 Add notes on the new logger info device for fronius
  source/_integrations/fronius.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#18575 Add quality scale for goalzero
  source/_integrations/goalzero.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#19053 Add volatile organic compounds device class
  source/_integrations/sensor.markdown
Labels: cla-signed, next, has-parent, parent-merged

#19049 Add basic battery/gas docs
  source/_docs/energy.markdown
  source/_docs/energy/battery.markdown
  source/_docs/energy/gas.markdown
  source/_integrations/powerwall.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#19048 Eagle-200 docs
  source/_integrations/rainforest_eagle.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#19058 Update tplink.markdown: include device EP40 support
  source/_integrations/tplink.markdown
Labels: cla-signed, current

#19061 Fix solarlog unit of measurements
  source/_integrations/solarlog.markdown
Labels: cla-signed, next, has-parent

#18799 Add information about `sensor` platform for Tractive integration
  source/_integrations/tractive.markdown
Labels: new-feature, cla-signed, next, has-parent

#19067 Remove Wp (watt-peak) from unit of measurements
  source/_integrations/solarlog.markdown
Labels: cla-signed, next, has-parent, parent-merged

#18493 Add blogpost about upcomming supervisor changes
  source/_posts/2021-08-24-supervisor-update.markdown
Labels: cla-signed, blog, current, has-parent

#19035 Adjust homeassistant services description to clarify their purpose
  source/_integrations/homeassistant.markdown
Labels: cla-signed, current

#19036 Remove non-existing services from Kostal Plenticore documentation
  source/_integrations/kostal_plenticore.markdown
Labels: cla-signed, current, has-parent

#19037 Clarify target example in script service call documentation
  source/_docs/scripts/service-calls.markdown
Labels: cla-signed, current

#19038 Fix typo in fido documentation
  source/_integrations/fido.markdown
Labels: cla-signed, current

#19033 Fixes typo on Derivative page
  source/_integrations/derivative.markdown
Labels: cla-signed, current

#18885 Fixed Hue bulb reset instructions
  source/_integrations/zha.markdown
Labels: cla-signed, current

#19057 Change description for unhealthy
  source/more-info/unhealthy/untrusted.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#19070 Update 2021-08-24-supervisor-update.markdown
  source/_posts/2021-08-24-supervisor-update.markdown
Labels: cla-signed, current

#18851 Configurable default `hvac_mode` for KNX climate
  source/_integrations/knx.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#18962 Add binary sensor platform to Renault integration
  source/_integrations/renault.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19071 Update year in blogpost
  source/_posts/2021-08-24-supervisor-update.markdown
Labels: cla-signed, current
