Repository home-assistant/home-assistant.io, pull requests merged in 2021-07, with the labels that each got.

#18358 Update climate.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
Labels: cla-signed, current

#18241 Update daikin.markdown
  source/_integrations/daikin.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18363 Allow combining value_template and position_template for template cover
  source/_integrations/cover.template.markdown
Labels: cla-signed, has-parent, new-feature, next

#18360 Update acmeda.markdown
  source/_integrations/acmeda.markdown
Labels: cla-signed, current, in-progress

#18367 Adds core.md web interface links
  source/_includes/installation/core.md
Labels: cla-signed, current

#18355 Add new service set_rain_delay
  source/_integrations/rainbird.markdown
Labels: cla-signed, has-parent, new-feature, next

#18370 Add Smappee Connect series
  source/_integrations/smappee.markdown
Labels: cla-signed, current

#18373 Update Fritz sensors list and deprecate fritzbox_netmonitor
  source/_integrations/fritz.markdown
  source/_integrations/fritzbox_netmonitor.markdown
  source/_redirects
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18389 Fix two HVAC mode typos
  source/_integrations/knx.markdown
Labels: cla-signed, current

#18388 Add sensor docs for AirVisual
  source/_integrations/airvisual.markdown
Labels: cla-signed, has-parent, next

#18343 Migrate `air_quality` platform to `sensor` for GIOS integration
  source/_integrations/gios.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18381 Fix typo in documentation
  source/_integrations/alexa.smart_home.markdown
Labels: cla-signed, current

#17638 Add sensor platform documentation to goalzero
  source/_integrations/goalzero.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18378 Typo in automation.turn_off part
  source/_docs/automation/services.markdown
Labels: cla-signed, current

#18376 Update API Key cURL to reflect correct URL
  source/_integrations/avion.markdown
Labels: cla-needed, current

#18401 Corrected Synology Docker update instruction
  source/_includes/installation/container/alternative.md
Labels: cla-signed, current

#18409 Add Rituals breaking change and number platform to release notes
  source/_posts/2021-07-07-release-20217.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, rc

#18408 Update TH-P60ST50A supported model note
  source/_integrations/panasonic_viera.markdown
Labels: cla-signed, current

#18403 Revert nmap_tracker to 2021.6 version
  source/_integrations/nmap_tracker.markdown
Labels: cla-signed, has-parent, next

#18411 Adjust check config documentation
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_faq/component.markdown
  source/_includes/common-tasks/configuration_check.md
Labels: cla-signed, current

#18425 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#18426 Highlighting breaking change/prerequisite
  source/_includes/installation/container.md
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#18418 2021-07-07-release-20217.markdown: fix typos
  source/_posts/2021-07-07-release-20217.markdown
Labels: cla-signed, current

#18430 Update foscam.markdown
  source/_integrations/foscam.markdown
Labels: cla-signed, current

#18417 Update vendor link to the international site
  source/_integrations/fritz.markdown
Labels: cla-signed, current

#18431 Add Fritz missing info for device profiles and port forwards
  source/_integrations/fritz.markdown
Labels: cla-signed, current

#18472 Add missing ha_category
  source/_integrations/remote.markdown
Labels: cla-signed, current

#18475 Inject post.url for anchor links
  source/_includes/blog/post/article.html
Labels: cla-signed, current

#18476 Fix incorrect default scan interval for Luftdaten
  source/_integrations/luftdaten.markdown
Labels: cla-signed, current

#18462 Add missing tag
  source/_includes/installation/container/cli.md
Labels: cla-signed, current

#18465 Update mqtt_room.markdown Added my ESP-32-BLE-Scanner for Home Assistant
  source/_integrations/mqtt_room.markdown
Labels: cla-signed, current

#18452 fixed typo
  source/_integrations/ambee.markdown
Labels: cla-signed, current

#18458 Clarify and fix formatting for MQTT light JSON schema
  source/_integrations/light.mqtt.markdown
Labels: cla-signed, current

#18447 Clarifies usage of trusted_proxies
  source/_integrations/http.markdown
Labels: cla-signed, current

#18479 Add missing webhook to default config docs
  source/_integrations/default_config.markdown
Labels: cla-signed, current

#18454 MQTT Fan docs - sorted config and small text corrections
  source/_integrations/fan.mqtt.markdown
Labels: cla-signed, current, in-progress

#18406 Add array write to turn_on/off in modbus switch/fan/light
  source/_integrations/modbus.markdown
Labels: cla-signed, has-parent, new-feature, next

#18486 Fix broken links in dwd weather warnings
  source/_integrations/dwd_weather_warnings.markdown
Labels: cla-signed, current

#18499 Fix tables on SMA integration page
  source/_integrations/sma.markdown
Labels: cla-signed, current

#18496 Add references to traces for automation debugging
  source/_docs/automation/troubleshooting.markdown
  source/_docs/automation/yaml.markdown
  source/images/integrations/automation/automation-tracing.png
Labels: cla-signed, current

#18504 Update Z-Wave JS docs
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#18497 Document automation trigger ID template variables
  source/_docs/automation/templating.markdown
Labels: cla-signed, current

#18508 Remove defunct Weather Underground integration
  source/_integrations/wunderground.markdown
  source/_redirects
Labels: cla-signed, cleanup, has-parent, next, parent-merged

#18503 Update ohmconnect.markdown
  source/_integrations/ohmconnect.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#18509 Deprecate Lyft integration
  source/_integrations/lyft.markdown
Labels: cla-signed, has-parent, next

#18459 Doc for Coinbase exchange rate base currency option
  source/_integrations/coinbase.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next, parent-merged

#18519 Mark Tasmota PR adding support for color_mode white and removing support for rgbw as breaking
  source/_posts/2021-07-07-release-20217.markdown
Labels: cla-signed, current

#18523 Removed icon
  source/_lovelace/gauge.markdown
Labels: cla-signed, current

#18524 Additional step to link multiple Spotify accounts
  source/_integrations/spotify.markdown
Labels: cla-signed, current

#18529 Document `white` light `turn_on` parameter
  source/_integrations/light.markdown
Labels: cla-signed, current

#18467 Update huawei_lte auth config
  source/_integrations/huawei_lte.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase, parent-merged

#18527 Update ambee with API requirements.
  source/_integrations/ambee.markdown
Labels: cla-signed, current

#18525 Add name to Utility Meter configuration options
  source/_integrations/utility_meter.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18445 Rename device profiles to parental control for fritz integration
  source/_integrations/fritz.markdown
Labels: cla-signed, has-parent, new-feature, next

#18549 Update media_player.markdown
  source/_integrations/media_player.markdown
Labels: cla-signed, current

#18546 Add unmaintained warning to ozw integration
  source/_integrations/ozw.markdown
Labels: cla-signed, current

#17576 Adding documentation for new Gree features
  source/_integrations/gree.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18551 updated external broken links
  source/_integrations/magicseaweed.markdown
Labels: cla-signed, current

#17128 Add docs for new siren platform
  source/_integrations/siren.markdown
Labels: cla-signed, has-parent, in-progress, new-integration, next, parent-merged

#18369 New modbus data types
  source/_integrations/modbus.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#18420 Update to reflect use of Network integration
  source/_integrations/sonos.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase, parent-merged

#18450 Add MQTT humidifier documentation
  source/_docs/mqtt/discovery.markdown
  source/_integrations/humidifier.mqtt.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase, parent-merged

#18346 Add Switcher config flow discovery support
  source/_integrations/switcher_kis.markdown
Labels: cla-signed, has-parent, new-feature, next

#18495 add binary sensor to freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18490 Add switch to freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#18494 add sensor to freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18489 add lock to Freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, new-feature, next, parent-merged

#18518 add fan to Freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18517 add cover to Freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, next, parent-merged

#18553 Update tibber.markdown
  source/_integrations/tibber.markdown
Labels: cla-signed, current

#18407 Update icloud.markdown with section on app specific passwords.
  source/_integrations/icloud.markdown
Labels: cla-signed, current

#18435 Clarify country name configuration MeteoAlarm
  source/_integrations/meteoalarm.markdown
Labels: cla-signed, current

#17814 Update honeywell documentation
  source/_integrations/honeywell.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18466 Update smtp.markdown
  source/_integrations/smtp.markdown
Labels: cla-signed, current, in-progress

#18552 Update co2signal.markdown
  source/_integrations/co2signal.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18558 Document new options parameter for zwave_js.set_value service
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18554 Add IKEA Tradfri shortcut button limitation note
  source/_integrations/tradfri.markdown
Labels: cla-signed, current

#18556 Add missing Nanoleaf to discovery integration documentation
  source/_integrations/discovery.markdown
Labels: cla-signed, current

#18560 Add unique ID support to light, cover and media player groups
  source/_integrations/cover.group.markdown
  source/_integrations/light.group.markdown
  source/_integrations/media_player.group.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#13876 Add generic_hygrostat integration
  source/_integrations/generic_hygrostat.markdown
Labels: cla-signed, has-parent, new-integration, next, parent-merged

#18564 Fix docker command
  source/_includes/installation/container/cli.md
Labels: cla-signed, current

#18565 Update prometheus configuration example for version 2.26+
  source/_integrations/prometheus.markdown
Labels: cla-signed, current

#18561 Add docs for new goalzero sensors
  source/_integrations/goalzero.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18541 Documentation update for Advantage Air PR #51941
  source/_integrations/advantage_air.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18567 Add event to binary sensor example
  source/_integrations/template.markdown
Labels: cla-signed, current

#18532 Growatt - Added alternative server specification info
  source/_integrations/growatt_server.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17950 Add Adax heaters
  source/_integrations/adax.markdown
Labels: awaits-parent, cla-signed, has-parent, next

#18482 Added in some Words about Battery Drain potential.
  source/_integrations/tesla.markdown
Labels: cla-signed, current, in-progress

#16596 Add Flipr integration
  source/_integrations/flipr.markdown
Labels: awaits-parent, cla-signed, has-parent, new-integration, next

#18543 Change 'condition' to 'conditions'
  source/_docs/scripts/conditions.markdown
Labels: cla-signed, current

#18566 Add Silicon Labs SLUSB7000A to the supported list
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, current, in-progress

#18576 Minor typo updates to integrations/alert doco
  source/_integrations/alert.markdown
Labels: cla-signed, current

#18577 Document the homekit.unpair service
  source/_integrations/homekit.markdown
Labels: cla-signed, has-parent, new-feature, next

#17998 Updated IoT class to Cloud Push.
  source/_integrations/wirelesstag.markdown
Labels: cla-signed, has-parent, new-feature, next

#18415 Google Assistant - update fan platform capabilties
  source/_integrations/google_assistant.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#14352 Documentation for new Automate integration
  source/_integrations/acmeda.markdown
  source/_integrations/automate.markdown
Labels: cla-signed, has-parent, in-progress, next, parent-merged

#18398 Remove total_consumption attribute
  source/_integrations/fritzbox.markdown
Labels: cla-signed, has-parent, next, parent-merged

#18580 Update zwave-js docs with new parameter for multicast_set_value service
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, next

#18590 CO2signal extra sensor doc
  source/_integrations/co2signal.markdown
Labels: cla-signed, has-parent, new-feature, next

#18591 Add Brel Home to supported brands for motion blinds
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, current

#17496 Mention support for velux light devices
  source/_integrations/velux.markdown
Labels: cla-signed, has-parent, new-feature, next

#17900 Update yale_smart_alarm documentation
  source/_integrations/yale_smart_alarm.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18597 Add how to disable auto polling to google and waze travel docs
  source/_integrations/google_travel_time.markdown
  source/_integrations/waze_travel_time.markdown
Labels: cla-signed, current

#18599 Improvements for nest documentation based on recent user issues
  source/_integrations/nest.markdown
Labels: cla-signed, current

#18601 Fixed typo in Select entity documentation
  source/_integrations/select.markdown
Labels: cla-signed, current

#18614 Added header for "Reverse proxies" section
  source/_integrations/http.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#18605 Feat/calendar google docs
  source/_integrations/calendar.google.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#18613 Fix webhook trigger.json example
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#18609 Fixed small errors in cast.markdown
  source/_integrations/cast.markdown
Labels: cla-signed, current

#18585 Deprecate wled.preset service
  source/_integrations/wled.markdown
Labels: cla-signed, cleanup, has-parent, next

#18555 Clean up device vs entity mixup in older documentation
  source/_docs/configuration/devices.markdown
Labels: cla-signed, current

#18584 Add WLED playlist support
  source/_integrations/wled.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18563 Add crossfade option in `sonos.set_option` service
  source/_integrations/sonos.markdown
Labels: cla-signed, has-parent, new-feature, next

#18628 docs(automation): clarify the importance of cross
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#18630 Add select platform back to Rituals Perfume Genie
  source/_integrations/rituals_perfume_genie.markdown
Labels: cla-signed, current

#18631 Upgrade Rituals Perfume Genie to quality level "silver"
  source/_integrations/rituals_perfume_genie.markdown
Labels: cla-signed, has-parent, next

#18423 Add description for removing holidays by name
  source/_integrations/workday.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18641 KNX hs-color lights
  source/_integrations/knx.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17706 Adds Prosegur
  source/_integrations/prosegur.markdown
Labels: awaits-parent, cla-signed, has-parent, new-integration, next, parent-merged

#18637 Remove Garmin Connect integration
  CODEOWNERS
  source/_integrations/garmin_connect.markdown
  source/_redirects
Labels: cla-signed, cleanup, has-parent, next

#18540 Add documentation on new template functions for devices
  source/_docs/automation/templating.markdown
  source/_docs/configuration/templating.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18627 Add currency core configuration
  source/_docs/configuration/basic.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18505 Add this variable for use by automation and script templates
  source/_docs/automation/templating.markdown
  source/_integrations/script.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next

#18339 Xiaomi_Miio Humidifier rework
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, next

#18295 Add minimum hours-to-show
  source/_lovelace/logbook.markdown
  source/_lovelace/sensor.markdown
  source/lovelace/header-footer.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18544 Update modbus description of scan interval (breaking change)
  source/_integrations/modbus.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18573 Update to PyVicare 1.0
  source/_integrations/vicare.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#18589 More recent Google Home linking instructions
  source/_integrations/google_assistant.markdown
Labels: cla-signed, current

#18433 Update bluetooth_tracker.markdown
  source/_integrations/bluetooth_tracker.markdown
Labels: cla-signed, current

#18392 Update tuya.markdown
  source/_integrations/tuya.markdown
Labels: cla-signed, current

#18109 Update the "I'm Locked Out" documentation for using a container CLI
  source/_docs/locked_out.md
Labels: cla-signed, current, in-progress

#18477 Add missing suggested_area information
  source/_integrations/number.mqtt.markdown
  source/_integrations/select.mqtt.markdown
Labels: cla-signed, current

#15271 Add documentation for YouLess integration
  source/_integrations/youless.markdown
Labels: Hacktoberfest, awaits-parent, cla-signed, hacktoberfest-accepted, has-parent, new-integration, next, parent-merged

#18534 Update description of modbus count (it can now be calculated).
  source/_integrations/modbus.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next, parent-merged

#18025 Add documenation for nfandroidtv config flow
  source/_integrations/nfandroidtv.markdown
Labels: cla-signed, has-parent, in-progress, next, parent-merged

#17314 Refactor bme280, add SPI support
  source/_integrations/bme280.markdown
Labels: cla-signed, has-parent, in-progress, next, parent-merged

#18646 Move the alert location
  .gitignore
  Rakefile
  sass/custom/_paulus.scss
  source/_includes/asides/component_navigation.html
  source/_layouts/default.html
  source/_layouts/page.html
Labels: cla-signed, current

#18521 add climate to freedompro
  source/_integrations/freedompro.markdown
Labels: cla-signed, has-parent, next, parent-merged

#18328 Energy Docs
  source/_docs/energy.markdown
  source/_docs/energy/electricity-grid.markdown
  source/_docs/energy/faq.markdown
  source/_docs/energy/individual-devices.markdown
  source/_docs/energy/solar-panels.markdown
  source/_includes/asides/docs_navigation.html
  source/images/docs/energy/devices.png
  source/images/docs/energy/energy-overview.png
  source/images/docs/energy/grid.png
  source/images/docs/energy/solar.png
Labels: cla-signed, in-progress, needs-rebase, new-feature, next

#18648 Fix Prosegur link in 2021.8.0 release notes
  source/_posts/2021-08-04-release-20218.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#18587 Document zwave_js.reset_meter service
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#18657 Add energy statistics more info
  source/more-info/statistics.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, next

#18659 Update the in-page anchor
  source/more-info/statistics.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, next

#18656 Revert "Documentation for new Automate integration"
  source/_integrations/acmeda.markdown
  source/_integrations/automate.markdown
Labels: cla-signed, has-parent, next

#18666 Add default value for active installations
  source/_includes/asides/component_navigation.html
Labels: cla-signed, current

#18664 Update tplink.markdown
  source/_integrations/tplink.markdown
Labels: cla-signed, current

#18667 Update hikvision.markdown
  source/_integrations/hikvision.markdown
Labels: cla-signed, current
