Repository home-assistant/home-assistant.io, pull requests merged in 2021-09, with the labels that each got.

#18960 Add device tracker platform to Renault integration
  source/_integrations/renault.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#19160 Add select platform to Renault integration
  source/_integrations/renault.markdown
Labels: cla-signed, in-progress, current, has-parent, parent-merged

#18983 Update sensor list for Sense integration.
  source/_integrations/sense.markdown
Labels: new-feature, cla-signed, next, has-parent

#19100 Add vacation mode to manual alarm_control_panel
  source/_integrations/manual.markdown
Labels: new-feature, cla-signed, next, has-parent

#19155 Add documentation on how to use IoTaWatt with energy management
  source/_integrations/iotawatt.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#19162 Fix release notes
  source/_posts/2021-09-01-release-20219.markdown
Labels: cla-signed, current

#18981 Add services to Renault integration
  source/_integrations/renault.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19164 Legacy firmware 1.26
  source/_integrations/dlink.markdown
Labels: cla-signed, current

#19186 Fix template number & select quoting errors
  source/_posts/2021-09-01-release-20219.markdown
Labels: cla-signed, current

#19192 Improve information about entities naming in Shelly integration
  source/_integrations/shelly.markdown
Labels: cla-signed, current

#19182 Update cycle parameter in utility_meter
  source/_integrations/utility_meter.markdown
Labels: cla-signed, current

#19190 Add gas usage graph to energy.markdown
  source/_lovelace/energy.markdown
  source/images/lovelace/energy/gas-graph.png
Labels: cla-signed, current

#19189 Add step to number template example
  source/_posts/2021-09-01-release-20219.markdown
Labels: cla-signed, current

#19197 Fix small formatting error in documentation
  source/_docs/authentication/providers.markdown
Labels: cla-signed, current

#18704 System Bridge 2.5.0 - Additional Sensors Docs
  source/_integrations/system_bridge.markdown
Labels: cla-signed, next, has-parent, parent-merged

#19167 Homepage CSS change for Sponsors and In the Press
  sass/custom/_paulus.scss
  source/images/sponsors/nabu_casa.svg
  source/index.html
Labels: cla-signed, current

#19124 Update keba.markdown
  source/_integrations/keba.markdown
Labels: cla-signed, current

#19043 Add reference to context in automation templating
  source/_docs/automation/templating.markdown
  source/_docs/configuration/state_object.markdown
Labels: cla-signed, in-progress, current

#19052 Alternative for 18559
  sass/oscailte/base/_navigation.scss
Labels: cla-signed, current

#19213 Add manual configuration example to zeroconf
  source/_integrations/zeroconf.markdown
Labels: cla-signed, current

#19215 Xiaomi Miio hyperlink to Air Purifier Segment broken
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#19217 Add "gas" to the list of sensor.device_class
  source/_integrations/sensor.markdown
Labels: cla-signed, current

#19227 Remove references to legacy `ti_cc` ZHA radio library
  source/_integrations/zha.markdown
Labels: cla-signed, in-progress, current, has-parent

#19243 Removed incorrect information
  source/_docs/configuration/splitting_configuration.markdown
Labels: cla-signed, current

#19238 Clarify that `condition` only stops current sequence
  source/_docs/scripts.markdown
Labels: cla-signed, current

#19236 Update deluge.markdown
  source/_integrations/deluge.markdown
Labels: cla-signed, current

#19218 CSS added margin top to Sponsors box as in Press box
  sass/custom/_paulus.scss
  source/index.html
Labels: cla-signed, current

#19232 Add variable names for number and select
  source/_integrations/template.markdown
Labels: cla-signed, current

#19257 Remove Trackr integration (API removed) - Updated
  source/_integrations/trackr.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged

#19272 Fixed typo (platfrom -> platform)
  source/_posts/2021-09-01-release-20219.markdown
Labels: cla-signed, current

#19269 Update Link For Red Hat Security Guide
  source/_docs/configuration/securing.markdown
Labels: cla-signed, current

#19267 Correct type of MQTT optimistic configuration
  source/_integrations/cover.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
Labels: cla-signed, current

#19253 Update yeelight.markdown
  source/_integrations/yeelight.markdown
Labels: cla-signed, current

#19280 Yamaha Musiccast - Add Troubleshooting section
  source/_integrations/yamaha_musiccast.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#19281 Note about SNTP for Shelly
  source/_integrations/shelly.markdown
Labels: cla-signed, current

#19305 Add link to addons page from compare table.
  source/installation/index.html
Labels: cla-signed, current

#19268 Mention grid card for masonry views
  source/_lovelace/masonry.markdown
Labels: cla-signed, current

#19273 Update emoncms.markdown
  source/_integrations/emoncms.markdown
Labels: cla-signed, current

#19266 Remove reference to white_value from MQTT light documentation
  source/_integrations/light.mqtt.markdown
Labels: cla-signed, current

#19301 Downscaled two images on the homepage
  source/images/press/troyhunt.jpg
  source/images/press/tweakers.png
Labels: cla-signed, current

#19255 Use `map` for `headers` field in the rest_command integration
  source/_integrations/rest_command.markdown
Labels: cla-signed, current

#19248 Use watt in example
  source/_integrations/template.markdown
Labels: cla-signed, current

#19306 Add notes for 2021.9.6
  source/_posts/2021-09-01-release-20219.markdown
Labels: cla-signed, current

#19314 Add libturbojpeg to the apt-get install list
  source/_includes/installation/core.md
Labels: cla-signed, current

#19286 Remove meteoalarm image
  source/images/supported_brands/meteoalarm.png
Labels: cla-signed, current, has-parent

#19313 Update modbus.markdown
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#19298 Add example: write a 32-bit float value register
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#19309 Update the velbus documentation for the velbusaio module
  source/_integrations/velbus.markdown
Labels: cla-signed, next, has-parent, parent-merged

#19307 Use configuration_basic for db_url examples for readability
  source/_integrations/recorder.markdown
Labels: cla-signed, current

#19151 Added HMIP-DLD Integration
  source/_integrations/homematic.markdown
Labels: cla-signed, current

#17466 Add ZHA best practices for avoiding pairing difficulties
  source/_integrations/zha.markdown
Labels: cla-signed, in-progress, current, integration: zha

#19329 Netgear Config Flow documentation
  source/_integrations/netgear.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19328 Clarify Daikin warning
  source/_integrations/daikin.markdown
Labels: cla-signed, current

#19317 Update youless.markdown
  source/_integrations/youless.markdown
Labels: cla-signed, current

#19216 Add state_class to abbreviations
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#19343 Use energy category not platform for youless
  source/_integrations/youless.markdown
Labels: cla-signed, current

#19336 Add info on trigger id's uniqueness requirement
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#19346 Correct links on modbus page
  source/_integrations/modbus.markdown
Labels: cla-signed, current, by-code-owner, integration: modbus

#19322 Add Surepetcare config flow
  source/_integrations/surepetcare.markdown
Labels: cla-signed, next, has-parent, parent-merged

#19362 Fix missing }
  source/_integrations/template.markdown
Labels: cla-signed, current

#19354 Clarify that overriding Home in UI is not supported
  source/_integrations/zone.markdown
Labels: cla-signed, current

#19366 InfluxDB: Clarify queries and queries_flux options
  source/_integrations/influxdb.markdown
Labels: cla-signed, current

#17841 Add Crownstone documentation
  source/_integrations/crownstone.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#19308 Current example in Conditions documentation don't work
  source/_docs/scripts/conditions.markdown
Labels: cla-signed, current

#19370 Fix meteoalarm image
  source/_integrations/meteoalarm.markdown
Labels: cla-signed, current

#19340 Add note about subscription for Flume API
  source/_integrations/flume.markdown
Labels: cla-signed, current

#19386 Fix my home-assistant link to Configuration
  source/_docs/configuration.markdown
Labels: cla-signed, current

#19405 Update Discovery integration docs
  source/_integrations/discovery.markdown
Labels: cla-signed, current

#19409 Drop unused feedback: true from blog posts
  source/_posts/2021-03-03-release-20213.markdown
  source/_posts/2021-03-18-nabu-casa-has-acquired-esphome.markdown
  source/_posts/2021-04-07-release-20214.markdown
  source/_posts/2021-05-05-release-20215.markdown
  source/_posts/2021-06-02-release-20216.markdown
  source/_posts/2021-07-07-release-20217.markdown
  source/_posts/2021-08-04-home-energy-management.markdown
  source/_posts/2021-08-04-release-20218.markdown
  source/_posts/2021-09-01-release-20219.markdown
Labels: current

#19398 Remove `mode` and `model` attributes of Xiaomi Miio air purifiers
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, next, has-parent, parent-merged

#19395 Update alarm_control_panel.mqtt.markdown
  source/_integrations/alarm_control_panel.mqtt.markdown
Labels: current

#19347 Textual clarification for Home energy management
  source/_docs/energy.markdown
Labels: cla-signed, current

#19410 Fix alert for multiple integrations
  source/_layouts/page.html
Labels: cla-signed, current

#19356 Motion blinds add troubleshooting for Ubiquiti IGMPv3 setting
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, current

#19345 Add the unit ft³ for the device_classe gas for sensors
  source/_integrations/sensor.markdown
Labels: cla-signed, current

#19400 Add information about Shelly generation 2 devices
  source/_integrations/shelly.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19423 Fix typo
  source/_integrations/shelly.markdown
Labels: cla-signed, current

#19420 Update list of modems known to NOT work
  source/_integrations/sms.markdown
Labels: cla-signed, current

#19208 Add port for VSX-824
  source/_integrations/pioneer.markdown
Labels: cla-needed, current

#19318 Added a CSV example
  source/_integrations/file.markdown
Labels: cla-signed, in-progress, current

#19429 Typo fixes in automation trigger docs
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#19427 Add OS-Agent unsupported message
  source/more-info/unsupported/os_agent.markdown
Labels: cla-signed, awaits-parent, current

#19434 USB or Zeroconf discoverable Zigbee coordinator by Tube
  source/_integrations/zha.markdown
Labels: cla-signed, next, has-parent

#18965 Add input_select to Supported Components
  source/_integrations/homekit.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#19368 Add mention of energy: to Energy FAQ
  source/_docs/energy/faq.markdown
Labels: cla-signed, current

#19339 Clean up upnp YAML config
  source/_integrations/upnp.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#19170 Description of restart service in modbus
  source/_integrations/modbus.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#18979 Add upnp sensor for IP, Status, and Uptime
  source/_integrations/upnp.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19371 Add config flow documentation to switchbot
  source/_integrations/switchbot.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19315 Add WattTime docs
  source/_integrations/watttime.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#19229 Add `state_color` to Entity card
  source/_lovelace/entity.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#19222 Add `icon` to attribute row
  source/_lovelace/entities.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19271 Remove Tesla integration
  source/_integrations/tesla.markdown
  source/_redirects
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged, cleanup

#17326 Add Whirlpool integration
  source/_integrations/whirlpool.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#19249 Add date device class
  source/_integrations/sensor.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19237 Deprecate `unit` in integration Riemann Sum
  source/_integrations/integration.markdown
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#19235 Added services for bond integration state belief
  source/_integrations/bond.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19416 surepetcare.set_pet_location
  source/_integrations/surepetcare.markdown
Labels: new-feature, cla-signed, next, has-parent

#19465 Fix grammer typos
  source/_integrations/template.markdown
Labels: cla-signed, current

#19449 Remove stale 1-Wire configuration
  source/_integrations/onewire.markdown
Labels: cla-signed, current, has-parent

#19454 Add example for ser2net 4.X.X
  source/_integrations/dsmr.markdown
Labels: cla-signed, current

#19453 Update nissan_leaf.markdown
  source/_integrations/nissan_leaf.markdown
Labels: cla-signed, in-progress, current

#19478 Update hue.markdown
  source/_integrations/hue.markdown
Labels: cla-signed, current

#19479 Fixed default for code_arm_required in Template Alarm docs
  source/_integrations/alarm_control_panel.template.markdown
Labels: cla-signed, current

#19486 Set nvmrc to use nodejs 14 (LTS)
  .nvmrc
Labels: cla-signed, current

#19489 Add script to accepted blueprint domains
  source/_docs/blueprint/schema.markdown
Labels: cla-signed, current

#19487 Document is_number filter and function
  source/_docs/configuration/templating.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#19441 Clarify `timestamp_local` and `timestamp_utc` template filters
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#19492 Use `is_number` in template examples
  source/_docs/configuration/templating.markdown
Labels: cla-signed, in-progress, next

#19493 Update dsmr.markdown
  source/_integrations/dsmr.markdown
Labels: cla-needed, current

#19355 mention helpers UI for timers
  source/_integrations/timer.markdown
Labels: cla-signed, in-progress, current

#19496 Fix broken my links/badges on automation troubleshooting page
  source/_docs/automation/troubleshooting.markdown
Labels: cla-signed, current

#19488 Bump ruby to 2.7.2, bump bundler 2.2.28
  .devcontainer/devcontainer.json
  .github/workflows/test.yml
  .ruby-version
  Gemfile.lock
Labels: cla-signed, current

#19440 Change template to use the day
  source/_integrations/time_date.markdown
Labels: cla-signed, current

#19483 update tplink docs for python-kasa rework
  source/_integrations/tplink.markdown
Labels: cla-signed, next, has-parent

#19087 Config-flow options for DLNA integration
  source/_integrations/dlna_dmr.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#19241 Add a note that if you want to manage users you have to enable advanced mode
  source/_docs/authentication.markdown
Labels: cla-signed, in-progress, current

#19396 Adding amberelectric documentation
  source/_integrations/amberelectric.markdown
Labels: new-integration, cla-signed, in-progress, next, has-parent, parent-merged

#19466 Add binary sensor platform to Tractive integration
  source/_integrations/tractive.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19507 Remove GitHub Action to build Jekyll
  .github/workflows/test.yml
Labels: cla-signed, current

#19508 Update workflow and devcontainer to Node 14
  .devcontainer/devcontainer.json
  .github/workflows/test.yml
Labels: cla-signed, current

#19447 Add information about standing MIOT fans, Xiaomi Miio integration
  source/_integrations/xiaomi_miio.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19464 Add docs for glances raid monitoring
  source/_integrations/glances.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19156 Add a TOC to the condition reference
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
Labels: cla-signed, in-progress, current

#18582 Change image of phone on homepage to newest iPhone model 12
  source/images/hero_screenshot.png
Labels: cla-signed, current

#19512 Fix typo in documentation
  source/_integrations/remember_the_milk.markdown
Labels: cla-signed, current

#19516 Update blue page
  sass/custom/_details.scss
  sass/custom/_landingpage.scss
  source/blue/index.html
Labels: cla-signed, current

#19522 Shelly Gen2 Add note about device authentication
  source/_integrations/shelly.markdown
Labels: cla-signed, next, has-parent

#19523 delete 'double' automatic
  source/_integrations/template.markdown
Labels: cla-signed, current

#19482 Update template alarm docs - add code_format
  source/_integrations/alarm_control_panel.template.markdown
Labels: new-feature, cla-signed, next, has-parent

#19458 Add locks to surepetcare
  source/_integrations/surepetcare.markdown
Labels: new-feature, cla-signed, next, has-parent

#19438 Update docs after fix for 56552
  source/_integrations/sms.markdown
Labels: cla-signed, current, has-parent, parent-merged

#19494 Document default parameter for float functions
  source/_docs/configuration/templating.markdown
Labels: new-feature, cla-signed, next, has-parent

#19506 Document default parameter for time template functions
  source/_docs/configuration/templating.markdown
Labels: cla-signed, next, has-parent

#19526 Fix zwave_js FAQ formatting
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#16631 Update Modem Caller ID docs for config flow
  source/_integrations/modem_callerid.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#19446 Create airthings.markdown
  source/_integrations/airthings.markdown
Labels: new-integration, cla-signed, in-progress, next, has-parent, parent-merged

#19297 proposed binary_sensor group
  source/_integrations/binary_sensor.group.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#19157 Add information about Tractive switch platform
  source/_integrations/tractive.markdown
Labels: new-feature, cla-signed, next, has-parent

#19530 Add ll-hls to stream
  source/_integrations/stream.markdown
Labels: cla-signed, next, has-parent

#19513 update doc for keyboard_remote type
  source/_integrations/keyboard_remote.markdown
Labels: cla-signed, next, has-parent, parent-merged

#19528 Roku integration: Remove duplicated "Remote" section
  source/_integrations/roku.markdown
Labels: cla-signed, current

#19364 Add new sensors to Kostal Plenticore integration.
  source/_integrations/kostal_plenticore.markdown
Labels: new-feature, cla-signed, next, has-parent

#19525 Added new Tuya v2 Integration
  source/_integrations/tuya.markdown
  source/images/integrations/tuya/image_001.png
  source/images/integrations/tuya/image_002.png
  source/images/integrations/tuya/image_003.png
  source/images/integrations/tuya/image_004.png
  source/images/integrations/tuya/image_005.png
  source/images/integrations/tuya/image_006.png
  source/images/integrations/tuya/image_007.png
  source/images/integrations/tuya/image_008.png
Labels: new-feature, cla-signed, in-progress, next, has-parent

#19531 UniFi remove_clients service
  source/_integrations/unifi.markdown
Labels: new-feature, cla-signed, next, has-parent

#19534 tiny edit
  source/_integrations/input_datetime.markdown
Labels: cla-signed, current

#19532 small edits
  source/_integrations/input_boolean.markdown
Labels: cla-signed, current
