Repository home-assistant/home-assistant.io, pull requests merged in 2021-04, with the labels that each got.

#17220 Add Denon AVR-S650H to denonavr integration documentation
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#17214 Add troubleshooting hint regarding "IGMP snooping"
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, current, in-progress

#16148 NWS sensor documentation addition
  source/_integrations/nws.markdown
Labels: has-parent, new-feature, next, parent-merged

#17233 Export Quality scale and IoT class for integrations
  source/integrations.json
Labels: cla-signed, current

#17230 Remove Geizhals integration (ADR-0004)
  .vscode/cSpell.json
  source/_integrations/geizhals.markdown
  source/_redirects
Labels: cla-signed, cleanup, has-parent, next, parent-merged

#17232 Country note
  source/_integrations/analytics.markdown
Labels: cla-signed, in-progress, needs-rebase, next

#17234 ✨ The 15th community highlight!
  source/_posts/2021-03-26-community-highlights.markdown
  source/_posts/2021-04-02-community-highlights.markdown
  source/images/blog/2021-04-02-community-highlights/banner-card.png
  source/images/blog/2021-04-02-community-highlights/botanist.jpg
  source/images/blog/2021-04-02-community-highlights/dashboard.png
  source/images/blog/2021-04-02-community-highlights/social.png
Labels: blog, cla-signed, current

#17249 Add missing internal quality_scale
  source/_integrations/calendar.markdown
  source/_integrations/command_line.markdown
  source/_integrations/default_config.markdown
  source/_integrations/dhcp.markdown
  source/_integrations/image_processing.markdown
  source/_integrations/local_ip.markdown
  source/_integrations/logbook.markdown
  source/_integrations/media_source.markdown
  source/_integrations/my.markdown
  source/_integrations/remote.markdown
  source/_integrations/search.markdown
  source/_integrations/ssdp.markdown
  source/_integrations/tts.markdown
  source/_integrations/vacuum.markdown
  source/_integrations/water_heater.markdown
Labels: cla-signed, current

#17237 Remove discontinued Nuki software bridge dead link
  source/_integrations/nuki.markdown
Labels: cla-signed, current

#17245 Add note about HomeKit reliability with older home hubs
  source/_integrations/homekit.markdown
Labels: cla-signed, current

#17243 Update docs for trigger-based template sensors.
  source/_integrations/template.markdown
Labels: cla-signed, has-parent, new-feature, next

#17260 Reword analytics
  source/_integrations/analytics.markdown
Labels: cla-signed, in-progress, needs-rebase, next

#17252 Fix documentation for new feature mqtt command templates
  source/_integrations/fan.mqtt.markdown
Labels: cla-signed, has-parent, next

#16975 Quick howto to flash Hue devices via OTA folder.
  source/_integrations/zha.markdown
Labels: cla-signed, current, in-progress

#15192 Add compensation integration
  source/_integrations/compensation.markdown
Labels: Hacktoberfest, cla-signed, hacktoberfest-accepted, has-parent, new-integration, next, parent-merged

#17250 Modbus service
  source/_integrations/modbus.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase, parent-merged

#17228 Feature/add heat on demand docs
  source/_integrations/hive.markdown
Labels: awaits-parent, cla-signed, current, has-parent, in-progress, needs-rebase, new-feature, parent-merged

#17263 Remove Social Blade integration (ADR-0004)
  source/_integrations/socialblade.markdown
  source/_redirects
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#15716 Update google_travel_time docs to reflect config flow support
  source/_integrations/google_travel_time.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#17267 Adjust view feedback button wording
  source/_includes/feedback.html
Labels: cla-signed, current

#17264 Add note about OpenWeatherMap API key activation delays
  source/_integrations/openweathermap.markdown
Labels: cla-signed, current

#17265 Add clarity to apostrophes meaning in SMTP docs
  source/_integrations/smtp.markdown
Labels: cla-signed, current

#17269 Make Google maps example clear to have an email
  source/_integrations/google_maps.markdown
Labels: cla-signed, current

#17270 Escape template in MQTT cover set_position_template
  source/_integrations/cover.mqtt.markdown
Labels: cla-signed, current

#17268 Add clarity to automation editor page example sensor
  source/_docs/automation/editor.markdown
Labels: cla-signed, current

#17266 Add alternative, easier method to get API token for FortiOS
  source/_integrations/fortios.markdown
Labels: cla-signed, current

#17227 Update mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: cla-signed, current, in-progress

#17192 Update enphase_envoy for config flow
  source/_integrations/enphase_envoy.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17129 Add SiteSage Emonitor integration
  source/_integrations/emonitor.markdown
Labels: cla-signed, has-parent, new-integration, next, parent-merged

#17284 Fix broken link in Tahoma documentation
  source/_integrations/tahoma.markdown
Labels: cla-signed, current

#17285 Fixed single/double quotes errors in examples
  source/_integrations/sensor.rest.markdown
Labels: cla-signed, current, in-progress

#17291 Cleanup Climacell v4 notice
  source/_integrations/climacell.markdown
Labels: cla-signed, has-parent, new-feature, next

#17292 Add note about breaking changes to zwave_js section of release notes
  source/_posts/2021-04-07-release-20214.markdown
Labels: blog, cla-signed, in-progress, rc

#17272 Add phonenumber notice to Tuya integration documentation
  source/_integrations/tuya.markdown
Labels: cla-signed, current

#17273 Ensure Centralite can be found in search engines
  source/_integrations/litejet.markdown
Labels: current

#17274 Remove ADB add-on from Android TV docs, as it is deprecated
  source/_integrations/androidtv.markdown
Labels: cla-signed, cleanup

#17283 Fix direct state attribute access in HomeMatic example
  source/_integrations/homematic.markdown
Labels: cla-signed, current

#17295 Update pvoutput.markdown
  source/_integrations/pvoutput.markdown
Labels: cla-needed, current

#17303 Apparmor more-info
  source/more-info/unsupported/apparmor.markdown
Labels: cla-signed, current

#17307 Change uuid
  source/_integrations/analytics.markdown
Labels: cla-signed, has-parent, new-feature, next

#17125 Add newly supported bulbs for tplink
  source/_integrations/tplink.markdown
Labels: cla-signed, has-parent, next, parent-merged

#17315 HAOS Update to 5.13
  _config.yml
Labels: cla-signed, current

#17319 Fix 2 broken link + typo
  source/_posts/2021-04-07-release-20214.markdown
Labels: cla-signed, current

#17335 Fix really tiny typo DMSR -> DSMR
  source/_posts/2021-04-07-release-20214.markdown
Labels: current

#17343 Finish sentence
  source/_integrations/filter.markdown
Labels: current

#17329 Fix MQTT Light Breaking Change details header
  source/_posts/2021-04-07-release-20214.markdown
Labels: cla-signed, current

#17332 Specify that only the owner can set analytics settings
  source/_integrations/analytics.markdown
Labels: cla-signed, current

#17350 Update ameridroid link
  source/blue/index.html
Labels: cla-signed, current

#17327 Blog post for the April 2021 Android release
  source/_posts/2021-04-09-android-april-2021-release.markdown
  source/images/blog/2021-04-09-android-april-2021/Companion.png
  source/images/blog/2021-04-09-android-april-2021/action_bar.png
  source/images/blog/2021-04-09-android-april-2021/high_accuracy_zone.png
  source/images/blog/2021-04-09-android-april-2021/log_viewer.png
  source/images/blog/2021-04-09-android-april-2021/shortcuts.png
Labels: blog, cla-signed, current

#17355 Remove scan_interval warning in PVOutput docs
  source/_integrations/pvoutput.markdown
Labels: cla-signed, current

#17353 Update tesla.markdown
  source/_integrations/tesla.markdown
Labels: cla-signed, current, in-progress

#17354 Remove stale statements from Bayesian docs
  source/_integrations/bayesian.markdown
Labels: cla-signed, current

#17363 ✨ The 16th community highlight!
  source/_posts/2021-04-09-community-highlights.markdown
  source/images/blog/2021-04-09-community-highlights/dashboard.png
  source/images/blog/2021-04-09-community-highlights/gauge.png
  source/images/blog/2021-04-09-community-highlights/notify.jpeg
  source/images/blog/2021-04-09-community-highlights/social.png
Labels: blog, cla-signed, current

#17370 Add missing anchor links for the patch releases
  source/_posts/2021-04-07-release-20214.markdown
Labels: cla-signed, current

#17377 Add missing patch release anchor link
  source/_posts/2021-04-07-release-20214.markdown
Labels: cla-signed, current, in-progress

#17359 Add note about Daikin streamer switch detection (#44727)
  source/_integrations/daikin.markdown
Labels: cla-error, cla-signed, current

#17368 Update panasonic_viera.markdown
  source/_integrations/panasonic_viera.markdown
Labels: cla-signed, current

#17367 Remove owner requirement for analytics
  source/_integrations/analytics.markdown
Labels: cla-signed, current, has-parent, in-progress

#17366 Fix accessory mode domain list in homekit
  source/_integrations/homekit.markdown
Labels: cla-signed, current

#17369 Improve example and explain speed_range for mqtt fan
  source/_integrations/fan.mqtt.markdown
  source/_integrations/fan.template.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#17375 Modbus typo: register -> address
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#17373 Add troubleshooting section and note about ad blockers
  source/_integrations/sharkiq.markdown
Labels: cla-signed, current

#17380 Correct internal quality scale labels to improve analytics
  source/_integrations/air_quality.markdown
  source/_integrations/command_line.markdown
  source/_integrations/geo_location.markdown
  source/_integrations/local_ip.markdown
  source/_integrations/stt.markdown
  source/_integrations/webhook.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#16360 rflink: Add hint about which configuration file is used
  source/_integrations/rflink.markdown
Labels: Stale, cla-signed, current

#17376 Corrected possible input_types for switch.
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#17381 Fix broken link on Lovelace Markdown card page
  source/_lovelace/markdown.markdown
Labels: cla-signed, current

#17378 Process feedback for Blink integration
  source/_integrations/blink.markdown
Labels: cla-signed, current

#17379 Process feedback for Hikvision documentation
  source/_integrations/hikvision.markdown
Labels: cla-signed, current

#17238 Fix Synology entity ID naming
  source/_integrations/synology_dsm.markdown
Labels: cla-signed, current, in-progress

#17364 Ezviz Update - New pull request includes Config flow.
  source/_integrations/ezviz.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#17333 Update generic.markdown section about the `rtsp_transport` option added recently
  source/_integrations/generic.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#17346 Remove the `name` variable from Amazon Polly documentation
  source/_integrations/amazon_polly.markdown
Labels: cla-signed, current

#17384 Improve min/max syntax in template docs
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#17385 Remove bad state attribute access example from state_object page
  source/_docs/configuration/state_object.markdown
Labels: cla-signed, current

#17383 Show integration usage
  .gitignore
  Rakefile
  sass/custom/_paulus.scss
  source/_includes/asides/component_navigation.html
Labels: cla-signed, current

#17386 Fix broken my link on templating configuration page
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#17387 Update style in Proximity doc
  source/_integrations/proximity.markdown
Labels: current

#17097 Add support for event type closed to integration folder_watcher
  source/_integrations/folder_watcher.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16957 Update cla_sign.html
  source/developers/cla_sign.html
Labels: cla-signed, current

#17390 Clarify Tuya.markdown available account types
  source/_integrations/tuya.markdown
Labels: cla-signed, current

#17396 Replace Cookbook with Examples
  Rakefile
  _config.yml
  package.json
  source/_cookbook/automation_enocean_phue.markdown
  source/_cookbook/automation_first_light.markdown
  source/_cookbook/automation_flashing_lights.markdown
  source/_cookbook/automation_for_rainy_days.markdown
  source/_cookbook/automation_sun.markdown
  source/_cookbook/automation_telegram_presence_alert.markdown
  source/_cookbook/automation_using_timeinterval_inputboolean.markdown
  source/_cookbook/dim_and_brighten_lights.markdown
  source/_cookbook/dim_lights_when_playing_media.markdown
  source/_cookbook/foscam_away_mode_PTZ.markdown
  source/_cookbook/notify_if__new_ha_release.markdown
  source/_cookbook/notify_if_over_threshold.markdown
  source/_cookbook/perform_actions_based_on_input_select.markdown
  source/_cookbook/restart_ha_if_wemo_switch_is_not_detected.markdown
  source/_cookbook/send_a_reminder.markdown
  source/_cookbook/sonos_say.markdown
  source/_cookbook/track_battery_level.markdown
  source/_cookbook/turn_on_light_for_10_minutes_when_motion_detected.markdown
  source/_data/blueprint_exchange_data.json
  source/_data/glossary.yml
  source/_docs/configuration.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/frontend.markdown
  source/_examples/configuration_yaml_by_DrJohnT.markdown
  source/_examples/configuration_yaml_by_alok_saboo.markdown
  source/_examples/configuration_yaml_by_aneisch.markdown
  source/_examples/configuration_yaml_by_apocrathia.markdown
  source/_examples/configuration_yaml_by_carlo_costanzo.markdown
  source/_examples/configuration_yaml_by_cy1701.markdown
  source/_examples/configuration_yaml_by_geekofweek.markdown
  source/_examples/configuration_yaml_by_gummientchen.markdown
  source/_examples/configuration_yaml_by_jimpower.markdown
  source/_examples/configuration_yaml_by_jonathan_adams.markdown
  source/_examples/configuration_yaml_by_joshuagarrison27.markdown
  source/_examples/configuration_yaml_by_klaasnicolaas.markdown
  source/_examples/configuration_yaml_by_mcaminiti.markdown
  source/_examples/configuration_yaml_by_shortbloke.markdown
  source/_examples/configuration_yaml_by_silvrrgit.markdown
  source/_examples/configuration_yaml_by_skalavala.markdown
  source/_examples/configuration_yaml_by_tinkerer.markdown
  source/_examples/configuration_yaml_by_ubhits.markdown
  source/_examples/google_maps_card.markdown
  source/_examples/notify.mqtt.markdown
  source/_examples/owntracks_two_mqtt_broker.markdown
  source/_includes/asides/cookbook_navigation.html
  source/_includes/custom/grid_item_right.html
  source/_includes/site/header.html
  source/_includes/site/sidebar.html
  source/_integrations/foscam.markdown
  source/_integrations/generic.markdown
  source/_posts/2016-02-20-community-highlights.markdown
  source/_posts/2017-10-14-templating-date-time.markdown
  source/_redirects
  source/examples/index.markdown
Labels: cla-signed, current

#17398 Fix typo in logger example YAML
  source/_integrations/logger.markdown
Labels: cla-signed, current

#17399 Update slack.markdown
  source/_integrations/slack.markdown
Labels: cla-signed, current

#17412 Add supported model to Panasonic Viera
  source/_integrations/panasonic_viera.markdown
Labels: cla-signed, current

#17413 API URL Updated
  source/_integrations/startca.markdown
Labels: cla-signed, current

#17405 Update epsonworkforce.markdown
  source/_integrations/epsonworkforce.markdown
Labels: cla-signed, current

#17361 Improve Google Cast documentation
  source/_includes/integrations/option_flow.md
  source/_integrations/cast.markdown
Labels: cla-signed, current, in-progress

#17109 Add Rituals Perfume Genie sensor platform
  source/_integrations/rituals_perfume_genie.markdown
Labels: awaits-parent, cla-signed, has-parent, new-integration, next

#17388 Move additional automation reading in getting started
  source/getting-started/automation.markdown
Labels: cla-signed, current

#17417 Remove note about admin account
  source/_integrations/analytics.markdown
Labels: cla-signed, current

#17418 Add unit to timeout in Telegram Bot docs
  source/_integrations/telegram_bot.markdown
Labels: cla-signed, current

#17402 Updates for live db migration and recovery
  source/_integrations/recorder.markdown
Labels: cla-signed, has-parent, new-feature, next

#17400 Fix NetworkManager config for veth interfaces
  source/more-info/unsupported/network_manager.markdown
Labels: cla-signed, current

#17406 Update telegram_bot.markdown
  source/_integrations/telegram_bot.markdown
Labels: cla-signed, current

#17404 Add note that media_source media must be natively supported
  source/_integrations/media_source.markdown
Labels: cla-signed, current

#15718 Add iAlarm integration
  source/_integrations/ialarm.markdown
  source/images/supported_brands/antifurto365-ialarm.png
Labels: cla-signed, has-parent, in-progress, new-integration, next, parent-merged

#17422 Round integration usage percentage to 1 decimal
  source/_includes/asides/component_navigation.html
Labels: cla-signed, current

#17123 Update Litter-Robot documentation to reflect new feature support
  source/_integrations/litterrobot.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17426 minor typo correction
  source/_integrations/nest.markdown
Labels: cla-signed, current

#17430 Add LTT + Troy to frontpage
  .gitignore
  sass/custom/_paulus.scss
  source/images/press/ltt.svg
  source/images/press/troyhunt.jpg
  source/images/press/wired.com.svg
  source/index.html
Labels: cla-signed, current

#17290 Improvements to Hue documentation
  source/_integrations/hue.markdown
Labels: cla-signed, current

#17312 Supervisor source modification
  source/more-info/unsupported/source_mods.markdown
Labels: awaits-parent, cla-signed, current

#17429 Clarification to what the Entities card actions are linked
  source/_lovelace/entities.markdown
Labels: cla-signed, current

#17433 Tweak mqtt_eventstream ignore_event documentation
  source/_integrations/mqtt_eventstream.markdown
Labels: cla-signed, current

#16139 Add ecobee humidifier
  source/_integrations/ecobee.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17438 Remove unsupported KL430
  source/_integrations/tplink.markdown
Labels: cla-signed, current

#17439 Remove blueprint_exchange_data.json
  source/_data/blueprint_exchange_data.json
Labels: cla-signed, current

#17444 Document the new ZHA `custom_quirks_path` option
  source/_integrations/zha.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17447 Fix Dockerfile for devcontainer
  .devcontainer/devcontainer.json
  Dockerfile
Labels: cla-signed, current, in-progress

#17456 Update modbus.markdown
  source/_integrations/modbus.markdown
Labels: cla-signed, current, in-progress, needs-rebase

#17293 Add Hive boost off
  source/_integrations/hive.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, parent-merged

#17460 Add clarity about manual add-on alternative
  source/addons/index.html
Labels: cla-signed, current

#17449 Add documentation for amcrest events
  source/_integrations/amcrest.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#17461 Add binary sensor to Rituals Perfume Genie
  source/_integrations/rituals_perfume_genie.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, next, parent-merged

#17401 Update proxmoxve documentation with port and user instructions
  source/_integrations/proxmoxve.markdown
Labels: cla-signed, current

#17471 add missing description
  source/_integrations/fan.template.markdown
Labels: cla-needed, current

#17340 Added address info for modbus.binary_sensor
  source/_integrations/modbus.markdown
Labels: cla-signed, current, in-progress

#17423 update swiss_hydrological_data docs
  source/_integrations/swiss_hydrological_data.markdown
Labels: awaits-parent, cla-signed, has-parent, next

#17473 Clarifying how attributes are set
  source/_integrations/sql.markdown
Labels: cla-signed, current

#17469 Update `regex_search` and `regex_match` to new tests
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17477 Fix reference to Raspberry Pi, while it might be something else
  source/_includes/installation/core.md
Labels: cla-signed, current

#17475 Remove confusing port mentions from Alexa docs
  source/_integrations/alexa.smart_home.markdown
Labels: cla-signed, current

#17476 Add paid notice to Risco cloud page
  source/_integrations/risco.markdown
Labels: cla-signed, current

#17478 Small tweak to input_boolean docs
  source/_integrations/input_boolean.markdown
Labels: cla-signed, current

#17480 Add climacell to additional categories
  source/_integrations/climacell.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17482 Tweaks to Media Source documentation
  source/_integrations/media_source.markdown
Labels: cla-signed, current

#17464 Small wording tweaks to NUT documentation
  source/_integrations/nut.markdown
Labels: cla-signed, current

#17440 Add note about region code
  source/_integrations/analytics.markdown
Labels: awaits-parent, cla-signed, current, has-parent, in-progress

#17483 Make the IoT class linkable instead of using an (i) icon
  source/_includes/asides/component_navigation.html
Labels: cla-signed, current

#17467 Add link from using blueprint to creating blueprint
  source/_docs/automation/using_blueprints.markdown
Labels: cla-signed, current

#17481 Deprecate GNTP (Growl) integration
  source/_integrations/gntp.markdown
Labels: cla-signed, has-parent, next

#17485 Remove header rule
  source/_headers
Labels: cla-signed, current

#17484 Fetch stable version of HAOS on build
  .gitignore
  Rakefile
  _config.yml
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#17486 ✨ The 17th community highlight!
  source/_posts/2021-04-16-community-highlights.markdown
  source/images/blog/2021-04-16-community-highlights/battery.png
  source/images/blog/2021-04-16-community-highlights/social.png
Labels: blog, cla-signed, current

#17494 Update note about Z-Wave deprecation
  source/_docs/z-wave/control-panel.markdown
  source/_integrations/zwave.markdown
Labels: cla-signed, current

#17495 Small title adjustment in VLC
  source/_integrations/vlc.markdown
Labels: cla-signed, current

#17493 Extend examples on Shell Command documentation
  source/_integrations/shell_command.markdown
Labels: cla-signed, current

#17019 Add documentation about device tracker platform for Mazda integration
  source/_integrations/mazda.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17500 Fixed typo
  source/_integrations/tado.markdown
Labels: cla-signed, current

#17507 Add restart note to Legrand Home+ Control docs
  source/_integrations/home_plus_control.markdown
Labels: cla-signed, current

#17508 Clarify polling rate is calculated for UK Transport
  source/_integrations/uk_transport.markdown
Labels: cla-signed, current

#17506 Clarify stream documentation
  source/_integrations/stream.markdown
Labels: cla-signed, current

#17492 Add new services to the profiler
  source/_integrations/profiler.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17521 Fix the current version on the front page
  _config.yml
Labels: cla-signed, current

#17457 Update zha.markdown with ZHA remove service example
  source/_integrations/zha.markdown
Labels: cla-signed, current, in-progress

#17530 Update GitHub issue form
  .github/ISSUE_TEMPLATE/feedback.yml
Labels: cla-signed, current

#17531 Remove outdated note in system monitor docs
  source/_integrations/systemmonitor.markdown
Labels: cla-signed, current

#17533 Update air_quality docs
  source/_integrations/air_quality.markdown
Labels: cla-signed, current, in-progress

#16363 Don't refer to deprecated Hyperion effect names
  source/_integrations/hyperion.markdown
Labels: cla-signed, has-parent, in-progress, next, parent-merged

#17535 Clarify cast known_hosts does not require mDNS routing
  source/_integrations/cast.markdown
Labels: cla-signed, current
