Repository home-assistant/home-assistant.io, pull requests merged in 2021-12, with the labels that each got.

#20526 Clarify Plex needs login as administrator
  source/_integrations/plex.markdown
Labels: cla-signed, current

#20325 Add Tailscale integration
  source/_integrations/tailscale.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#20538 Add Lines to supported devices
  source/_integrations/nanoleaf.markdown
Labels: cla-signed, current

#20535 Change Nanoleaf IoT class to Local Push
  source/_integrations/nanoleaf.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20518 Add button device classes to MQTT
  source/_integrations/button.mqtt.markdown
Labels: new-feature, cla-signed, has-parent, parent-merged

#20519 Add button device classes
  source/_integrations/button.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20546 Add support for Christmas Tree pickup to TwenteMilieu
  source/_integrations/twentemilieu.markdown
Labels: new-feature, cla-signed, has-parent, parent-merged

#20439 Document MQTT lock.open
  source/_integrations/lock.mqtt.markdown
Labels: cla-signed, in-progress, current, has-parent, parent-merged

#20543 Statistics additional binary characteristics
  source/_integrations/statistics.markdown
  source/images/screenshots/stats-sensor.png
Labels: cla-signed, next, has-parent, parent-merged

#20066 Update SimpliSafe docs for new service structure
  source/_integrations/simplisafe.markdown
Labels: Hacktoberfest, new-feature, cla-signed, in-progress, next, has-parent, parent-merged, hacktoberfest-accepted

#20077 Fix documentation for sensor card limits
  source/_lovelace/sensor.markdown
Labels: Hacktoberfest, cla-signed, next, has-parent, hacktoberfest-accepted

#20551 Revert "Add template int filter / function documentation"
  source/_docs/configuration/templating.markdown
Labels: cla-signed, next, cleanup

#20552 Revert "Add `bytes` support to bitwise template filters"
  source/_docs/configuration/templating.markdown
Labels: cla-signed, next, cleanup

#20382 Change markdown to accommodate config_flow setup
  source/_integrations/trafikverket_weatherstation.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#20553 Add screenshot of button device classes
  source/_integrations/button.markdown
  source/images/screenshots/button_classes_icons.png
Labels: cla-signed, next, has-parent

#20522 MQTT availability_template documentation
  source/_docs/mqtt/discovery.markdown
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20547 New template filters pack and unpack
  source/_docs/configuration/templating.markdown
Labels: new-feature, cla-signed, current, has-parent, parent-merged

#20527 Clarify strings need quotes in Neurio energy
  source/_integrations/neurio_energy.markdown
Labels: cla-signed, current

#20556 Adjust supervisor references
  source/_faq/addon_not_starting.markdown
  source/_includes/common-tasks/backups.md
  source/_includes/common-tasks/beta_version.md
  source/_includes/common-tasks/data_disk.md
  source/_includes/common-tasks/file_access.md
  source/_includes/common-tasks/third-party-addons.md
  source/_includes/common-tasks/update.md
  source/_integrations/firmata.markdown
  source/_integrations/zha.markdown
  source/_integrations/zwave.markdown
  source/_integrations/zwave_js.markdown
  source/addons/index.html
  source/getting-started/configuration.markdown
  source/images/addons/addon-store.png
  source/images/hassio/screenshots/adding_repositories.png
  source/images/hassio/screenshots/dashboard.png
  source/images/hassio/screenshots/main_panel_addon_store.png
  source/more-info/dockerhub-rate-limit.markdown
  source/more-info/free-space.markdown
  source/more-info/local-media/add-media.markdown
  source/more-info/unhealthy/setup.markdown
  source/more-info/unhealthy/supervisor.markdown
  source/more-info/unsupported/docker_configuration.markdown
  source/more-info/unsupported/docker_version.markdown
  source/more-info/unsupported/privileged.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#20555 Describe new Sonos switches and sensor
  source/_integrations/sonos.markdown
Labels: new-feature, cla-signed, next, has-parent

#20548 add icon_template to command_line switch documentation
  source/_integrations/switch.command_line.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#19635 Privacy mode for amcrest cameras (second try)
  source/_integrations/amcrest.markdown
Labels: Hacktoberfest, new-feature, cla-signed, next, has-parent, parent-merged, hacktoberfest-accepted

#20557 Add Siren to ZHA docs
  source/_integrations/zha.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20380 Add documentation for Nest Battery Camera Clip Previews and media source
  source/_integrations/nest.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase

#20563 Fronius is configurable form UI
  source/_posts/2021-12-11-release-202112.markdown
Labels: cla-signed, cherry-picked, in-progress, has-parent, needs-rebase, rc

#20574 Add missing option `entry_id` to `homeassistant.reload_config_entry`
  source/_integrations/homeassistant.markdown
Labels: cla-signed, current

#20570 BMW ConnectedDrive: Update vehicle finder description.
  source/_integrations/bmw_connected_drive.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20576 Add linked_humidity_sensor to HomeKit docs
  source/_integrations/homekit.markdown
Labels: cla-signed, current

#19472 Added documentation for nina
  source/_integrations/nina.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#20585 Update flux_led to include list of unsupported/supported models
  source/_integrations/flux_led.markdown
Labels: cla-signed, current

#20593 Roon: fix ghost in documentation
  source/_integrations/roon.markdown
Labels: cla-signed, current

#20572 Add breaking change note for Hue integration
  source/_posts/2021-12-11-release-202112.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#20602 Docker container moved to new maintainer
  source/_integrations/deconz.markdown
Labels: cla-signed, current

#20607 Remove loopenergy docs
  CODEOWNERS
  source/_integrations/loopenergy.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged

#20240 Add Elmax integration documentation.
  source/_integrations/elmax.markdown
Labels: new-integration, cla-signed, awaits-parent, in-progress, next, has-parent

#20617 Update nest instructions with community feedback
  source/_integrations/nest.markdown
Labels: cla-signed, current

#20446 Add Troubleshooting for known issue to ffmpeg_noise
  source/_integrations/ffmpeg_noise.markdown
Labels: cla-signed, in-progress, current

#20614 Add back simple `redirect_uri_mismatch` instructions
  source/_integrations/nest.markdown
Labels: cla-signed, in-progress, next, has-parent

#20616 Clarify integration is for Gen 3
  source/_integrations/tesla_wall_connector.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#20613 Update flux_led naming
  source/_integrations/flux_led.markdown
Labels: new-feature, cla-signed, next, has-parent

#20620 Change Integrations to Devices & Services
  source/_integrations/aemet.markdown
  source/_integrations/asuswrt.markdown
  source/_integrations/bmw_connected_drive.markdown
  source/_integrations/control4.markdown
  source/_integrations/dexcom.markdown
  source/_integrations/dlna_dmr.markdown
  source/_integrations/dsmr.markdown
  source/_integrations/eafm.md
  source/_integrations/ecobee.markdown
  source/_integrations/flume.markdown
  source/_integrations/freebox.markdown
  source/_integrations/harmony.markdown
  source/_integrations/homekit.markdown
  source/_integrations/huawei_lte.markdown
  source/_integrations/keenetic_ndms2.markdown
  source/_integrations/konnected.markdown
  source/_integrations/meteo_france.markdown
  source/_integrations/mysensors.markdown
  source/_integrations/nest.markdown
  source/_integrations/netatmo.markdown
  source/_integrations/plex.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/ruckus_unleashed.markdown
  source/_integrations/screenlogic.markdown
  source/_integrations/sentry.markdown
  source/_integrations/somfy_mylink.markdown
  source/_integrations/subaru.markdown
  source/_integrations/xiaomi_aqara.markdown
  source/_integrations/zha.markdown
  source/_integrations/zwave.markdown
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next

#20606 Update alarm_control_panel.mqtt.markdown
  source/_integrations/alarm_control_panel.mqtt.markdown
Labels: cla-signed, current

#20623 Update panasonic_viera.markdown
  source/_integrations/panasonic_viera.markdown
Labels: cla-signed, current

#20621 Fix example on MQTT button page
  source/_integrations/button.mqtt.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#20625 Include Category Energy
  source/_integrations/tesla_wall_connector.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#20630 Update dexcom.markdown
  source/_integrations/dexcom.markdown
Labels: cla-signed, current

#20626 Button list updated
  source/_integrations/webostv.markdown
Labels: cla-signed, current

#20573 Add Ohmpilot and energy dashboard recommendations to Fronius
  source/_integrations/fronius.markdown
Labels: cla-signed, next, has-parent, parent-merged

#20568 Add setup note to Xiaomi Miio integration page
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#20642 Remove outdated Ecowitt reference from Ambient PWS docs
  source/_integrations/ambient_station.markdown
Labels: cla-signed, current

#20639 Fixing typo
  source/_integrations/switchbot.markdown
Labels: cla-signed, current

#20609 rfxtrx: Documenation update
  source/_integrations/rfxtrx.markdown
Labels: cla-signed, current

#20643 Fix broken link
  source/_integrations/enocean.markdown
Labels: cla-signed, current

#20644 Improve input_number example
  source/_integrations/input_number.markdown
Labels: cla-signed, current

#19933 Update unit_of_measurement description
  source/_integrations/template.markdown
Labels: Hacktoberfest, cla-signed, in-progress, current, has-parent, hacktoberfest-accepted

#20646 Add media_player platform to lookin
  source/_integrations/lookin.markdown
Labels: cla-signed, next, has-parent

#20650 fix blog post typo
  source/_posts/2021-12-11-release-202112.markdown
Labels: cla-signed, cherry-picked, in-progress, needs-rebase, rc

#20648 Update ecobee.markdown
  source/_integrations/ecobee.markdown
Labels: cla-signed, current

#20679 List Siren under support device types in ZHA docs
  source/_integrations/zha.markdown
Labels: cla-signed, next, has-parent

#20678 Remove machine spesific image refrences
  _config.yml
  source/_includes/common-tasks/beta_version.md
  source/_includes/common-tasks/development_version.md
  source/_includes/common-tasks/specific_version.md
  source/_includes/common-tasks/update.md
  source/_includes/installation/container.md
  source/_includes/installation/container/alternative.md
  source/_includes/installation/container/cli.md
  source/_includes/installation/container/compose.md
  source/_integrations/dsmr.markdown
  source/more-info/local-media/setup-media.markdown
Labels: cla-signed, current

#20680 Fix my link to add-on store
  source/_includes/common-tasks/file_access.md
Labels: cla-signed, current

#20666 2021.12 release notes: Add breaking changes in the statistics component
  source/_posts/2021-12-11-release-202112.markdown
Labels: cla-signed, in-progress, current

#20659 Fix mqtt button entity full example
  source/_integrations/button.mqtt.markdown
Labels: cla-signed, current

#20672 Update tuya.markdown
  source/_integrations/tuya.markdown
Labels: cla-signed, current

#19150 Clarify command_line runtime environment
  source/_integrations/command_line.markdown
  source/_integrations/sensor.command_line.markdown
  source/_integrations/shell_command.markdown
Labels: cla-signed, in-progress, current, smash

#20696 Expand explanation of the "AppArmor issues" solution
  source/more-info/unsupported/apparmor.markdown
Labels: cla-signed, current

#20690 Remove deprecated YAML configuration from Luftdaten
  source/_integrations/luftdaten.markdown
Labels: cla-signed, next, has-parent, cleanup

#20656 Updating and simplifying nest integration documentation structure
  source/_integrations/nest.markdown
Labels: cla-signed, in-progress, current

#20708 Extend VirtualBox installation guide
  source/_includes/installation/operating_system.md
Labels: cla-signed, current, installation

#20710 Remove deprecated server configuration instruction
  source/_integrations/jellyfin.markdown
Labels: cla-signed, current

#20718 Update statistics.markdown
  source/_integrations/statistics.markdown
Labels: cla-signed, current

#20712 Fix typo
  source/more-info/local-media/setup-media.markdown
Labels: cla-signed, current

#20734 Improve readability pack and unpack template examples
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#20723 Fault in example
  source/_integrations/media_player.markdown
Labels: cla-signed, in-progress, current

#20707 [improve][tuya] Add a tip that resolves an edge case
  source/_integrations/tuya.markdown
Labels: cla-signed, in-progress, current

#20378 Update zwave_js documentation for support
  source/_docs/z-wave/controllers.markdown
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#20744 Fixing examples with templates
  source/_integrations/utility_meter.markdown
Labels: cla-signed, current

#20739 Fix timestamp_custom example
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#20752 Add iOS blog post
  source/_posts/2021-12-18-ios-multi-server.markdown
  source/images/blog/2021-12-ios/social.png
Labels: cla-signed, current

#20575 Add pico remote support to non-pro lutron caseta bridges
  source/_integrations/lutron_caseta.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20738 Update supported flux_led models
  source/_integrations/flux_led.markdown
Labels: cla-signed, current

#20765 Update flux_led for reboot button
  source/_integrations/flux_led.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20726 Add config flow to Azure_event_hub integration documentation
  source/_integrations/azure_event_hub.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#20703 Update tibber.markdown
  source/_integrations/tibber.markdown
Labels: cla-signed, next, has-parent, parent-merged

#20478 Add Open-Meteo integration
  source/_integrations/open_meteo.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#20080 Add events and device triggers to LCN
  source/_integrations/lcn.markdown
Labels: Hacktoberfest, cla-signed, next, has-parent, parent-merged, hacktoberfest-accepted

#20766 Stick to Sonoff common used spelling
  source/_integrations/zha.markdown
Labels: cla-signed, current

#20753 Device is polled, not pushed
  source/_integrations/izone.markdown
Labels: cla-signed, awaits-parent, in-progress, next, has-parent

#20584 Add set_zones service to flux_led
  source/_integrations/flux_led.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20772 Update nest documentation for nest permissions
  source/_integrations/nest.markdown
Labels: cla-signed, current, has-parent

#20774 Add blog post for Android 2021.12 release
  source/_posts/2021-12-21-android-december-2021-release.markdown
  source/images/blog/2021-12-21-android-december-2021/Companion.png
  source/images/blog/2021-12-21-android-december-2021/instant_updates.gif
  source/images/blog/2021-12-21-android-december-2021/media_player.png
  source/images/blog/2021-12-21-android-december-2021/phone_wear.png
  source/images/blog/2021-12-21-android-december-2021/wear.jpg
  source/images/blog/2021-12-21-android-december-2021/wear_home.png
  source/images/blog/2021-12-21-android-december-2021/wear_tile.png
  source/images/blog/2021-12-21-android-december-2021/welcome.png
Labels: cla-signed, blog, current

#20781 Add play store badge for easy access
  source/_posts/2021-12-21-android-december-2021-release.markdown
Labels: cla-signed, current

#20783 Replace youtube URL with one that works embedded
  source/_posts/2021-12-21-android-december-2021-release.markdown
Labels: cla-signed, current

#20786 Update known supported vendors for flux_led
  source/_integrations/flux_led.markdown
Labels: cla-signed, next

#20776 2021.12.4
  _config.yml
  source/_posts/2021-12-11-release-202112.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#20791 Update number.mqtt.markdown
  source/_integrations/number.mqtt.markdown
Labels: cla-signed, current

#20755 Add select platform to Magic Home/flux_led
  source/_integrations/flux_led.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20793 Correct template example
  source/_integrations/template.markdown
Labels: cla-signed, current

#20788 Remove stale nest documentation
  source/_integrations/nest.markdown
Labels: cla-signed, current

#20069 Add documenation for slugify template filter
  source/_docs/configuration/templating.markdown
Labels: Hacktoberfest, new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged, hacktoberfest-accepted

#20790 Update nest webrtc docs to recommend picture glance cards
  source/_integrations/nest.markdown
Labels: cla-signed, current

#20778 ZHA USB discovery of SONOFF Zigbee 3.0 USB Dongle
  source/_integrations/zha.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#20784 Add flux_led.set_music_mode service
  source/_integrations/flux_led.markdown
Labels: new-feature, cla-signed, next, has-parent

#20789 Restructure nest documentation troubleshooting
  source/_integrations/nest.markdown
Labels: cla-signed, current

#20794 Document short hand templates in condition actions
  source/_docs/scripts/conditions.markdown
Labels: new-feature, cla-signed, next, has-parent

#20795 Deprecate mcp23017 integration (ADR-0019)
  source/_integrations/mcp23017.markdown
Labels: cla-signed, next, has-parent, parent-merged

#20797 Deprecate pcal9535a integration (ADR-0019)
  source/_integrations/pcal9535a.markdown
Labels: cla-signed, next, has-parent

#20801 Update zha.markdown best practices section title
  source/_integrations/zha.markdown
Labels: cla-signed, current

#20805 Add location of configuration.yaml for Home Assistant Operating System.
  source/_docs/configuration.markdown
Labels: cla-signed, current

#20804 Deprecate Sensirion SHT31 integration (ADR-0019)
  source/_integrations/sht31.markdown
Labels: cla-signed, next, has-parent

#20803 Deprecate DHT Sensor integration (ADR-0019)
  source/_integrations/dht.markdown
Labels: cla-signed, next, has-parent

#20802 Deprecate BH1750 integration (ADR-0019)
  source/_integrations/bh1750.markdown
Labels: cla-signed, next, has-parent

#20799 Deprecate pi4ioe5v9xxxx integration (ADR-0019)
  source/_integrations/pi4ioe5v9xxxx.markdown
Labels: cla-signed, next, has-parent

#20800 Deprecate BeagleBone Black GPIO integration (ADR-0019)
  source/_integrations/bbb_gpio.markdown
Labels: cla-signed, next, has-parent

#20815 Add genie blog
  source/_posts/2021-12-21-stanford-genie.markdown
  source/images/blog/2021-12-stanford-genie/social.png
Labels: cla-signed, current

#20769 Add iif (immediate if) template function/filter
  source/_docs/configuration/templating.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#20807 Fix link to template sensors
  source/_integrations/vesync.markdown
Labels: cla-signed, current

#20816 Device Triggers UI visitbility note added
  source/_integrations/homekit.markdown
Labels: cla-signed, current

#20822 correct spelling attribut -> attribute
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#20743 Create area.markdown
  source/_lovelace/area.markdown
Labels: cla-signed, in-progress, current

#20554 Update Sensibo for config_flow
  source/_integrations/sensibo.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20824 Update breaking changes for Hue
  source/_posts/2021-12-11-release-202112.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#20725 Fritz deprecate services for button entities
  source/_integrations/fritz.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#20835 Document MWh as supported energy unit
  source/_integrations/sensor.markdown
Labels: cla-signed, current

#20836 Document apparent and reactive power sensor device classes
  source/_integrations/sensor.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20813 Update AsusWRT documentation
  source/_integrations/asuswrt.markdown
Labels: cla-signed, current

#20668 Update octoprint.markdown
  source/_integrations/octoprint.markdown
Labels: cla-signed, current

#20817 Update information on obtaining the password for enphase envoy units
  source/_integrations/enphase_envoy.markdown
Labels: cla-signed, current

#20823 Remove TaHoma documentation
  .textlintrc.json
  CODEOWNERS
  source/_integrations/somfy.markdown
  source/_integrations/tahoma.markdown
  source/_redirects
Labels: cla-signed, in-progress, next, has-parent, cleanup

#20839 Add 2021.12.1 changelog link
  source/_posts/2021-12-21-android-december-2021-release.markdown
Labels: cla-signed, blog, current

#20840 Group integrations better
  plugins/filters.rb
Labels: cla-signed, current

#20842 Fix typo in nest documentation
  source/_integrations/nest.markdown
Labels: cla-signed, current

#20847 Make it clear when a connect bridge is required for august
  source/_integrations/august.markdown
Labels: cla-signed, current

#20848 Fix formatting on august lock table
  source/_integrations/august.markdown
Labels: cla-signed, current

#20845 Add Button platform to ZHA docs
  source/_integrations/zha.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20850 Add blog post open home
  source/_posts/2021-12-23-the-open-home.markdown
  source/images/blog/2021-12-open-home/header.png
  source/images/blog/2021-12-open-home/social.png
Labels: cla-signed, current

#20264 Generic thermostats presets
  source/_integrations/generic_thermostat.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#18935 Add config flow instructions to version integration
  source/_integrations/version.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#20841 Add Overkiz documentation for new integration
  .textlintrc.json
  source/_integrations/overkiz.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#20843 Update tado docs; added default for float in example
  source/_integrations/tado.markdown
Labels: cla-signed, current

#20869 Update DenonAVR Markdown with additional model
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#20859 Remove zwave_js device automation information
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#20886 Add default frame rate
  source/_integrations/generic.markdown
Labels: cla-signed, current

#20837 Add configuration flow to PVOutput
  source/_integrations/pvoutput.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20894 Fix typo in nest documentation ("Nest" -> "Next")
  source/_integrations/nest.markdown
Labels: cla-signed, current

#20890 Add Scene platform and category to current Overkiz docs
  source/_integrations/overkiz.markdown
Labels: new-feature, cla-signed, awaits-parent, current, has-parent

#20892 Extract attribute into sensor for PVOutput
  source/_integrations/pvoutput.markdown
Labels: new-feature, cla-signed, next, has-parent, cleanup

#20905 Add binary sensor entity to Overkiz documentation
  source/_integrations/overkiz.markdown
Labels: cla-signed, next, has-parent

#20880 Add light platform to current Overkiz documentation
  source/_integrations/overkiz.markdown
Labels: new-feature, cla-signed, next, has-parent

#20908 FRITZ: Fix service parameter typo
  source/_integrations/fritz.markdown
Labels: cla-signed, current
