Repository home-assistant/home-assistant.io, pull requests merged in 2021-03, with the labels that each got.

#16783 Neato improve troubleshooting section
  source/_integrations/neato.markdown
Labels: cla-signed, current

#16780 Grant permissions with groups
  source/_integrations/proxmoxve.markdown
Labels: cla-signed, current

#16790 Remove griddy integration
  source/_integrations/griddy.markdown
  source/_redirects
Labels: cla-signed, cleanup, has-parent, in-progress, next

#16733 Clarify template trigger behaviour
  source/_docs/automation/trigger.markdown
Labels: cla-signed, has-parent, next, parent-merged

#16802 Fixing incorrect code sample
  source/_lovelace/entities.markdown
Labels: cla-needed, current

#16795 Correct supported features for MQTT light basic schema
  source/_integrations/light.mqtt.markdown
Labels: cla-signed, current

#16796 Update Z-Wave JS limitations for next release
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next

#16804 deleted no longer valid note
  source/_integrations/mikrotik.markdown
Labels: cla-signed, current

#16806 My plugin updates
  .textlintrc.json
  plugins/my.rb
  sass/custom/_paulus.scss
  source/_docs/automation/services.markdown
  source/_docs/automation/templating.markdown
  source/_docs/automation/using_blueprints.markdown
  source/_includes/asides/component_navigation.html
  source/_includes/common-tasks/snapshots.md
  source/_includes/integrations/config_flow.md
Labels: cla-signed, in-progress, needs-rebase, next

#16810 Reflect current restrictions on 64-bit Raspberry Pi images
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#16801 Document logging default log severity level
  source/_integrations/logger.markdown
Labels: cla-signed, current

#16800 Fix grammar issues
  source/_integrations/alexa.intent.markdown
Labels: cla-signed, current, in-progress

#16811 Move Pi-Hole API key instructions
  source/_integrations/pi_hole.markdown
Labels: cla-signed, current

#16809 Enquote username/password in evohome example
  source/_integrations/evohome.markdown
Labels: cla-signed, current

#16808 Remove YAML optionals from Sighthound config example
  source/_integrations/sighthound.markdown
Labels: cla-signed, current, in-progress

#16813 Add missing Switch device classes
  source/_docs/configuration/customizing-devices.markdown
  source/_integrations/switch.markdown
Labels: cla-signed, current

#16816 Add more My links
  source/_docs/authentication/multi-factor-auth.markdown
  source/_docs/authentication/providers.markdown
  source/_docs/automation/basics.markdown
  source/_docs/automation/editor.markdown
  source/_docs/automation/troubleshooting.markdown
  source/_docs/automation/yaml.markdown
  source/_docs/blueprint/tutorial.markdown
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/devices.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/templating.markdown
  source/_integrations/xbox.markdown
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next

#16817 Collection of Markdown/YAML cleanups
  source/_docs/authentication/multi-factor-auth.markdown
  source/_docs/automation/action.markdown
  source/_docs/automation/basics.markdown
  source/_docs/automation/condition.markdown
  source/_docs/automation/templating.markdown
  source/_docs/automation/trigger.markdown
  source/_docs/automation/yaml.markdown
  source/_docs/blueprint/schema.markdown
  source/_docs/blueprint/tutorial.markdown
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/devices.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/configuration/platform_options.markdown
  source/_docs/configuration/remote.markdown
  source/_docs/configuration/secrets.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/configuration/yaml.markdown
Labels: cla-signed, next

#16815 Update example zwave_js_event value notification event to include new keys
  source/_integrations/zwave_js.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16819 Update turn_on_light_for_10_minutes_when_motion_detected.markdown
  source/_cookbook/turn_on_light_for_10_minutes_when_motion_detected.markdown
Labels: cla-signed, current

#16807 Add list of commands
  source/_integrations/philips_js.markdown
Labels: cla-signed, has-parent, next, parent-merged

#16798 Add zwave_js release notes summary
  source/_posts/2021-02-03-release-20213.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#16823 Add airflow min-max service description
  source/_integrations/izone.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next

#16015 Updates to the Google Assistant setup instructions
  source/_integrations/google_assistant.markdown
Labels: cla-needed, current

#16331 Add missing obihai breaking change
  source/_posts/2021-02-03-release-20212.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#16827 Revert Flux LED config flow changes
  source/_integrations/flux_led.markdown
Labels: cla-signed, current

#16781 Update documentation for the light integration
  source/_integrations/light.markdown
Labels: cla-signed, current

#16767 Improve nest troubleshooting and clarify steps based on latest feedback
  source/_integrations/nest.markdown
  source/images/integrations/nest/oauth_consent_production_status.png
Labels: cla-signed, current

#16834 Add note to climacell docs about v3 vs v4
  source/_integrations/climacell.markdown
Labels: cla-signed, current

#16836 Update 2021-03-03-release-20213.markdown
  source/_posts/2021-03-03-release-20213.markdown
Labels: cla-signed, current

#16666 📝 Remove logo of Open Exchange Rates
  source/_integrations/openexchangerates.markdown
Labels: awaits-parent, cla-signed, cleanup, current, has-parent

#16828 Update device-specific.markdown
  source/_docs/z-wave/device-specific.markdown
Labels: cla-signed, current

#16832 Tweaks for Entity Filter card
  source/_lovelace/entity-filter.markdown
Labels: cla-signed, current

#16841 Add more info to GitHub integration
  source/_integrations/github.markdown
Labels: cla-signed, current

#16837 Blog post for the android releases in 2021 Q1
  source/_posts/2021-03-06-android-2021-q1-releases.markdown
  source/images/blog/2021-03-06-android-q1-releases/3_finger_swipe_gesture.gif
  source/images/blog/2021-03-06-android-q1-releases/Companion.png
  source/images/blog/2021-03-06-android-q1-releases/high_accuracy.png
  source/images/blog/2021-03-06-android-q1-releases/location_disabled.png
Labels: blog, cla-signed, current

#16866 2021-3 Z-Wave JS version fixed
  source/_posts/2021-03-03-release-20213.markdown
Labels: cla-signed, current

#16872 Add installation type in the title of common tasks
  source/common-tasks/container.markdown
  source/common-tasks/core.markdown
  source/common-tasks/os.markdown
  source/common-tasks/supervised.markdown
Labels: cla-signed, current

#16873 Update mycroft.markdown
  source/_integrations/mycroft.markdown
Labels: cla-needed, current

#16875 Tweaks to HomeKit documentation
  source/_integrations/homekit.markdown
Labels: cla-signed, current

#16881 Fix Z-Wave JS server minimum version in 2021.3.0 release notes
  source/_posts/2021-03-03-release-20213.markdown
Labels: cla-signed, current

#16883 Fix a missing end quote.
  source/_docs/scripts.markdown
Labels: cla-signed, current

#16867 Home Assistant Server
  source/_integrations/asterisk_mbox.markdown
  source/_integrations/cloudflare.markdown
  source/_integrations/debugpy.markdown
  source/_integrations/dialogflow.markdown
  source/_integrations/fail2ban.markdown
  source/_integrations/geniushub.markdown
  source/_integrations/geofency.markdown
  source/_integrations/homematic.markdown
  source/_integrations/ifttt.markdown
  source/_integrations/locative.md
  source/_integrations/otp.markdown
  source/_integrations/sonos.markdown
  source/_integrations/wink.markdown
  source/_posts/2020-07-01-release-112.markdown
  source/_posts/2020-08-28-android-230-release.markdown
  source/_posts/2020-09-12-android-240-release.markdown
  source/_posts/2020-09-17-release-115.markdown
  source/_posts/2020-11-06-android-300-release.markdown
Labels: cla-signed, current

#16882 Change default homekit ports to 21063 and 21064
  source/_integrations/homekit.markdown
Labels: cla-signed, has-parent, next, parent-merged

#16864 Fix category on Wolf SmartSet
  source/_integrations/wolflink.markdown
Labels: cla-signed, current

#16901 Add update information to cert_expiry docs
  source/_integrations/cert_expiry.markdown
Labels: cla-signed, current

#16902 Remove broken link from ASUSWRT
  source/_integrations/asuswrt.markdown
Labels: cla-signed, current

#16913 Just a missing space ;)
  source/_integrations/demo.markdown
Labels: cla-signed, current

#16916 Add Text-to-speech category to cloud
  source/_integrations/cloud.markdown
Labels: cla-signed, current

#16911 DOC: add note to make sure skill account is same account as the one used to login on alexa devices
  source/_integrations/alexa.smart_home.markdown
Labels: cla-signed, current

#16919 grammar
  source/_integrations/zha.markdown
Labels: cla-signed, current

#16929 Lock GitHub Action runner due FFI compability issue
  .github/workflows/test.yml
Labels: cla-signed, current

#16926 Minor script tweaks
  source/_integrations/script.markdown
Labels: cla-signed, current

#16829 Update index.html
  source/installation/index.html
Labels: cla-signed, current

#16953 Docs for Hangouts integration: Chrome no longer seems to show oauth_code cookie
  source/_integrations/hangouts.markdown
Labels: cla-signed, current

#16956 Update philips_js.markdown
  source/_integrations/philips_js.markdown
Labels: cla-signed, current

#16955 Correct operation modes
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#16942 Update configuration.markdown
  source/_docs/configuration.markdown
Labels: cla-signed, current

#16934 Update philips_js.markdown
  source/_integrations/philips_js.markdown
Labels: cla-signed, current

#16968 Tweak input_datetime documentation
  source/_integrations/input_datetime.markdown
Labels: cla-signed, current

#16963 Update template fan to provide guidance on how to convert from speeds
  source/_integrations/fan.template.markdown
Labels: cla-signed, current

#16961 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#16971 ✨ 12th Community highlights blog!
  source/_posts/2021-03-12-community-highlights.markdown
  source/images/blog/2021-03-12-community-highlights/blueprint.png
  source/images/blog/2021-03-12-community-highlights/feeder.jpg
  source/images/blog/2021-03-12-community-highlights/social.png
  source/images/blog/2021-03-12-community-highlights/workstation.png
Labels: blog, cla-signed, current

#16973 Update sonos_say.markdown
  source/_cookbook/sonos_say.markdown
Labels: cla-signed, current

#16985 Correct default value for hub in modbus.
  source/_integrations/binary_sensor.modbus.markdown
  source/_integrations/modbus.markdown
  source/_integrations/sensor.modbus.markdown
Labels: cla-signed, current

#16979 Update to modbus page
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#16994 Add missing link to update
  source/_posts/2021-03-03-release-20213.markdown
Labels: cla-signed, current

#17006 Some fixes for service-call docu
  source/_docs/scripts/service-calls.markdown
Labels: cla-signed, current

#16874 Deprecate HomeKit auto start
  source/_integrations/homekit.markdown
Labels: cla-signed, cleanup, has-parent, next, parent-merged

#16865 Add icon reference to Lovelace documentation
  source/lovelace/badges.markdown
  source/lovelace/dashboards-and-views.markdown
  source/lovelace/header-footer.markdown
Labels: cla-signed, current

#16869 Add unique ID to weather template
  source/_integrations/weather.template.markdown
Labels: cla-signed, current

#16870 Add note about tested hardware in NAD documentation
  source/_integrations/nad.markdown
Labels: cla-signed, current

#17012 Lowercase MDI icons URLs
  source/_docs/configuration/customizing-devices.markdown
  source/lovelace/badges.markdown
  source/lovelace/dashboards-and-views.markdown
  source/lovelace/header-footer.markdown
Labels: cla-signed, current

#16776 [Xiaomi Miio] Add example for vacuum segment clean with repetition
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current, in-progress

#16991 generic camera : example of secured access
  source/_integrations/generic.markdown
Labels: cla-signed, current

#16684 remove KNX config_file
  source/_integrations/knx.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next, parent-merged

#16096 Add weather support to Tado integration
  source/_integrations/tado.markdown
Labels: awaits-parent, has-parent, in-progress, new-feature, next, parent-merged

#16717 Add Xiaomi Miio sensor config flow
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#15377 Adding Panasonic Viera remote documentation
  source/_integrations/panasonic_viera.markdown
Labels: Hacktoberfest, cla-signed, hacktoberfest-accepted, has-parent, new-feature, next, parent-merged

#16782 Add Xiaomi Miio Light config flow
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16619 Add subdevice lightbulb support
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16377 Add apply_filter to recorder.purge service
  source/_integrations/recorder.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16972 added another choose example
  source/_docs/scripts.markdown
Labels: cla-signed, current, in-progress

#16568 Hive UI Docs update
  source/_integrations/hive.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16617 Add gateway switch support
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#17007 Tweaks to the blueprint selectors
  source/_docs/blueprint/selectors.markdown
Labels: cla-signed, current

#16990 corrected parameter in Service `opentherm_gw.set_hot_water_setpoint`
  source/_integrations/opentherm_gw.markdown
Labels: cla-signed, current

#16933 added missing instructions
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#17014 Remove duplicate configuration instruction from Panasonic Viera
  source/_integrations/panasonic_viera.markdown
Labels: cla-signed, next

#16946 Update WOL Documentation For Bugfix
  source/_integrations/wake_on_lan.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17003 Update documentation MQTT suggested_area
  source/_docs/mqtt/discovery.markdown
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/tag.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17015 Add report model to Yeelight documentation
  source/_integrations/yeelight.markdown
Labels: cla-signed, current

#17013 Update verisure documentation for 2fa bug
  source/_integrations/verisure.markdown
Labels: cla-signed, current, has-parent, in-progress

#17000 Add config flow to Verisure
  source/_integrations/verisure.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17021 Small fix
  source/_docs/locked_out.md
Labels: cla-signed, current

#17023 Update output of help
  source/_includes/common-tasks/commandline.md
Labels: cla-signed, current

#17025 Wrap service call docs template example value in quotes
  source/_docs/scripts/service-calls.markdown
Labels: cla-signed, current

#17027 Update automation.markdown
  source/_docs/automation.markdown
Labels: cla-signed, current

#17032 Remove confusing line from History docs
  source/_integrations/history.markdown
Labels: cla-signed, current

#17010 Add screenlogic integration documentation
  source/_integrations/screenlogic.markdown
Labels: awaits-parent, cla-signed, has-parent, new-integration, next

#17043 Removed repeated word
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#16033 Amcrest add documentation for CrossLineDetected
  source/_integrations/amcrest.markdown
Labels: awaits-parent, has-parent, new-feature, next

#17026 Url option
  source/_integrations/prowl.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16910 Update using_blueprints.markdown
  source/_docs/automation/using_blueprints.markdown
Labels: cla-signed, current, in-progress

#17057 ✨ 13th Community highlights blog!
  source/_posts/2021-03-19-community-highlights.markdown
  source/images/blog/2021-03-19-community-highlights/social.png
Labels: blog, cla-signed, current

#17060 Update documentation for the OpenWeatherMap integration
  source/_integrations/openweathermap.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17064 add clarification that Spotify URI Redirect is case sensitive
  source/_integrations/spotify.markdown
Labels: cla-signed, current

#17039 Add details about unavailable and unknown states for Prometheus
  source/_integrations/prometheus.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16976 Add homeassistant.reload_config_entry service
  source/_integrations/homeassistant.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#13943 Add notification with images example
  source/_integrations/matrix.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next, parent-merged

#16442 Add join/unjoin documentation for media_player
  source/_integrations/media_player.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17070 Update zwave_js.markdown
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#17078 ProxmoxVE Change realm to username instead of password
  source/_integrations/proxmoxve.markdown
Labels: cla-signed, current

#17088 Fix YAML indent in example
  source/_integrations/influxdb.markdown
Labels: cla-signed, current

#17074 Update august to be cloud push
  source/_integrations/august.markdown
Labels: cla-signed, has-parent, next, parent-merged

#16962 Update systemmonitor.markdown
  source/_integrations/systemmonitor.markdown
Labels: cla-signed, current, in-progress

#17005 Update enable_i2c.md
  source/_includes/common-tasks/enable_i2c.md
Labels: cla-signed, current, in-progress

#16909 Update editor.markdown
  source/_docs/automation/editor.markdown
Labels: cla-signed, current, in-progress

#17041 Updated sensor documentation to be more approachable to new users.
  source/_integrations/sensor.markdown
Labels: cla-signed, current

#17024 Update calendar.google.markdown
  source/_integrations/calendar.google.markdown
Labels: cla-signed, current

#17083 Add information about CoIoT and unicast to Shelly integration docs
  source/_integrations/shelly.markdown
Labels: cla-signed, current

#16344 Add documentation for Hyperion effect hide option
  source/_integrations/hyperion.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16495 Update zha.markdown
  source/_integrations/zha.markdown
Labels: cla-signed, current

#17081 Update homekit for activity based remotes
  source/_integrations/homekit.markdown
Labels: cla-signed, has-parent, next, parent-merged

#17073 Update screenlogic from water_heater to climate
  source/_integrations/screenlogic.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17018 Remove unneeded consideration section from weather template
  source/_integrations/weather.template.markdown
Labels: cla-signed, current

#17100 Add section to warning about WiFi-based Zigbee-to-Serial bridges so it has a direct URL link
  source/_integrations/zha.markdown
Labels: cla-signed, current

#16182 I found that a 4pm or other non midnight required buffering.
  source/_integrations/history_stats.markdown
Labels: cla-signed, current, in-progress

#17075 KNX yaml style and sensor value types
  source/_integrations/knx.markdown
Labels: cla-signed, current

#17108 Fix error in mystrom documentation
  source/_integrations/mystrom.markdown
Labels: cla-signed, current

#17118 Clarify details of sensor created by websocket_api
  source/_integrations/sensor.websocket_api.markdown
  source/_integrations/websocket_api.markdown
  source/_redirects
Labels: cla-signed, current, in-progress

#17122 Add multiple actions example to switch template
  source/_integrations/switch.template.markdown
Labels: cla-signed, current

#17111 Clarify how to reboot Roomba to generate auto-discovery
  source/_integrations/roomba.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase

#15780 Add new protocol key descr for graphite
  source/_integrations/graphite.markdown
Labels: awaits-parent, has-parent, new-feature, next

#17115 Update python_script.markdown, help new users find "services"
  source/_integrations/python_script.markdown
Labels: cla-signed, current, in-progress

#17132 Small example code improvements to deCONZ
  source/_integrations/deconz.markdown
Labels: cla-signed, current

#17133 Update index.markdown
  source/lovelace/index.markdown
Labels: cla-signed, current

#16771 Add opportunity to define token for each message
  source/_integrations/notify_events.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#17140 ✨ 14th Community highlights blog!
  source/_posts/2021-03-26-community-highlights.markdown
  source/images/blog/2021-03-26-community-highlights/social.png
  source/images/blog/2021-03-26-community-highlights/uptime-card.png
Labels: blog, cla-signed, current

#17147 Update conditions.markdown
  source/_docs/scripts/conditions.markdown
Labels: cla-signed, current

#17130 Make clear that dlib platform are only available on Core
  source/_integrations/dlib_face_detect.markdown
  source/_integrations/dlib_face_identify.markdown
Labels: cla-signed, current

#17106 Add explaination for 'unkown' sensor
  source/_integrations/statistics.markdown
Labels: cla-signed, current

#17131 Raspberry Pi Camera availability notice
  source/_integrations/rpi_camera.markdown
Labels: cla-signed, current

#17048 Support preset modes and percentage for mqtt fan
  source/_docs/mqtt/discovery.markdown
  source/_integrations/fan.mqtt.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase, parent-merged

#16948 Added docs for new attributes
  source/_integrations/weather.template.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16678 Update modbus configuration to use new
  source/_integrations/binary_sensor.modbus.markdown
  source/_integrations/climate.modbus.markdown
  source/_integrations/cover.modbus.markdown
  source/_integrations/modbus.markdown
  source/_integrations/sensor.modbus.markdown
  source/_integrations/switch.modbus.markdown
  source/_redirects
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#16947 New services for managing lock codes on ZHA Zigbee locks
  source/_integrations/zha.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next, parent-merged

#16440 Updated econet.markdown for climate updates
  source/_integrations/econet.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#17095 Improve Docker and Kubernetes support for KNX
  source/_integrations/knx.markdown
Labels: cla-signed, current, has-parent, in-progress, needs-rebase, parent-merged

#17149 Highlight that an ARM version is not available.
  source/_integrations/facebox.markdown
Labels: current, in-progress

#16644 Add Legrand Home+ Control Integration document
  source/_integrations/home_plus_control.markdown
Labels: cla-signed, has-parent, in-progress, new-integration, next, parent-merged
