Repository home-assistant/home-assistant.io, pull requests merged in 2021-01, with the labels that each got.

#16060 Clarify note on enabling remote features setting on Xbox
  source/_integrations/xbox.markdown
Labels: current

#16059 Added avr type
  source/_integrations/denonavr.markdown
Labels: current

#16069 Remove deprecated PTVSD integration
  source/_integrations/ptvsd.markdown
  source/_posts/2019-05-16-release-93.markdown
  source/_posts/2019-10-30-release-101.markdown
  source/_posts/2020-07-01-release-112.markdown
  source/_posts/2020-11-18-release-118.markdown
  source/_redirects
Labels: awaits-parent, cleanup, has-parent, next

#16071 Update device-specific.markdown
  source/_docs/z-wave/device-specific.markdown
Labels: current, in-progress

#16066 Fix I2C links on MCP23017 integration page
  source/_integrations/mcp23017.markdown
Labels: current

#16065 Fix missing logo for SRP Energy
  source/_integrations/srp_energy.markdown
Labels: current

#16064 Improve Weather Underground warning
  source/_integrations/wunderground.markdown
Labels: current

#16063 Fix Evohome example in documentation
  source/_integrations/evohome.markdown
Labels: current

#16051 Update velux.markdown
  source/_integrations/velux.markdown
Labels: current

#16075 Update velux.markdown
  source/_integrations/velux.markdown
Labels: current

#16076 Add Binary Sensor to Tado integration
  source/_integrations/tado.markdown
Labels: has-parent, new-feature, next, parent-merged

#16085 Update panasonic_viera.markdown with TX-L47ET60E Model
  source/_integrations/panasonic_viera.markdown
Labels: current

#16088 Confirm Hikvision DS-2CD2385G1 works well
  source/_integrations/hikvision.markdown
Labels: current

#16091 Updated workday.markdown to fix example 2 duplicate
  source/_integrations/workday.markdown
Labels: current

#16079 Update KNX for xknx 0.16.0
  source/_integrations/knx.markdown
Labels: has-parent, new-feature, next

#16086 Fix alexa_confirm.yaml example
  source/_integrations/alexa.intent.markdown
Labels: current

#16020 Add docs for Sure Petcare set_lock_state service
  source/_integrations/surepetcare.markdown
Labels: has-parent, in-progress, new-feature, next, parent-merged

#16084 Add description of venetian blind tilt control configuration
  source/_integrations/rfxtrx.markdown
Labels: has-parent, new-feature, next, parent-merged

#16082 Update broadlink.markdown
  source/_integrations/broadlink.markdown
Labels: current

#16080 Update tplink.markdown
  source/_integrations/tplink.markdown
Labels: current

#16078 repair pin instructions include 're-toggle'
  source/_integrations/braviatv.markdown
Labels: current

#16067 Integration search filter improvements
  source/integrations/index.html
Labels: current

#16098 Update list "Support by third-party tools"
  source/_docs/mqtt/discovery.markdown
Labels: current

#16103 Add docs for RainMachine entity services
  source/_integrations/rainmachine.markdown
Labels: has-parent, new-feature, next

#16107 Update calendar.google.markdown
  source/_integrations/calendar.google.markdown
Labels: current

#16055 Add ondilo_ico documentation
  source/_integrations/ondilo_ico.markdown
Labels: awaits-parent, has-parent, new-integration, next, parent-merged

#16026 ViCare: set_vicare_mode service
  source/_integrations/vicare.markdown
Labels: awaits-parent, has-parent, next, parent-merged

#16110 Update spotify.markdown
  source/_integrations/spotify.markdown
Labels: current

#16101 Tweak ping device_tracker docs
  source/_integrations/ping.markdown
Labels: current

#16111 Update brother.markdown
  source/_integrations/brother.markdown
  source/images/integrations/brother/brother-printer-webui.png
Labels: current, in-progress

#16116 Update gpslogger F-Droid URL
  source/_integrations/gpslogger.markdown
Labels: current

#16125 Change white/blacklist in recorder, history, Pushbullet and Watson IOT docs
  source/_integrations/history.markdown
  source/_integrations/pushbullet.markdown
  source/_integrations/recorder.markdown
  source/_integrations/watson_iot.markdown
Labels: current

#16126 Entities card: Tweaks, buttons screenshot + attribute example
  source/_lovelace/entities.markdown
  source/images/lovelace/lovelace_entity_row_buttons.jpg
Labels: current, in-progress

#16124 Update sensor.rflink.markdown
  source/_integrations/sensor.rflink.markdown
Labels: current

#16123 Delete 'reset_after' reference for KNX switches
  source/_integrations/knx.markdown
Labels: current

#16121 Update aquostv.markdown with Sharp LC-70LE747
  source/_integrations/aquostv.markdown
Labels: current

#16118 use correct attribute for valve position
  source/_integrations/homematic.markdown
Labels: current

#16117 Remove Server-sent events in http.markdown
  source/_integrations/http.markdown
Labels: current, has-parent

#16130 Format blueprint descriptions with markdown
  source/_docs/blueprint/schema.markdown
Labels: has-parent, new-feature, next

#16137 Update Home Assistant OS to 5.10
  source/hassio/installation.markdown
Labels: current

#16140 Update spotify.markdown
  source/_integrations/spotify.markdown
Labels: current

#16144 Change example to use expand as a function
  source/_docs/configuration/templating.markdown
Labels: current

#16143 Made the user exemptions for action confirmation a bit clearer
  source/lovelace/actions.markdown
Labels: current

#16138 Fix two spelling mistakes and minor grammar optimizations
  source/_integrations/xbox.markdown
Labels: current

#16142 Update unifi with advanced configuration details and presence detection defaults
  source/_integrations/unifi.markdown
Labels: current

#16141 Recommend using Python ADB approach for Android TV setup
  source/_integrations/androidtv.markdown
Labels: current

#16146 Add requirement for setting DEBUG when testing Alexa Smart Home
  source/_integrations/alexa.smart_home.markdown
Labels: current

#16120 Add landingpage for removed integrations
  source/_redirects
  source/more-info/removed-integration.markdown
Labels: current

#16155 Clarify introduction of panel_custom.
  source/_integrations/panel_custom.markdown
Labels: current

#16133 Update somfy_mylink to be a config_flow
  source/_integrations/somfy_mylink.markdown
Labels: has-parent, new-feature, next, parent-merged

#16153 Daikin: Add region changing note
  source/_integrations/daikin.markdown
Labels: current

#16151 Daikin: Add supported US controller info
  source/_integrations/daikin.markdown
Labels: current

#16147 Add docs for Z-Wave JS integration
  source/_integrations/zwave_js.markdown
Labels: has-parent, new-integration, next, parent-merged

#16149 Remove safe_mode from homekit
  source/_integrations/homekit.markdown
Labels: awaits-parent, cleanup, has-parent, next

#16154 Remove documentation for august yaml configuration
  source/_integrations/august.markdown
Labels: awaits-parent, cleanup, has-parent, next

#16162 New `input_datetime` default/initial value
  source/_integrations/input_datetime.markdown
Labels: has-parent, next

#16160 Add switch platform to Z-Wave JS docs
  source/_integrations/zwave_js.markdown
Labels: has-parent, new-feature, next

#16165 Hikvision component also works with other NVRs
  source/_integrations/hikvision.markdown
Labels: current

#16166 update fritz integration docs
  source/_integrations/fritz.markdown
Labels: current

#16157 Add Portuguese (pt) to the list
  source/_integrations/meteoalarm.markdown
Labels: current

#16167 Remove panasonic_viera from legacy discovery
  source/_integrations/discovery.markdown
Labels: cleanup, current

#16043 Clarify nest device trigger documentation
  source/_integrations/nest.markdown
  source/images/integrations/nest/device_triggers.png
Labels: current

#16171 Update numeric_state trigger documentation
  source/_docs/automation/trigger.markdown
Labels: has-parent, next

#15815 Update transmission.markdown
  source/_integrations/transmission.markdown
Labels: awaits-parent, has-parent, new-feature, next

#16164 Update Sonos->Plex service description
  source/_integrations/plex.markdown
Labels: awaits-parent, has-parent, next

#16176 Mention ISO 8601 for "timestamp" device_class
  source/_integrations/sensor.markdown
Labels: current

#16172 Add DHCP Discovery
  source/_integrations/dhcp.markdown
Labels: cla-signed, has-parent, new-integration, next, parent-merged

#16180 Remove command line sensor hddtemp example
  source/_integrations/sensor.command_line.markdown
Labels: cla-signed, current

#16188 Slightly refine wording in variables description
  source/_docs/scripts.markdown
Labels: cla-signed, current

#16189 Add binary_sensor to zwave_js docs
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, next

#16185 Update Tasmota documentation
  source/_integrations/tasmota.markdown
Labels: cla-signed, has-parent, in-progress, needs-rebase, next, parent-merged

#15035 Foscam config flow and stream option
  source/_integrations/foscam.markdown
Labels: Hacktoberfest, hacktoberfest-accepted, has-parent, new-feature, next

#16183 Remove YAML support from harmony.
  source/_integrations/harmony.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16184 Clarify state trigger functionality
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current, in-progress

#15852 Shelly RGB devices are now fully supported
  source/_integrations/shelly.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16178 total_download should say total_upload
  source/_integrations/startca.markdown
Labels: cla-signed, current

#16174 Small tweaks to header/footer for cards
  source/lovelace/header-footer.markdown
Labels: cla-signed, current

#16161 Add doc on home-assistant plugin
  source/_integrations/doods.markdown
Labels: cla-needed, current, in-progress

#16131 Add an nest event example automation
  source/_integrations/nest.markdown
Labels: current, in-progress

#16158 Document MQTT availability_mode
  source/_integrations/alarm_control_panel.mqtt.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16196 Add odroid-n2
  source/_integrations/version.markdown
Labels: current

#16195 Clarify auth provider text
  source/_docs/authentication/providers.markdown
Labels: cla-signed, current

#16192 Add zwave_js lock support to docs
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, next

#16197 Fix switcher_kis max timer value
  source/_integrations/switcher_kis.markdown
Labels: has-parent, new-feature, next, parent-merged

#16199 Add alert banner
  sass/custom/_layout.scss
  sass/oscailte/base/_navigation.scss
  source/_layouts/default.html
Labels: cla-signed, current

#16073 Update enable_i2c.markdown
  source/hassio/enable_i2c.markdown
Labels: cla-signed, current, in-progress

#16201 Mention Python 3.7 in bulletin
  source/_posts/2021-01-14-security-bulletin.markdown
Labels: cla-signed, current

#16203 Change NextTracks F-Droid information
  source/_integrations/owntracks.markdown
Labels: cla-signed, current

#16210 Document MQTT availability_mode for all components
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: cla-signed, in-progress, needs-rebase, new-feature, next

#16211 Add remark about limited featureset on varying MPD implementations
  source/_integrations/mpd.markdown
Labels: cla-signed, current, in-progress

#16208 📝 Remove logo of QVR Pro
  source/_integrations/qvr_pro.markdown
Labels: cla-signed, current, has-parent

#16207 📝 Remove logo of RaspyRFM
  source/_integrations/raspyrfm.markdown
Labels: cla-signed, current, has-parent

#16204 📝 Remove logo of Serial Particulate Matter
  source/_integrations/serial_pm.markdown
Labels: cla-signed, cleanup, current, has-parent

#16205 📝 Remove logo of SCSGate
  source/_integrations/scsgate.markdown
Labels: awaits-parent, cla-signed, cleanup, current, has-parent

#16115 Add MQTT Number
  source/_integrations/number.mqtt.markdown
Labels: cla-signed, has-parent, next, parent-merged

#16212 📝 Remove logo of PJLink
  source/_integrations/pjlink.markdown
Labels: awaits-parent, cla-signed, current, has-parent

#16213 Update roon play media
  source/_integrations/roon.markdown
Labels: cla-signed, has-parent, in-progress, new-feature, next, parent-merged

#16218 Add note about default action override
  source/lovelace/actions.markdown
Labels: cla-signed, current

#16219 Adjust `entities` special row example
  source/_lovelace/entities.markdown
  source/images/lovelace/lovelace_entity_row_special.jpg
Labels: cla-signed, current, in-progress

#16193 add zwave_js climate support to docs
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16217 Fix command and change to script format
  source/_integrations/cast.markdown
Labels: cla-signed, current

#16216 Remove references to YAML in nut
  source/_integrations/nut.markdown
Labels: awaits-parent, has-parent, new-feature, next

#16220 Update egardia.markdown
  source/_integrations/egardia.markdown
Labels: cla-signed, current

#16247 Remove references to YAML in myq
  source/_integrations/myq.markdown
Labels: cla-signed, cleanup, has-parent, next

#16255 Default for the Number Selector is slider, not box
  source/_docs/blueprint/selectors.markdown
Labels: cla-needed, current

#16246 Remove ads logo in favor of brands
  source/_integrations/ads.markdown
Labels: cla-signed, current, has-parent

#16238 Add custom services to dyson documentation
  source/_integrations/dyson.markdown
Labels: cla-signed, has-parent, new-feature, next, parent-merged

#16242 Format values as code blocks
  source/_integrations/fan.template.markdown
Labels: cla-signed, current

#16240 Removed logo of nuimo_controller in favor of brands.
  source/_integrations/nuimo_controller.markdown
Labels: cla-signed, current, has-parent

#16235 Updated Google Calendar Integration doc to use condition attributes released in 0.115.
  source/_integrations/calendar.google.markdown
Labels: cla-signed, current

#16234 Add link from MQTT discovery to Scenes.mqtt.markdown
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#16233 Add MiHome devices token App for Windows and MACOS
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#16224 Add Discourse forum link to footer
  source/_includes/site/footer.html
Labels: cla-signed, current

#16223 Update xiaomi_miio.markdown
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#16222 Clarified that the examples are for automations
  source/_integrations/signal_messenger.markdown
Labels: cla-signed, current

#16249 Remove YAML support from nexia
  source/_integrations/nexia.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#16248 Remove YAML support from hunterdouglas_powerview
  source/_integrations/hunterdouglas_powerview.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#16261 Entities card: Button row name now optional
  source/_lovelace/entities.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16252 Remove YAML support from rachio
  source/_integrations/rachio.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#16251 Remove YAML support from powerwall
  source/_integrations/powerwall.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#16269 Fix broken link
  source/getting-started/index.markdown
Labels: cla-signed, current

#16272 Adjust name of akasma74 custom integration
  source/_posts/2021-01-21-security-disclosure.markdown
Labels: cla-signed, current

#16273 Add cover to ha_category in zwave-js
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, next

#16215 Update lutron caseta for config flow and one touch pairing
  source/_integrations/lutron_caseta.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16250 Remove YAML support from nuheat
  source/_integrations/nuheat.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#16283 Update knx.markdown
  source/_integrations/knx.markdown
Labels: cla-signed, current

#16284 remove reference to tasmota
  source/_integrations/tag.mqtt.markdown
Labels: cla-signed, current

#16278 Add fan to zwave-js
  source/_integrations/zwave_js.markdown
Labels: cla-signed, has-parent, next, parent-merged

#16281 Lovelace alignments for all cards
  source/_lovelace/alarm-panel.markdown
  source/_lovelace/button.markdown
  source/_lovelace/calendar.markdown
  source/_lovelace/conditional.markdown
  source/_lovelace/entity-filter.markdown
  source/_lovelace/entity.markdown
  source/_lovelace/gauge.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/grid.markdown
  source/_lovelace/history-graph.markdown
  source/_lovelace/horizontal-stack.markdown
  source/_lovelace/humidifier.markdown
  source/_lovelace/iframe.markdown
  source/_lovelace/light.markdown
  source/_lovelace/logbook.markdown
  source/_lovelace/map.markdown
  source/_lovelace/markdown.markdown
  source/_lovelace/media-control.markdown
  source/_lovelace/picture-elements.markdown
  source/_lovelace/picture-entity.markdown
  source/_lovelace/picture-glance.markdown
  source/_lovelace/picture.markdown
  source/_lovelace/plant-status.markdown
  source/_lovelace/sensor.markdown
  source/_lovelace/shopping-list.markdown
  source/_lovelace/thermostat.markdown
  source/_lovelace/vertical-stack.markdown
  source/_lovelace/weather-forecast.markdown
  source/lovelace/badges.markdown
  source/lovelace/dashboards-and-views.markdown
  source/lovelace/header-footer.markdown
Labels: cla-signed, current, in-progress

#16214 Document `buttons` action support for `entities` card
  source/_lovelace/entities.markdown
Labels: cla-signed, current, in-progress

#16097 Note about isoformat() for frontend templates
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#16280 Extended frontend theme info a bit
  source/_integrations/frontend.markdown
Labels: cla-signed, current

#16279 Additional d removed from documentation.
  source/hassio/enable_i2c.markdown
Labels: cla-signed, current

#16286 Add docs for new zwave_js lock services
  source/_integrations/zwave_js.markdown
Labels: awaits-parent, cla-signed, current, has-parent, in-progress, new-feature

#16277 New `format` option for attribute rows
  source/_lovelace/entities.markdown
Labels: cla-signed, has-parent, new-feature, next

#16271 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#16264 Removed sochain logo in favor of brands
  source/_integrations/sochain.markdown
Labels: cla-signed, current, has-parent

#16262 Update controllers.markdown
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, current

#16258 Update solaredge.markdown
  source/_integrations/solaredge.markdown
Labels: cla-signed, current

#16253 Remove YAML support from tado (except device_tracker)
  source/_integrations/tado.markdown
Labels: awaits-parent, cla-signed, cleanup, has-parent, next

#16285 Update picture-entity.markdown
  source/_lovelace/picture-entity.markdown
Labels: cla-signed, current, in-progress

#16263 Update limitations section of Z-Wave JS docs
  source/_integrations/zwave_js.markdown
Labels: cla-signed, in-progress, next

#16302 Update of filename description
  source/_integrations/file.markdown
Labels: cla-signed, current

#16202 update for xknx 0.16.1 - event_register service
  source/_integrations/knx.markdown
Labels: cla-signed, has-parent, new-feature, next

#16294 easier return entity state object of a trigger
  source/_docs/automation/templating.markdown
Labels: cla-signed, current

#16298 Add note about mDNS with KVM bridged networking
  source/hassio/installation.markdown
Labels: cla-signed, current

#16306 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#16289 Add devices to HomematicIP Cloud
  source/_integrations/homematicip_cloud.markdown
Labels: awaits-parent, cla-signed, has-parent, new-feature, next

#16268 Add extra dict possible for send to Chromecast
  source/_integrations/media_player.markdown
Labels: cla-signed, current, in-progress

#16257 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current
