Repository home-assistant/home-assistant.io, pull requests merged in 2022-03, with the labels that each got.

#21850 Add sensor platform to WiZ
  source/_integrations/wiz.markdown
Labels: new-feature, cla-signed, next, has-parent

#21757 Add `Display` and `Auxiliary Heat` switch to dmaker.airfresh.a1/t2017
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21840 Key retrieval for Brel Home app
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, current

#21845 Waze Travel Time - Clarify case sensitivity for zone resolving
  source/_integrations/waze_travel_time.markdown
Labels: cla-signed, current

#21846 Google Travel Time - Use same info for origin/destination sources
  source/_integrations/google_travel_time.markdown
Labels: cla-signed, current

#21842 Document slave sensors.
  source/_integrations/modbus.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21619 dlna_dmr: Document ability to browse and play media
  source/_integrations/dlna_dmr.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21847 Remove deprecated Raspihats integration
  source/_integrations/raspihats.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#21613 Document Powerwall backup reserve sensor
  source/_integrations/powerwall.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21868 Correct default value for precision from 1 to 0
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#21857 Add reset filters buttons for dmaker.airfresh.a1/T2017 to xiaomi_miio
  source/_integrations/xiaomi_miio.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21866 Update modbus.markdown
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#21878 2022.3 Release notes tweaks
  source/_posts/2022-03-02-release-20223.markdown
Labels: cla-signed, blog, current

#21886 Update to HA Domain for Newsletter
  source/_redirects
Labels: cla-signed, current

#21880 Minor tweak of template documentation
  source/_integrations/template.markdown
Labels: cla-signed, current

#21879 Add section for Version entities
  source/_integrations/version.markdown
Labels: cla-signed, current

#21876 Add Sleepiq light documentation
  source/_integrations/sleepiq.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21887 Sleepiq pressure
  source/_integrations/sleepiq.markdown
Labels: new-feature, cla-signed, next, has-parent

#21869 Mention Ecobee developer password 16-character limit
  source/_integrations/ecobee.markdown
Labels: cla-signed, in-progress, current

#21875 Add info about UPnP for Fritz integration
  source/_integrations/fritz.markdown
Labels: cla-signed, current

#21900 Fix radio browser My Button
  source/_posts/2022-03-02-release-20223.markdown
Labels: cla-signed, current

#21904 Update filesize.markdown
  source/_integrations/filesize.markdown
Labels: cla-signed, next, has-parent

#21901 Reflect new nomenclature in base lib python-holidays
  source/_integrations/workday.markdown
Labels: cla-signed, current

#21917 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#21906 Remove rfxtrx signal repeat section
  source/_integrations/rfxtrx.markdown
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#21928 Removed dist-to-zone attribute
  source/_integrations/proximity.markdown
Labels: cla-signed, current

#21929 Document threshold binary sensor device_class option
  source/_integrations/threshold.markdown
Labels: cla-signed, current

#21924 Added blurb to point users time templating
  source/_integrations/time_date.markdown
Labels: cla-signed, current

#21911 Update link
  source/_integrations/time_date.markdown
Labels: cla-signed, current

#21909 Revert "Update filesize.markdown (#21904)"
  source/_integrations/filesize.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#21851 Add config flow to Season
  source/_integrations/season.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21937 Add newsletter signup to block sidebar
  source/_includes/asides/about.html
Labels: cla-signed, current

#21942 Add Marantz NR1711 as supported denonavr device
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#21940 Add Siren to the Z-Wave.Me integration
  source/_integrations/zwave_me.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21893 Update waze_travel_time.markdown
  source/_integrations/waze_travel_time.markdown
Labels: cla-signed, in-progress, current

#21947 Document known issues with reporting battery charge percentage with august locks
  source/_integrations/august.markdown
Labels: cla-signed, current

#21949 Add required fields to config.yaml example
  source/_integrations/mqtt_room.markdown
Labels: cla-signed, current

#21916 Add Kaleidescape integration
  source/_integrations/kaleidescape.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#21968 Update greenwave.markdown
  source/_integrations/greenwave.markdown
Labels: cla-signed, current, has-parent

#21965 Update lirc.markdown
  source/_integrations/lirc.markdown
Labels: cla-signed, current, has-parent

#21933 Updated documentation on DTE bridge
  source/_integrations/dte_energy_bridge.markdown
Labels: cla-signed, in-progress, current

#21950 Add Quick bar option to Customizations reload
  source/_docs/configuration/customizing-devices.markdown
Labels: cla-signed, in-progress, current

#21964 Update neurio_energy.markdown
  source/_integrations/neurio_energy.markdown
Labels: cla-signed, current, has-parent

#21963 Update nx584.markdown
  source/_integrations/nx584.markdown
Labels: cla-signed, current, has-parent

#21962 Fix reversed before and after descriptions in TOD integration
  source/_integrations/tod.markdown
Labels: cla-signed, current

#21894 Document Mazda button entities
  source/_integrations/mazda.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21277 Add documentation for Mazda binary sensors
  source/_integrations/mazda.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21985 Fix link to ContentDirectory spec
  source/_integrations/dlna_dms.markdown
Labels: cla-signed, current

#21975 Adds Tadiran to supported models list
  source/_integrations/gree.markdown
Labels: cla-signed, current

#21982 Sync Magic Home supported table with upstream
  source/_integrations/flux_led.markdown
Labels: cla-signed, current

#21849 Add config flow to Uptime
  source/_integrations/uptime.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21941 Add Sensibo select entity
  source/_integrations/sensibo.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#20763 Add switch platform to Bosch SHC integration.
  source/_integrations/bosch_shc.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21903 Document new Airzone integration
  source/_integrations/airzone.markdown
Labels: new-integration, cla-signed, has-parent, parent-merged

#21957 Add sensor platform for Kaleidescape integration
  source/_integrations/kaleidescape.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21813 Remove deprecated PCAL9535A I/O Expander integration
  CODEOWNERS
  source/_integrations/pcal9535a.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#21822 Remove deprecated PiFace Digital I/O (PFIO) integration
  source/_integrations/rpi_pfio.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#21993 Templating: "search" actually defaults to IgnoreCase false
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#22001 Update fronius.markdown
  source/_integrations/fronius.markdown
Labels: cla-signed, current

#21989 Add sensors to Sensibo
  source/_integrations/sensibo.markdown
Labels: new-feature, cla-signed, next, has-parent

#21995 Add remote platform docs for Kaliedescape integration
  source/_integrations/kaleidescape.markdown
Labels: new-feature, cla-signed, next, has-parent

#21984 Add documention for Mazda switch platform
  source/_integrations/mazda.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21344 Add mqtt notify service and update example page
  source/_docs/mqtt/discovery.markdown
  source/_examples/notify.mqtt.markdown
  source/_integrations/notify.mqtt.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22006 Wordsmithing for Kaleidescape integration
  source/_integrations/kaleidescape.markdown
Labels: cla-signed, next

#21714 Remove deprecated YAML config from bmw_connected_drive
  source/_integrations/bmw_connected_drive.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#22017 Clarify Google Cast play youtube playlist
  source/_integrations/cast.markdown
Labels: cla-signed, current

#21973 Update arest.markdown
  source/_integrations/arest.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21974 Update concord232.markdown
  source/_integrations/concord232.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21978 Update futurenow.markdown
  source/_integrations/futurenow.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21979 Update horizon.markdown
  source/_integrations/horizon.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21980 Update iglo.markdown
  source/_integrations/iglo.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21981 Update obihai.markdown
  source/_integrations/obihai.markdown
Labels: cla-signed, current, has-parent

#21983 Update qld_bushfire.markdown
  source/_integrations/qld_bushfire.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21977 Remove EQ3 Bluetooth Smart Thermostats logo from frontmatter
  source/_integrations/eq3btsmart.markdown
Labels: cla-signed, current, has-parent

#21976 Update enigma2.markdown
  source/_integrations/enigma2.markdown
Labels: cla-signed, awaits-parent, current, has-parent

#21997 Remove deprecated OpenZWave integration
  CODEOWNERS
  source/_integrations/ozw.markdown
  source/_integrations/zwave_js.markdown
  source/_redirects
Labels: cla-signed, awaits-parent, next, has-parent, cleanup

#22020 Content Trust with Home Assistant
  source/_posts/2022-03-14-cas-content-trust.markdown
Labels: cla-signed, blog, current

#22007 Add binary_sensor to Sensibo
  source/_integrations/sensibo.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#21773 Add protocols to RFXtrx doc
  source/_integrations/rfxtrx.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22023 Update mythicbeastsdns.markdown
  source/_integrations/mythicbeastsdns.markdown
Labels: cla-signed, current, has-parent

#22028 2022.3.5
  _config.yml
  source/_posts/2022-03-02-release-20223.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22024 Update lw12wifi.markdown
  source/_integrations/lw12wifi.markdown
Labels: cla-signed, current, has-parent

#22025 Update greeneye_monitor.markdown
  source/_integrations/greeneye_monitor.markdown
Labels: cla-signed, current

#22027 Cleanup documentation for google calendar
  source/_integrations/google.markdown
Labels: cla-signed, in-progress, current

#22031 update location of Entities list : Deleting Automations
  source/_docs/automation/yaml.markdown
Labels: cla-signed, current

#22030 Rename Lovelace Dashboard to just Dashboard
  source/_lovelace/alarm-panel.markdown
  source/_lovelace/area.markdown
  source/_lovelace/button.markdown
  source/_lovelace/calendar.markdown
  source/_lovelace/conditional.markdown
  source/_lovelace/energy.markdown
  source/_lovelace/entities.markdown
  source/_lovelace/entity.markdown
  source/_lovelace/gauge.markdown
  source/_lovelace/glance.markdown
  source/_lovelace/grid.markdown
  source/_lovelace/history-graph.markdown
  source/_lovelace/horizontal-stack.markdown
  source/_lovelace/humidifier.markdown
  source/_lovelace/iframe.markdown
  source/_lovelace/light.markdown
  source/_lovelace/logbook.markdown
  source/_lovelace/map.markdown
  source/_lovelace/markdown.markdown
  source/_lovelace/media-control.markdown
  source/_lovelace/plant-status.markdown
  source/_lovelace/sensor.markdown
  source/_lovelace/shopping-list.markdown
  source/_lovelace/sidebar.markdown
  source/_lovelace/statistics-graph.markdown
  source/_lovelace/thermostat.markdown
  source/_lovelace/vertical-stack.markdown
  source/_lovelace/weather-forecast.markdown
  source/lovelace/actions.markdown
  source/lovelace/badges.markdown
  source/lovelace/cards.markdown
  source/lovelace/changelog.markdown
  source/lovelace/dashboards.markdown
  source/lovelace/header-footer.markdown
  source/lovelace/how-it-works.markdown
  source/lovelace/index.markdown
  source/lovelace/views.markdown
Labels: cla-signed, current

#22026 Add configuration flow to Google Calendar
  source/_integrations/google.markdown
  source/images/integrations/google/device_connected.png
  source/images/integrations/google/enter_code.png
  source/images/integrations/google/link_account.png
  source/images/integrations/google/success.png
Labels: cla-signed, next, has-parent, parent-merged

#22050 Removed external image option
  source/_integrations/pushover.markdown
Labels: cla-signed, current

#22049 Add prerequisition notes
  source/_integrations/home_connect.markdown
Labels: cla-signed, in-progress, current

#22054 Simple fixes on integrations/version documentation
  source/_integrations/version.markdown
Labels: cla-signed, current

#22056 Add note that Magic Home and Surp Life are interchangeable
  source/_integrations/flux_led.markdown
Labels: cla-signed, current

#22058 Document trigger variables
  source/_docs/automation/trigger.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22061 Add config flow for Sun
  source/_integrations/sun.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22060 Add config flow for integration sensor
  source/_integrations/integration.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22065 Clean up of _redirects
  source/_redirects
Labels: cla-signed, current

#22066 Clean up of _redirects
  source/_redirects
Labels: cla-signed, in-progress, next, needs-rebase

#21801 Remove deprecated (old) Z-Wave integration
  CODEOWNERS
  source/_docs/configuration/splitting_configuration.markdown
  source/_integrations/persistent_notification.markdown
  source/_integrations/zwave.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#22068 Add Sonos subwoofer gain note
  source/_integrations/sonos.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, needs-rebase

#22070 Consolidate mysensors pages
  source/_integrations/binary_sensor.mysensors.markdown
  source/_integrations/climate.mysensors.markdown
  source/_integrations/cover.mysensors.markdown
  source/_integrations/device_tracker.mysensors.markdown
  source/_integrations/light.mysensors.markdown
  source/_integrations/mysensors.markdown
  source/_integrations/notify.mysensors.markdown
  source/_integrations/sensor.mysensors.markdown
  source/_integrations/switch.mysensors.markdown
  source/_redirects
Labels: cla-signed, current

#21967 Add note about upcoming price descriptor
  source/_integrations/amberelectric.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21747 Add switch info to Uptimerobot
  source/_integrations/uptimerobot.markdown
Labels: new-feature, cla-signed, awaits-parent, in-progress, next, has-parent, parent-merged

#22073 Sensibo fix example data missing
  source/_integrations/sensibo.markdown
Labels: cla-signed, current

#18538 Update subaru integration documentation
  source/_integrations/subaru.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22080 Update twitter.markdown
  source/_integrations/twitter.markdown
Labels: cla-signed, current

#21943 Remove SmartHab documentation
  CODEOWNERS
  source/_integrations/smarthab.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#22084 Add calendar platform to Twente Milieu
  source/_integrations/twentemilieu.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22075 Tweeks on configuration.yaml category
  source/_docs/configuration.markdown
  source/_docs/configuration/basic.markdown
Labels: cla-signed, current

#22088 Integration integration optional unique_id
  source/_integrations/integration.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#22091 Update geo_location.markdown
  source/_integrations/geo_location.markdown
Labels: cla-signed, current, has-parent

#22093 Update derivative.markdown
  source/_integrations/derivative.markdown
Labels: cla-signed, current, has-parent

#22094 Update limitlessled.markdown
  source/_integrations/limitlessled.markdown
Labels: cla-signed, current, has-parent

#21612 Add documentation for Backup integration
  source/_integrations/backup.markdown
  source/_integrations/default_config.markdown
  source/installation/index.html
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22097 Add redirects for old mysensors platform pages
  source/_redirects
Labels: cla-signed, current

#22069 Add documentation for Switch as X
  source/_integrations/light.switch.markdown
  source/_integrations/switch_as_x.markdown
  source/_redirects
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#22099 Add Cover to the Z-Wave.Me integration
  source/_integrations/zwave_me.markdown
Labels: new-feature, cla-signed, next, has-parent

#22101 Update Redirect for Newsletter
  source/_redirects
Labels: cla-signed, current

#22063 Add config flow for Derivative
  source/_integrations/derivative.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22102 Comment out subscribe form in blog sidebar for now
  source/_includes/asides/about.html
Labels: cla-signed, current

#22090 Remove CPUSpeed logo from frontmatter
  source/_integrations/cpuspeed.markdown
Labels: cla-signed, in-progress, current, has-parent

#22105 Update zone documentation for new state
  source/_integrations/zone.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22107 Improve Tailscale note, to make more clear what it is not.
  source/_integrations/tailscale.markdown
Labels: cla-signed, current

#22110 Update binary sensor group documentation
  source/_integrations/binary_sensor.group.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22053 Update utility_meter documentation for select entity
  source/_integrations/utility_meter.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22071 Add config flow for Threshold
  source/_integrations/threshold.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22115 Add note regarding SamsungTV sources
  source/_integrations/samsungtv.markdown
Labels: cla-signed, current

#22108 Add documentation for Supervisor Update entities
  source/_integrations/hassio.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22086 Add note about switcher needing access to port 20002 UDP
  source/_integrations/switcher_kis.markdown
Labels: cla-signed, in-progress, current

#22114 Revert "Add mqtt notify service and update example page"
  source/_docs/mqtt/discovery.markdown
  source/_examples/notify.mqtt.markdown
  source/_integrations/notify.mqtt.markdown
Labels: cla-signed, next, has-parent

#22112 Add note for H and J models
  source/_integrations/samsungtv.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#21810 [RFLink] fixed links because of re-design of rflink.nl
  source/_integrations/rflink.markdown
Labels: cla-signed, current

#22047 Add text mentioning replacement integration.
  source/_integrations/updater.markdown
Labels: cla-signed, current

#22100 Update Light group documentation for all option
  source/_integrations/light.group.markdown
Labels: new-feature, cla-signed, awaits-parent, in-progress, next, has-parent, parent-merged

#21591 Add documentation for adding server MOTD sensor
  source/_integrations/minecraft_server.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22123 Update binary_sensor.group.markdown
  source/_integrations/binary_sensor.group.markdown
Labels: cla-signed, current

#22124 Update light.group.markdown
  source/_integrations/light.group.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#22130 Clarify MQTT camera documentation
  source/_integrations/camera.mqtt.markdown
Labels: cla-signed, current

#22051 Add info about the new inverter size option
  source/_integrations/forecast_solar.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#20106 Add config flow docs to deluge
  source/_integrations/deluge.markdown
Labels: Hacktoberfest, cla-signed, next, has-parent, hacktoberfest-accepted

#22129 Clarify requirement for ethernet cable
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#22132 Update Grid neutrality gauge to much current version
  source/images/dashboards/energy/grid-neutrality-gauge.png
Labels: cla-signed, in-progress, current, has-parent

#21930 Document for greyscale filter when entity state is off in picture-elements
  source/_dashboards/picture-elements.markdown
Labels: cla-signed, in-progress, current

#22079 Add lock information to wallbox.markdown
  source/_integrations/wallbox.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#22136 Adjust text of grid neutrality card
  source/_dashboards/energy.markdown
Labels: cla-signed, current

#22139 Fix Xiaomi Aqara Lock documentation
  source/_integrations/lock.xiaomi_aqara.markdown
Labels: cla-signed, current

#22137 Update and consolidate group documentation
  source/_integrations/binary_sensor.group.markdown
  source/_integrations/cover.group.markdown
  source/_integrations/fan.group.markdown
  source/_integrations/group.markdown
  source/_integrations/light.group.markdown
  source/_integrations/media_player.group.markdown
  source/_integrations/notify.group.markdown
  source/_redirects
Labels: cla-signed, in-progress, next

#21925 Add description for SleepIQ actuator number entities
  source/_integrations/sleepiq.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22131 Add command support to SamsungTV H/J models
  source/_integrations/samsungtv.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22119 Adjust link to release notes
  source/_includes/common-tasks/update.md
Labels: cla-signed, current

#22118 Add working model to Hikvision
  source/_integrations/hikvision.markdown
Labels: cla-signed, current

#22157 Fix incorrect link for IR codes
  source/_integrations/denonavr.markdown
Labels: cla-signed, current
