Repository home-assistant/home-assistant.io, pull requests merged in 2022-02, with the labels that each got.

#21423 Add zwave_js_notification event example
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#21391 Update fitbit.markdown to clarify secure setup
  source/_integrations/fitbit.markdown
Labels: cla-signed, in-progress, current

#21421 Update nanoleaf.markdown
  source/_integrations/nanoleaf.markdown
Labels: cla-signed, in-progress, current

#21339 Update Hue docs
  source/_integrations/hue.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21254 Add MQTT siren platform
  source/_docs/mqtt/discovery.markdown
  source/_integrations/siren.mqtt.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21427 Replace create-automation image
  source/images/docs/automation-editor/create-automation.png
Labels: cla-signed, current

#21431 Remove the other trailing comma and minor copyedit (mqtt/discovery)
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#21436 Fix merge conflict resolution in flux_led docs
  source/_integrations/flux_led.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#21439 Fix typo in rtsp_to_webrtc.markdown
  source/_integrations/rtsp_to_webrtc.markdown
Labels: cla-signed, current

#21447 Improvements for 22.2 blogpost
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, current

#21452 Add definition for "DnD"
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#21453 Update spotify.markdown
  source/_integrations/spotify.markdown
Labels: cla-signed, current

#21451 Update webostv turn on example - remove broadcast_address
  source/_integrations/webostv.markdown
Labels: cla-signed, current

#21440 Correction to release notes for Mazda integration
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, current

#21456 Add input_button to default config page
  source/_integrations/default_config.markdown
Labels: cla-signed, current

#21459 Template filter `is_defined` missing documentation
  source/_docs/configuration/templating.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#21415 Mqtt fan support unknown state
  source/_integrations/fan.mqtt.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21418 MQTT humidifier support unknown state
  source/_integrations/humidifier.mqtt.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21419 MQTT light support unknown state
  source/_integrations/light.mqtt.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21465 Update `hass` help output
  source/_docs/tools/hass.markdown
Labels: cla-signed, current

#21462 Corrected automation for input button
  source/_integrations/input_button.markdown
Labels: cla-signed, current

#21474 Update devices that support UniFi Protect
  source/_integrations/unifiprotect.markdown
Labels: cla-signed, current

#21189 Document that HomeKit emits an event
  source/_integrations/homekit.markdown
Labels: cla-signed, current

#21466 Update intellifire.markdown
  source/_integrations/intellifire.markdown
Labels: cla-signed, current

#21448 Add uvjustin as primary LL-HLS credit
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, current

#21443 Update webostv with more real-life example of turn on automation
  source/_integrations/webostv.markdown
Labels: cla-signed, current

#21477 Add comment about generic camera feature
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#21479 "Supervisor" should be "Supervised" for installation method
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, current

#21481 Add breaking change about CLI args
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, current

#21485 Adjust wording
  source/_integrations/github.markdown
Labels: cla-signed, next, has-parent

#21490 Clarify output of `ha os datadisk list`
  source/_includes/common-tasks/data_disk.md
Labels: cla-signed, current

#21488 Add link to known issues on integration page
  source/_includes/asides/component_navigation.html
Labels: cla-signed, current

#21473 Remove reference to !secret in Todoist documentation
  source/_integrations/todoist.markdown
Labels: cla-signed, in-progress, current

#21494 WiZ docs
  source/_integrations/wiz.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#21487 Add diagnostics documentation
  source/_integrations/diagnostics.markdown
Labels: cla-signed, current

#21492 Emphasize this issue form is not for reporting bugs
  .github/ISSUE_TEMPLATE/feedback.yml
Labels: cla-signed, current

#21493 Add fixes hint to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed, current

#21484 Update harmony.markdown
  source/_integrations/harmony.markdown
Labels: cla-signed, current

#21495 Remove deprecated GNTP integration
  source/_integrations/gntp.markdown
  source/_redirects
Labels: cla-signed, awaits-parent, next, has-parent, cleanup

#21496 Add comment about SimpliSafe plans
  source/_integrations/simplisafe.markdown
Labels: cla-signed, current

#21500 Fix typo in RTSPtoWebRTC documentation
  source/_integrations/rtsp_to_webrtc.markdown
Labels: cla-signed, current

#21501 Add switch platfrom to WiZ
  source/_integrations/wiz.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21506 Update webhook trigger documentation
  source/_docs/automation/trigger.markdown
Labels: cla-signed, current

#21504 Update universal.markdown
  source/_integrations/universal.markdown
Labels: cla-signed, current

#21505 Removed ambigious numbers in example
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#21455 Add unique ID to InfluxDB sensor
  source/_integrations/influxdb.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21526 Add note about where to find the path to used config path
  source/_docs/configuration.markdown
  source/images/screenshots/panel_config_info.png
Labels: cla-signed, current

#21518 Total Connect: Add Sensor Activities and improve grammar
  source/_integrations/totalconnect.markdown
Labels: cla-signed, current

#21529 Fix iif template example typo
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#21527 HomeMatic support changes blog post
  source/_posts/2022-02-07-improved-homematic-support.markdown
  source/images/blog/2022-02/raspberrymatic-ccu-addon.png
Labels: cla-signed, blog, current

#21532 Configuration location grammar tweaks
  source/_docs/configuration.markdown
Labels: cla-signed, current

#21534 Homematic blog tweaks
  source/_posts/2022-02-07-improved-homematic-support.markdown
Labels: cla-signed, current

#21533 Change WiZ ha_iot_class to Local Push
  source/_integrations/wiz.markdown
Labels: cla-signed, next, has-parent

#21399 Add dhcp discover to elkm1
  source/_integrations/elkm1.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21536 Remove temperature_units from elkm1 yaml
  source/_integrations/elkm1.markdown
Labels: cla-signed, awaits-parent, next, has-parent, cleanup

#21550 Link to camera integration broken
  source/_integrations/rtsp_to_webrtc.markdown
Labels: cla-signed, current

#21594 Typo dangling quote at end of string
  source/_integrations/light.mqtt.markdown
Labels: cla-signed, current

#21582 vacuum: fix service typo
  source/_integrations/vacuum.markdown
Labels: cla-signed, current

#21603 Update Webhallen Stock
  source/blue/index.html
Labels: cla-signed, current

#21604 HA Blue Out Of Stock
  sass/custom/_landingpage.scss
  source/blue/index.html
Labels: cla-signed, current

#21589 Blog post for Android February release
  source/_posts/2022-02-08-android-february.markdown
  source/images/blog/2022-02-android/Companion.png
  source/images/blog/2022-02-android/add_widget.png
  source/images/blog/2022-02-android/changelog.png
  source/images/blog/2022-02-android/sign_in_on_phone.png
  source/images/blog/2022-02-android/template_tile.png
  source/images/blog/2022-02-android/websocket_setting.png
Labels: cla-signed, blog, current

#21578 Remove documentation on disabled zone bypass switch feature
  source/_integrations/envisalink.markdown
Labels: new-feature, cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#21561 Add select platform to roku
  source/_integrations/roku.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21631 Use right state 'unknown' instead of 'unavailable' in Picnic docs
  source/_integrations/picnic.markdown
Labels: cla-signed, current

#21638 Add rtsp_to_webrtc installation video
  source/_integrations/rtsp_to_webrtc.markdown
Labels: cla-signed, current

#20915 Add set_guest_wifi_password description
  source/_integrations/fritz.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21583 Update documentation for MQTT import flow removal
  source/_docs/mqtt/birth_will.markdown
  source/_docs/mqtt/broker.markdown
  source/_docs/mqtt/discovery.markdown
  source/_integrations/mqtt.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21610 Docs for octoprint job buttons
  source/_integrations/octoprint.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#21640 Add version sources
  source/_integrations/version.markdown
Labels: cla-signed, current

#21585 Add occupancy sensor to WiZ
  source/_integrations/wiz.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21645 Update WiZ for effect speed control
  source/_integrations/wiz.markdown
Labels: new-feature, cla-signed, next, has-parent

#21571 More Tibber sensors
  source/_integrations/tibber.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21347 Update docs for refactored ISS integration
  source/_integrations/iss.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#21365 Documentation for the FiveM integration
  source/_integrations/fivem.markdown
Labels: cla-signed, next, has-parent, parent-merged

#20684 Add Z-Wave.Me integration page
  source/_integrations/zwave_me.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#21559 Update docs for zwave_js ping button entity to replace service
  source/_integrations/zwave_js.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21648 Add caveat about stream requirement to generic
  source/_integrations/generic.markdown
Labels: cla-signed, current

#21491 Update google_assistant JavaScript to support local query. Remove onP…
  source/_integrations/google_assistant.markdown
  source/assets/integrations/google_assistant/app.js
Labels: cla-signed, current, has-parent

#21650 Add binary_sensor to Version
  source/_integrations/version.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21662 SSL options incompatible with local fulfillment
  source/_integrations/google_assistant.markdown
Labels: cla-signed, current

#21666 correction to prerequisites
  source/_includes/installation/core.md
Labels: cla-signed, current

#21314 Update SleepIQ with config flow instructions
  source/_integrations/sleepiq.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#21651 Add ent_cat abbreviation to MQTT discovery
  source/_docs/mqtt/discovery.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21617 Update android blog for 2022.2.1 changes
  source/_posts/2022-02-08-android-february.markdown
Labels: cla-signed, blog, in-progress, current, has-parent, needs-rebase

#21528 Add Netgear allow/block switch
  source/_integrations/netgear.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#21677 Rename "air condition" to "air conditioning"
  source/_integrations/bmw_connected_drive.markdown
Labels: cla-signed, current

#21554 Update procedure on HAOS installation on x86_64
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#21671 Update Vallox documentation
  source/_integrations/vallox.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#21658 Improve Twilio example
  source/_integrations/twilio.markdown
Labels: cla-signed, current

#21670 Update gtfs.markdown
  source/_integrations/gtfs.markdown
Labels: cla-signed, in-progress, current

#21672 Add config flow to MJPEG IP Camera
  source/_integrations/mjpeg.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21566 Add nest documentation for publishing events with zone information
  source/_integrations/nest.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#21057 Small updates with extra help - based on reviewing forums
  source/_integrations/netatmo.markdown
Labels: cla-signed, current

#21146 Update electricity-grid.markdown
  source/_docs/energy/electricity-grid.markdown
Labels: cla-signed, cla-error, in-progress, current

#21548 MQTT climate Remove deprecated `send_if_off` config item
  source/_integrations/climate.mqtt.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#21575 Fix rendering of `is_defined` example.
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#21540 Add Retain suggestion to the config topics
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#21695 Improve glossary entry of automations
  source/_data/glossary.yml
Labels: cla-signed, current

#21694 Improve glossary entry of add-ons
  source/_data/glossary.yml
Labels: cla-signed, current

#20065 Add section on keeping blueprints up to date
  source/_docs/automation/using_blueprints.markdown
Labels: Hacktoberfest, cla-signed, in-progress, current, hacktoberfest-accepted

#21602 Update zha.markdown
  source/_integrations/zha.markdown
Labels: cla-signed, current

#21689 step-by-step instructions for Twitter integration
  source/_integrations/twitter.markdown
Labels: cla-signed, current

#21693 Improve glossary entries of device and entity
  source/_data/glossary.yml
Labels: cla-signed, in-progress, current

#21699 Add int8 and uint8.
  source/_integrations/modbus.markdown
Labels: new-feature, awaits-parent, next, has-parent

#21696 Improve glossary entries of domain, integration, platform
  source/_data/glossary.yml
Labels: cla-signed, in-progress, current

#21690 Add docs for Pure Energie integration
  source/_integrations/pure_energie.markdown
Labels: new-integration, cla-signed, awaits-parent, next, has-parent

#21364 Updated SMTP usage description with example email address.
  source/_integrations/smtp.markdown
Labels: cla-signed, current

#21701 Fix heading type for Utility Meter integration
  source/_integrations/utility_meter.markdown
Labels: cla-signed, current

#21307 Make the web notification docs up-to-date & readable
  source/_integrations/html5.markdown
Labels: cla-signed, current

#21549 Accessibility and SEO improvements
  sass/fontawesome/_path.scss
  source/_includes/custom/features.html
  source/_includes/site/header.html
  source/index.html
Labels: cla-signed, current

#20957 Add new battery/discharge sensors to kostal_plenticore solar inverter
  source/_integrations/kostal_plenticore.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21420 MQTT vacuum unknown state
  source/_integrations/vacuum.mqtt.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21414 Mqtt switch support unknown state
  source/_integrations/switch.mqtt.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#21547 MQTT climate preset_mode rework
  source/_integrations/climate.mqtt.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21417 Add siren to Overkiz documentation
  source/_integrations/overkiz.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21628 Add some details to wiz docu
  source/_integrations/wiz.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21304 Vicare heating type
  source/_integrations/vicare.markdown
Labels: cla-signed, next, has-parent

#21707 Remove note about disabled entities
  source/_integrations/github.markdown
Labels: cla-signed, next, has-parent

#21722 Update list compatibility
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#21712 Add Radio Browser integration
  source/_integrations/radio_browser.markdown
Labels: new-integration, cla-signed, awaits-parent, next, has-parent, parent-merged

#21626 Add documentation for Alarm Control Panel
  source/_integrations/alarm_control_panel.markdown
Labels: cla-signed, in-progress, current

#21355 Filter integration optional unique_id
  source/_integrations/filter.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21728 Remove "send location" from bmw_connected_drive
  source/_integrations/bmw_connected_drive.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#21632 Add info for next delivery Picnic sensors
  source/_integrations/picnic.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#20877 Document zwave_js.event automation trigger
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next, has-parent, parent-merged

#20941 Mqtt light cmd template
  source/_docs/mqtt/discovery.markdown
  source/_integrations/light.mqtt.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#21624 Document the new DLNA DMS integration
  source/_integrations/dlna_dms.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase

#21732 Add additional brands to WiZ
  source/_integrations/wiz.markdown
Labels: cla-signed, next

#21731 Spelling fixes: Togo & Pitcairn Islands
  source/developers/cla_sign.html
Labels: cla-signed, current

#21378 Update event documentation
  source/_docs/configuration/events.markdown
Labels: cla-signed, in-progress, current

#21702 Add efr SGM-C4 and InF Mode HowTo
  source/_integrations/edl21.markdown
Labels: cla-signed, current

#21226 Update zha.markdown with "no longer recommend" comments for CC253x
  source/_integrations/zha.markdown
Labels: cla-signed, current

#19476 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: cla-signed, in-progress, current, smash

#21597 Update zha.markdown Zigbee channel recommendation
  source/_integrations/zha.markdown
Labels: cla-signed, current

#20037 Add condition in example
  source/_integrations/feedreader.markdown
Labels: Hacktoberfest, cla-signed, in-progress, current, hacktoberfest-accepted

#21700 Improve advanced filtering documentation for the Plex Integration
  source/_integrations/plex.markdown
Labels: cla-signed, current

#21510 Add Dooya & Brel motor to cover.rflink.markdown
  source/_integrations/cover.rflink.markdown
Labels: cla-signed, in-progress, current

#21738 Add more WiZ brands that have custom modules
  source/_integrations/wiz.markdown
Labels: cla-signed, next

#21739 Add the ICAO 24-bit address to the OpenSky sensor events
  source/_integrations/opensky.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21741 Update RFXtrx logging snippet
  source/_integrations/rfxtrx.markdown
Labels: cla-signed, current

#21742 Deprecate the updater integration
  source/_integrations/default_config.markdown
  source/_integrations/updater.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#21749 Add Twitter and Newsletter
  source/_redirects
Labels: cla-signed, current

#21751 Corrected link to android Mobile Controller App
  source/_integrations/daikin.markdown
Labels: cla-signed, current

#21667 Update MQTT broker documentation
  source/_docs/mqtt/broker.markdown
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#21752 New option for Fritz: enable old discovery method
  source/_integrations/fritz.markdown
Labels: cla-signed, next, has-parent

#21686 Add timer support to tolo integration
  source/_integrations/tolo.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21678 Adjust phone_modem docs for button entity
  source/_integrations/modem_callerid.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#21538 Add documentation for xiaomi_miio's dmaker.airfresh.{a1,t2017} support
  source/_integrations/xiaomi_miio.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21328 Add documentation for the new moehlenhoff_alpha2 integration
  source/_integrations/moehlenhoff_alpha2.markdown
Labels: cla-signed, next, has-parent, parent-merged

#21758 Add humidifier support to zwave_js
  source/_integrations/zwave_js.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged
