Repository home-assistant/home-assistant.io, pull requests merged in 2022-09, with the labels that each got.

#23972 Add device class moisture to sensors
  source/_integrations/sensor.markdown
Labels: cla-signed, next, has-parent

#23974 Update modbus.markdown
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#23980 typo correction
  source/_docs/configuration/events.markdown
Labels: cla-signed, current

#23863 Update documentation for ISS
  source/_integrations/iss.markdown
Labels: cla-signed, next, has-parent, parent-merged

#24018 Update yolink supported production list
  source/_integrations/yolink.markdown
Labels: cla-signed, current

#24021 Update denonavr.markdown with additional Supported Device
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#23998 update Polly docs; add AWS doc links and cleanup
  source/_integrations/amazon_polly.markdown
Labels: cla-signed, current

#23917 adding example for old foscam and similar no-brand
  source/_integrations/mjpeg.markdown
Labels: cla-signed, in-progress, current

#23994 Add BlueMaestro integration
  source/_integrations/bluemaestro.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#24012 Update LED-BLE brands and names
  source/_integrations/led_ble.markdown
Labels: cla-signed, next, has-parent, parent-merged

#24006 Rename BThome to BTHome
  source/_integrations/bthome.markdown
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged

#24011 Add Feasycom FSC-BP119 to the tested bluetooth adapters list
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next

#23985 Update lacrosse_view HA version to 2022.9
  source/_integrations/lacrosse_view.markdown
Labels: cla-signed, next, has-parent

#23948 Update litterrobot documentation for Feeder-Robot switch
  source/_integrations/litterrobot.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23743 Refactor volvooncall to use ConfigFlow
  source/_integrations/volvooncall.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#24020 Add MFA warning to SimpliSafe docs
  source/_integrations/simplisafe.markdown
Labels: cla-signed, current

#23984 Add lifx.set_hev_cycle_state documentation
  source/_integrations/lifx.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#24000 Add sensor platform to Melnor Bluetooth docs
  source/_integrations/melnor.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#17915 Add Nobø Ecohub integration
  CODEOWNERS
  source/_integrations/nobo_hub.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#24008 Document default_config loading hardware
  source/_integrations/default_config.markdown
Labels: cla-signed, next, has-parent

#23966 Fix details block in Bravia TV
  source/_integrations/braviatv.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#24023 Update Bluetooth links since documentation has moved
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next

#24022 Updated text to match UI
  source/getting-started/automation.markdown
Labels: cla-needed, current

#24004 Fixed spelling mistake in alexa.smart_home.markdown
  source/_integrations/alexa.smart_home.markdown
Labels: cla-signed, current

#24009 Document the hardware integration
  source/_integrations/hardware.markdown
Labels: cla-signed, current

#24026 Update Release Notes main content
  source/_posts/2022-09-07-release-20229.markdown
  source/images/blog/2022-09/automation_editor_new.png
  source/images/blog/2022-09/automation_overflow.png
  source/images/blog/2022-09/automation_state_selector.gif
  source/images/blog/2022-09/create_schedule.gif
  source/images/blog/2022-09/hardware_page.png
  source/images/blog/2022-09/zigbee.png
  source/images/blog/2022-09/zwave_updates.png
Labels: cla-signed, in-progress, needs-rebase, rc

#23967 Add docs for tilt_ble integration
  source/_integrations/tilt_ble.markdown
Labels: new-integration, cla-signed, next, has-parent

#24031 Fix ha_release for bluemaestro
  source/_integrations/bluemaestro.markdown
Labels: cla-signed, next, has-parent

#24030 Comments and Intro
  source/_posts/2022-09-07-release-20229.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#24032 Tweak bluetooth release notes
  source/_posts/2022-09-07-release-20229.markdown
Labels: cla-signed, rc

#24039 Fix typo
  source/_posts/2022-09-07-release-20229.markdown
Labels: cla-signed, current

#24038 Update default config to include Schedule
  source/_integrations/default_config.markdown
Labels: cla-signed, current

#24046 Fixed typo
  source/_integrations/justnimbus.markdown
Labels: current

#24050 Fix broken links
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#24056 Add OpenWeatherMap API policy change in note
  source/_integrations/openweathermap.markdown
Labels: cla-signed, current

#23986 Adding non-supported list
  source/_integrations/panasonic_bluray.markdown
Labels: cla-signed, current

#23988 Document connectivity check unsupported evaluation
  source/more-info/unsupported/connectivity_check.markdown
Labels: cla-signed, current, has-parent

#24016 Update androidtv.markdown
  source/_integrations/androidtv.markdown
Labels: cla-needed, current

#24052 Remove broken WeMo Dimmer Switch link
  source/_integrations/wemo.markdown
Labels: cla-signed, current

#24081 Update docker API version
  source/more-info/unsupported/docker_version.markdown
Labels: cla-signed, current

#23925 update universal media player for unique_id
  source/_integrations/universal.markdown
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged

#24082 Remove duplicated category
  source/_integrations/rainmachine.markdown
Labels: cla-signed, current

#24090 Replace "Updates" category name with "Update"
  source/_integrations/advantage_air.markdown
  source/_integrations/demo.markdown
  source/_integrations/fritz.markdown
  source/_integrations/hassio.markdown
  source/_integrations/leviton_z_wave.markdown
  source/_integrations/netgear.markdown
  source/_integrations/pi_hole.markdown
  source/_integrations/qnap_qsw.markdown
  source/_integrations/rainmachine.markdown
  source/_integrations/sensibo.markdown
  source/_integrations/synology_dsm.markdown
  source/_integrations/unifi.markdown
  source/_integrations/wled.markdown
  source/_integrations/zwave_js.markdown
Labels: cla-signed, current

#24104 Fix word typo
  source/_integrations/xiaomi_ble.markdown
Labels: cla-signed, current

#24105 Zigstar zeroconf
  source/_integrations/zha.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#24085 Add input mapping for Pioneer VSX-1021
  source/_integrations/pioneer.markdown
Labels: cla-signed, current

#24014 Doc fix: Remove outdated information
  source/_integrations/workday.markdown
Labels: cla-signed, in-progress, current

#24111 Update supported lutron_caseta models
  source/_integrations/lutron_caseta.markdown
Labels: cla-signed, next, has-parent

#24100 Ecowitt no TLS/SSL support
  source/_integrations/ecowitt.markdown
Labels: cla-signed, current

#24072 Remove supported sensors
  source/_integrations/bthome.markdown
Labels: cla-signed, next, has-parent, parent-merged

#24125 Remove Ambee integration
  CODEOWNERS
  source/_integrations/ambee.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#24124 Remove duplicate listing of SIM800C
  source/_integrations/sms.markdown
Labels: cla-signed, current

#24129 Update 2022.9 ToC
  source/_posts/2022-09-07-release-20229.markdown
Labels: cla-signed, current

#24126 Remove U.S. Citizenship and Immigration Services (USCIS) integration
  source/_integrations/uscis.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, cleanup

#24130 Add www to clickatell URL
  source/_integrations/clickatell.markdown
Labels: cla-signed, current

#24099 Document number selector step size 'any'
  source/_docs/blueprint/selectors.markdown
Labels: new-feature, cla-signed, next, has-parent

#24028 Add docs for lifx infrared brightness entity
  source/_integrations/lifx.markdown
Labels: cla-signed, has-parent, parent-merged

#24131 Add documentation for version in templates
  source/_docs/configuration/templating.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#24122 Update abode.markdown
  source/_integrations/abode.markdown
Labels: cla-signed, current

#24134 Add some hints about script blueprints
  source/_docs/blueprint.markdown
  source/_docs/blueprint/tutorial.markdown
Labels: cla-signed, in-progress, current

#24073 Fix typo/copy-paste mistake in DWD docs
  source/_integrations/dwd_weather_warnings.markdown
Labels: cla-signed, current

#23868 Update alarm_control_panel.template.markdown
  source/_integrations/alarm_control_panel.template.markdown
Labels: cla-signed, current

#24076 Update the URL to point to the documentation for power supply warnings for rpi_power integration
  source/_integrations/rpi_power.markdown
Labels: cla-signed, current

#24062 Update daikin.markdown
  source/_integrations/daikin.markdown
Labels: cla-signed, current

#24121 Lovelace to entity
  source/_integrations/nmbs.markdown
Labels: cla-signed, current

#23971 Update credits
  source/developers/credits.markdown
Labels: cla-signed, current

#24137 Remove reference for deprecated Speedtest service
  source/_integrations/speedtestdotnet.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, cleanup

#23549 Update accuweather.markdown
  source/_integrations/accuweather.markdown
Labels: cla-signed, current

#24140 Fix typo in bluez version
  source/_integrations/bluetooth.markdown
Labels: cla-signed, current

#24019 Switchbee docs
  source/_integrations/switchbee.markdown
Labels: new-integration, cla-signed, in-progress, next, has-parent, parent-merged

#24143 Add a missing description field
  source/_docs/blueprint/tutorial.markdown
Labels: cla-needed, current

#24144 Remove an extra indentation
  source/_docs/configuration/splitting_configuration.markdown
Labels: cla-needed, current

#24053 Zigbee backup and restore in ZHA docs
  source/_integrations/zha.markdown
Labels: cla-signed, current

#24156 Update aws.markdown
  source/_integrations/aws.markdown
Labels: cla-signed, current

#24075 Update litterrobot to cloud push
  source/_integrations/litterrobot.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#24153 Add litter level sensor to Litter-Robot documentation
  source/_integrations/litterrobot.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#23374 Add docs for migration of Guardian AP services to a switch
  source/_integrations/guardian.markdown
Labels: cla-signed, awaits-parent, next, parent-merged

#24158 Update time_date.markdown
  source/_integrations/time_date.markdown
Labels: cla-signed, current

#23670 Add docs for migration of SimpliSafe service to a button
  source/_integrations/simplisafe.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23952 Clarify use of Sonos favorites sensor in service calls
  source/_integrations/sonos.markdown
Labels: cla-signed, in-progress, current

#24163 Add brand
  source/_integrations/led_ble.markdown
Labels: cla-signed, current

#24162 Add number platform to Melnor Bluetooth docs
  source/_integrations/melnor.markdown
Labels: new-feature, cla-signed, next, has-parent

#24176 Add some hints to Synology DSM
  source/_integrations/synology_dsm.markdown
Labels: cla-signed, current

#24177 Docker Compose V2 changes
  source/_includes/installation/container.md
Labels: cla-signed, current

#23688 Add guidance for dealing with Bluetooth interference
  source/_integrations/bluetooth.markdown
Labels: cla-signed, in-progress, current, needs-rebase

#24186 Update sms.markdown
  source/_integrations/sms.markdown
Labels: cla-signed, current

#24178 Add iBeacon integration
  source/_integrations/ibeacon.markdown
Labels: cla-signed, next, has-parent, parent-merged

#24196 Formatting Changes
  source/_integrations/timer.markdown
Labels: cla-signed, current

#24170 Remove docs for deprecated Flu Near You integration
  CODEOWNERS
  source/_integrations/flunearyou.markdown
  source/_redirects
Labels: cla-signed, in-progress, next, has-parent, parent-merged, cleanup

#24175 Update sign CLA URL
  source/developers/cla_sign.html
Labels: cla-signed, current

#24202 Add HZW1004 to supported panasonic TVs
  source/_integrations/panasonic_viera.markdown
Labels: current

#24203 Promote State of the Open Home
  source/images/frontpage/hacktoberfest.png
  source/images/frontpage/state-of-the-open-home-2022.png
  source/index.html
Labels: current

#24212 update API credentials info
  source/_integrations/smappee.markdown
Labels: current

#24172 Add Kegtron documentation
  source/_integrations/kegtron.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#24213 Update statistics.markdown's change* platform
  source/_integrations/statistics.markdown
Labels: current

#24204 Remove Google Analytics
  _config.yml
  source/_includes/google_analytics.html
  source/_includes/javascripts/scripts.html
Labels: current

#24206 Unsupported restart policy information
  source/more-info/unsupported/restart_policy.markdown
Labels: in-progress, current, has-parent

#24149 Added button platform to SwitchBee docs
  source/_integrations/switchbee.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#24207 Rename zwavejs2mqtt to zwave-js-ui in docs
  source/_docs/z-wave/controllers.markdown
  source/_integrations/zwave_js.markdown
Labels: current

#24219 Amended the push update instructions for Yale Access Bluetooth
  source/_integrations/yalexs_ble.markdown
Labels: current

#24059 Docs about Bravia TV Button platform
  source/_integrations/braviatv.markdown
Labels: new-feature, cla-signed, next, has-parent

#24241 Update URL
  source/_docs/automation/trigger.markdown
Labels: current

#24225 Document how homekit_controller can use thread networks
  source/_integrations/homekit_controller.markdown
Labels: next, has-parent

#23109 Update netatmo.markdown
  source/_integrations/netatmo.markdown
Labels: cla-signed, awaits-parent, next, has-parent, needs-rebase

#24228 Add intro and example to iBeacon Tracker
  source/_integrations/ibeacon.markdown
Labels: next, has-parent, parent-merged

#24013 Add Google Sheets docs
  source/_integrations/google_sheets.markdown
Labels: new-integration, cla-signed, in-progress, next, has-parent, parent-merged

#21625 Add documentation for Lidarr integration
  source/_integrations/lidarr.markdown
Labels: new-integration, cla-signed, in-progress, next, has-parent, parent-merged

#24102 Add range to min-max integration
  source/_integrations/min_max.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#24249 Add pull_request to CLA sign data
  source/developers/cla_sign.html
Labels: current

#22815 Add netgear switch discription
  source/_integrations/netgear.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#20550 Add docs to radarr config flow
  source/_integrations/radarr.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#23237 Intellifire fan
  source/_integrations/intellifire.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#24183 Update connectivity check solution for uri not set
  source/more-info/unsupported/connectivity_check.markdown
Labels: cla-signed, current

#24234 Adjust the OS/Supervised docs for spesific version
  source/_includes/common-tasks/beta_version.md
  source/_includes/common-tasks/development_version.md
  source/_includes/common-tasks/specific_version.md
  source/_includes/common-tasks/update.md
Labels: current

#24214 Update bluetooth requirements in documentation
  source/_integrations/bluetooth.markdown
Labels: current

#24237 Explain default behavior of `expire_after` option for MQTT sensors
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: current

#24239 Hide core instructions for caldav
  source/_integrations/caldav.markdown
Labels: current

#24231 Add documentation for the lifx.effect_move service
  source/_integrations/lifx.markdown
Labels: new-feature, next, has-parent, parent-merged

#24250 Add binary sensor docs for Radarr
  source/_integrations/radarr.markdown
Labels: next, has-parent, parent-merged

#23939 Update dsmr_reader config flow and autodiscovery
  source/_includes/integrations/config_flow.md
  source/_integrations/dsmr_reader.markdown
Labels: cla-signed, awaits-parent, in-progress, next, has-parent, parent-merged

#23996 Docs about PSK auth and SSDP discovery in Bravia TV
  source/_integrations/braviatv.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#24045 Clarify access vs master code
  source/_integrations/risco.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#21899 [Bayesian] Make examples easier to understand, adds tips
  source/_integrations/bayesian.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#24261 Fix EZVIZ spelling case
  source/_integrations/ezviz.markdown
Labels: in-progress, current, has-parent

#24066 Add generic speed device_class
  source/_integrations/sensor.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#24265 Add units to speed device class
  source/_integrations/sensor.markdown
Labels: next, has-parent

#24067 Add generic volume device_class
  source/_integrations/sensor.markdown
Labels: cla-signed, next, has-parent, parent-merged

#24266 Update switcher_kis network setup notes
  source/_integrations/switcher_kis.markdown
Labels: current

#24255 Update apcupsd docs to reflect support for config flow.
  source/_integrations/apcupsd.markdown
Labels: next, has-parent, parent-merged

#24248 Add generic weight device class
  source/_integrations/sensor.markdown
Labels: next, has-parent

#24268 Update Slack documentation to fix incorrect button description
  source/_integrations/slack.markdown
Labels: current

#24159 Added SwitchBee Light platform docs
  source/_integrations/switchbee.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#24284 Add additional known working iBeacon devices
  source/_integrations/ibeacon.markdown
Labels: in-progress, next, needs-rebase

#24277 Add subview documentation
  source/dashboards/views.markdown
Labels: new-feature, next, has-parent, parent-merged

#24287 Month of What the heck?! 2022
  source/_posts/2020-08-18-the-month-of-what-the-heck.markdown
  source/_posts/2022-09-30-the-month-of-what-the-heck.markdown
  source/images/blog/2022-09-30-the-month-of-what-the-heck/social.png
Labels: blog, current
