Repository home-assistant/home-assistant.io, pull requests merged in 2022-07, with the labels that each got.

#23241 Add config flow to Bose SoundTouch documentation
  source/_integrations/soundtouch.markdown
Labels: cla-signed, awaits-parent, in-progress, next, has-parent, parent-merged

#23247 qnap_qsw: document firmware update
  source/_integrations/qnap_qsw.markdown
Labels: cla-signed, next, has-parent

#18572 Add config flow to AnthemAv integration
  source/_integrations/anthemav.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#23253 Revert "Config flow for Scrape integration"
  source/_integrations/scrape.markdown
Labels: cla-signed, next

#23234 Add NextDNS documentation
  source/_integrations/nextdns.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#23271 Added Automatic setup to application credentials page
  source/_integrations/application_credentials.markdown
  source/images/integrations/application_credentials/application-credential-setup.png
  source/images/integrations/application_credentials/application-credentials.png
Labels: cla-signed, current

#23236 Intellifire climate
  source/_integrations/intellifire.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#22889 Convert life360 integration to entity based
  source/_integrations/life360.markdown
  source/images/integrations/life360/integration_options.png
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#23279 Added location description to the overflow menu for app credentials.
  source/_integrations/application_credentials.markdown
  source/images/integrations/application_credentials/devices-and-services-menu.png
Labels: cla-signed, current

#23265 Add info about diagnostics platform to the NextDNS documentation
  source/_integrations/nextdns.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23280 Fix default names of derivative and integration
  source/_integrations/derivative.markdown
  source/_integrations/integration.markdown
Labels: cla-signed, current

#23300 Update URLs
  source/_integrations/denon.markdown
  source/_integrations/denonavr.markdown
  source/_integrations/ifttt.markdown
  source/_integrations/imap.markdown
  source/_integrations/keyboard.markdown
  source/_integrations/wemo.markdown
  source/_integrations/zha.markdown
Labels: cla-signed, current

#23297 Improve nest troubleshooting and upgrade instructions
  source/_integrations/nest.markdown
Labels: cla-signed, current

#23295 Add requirements for initial value
  source/_integrations/counter.markdown
Labels: cla-signed, current

#23294 Update simplepush.markdown
  source/_integrations/simplepush.markdown
Labels: cla-needed, current

#23255 Update links to smartthings developer website
  source/_integrations/smartthings.markdown
Labels: cla-signed, current

#23305 Update Life360 breaking change notes
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, current

#23306 Update Gauge to make needle required true when using segments
  source/_dashboards/gauge.markdown
Labels: cla-signed, current

#23304 Document trigger/arm_custom_bypass options in template alarm control panel
  source/_integrations/alarm_control_panel.template.markdown
Labels: cla-signed, awaits-parent, in-progress, next, has-parent, needs-rebase, parent-merged

#23307 Update efibootmgr command
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#23316 Correct link to github user - kingy444
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#23329 2022.7.2
  _config.yml
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#23327 Add bluetooth integration
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23326 Add huawei_lte wifi guest network switch
  source/_integrations/huawei_lte.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase

#23334 Update nest documentation with common misunderstandings
  source/_integrations/nest.markdown
  source/images/integrations/nest/application_credentials.png
  source/images/integrations/nest/attention.png
  source/images/integrations/nest/deprecation.png
  source/images/integrations/nest/setup_prompt.png
Labels: cla-signed, current

#22980 Update application credentials instructions for google calendar OAuth
  source/_integrations/google.markdown
Labels: cla-signed, current

#23331 Add update OS hint to privilige error docs
  source/more-info/unsupported/privileged.markdown
Labels: cla-signed, current

#23328 Add documentation for HomeWizard Wifi Watermeter
  source/_integrations/homewizard.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23323 Update Life360 breaking change notes
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, current

#23338 Added hint to Amcrest directions
  source/_integrations/amcrest.markdown
Labels: cla-signed, current

#23339 Add sensors to Sensibo
  source/_integrations/sensibo.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23348 Add binary_sensor support to ElkM1 integration
  source/_integrations/elkm1.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23357 Correct information about number entity unit conversion in 2022.7 release notes
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, current

#23359 Improve MQTT device_tracker documentation
  source/_docs/mqtt/discovery.markdown
  source/_integrations/device_tracker.mqtt.markdown
Labels: cla-signed, current

#23351 Add Rhasspy integration
  source/_integrations/rhasspy.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23364 Update ecobee.markdown
  source/_integrations/ecobee.markdown
Labels: cla-signed, current

#23362 Update Fronius documentation to include new entity naming style
  source/_integrations/fronius.markdown
Labels: cla-signed, next, has-parent

#23371 Partner Program Announcement
  source/_posts/2022-07-12-partner-program.markdown
  source/images/blog/2022-07-12-partner-program/partner-program-logos.jpg
  source/images/blog/2022-07-12-partner-program/partner_program_og.jpg
Labels: cla-signed, blog, current

#23375 Updated urls to github project of upstream lib
  source/_integrations/homematicip_cloud.markdown
Labels: cla-signed, current

#23313 Update for Number platform
  source/_integrations/plugwise.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23380 Missed breaking change to media_player in 2022.5
  source/_posts/2022-05-04-release-20225.markdown
Labels: cla-signed, current

#23373 Add docs for Guardian migration of certain services to buttons
  source/_integrations/guardian.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#23388 Update UniFi Protect docs regrading Smart Detections
  source/_integrations/unifiprotect.markdown
Labels: cla-signed, current

#23390 Add bluez to the core install instructions
  source/_includes/installation/core.md
Labels: cla-signed, next, has-parent

#23394 Add multi-factor authentication support to Verisure
  source/_integrations/verisure.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23408 Added Denon AVR-S950H
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#23405 Update history_stats.markdown
  source/_integrations/history_stats.markdown
Labels: cla-signed, current

#23412 Document the install UniFi device update feature
  source/_integrations/unifi.markdown
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged

#23379 BleBox button update
  source/_integrations/blebox.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23418 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#23417 Update HomeKit Controller for BLE support
  source/_integrations/homekit_controller.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23437 Update overkiz.markdown
  source/_integrations/overkiz.markdown
Labels: cla-signed, current

#23381 Add YoLink garage door document
  source/_integrations/yolink.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23430 Embed Nest integration setup video
  source/_integrations/nest.markdown
Labels: cla-signed, current

#23045 Update litterrobot documentation to match current implementation
  source/_integrations/litterrobot.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#23439 miiocli has changed option vacuum to roborockvacuum
  source/_integrations/xiaomi_miio.markdown
Labels: cla-signed, current

#23441 Fix dead link in manual Lutron Caseta instructions
  source/_integrations/lutron_caseta.markdown
Labels: cla-signed, current

#23076 Update sql.markdown
  source/_integrations/sql.markdown
Labels: cla-signed, in-progress, current

#23444 Tiny adjustment to feedback issue form
  .github/ISSUE_TEMPLATE/feedback.yml
Labels: cla-signed, current

#23261 Update LIFX for config entry per device reliability refactor
  source/_integrations/lifx.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23446 Add known working bluetooth adapters
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next, has-parent

#23449 Fixed typo
  source/_integrations/group.markdown
Labels: cla-signed, current

#23450 devices -> brands, 1900->1000
  source/_includes/custom/features.html
Labels: cla-signed, current

#23457 Document `auto_fit` config option
  source/_dashboards/map.markdown
Labels: cla-signed, next, has-parent

#23455 Add ASUS USB-BT500 to good bluetooth adapters list
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next

#23465 Remove XBee integration
  source/_integrations/xbee.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, cleanup

#23467 Remove SoChain integration
  source/_integrations/sochain.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, cleanup

#23468 Remove Google Play Music Desktop Player (GPMDP) integration
  source/_integrations/gpmdp.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, cleanup

#23471 Statistics integration: Fix typo
  source/_integrations/statistics.markdown
Labels: cla-signed, current

#23470 2022.7.6
  _config.yml
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, blog, in-progress, current, has-parent, needs-rebase

#23407 Update stream technical details
  source/_integrations/stream.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#23476 Deprecate U.S. Citizenship and Immigration Services (USCIS) integration
  source/_integrations/uscis.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23486 Add Works with Badge to sidebar + set ESPHome as works with Local
  source/_includes/asides/component_navigation.html
  source/_integrations/esphome.markdown
  source/images/works_with/works-with-bluetooth.png
  source/images/works_with/works-with-cloud.png
  source/images/works_with/works-with-local.png
  source/images/works_with/works-with-matter.png
  source/images/works_with/works-with-zigbee.png
  source/images/works_with/works-with-zwave.png
Labels: cla-signed, current

#23479 Update stream technical details spacing
  source/_integrations/stream.markdown
Labels: cla-signed, current

#23485 Fix typo harmony hub remote example code
  source/_integrations/universal.markdown
Labels: cla-signed, current

#23484 Add inkbird BLE integration
  source/_integrations/inkbird.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23509 Fix typo “Resey” -> “Reset”
  source/_integrations/zha.markdown
Labels: cla-signed, current

#23498 Remove ha_zeroconf from inkbird and replace with ha_bluetooth
  source/_integrations/inkbird.markdown
Labels: cla-signed, next

#23492 Add Govee BLE integration
  source/_integrations/govee_ble.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23503 Add moat integration
  source/_integrations/moat.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23506 Add configuration option examples to OpenTherm Gateway
  source/_integrations/opentherm_gw.markdown
Labels: cla-signed, current

#23495 Update switchbot to be local push
  source/_integrations/switchbot.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23491 Xiaomi MiBeacon/BLE support
  source/_integrations/xiaomi_ble.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23493 Update docs to reflect SimpliSafe's auth mechanism reversion
  source/_integrations/simplisafe.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23481 Add SensorPush integration
  source/_integrations/sensorpush.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23488 Update bluetooth with support setting up and removing in the UI
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23512 Update switchbot to remove common options
  source/_integrations/switchbot.markdown
Labels: cla-signed, next, has-parent

#23510 Add notes about bluetooth requirements for each install type
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next

#23514 Update list of known working bluetooth adapters
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next, has-parent

#23521 Add information about Bluetooth interference
  source/_integrations/bluetooth.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase

#23517 Update basics.markdown
  source/_docs/automation/basics.markdown
Labels: cla-signed, current

#23049 Minor addition to supervisor unhealthy
  source/more-info/unhealthy/supervisor.markdown
Labels: cla-signed, current

#23263 Link Utility integration for non-negative derivatives
  source/_integrations/derivative.markdown
Labels: cla-signed, current

#23281 Update caldav.markdown with Radicale example
  source/_integrations/caldav.markdown
Labels: cla-signed, current

#23303 Document MQTT discovery messages allow unknown configuration keys
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#23354 Migrate HomeWizard entity names to new naming style
  source/_integrations/homewizard.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23310 Update integration.markdown
  source/_integrations/integration.markdown
Labels: cla-signed, in-progress, current

#23296 Update docs for false mention
  source/_integrations/google_assistant.markdown
Labels: cla-signed, current

#23451 Update actions.markdown
  source/dashboards/actions.markdown
Labels: cla-signed, current

#23469 Clarified the meaning and usage of notify.notify
  source/_integrations/notify.markdown
Labels: cla-signed, current

#23489 Minor grammar fixes
  source/_docs/mqtt/discovery.markdown
Labels: cla-signed, current

#23515 Add Bluetooth Grill Thermometer IBT-2X to inkbird
  source/_integrations/inkbird.markdown
Labels: cla-signed, next

#23516 Document how to select a different bluetooth adapter
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23426 Added new supported device HmIP-STE2-PCB
  source/_integrations/homematicip_cloud.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#23529 Use more inclusive terminology in mqtt eventstream
  source/_integrations/mqtt_eventstream.markdown
Labels: cla-signed, current

#23530 Add support for switchbot BLE contact sensor
  source/_integrations/switchbot.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23533 2022.7.7
  _config.yml
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, blog, in-progress, current, has-parent, needs-rebase

#23531 Remove miflora integration
  source/_integrations/miflora.markdown
  source/_redirects
Labels: cla-signed, next, has-parent

#23537 Fix typo
  source/_integrations/almond.markdown
Labels: cla-signed, current

#23382 Z-Wave JS integration rename to Z-Wave
  source/_integrations/zwave_js.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23443 Make extra clear that Ubuntu is not supported with Supervised
  source/_includes/installation/supervised.md
Labels: cla-signed, current

#23532 Remove Xiaomi Mijia BLE Temperature and Humidity Sensor
  source/_integrations/mitemp_bt.markdown
  source/_redirects
Labels: cla-signed, has-parent, cleanup

#23540 Use more inclusive terminology in airzone
  source/_integrations/airzone.markdown
Labels: cla-signed, current

#23541 Update baf.markdown for occupancy sensor
  source/_integrations/baf.markdown
Labels: cla-signed, next, has-parent

#23544 Deprecate the Ambee integration
  source/_integrations/ambee.markdown
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#23547 Document new xiaomi sensors
  source/_integrations/xiaomi_ble.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23546 Deprecate the OpenALPR Local integration
  source/_integrations/openalpr_local.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23550 Leviton Integration Page + Announcement
  source/_integrations/leviton.markdown
  source/_posts/2022-07-27-leviton-partner.markdown
  source/images/blog/2022-07-27-leviton-partner/leviton-device-page.png
  source/images/blog/2022-07-27-leviton-partner/leviton-devices.jpg
  source/images/blog/2022-07-27-leviton-partner/social-image.jpg
Labels: cla-signed, blog, current

#23555 Merge current into next
  source/_integrations/leviton.markdown
  source/_posts/2022-07-27-leviton-partner.markdown
  source/images/blog/2022-07-27-leviton-partner/leviton-device-page.png
  source/images/blog/2022-07-27-leviton-partner/leviton-devices.jpg
  source/images/blog/2022-07-27-leviton-partner/social-image.jpg
Labels: cla-signed, in-progress, next, needs-rebase

#23559 Fix Link in blog post
  source/_posts/2022-07-27-leviton-partner.markdown
Labels: cla-signed, current

#23564 Update system health pages
  source/_integrations/system_health.markdown
  source/images/more-info/system_health.png
  source/images/more-info/system_health_github.png
  source/more-info/system-health.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#23561 Fix typo in bluetooth docs
  source/_integrations/bluetooth.markdown
Labels: cla-signed, next

#23570 Add authentication clarification to SimpliSafe docs
  source/_integrations/simplisafe.markdown
Labels: cla-signed, next

#23569 Correct grammar in selectors documentation
  source/_docs/blueprint/selectors.markdown
Labels: cla-signed, current

#23578 Migrate Nest alert
  source/_integrations/nest.markdown
  source/more-info/nest-auth-deprecation.markdown
Labels: cla-signed, current

#23332 Add additional anthemav compatible models
  source/_integrations/anthemav.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#23579 Restyle integration alert bar
  sass/custom/_paulus.scss
  source/_integrations/nest.markdown
  source/_layouts/page.html
Labels: cla-signed, current

#23586 Fix incorrect event data keys in SimpliSafe docs
  source/_integrations/simplisafe.markdown
Labels: cla-signed, in-progress, next

#23589 Minor improvement: Add explicit ref to the "Create backup" button
  source/_includes/common-tasks/backups.md
Labels: cla-signed, current

#23583 Fix Cache-Control max-age syntax
  source/_headers
Labels: cla-signed, current

#23545 Changed OpenUV update automation example to be more realistic
  source/_integrations/openuv.markdown
Labels: cla-signed, current
