Repository home-assistant/home-assistant.io, pull requests merged in 2022-04, with the labels that each got.

#22216 Clarify how to find media_id for BBC sounds clips
  source/_integrations/cast.markdown
Labels: cla-signed, current

#22215 Sort 3rd-party players in Google Cast docs
  source/_integrations/cast.markdown
Labels: cla-signed, current

#22213 Fix double mean
  source/_integrations/min_max.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#16129 Add docs for Meater integration
  source/_integrations/meater.markdown
Labels: new-integration, cla-signed, awaits-parent, next, has-parent

#22221 Rename current_version to installed_version in Update platform
  source/_integrations/update.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#22223 Remove partner configuration option
  source/_integrations/eight_sleep.markdown
Labels: cla-signed, current

#21988 Drop support for Tradfri groups
  source/_integrations/tradfri.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#22227 update template availability documentation
  source/_integrations/cover.template.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/light.template.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/vacuum.template.markdown
Labels: cla-signed, current

#22229 Update plugwise docs for added select platform
  source/_integrations/plugwise.markdown
Labels: cla-signed, next, has-parent

#22236 Minor wording and puncutation changes
  source/_integrations/workday.markdown
Labels: cla-needed, current

#22231 Update OctoPrint camera docs
  source/_integrations/octoprint.markdown
Labels: cla-signed, current

#22237 Add terms "weekend" and "weekday"
  source/_integrations/workday.markdown
Labels: cla-signed, current

#22180 Add config flow for Utility Meter
  source/_integrations/utility_meter.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22246 Document `auto_repack` for the recorder
  source/_integrations/recorder.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22252 Add KNX sensor type `latin_1`
  source/_integrations/knx.markdown
Labels: cla-signed, next, has-parent

#22247 added documentation of support of FortiOS 7.2.0
  source/_integrations/fortios.markdown
Labels: cla-signed, current

#21424 Add honeywell sensor
  source/_integrations/honeywell.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22250 Add Mazda breaking changes to 2022.4 release notes
  source/_posts/2022-04-06-release-20224.markdown
Labels: cla-signed, in-progress, has-parent, needs-rebase, rc

#22268 Fix typo in release notes
  source/_posts/2022-04-06-release-20224.markdown
Labels: cla-signed, current

#22272 Add Redirect for bad link in newsletter
  source/_redirects
Labels: cla-signed, current

#22284 Update timer.markdown
  source/_integrations/timer.markdown
Labels: cla-signed, current

#22285 Clarify old-style groups are only availble via YAML
  source/_integrations/group.markdown
Labels: cla-signed, current

#22258 Document restore of trigger-based template binary sensors
  source/_integrations/template.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase

#22291 Add `homeassistant.min_version` to schema
  source/_docs/blueprint/schema.markdown
Labels: cla-signed, current

#22277 2022.4.1
  _config.yml
  source/_posts/2022-04-06-release-20224.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22294 Update operating_system.md
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#22299 Correct the use of "then" to "than"
  source/_integrations/utility_meter.markdown
Labels: cla-signed, current

#22306 Update google documentation for "message"
  source/_integrations/google.markdown
Labels: cla-signed, current

#22325 Slightly clarify that the Integration inputs must be of device_class: power in order to create a device_class: energy integration
  source/_integrations/integration.markdown
Labels: cla-signed, current

#22334 2022.4.2
  _config.yml
  source/_posts/2022-04-06-release-20224.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22327 Update API limit in tomorrowio docs
  source/_integrations/tomorrowio.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22340 Fix Roth Touchline URL
  source/_integrations/touchline.markdown
Labels: cla-signed, current

#22343 Update forked_daapd.markdown
  source/_integrations/forked_daapd.markdown
Labels: cla-signed, current

#22347 Link right clicking our logo to brand design guide lines
  source/_includes/javascripts/scripts.html
Labels: cla-signed, current

#22348 Link newsletter on frontpage
  source/_redirects
  source/index.html
Labels: cla-signed, current

#22338 Add stop/error script/automation action
  source/_docs/scripts.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22364 Let's Encrypt image is deprecated
  source/_integrations/fail2ban.markdown
Labels: cla-signed, current

#22363 Clarify service name in Discord
  source/_integrations/discord.markdown
Labels: cla-signed, in-progress, current

#22322 Trigger on not matching to/from states
  source/_docs/automation/trigger.markdown
Labels: new-feature, cla-signed, next, has-parent

#22370 Discourage use of discovery integration
  source/_integrations/discovery.markdown
Labels: cla-signed, current

#22280 Improve Airzone integration documentation
  source/_integrations/airzone.markdown
Labels: cla-signed, current

#22377 Update opensky.markdown
  source/_integrations/opensky.markdown
Labels: cla-signed, current

#22369 Remove digitalloggers documentation
  source/_integrations/digitalloggers.markdown
  source/_redirects
Labels: cla-signed, next, has-parent, parent-merged, cleanup

#22379 Remove Twitter and FB SDKs
  sass/partials/_sharing.scss
  source/_includes/after_footer.html
  source/_includes/asides/about.html
  source/_includes/facebook_like.html
  source/_includes/post/sharing.html
  source/_includes/twitter_sharing.html
  source/_posts/2019-09-18-release-99.markdown
  source/_posts/2020-09-20-community-highlights.markdown
  source/_posts/2020-11-30-community-highlights.markdown
  source/_posts/2021-04-23-community-highlights.markdown
  source/_posts/2021-05-07-community-highlights.markdown
Labels: cla-signed, current

#22318 Update Shelly gen2 authentication support
  source/_integrations/shelly.markdown
Labels: new-feature, cla-signed, next, has-parent

#22380 Add aditional supported blinds
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, in-progress, current

#22382 Add KL420 to tplink supported list
  source/_integrations/tplink.markdown
Labels: cla-signed, in-progress, current, needs-rebase

#22387 Add "more" tags to some blog posts
  source/_posts/2022-01-07-android-quest.markdown
  source/_posts/2022-02-02-release-20222.markdown
  source/_posts/2022-02-08-android-february.markdown
  source/_posts/2022-03-02-release-20223.markdown
  source/_posts/2022-04-06-release-20224.markdown
  source/state-of-the-open-home/index.markdown
Labels: cla-signed, current

#22389 Do not load youtube iframes until interaction
  sass/custom/_paulus.scss
  source/_includes/javascripts/scripts.html
  source/_integrations/alexa.intent.markdown
  source/_integrations/nest.markdown
  source/_integrations/owntracks.markdown
  source/_integrations/person.markdown
  source/_integrations/rtsp_to_webrtc.markdown
  source/_integrations/somfy.markdown
  source/_integrations/tag.markdown
  source/_posts/2021-12-18-ios-multi-server.markdown
  source/_posts/2021-12-21-android-december-2021-release.markdown
  source/_posts/2021-12-21-stanford-genie.markdown
  source/_posts/2021-12-23-the-open-home.markdown
  source/_posts/2021-12-28-northeastern-university-home-energy-management.markdown
  source/conference/index.markdown
  source/dashboards/index.markdown
  source/state-of-the-open-home/index.markdown
Labels: cla-signed, current

#22386 Update webostv.markdown
  source/_integrations/webostv.markdown
Labels: cla-signed, current

#22391 Remove script editor docs
  source/_docs/automation/editor.markdown
  source/_docs/scripts/editor.markdown
  source/_includes/asides/docs_navigation.html
Labels: cla-signed, current

#22390 Add ability to continue scripts/automations on error
  source/_docs/scripts.markdown
Labels: new-feature, cla-signed, next, has-parent

#22288 MQTT Scene - Correct merging #22197
  source/_integrations/scene.mqtt.markdown
Labels: cla-signed, in-progress, current

#22394 Add nVent RAYCHEM SENZ integration
  source/_integrations/senz.markdown
Labels: new-integration, cla-signed, next, has-parent

#22244 Add section about new entity ambilight+hue switch
  source/_integrations/philips_js.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22342 Add if/else automation/script action
  source/_docs/scripts.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22375 Add parallel automation/script actions
  source/_docs/scripts.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22401 Allow disabling specific triggers/actions/conditions
  source/_docs/automation/trigger.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22400 Add for each item support to repeat action
  source/_docs/scripts.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22374 Add Airzone System ID config
  source/_integrations/airzone.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#22411 Update insteon.markdown
  source/_integrations/insteon.markdown
Labels: cla-signed, current

#22409 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#22415 Blog post buying device
  source/_posts/2022-04-16-device-to-run-home-assistant.markdown
Labels: cla-signed, blog, current

#22413 Fix typo in Sensors area.
  source/_integrations/aurora.markdown
Labels: cla-signed, current

#22419 Add Wikipedia link to derivative
  source/_integrations/derivative.markdown
Labels: cla-signed, current

#22393 Clarify source of nextcloud entity information
  source/_integrations/nextcloud.markdown
Labels: cla-signed, in-progress, current

#22408 Documentation for condition shorthand
  source/_docs/automation/condition.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#22421 Add Template selector
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/selector-template.png
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22425 Added another Raspberry Pi restock tracking site
  source/_includes/installation/operating_system.md
Labels: cla-signed, current

#22331 Update PECO page with new map alert entity
  source/_integrations/peco.markdown
Labels: new-feature, cla-signed, next, has-parent

#22429 Update documentation for FRITZ!Box Call Monitor
  source/_integrations/fritzbox_callmonitor.markdown
Labels: cla-signed, current

#22430 Add diagnostics platform to the Supervisor integration
  source/_integrations/hassio.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22323 Add Z-Wave.Me Fan support
  source/_integrations/zwave_me.markdown
Labels: new-feature, cla-signed, next, has-parent

#22403 Add clear_skipped service to update entity
  source/_integrations/update.markdown
Labels: new-feature, cla-signed, next, has-parent

#20052 Add target_temp_step to generic_thermostat
  source/_integrations/generic_thermostat.markdown
Labels: Hacktoberfest, cla-signed, next, has-parent, parent-merged, hacktoberfest-accepted

#22441 Update sms.markdown
  source/_integrations/sms.markdown
Labels: cla-signed, current

#22436 Removed supervisor from sidebar image.
  source/images/getting-started/lovelace.png
Labels: cla-signed, current

#22444 Updated navigation to add integrations.
  source/getting-started/onboarding.markdown
Labels: cla-signed, current

#22431 Clarify template switch options
  source/_integrations/switch.template.markdown
Labels: cla-signed, current

#22445 Cleanup Insteon documentation
  source/_integrations/insteon.markdown
Labels: cla-signed, current

#22447 Add blog post about Insteon
  source/_integrations/insteon.markdown
  source/_posts/2022-04-19-for-insteon-users.markdown
  source/images/integrations/insteon/insteon-products.jpg
Labels: cla-signed, current

#22407 Add backup.create service
  source/_integrations/backup.markdown
Labels: new-feature, cla-signed, next, has-parent

#22211 Document `this` variable in state-based template entities
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/cover.template.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/light.template.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/template.markdown
  source/_integrations/vacuum.template.markdown
  source/_integrations/weather.template.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#22451 Take into account an offset for the menu bar on anchor targets
  sass/custom/_paulus.scss
Labels: cla-signed, current

#22454 Remove EVENT_TIME_CHANGED and EVENT_TIMER_OUT_OF_SYNC
  source/_docs/configuration/events.markdown
  source/_integrations/history.markdown
Labels: cla-signed, next, has-parent

#22178 Configuration values for automations
  source/_docs/automation/yaml.markdown
Labels: cla-signed, in-progress, current

#22483 Fixed spelling mistake in template example in 2022.2 release note
  source/_posts/2022-02-02-release-20222.markdown
Labels: cla-signed, current

#22469 Update environment_canada
  source/_integrations/environment_canada.markdown
Labels: cla-signed, current

#22490 Document new Airzone thermostat low battery warning
  source/_integrations/airzone.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22492 Add diagnostics to Airzone ha_platforms
  source/_integrations/airzone.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22487 Add KNX notify `type` configuration option
  source/_integrations/knx.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22450 Remove Arlo integration
  source/_integrations/arlo.markdown
  source/_redirects
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged, cleanup

#22452 BMW: Replace button entity with homeassistant service
  source/_integrations/bmw_connected_drive.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22162 Update sql for config flow
  source/_integrations/sql.markdown
Labels: new-feature, cla-signed, next, has-parent

#22508 Add electric current and voltage sensor to Fritz!Smarthome
  source/_integrations/fritzbox.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22509 2022.4.7
  _config.yml
  source/_posts/2022-04-06-release-20224.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22328 Add documentation for calendar trigger initial version
  source/_docs/automation/templating.markdown
  source/_docs/automation/trigger.markdown
  source/_integrations/calendar.markdown
  source/images/integrations/calendar/trigger.png
Labels: new-feature, cla-signed, in-progress, next, has-parent

#22507 Minor boradlink domain correction
  source/_integrations/broadlink.markdown
Labels: cla-signed, current

#22479 Added documentation for gauge segments feature
  source/_dashboards/gauge.markdown
  source/images/dashboards/lovelace_gauge_segments.png
Labels: new-feature, cla-signed, next, has-parent

#22464 ONVIF: Update Sensors
  source/_integrations/onvif.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22516 Add unsupported help for dns server issue
  source/more-info/unsupported/dns_server.markdown
Labels: cla-signed, in-progress, current, has-parent

#22449 Corrected documentation in anticipation of the new feature from home-…
  source/_docs/blueprint/schema.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22477 Document resume & offset in Plex `play_media`
  source/_integrations/plex.markdown
Labels: cla-signed, current, has-parent

#22467 Add trigger and condition to configuration vars
  source/_docs/automation/yaml.markdown
Labels: cla-signed, current

#21660 Adding to the set climate timer service as part of code pr
  source/_integrations/tado.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#22402 Merge stop & error script actions
  source/_docs/scripts.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#21770 Add Alarm Control Panel to Overkiz integration
  source/_integrations/overkiz.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22399 Added new update platform to fritz documentation
  source/_integrations/fritz.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#22383 Update LIFX documentation
  source/_integrations/lifx.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22365 Intellifire Troubleshooting updates
  source/_integrations/intellifire.markdown
  source/images/integrations/intellifire/soft_reset.png
Labels: cla-signed, in-progress, next, needs-rebase

#21705 Add Yamaha MusicCast Switch entities
  source/_integrations/yamaha_musiccast.markdown
Labels: new-feature, cla-signed, next, has-parent

#22478 Describe Plex "scan_clients" button
  source/_integrations/plex.markdown
Labels: cla-signed, in-progress, current, has-parent

#22527 Remove references to removed attribute
  source/_integrations/emulated_kasa.markdown
Labels: cla-signed, in-progress, current

#22532 Minor clarification of SQLAlchemy DB support
  source/_integrations/recorder.markdown
Labels: cla-signed, current

#22504 Update wallbox.markdown
  source/_integrations/wallbox.markdown
Labels: new-feature, cla-signed, next, has-parent

#22417 Add new QNAP QSW integration
  source/_integrations/qnap_qsw.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#19705 Add config flow to tautulli docs
  source/_integrations/tautulli.markdown
Labels: Hacktoberfest, new-feature, cla-signed, awaits-parent, next, has-parent, hacktoberfest-accepted

#22528 Add button to yale_smart_alarm
  source/_integrations/yale_smart_alarm.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22476 Create trafikverket_ferry integration
  source/_integrations/trafikverket_ferry.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#22488 Document zwave_js Multilevel Switch
  source/_integrations/zwave_js.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22489 Add documentation for zwave_js.invoke_cc_api service
  source/_integrations/zwave_js.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#22423 Update SimpliSafe docs to reflect simpler setup
  source/_integrations/simplisafe.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent

#22533 hassio: Add missing compressed attribute to backup
  source/_integrations/hassio.markdown
Labels: cla-signed, awaits-parent, in-progress, current, has-parent, needs-rebase

#22537 Add slimproto docs
  source/_integrations/slimproto.markdown
Labels: new-integration, cla-signed, next, has-parent, parent-merged

#22406 2022.5: Beta release notes
  CODEOWNERS
  _config.yml
  source/_integrations/airly.markdown
  source/_integrations/alpha_vantage.markdown
  source/_integrations/arest.markdown
  source/_integrations/bitcoin.markdown
  source/_integrations/calendar.markdown
  source/_integrations/camera.markdown
  source/_integrations/dweet.markdown
  source/_integrations/flock.markdown
  source/_integrations/fritz.markdown
  source/_integrations/fritzbox_callmonitor.markdown
  source/_integrations/gios.markdown
  source/_integrations/gitter.markdown
  source/_integrations/glances.markdown
  source/_integrations/influxdb.markdown
  source/_integrations/insteon.markdown
  source/_integrations/intellifire.markdown
  source/_integrations/knx.markdown
  source/_integrations/lifx.markdown
  source/_integrations/meater.markdown
  source/_integrations/mpd.markdown
  source/_integrations/no_ip.markdown
  source/_integrations/onvif.markdown
  source/_integrations/pi_hole.markdown
  source/_integrations/pvoutput.markdown
  source/_integrations/sabnzbd.markdown
  source/_integrations/sensibo.markdown
  source/_integrations/senz.markdown
  source/_integrations/slimproto.markdown
  source/_integrations/smtp.markdown
  source/_integrations/squeezebox.markdown
  source/_integrations/steam_online.markdown
  source/_integrations/syslog.markdown
  source/_integrations/tplink.markdown
  source/_integrations/tractive.markdown
  source/_integrations/tradfri.markdown
  source/_integrations/tuya.markdown
  source/_integrations/version.markdown
  source/_integrations/vicare.markdown
  source/_integrations/xiaomi_miio.markdown
  source/_integrations/yamaha_musiccast.markdown
  source/_integrations/zha.markdown
  source/_integrations/zwave_js.markdown
  source/_posts/2022-05-04-release-20225.markdown
  source/changelogs/core-2022.5.markdown
  source/images/blog/2022-05/configuration-menu.png
  source/images/blog/2022-05/entity-finder.png
  source/images/blog/2022-05/social.png
Labels: cla-signed, blog, in-progress, needs-rebase, rc

#22545 Add line to remind about server control change
  source/_posts/2022-05-04-release-20225.markdown
Labels: cla-signed, in-progress, needs-rebase, rc

#22550 Add documenation for m hotkey
  source/_docs/tools/quick-bar.markdown
Labels: cla-signed, next, has-parent

#22555 MotionBlinds add Gaviota to supported brands
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, current

#22557 Rename hangouts to chat
  source/_integrations/hangouts.markdown
Labels: cla-signed, current

#22564 Rename hangouts to chat
  source/_integrations/hangouts.markdown
Labels: cla-signed, current

#22556 Update MQTT light documentation
  source/_integrations/light.mqtt.markdown
Labels: cla-signed, current

#22560 Update number of integrations
  source/_includes/custom/welcome.html
Labels: cla-signed, current

#22561 Fix spelling
  source/_integrations/motion_blinds.markdown
Labels: cla-signed, current

#22568 Add zwave-js-server breaking change note
  source/_posts/2022-05-04-release-20225.markdown
Labels: cla-signed, in-progress, has-parent, needs-rebase, rc

#22570 Link to app.js releases from Nabu Casa
  source/_integrations/google_assistant.markdown
  source/assets/integrations/google_assistant/app.js
Labels: cla-signed, current

#22576 Blog Post for CN
  source/_posts/2022-04-30-creator-network-launched.markdown
  source/images/blog/2022-04-30-creator-network/CreatorNetwork_social.jpg
  source/images/blog/2022-04-30-creator-network/Creators.jpg
Labels: cla-signed, current

#22572 Sabnzbd config flow documentation
  source/_integrations/sabnzbd.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22573 Correct button name
  source/_integrations/bmw_connected_drive.markdown
Labels: cla-signed, current
