Repository home-assistant/home-assistant.io, pull requests merged in 2022-06, with the labels that each got.

#22939 Explain limitation of multiple !include on top level
  source/_docs/configuration/splitting_configuration.markdown
Labels: cla-signed, current

#22938 Add use wallclock as timestamps option for onvif
  source/_integrations/onvif.markdown
Labels: cla-signed, next, has-parent

#22945 Fix "Template filter/function defaults" examples in 2022.6 release notes
  source/_posts/2022-06-01-release-20226.markdown
Labels: cla-signed, current

#22958 Improve MQTT siren documentation
  source/_integrations/siren.mqtt.markdown
Labels: cla-signed, current

#22960 2022.6: Update release party, fix MQTT example
  source/_posts/2022-06-01-release-20226.markdown
Labels: cla-signed, current

#22912 Increase number of integrations.
  source/help/talking-points.markdown
Labels: cla-signed, current

#22948 Updates Conrad ESP32-C3 link to international site
  source/_posts/2022-05-29-matter-in-home-assistant-workshop-announcement.markdown
Labels: cla-signed, current

#22494 Config flow for Scrape integration
  source/_integrations/scrape.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#22964 Update doc add vibration sensor
  source/_integrations/yolink.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22944 Add powerview supported shade information
  source/_integrations/hunterdouglas_powerview.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22994 Fix spelling on unifi_direct
  source/_integrations/unifi_direct.markdown
Labels: cla-signed, current

#22954 Add config flow to radiotherm
  source/_integrations/radiotherm.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22997 Add yolink lock support
  source/_integrations/yolink.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23006 Update URLs
  source/_integrations/zha.markdown
Labels: cla-signed, current

#23005 Jellyfin: add support for movie collections
  source/_integrations/jellyfin.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase

#23021 Revert "Create documentation for iAlarmXR device support (#22009)"
  CODEOWNERS
  source/_integrations/ialarm.markdown
  source/_integrations/ialarm_xr.markdown
Labels: cla-signed, next, has-parent

#23000 Reduce image size
  source/getting-started/automation.markdown
  source/images/blog/2022-05-matter-in-home-assistant-workshop-announcement/social.png
  source/images/docs/quick-bar/disable-shortcuts-toggle.png
  source/images/getting-started/automation-editor.png
  source/images/integrations/homekit_controller/device_automation_finish.png
  source/images/integrations/homekit_controller/device_automation_new.png
  source/images/screenshots/button_classes_icons.png
Labels: cla-signed, current

#23015 Broken link to 'SmartMeter Webshop' removed
  source/_integrations/dsmr.markdown
Labels: cla-signed, current

#22991 Local sync is now enabled by #21491
  source/_integrations/google_assistant.markdown
Labels: cla-signed, current

#22998 URL Update
  README.md
  source/_docs/mqtt/broker.markdown
Labels: cla-signed, current

#22999 Remove unnecessary brackets
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed, current

#22989 Add T3950 to Venstar devices
  source/_integrations/venstar.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#22749 Update documentation for System Bridge 3.x.x
  source/_integrations/system_bridge.markdown
Labels: cla-signed, next, has-parent, parent-merged

#22988 Update Sensibo for more sensors
  source/_integrations/sensibo.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23032 More URL Updates
  source/_posts/2016-07-28-esp8266-and-micropython-part1.markdown
  source/_posts/2016-08-31-esp8266-and-micropython-part2.markdown
  source/_posts/2018-06-04-esphomelib.markdown
  source/_posts/2021-01-23-security-disclosure2.markdown
  source/_posts/2021-05-12-integrations-api.markdown
Labels: cla-signed, current

#23010 Update radiotherm for hold mode switch
  source/_integrations/radiotherm.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23034 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: cla-signed, current

#23035 More URL Updates
  source/_posts/2016-07-19-visualizing-your-iot-data.markdown
  source/_posts/2016-07-23-internet-of-things-data-exploration-with-jupyter-notebooks.markdown
  source/_posts/2016-08-19-github-style-calendar-heatmap-of-device-data.markdown
  source/_posts/2017-11-29-hassio-virtual-machine.markdown
Labels: cla-signed, current

#23038 Matter Workshop: Mention support of 64-bit versions only
  source/_posts/2022-05-29-matter-in-home-assistant-workshop-announcement.markdown
Labels: cla-signed, current

#23036 Update yolink device support
  source/_integrations/yolink.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23041 Add warning about 700 series controllers
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, current

#22841 Add note to Steam regarding friends list privacy
  source/_integrations/steam_online.markdown
  source/images/screenshots/steam_privacy_settings.png
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#23044 Update application credentials documentation for remaining integrations
  source/_integrations/home_connect.markdown
  source/_integrations/lyric.markdown
  source/_integrations/neato.markdown
  source/_integrations/withings.markdown
Labels: cla-signed, current

#23042 Adds docs on UniFi Protect tamper sensor
  source/_integrations/unifiprotect.markdown
Labels: cla-signed, next, has-parent

#23055 Add buttons to powerview
  source/_integrations/hunterdouglas_powerview.markdown
Labels: cla-signed, next, has-parent

#23057 Add powerview update entity information
  source/_integrations/hunterdouglas_powerview.markdown
Labels: cla-signed, next, has-parent

#23058 Update core upgrade instructions
  source/_includes/common-tasks/beta_version.md
  source/_includes/common-tasks/development_version.md
  source/_includes/common-tasks/specific_version.md
  source/_includes/common-tasks/update.md
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#23056 Reduce image size
  source/images/addons/addon-store.png
  source/images/blog/2021-12-stanford-genie/social.png
  source/images/blog/2022-02-android/Companion.png
  source/images/blog/2022-04-for-insteon-users/insteon-panel-1.jpg
  source/images/blog/2022-04-for-insteon-users/insteon-panel-2.jpg
  source/images/dashboards/lovelace_gauge_segments.png
  source/images/energy/cost.png
  source/images/getting-started/integrations.png
  source/images/getting-started/lovelace.png
  source/images/getting-started/username.png
  source/images/hassio/screenshots/adding_repositories.png
  source/images/hassio/screenshots/dashboard.png
  source/images/hassio/screenshots/exit-shell.png
  source/images/installation/etcher1.png
  source/images/installation/etcher2.png
  source/images/installation/etcher3.png
  source/images/installation/etcher4.png
  source/images/installation/etcher5.png
  source/images/installation/etcher6.png
  source/images/installation/intel-nuc-disable-secure-boot.jpg
  source/images/installation/intel-nuc-enter-bios.jpg
  source/images/installation/intel-nuc-uefi-boot.jpg
  source/images/supported_brands/arris.jpg
  source/images/supported_brands/bsblan.png
  source/images/supported_brands/environment_agency.jpg
  source/images/supported_brands/matter.png
  source/images/supported_brands/numato.png
  source/images/supported_brands/wiffi.png
Labels: cla-signed, current

#22990 add VeSync voltage and yearly, weekly, montly energy sensors
  source/_integrations/vesync.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23060 Remove broken Z-Wave plus link & text
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, current

#22925 Update octoprint.markdown
  source/_integrations/octoprint.markdown
Labels: cla-signed, in-progress, current

#23040 improving the documentation for Buienradar condition codes
  source/_integrations/buienradar.markdown
Labels: cla-signed, in-progress, current

#22883 Deprecate google calendar add_event service, replaced with create_event
  source/_integrations/google.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23062 Added next models
  source/_integrations/epsonworkforce.markdown
Labels: cla-signed, current

#23067 Add power monitoring sensors to WiZ
  source/_integrations/wiz.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23064 Adjust dlink platform example to use a list
  source/_integrations/dlink.markdown
Labels: cla-signed, current

#23047 Add yolink Thermostat support
  source/_integrations/yolink.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23072 Clarify Plex client compatibility
  source/_integrations/plex.markdown
Labels: cla-signed, current

#23070 Update links to zone trigger and zone condition
  source/_integrations/zone.markdown
Labels: cla-signed, current

#22956 Update eight_sleep docs for config flow
  source/_integrations/eight_sleep.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23080 Update tank_utility.markdown
  source/_integrations/tank_utility.markdown
Labels: cla-signed, current

#23082 Clarified manual polling disable instructions
  source/_integrations/waze_travel_time.markdown
Labels: cla-signed, current

#23028 Update Aladdin Connect for Config Flow
  source/_integrations/aladdin_connect.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#23087 Enable tdbushades powerview
  source/_integrations/hunterdouglas_powerview.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23081 Update tank_utility.markdown
  source/_integrations/tank_utility.markdown
Labels: cla-signed, in-progress, current

#18108 Add documentation for Skybell config flow
  source/_integrations/skybell.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#23090 Update daikin.markdown
  source/_integrations/daikin.markdown
Labels: cla-signed, current

#23093 Update pushover.markdown
  source/_integrations/pushover.markdown
Labels: cla-signed, current

#23110 Add a link to my DSMR project pgae
  source/_integrations/dsmr.markdown
Labels: cla-signed, current

#23113 Update threshold.markdown
  source/_integrations/threshold.markdown
Labels: cla-signed, current

#23115 Document `device_class` option for MQTT number
  source/_integrations/number.mqtt.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#23132 Update timer help - minor menu typo/update
  source/_integrations/timer.markdown
Labels: cla-signed, current

#23097 Clarify which credentials are needed for the Envisalink configuration
  source/_integrations/envisalink.markdown
Labels: cla-signed, current

#23131 Update yeelight.markdown
  source/_integrations/yeelight.markdown
Labels: cla-signed, current

#23134 Reduce image size
  source/images/docs/automation-editor/create-automation.png
  source/images/docs/automation-editor/new-action.png
  source/images/docs/automation-editor/new-automation.png
  source/images/docs/automation-editor/new-trigger.png
  source/images/faq/faq_no_unique_id.jpg
  source/images/getting-started/automation-editor.png
  source/images/screenshots/agent_dvr.jpg
  source/images/screenshots/panel_config_info.png
  source/images/screenshots/steam_privacy_settings.png
Labels: cla-signed, current

#23013 Add custom service Pure Boost
  source/_integrations/sensibo.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23139 Add timer to sensibo
  source/_integrations/sensibo.markdown
Labels: cla-signed, next, has-parent

#23141 add uuid to auto generated zone
  source/_integrations/owntracks.markdown
Labels: cla-signed, current

#23140 Reduce image size
  source/images/integrations/brother/brother-printer-webui.png
  source/images/integrations/calendar/trigger.png
  source/images/integrations/geocaching/geocaching_authorized_developer.png
  source/images/integrations/google/device_connected.png
  source/images/integrations/google/enter_code.png
  source/images/integrations/google/link_account.png
  source/images/integrations/google/success.png
  source/images/integrations/group/Group_members.png
  source/images/integrations/group/Group_settings.png
  source/images/integrations/xbox/xbox_picture_entity.png
Labels: cla-signed, current

#23143 docs: Fix missing tailing quote
  source/_integrations/cast.markdown
Labels: cla-signed, current

#23142 remove reference to share option
  source/_integrations/owntracks.markdown
Labels: cla-signed, current

#23125 Clarify group behavior
  source/_integrations/group.markdown
Labels: cla-signed, current

#23111 Remove Somfy documentation
  CODEOWNERS
  source/_integrations/somfy.markdown
  source/_redirects
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#23145 Adjust icon for panel iframe example
  source/_integrations/rachio.markdown
Labels: cla-signed, current

#23120 Add state based template select example
  source/_integrations/template.markdown
Labels: cla-signed, current

#22967 Fixing some inaccuracies on unpack() filter
  source/_docs/configuration/templating.markdown
Labels: cla-signed, current

#23083 Add note reloading MQTT device_tracker not supported
  source/_integrations/device_tracker.mqtt.markdown
Labels: cla-signed, current

#23149 Improved the documentation of the tools to read the prof and the call…
  source/_integrations/profiler.markdown
Labels: cla-signed, current

#22915 Fix typo in title attribute
  source/_integrations/myq.markdown
Labels: cla-needed, current

#22628 Add documentation for installation on older BIOS's which don't detect…
  source/_includes/installation/operating_system.md
Labels: cla-signed, in-progress, current, has-parent, needs-rebase

#23043 Document new RESTful sensor configuration options
  source/_integrations/sensor.rest.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23138 Add filter and service to Sensibo
  source/_integrations/sensibo.markdown
Labels: cla-signed, awaits-parent, next, has-parent, parent-merged

#23167 Fixed dead links
  source/_integrations/soma.markdown
Labels: cla-signed, current

#23169 Base_URL is deprecated
  source/_integrations/tts.markdown
Labels: cla-signed, current

#23171 Clarify `announce` and `enqueue` is ignored if not supported by targeted media_player
  source/_integrations/media_player.markdown
Labels: cla-signed, current

#23170 Cgroup adjustment
  source/more-info/unsupported/docker_configuration.markdown
Labels: cla-signed, current

#23172 Update of information on Z-Wave.Me hardware and integrations
  source/_docs/z-wave/controllers.markdown
Labels: cla-signed, in-progress, current

#23176 Sensibo custom service to switch for Pure Boost
  source/_integrations/sensibo.markdown
Labels: cla-signed, next, has-parent

#23188 Update note for newer bridge firmware versions
  source/_integrations/comfoconnect.markdown
Labels: cla-needed, current

#23192 Remove config check addon from guide
  source/_includes/common-tasks/update.md
Labels: cla-signed, current, has-parent

#23175 Add config flow to simplepush documentation
  source/_integrations/simplepush.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23203 Add serial to type, solve issue 23201
  source/_integrations/modbus.markdown
Labels: cla-signed, current

#23210 Add note of support for TP-Link KP125 plug
  source/_integrations/tplink.markdown
Labels: cla-signed, current

#23216 Correct group behavior documentation
  source/_integrations/group.markdown
Labels: cla-signed, current

#22879 Add this variable to trigger-based templates
  source/_integrations/template.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23218 Add units to weather template
  source/_integrations/weather.template.markdown
Labels: cla-signed, next, has-parent, parent-merged

#23196 Describe additional Sonos surround features
  source/_integrations/sonos.markdown
Labels: cla-signed, next, has-parent

#22629 Update sample .yaml to give noobs (like me) an easier starting point
  source/_integrations/systemmonitor.markdown
Labels: cla-signed, in-progress, current

#22922 Hive update docs to reflect mandatory 2FA now required
  source/_integrations/hive.markdown
Labels: cla-signed, current

#22932 Revised Synology NAS Docker install instructions to align with the current workflow in DSM
  source/_includes/installation/container/alternative.md
Labels: cla-signed, current

#22320 Updates Fronius docs adding consumption path
  source/_integrations/fronius.markdown
Labels: cla-signed, in-progress, current

#23144 Extend working models for Aruba
  source/_integrations/aruba.markdown
Labels: cla-signed, current

#23217 Document changed group behavior when members are unavailable or unknown
  source/_integrations/group.markdown
Labels: cla-signed, in-progress, next, needs-rebase

#23185 Document that trigger.idx starts at 0
  source/_docs/automation/templating.markdown
Labels: cla-signed, current

#23226 Add limitations to cloudflare integration docs
  source/_integrations/cloudflare.markdown
Labels: cla-signed, current

#23224 The LIFX integration depends on the network config being correct
  source/_integrations/lifx.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#23168 chore: Set permissions for GitHub actions
  .github/workflows/lock.yml
  .github/workflows/stale.yml
Labels: cla-signed, in-progress, current

#22908 Add Support for Session Ended Requests
  source/_integrations/alexa.intent.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#22526 Update zha.markdown about Diagnostics information
  source/_integrations/zha.markdown
Labels: cla-signed, in-progress, current, has-parent, needs-rebase, parent-merged

#23220 Update recorder.markdown
  source/_integrations/recorder.markdown
Labels: cla-signed, in-progress, current

#22410 Restructure Discord.markdown to clarify process
  source/_integrations/discord.markdown
Labels: cla-signed, current

#22427 Detail the event data for folder_watcher
  source/_integrations/folder_watcher.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent

#23117 Document new configuration options for SNMP sensor
  source/_integrations/snmp.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#23183 Update docs to allow username and password for stream URLs via the UI for generic 2
  source/_integrations/generic.markdown
Labels: cla-signed, next, has-parent

#22911 Add Netgear Utilization sensors
  source/_integrations/netgear.markdown
Labels: cla-signed, next, has-parent

#22874 Netgear add update entity
  source/_integrations/netgear.markdown
Labels: cla-signed, next, has-parent

#22902 Add Netgear ethernet link status info
  source/_integrations/netgear.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#23223 Adjust filtering to make includes stronger than excludes
  source/_includes/common-tasks/filters.md
Labels: cla-signed, next, has-parent, parent-merged

#21422 Add number platform for kostal plenticore
  source/_integrations/kostal_plenticore.markdown
Labels: new-feature, cla-signed, awaits-parent, next, has-parent, parent-merged

#22709 Anywair support in IntesisHome
  source/_integrations/intesishome.markdown
Labels: cla-signed, in-progress, next, has-parent, needs-rebase, parent-merged

#23221 Document `int` and `boolean` template filters
  source/_docs/configuration/templating.markdown
Labels: cla-signed, next, has-parent, parent-merged

#20098 Add HomeConnect services documentation
  source/_integrations/home_connect.markdown
Labels: Hacktoberfest, new-feature, cla-signed, next, has-parent, hacktoberfest-accepted

#23199 Add Redirects for About Page
  source/_redirects
Labels: cla-signed, awaits-parent, in-progress, current, has-parent, needs-rebase

#22873 Added tip that RouterOS uses ping
  source/_integrations/mikrotik.markdown
Labels: cla-signed, current

#23096 Update alexa.smart_home.markdown with up to date information
  source/_integrations/alexa.smart_home.markdown
Labels: cla-signed, current

#21969 Document new options for triggering Alexa routines
  source/_integrations/alexa.smart_home.markdown
  source/images/integrations/alexa/alexa_app_button_trigger.png
  source/images/integrations/alexa/alexa_app_switch_trigger.png
Labels: new-feature, cla-signed, next, has-parent

#23075 Add boot time sensor for System Bridge
  source/_integrations/system_bridge.markdown
Labels: cla-signed, next, has-parent

#22148 Documentation: telegram_bot.send_poll
  source/_integrations/telegram_bot.markdown
Labels: new-feature, cla-signed, awaits-parent, in-progress, next, has-parent

#22959 2022.7: Beta release notes
  _config.yml
  source/_posts/2022-07-06-release-20227.markdown
  source/changelogs/core-2022.7.markdown
  source/images/blog/2022-07/social.png
Labels: cla-signed, blog, in-progress, needs-rebase, rc

#23238 Mention additional new Sonos controls in 2022.7 release notes
  source/_posts/2022-07-06-release-20227.markdown
Labels: cla-signed, in-progress, has-parent, needs-rebase, rc

#23239 Remove Linux capabilities section
  source/_integrations/nmap_tracker.markdown
Labels: cla-signed, current

#23206 Add documentation of selecting source for Spotify
  source/_integrations/spotify.markdown
Labels: cla-signed, current

#23240 Replace wrong link, remove broken links in fritzbox docs
  source/_integrations/fritzbox.markdown
Labels: cla-signed, current

#22598 Add config_flow details to LG soundbar
  source/_integrations/discovery.markdown
  source/_integrations/lg_soundbar.markdown
Labels: cla-signed, next, has-parent

#22372 Add Matrix HTML format message documentation
  source/_integrations/matrix.markdown
Labels: new-feature, cla-signed, next, has-parent

#22799 Add presence detection to devolo_home_network
  source/_integrations/devolo_home_network.markdown
Labels: new-feature, cla-signed, next, has-parent

#23242 Add vacation mode to template alarm control panel
  source/_integrations/alarm_control_panel.template.markdown
Labels: cla-signed, awaits-parent, next, has-parent

#23198 Include virt-install OS installation instructions
  source/_includes/installation/operating_system.md
Labels: cla-signed, current
