Repository home-assistant/home-assistant.io, pull requests merged in 2023-01, with the labels that each got.

#25496 Show CLA error
  source/developers/cla_sign.html
Labels: current

#25486 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#25483 Add links to the support documentation.
  source/_integrations/google_domains.markdown
Labels: current

#25482 Update freebox url
  source/_integrations/freebox.markdown
Labels: current

#25448 Add optimistic config option for MQTT climate
  source/_integrations/climate.mqtt.markdown
Labels: awaits-parent, next, has-parent, by-code-owner, integration: mqtt

#25421 Updated SwitchBot documentation to include details about the lock
  source/_integrations/switchbot.markdown
Labels: next, has-parent, parent-merged

#25476 Update ambient_station.markdown to include notes about built in Ecowitt integration.
  source/_integrations/ambient_station.markdown
Labels: current

#25508 Add TDBU information
  source/_integrations/motion_blinds.markdown
Labels: current

#25507 Statistics: add notice on max_age - closes #25506
  source/_integrations/statistics.markdown
Labels: in-progress, current

#25511 Update Leviton Decora URLs
  source/_integrations/decora_wifi.markdown
Labels: current

#25514 Update ISY994 documentation to be model agnostic
  .textlintrc.json
  source/_integrations/isy994.markdown
  source/_integrations/ssdp.markdown
Labels: next, has-parent, parent-merged

#25504 Mqtt light command templates
  source/_integrations/light.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: next, parent-merged, integration: mqtt

#25524 improve the comment of the 'for' usage in the state conditions
  source/_docs/scripts/conditions.markdown
Labels: current

#25525 Fix CURL command in WattTime docs
  source/_integrations/watttime.markdown
Labels: current

#25432 Add snooz transition services
  source/_integrations/snooz.markdown
Labels: in-progress, next, has-parent

#25472 Added documentation for Zeversolar
  source/_integrations/zeversolar.markdown
Labels: awaits-parent, next, has-parent

#25437 Add docs for energyzero integration
  source/_integrations/energyzero.markdown
Labels: new-integration, awaits-parent, next, has-parent

#25530 Clarify how to set up a private broker with TLS
  source/_integrations/mqtt.markdown
Labels: current

#25531 Update qnap.markdown
  source/_integrations/qnap.markdown
Labels: current

#25536 Update fritzsmarthome link
  source/_integrations/fritzbox.markdown
Labels: current

#25528 Add docs for ANWB Energie integration
  source/_integrations/anwb_energie.markdown
Labels: new-integration, awaits-parent, next, has-parent

#25538 Guide setting MQTT broker verification using UI
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#25537 Update bsblan URLs
  source/_integrations/bsblan.markdown
Labels: current

#25533 Drop eagle-200 recommendation for electricity monitoring
  source/_docs/energy/electricity-grid.markdown
Labels: current

#25480 Docs for new Ruuvi Gateway integration
  source/_integrations/ruuvi_gateway.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#25541 Change wording for SkyConnect page
  source/skyconnect/index.html
Labels: current

#25554 Update default_config.markdown
  source/_integrations/default_config.markdown
Labels: current

#25556 Use valid zone numbers in sample configuration
  source/_integrations/envisalink.markdown
Labels: current

#25555 Remove unnecessary step from setup instructions
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#25548 Update image_upload.markdown
  source/_integrations/image_upload.markdown
Labels: current

#25558 Add RLC-823A to tested devices
  source/_integrations/reolink.markdown
Labels: current

#25551 Add E1 Zoom to tested models
  source/_integrations/reolink.markdown
Labels: current

#25559 Added error 500
  source/_integrations/google_assistant.markdown
Labels: current

#25549 Add docs for Mijndomein Energie integration
  source/_integrations/mijndomein_energie.markdown
Labels: new-integration, awaits-parent, next, has-parent

#25545 Adding third party tools
  source/_integrations/mqtt.markdown
Labels: current

#25542 Add HomeWizard P1 meter to Identify and Cloud communication
  source/_integrations/homewizard.markdown
Labels: next, has-parent

#25264 Add LD2410 BLE integration
  CODEOWNERS
  source/_integrations/ld2410_ble.markdown
Labels: next, has-parent

#25589 2023.1.1
  _config.yml
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25594 Update econet URL
  source/_integrations/econet.markdown
Labels: current

#25587 Update CityBikes documentation
  source/_integrations/citybikes.markdown
Labels: current

#25584 Update alexa.smart_home.markdown
  source/_integrations/alexa.smart_home.markdown
Labels: current

#25596 Fix switchbot hub URL
  source/_integrations/switchbot.markdown
Labels: current

#25595 Add E1 Pro and E1 Outdoor to tested models
  source/_integrations/reolink.markdown
Labels: current

#25597 Netgear add notes about speedtest data usage
  source/_integrations/netgear.markdown
Labels: current, has-parent

#25581 Google assistant sdk
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#25339 Update derivative.markdown
  source/_integrations/derivative.markdown
Labels: current

#25600 fix isuues > discussions link for intents repo
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25613 Fixed python_script minor typo
  source/_integrations/python_script.markdown
Labels: current

#25602 Update derivative.markdown
  source/_integrations/derivative.markdown
Labels: current

#25608 Remove E1 Pro from supported
  source/_integrations/reolink.markdown
Labels: current

#25601 Include RLC-810A in working models
  source/_integrations/reolink.markdown
Labels: current

#25623 Make api key mandatory for PI-hole
  source/_integrations/pi_hole.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25557 yalexs_ble: Mention Support For Yale Unity Screen Door Lock
  source/_integrations/yalexs_ble.markdown
Labels: current

#25582 Docs: Integration reolink tested RLC-820A
  source/_integrations/reolink.markdown
Labels: current

#25603 Update bayesian.markdown
  source/_integrations/bayesian.markdown
Labels: current

#23993 Add documentation for Starlink
  source/_integrations/starlink.markdown
Labels: new-integration, cla-signed, awaits-parent, next, has-parent

#25621 Document QNAP QSW port sensors
  source/_integrations/qnap_qsw.markdown
Labels: awaits-parent, next, has-parent

#25529 Clarify exactly how to get the API key for ViCare
  source/_integrations/vicare.markdown
Labels: current

#25633 Add "sensor" platform to Nuki
  source/_integrations/nuki.markdown
Labels: next, has-parent, parent-merged

#25567 Add reported working cameras to Reolink documentation
  source/_integrations/reolink.markdown
Labels: current, integration: reolink

#25654 2023.1.2
  _config.yml
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25640 Add network resource button entities to ISY994
  source/_integrations/isy994.markdown
Labels: next, has-parent

#25569 Document Airzone Select platform
  source/_integrations/airzone.markdown
Labels: next, has-parent, parent-merged

#25655 Changed SCAN_INTERVAL and note about rate limiting
  source/_integrations/hydrawise.markdown
Labels: current

#25565 Update power factor sensor units
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: awaits-parent, in-progress, current, has-parent, parent-merged

#25413 MQTT Climate: Add documentation for receiving the current humidity
  source/_integrations/climate.mqtt.markdown
Labels: next, has-parent, parent-merged

#24293 Add back yaml support
  source/_integrations/sql.markdown
Labels: in-progress, next, has-parent, parent-merged

#25042 Add docs for Google Mail
  source/_integrations/google_mail.markdown
Labels: in-progress, next, has-parent, parent-merged

#25609 Add query button entities to ISY994 devices and hub
  source/_integrations/isy994.markdown
Labels: in-progress, next, has-parent, parent-merged

#25642 Add 'select' (and more) to the list of demos
  source/_integrations/demo.markdown
Labels: current

#25656 Add config flow to IMAP integration
  source/_integrations/imap.markdown
Labels: next, has-parent, parent-merged

#25659 Add reported Reolink cameras
  source/_integrations/reolink.markdown
Labels: current

#25662 Reolink admin needed
  source/_integrations/reolink.markdown
Labels: current

#25616 Add docs for the ReCollect Waste calendar entity
  source/_integrations/recollect_waste.markdown
Labels: next, has-parent, parent-merged

#25673 Correct Reolink model list
  source/_integrations/reolink.markdown
Labels: current

#22886 Add switch platform to devolo_home_network
  source/_integrations/devolo_home_network.markdown
Labels: cla-signed, next, has-parent, parent-merged

#25672 Reolink add support for FLV protocol
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent

#24574 Intellifire lights
  source/_integrations/intellifire.markdown
Labels: Hacktoberfest, new-feature, next, has-parent, parent-merged, hacktoberfest-accepted

#25468 Add TFA Dostmann LaCrosse sensors as tested device
  source/_integrations/lacrosse.markdown
Labels: current

#25501 Fix button name for restarting system
  source/more-info/unhealthy/setup.markdown
Labels: current

#25523 Adjust working in Proximity documentation
  source/_integrations/proximity.markdown
Labels: current

#25677 Add documentation for kitchen_sink
  source/_integrations/kitchen_sink.markdown
Labels: awaits-parent, in-progress, next, has-parent

#25690 2023.1.3
  _config.yml
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25650 Add ISY994 variables as number entities
  source/_integrations/isy994.markdown
Labels: awaits-parent, next, has-parent

#25637 Update Starlink documentation for new binary_sensor platform
  source/_integrations/starlink.markdown
Labels: awaits-parent, next, has-parent

#25704 Add docs for Energie VanOns integration
  source/_integrations/energie_vanons.markdown
Labels: new-integration, next, has-parent, parent-merged

#25658 Add binary_sensor platform to SFR Box
  source/_integrations/sfr_box.markdown
Labels: awaits-parent, next, has-parent

#25575 Deprecate power_command_topic for MQTT climate
  source/_integrations/climate.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, by-code-owner, integration: mqtt

#25722 Remove 32 bits from guides
  _config.yml
Labels: current

#25485 D-Link config flow
  source/_integrations/dlink.markdown
Labels: next, has-parent, parent-merged

#25671 Add OpenUV docs that describe the 403/re-auth idiosyncrasy
  source/_integrations/openuv.markdown
Labels: in-progress, current, has-parent, parent-merged

#25705 Update KNX for xknx 2.3.0
  source/_integrations/knx.markdown
Labels: next, has-parent, parent-merged

#25657 Google Assistant SDK: Document conversation agent
  source/_integrations/google_assistant_sdk.markdown
  source/images/integrations/google_assistant_sdk/conversation.png
Labels: in-progress, next, has-parent, parent-merged

#25723 2023.1.4
  _config.yml
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25729 Update xiaomi_miio.markdown
  source/_integrations/xiaomi_miio.markdown
Labels: current

#25725 Add button platform to moehlenhoff alpha 2
  source/_integrations/moehlenhoff_alpha2.markdown
Labels: next, has-parent

#25734 Update ssdp URLs
  source/_integrations/ssdp.markdown
Labels: current

#25737 Added docs for ip command
  source/_integrations/systemmonitor.markdown
Labels: current

#25718 Remove manual configuration details from ISY994
  source/_integrations/isy994.markdown
Labels: next, has-parent, parent-merged

#25733 Update oralb sensor data and supported devices
  source/_integrations/oralb.markdown
Labels: awaits-parent, in-progress, next, has-parent

#25731 Remove deprecated "on_level" service from ISY994
  source/_integrations/isy994.markdown
Labels: awaits-parent, next, has-parent

#25756 Add DHCP in DLink docs
  source/_integrations/dlink.markdown
Labels: next, has-parent

#25754 Add Insteon ramp rate select entities to ISY994, deprecate service
  source/_integrations/isy994.markdown
Labels: next, has-parent

#25749 Update webOS TV ports
  source/_integrations/webostv.markdown
Labels: current

#25760 Fix modbus logging example
  source/_integrations/modbus.markdown
Labels: current

#25762 Add missing required IDs to issue form
  .github/ISSUE_TEMPLATE/feedback.yml
Labels: current

#25772 Don't use Accumulated sensors
  source/_integrations/iotawatt.markdown
Labels: current

#25766 Fix incorrect case in ZHA docs
  source/_integrations/zha.markdown
Labels: current

#25761 Deprecate ISY994 custom cleanup entities service
  source/_integrations/isy994.markdown
Labels: next, has-parent

#25728 Document locking and unlocking for MQTT lock
  source/_integrations/lock.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: next, has-parent, parent-merged

#25782 Comment on the offline key is misleading.
  source/_integrations/yalexs_ble.markdown
Labels: current

#25748 Update HERE travel time docs to link to current version
  source/_integrations/here_travel_time.markdown
Labels: current

#25604 Update sensor documentation for HomeWizard
  source/_integrations/homewizard.markdown
Labels: in-progress, next, has-parent, parent-merged

#25730 Add Bluetooth Adapters integration
  source/_integrations/bluetooth_adapters.markdown
Labels: next, has-parent, parent-merged

#25779 Update Reolink documentation to instruct users to update camera firmw…
  source/_integrations/reolink.markdown
Labels: current

#25759 Fixed transliteration of Kyiv to official Ukrainian version.
  source/developers/cla_sign.html
Labels: current

#25678 Correct Sensor units for duration and improve readability
  source/_integrations/sensor.markdown
Labels: current

#25698 Unify references to MQTT templating documentation
  source/_integrations/cover.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#25687 Add AQI rating template sensor example to the PurpleAir docs
  source/_integrations/purpleair.markdown
Labels: current

#22140 Add new documentation concerning icons
  source/_docs/frontend.markdown
  source/_docs/frontend/icons.markdown
  source/_includes/asides/docs_navigation.html
  source/images/frontend/mdi.png
  source/images/frontend/ui2022.png
  source/images/screenshots/icon-picker.png
  source/images/screenshots/mdi-picker.png
Labels: cla-signed, current

#25789 Update all mentions links to MDI with the updated URL
  source/_dashboards/markdown.markdown
  source/_docs/configuration/customizing-devices.markdown
  source/_docs/frontend.markdown
  source/_docs/frontend/icons.markdown
  source/_integrations/counter.markdown
  source/_integrations/panel_custom.markdown
  source/_integrations/timer.markdown
  source/_integrations/weather.markdown
  source/_integrations/zone.markdown
  source/_posts/2015-11-16-zwave-switches-lights-and-honeywell-thermostats-now-supported.markdown
  source/_posts/2017-04-08-eddystone-beacons--lockitron-locks--total-connect.markdown
  source/_posts/2019-02-06-release-87.markdown
  source/_posts/2020-07-01-release-113.markdown
  source/_posts/2020-09-17-release-115.markdown
  source/_posts/2021-10-06-release-202110.markdown
  source/_posts/2021-11-03-release-202111.markdown
  source/_posts/2022-04-06-release-20224.markdown
  source/_posts/2022-08-03-release-20228.markdown
  source/dashboards/badges.markdown
  source/dashboards/dashboards.markdown
  source/dashboards/header-footer.markdown
  source/dashboards/index.markdown
  source/dashboards/views.markdown
Labels: current

#24778 Added troubleshooting for 0 devices in home assistant
  source/_integrations/tuya.markdown
Labels: in-progress, current

#21556 Update documentation for how cards can be configured in the UI
  source/_dashboards/alarm-panel.markdown
  source/_dashboards/area.markdown
  source/_dashboards/button.markdown
  source/_dashboards/calendar.markdown
  source/_dashboards/conditional.markdown
  source/_dashboards/entities.markdown
  source/_dashboards/entity-filter.markdown
  source/_dashboards/entity.markdown
  source/_dashboards/gauge.markdown
  source/_dashboards/glance.markdown
  source/_dashboards/grid.markdown
  source/_dashboards/history-graph.markdown
  source/_dashboards/horizontal-stack.markdown
  source/_dashboards/humidifier.markdown
  source/_dashboards/iframe.markdown
  source/_dashboards/light.markdown
  source/_dashboards/logbook.markdown
  source/_dashboards/map.markdown
  source/_dashboards/markdown.markdown
  source/_dashboards/media-control.markdown
  source/_dashboards/picture-elements.markdown
  source/_dashboards/picture-entity.markdown
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
  source/_dashboards/plant-status.markdown
  source/_dashboards/sensor.markdown
  source/_dashboards/shopping-list.markdown
  source/_dashboards/statistics-graph.markdown
  source/_dashboards/thermostat.markdown
  source/_dashboards/vertical-stack.markdown
  source/_dashboards/weather-forecast.markdown
  source/dashboards/cards.markdown
Labels: cla-signed, current

#25787 Deprecate ISY994 custom reload service
  source/_integrations/isy994.markdown
Labels: awaits-parent, next, has-parent

#25716 Add docs for Fire TV (virtual) integration
  source/_integrations/fire_tv.markdown
Labels: awaits-parent, next, has-parent

#25786 Add Insteon backlight control support to ISY994
  source/_integrations/isy994.markdown
Labels: awaits-parent, next, has-parent

#25741 add another compatible model
  source/_integrations/ld2410_ble.markdown
Labels: in-progress, next, needs-rebase

#25719 Set onewire quality scale to gold
  source/_integrations/onewire.markdown
Labels: next, has-parent

#25685 Remove deprecated YAML manual config for PVPC Hourly Pricing
  source/_integrations/pvpc_hourly_pricing.markdown
Labels: next, has-parent

#25739 Remove firmware version requirement new HomeWizard features
  source/_integrations/homewizard.markdown
Labels: in-progress, next, needs-rebase

#25372 Update Venstar documentation with current schedule sensor
  source/_integrations/venstar.markdown
Labels: in-progress, next, has-parent, parent-merged

#25795 2023.1.5
  _config.yml
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25800 Remove deprecated Renault service
  source/_integrations/renault.markdown
Labels: awaits-parent, next, has-parent

#25720 Set renault quality scale to platinum
  source/_integrations/renault.markdown
Labels: awaits-parent, next, has-parent

#25803 Reolink: Add C1 Pro to tested models
  source/_integrations/reolink.markdown
Labels: current

#24343 Fix platform variables for device platform
  source/_docs/automation/templating.markdown
Labels: Hacktoberfest, Stale, in-progress, current, hacktoberfest-accepted

#25665 Removes OpenALPR Local integration
  source/_integrations/openalpr_local.markdown
  source/_redirects
Labels: next, has-parent, parent-merged

#25692 Add translation parameters on selector select
  source/_docs/blueprint/selectors.markdown
Labels: in-progress, next, has-parent, parent-merged

#25819 Update WiZ URL
  source/_integrations/wiz.markdown
Labels: current

#25813 Add "Browser restart" to fix possible issues
  source/_docs/frontend/browsers.markdown
Labels: current

#25814 Update shelly.markdown
  source/_integrations/shelly.markdown
Labels: current

#25822 Shelly unicast - remove model names and minimum firmware
  source/_integrations/shelly.markdown
Labels: current

#25825 Shelly - Move Bluetooth sesction to start
  source/_integrations/shelly.markdown
Labels: current

#25588 Add sensors to ld2410_ble
  source/_integrations/ld2410_ble.markdown
Labels: awaits-parent, next, has-parent

#25797 Rename Eufy integration to EufyHome
  source/_integrations/eufy.markdown
Labels: next, has-parent

#25796 Add documentation for Starlink Switch platform
  source/_integrations/starlink.markdown
Labels: awaits-parent, next, has-parent

#25844 Conversation custom sentences
  source/_integrations/conversation.markdown
  source/images/screenshots/voice-commands.png
Labels: current

#25848 2023.1.6
  _config.yml
  source/_posts/2023-01-04-release-20231.markdown
Labels: in-progress, current, has-parent, needs-rebase

#25852 Added 'Swiftfinder' to Known Working Devices list
  source/_integrations/ibeacon.markdown
Labels: current

#25864 Add an Australian distributor for SkyConnects
  source/skyconnect/index.html
Labels: current
