Repository home-assistant/home-assistant.io, pull requests merged in 2023-10, with the labels that each got.

#29079 Update imap.markdown
  source/_integrations/imap.markdown
Labels: Hacktoberfest, current

#29085 Nest Troubleshooting info for "No Access to Partner Information" Error Update nest.markdown
  source/_integrations/nest.markdown
Labels: Hacktoberfest, current

#29083 icon for command_line sensors
  source/_integrations/command_line.markdown
Labels: Hacktoberfest, next, has-parent

#29090 Typo in imap docs
  source/_integrations/imap.markdown
Labels: Hacktoberfest, current

#29094 resetting password via console: explain placeholders in command
  source/_docs/locked_out.md
Labels: Hacktoberfest, current

#29080 Fix Vallox profile name
  source/_integrations/vallox.markdown
Labels: Hacktoberfest, current

#29064 Replace service for CLA authorize
  source/developers/cla_sign.html
Labels: in-progress, current, has-parent

#29084 Fixed dead link to yr.no documentation
  source/_integrations/generic.markdown
Labels: Hacktoberfest, current

#29086 Update UPB docs to address feedback and to add Debugging section
  source/_integrations/upb.markdown
Labels: Hacktoberfest, current

#29088 Updated URL to HEOS website in docs
  source/_integrations/heos.markdown
Labels: Hacktoberfest, current

#29025 Add documentation for fitbit UI configuration flows
  source/_integrations/fitbit.markdown
Labels: next, has-parent, parent-merged

#29098 Update information about Shelly `update` platform
  source/_integrations/shelly.markdown
Labels: Hacktoberfest, current

#29105 Fixed dead links to Bitron Video USB Stick
  source/_integrations/zha.markdown
Labels: Hacktoberfest, current

#29106 Hue update
  source/_posts/2023-09-22-philips-hue-force-users-upload-data-to-cloud.markdown
Labels: Hacktoberfest, current

#29107 Updated Volvo On Call URL and name
  source/_integrations/volvooncall.markdown
Labels: Hacktoberfest, current

#29111 Update lyric.markdown instructions to add clarity
  source/_integrations/lyric.markdown
Labels: Hacktoberfest, current

#29113 Green page FAQ: update SkyConnect text
  source/green/index.html
Labels: Hacktoberfest, current

#29114 Green page: update SkyConnect marketing copy
  source/green/index.html
Labels: Hacktoberfest, current

#29115 Blog: update section on Green
  source/_posts/2023-09-17-home-assistant-green-your-entry-to-home-assistant.markdown
Labels: Hacktoberfest, current

#29119 Update styling of my badges
  sass/custom/_paulus.scss
Labels: Hacktoberfest, current

#29121 Fixed broken link pilight protocols doc
  source/_integrations/pilight.markdown
Labels: Hacktoberfest, current

#29122 Update select.markdown
  source/_integrations/select.markdown
Labels: Hacktoberfest, current

#29123 Corrected typo in URL to modbus specification doc
  source/_integrations/modbus.markdown
Labels: Hacktoberfest, current

#29124 Add Everything Smart, SmarterHome and Swiss Domotique to the Green distributors list
  source/green/index.html
Labels: Hacktoberfest, current

#29118 Update label mode option description for map card
  source/_dashboards/map.markdown
Labels: Hacktoberfest, in-progress, next, needs-rebase

#29127 Updated MGV website link
  source/_integrations/mvglive.markdown
Labels: Hacktoberfest, current

#29128 Fix link in locative.md
  source/_integrations/locative.md
Labels: Hacktoberfest, current

#29130 Removed dead URL to Plugwise Stretch
  source/_integrations/plugwise.markdown
Labels: Hacktoberfest, current

#29133 Fix link to notify service in webostv
  source/_integrations/webostv.markdown
Labels: Hacktoberfest, current

#29135 Fixed broken link to Keba manual
  source/_integrations/keba.markdown
Labels: Hacktoberfest, current

#29092 Adjust documentation for knx
  source/_integrations/knx.markdown
Labels: Hacktoberfest, current

#29131 Update reolink.markdown with extra troubleshooting
  source/_integrations/reolink.markdown
Labels: Hacktoberfest, current

#29109 Add notable change about zwave_js
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, in-progress, rc

#29102 RFLink: remove logo from header
  source/_integrations/binary_sensor.rflink.markdown
  source/_integrations/cover.rflink.markdown
  source/_integrations/light.rflink.markdown
  source/_integrations/sensor.rflink.markdown
  source/_integrations/switch.rflink.markdown
Labels: Hacktoberfest, current

#29103 Integrations pages: remove logo from header
  source/_integrations/bsblan.markdown
  source/_integrations/dsmr.markdown
  source/_integrations/enocean.markdown
  source/_integrations/numato.markdown
  source/_integrations/wiffi.markdown
Labels: Hacktoberfest, current

#29129 Building block integration: add text fragment source
  source/_includes/integrations/building_block_integration.md
Labels: Hacktoberfest, current

#29136 Fix wrong URL
  source/green/index.html
Labels: Hacktoberfest, current

#29140 Update sidebar.markdown
  source/_dashboards/sidebar.markdown
Labels: Hacktoberfest, current

#29137 Remove custom port limit for alexa account linking
  source/_integrations/alexa.smart_home.markdown
Labels: Hacktoberfest, current, by-code-owner, integration: alexa

#29138 Updated broken product links on Eufy page
  source/_integrations/eufylife_ble.markdown
Labels: Hacktoberfest, current

#28310 Add wake_word integration docs
  source/_integrations/wake_word.markdown
  source/_integrations/wyoming.markdown
Labels: next, has-parent, parent-merged

#29150 Installation overview page: remove link to onboarding
  source/installation/index.html
Labels: Hacktoberfest, current

#29149 Building block integration text fragment: update
  source/_includes/integrations/building_block_integration.md
Labels: Hacktoberfest, current

#29145 A-b entities: add info that integration is a building block for other…
  source/_integrations/air_quality.markdown
  source/_integrations/alarm_control_panel.markdown
  source/_integrations/binary_sensor.markdown
  source/_integrations/button.markdown
Labels: Hacktoberfest, current

#29152 c-entities
  source/_integrations/calendar.markdown
  source/_integrations/camera.markdown
  source/_integrations/climate.markdown
  source/_integrations/cover.markdown
Labels: Hacktoberfest, current

#29162 Fix extra space in post
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, current

#29160 Updated links to Oral B toothbrushes
  source/_integrations/oralb.markdown
Labels: Hacktoberfest, current

#29161 Add the setup detail that ViCare is required on the device
  source/_integrations/vicare.markdown
Labels: Hacktoberfest, current

#29171 Update Todoist settings page link to get the API token
  source/_integrations/todoist.markdown
Labels: Hacktoberfest, current

#29163 Update switchbot_cloud.markdown
  source/_integrations/switchbot_cloud.markdown
Labels: Hacktoberfest, current

#29172 Remove play on roku sections
  source/_integrations/roku.markdown
Labels: Hacktoberfest, current

#29174 Removed deprecated close_comm_on_error from snippets
  source/_integrations/modbus.markdown
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, in-progress, next, has-parent

#29177 Remove support for logo in frontmatter
  source/_includes/asides/component_navigation.html
  source/_integrations/gogogate2.markdown
  source/_integrations/lifx_cloud.markdown
  source/_integrations/nzbget.markdown
  source/integrations/index.html
Labels: Hacktoberfest, current

#29178 Updated OpenEnergyMonitor docs
  source/_integrations/oem.markdown
Labels: Hacktoberfest, current

#29182 Fix broken Link alexa.markdown - emulated_hue
  source/_integrations/alexa.markdown
Labels: Hacktoberfest, current

#29183 Fix broken link mqtt.markdown --> image.mqtt
  source/_integrations/mqtt.markdown
Labels: Hacktoberfest, current

#29185 Document more building block entities
  source/_integrations/scene.markdown
  source/_integrations/select.markdown
  source/_integrations/siren.markdown
  source/_integrations/stt.markdown
  source/_integrations/switch.markdown
  source/_integrations/text.markdown
  source/_integrations/time.markdown
  source/_integrations/tts.markdown
  source/_integrations/update.markdown
  source/_integrations/vacuum.markdown
  source/_integrations/wake_word.markdown
  source/_integrations/weather.markdown
Labels: Hacktoberfest, current

#29184 Fix broken links medcom_ble.markdown
  source/_integrations/medcom_ble.markdown
Labels: Hacktoberfest, current

#29190 Update daikin.markdown with note about local api support in BRP084Cxx firmware 2.8.0
  source/_integrations/daikin.markdown
Labels: Hacktoberfest, current

#29154 Onboarding page: add info on entering IP address
  source/getting-started/onboarding.markdown
Labels: Hacktoberfest, current

#29196 Add Ameridroid and m.nu to Yellow (Std) distributors
  source/yellow/index.html
Labels: Hacktoberfest, current

#29201 Add troubleshooting tips to WeatherKit docs
  source/_integrations/weatherkit.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#29195 Change OpenWeatherMap unit_of_measurement from mm to mm/h
  source/_integrations/openweathermap.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent

#29170 Add Twitch Breaking Change to 2023.10 Release Notes
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, current

#29197 Add support for Aranet2 devices
  source/_integrations/aranet.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent

#29204 Update ZHA docs to mention Home Assistant Yellow
  source/_integrations/zha.markdown
Labels: Hacktoberfest, current

#29206 Correct modbus spelling error.
  source/_integrations/modbus.markdown
Labels: Hacktoberfest, current

#29207 Add note regarding BT issues to Idasen Desk
  source/_integrations/idasen_desk.markdown
Labels: Hacktoberfest, current

#29208 Fix link in help/Trivia to Skyconnect
  source/help/trivia.markdown
Labels: Hacktoberfest, current

#28384 Add media player docs to System Bridge
  source/_integrations/system_bridge.markdown
Labels: next, has-parent

#29147 Add documentation for Eastron virtual integration
  source/_integrations/eastron.markdown
Labels: Hacktoberfest, in-progress, next, has-parent

#29081 Added VPN to remote access page
  source/_docs/configuration/remote.markdown
Labels: current

#29210 Add unique ID to the generic hygrostat component
  source/_integrations/generic_hygrostat.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent

#29213 2023.10.1
  _config.yml
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, current, has-parent

#29211 Move energy troubleshooting section to energy FAQ
  source/_docs/energy.markdown
  source/_docs/energy/faq.markdown
Labels: Hacktoberfest, current

#29219 Update twitch.markdown
  source/_integrations/twitch.markdown
Labels: Hacktoberfest, current

#29046 locked out - add steps to onboarding section
  source/_docs/locked_out.md
Labels: current

#29058 Remove extra key word
  source/_integrations/fully_kiosk.markdown
Labels: current

#29221 Add missing 2023.10.1 link to table of contents
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, current

#29151 Adds 'Python Scripts' documentation on using responses from services.
  source/_integrations/python_script.markdown
Labels: Hacktoberfest, current

#28682 Update statistics integration with mean_circular
  source/_integrations/statistics.markdown
Labels: awaits-parent, next, has-parent

#29224 Add note about conditional card always showing while editing dashboard
  source/_dashboards/conditional.markdown
Labels: Hacktoberfest, current

#29236 Switchbot Cloud: Fixing vocabulary
  source/_integrations/switchbot_cloud.markdown
Labels: Hacktoberfest, current

#29233 Update fibaro to include the event platform
  source/_integrations/fibaro.markdown
Labels: Hacktoberfest, awaits-parent, in-progress, next, has-parent

#29063 chore: updated list of supported products.
  source/_integrations/blebox.markdown
Labels: current

#29250 Add Cribl docs
  source/_integrations/cribl.markdown
Labels: Hacktoberfest, next, has-parent

#29254 nissan_leaf.markdown: Add two trailing full stops
  source/_integrations/nissan_leaf.markdown
Labels: Hacktoberfest, current

#29259 common-tasks/update.md: Fix docker compose command examples
  source/_includes/common-tasks/update.md
Labels: Hacktoberfest, current

#29258 ovo_energy.markdown: Mention only works in UK
  source/_integrations/ovo_energy.markdown
Labels: Hacktoberfest, current

#29260 supla.markdown: Add a couple of trailing full stops
  source/_integrations/supla.markdown
Labels: Hacktoberfest, current

#29255 Add max devices config to energy devices graph
  source/_dashboards/energy.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29261 supla.markdown: Fix access_token description
  source/_integrations/supla.markdown
Labels: Hacktoberfest, current

#29262 supla.markdown: Minor syntax tweak for bolding
  source/_integrations/supla.markdown
Labels: Hacktoberfest, current

#29276 bloomsky.markdown: Add Weather to ha_category
  source/_integrations/bloomsky.markdown
Labels: Hacktoberfest, current

#29275 docs_navigation.html: Add Home Assistant Green to Hardware
  source/_includes/asides/docs_navigation.html
Labels: Hacktoberfest, current

#29270 battery.markdown: Fix/update Shelly shop link
  source/_docs/energy/battery.markdown
Labels: Hacktoberfest, current

#29269 solar-panels.markdown: Fix/update Shelly shop link
  source/_docs/energy/solar-panels.markdown
Labels: Hacktoberfest, current

#29271 electricity-grid.markdown: Fix/update Shelly shop link
  source/_docs/energy/electricity-grid.markdown
Labels: Hacktoberfest, current

#29273 energy.markdown: Add missing "the"
  source/_docs/energy.markdown
Labels: Hacktoberfest, current

#29274 common_tasks_navigation.html: Fix missing </li>
  source/_includes/asides/common_tasks_navigation.html
Labels: Hacktoberfest, current

#29283 ld2410_ble.markdown: Update app download links
  source/_integrations/ld2410_ble.markdown
Labels: Hacktoberfest, current

#29277 builtin_sentences.markdown: Fix casing of GitHub
  source/voice_control/builtin_sentences.markdown
Labels: Hacktoberfest, current

#29287 Update HomeKit Device documentation
  source/_integrations/homekit_controller.markdown
Labels: Hacktoberfest, current

#29288 Update HomeKit Bridge documentation
  source/_integrations/homekit.markdown
Labels: Hacktoberfest, current

#29272 energy/faq.markdown: Remove "the" from link text
  source/_docs/energy/faq.markdown
Labels: Hacktoberfest, current

#29266 facebox.markdown: Minor editing
  source/_integrations/facebox.markdown
Labels: Hacktoberfest, current

#29050 Add documentation for support of Minecraft Server Bedrock Edition
  source/_integrations/minecraft_server.markdown
Labels: awaits-parent, next, has-parent

#29290 Update jewish_calendar docs about diapora setting
  source/_integrations/jewish_calendar.markdown
Labels: Hacktoberfest, current

#29292 myq.markdown: Update HomeKit names
  source/_integrations/myq.markdown
Labels: Hacktoberfest, current

#29293 openweathermap.markdown: Fix parsing of markdown in HTML tags
  source/_integrations/openweathermap.markdown
Labels: Hacktoberfest, current

#29263 supla.markdown: Copyediting and updates
  source/_integrations/supla.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#29294 Update HomeKit docs for reload support
  source/_integrations/homekit.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29280 yaml.markdown: Link configuration.yaml at first usage
  source/_docs/configuration/yaml.markdown
Labels: Hacktoberfest, current

#29291 Update security page
  source/security/index.markdown
Labels: Hacktoberfest, current

#29267 Add Portland General Electric virtual integration via Opower
  source/_integrations/portlandgeneral.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent

#29248 Add Update entity description to Plex
  source/_integrations/plex.markdown
Labels: Hacktoberfest, awaits-parent, in-progress, next, has-parent

#29310 tasmota.markdown: Tweaks and edits
  source/_integrations/tasmota.markdown
Labels: Hacktoberfest, current

#29309 remote_rpi_gpio.markdown: Editing and improvements
  source/_integrations/remote_rpi_gpio.markdown
Labels: Hacktoberfest, current

#29311 opentherm_gw.markdown: Tweak/improve syntax
  source/_integrations/opentherm_gw.markdown
Labels: Hacktoberfest, current

#29307 Remove Mazda integration
  CODEOWNERS
  source/_integrations/mazda.markdown
  source/_redirects
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#29317 2023.10.2
  _config.yml
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#29242 Add country selector
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/country_selector.png
Labels: Hacktoberfest, awaits-parent, next, has-parent

#29257 Update to reflect current software
  source/_includes/asides/voice_navigation.html
  source/_includes/site/header.html
  source/_posts/2023-04-27-year-of-the-voice-chapter-2.markdown
  source/images/assist/esp32-atom_silence_detection_01.png
  source/images/assist/wake_word_connect_to_hosted_runtime.png
  source/images/assist/wake_word_disable_on_atom_echo.png
  source/images/assist/wake_word_enter_target_word.png
  source/images/assist/wake_word_listen_demo.png
  source/images/assist/wake_word_press_play_button.png
  source/images/assist/wake_word_runtime_run_all.png
  source/images/assist/wake_word_select_assistant.png
  source/images/assist/wake_word_upgrade_to_colab.png
  source/voice_control/create_wake_word.markdown
  source/voice_control/custom_sentences.markdown
  source/voice_control/thirteen-usd-voice-remote.markdown
Labels: Hacktoberfest, current

#29322 Voice 4
  source/_posts/2023-10-12-year-of-the-voice-chapter-4-wakewords.markdown
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/ESP32-breadboard.jpeg
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/assist-microphone-addon.png
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/ha-support.png
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/open-wake-word-architecture.png
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/pick-wake-word.png
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/social.png
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/wake-word-architecture.png
  source/images/blog/2023-10-12-year-of-the-voice-chapter-4/wake-word-integration.png
Labels: Hacktoberfest, current

#29319 local stt and tts pipeline: update to reflect current SW
  source/images/assist/piper-whisper-install-05.png
  source/images/assist/piper-whisper-install-new-02.png
  source/images/assist/piper-whisper-install-new-03.png
  source/voice_control/voice_remote_local_assistant.markdown
Labels: Hacktoberfest, current

#29329 Add Chapter 4 to the main Year of the Voice blog post
  source/_posts/2022-12-20-year-of-voice.markdown
Labels: Hacktoberfest, current

#29330 Update voice_remote_local_assistant.markdown
  source/voice_control/voice_remote_local_assistant.markdown
Labels: Hacktoberfest, current

#29332 Update mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: Hacktoberfest, current

#29328 2023.10.3
  _config.yml
  source/_posts/2023-10-04-release-202310.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#29334 Fix link to Year of the Voice Chapter 4 blog post
  source/_posts/2022-12-20-year-of-voice.markdown
Labels: Hacktoberfest, current

#29333 Update motioneye.markdown
  source/_integrations/motioneye.markdown
Labels: Hacktoberfest, current

#29331 nissan_leaf.markdown: Mention that it is for pre 2019 vehicles
  source/_integrations/nissan_leaf.markdown
Labels: Hacktoberfest, current

#29335 Add Mazda blog
  source/_posts/2023-10-13-removal-of-mazda-connected-services-integration.markdown
Labels: Hacktoberfest, current

#29344 Update schema.markdown
  source/_docs/blueprint/schema.markdown
Labels: Hacktoberfest, current

#29245 Add service documentation for Netatmo integration
  source/_integrations/netatmo.markdown
Labels: Hacktoberfest, next, has-parent

#29348 Add Home Assistant OS 11 blog post
  source/_posts/2023-10-14-home-assistant-os-release-11.markdown
  source/images/blog/2023-10-14-home-assistant-os-11/home-assistant-os-11-landing-page.png
Labels: Hacktoberfest, current

#29350 Add The Pi Hut as Green distributor
  source/green/index.html
Labels: Hacktoberfest, current

#29358 Onboarding: fix typo. Closes #29355
  source/getting-started/onboarding.markdown
Labels: Hacktoberfest, current

#29019 Demo integration key only
  source/_integrations/demo.markdown
Labels: awaits-parent, next, has-parent

#29366 Remove erroneous statement about script field description
  source/_integrations/script.markdown
Labels: Hacktoberfest, current

#29360 Add details for "Battery Strategy" and "Battery Smart Control" sensors
  source/_integrations/kostal_plenticore.markdown
Labels: Hacktoberfest, current

#29361 Fix Alexa smart home supported platforms
  source/_integrations/alexa.smart_home.markdown
Labels: Hacktoberfest, current

#29374 Fix typo in apple.markdown
  source/voice_control/apple.markdown
Labels: Hacktoberfest, current

#29377 Update trivia.markdown - Add Home Assistant Green
  source/help/trivia.markdown
Labels: Hacktoberfest, current

#29340 Durability -> Sustainability
  source/_posts/2021-12-23-the-open-home.markdown
Labels: Hacktoberfest, current

#29385 Add new govee models
  source/_integrations/govee_ble.markdown
Labels: Hacktoberfest, next, has-parent

#29384 Update thirteen-usd-voice-remote.markdown
  source/voice_control/thirteen-usd-voice-remote.markdown
Labels: Hacktoberfest, current

#29318 Update to WeatherFlow documentation with networking notes
  source/_integrations/weatherflow.markdown
Labels: Hacktoberfest, current

#29391 Broken link blogpost
  source/_posts/2023-08-02-release-20238.markdown
Labels: Hacktoberfest, current

#29390 Broken link alexa
  source/_integrations/alexa.smart_home.markdown
Labels: Hacktoberfest, current
