Repository home-assistant/home-assistant.io, pull requests merged in 2023-11, with the labels that each got.

#29634 Modbus remove unused links
  source/_integrations/modbus.markdown
Labels: Hacktoberfest, current

#29638 Clearify imap event text attribute limitations
  source/_integrations/imap.markdown
Labels: current, by-code-owner, integration: imap

#29637 Update third-party-addons.md
  source/_includes/common-tasks/third-party-addons.md
Labels: current

#29639 Remove HAlloween video
  source/voice_control/index.markdown
Labels: current

#29640 Common tasks: remove dev docs. Reverts #29637
  source/_includes/common-tasks/third-party-addons.md
Labels: current

#29591 Add button platform to Roborock
  source/_integrations/roborock.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29641 Fix google_mail.markdown table
  source/_integrations/google_mail.markdown
Labels: current

#29647 Clarify discharge to grid entity.
  source/_integrations/kostal_plenticore.markdown
Labels: current

#29651 Clarify the mqtt entity_category for sensors must be diagnostic
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#29546 Add Idasen Desk connection buttons
  source/_integrations/idasen_desk.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29598 Add trigger selector for blueprint
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/selector-trigger.png
Labels: Hacktoberfest, awaits-parent, next, has-parent

#29669 Add SmartGuys to Green distributors
  source/green/index.html
Labels: current

#29671 Update todo.markdown
  source/_integrations/todo.markdown
Labels: current

#29663 Add Link to Mastodon
  source/help/index.markdown
Labels: current

#29680 Fix chapter structure in devolo Home Network
  source/_integrations/devolo_home_network.markdown
Labels: current

#29659 Release notes: fix typo
  source/_posts/2023-11-01-release-202311.markdown
Labels: current

#29658 Assist: enable wake word: Add missing link to related topic
  source/voice_control/install_wake_word_add_on.markdown
Labels: current

#29682 2023.11.1
  _config.yml
  source/_posts/2023-11-01-release-202311.markdown
Labels: blog, current, has-parent

#29677 Add Caldav configuration flow documentation
  source/_integrations/caldav.markdown
Labels: next, has-parent, parent-merged

#29610 Improve IMAP integration SSL settings copy
  source/_integrations/imap.markdown
Labels: Hacktoberfest, current, integration: imap

#29709 Change URL to Home Assistant home page in iFrame card example
  source/_dashboards/iframe.markdown
Labels: current

#29708 Fix typo in statistics.markdown #29698
  source/_integrations/statistics.markdown
Labels: current

#29582 Add update documentation for System Bridge
  source/_integrations/system_bridge.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29723 Add Madeco as supported by motion_blinds
  source/_integrations/motion_blinds.markdown
Labels: current

#29726 Add blog about myq
  source/_posts/2023-11-06-removal-of-myq-integration.markdown
Labels: blog, current

#29727 Add processes to System Bridge docs
  source/_integrations/system_bridge.markdown
Labels: next, has-parent

#29724 Update mqtt_room.markdown to follow best practice
  source/_integrations/mqtt_room.markdown
Labels: current

#29661 Assist: about wake words: add approach
  source/voice_control/about_wake_word.markdown
Labels: current

#29705 Improve Oral-B documentation
  source/_integrations/oralb.markdown
Labels: current

#29735 Oral-B: fix link format
  source/_integrations/oralb.markdown
Labels: current

#29711 Add CalDAV todo documentation
  source/_integrations/caldav.markdown
Labels: next, has-parent

#29734 Remove MyQ Integration
  CODEOWNERS
  source/_integrations/myq.markdown
  source/_redirects
Labels: awaits-parent, next, has-parent

#29741 Add note about hassio installation type compatibility
  source/_integrations/hassio.markdown
Labels: current

#29728 Add HDR switch to Reolink docs
  source/_integrations/reolink.markdown
Labels: next, has-parent

#29752 Removed already illegal int8 from doc
  source/_integrations/modbus.markdown
Labels: awaits-parent, next, has-parent

#29753 Moving from 'Located in' to 'Shipping from'
  source/green/index.html
  source/skyconnect/index.html
  source/yellow/index.html
Labels: current

#29743 Draw attention to and clarify adding a slack bot to a channel
  source/_integrations/slack.markdown
Labels: current

#29537 Document `zwave_js.refresh_notifications` service
  source/_integrations/zwave_js.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29715 Add documentation for V2C Trydan EVSE
  source/_integrations/v2c.markdown
Labels: in-progress, next, has-parent, parent-merged

#29757 Add 7590 AX and DECT 302 to tested devices for Fritz! Smart Home
  source/_integrations/fritzbox.markdown
Labels: current

#29756 Update default social
  source/images/default-social.png
Labels: current

#29729 Update raspberrypi.markdown
  source/installation/raspberrypi.markdown
Labels: current

#29520 Update docs for zwave_js.set_config_parameter changes
  source/_integrations/zwave_js.markdown
Labels: Hacktoberfest, awaits-parent, next, parent-merged

#29771 Update voice landing page
  source/voice_control/index.markdown
Labels: current

#29772 Remove untrue sentence from weather entity component docs
  source/_integrations/weather.markdown
Labels: current

#29779 Remove zwave2mqtt references from mqtt docs
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#29780 Update cover.template.markdown
  source/_integrations/cover.template.markdown
Labels: current

#29785 2023.11.2
  _config.yml
  source/_posts/2023-11-01-release-202311.markdown
Labels: blog, in-progress, current, has-parent, needs-rebase

#29042 Fix DST handling in TOD
  source/_integrations/tod.markdown
Labels: in-progress, next, has-parent

#29788 Add github handle URLs to 2023.11.2
  source/_posts/2023-11-01-release-202311.markdown
Labels: current

#29789 Update docs for conversation reload service
  source/_integrations/conversation.markdown
Labels: next, has-parent

#29797 Fix aladdin connect intro
  source/_integrations/aladdin_connect.markdown
Labels: current

#29792 Update google calendar instructions to recommend Web Auth
  source/_integrations/google.markdown
  source/_integrations/google_mail.markdown
  source/_integrations/google_sheets.markdown
  source/_integrations/google_tasks.markdown
Labels: next, has-parent, parent-merged

#29805 Fix Google Calendar links needed by the comon config templates
  source/_integrations/google.markdown
Labels: next, has-parent

#29774 Hide # of installations for entity components
  source/_includes/asides/component_navigation.html
Labels: current

#29740 Update nibe_heatpump.markdown
  source/_integrations/nibe_heatpump.markdown
Labels: current

#29819 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#29701 Explain how to use MQTT discovery messages
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#29803 Update Subaru documentation
  source/_integrations/subaru.markdown
Labels: current

#29824 Matter: Remove list of supported devices
  source/_integrations/matter.markdown
Labels: current

#29800 Honeywell know issue
  source/_integrations/honeywell.markdown
Labels: current

#29686 Add HAOS+Raspi troubleshooting instructions to Idasen desk
  source/_integrations/idasen_desk.markdown
Labels: current

#29314 Update the prologue for ZHA integration
  source/_integrations/zha.markdown
Labels: Hacktoberfest, current

#29763 Add V2C switch
  source/_integrations/v2c.markdown
Labels: next, has-parent, parent-merged

#29828 Velbus: Add information about the VMB7IN module
  source/_integrations/velbus.markdown
Labels: current

#29762 Add V2C sensor description
  source/_integrations/v2c.markdown
Labels: next, has-parent, parent-merged

#29781 Add V2C Binary Sensors description
  source/_integrations/v2c.markdown
Labels: next, has-parent, parent-merged

#29764 Add V2C number description
  source/_integrations/v2c.markdown
Labels: next, has-parent, parent-merged

#29832 Quotes needed in templates for sensor names
  source/_integrations/fronius.markdown
Labels: current

#29835 Reolink: Clarify where the user account is needed
  source/_integrations/reolink.markdown
Labels: current

#29790 Clarify duration/end_date_time usage
  source/_integrations/calendar.markdown
Labels: current

#29842 Add documentation for telegram_bot reply_to_message_id option
  source/_integrations/telegram_bot.markdown
Labels: next, has-parent, parent-merged

#29846 Add deprecation notice to Konnected documentation
  source/_integrations/konnected.markdown
Labels: current

#29848 add a new product(WEM3050T,released on Nov 2023) introduction
  source/_integrations/iammeter.markdown
Labels: current

#29678 Add documentation for todo.get_items service
  source/_integrations/todo.markdown
Labels: awaits-parent, next, has-parent

#29827 Add support for lupusec smoke and water sensor
  source/_integrations/lupusec.markdown
Labels: new-feature, next, has-parent

#29855 Add new distributors
  source/green/index.html
  source/yellow/index.html
Labels: current

#29768 Document zwave_js.set_lock_configuration service
  source/_integrations/zwave_js.markdown
Labels: next, has-parent, parent-merged

#29864 s-t integrations: apply sentence-style capitalization
  source/_integrations/scene.markdown
  source/_integrations/schluter.markdown
  source/_integrations/screenlogic.markdown
  source/_integrations/script.markdown
  source/_integrations/sensibo.markdown
  source/_integrations/sensor.markdown
  source/_integrations/skybell.markdown
  source/_integrations/sms.markdown
  source/_integrations/snmp.markdown
  source/_integrations/spc.markdown
  source/_integrations/speedtestdotnet.markdown
  source/_integrations/splunk.markdown
  source/_integrations/spotify.markdown
  source/_integrations/ssdp.markdown
  source/_integrations/starlingbank.markdown
  source/_integrations/starlink.markdown
  source/_integrations/steamist.markdown
  source/_integrations/stream.markdown
  source/_integrations/sun.markdown
  source/_integrations/switch.markdown
  source/_integrations/switchbot.markdown
  source/_integrations/syncthing.markdown
  source/_integrations/system_bridge.markdown
  source/_integrations/tado.markdown
  source/_integrations/tag.markdown
  source/_integrations/tasmota.markdown
  source/_integrations/tcp.markdown
  source/_integrations/template.markdown
  source/_integrations/threshold.markdown
  source/_integrations/tibber.markdown
  source/_integrations/timer.markdown
  source/_integrations/tod.markdown
  source/_integrations/toon.markdown
  source/_integrations/traccar.markdown
  source/_integrations/tractive.markdown
  source/_integrations/transmission.markdown
  source/_integrations/tuya.markdown
Labels: current

#29861 g-i integrations: apply sentence-style capitalization
  source/_integrations/garages_amsterdam.markdown
  source/_integrations/gc100.markdown
  source/_integrations/gdacs.markdown
  source/_integrations/geniushub.markdown
  source/_integrations/geo_json_events.markdown
  source/_integrations/geonetnz_quakes.markdown
  source/_integrations/geonetnz_volcano.markdown
  source/_integrations/glances.markdown
  source/_integrations/goalzero.markdown
  source/_integrations/gogogate2.markdown
  source/_integrations/google_pubsub.markdown
  source/_integrations/group.markdown
  source/_integrations/gstreamer.markdown
  source/_integrations/hassio.markdown
  source/_integrations/heos.markdown
  source/_integrations/here_travel_time.markdown
  source/_integrations/history_stats.markdown
  source/_integrations/home_plus_control.markdown
  source/_integrations/homematicip_cloud.markdown
  source/_integrations/homewizard.markdown
  source/_integrations/hydrawise.markdown
  source/_integrations/hyperion.markdown
  source/_integrations/ihc.markdown
  source/_integrations/influxdb.markdown
  source/_integrations/input_boolean.markdown
  source/_integrations/input_button.markdown
  source/_integrations/input_datetime.markdown
  source/_integrations/input_number.markdown
  source/_integrations/input_select.markdown
  source/_integrations/input_text.markdown
  source/_integrations/integration.markdown
Labels: current

#29860 c-f integrations: apply sentence style capitalization
  source/_integrations/caldav.markdown
  source/_integrations/calendar.markdown
  source/_integrations/camera.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/co2signal.markdown
  source/_integrations/config.markdown
  source/_integrations/cover.markdown
  source/_integrations/derivative.markdown
  source/_integrations/devolo_home_control.markdown
  source/_integrations/devolo_home_network.markdown
  source/_integrations/dexcom.markdown
  source/_integrations/digital_ocean.markdown
  source/_integrations/ecobee.markdown
  source/_integrations/econet.markdown
  source/_integrations/ecovacs.markdown
  source/_integrations/efergy.markdown
  source/_integrations/egardia.markdown
  source/_integrations/enocean.markdown
  source/_integrations/environment_canada.markdown
  source/_integrations/everlights.markdown
  source/_integrations/evohome.markdown
  source/_integrations/feedreader.markdown
  source/_integrations/filter.markdown
  source/_integrations/fitbit.markdown
  source/_integrations/foobot.markdown
  source/_integrations/fortios.markdown
  source/_integrations/freebox.markdown
  source/_integrations/freedompro.markdown
  source/_integrations/fritzbox.markdown
  source/_integrations/frontier_silicon.markdown
Labels: current

#29859 a-b integrations: apply sentence-style capitalization
  source/_integrations/ads.markdown
  source/_integrations/advantage_air.markdown
  source/_integrations/airthings_ble.markdown
  source/_integrations/airvisual.markdown
  source/_integrations/airvisual_pro.markdown
  source/_integrations/airzone.markdown
  source/_integrations/airzone_cloud.markdown
  source/_integrations/alarmdecoder.markdown
  source/_integrations/alert.markdown
  source/_integrations/alexa.intent.markdown
  source/_integrations/alexa.smart_home.markdown
  source/_integrations/alpha_vantage.markdown
  source/_integrations/amcrest.markdown
  source/_integrations/ampio.markdown
  source/_integrations/analytics.markdown
  source/_integrations/androidtv.markdown
  source/_integrations/anthemav.markdown
  source/_integrations/apache_kafka.markdown
  source/_integrations/apple_tv.markdown
  source/_integrations/application_credentials.markdown
  source/_integrations/arcam_fmj.markdown
  source/_integrations/arest.markdown
  source/_integrations/asuswrt.markdown
  source/_integrations/atag.markdown
  source/_integrations/august.markdown
  source/_integrations/aussie_broadband.markdown
  source/_integrations/awair.markdown
  source/_integrations/axis.markdown
  source/_integrations/azure_event_hub.markdown
  source/_integrations/baf.markdown
  source/_integrations/bbox.markdown
  source/_integrations/binary_sensor.markdown
  source/_integrations/bloomsky.markdown
  source/_integrations/bosch_shc.markdown
  source/_integrations/braviatv.markdown
  source/_integrations/brother.markdown
  source/_integrations/button.markdown
Labels: current

#29862 l-n integrations: apply sentence-style capitalization
  source/_integrations/justnimbus.markdown
  source/_integrations/jvc_projector.markdown
  source/_integrations/keymitt_ble.markdown
  source/_integrations/kira.markdown
  source/_integrations/knx.markdown
  source/_integrations/kulersky.markdown
  source/_integrations/lacrosse.markdown
  source/_integrations/landisgyr_heat_meter.markdown
  source/_integrations/lcn.markdown
  source/_integrations/ld2410_ble.markdown
  source/_integrations/lifx.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/limitlessled.markdown
  source/_integrations/linode.markdown
  source/_integrations/livisi.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/logbook.markdown
  source/_integrations/logger.markdown
  source/_integrations/lutron.markdown
  source/_integrations/manual_mqtt.markdown
  source/_integrations/matrix.markdown
  source/_integrations/maxcube.markdown
  source/_integrations/medcom_ble.markdown
  source/_integrations/media_player.markdown
  source/_integrations/media_source.markdown
  source/_integrations/met_eireann.markdown
  source/_integrations/min_max.markdown
  source/_integrations/minio.markdown
  source/_integrations/monoprice.markdown
  source/_integrations/motion_blinds.markdown
  source/_integrations/mqtt_eventstream.markdown
  source/_integrations/mqtt_statestream.markdown
  source/_integrations/mystrom.markdown
  source/_integrations/neato.markdown
  source/_integrations/netdata.markdown
  source/_integrations/nexia.markdown
  source/_integrations/nightscout.markdown
  source/_integrations/numato.markdown
  source/_integrations/number.markdown
  source/_integrations/nzbget.markdown
Labels: current

#29865 u-z integrations: apply sentence-style capitalization
  source/_integrations/upcloud.markdown
  source/_integrations/update.markdown
  source/_integrations/vallox.markdown
  source/_integrations/venstar.markdown
  source/_integrations/vicare.markdown
  source/_integrations/vodafone_station.markdown
  source/_integrations/volvooncall.markdown
  source/_integrations/vultr.markdown
  source/_integrations/w800rf32.markdown
  source/_integrations/water_heater.mqtt.markdown
  source/_integrations/wirelesstag.markdown
  source/_integrations/ws66i.markdown
  source/_integrations/yamaha_musiccast.markdown
  source/_integrations/zabbix.markdown
  source/_integrations/zestimate.markdown
  source/_integrations/zeversolar.markdown
  source/_integrations/zoneminder.markdown
Labels: current

#29863 o-r integrations: apply sentence-style capitalization
  source/_integrations/octoprint.markdown
  source/_integrations/oncue.markdown
  source/_integrations/onvif.markdown
  source/_integrations/opensensemap.markdown
  source/_integrations/opentherm_gw.markdown
  source/_integrations/openuv.markdown
  source/_integrations/pilight.markdown
  source/_integrations/ping.markdown
  source/_integrations/plaato.markdown
  source/_integrations/plant.markdown
  source/_integrations/plex.markdown
  source/_integrations/point.markdown
  source/_integrations/powerwall.markdown
  source/_integrations/progettihwsw.markdown
  source/_integrations/proximity.markdown
  source/_integrations/python_script.markdown
  source/_integrations/qld_bushfire.markdown
  source/_integrations/qnap_qsw.markdown
  source/_integrations/qwikswitch.markdown
  source/_integrations/radarr.markdown
  source/_integrations/rainbird.markdown
  source/_integrations/raincloud.markdown
  source/_integrations/recorder.markdown
  source/_integrations/remote_rpi_gpio.markdown
  source/_integrations/reolink.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/ridwell.markdown
  source/_integrations/ring.markdown
  source/_integrations/risco.markdown
  source/_integrations/roomba.markdown
  source/_integrations/rtsp_to_webrtc.markdown
  source/_integrations/rympro.markdown
Labels: current

#29866 Dashboards: apply sentence style capitalization
  source/_dashboards/alarm-panel.markdown
  source/_dashboards/area.markdown
  source/_dashboards/button.markdown
  source/_dashboards/calendar.markdown
  source/_dashboards/conditional.markdown
  source/_dashboards/entities.markdown
  source/_dashboards/entity.markdown
  source/_dashboards/gauge.markdown
  source/_dashboards/glance.markdown
  source/_dashboards/grid.markdown
  source/_dashboards/history-graph.markdown
  source/_dashboards/horizontal-stack.markdown
  source/_dashboards/humidifier.markdown
  source/_dashboards/iframe.markdown
  source/_dashboards/light.markdown
  source/_dashboards/logbook.markdown
  source/_dashboards/map.markdown
  source/_dashboards/markdown.markdown
  source/_dashboards/media-control.markdown
  source/_dashboards/picture-elements.markdown
  source/_dashboards/picture-entity.markdown
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
  source/_dashboards/plant-status.markdown
  source/_dashboards/sensor.markdown
  source/_dashboards/shopping-list.markdown
  source/_dashboards/statistic.markdown
  source/_dashboards/statistics-graph.markdown
  source/_dashboards/thermostat.markdown
  source/_dashboards/vertical-stack.markdown
  source/_dashboards/weather-forecast.markdown
Labels: current

#29867 Docs: apply sentence-style capitalization
  source/_docs/authentication/providers.markdown
  source/_docs/automation/modes.markdown
  source/_docs/automation/templating.markdown
  source/_docs/automation/trigger.markdown
  source/_docs/automation/yaml.markdown
  source/_docs/blueprint/selectors.markdown
  source/_docs/blueprint/tutorial.markdown
  source/_docs/configuration/customizing-devices.markdown
  source/_docs/configuration/remote.markdown
  source/_docs/configuration/securing.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/configuration/yaml.markdown
  source/_docs/energy/electricity-grid.markdown
  source/_docs/energy/faq.markdown
  source/_docs/energy/individual-devices.markdown
  source/_docs/frontend/icons.markdown
  source/_docs/locked_out.md
  source/_docs/scripts.markdown
  source/_docs/tools/dev-tools.markdown
  source/_docs/tools/quick-bar.markdown
  source/_docs/z-wave/controllers.markdown
Labels: current

#29873 Adding blog for Home Assistant Green release
  source/_posts/2023-11-16-home-assistant-green-now-available.markdown
  source/images/blog/2023-11-green-release/green-image.jpg
Labels: current

#29877 Fix capitalization of Alza in Green distributors list
  source/green/index.html
Labels: current

#29879 Revert 'sentence-style capitalization' in HomeWizard
  source/_integrations/homewizard.markdown
Labels: in-progress, current, needs-rebase

#29786 Add config flow for Ping
  source/_integrations/ping.markdown
Labels: in-progress, next, has-parent, parent-merged

#29884 add MarketCom shops to Green distributors
  source/green/index.html
Labels: current

#29401 Add mode parameter to intent_script
  source/_integrations/intent_script.markdown
Labels: Hacktoberfest, next, has-parent

#29875 Remove deprecated white_value example in template light doc #76923
  source/_integrations/light.template.markdown
Labels: in-progress, current, has-parent, needs-rebase

#29890 Dashboards: apply sentence style caps
  source/_dashboards/alarm-panel.markdown
  source/_dashboards/area.markdown
  source/_dashboards/button.markdown
  source/_dashboards/calendar.markdown
  source/_dashboards/conditional.markdown
  source/_dashboards/entities.markdown
  source/_dashboards/entity-filter.markdown
  source/_dashboards/entity.markdown
  source/_dashboards/gauge.markdown
  source/_dashboards/glance.markdown
  source/_dashboards/grid.markdown
  source/_dashboards/history-graph.markdown
  source/_dashboards/horizontal-stack.markdown
  source/_dashboards/humidifier.markdown
  source/_dashboards/iframe.markdown
  source/_dashboards/light.markdown
  source/_dashboards/logbook.markdown
  source/_dashboards/map.markdown
  source/_dashboards/markdown.markdown
  source/_dashboards/masonry.markdown
  source/_dashboards/media-control.markdown
  source/_dashboards/panel.markdown
  source/_dashboards/picture-elements.markdown
  source/_dashboards/picture-entity.markdown
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
  source/_dashboards/plant-status.markdown
  source/_dashboards/sensor.markdown
  source/_dashboards/shopping-list.markdown
  source/_dashboards/sidebar.markdown
  source/_dashboards/statistic.markdown
  source/_dashboards/statistics-graph.markdown
  source/_dashboards/thermostat.markdown
  source/_dashboards/tile.markdown
  source/_dashboards/vertical-stack.markdown
  source/_dashboards/weather-forecast.markdown
  source/_includes/dashboard/edit_dashboard.md
  source/dashboards/actions.markdown
  source/dashboards/badges.markdown
  source/dashboards/views.markdown
Labels: current

#29892 Docs c z apply sentence style caps add term refs
  source/_data/glossary.yml
  source/_docs/asterisk_mbox.markdown
  source/_docs/authentication.markdown
  source/_docs/authentication/providers.markdown
  source/_docs/automation.markdown
  source/_docs/automation/action.markdown
  source/_docs/automation/basics.markdown
  source/_docs/automation/condition.markdown
  source/_docs/automation/editor.markdown
  source/_docs/automation/modes.markdown
  source/_docs/automation/services.markdown
  source/_docs/automation/templating.markdown
  source/_docs/automation/trigger.markdown
  source/_docs/automation/troubleshooting.markdown
  source/_docs/automation/using_blueprints.markdown
  source/_docs/automation/yaml.markdown
  source/_docs/backend/database.markdown
  source/_docs/blueprint.markdown
  source/_docs/blueprint/selectors.markdown
  source/_docs/blueprint/tutorial.markdown
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/customizing-devices.markdown
  source/_docs/configuration/state_object.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/energy/faq.markdown
  source/_docs/frontend/browsers.markdown
  source/_docs/frontend/icons.markdown
  source/_docs/scene/editor.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
  source/_docs/scripts/service-calls.markdown
  source/_docs/tools/check_config.markdown
  source/_docs/tools/dev-tools.markdown
  source/_docs/tools/quick-bar.markdown
Labels: current

#29896 Ensure unique categories on integrations view
  source/integrations/index.html
Labels: current

#29899 New api endpoint Trafikverket weather
  source/_integrations/trafikverket_weatherstation.markdown
Labels: next, has-parent, parent-merged

#29904 m-o integrations: apply sentence-style caps to categories
  source/_integrations/manual.markdown
  source/_integrations/manual_mqtt.markdown
  source/_integrations/marantz.markdown
  source/_integrations/matter.markdown
  source/_integrations/maxcube.markdown
  source/_integrations/media_extractor.markdown
  source/_integrations/media_player.markdown
  source/_integrations/media_source.markdown
  source/_integrations/mediaroom.markdown
  source/_integrations/meraki.markdown
  source/_integrations/meteoalarm.markdown
  source/_integrations/microsoft_face.markdown
  source/_integrations/microsoft_face_detect.markdown
  source/_integrations/microsoft_face_identify.markdown
  source/_integrations/mikrotik.markdown
  source/_integrations/minecraft_server.markdown
  source/_integrations/modern_forms.markdown
  source/_integrations/monessen.markdown
  source/_integrations/monoprice.markdown
  source/_integrations/motioneye.markdown
  source/_integrations/mpd.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/mqtt_json.markdown
  source/_integrations/mqtt_room.markdown
  source/_integrations/mullvad.markdown
  source/_integrations/mutesync.markdown
  source/_integrations/myq.markdown
  source/_integrations/mysensors.markdown
  source/_integrations/mystrom.markdown
  source/_integrations/nad.markdown
  source/_integrations/ness_alarm.markdown
  source/_integrations/nest.markdown
  source/_integrations/netatmo.markdown
  source/_integrations/netdata.markdown
  source/_integrations/netgear.markdown
  source/_integrations/netgear_lte.markdown
  source/_integrations/nexia.markdown
  source/_integrations/nexity.markdown
  source/_integrations/nextcloud.markdown
  source/_integrations/nina.markdown
  source/_integrations/nmap_tracker.markdown
  source/_integrations/notion.markdown
  source/_integrations/numato.markdown
  source/_integrations/nut.markdown
  source/_integrations/nx584.markdown
  source/_integrations/octoprint.markdown
  source/_integrations/oncue.markdown
  source/_integrations/onkyo.markdown
  source/_integrations/onvif.markdown
  source/_integrations/openalpr_cloud.markdown
  source/_integrations/opencv.markdown
  source/_integrations/openhardwaremonitor.markdown
  source/_integrations/openhome.markdown
  source/_integrations/opentherm_gw.markdown
  source/_integrations/openuv.markdown
  source/_integrations/opnsense.markdown
  source/_integrations/overkiz.markdown
  source/_integrations/owntracks.markdown
Labels: current

#29901 d and e integrations: apply sentence-style capitalization
  source/_integrations/dacia.markdown
  source/_integrations/daikin.markdown
  source/_integrations/danfoss_air.markdown
  source/_integrations/datadog.markdown
  source/_integrations/date.markdown
  source/_integrations/datetime.markdown
  source/_integrations/ddwrt.markdown
  source/_integrations/debugpy.markdown
  source/_integrations/deconz.markdown
  source/_integrations/default_config.markdown
  source/_integrations/demo.markdown
  source/_integrations/denon.markdown
  source/_integrations/denonavr.markdown
  source/_integrations/device_sun_light_trigger.markdown
  source/_integrations/device_tracker.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_tracker.xiaomi.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/devolo_home_control.markdown
  source/_integrations/devolo_home_network.markdown
  source/_integrations/dhcp.markdown
  source/_integrations/diagnostics.markdown
  source/_integrations/dialogflow.markdown
  source/_integrations/digital_loggers.markdown
  source/_integrations/digital_ocean.markdown
  source/_integrations/directv.markdown
  source/_integrations/discord.markdown
  source/_integrations/discovergy.markdown
  source/_integrations/dlib_face_detect.markdown
  source/_integrations/dlib_face_identify.markdown
  source/_integrations/dlink.markdown
  source/_integrations/dlna_dmr.markdown
  source/_integrations/dlna_dms.markdown
  source/_integrations/dnsip.markdown
  source/_integrations/dominos.markdown
  source/_integrations/doods.markdown
  source/_integrations/doorbird.markdown
  source/_integrations/dovado.markdown
  source/_integrations/downloader.markdown
  source/_integrations/dsmr_reader.markdown
  source/_integrations/dunehd.markdown
  source/_integrations/duotecno.markdown
  source/_integrations/dwd_weather_warnings.markdown
  source/_integrations/dynalite.markdown
  source/_integrations/ecoal_boiler.markdown
  source/_integrations/ecobee.markdown
  source/_integrations/econet.markdown
  source/_integrations/ecowitt.markdown
  source/_integrations/egardia.markdown
  source/_integrations/elkm1.markdown
  source/_integrations/emby.markdown
  source/_integrations/enigma2.markdown
  source/_integrations/enocean.markdown
  source/_integrations/enphase_envoy.markdown
  source/_integrations/environment_canada.markdown
  source/_integrations/envisalink.markdown
  source/_integrations/epson.markdown
  source/_integrations/evohome.markdown
  source/_integrations/ezviz.markdown
Labels: current

#29905 p-r integrations: apply sentence-style caps to categories
  source/_integrations/panasonic_bluray.markdown
  source/_integrations/panasonic_viera.markdown
  source/_integrations/pandora.markdown
  source/_integrations/person.markdown
  source/_integrations/philips_js.markdown
  source/_integrations/pi_hole.markdown
  source/_integrations/pilight.markdown
  source/_integrations/ping.markdown
  source/_integrations/pioneer.markdown
  source/_integrations/pjlink.markdown
  source/_integrations/plex.markdown
  source/_integrations/plugwise.markdown
  source/_integrations/point.markdown
  source/_integrations/powerwall.markdown
  source/_integrations/private_ble_device.markdown
  source/_integrations/progettihwsw.markdown
  source/_integrations/proximity.markdown
  source/_integrations/proxmoxve.markdown
  source/_integrations/ps4.markdown
  source/_integrations/qingping.markdown
  source/_integrations/qnap.markdown
  source/_integrations/qnap_qsw.markdown
  source/_integrations/qrcode.markdown
  source/_integrations/quadrafire.markdown
  source/_integrations/quantum_gateway.markdown
  source/_integrations/qwikswitch.markdown
  source/_integrations/rachio.markdown
  source/_integrations/radio_browser.markdown
  source/_integrations/rainbird.markdown
  source/_integrations/raincloud.markdown
  source/_integrations/rainmachine.markdown
  source/_integrations/random.markdown
  source/_integrations/rdw.markdown
  source/_integrations/remote_rpi_gpio.markdown
  source/_integrations/renault.markdown
  source/_integrations/renson.markdown
  source/_integrations/rest.markdown
  source/_integrations/rexel.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/ring.markdown
  source/_integrations/risco.markdown
  source/_integrations/rituals_perfume_genie.markdown
  source/_integrations/roborock.markdown
  source/_integrations/roku.markdown
  source/_integrations/roon.markdown
  source/_integrations/rpi_power.markdown
  source/_integrations/ruckus_unleashed.markdown
  source/_integrations/russound_rio.markdown
  source/_integrations/russound_rnet.markdown
Labels: current

#29902 F and G integrations: apply sentence-style in categories
  source/_integrations/faa_delays.markdown
  source/_integrations/facebox.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/fastdotcom.markdown
  source/_integrations/ffmpeg.markdown
  source/_integrations/ffmpeg_motion.markdown
  source/_integrations/ffmpeg_noise.markdown
  source/_integrations/fibaro.markdown
  source/_integrations/fire_tv.markdown
  source/_integrations/fireservicerota.markdown
  source/_integrations/firmata.markdown
  source/_integrations/fivem.markdown
  source/_integrations/fjaraskupan.markdown
  source/_integrations/flexom.markdown
  source/_integrations/flic.markdown
  source/_integrations/flo.markdown
  source/_integrations/flume.markdown
  source/_integrations/flux_led.markdown
  source/_integrations/folder_watcher.markdown
  source/_integrations/forked_daapd.markdown
  source/_integrations/fortios.markdown
  source/_integrations/freebox.markdown
  source/_integrations/freedompro.markdown
  source/_integrations/fritz.markdown
  source/_integrations/fritzbox.markdown
  source/_integrations/fritzbox_callmonitor.markdown
  source/_integrations/frontend.markdown
  source/_integrations/frontier_silicon.markdown
  source/_integrations/fully_kiosk.markdown
  source/_integrations/garages_amsterdam.markdown
  source/_integrations/gardena_bluetooth.markdown
  source/_integrations/gc100.markdown
  source/_integrations/generic_thermostat.markdown
  source/_integrations/geniushub.markdown
  source/_integrations/geofency.markdown
  source/_integrations/glances.markdown
  source/_integrations/google.markdown
  source/_integrations/google_assistant.markdown
  source/_integrations/google_mail.markdown
  source/_integrations/google_maps.markdown
  source/_integrations/google_wifi.markdown
  source/_integrations/gpslogger.markdown
  source/_integrations/group.markdown
  source/_integrations/gstreamer.markdown
  source/_integrations/guardian.markdown
Labels: current

#29885 Update concepts-terminology.markdown
  source/getting-started/concepts-terminology.markdown
Labels: current

#29915 Add new sensors to Trafikverket Weather
  source/_integrations/trafikverket_weatherstation.markdown
Labels: next, has-parent, parent-merged

#29916 Fix spelling in Event MQTT section
  source/_integrations/event.mqtt.markdown
Labels: current

#29898 b and c integrations: minor style change
  source/_integrations/baf.markdown
  source/_integrations/balboa.markdown
  source/_integrations/bayesian.markdown
  source/_integrations/bbox.markdown
  source/_integrations/binary_sensor.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/binary_sensor.rest.markdown
  source/_integrations/binary_sensor.rflink.markdown
  source/_integrations/binary_sensor.xiaomi_aqara.markdown
  source/_integrations/blackbird.markdown
  source/_integrations/blink.markdown
  source/_integrations/bloomsky.markdown
  source/_integrations/bluemaestro.markdown
  source/_integrations/bluesound.markdown
  source/_integrations/bluetooth.markdown
  source/_integrations/bluetooth_le_tracker.markdown
  source/_integrations/bluetooth_tracker.markdown
  source/_integrations/bmw_connected_drive.markdown
  source/_integrations/bond.markdown
  source/_integrations/bosch_shc.markdown
  source/_integrations/brandt.markdown
  source/_integrations/braviatv.markdown
  source/_integrations/broadlink.markdown
  source/_integrations/brother.markdown
  source/_integrations/browser.markdown
  source/_integrations/brunt.markdown
  source/_integrations/bsblan.markdown
  source/_integrations/bt_home_hub_5.markdown
  source/_integrations/bt_smarthub.markdown
  source/_integrations/bthome.markdown
  source/_integrations/bticino.markdown
  source/_integrations/bubendorff.markdown
  source/_integrations/buienradar.markdown
  source/_integrations/button.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/calendar.markdown
  source/_integrations/camera.markdown
  source/_integrations/canary.markdown
  source/_integrations/cast.markdown
  source/_integrations/cert_expiry.markdown
  source/_integrations/channels.markdown
  source/_integrations/cisco_ios.markdown
  source/_integrations/cisco_mobility_express.markdown
  source/_integrations/clementine.markdown
  source/_integrations/climate.markdown
  source/_integrations/cloud.markdown
  source/_integrations/cloudflare.markdown
  source/_integrations/cmus.markdown
  source/_integrations/color_extractor.markdown
  source/_integrations/command_line.markdown
  source/_integrations/compensation.markdown
  source/_integrations/concord232.markdown
  source/_integrations/configurator.markdown
  source/_integrations/control4.markdown
  source/_integrations/conversation.markdown
  source/_integrations/cover.template.markdown
  source/_integrations/cozytouch.markdown
  source/_integrations/cpuspeed.markdown
  source/_integrations/cups.markdown
Labels: current

#29903 h-l integrations: apply sentence-style caps in categories
  source/_integrations/harman_kardon_avr.markdown
  source/_integrations/hassio.markdown
  source/_integrations/hddtemp.markdown
  source/_integrations/heos.markdown
  source/_integrations/hexaom.markdown
  source/_integrations/hi_kumo.markdown
  source/_integrations/hikvision.markdown
  source/_integrations/hitron_coda.markdown
  source/_integrations/hive.markdown
  source/_integrations/home_connect.markdown
  source/_integrations/homekit.markdown
  source/_integrations/homekit_controller.markdown
  source/_integrations/homematic.markdown
  source/_integrations/homematicip_cloud.markdown
  source/_integrations/homeseer.markdown
  source/_integrations/horizon.markdown
  source/_integrations/hp_ilo.markdown
  source/_integrations/http.markdown
  source/_integrations/huawei_lte.markdown
  source/_integrations/hydrawise.markdown
  source/_integrations/iaqualink.markdown
  source/_integrations/ibeacon.markdown
  source/_integrations/icloud.markdown
  source/_integrations/ihc.markdown
  source/_integrations/image_processing.markdown
  source/_integrations/incomfort.markdown
  source/_integrations/insteon.markdown
  source/_integrations/intellifire.markdown
  source/_integrations/iperf3.markdown
  source/_integrations/ipp.md
  source/_integrations/isy994.markdown
  source/_integrations/itunes.markdown
  source/_integrations/jellyfin.markdown
  source/_integrations/kaleidescape.markdown
  source/_integrations/keba.markdown
  source/_integrations/keenetic_ndms2.markdown
  source/_integrations/kef.markdown
  source/_integrations/knx.markdown
  source/_integrations/kodi.markdown
  source/_integrations/konnected.markdown
  source/_integrations/laundrify.markdown
  source/_integrations/lcn.markdown
  source/_integrations/ld2410_ble.markdown
  source/_integrations/legrand.markdown
  source/_integrations/leviton_z_wave.markdown
  source/_integrations/lg_netcast.markdown
  source/_integrations/lg_soundbar.markdown
  source/_integrations/life360.markdown
  source/_integrations/light.template.markdown
  source/_integrations/linksys_smart.markdown
  source/_integrations/linode.markdown
  source/_integrations/linux_battery.markdown
  source/_integrations/livisi.markdown
  source/_integrations/locative.md
  source/_integrations/lookin.markdown
  source/_integrations/luci.markdown
  source/_integrations/lupusec.markdown
  source/_integrations/lutron_caseta.markdown
Labels: current

#29919 Add Reolink day night switch threshold docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#29914 Roomba: add steps to close all apps...
  source/_integrations/roomba.markdown
Labels: current

#29920 Add height sensor to Idasen Desk integration
  source/_integrations/idasen_desk.markdown
Labels: next, has-parent, parent-merged

#29926 Reolink: markup UI strings
  source/_integrations/reolink.markdown
Labels: current

#26949 Add broadlink climate
  CODEOWNERS
  source/_integrations/broadlink.markdown
Labels: next, has-parent, parent-merged

#29918 Mention execution queue full error in Overkiz integration
  source/_integrations/overkiz.markdown
Labels: current

#29932 Fix tts speak example
  source/_integrations/tts.markdown
Labels: current

#29929 Add todo.remove_completed_items service call
  source/_integrations/todo.markdown
Labels: next, has-parent, parent-merged

#29930 Glossary term 'integration': fix typo, slight rephrase
  source/_data/glossary.yml
Labels: current

#29917 Add Reolink animal detection docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#29950 Reolink: change initial setup formatting to numbered steps
  source/_integrations/reolink.markdown
Labels: current

#29951 Reolink consistently use bold markup
  source/_integrations/reolink.markdown
Labels: current

#29949 Update Home Assistant works with assets
  source/images/works_with/works-with-bluetooth.png
  source/images/works_with/works-with-cloud.png
  source/images/works_with/works-with-local.png
  source/images/works_with/works-with-matter.png
  source/images/works_with/works-with-zigbee.png
  source/images/works_with/works-with-zwave.png
Labels: current

#29818 Document proposed new area card features (camera_view and aspect_ratio)
  source/_dashboards/area.markdown
Labels: next, has-parent, parent-merged

#29953 Unifiprotect: fix unsupported glossary term reference
  source/_integrations/unifiprotect.markdown
Labels: current

#29574 Add image to Roborock
  source/_integrations/roborock.markdown
Labels: Hacktoberfest, next, has-parent

#28344 Workday check_date service
  source/_integrations/workday.markdown
Labels: next, has-parent, parent-merged

#28041 add komfovent integration docs
  source/_integrations/komfovent.markdown
Labels: next, has-parent, parent-merged

#29942 Update decora_wifi.markdown
  source/_integrations/decora_wifi.markdown
Labels: in-progress, current

#29941 Document that lock.mqtt payload_open doesn't have a default value
  source/_integrations/lock.mqtt.markdown
Labels: current

#29952 Document UniFi PoE power cycle button
  source/_integrations/unifi.markdown
Labels: next, has-parent, parent-merged

#29555 Add doc about the Picnic shopping cart todo list
  source/_integrations/picnic.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#29954 Picture glance card: procedure showing how to use card to PTZ control a camera
  source/_dashboards/picture-glance.markdown
  source/_integrations/amcrest.markdown
  source/_integrations/ezviz.markdown
  source/_integrations/foscam.markdown
  source/_integrations/onvif.markdown
  source/_integrations/reolink.markdown
  source/images/dashboards/picture_glance_camera_control.gif
  source/images/dashboards/picture_glance_card_define_tap_action.png
  source/images/dashboards/picture_glance_card_select_camera_arrows.png
  source/images/dashboards/picture_glance_card_select_camera_entity.png
Labels: current

#27014 Add Linear Garage Door documentation
  source/_integrations/linear_garage_door.markdown
Labels: in-progress, next, has-parent, parent-merged

#28654 Re-adding docs for Fast.com
  source/_integrations/fastdotcom.markdown
Labels: next, has-parent, parent-merged

#29958 2023.11.3
  _config.yml
  source/_posts/2023-11-01-release-202311.markdown
Labels: blog, current, has-parent

#27867 Add new section for PhilipsTV binary_sensor
  source/_integrations/philips_js.markdown
Labels: next, has-parent, parent-merged

#29816 Add local api documentation for Overkiz integration
  source/_integrations/overkiz.markdown
Labels: next, has-parent, parent-merged

#29955 Add alternative Phillips Hue bulb reset method
  source/_integrations/zha.markdown
Labels: current

#29822 Add number platform to ViCare integration
  source/_integrations/vicare.markdown
Labels: next, has-parent, parent-merged

#29883 Add Netatmo temperature services
  source/_integrations/netatmo.markdown
Labels: next, has-parent, parent-merged

#29928 Update getting started (and some other changes)
  sass/custom/_component_page.scss
  sass/custom/_details.scss
  sass/custom/_features.scss
  sass/custom/_getting_started.scss
  sass/custom/_landingpage.scss
  sass/custom/_paulus.scss
  sass/custom/_syntax.scss
  source/_includes/installation_survey.html
  source/_layouts/landingpage.html
  source/images/installation/generic-x86-64.svg
  source/images/installation/green-logo-square.png
  source/images/installation/green.jpg
  source/images/installation/macos.svg
  source/images/installation/odroid.jpg
  source/images/installation/odroid.png
  source/images/installation/rpi.jpg
  source/images/installation/windows.svg
  source/images/installation/x86.jpg
  source/images/installation/yellow-logo-square.png
  source/images/installation/yellow.jpg
  source/installation/index.html
Labels: current

#25994 Add RGB, RGBW and RGBWW capability to template.light
  source/_integrations/light.template.markdown
Labels: next, has-parent, parent-merged

#29874 Add logarithmic scale option to Statistics and History graph cards
  source/_dashboards/history-graph.markdown
  source/_dashboards/statistics-graph.markdown
Labels: next, has-parent, parent-merged

#25686 Update docs with optional API token info
  source/_integrations/pvpc_hourly_pricing.markdown
Labels: in-progress, next, has-parent, parent-merged

#24675 Nobø Hub - Support week profiles and global override
  source/_integrations/nobo_hub.markdown
Labels: Hacktoberfest, new-feature, next, has-parent, parent-merged, hacktoberfest-accepted

#29356 Add in extended note for alexa integration to describe routines
  source/_integrations/alexa.intent.markdown
Labels: Hacktoberfest, current, smash

#29966 Add Reolink diagnostics docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#29853 Update electricity-grid.markdown
  source/_docs/energy/electricity-grid.markdown
Labels: current, smash

#29983 Added step to "Take control" on first edit of a dashboard
  source/getting-started/onboarding_dashboard.markdown
Labels: current

#29982 Added note of potential loss of data when change database in recorder
  source/_integrations/recorder.markdown
Labels: current

#29580 Add more categories
  source/_integrations/advantage_air.markdown
Labels: Hacktoberfest, current

#29744 Update and improve introduction in matter.markdown
  source/_integrations/matter.markdown
Labels: current, smash, integration: matter
