Repository home-assistant/home-assistant.io, pull requests merged in 2023-04, with the labels that each got.

#26832 Rename Android TV to Android Debug Bridge
  source/_integrations/androidtv.markdown
Labels: next, has-parent

#26842 Document new profiler object logging with source
  source/_integrations/profiler.markdown
Labels: next, has-parent

#26828 Yellow product page: fix position of buy button
  sass/custom/_landingpage.scss
  source/skyconnect/index.html
  source/yellow/index.html
Labels: current

#26831 Update hassio.markdown
  source/_integrations/hassio.markdown
Labels: current

#25028 Add config flow to qbittorrent
  source/_integrations/qbittorrent.markdown
Labels: in-progress, next, has-parent, parent-merged

#26822 Add example of sorting states by entity_id
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#26740 Remove Darksky
  source/_integrations/darksky.markdown
  source/_integrations/weather.darksky.markdown
  source/_redirects
Labels: awaits-parent, next, has-parent

#26845 Remove confusing disaperaing logic for landingpage fab
  source/_layouts/landingpage.html
Labels: current

#26844 Document the constant selector
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/selector-constant.png
Labels: in-progress, next

#26820 Updating Supla docs with garage door channel type support
  source/_integrations/supla.markdown
Labels: next, has-parent

#26849 Remove description of obsolete ping service
  source/_integrations/zwave_js.markdown
Labels: current

#26792 Remove deprecated imap_content_sensor integration documentation
  source/_integrations/imap_email_content.markdown
  source/_redirects
Labels: next, has-parent, parent-merged, cleanup

#26839 Add sort list service to Shopping List
  source/_integrations/shopping_list.markdown
Labels: awaits-parent, next, has-parent

#26851 Fan and alarm tile features
  source/_dashboards/tile.markdown
  source/images/dashboards/tile-features/alarm_modes.png
  source/images/dashboards/tile-features/fan_speed.png
Labels: in-progress, next, has-parent

#26855 Add guidance on dumping template information to the profiler integration
  source/_integrations/profiler.markdown
Labels: next, has-parent

#26853 Update trigger.markdown
  source/_docs/automation/trigger.markdown
Labels: current

#26867 Fix 'Select' typos
  source/_integrations/update.mqtt.markdown
Labels: current

#26868 Update Spotify docs
  source/_integrations/spotify.markdown
  source/images/integrations/spotify/application-credentials.png
  source/images/integrations/spotify/create-spotify-application.png
  source/images/integrations/spotify/dashboard.png
  source/images/integrations/spotify/edit-settings.png
  source/images/integrations/spotify/redirect-uri.png
  source/images/integrations/spotify/save-application.png
  source/images/integrations/spotify/show-client-secret.png
Labels: current

#26761 Add new sensors to airq integration
  source/_integrations/airq.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#25986 Add Relative_time and today_at updates
  source/_docs/configuration/templating.markdown
Labels: new-feature, next, has-parent, parent-merged

#26862 Add Z-Wave overview and setup sections
  source/_includes/integrations/config_flow.md
  source/_integrations/zwave_js.markdown
Labels: current

#26882 Add documentation for supported features selector
  source/_docs/blueprint/selectors.markdown
Labels: in-progress, next, needs-rebase

#26870 Make users aware of recent issues with ultraloq
  source/_integrations/ultraloq.markdown
  source/_posts/2022-10-25-ultraloq-partner.markdown
Labels: current

#26897 Remove the coronavirus integration
  source/_integrations/coronavirus.markdown
  source/_redirects
Labels: next, has-parent, parent-merged

#26898 2023.4.1
  _config.yml
  source/_posts/2023-04-05-release-20234.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26901 Remove stale information from history
  source/_integrations/history.markdown
Labels: next, has-parent

#26918 Fix Insteon page
  source/_integrations/insteon.markdown
Labels: current

#26925 2023.4.2
  _config.yml
  source/_posts/2023-04-05-release-20234.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26923 Clarification of Temperature Sensor Limitations
  source/_integrations/nest.markdown
Labels: current

#26941 Add Epson XP-2100 to list of tested devices
  source/_integrations/epsonworkforce.markdown
Labels: current

#26894 Update typo in "external"
  source/_integrations/mailgun.markdown
Labels: current

#26927 URL updates
  source/_integrations/flux_led.markdown
  source/_integrations/subaru.markdown
Labels: current

#26816 HomeSeer partnership announcement blog post
  source/_posts/2023-04-11-homeseer-partner.markdown
  source/images/blog/2023-04-11-homeseer-partner/homeseer_top.png
  source/images/blog/2023-04-11-homeseer-partner/marketing.jpg
  source/images/blog/2023-04-11-homeseer-partner/social.png
Labels: in-progress, current, has-parent, needs-rebase

#26890 Add info where to find security keys
  source/_integrations/zwave_js.markdown
Labels: current

#26873 Restructure Z-Wave integration page
  source/_integrations/zwave_js.markdown
Labels: current

#26893 Update the documentation to support PR: #88801
  source/_integrations/home_connect.markdown
Labels: current, has-parent

#26975 Add new URLs
  source/help/reporting_issues.markdown
Labels: current

#26964 Z-Wave: move up section on advanced features
  source/_integrations/zwave_js.markdown
  source/images/integrations/z-wave/z-wave-device-info.png
  source/images/integrations/z-wave/z-wave-integration-config-panel.png
  source/images/integrations/z-wave/z-wave-integration-menu.png
Labels: current

#26939 Allow an unknown state, position or tilt for template cover
  source/_integrations/cover.template.markdown
Labels: next, has-parent, parent-merged

#26953 Add HomeKit RPi transcoding
  source/_integrations/homekit.markdown
Labels: next, has-parent, parent-merged

#26913 Fix incorrect default for db_url in SQL
  source/_integrations/sql.markdown
Labels: current

#26877 Added the term "Area" to glossary.
  source/_data/glossary.yml
Labels: current

#26956 Add documentation for to_json options
  source/_docs/configuration/templating.markdown
Labels: next, has-parent

#26980 2023.4.3
  source/_posts/2023-04-05-release-20234.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26983 Fix broken Z-Wave link
  source/_integrations/zwave_js.markdown
Labels: current

#26999 resort resellers and add lewis
  source/skyconnect/index.html
Labels: current

#26989 Z-Wave: Add overview of server installation option 1 and 2
  source/_integrations/zwave_js.markdown
  source/images/integrations/z-wave/z-wave-server-install-options-1-2.png
Labels: current

#26993 Fix more categories being active while they are not
  source/integrations/index.html
Labels: current

#26986 Fixer.io changed the free request rate
  source/_integrations/fixer.markdown
Labels: current

#26997 Add endraw to close the raw
  source/_docs/configuration/templating.markdown
Labels: current

#27001 Update arcam_fmj.markdown
  source/_integrations/arcam_fmj.markdown
Labels: current

#27008 Remove obsolete #
  source/integrations/index.html
Labels: current

#21637 Describe webhook trigger allowed_methods/local_only options
  source/_docs/automation/trigger.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#26991 Z-Wave: add Z-Wave terminology table
  source/_integrations/zwave_js.markdown
Labels: current

#27010 Describe `announce` service call option for Sonos
  source/_integrations/sonos.markdown
Labels: next, has-parent, parent-merged

#26942 Add ssl ciper list option to rest
  source/_integrations/rest.markdown
Labels: awaits-parent, next, has-parent

#27018 Adjust ssl_cipher_list options in rest docs
  source/_integrations/rest.markdown
Labels: next, has-parent

#27005 Update URLs
  source/_integrations/ads.markdown
  source/_integrations/counter.markdown
  source/_integrations/hunterdouglas_powerview.markdown
  source/_integrations/input_boolean.markdown
  source/_integrations/input_button.markdown
  source/_integrations/input_datetime.markdown
  source/_integrations/input_number.markdown
  source/_integrations/input_select.markdown
  source/_integrations/input_text.markdown
  source/_integrations/lirc.markdown
  source/_integrations/python_script.markdown
  source/_integrations/schedule.markdown
  source/_integrations/statistics.markdown
  source/_integrations/timer.markdown
  source/_integrations/torque.markdown
  source/_integrations/traccar.markdown
Labels: current

#27023 Update 2023.04 release notes - Home Connect
  source/_posts/2023-04-05-release-20234.markdown
Labels: current

#27022 Installation: update Raspberry Pi procedure
  source/_includes/installation/operating_system.md
  source/images/installation/rpi-imager-start.png
  source/images/installation/rpi-select-os.png
  source/images/installation/rpi-select-sd-card.png
  source/images/installation/rpi-select-write.png
  source/images/installation/rpi_imager.png
  source/installation/raspberrypi.markdown
Labels: current

#27017 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#27015 Add documentation for Ping drop rate & fix missing sensors
  source/_integrations/starlink.markdown
Labels: awaits-parent, next, has-parent

#26002 Add synology photos documentation
  source/_integrations/synology_dsm.markdown
Labels: new-feature, awaits-parent, next, has-parent

#27025 Update minimum supported controller version
  source/_integrations/tplink_omada.markdown
Labels: in-progress, next, has-parent

#27027 Z-Wave controllers: add info on Z-Pi 7 on Yellow
  source/_docs/z-wave/controllers.markdown
  source/images/docs/z-wave/zpi-7-yellow.jpg
Labels: current

#26934 Add MyPlace support to Advantage Air
  source/_integrations/advantage_air.markdown
Labels: next, has-parent, parent-merged

#26659 Android TV Remote integration documentation
  source/_integrations/androidtv_remote.markdown
  source/images/integrations/androidtv_remote/lovelace_example.png
Labels: new-integration, next, has-parent, parent-merged

#27026 Documentation improvements
  source/_integrations/fixer.markdown
  source/_integrations/honeywell.markdown
  source/_integrations/smtp.markdown
Labels: current

#26506 Monessen virtual IntelliFire integration
  source/_integrations/monessen.markdown
Labels: awaits-parent, in-progress, next, has-parent

#27000 Glossary: expand definition of 'action'
  source/_data/glossary.yml
Labels: current

#26973 Allow mqtt device_class or UOM to be None
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/update.mqtt.markdown
Labels: next, has-parent, parent-merged, integration: mqtt

#27043 Add blog post for Home Assistant OS 10 release
  source/_posts/2023-04-18-home-assistant-os-release-10.markdown
  source/images/blog/2023-04-18-os10/datadisk-new.png
  source/images/blog/2023-04-18-os10/hardkernel-odroid-m1.jpg
  source/images/blog/2023-04-18-os10/social.png
Labels: blog, current

#27051 Installation: ODROID: add M1
  _config.yml
  source/_includes/installation/container.md
  source/_includes/installation/core.md
  source/_includes/installation/operating_system.md
Labels: current

#27037 Z-Wave controllers on Yellow: Add additional modules to list
  source/_docs/z-wave/controllers.markdown
Labels: current

#27056 fine tune instruction on allowed types
  source/_dashboards/picture-elements.markdown
Labels: current

#26977 Update the fact that it's no more usable
  source/_integrations/thethingsnetwork.markdown
Labels: current

#26979 Update entities.markdown: corrected default value for `show_name`
  source/_dashboards/entities.markdown
Labels: current

#27066 Blue product page: add info that discontinued
  source/blue/index.html
Labels: current

#27064 Update Yellow product page
  source/yellow/index.html
Labels: current

#27069 Add Nuki smart lock 3.0 Pro to third-party supporting MQTT auto-discovery
  source/_integrations/mqtt.markdown
Labels: current

#27070 Documentation page: add links to Yellow and SkyConnect docs
  source/_includes/asides/docs_navigation.html
Labels: current

#27061 Updated to clarify the setup parameters for Pi-Hole.
  source/_integrations/pi_hole.markdown
Labels: current

#27078 Updated Automation Editor page based on 2023.4
  source/_docs/automation/editor.markdown
  source/images/docs/automation-editor/add-trigger-to-automation.png
  source/images/docs/automation-editor/create-automation.png
  source/images/docs/automation-editor/new-action.png
  source/images/docs/automation-editor/new-automation.png
  source/images/docs/automation-editor/new-trigger.png
  source/images/docs/automation-editor/send-notification.png
Labels: current

#27040 Update venstar.markdown
  source/_integrations/venstar.markdown
Labels: current

#27049 Update UniFi Protect documentation
  source/_integrations/unifiprotect.markdown
Labels: current

#27079 Flashing ODROID: add info that Allen key is needed
  source/_includes/common-tasks/flashing_n2_otg.md
Labels: current

#27083 Remove Nuki Hub description in third-party tools supporting MQTT auto-discovery
  source/_integrations/mqtt.markdown
Labels: current

#27081 Small improvements
  source/_integrations/http.markdown
  source/_integrations/websocket_api.markdown
Labels: current

#26791 Extend doorbell features
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent

#27077 Update tts docs
  source/_integrations/tts.markdown
Labels: next, has-parent, parent-merged

#26988 Update stt docs
  source/_integrations/stt.markdown
Labels: next, has-parent, parent-merged

#22907 Implement Config Flow Workday
  source/_integrations/workday.markdown
Labels: new-feature, cla-signed, next, has-parent, parent-merged

#27052 Getting started: markup ui elements
  source/getting-started/configuration.markdown
  source/getting-started/onboarding.markdown
Labels: current

#26872 Use correct chemical formula for Carbon Monoxide
  source/_integrations/london_air.markdown
Labels: current

#26520 Add new Roborock integration documentation
  source/_integrations/roborock.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#27093 Correct spelling sequentially into sequentially
  source/_docs/scripts.markdown
Labels: current

#26909 Nuance not supported list with NVR option
  source/_integrations/reolink.markdown
Labels: current

#26982 Add Markdown To Do list example for Habitica
  source/_integrations/habitica.markdown
Labels: current

#26885 Create configuration_yaml_by_ntalekt.markdown
  source/_examples/configuration_yaml_by_ntalekt.markdown
Labels: current

#26487 Google Assistant SDK: Add a step to change language if needed during authorization
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#27094 Fix typo
  source/_integrations/habitica.markdown
Labels: current

#27095 Clarification on binary sensors
  source/_integrations/hassio.markdown
Labels: current

#25851 Setup of anova docs
  source/_integrations/anova.markdown
Labels: in-progress, next, has-parent, parent-merged

#27091 Add info about new entities for easyEnergy
  source/_integrations/easyenergy.markdown
  source/images/integrations/easyenergy/pricegraph.png
Labels: next, has-parent, parent-merged

#24698 Add device actions to NUT integration doc
  source/_integrations/nut.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged, hacktoberfest-accepted

#27102 Update xiaomi_tv.markdown
  source/_integrations/xiaomi_tv.markdown
Labels: current

#27087 Add MQTT fan direction feature
  source/_integrations/fan.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: next, has-parent, parent-merged

#27114 Default config: add assist pipeline
  source/_integrations/default_config.markdown
Labels: next, has-parent

#27104 Update URLs
  source/_integrations/zha.markdown
Labels: current

#27101 Update history-graph.markdown
  source/_dashboards/history-graph.markdown
Labels: current

#26879 Add terminology tool tips to getting started pages
  source/_data/glossary.yml
  source/getting-started/automation.markdown
  source/getting-started/onboarding.markdown
  source/getting-started/presence-detection.markdown
Labels: current

#27118 Fix MQTT fan template types
  source/_integrations/fan.mqtt.markdown
Labels: current

#27120 Correct mqtt config template option type
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/tag.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#27110 Improve note on max_age and sampling_size relationship
  source/_integrations/statistics.markdown
Labels: current

#27100 Add ssl cipherlist option for imap config flow
  source/_integrations/imap.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#27122 Assist pipeline fix typo
  source/_integrations/assist_pipeline.markdown
Labels: in-progress, next, needs-rebase

#27123 TelldusLive API is now a subscription service
  source/_integrations/tellduslive.markdown
Labels: current

#27097 Removed missing Google maps example
  source/_integrations/system_log.markdown
Labels: current

#27098 Added hint a Compensation integration creates a new entity
  source/_integrations/compensation.markdown
Labels: current

#26838 Update configuration.markdown
  source/_docs/configuration.markdown
Labels: current

#26963 Add offset instructions to automation trigger
  source/_integrations/sun.markdown
Labels: current

#27048 Update tado.markdown
  source/_integrations/tado.markdown
Labels: next, has-parent

#27130 Add select platform to Roborock
  source/_integrations/roborock.markdown
Labels: next, has-parent

#26787 Add DHCP Discovery to Obihai
  source/_integrations/obihai.markdown
Labels: next, has-parent, parent-merged

#27135 Clarify Tile card documentation image caption
  source/_dashboards/tile.markdown
Labels: current

#27134 Add note on accessibility of advanced mqtt broker settings
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent

#27099 Add information to use Freebox Delta cameras
  source/_integrations/freebox.markdown
Labels: next, has-parent, parent-merged

#27139 Document 'special' zwave entities
  source/_integrations/zwave_js.markdown
Labels: next, parent-merged

#27144 Remove docs on deprecated `fan.set_speed` service
  source/_integrations/fan.markdown
Labels: in-progress, current, needs-rebase

#26365 BMW: Add EV select documentation
  source/_integrations/bmw_connected_drive.markdown
Labels: next, has-parent, parent-merged

#27136 Improve matter documentation
  source/_integrations/matter.markdown
  source/images/integrations/matter/matter_thread_infographic.webp
Labels: current, integration: matter

#27156 Update SolarEdge instructions
  source/_integrations/solaredge.markdown
Labels: current

#27154 Revert early docs merge for zwave
  source/_integrations/zwave_js.markdown
Labels: next

#27085 Voip integration
  source/_integrations/voip.markdown
  source/images/integrations/voip/voip_adapter.png
  source/images/integrations/voip/voip_adapter.svg
Labels: in-progress, next, needs-rebase, parent-merged

#27157 Update scripts.markdown
  source/_docs/scripts.markdown
Labels: current

#27151 Tiny text improvements
  source/_integrations/meteoalarm.markdown
Labels: current

#27138 Voice tutorial: Add procedure on setting up esp32 for voice control
  source/_includes/asides/docs_navigation.html
  source/_includes/site/sidebar.html
  source/docs/assist/voice_remote_local_assistant.markdown
  source/images/assist/assistant-expose-01.png
  source/images/assist/assistant-expose-02.png
  source/images/assist/esp32-atom-flash-06.png
  source/images/assist/esp32-atom-flash-07.png
  source/images/assist/esp32-atom-flash-no-port.png
  source/images/assist/esp32-atom-flash-select-port.png
  source/images/assist/m5stack-atom-echo-discovered-03.png
  source/images/assist/piper-whisper-install-01.png
  source/images/assist/piper-whisper-install-02.png
  source/images/assist/piper-whisper-install-03.png
  source/images/assist/piper-whisper-install-05.png
  source/images/assist/server-language-01.png
  source/projects/thirteen-usd-voice-remote.markdown
Labels: next

#27150 Limit imap_content event email body text data
  source/_integrations/imap.markdown
Labels: next, has-parent, parent-merged

#27174 Fix exclude update domain in recorder
  source/_integrations/recorder.markdown
Labels: current

#27171 Move troubleshooting topic
  source/_integrations/assist_pipeline.markdown
  source/_integrations/voip.markdown
  source/docs/assist/troubleshooting.markdown
  source/docs/assist/voice_remote_local_assistant.markdown
  source/images/assist/assistant-give-name-01.png
  source/images/assist/assistant-stt-tts-define.png
  source/images/assist/conversation-service-01.png
  source/images/assist/ha-cloud-tts-01.png
  source/images/assist/server-language-01.png
  source/images/assist/voip-select-pipline.png
  source/images/frontpage/voip-tut-frontpage-01.jpg
  source/projects/thirteen-usd-voice-remote.markdown
  source/projects/worlds-most-private-voice-assistant.markdown
Labels: in-progress, next, needs-rebase

#27175 Update recorder.markdown
  source/_integrations/recorder.markdown
Labels: current

#27172 Add voice blog
  source/_posts/2023-04-27-year-of-the-voice-chapter-2.markdown
  source/images/assist/ha_cloud.mp3
  source/images/assist/piper-logo.svg
  source/images/assist/piper.wav
  source/images/blog/2023-04-27-year-of-the-voice-chapter-2/assist-config.png
  source/images/blog/2023-04-27-year-of-the-voice-chapter-2/assist-debug.png
  source/images/blog/2023-04-27-year-of-the-voice-chapter-2/social.png
Labels: blog, current

#27184 Change YOTV promo to point to blog post
  source/index.html
Labels: current

#27185 Add draft on exposing devices to Assist
  source/_includes/asides/docs_navigation.html
  source/docs/assist/voice_remote_expose_devices.markdown
Labels: in-progress, next, needs-rebase

#27166 Add Seeed Studio as a distributor for the HA Yellow
  source/yellow/index.html
Labels: current

#27192 Local Assist pipeline: Add link to video explainer of config options
  source/docs/assist/voice_remote_local_assistant.markdown
Labels: in-progress, next, needs-rebase

#27188 Local assist pipeline: update screenshot
  source/docs/assist/voice_remote_local_assistant.markdown
  source/images/assist/piper-whisper-install-02.png
Labels: in-progress, next, needs-rebase

#27191 VoIP tutorial: update troubleshooting section
  source/images/assist/assistant-debug-03.png
  source/images/assist/grandstream-troubleshoot-10.png
  source/projects/worlds-most-private-voice-assistant.markdown
Labels: in-progress, next, needs-rebase

#27195 Update URLs
  source/_integrations/kraken.markdown
  source/_integrations/qld_bushfire.markdown
  source/tos/index.markdown
Labels: current

#27186 Assist tutorials: fix order in aside TOC
  source/_includes/asides/docs_navigation.html
Labels: in-progress, next, needs-rebase
