Repository home-assistant/home-assistant.io, pull requests merged in 2023-03, with the labels that each got.

#26399 Update Insteon documentation
  source/_integrations/insteon.markdown
  source/images/integrations/insteon/insteon-panel.png
Labels: in-progress, next, needs-rebase

#26402 Revert "Update derivative.markdown"
  source/_integrations/derivative.markdown
Labels: in-progress, current, needs-rebase

#26408 Remove reference to non-implemented attributes
  source/_integrations/scrape.markdown
Labels: current

#26411 Add Heltun integration
  source/_integrations/heltun.markdown
Labels: in-progress, next, has-parent, needs-rebase

#26427 Use brand logos if ha_brand in search results
  source/integrations/index.html
Labels: current, has-parent

#26423 Clarify Thread border router credential sync
  source/_integrations/thread.markdown
Labels: current

#26439 Address breaking change for `systemd-journal-remote` in the supervised installation method
  source/more-info/unsupported/systemd_journal.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26438 Add unsupported model
  source/_integrations/reolink.markdown
Labels: current

#26434 Remove references to `ozw` and `zwave` from docs
  source/_integrations/zwave_js.markdown
Labels: current

#26417 Update 2023-03-01-release-20233.markdown
  source/_posts/2023-03-01-release-20233.markdown
Labels: current

#25957 Add climate devices documentation for LIVISI integration
  source/_integrations/livisi.markdown
Labels: next, has-parent, parent-merged

#25419 Add Camera to Prosegur
  source/_integrations/prosegur.markdown
Labels: next, has-parent, parent-merged

#26386 Adding Obihai codeowner
  source/_integrations/obihai.markdown
Labels: next, has-parent, parent-merged

#26415 HELTUN partnership announcement blog post
  source/_posts/2023-03-03-heltun-partner.markdown
  source/images/blog/2023-03-03-heltun-partner/heltun-top.png
  source/images/blog/2023-03-03-heltun-partner/marketing.jpg
  source/images/blog/2023-03-03-heltun-partner/social.png
Labels: blog, next, has-parent

#26450 Add RLC-410 Support
  source/_integrations/reolink.markdown
Labels: current

#26260 Update renault documentation - Add button section
  source/_integrations/renault.markdown
Labels: in-progress, next, has-parent, parent-merged

#26394 Document energy_storage and volume_storage device classes
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#26354 Add Config Flow to Obihai
  source/_integrations/obihai.markdown
Labels: next, has-parent, parent-merged

#26447 Update Assist docs references to Wear OS
  source/_includes/asides/docs_navigation.html
  source/docs/assist/android.markdown
  source/docs/assist/index.markdown
Labels: current

#26435 Add UI only features to zwave_js docs
  source/_integrations/zwave_js.markdown
Labels: current

#26458 Fix grammar
  source/_integrations/zwave_js.markdown
Labels: in-progress, current, needs-rebase

#26355 Add reolink button entities
  source/_integrations/reolink.markdown
Labels: next, has-parent

#25742 device_class and state_class
  source/_integrations/sql.markdown
Labels: awaits-parent, next, has-parent

#26353 Reolink add switch entities
  source/_integrations/reolink.markdown
Labels: next, has-parent

#26282 Add Reolink siren documentation
  source/_integrations/reolink.markdown
Labels: in-progress, next, has-parent

#26341 Add Reolink select entities
  source/_integrations/reolink.markdown
Labels: new-feature, next, has-parent

#26421 Improve the important notes
  source/_integrations/home_connect.markdown
Labels: in-progress, current

#26283 Add new Reolink number entities
  source/_integrations/reolink.markdown
Labels: new-feature, awaits-parent, next, has-parent

#26338 Add reolink light entities
  source/_integrations/reolink.markdown
Labels: next, has-parent

#26358 Google app setup clarification
  source/_integrations/google_mail.markdown
  source/_integrations/google_sheets.markdown
Labels: current

#26416 Add a Jasco integration page
  source/_integrations/jasco.markdown
Labels: in-progress, current, needs-rebase

#26385 Add Obihai Reboot button
  source/_integrations/obihai.markdown
Labels: in-progress, next, has-parent

#26441 Update signal_messenger.markdown
  source/_integrations/signal_messenger.markdown
Labels: current

#26469 Add clarification for reolink entities
  source/_integrations/reolink.markdown
Labels: next, has-parent

#25917 Honeywell updates
  source/_integrations/honeywell.markdown
Labels: in-progress, current

#26045 Added a note for crossing thresholds
  source/_docs/automation/trigger.markdown
Labels: current

#26331 Add Door cover documentation
  source/_integrations/homekit.markdown
Labels: awaits-parent, next, has-parent

#26480 Add Network configuration to default setup
  source/_integrations/default_config.markdown
Labels: current

#26474 Add PSSO and ISS(2) to Livisi supported devices
  source/_integrations/livisi.markdown
Labels: next, has-parent

#26493 Add Supervisor security disclosure blog
  source/_posts/2023-03-08-supervisor-security-disclosure.markdown
  source/images/blog/2023-03-supervisor-security-disclosure/social.png
Labels: blog, current

#26495 Add workaround FAQ to Supervisor Security Disclosure
  source/_posts/2023-03-08-supervisor-security-disclosure.markdown
Labels: current

#26500 Update url for joseph
  source/_posts/2023-03-08-supervisor-security-disclosure.markdown
Labels: current

#26501 Remove latest-security-alert redirect
  source/_redirects
Labels: current

#26494 Add non-color bulb to tested devices
  source/_integrations/fritzbox.markdown
Labels: next, has-parent, parent-merged

#26508 Add Reolink RLC-822A as supported
  source/_integrations/reolink.markdown
Labels: current

#26510 Update link (fixes #26509)
  source/_integrations/google_maps.markdown
Labels: current

#26473 Add info about restore
  source/installation/index.html
Labels: current

#26512 Add some terms to lint file
  .textlintrc.json
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: in-progress, current

#26517 Adding Denon AVR-S740H
  source/_integrations/denonavr.markdown
Labels: current

#26518 Add documentation for core and SU stats sensors
  source/_integrations/hassio.markdown
Labels: awaits-parent, next, has-parent

#26515 Improve Generic x86-64 installation instructions
  source/_includes/installation/operating_system.md
Labels: current

#26489 Add Air Purifier MA2 (zhimi.airpurifier.ma2) to xiaomi_miio
  source/_integrations/xiaomi_miio.markdown
Labels: awaits-parent, next, has-parent

#26519 2023.3.3
  _config.yml
  source/_posts/2023-03-01-release-20233.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26526 Remove "en" from myStrom URL
  source/_integrations/mystrom.markdown
Labels: current

#26525 Fix HomeMatic URLs
  source/_integrations/homematic.markdown
Labels: current

#26523 Remove "us" from TP-Link Omada URL
  source/_integrations/tplink_omada.markdown
Labels: current

#26528 Update SimpliSafe URL
  source/_integrations/simplisafe.markdown
Labels: current

#26303 List all areas with templating
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, next, has-parent

#18864 Update ZHA documentation with tips on improving Zigbee network range
  source/_integrations/zha.markdown
Labels: cla-signed, in-progress, current

#26551 Update workday URL
  source/_integrations/workday.markdown
Labels: current

#26556 Update proximity.markdown
  source/_integrations/proximity.markdown
Labels: current

#26552 Update Cisco IOS URL
  source/_integrations/cisco_ios.markdown
Labels: current

#26553 Update Sinch URL
  source/_integrations/sinch.markdown
Labels: current

#26555 Remove "nl" from HomeWizard Energy URL
  source/_integrations/homewizard.markdown
Labels: current

#26542 Add Jekyll terminology tooltip plugin
  plugins/terminology_tooltip.rb
  sass/custom/_terminology_tooltip.scss
  sass/screen.scss
  source/_data/glossary.yml
  source/_docs/glossary.markdown
  source/_docs/scripts.markdown
Labels: current, has-parent

#26547 Add Reolink RLC-833A and RLC-1224A to supported
  source/_integrations/reolink.markdown
Labels: current

#26529 Add concepts and terminology to getting started guide
  source/_includes/asides/getting_started_navigation.html
  source/getting-started/concepts-terminology.markdown
  source/getting-started/index.markdown
  source/getting-started/onboarding.markdown
  source/images/getting-started/add-ons.png
  source/images/getting-started/home-assistant-device.png
Labels: current

#26575 Fixed typing mistake in KNX integration documentation.
  source/_integrations/knx.markdown
Labels: current

#26564 Reordered pm25 and pm10
  source/_integrations/sensor.markdown
Labels: current

#26576 Change category of Google Assistant SDK to Voice
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#26549 Fix extra `data` property
  source/_integrations/html5.markdown
Labels: current

#26524 Remove revision history from Konnected integration
  source/_integrations/konnected.markdown
Labels: current

#26568 I think default is google_translate_say
  source/_integrations/notify.tts.markdown
Labels: current

#26548 Doc cleanup for Shark IQ
  source/_integrations/sharkiq.markdown
  source/images/screenshots/more-info-dialog-sharkiq.png
Labels: current

#26436 Documentation for Jinja import
  source/_docs/configuration/templating.markdown
  source/_integrations/homeassistant.markdown
Labels: awaits-parent, next, has-parent

#26535 Add docs for ESERA 1-Wire (virtual) integration
  source/_integrations/esera_onewire.markdown
Labels: awaits-parent, next, has-parent

#26580 iOS 16.4 will have support for html5 notifications
  source/_integrations/html5.markdown
Labels: current

#21238 Update frontier_silicon documentation
  source/_integrations/frontier_silicon.markdown
Labels: new-feature, cla-signed, in-progress, next, has-parent, parent-merged

#26429 Add is_hidden_entity documentation
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, next, has-parent

#26472 Update input_number.markdown
  source/_integrations/input_number.markdown
Labels: current

#26585 Update recorder with sqlite testing info and making backups with external dbs
  source/_integrations/recorder.markdown
Labels: current

#25643 Change SQL integration to use HA recorder db as default
  source/_integrations/sql.markdown
Labels: awaits-parent, next, has-parent

#26583 2023.3.4
  _config.yml
  source/_posts/2023-03-01-release-20233.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26565 Document tplink_omada update entities
  source/_integrations/tplink_omada.markdown
Labels: next, has-parent, parent-merged

#26591 Update SQL query examples for schema 40
  source/_integrations/sql.markdown
Labels: next, has-parent, parent-merged

#26571 Update fibaro integration documentation
  source/_integrations/fibaro.markdown
Labels: current

#26594 Update template.markdown
  source/_integrations/template.markdown
Labels: current

#26598 Change codeowner of statistics.markdown
  source/_integrations/statistics.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26601 Remove stale `refresh_interval` from history graph card docs
  source/_dashboards/history-graph.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26603 Replace component with integration
  source/_integrations/zabbix.markdown
Labels: current

#26558 Clarify documentation for calendar.create_event service event end dates
  source/_integrations/calendar.markdown
Labels: awaits-parent, next, has-parent

#25899 Update google_assistant.markdown
  source/_integrations/google_assistant.markdown
Labels: current

#26604 Small documentation improvements
  source/_integrations/snips.markdown
  source/_integrations/tuya.markdown
Labels: current

#26065 Update assist documentation
  source/docs/assist/index.markdown
Labels: current

#26613 Add info that EU version of Aeotec Z-Stick 7 ..
  source/_docs/z-wave/controllers.markdown
Labels: current

#26612 Clean up Rakefile
  Rakefile
Labels: current

#26619 Small documentation improvements (2)
  source/_integrations/gpslogger.markdown
  source/_integrations/my.markdown
  source/_integrations/pandora.markdown
  source/_integrations/proximity.markdown
Labels: current

#26617 Correct default scan_interval.
  source/_integrations/modbus.markdown
Labels: current

#26611 Add turn_on trigger to Samsung TV
  source/_integrations/samsungtv.markdown
Labels: next, has-parent, parent-merged

#26595 Add modbus write_registers keys
  source/_integrations/modbus.markdown
Labels: in-progress, next, has-parent, parent-merged

#26610 Add keep_days option to recorder.purge_entities
  source/_integrations/recorder.markdown
Labels: awaits-parent, next, has-parent

#26625 Put allowed policies together at front of command
  source/_integrations/mikrotik.markdown
Labels: current

#26563 Update pushsafer.markdown
  source/_integrations/pushsafer.markdown
Labels: next, has-parent, parent-merged

#26631 Update the Reolink integration page
  source/_integrations/reolink.markdown
Labels: current

#26626 Update the device entry in glossary
  source/_data/glossary.yml
  source/_docs/glossary.html
  source/_docs/glossary.markdown
Labels: current

#26632 2023.3.5
  _config.yml
  source/_posts/2023-03-01-release-20233.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26636 Add Marantz CINEMA 50 to known working devices
  source/_integrations/denonavr.markdown
Labels: current

#26637 typo fix
  source/_integrations/matter.markdown
Labels: current

#26596 Update documentation to make the possible settings for state_characteristic more searchable
  source/_integrations/statistics.markdown
Labels: current

#26588 Add Reolink doorbell quick reply entities
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#26635 Add docs for voice_assistant integration
  source/_integrations/voice_assistant.markdown
Labels: next, has-parent, parent-merged

#26641 Update glossary entry on entity
  source/_data/glossary.yml
Labels: current

#26646 Update information about Outbound Websocket
  source/_integrations/shelly.markdown
Labels: current

#26630 Document changed light white service call attribute
  source/_integrations/light.markdown
Labels: awaits-parent, next, has-parent

#26654 Update belkin and lookin URLs
  source/_integrations/lookin.markdown
  source/_integrations/wemo.markdown
Labels: current

#26655 Spotify Integration: link directly to dashboard page of Spotify Developers website
  source/_integrations/spotify.markdown
Labels: current

#26642 doc: virt-install in presence of USB dongle
  source/_includes/installation/operating_system.md
Labels: current

#26660 Update definition of service
  source/_data/glossary.yml
Labels: current

#26665 Add note prusalink only supports Prusa Mini
  source/_integrations/prusalink.markdown
Labels: current

#26667 Include optional default value in strptime
  source/_docs/configuration/templating.markdown
Labels: current

#26673 Add Marantz SR5015 as supported
  source/_integrations/denonavr.markdown
Labels: current

#26674 Add lock to matter ha_platforms
  source/_integrations/matter.markdown
Labels: next, has-parent

#26685 Standardize use of markup for UI elements
  source/getting-started/automation.markdown
Labels: current

#26683 Fix typo on automation editor page
  source/_docs/automation/editor.markdown
Labels: current

#26687 exclude resources from sitemap
  _config.yml
Labels: current

#25442 Add YoLink FlexFob support
  source/_integrations/yolink.markdown
Labels: next, has-parent, parent-merged

#26647 Add state to glossary
  source/_data/glossary.yml
Labels: current

#26691 2023.3.6
  _config.yml
  source/_posts/2023-03-01-release-20233.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26694 Add URLs to SwitchBot
  source/_integrations/switchbot.markdown
Labels: current

#26722 Delete Magicseaweed
  source/_integrations/magicseaweed.markdown
Labels: next, has-parent

#26726 Add Magicseaweed redirect 301
  source/_redirects
Labels: in-progress, next, needs-rebase

#26702 Small documentation improvements (4)
  source/_docs/scripts.markdown
  source/_docs/scripts/service-calls.markdown
  source/_integrations/apple_tv.markdown
  source/_integrations/zeroconf.markdown
Labels: current

#26728 Add location field to create_event service
  source/_integrations/google.markdown
Labels: next, has-parent

#26704 Remove reference to template sensors
  source/_integrations/solaredge.markdown
  source/_integrations/solaredge_local.markdown
Labels: current

#24704 Sun attributes to sensors
  source/_integrations/sun.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, hacktoberfest-accepted

#26676 Add Yellow to Getting started section
  source/images/installation/home-assistant-yellow-exploded-and-labeled.png
  source/images/installation/yellow-docs.png
  source/images/installation/yellow-logo-square.png
  source/images/installation/yellow-logo.png
  source/installation/index.html
  source/installation/yellow.html
Labels: current

#26486 Verisure
  source/_integrations/verisure.markdown
Labels: awaits-parent, next, has-parent

#26731 Add location field to create_event service
  source/_integrations/calendar.markdown
Labels: next, has-parent

#26706 Add warning about a window size larger than one with many states
  source/_integrations/filter.markdown
Labels: next, has-parent

#26712 Add WLED IP sensor
  source/_integrations/wled.markdown
Labels: in-progress, next, has-parent, parent-merged

#26503 Implement config flow for nextcloud
  source/_integrations/nextcloud.markdown
Labels: awaits-parent, next, has-parent

#26732 Small documentation improvements (5)
  source/_integrations/seventeentrack.markdown
Labels: current

#26734 Fix link to Yellow documentation
  source/installation/yellow.html
Labels: current

#26735 Correct terminology anchor links
  source/getting-started/concepts-terminology.markdown
Labels: current

#26689 Improve webhook trigger documentation
  source/_docs/automation/trigger.markdown
Labels: current

#26677 Add RTMP port troubleshooting step
  source/_integrations/reolink.markdown
Labels: in-progress, current, has-parent

#25160 Add device HmIP-DLD
  source/_integrations/homematicip_cloud.markdown
Labels: awaits-parent, next, has-parent

#25812 Add calendar entity to Ridwell documentation
  source/_integrations/ridwell.markdown
Labels: awaits-parent, next, has-parent

#26213 Added section about hourly weather forecast attributes
  source/_integrations/weather.markdown
Labels: current

#26287 Update influxdb.markdown
  source/_integrations/influxdb.markdown
Labels: in-progress, current
