Repository home-assistant/home-assistant.io, pull requests merged in 2023-02, with the labels that each got.

#26036 Update recorder documentation to clarify which versions and engine are supported
  source/_integrations/recorder.markdown
Labels: current

#26040 Add two newly tested bluetooth adapters
  source/_integrations/bluetooth.markdown
Labels: current

#26039 Copyedit LD2410 BLE section
  source/_posts/2023-02-01-release-20232.markdown
Labels: in-progress, needs-rebase, rc

#26041 Updated OpenAI documentation
  source/_integrations/openai_conversation.markdown
Labels: next, has-parent, parent-merged

#25907 Addition of doc for PR in iframe card
  source/_dashboards/iframe.markdown
Labels: next, has-parent, parent-merged

#25653 Google Assistant SDK: Document audio response playback
  source/_integrations/google_assistant_sdk.markdown
Labels: next, has-parent, parent-merged

#26048 Update required permissions for fritzbox_callmonitor
  source/_integrations/fritzbox_callmonitor.markdown
Labels: next, has-parent

#26053 2023.2: Update changelog, fix broken link
  source/_posts/2023-02-01-release-20232.markdown
  source/changelogs/core-2023.2.markdown
Labels: current

#26067 Fix style issues in HomeWizard documentation
  source/_integrations/homewizard.markdown
Labels: current

#26066 Remove paper item icon color reference
  source/_dashboards/picture-elements.markdown
Labels: current

#26050 Add vertical option to tile card
  source/_dashboards/tile.markdown
Labels: current

#26055 Correct documentaion links to templating docs
  source/_docs/automation/troubleshooting.markdown
  source/_docs/configuration/templating.markdown
  source/_docs/scripts/conditions.markdown
  source/_docs/scripts/service-calls.markdown
  source/_integrations/alexa.flash_briefings.markdown
  source/_integrations/alexa.intent.markdown
  source/_integrations/generic.markdown
  source/_integrations/history_stats.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/notify.markdown
  source/_integrations/persistent_notification.markdown
  source/_integrations/rss_feed_template.markdown
  source/_integrations/switch.rest.markdown
  source/_integrations/universal.markdown
  source/_integrations/vacuum.mqtt.markdown
Labels: current

#26056 Fixed grammer
  source/_integrations/thread.markdown
Labels: current

#26072 Add blueprint author name
  source/_docs/blueprint/schema.markdown
Labels: next, has-parent

#26081 Fix typo in xiomi_miio.markdown
  source/_integrations/xiaomi_miio.markdown
Labels: current

#26077 Update Reolink documentation
  source/_integrations/reolink.markdown
Labels: current

#26092 Document new select entity services
  source/_integrations/select.markdown
Labels: next, has-parent

#26076 Add basic thread docs
  source/_integrations/thread.markdown
Labels: current

#26086 Correct yaml statement to enable debug
  source/_integrations/modbus.markdown
Labels: current, by-code-owner

#26093 Update google_assistant_sdk.markdown
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#26091 Update mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: current

#26083 Update aquostv.markdown
  source/_integrations/aquostv.markdown
Labels: current

#26080 Correct API Naming
  source/_integrations/google_mail.markdown
Labels: current

#26069 Starlink updated bypass mode warning
  source/_integrations/starlink.markdown
Labels: current

#25370 Add docs for new ONVIF aux command.
  source/_integrations/onvif.markdown
Labels: next, has-parent, parent-merged

#24118 Update zha.markdown ZHA quirks handling
  source/_integrations/zha.markdown
Labels: cla-signed, in-progress, current

#26078 Reolink add number platform
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent

#25925 Update sql.markdown
  source/_integrations/sql.markdown
Labels: current

#25871 Add docs for easyEnergy integration
  source/_integrations/easyenergy.markdown
Labels: new-integration, awaits-parent, next, has-parent

#26116 Add repeat options to tplink sequence effect docs
  source/_integrations/tplink.markdown
Labels: next, has-parent

#26118 2023.2.2
  _config.yml
  source/_posts/2023-02-01-release-20232.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26135 Add missing QNAP QSW documentation
  source/_integrations/qnap_qsw.markdown
Labels: current

#26130 Fix spelling
  source/index.html
Labels: current

#26128 Adjust capitalization on litterrobot entity names
  source/_integrations/litterrobot.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26136 Add SkyConnect as hardware option for ezsp radio type
  source/_integrations/zha.markdown
Labels: current

#26134 Use more inclusive terminology in Airzone
  source/_integrations/airzone.markdown
Labels: in-progress, current, needs-rebase

#26132 Update link to GPSD Project.
  source/_integrations/gpsd.markdown
Labels: current

#26110 Fix documentation on Alexa media player support
  source/_integrations/alexa.smart_home.markdown
Labels: current

#26155 Remove en_us fron synology srm URL
  source/_integrations/synology_srm.markdown
Labels: current

#26064 Add `suggested_display_precision` config setting for MQTT sensor
  source/_integrations/mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: next, has-parent, parent-merged

#26158 Fix little format issue
  source/_integrations/person.markdown
Labels: current

#26154 Remove en_us from synology URL
  source/_integrations/synology_dsm.markdown
Labels: current

#26143 Update matter documentation
  source/_integrations/matter.md
Labels: current

#26100 Fix Enphase Envoy documentation link
  source/_integrations/enphase_envoy.markdown
Labels: current

#26160 2023.2.3
  _config.yml
  source/_posts/2023-02-01-release-20232.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26163 Add battery sensor to Elgato
  source/_integrations/elgato.markdown
Labels: next, has-parent, parent-merged

#26164 Add studio mode switch to Elgato
  source/_integrations/elgato.markdown
Labels: next, has-parent, parent-merged

#26169 Make the "Order Now" dialog scrollable
  source/skyconnect/index.html
Labels: current

#26165 Extend troubleshooting section of Matter docs
  source/_integrations/matter.markdown
Labels: current

#26172 Add blog post about Matter
  source/_posts/2023-02-08-state-of-matter-and-thread.markdown
  source/images/blog/2023-02-08-state-of-matter-and-thread/android-thread.png
  source/images/blog/2023-02-08-state-of-matter-and-thread/thread-mockup.png
Labels: blog, current

#26176 Update yaml.markdown
  source/_docs/automation/yaml.markdown
Labels: current

#26205 Removed duplicate YAML example.
  source/docs/assist/custom_sentences.markdown
Labels: current

#26208 Fix Starlink docs stating sensors use Mbit/s
  source/_integrations/starlink.markdown
Labels: current

#26203 Update denonavr.markdown
  source/_integrations/denonavr.markdown
Labels: current

#26181 Add Reolink TrackMix PoE to Tested models
  source/_integrations/reolink.markdown
Labels: current

#26131 Add documentation for dormakaba_dkey
  source/_integrations/dormakaba_dkey.markdown
Labels: next, has-parent, parent-merged

#26215 Fix typo of 'dining' in Templating Documentation
  source/_docs/configuration/templating.markdown
Labels: current

#26216 Update Google Calendar Cloud Console instructions
  source/_integrations/google.markdown
Labels: current

#26209 Update alexa.intent.markdown
  source/_integrations/alexa.intent.markdown
Labels: current

#26201 Specify required Mastodon API permissions
  source/_integrations/mastodon.markdown
Labels: current

#26149 Add genius X and 10000 and add disclaimer for supported devices
  source/_integrations/oralb.markdown
Labels: current

#26182 Add SwitchBot-MQTT-BLE-ESP32 to third-party tools supporting MQTT auto-discovery
  source/_integrations/mqtt.markdown
Labels: current

#26183 Add recorder engine to analytics documentation
  source/_integrations/analytics.markdown
Labels: next, has-parent, parent-merged

#26225 Convert map to list in InfluxDB 1.x example
  source/_integrations/influxdb.markdown
Labels: current

#26231 Document dormakaba_dkey battery sensor
  source/_integrations/dormakaba_dkey.markdown
Labels: next, has-parent

#25790 Add documentation for DenonAVR telnet feature
  source/_integrations/denonavr.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#26239 Update energy example in Scrape
  source/_integrations/scrape.markdown
Labels: current

#26232 Document dormakaba_dkey door and dead bolt binary sensors
  source/_integrations/dormakaba_dkey.markdown
Labels: next, has-parent, parent-merged

#26258 Update imap_email_content.markdown
  source/_integrations/imap_email_content.markdown
Labels: current

#26257 Added third reality to the OTA provider list
  source/_integrations/zha.markdown
Labels: current

#26253 Add information about Shelly `triple_push` event
  source/_integrations/shelly.markdown
Labels: next, has-parent

#26264 2023.2.5
  _config.yml
  source/_posts/2023-02-01-release-20232.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26271 Fix capitalization of OwnTone integration
  source/_integrations/forked_daapd.markdown
  source/_integrations/media_player.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26127 Switchbot blind tilt support
  source/_integrations/switchbot.markdown
Labels: new-feature, next, has-parent

#26266 Specify qos is also used for MQTT lock command topic
  source/_integrations/lock.mqtt.markdown
Labels: current

#26268 Update providers.markdown
  source/_docs/authentication/providers.markdown
Labels: current

#26276 Add newly tested bluetooth adapters
  source/_integrations/bluetooth.markdown
Labels: current

#26285 Add reolink troubleshooting
  source/_integrations/reolink.markdown
Labels: current

#26305 Update keymitt_ble.markdown
  source/_integrations/keymitt_ble.markdown
Labels: current

#25967 Update list of configuration variables that blocks editing General Settings in UI
  source/_docs/configuration/basic.markdown
Labels: current

#26153 Update statistics-graph.markdown
  source/_dashboards/statistics-graph.markdown
Labels: current

#26244 Single quotes in the template example make the yaml invalid
  source/_integrations/london_air.markdown
Labels: current

#26307 Update Google Nest doc with Nest Doorbell support
  source/_integrations/nest.markdown
Labels: current

#24753 Documentation for proposed TP-Link Omada integration
  source/_integrations/tplink_omada.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, parent-merged, hacktoberfest-accepted

#26223 Allow resetting MQTT climate attributes
  source/_integrations/climate.mqtt.markdown
Labels: next, has-parent, parent-merged

#25215 add ecobee ventilator documentation
  source/_integrations/ecobee.markdown
Labels: in-progress, next, has-parent, parent-merged

#26175 Document rounded and with_unit arguments to states template function
  source/_docs/configuration/templating.markdown
Labels: in-progress, next, has-parent, parent-merged

#26026 Explain special values for MQTT numeric sensor
  source/_integrations/sensor.mqtt.markdown
Labels: next, has-parent, parent-merged

#26184 Add homeassistant.reload_all service
  source/_integrations/homeassistant.markdown
Labels: next, has-parent, parent-merged

#26313 Add option to hide legend on statistic graph card
  source/_dashboards/statistics-graph.markdown
Labels: awaits-parent, next, has-parent

#26269 Update KNX Secure documentation for Data Secure
  source/_integrations/knx.markdown
Labels: awaits-parent, next, has-parent

#26316 Add HA Yellow website
  sass/custom/_landingpage.scss
  source/blue/index.html
  source/images/yellow/home-assistant-yellow-exploded-and-labeled.png
  source/images/yellow/yellow-2d.jpg
  source/images/yellow/yellow-kit-2d.jpg
  source/images/yellow/yellow-kit-poe-2d.jpg
  source/images/yellow/yellow-pcb-preview.jpg
  source/images/yellow/yellow-poe-box-preview.jpg
  source/images/yellow/yellow-preview.jpg
  source/images/yellow/yellow_hero.jpg
  source/index.html
  source/skyconnect/index.html
  source/yellow/index.html
Labels: current

#26173 Add HomeKit VOC mappings
  source/_integrations/homekit.markdown
Labels: next, has-parent

#26317 Document templating `for` in state conditions
  source/_docs/scripts/conditions.markdown
Labels: next, has-parent

#25853 Add Aux heat details for Ecobee
  source/_integrations/ecobee.markdown
Labels: new-feature, next, has-parent

#26325 Fix typo (dependency's → dependencies)
  source/_includes/installation/operating_system.md
Labels: current

#26327 Transmission now supports daemon 3.0
  source/_integrations/transmission.markdown
Labels: in-progress, current, has-parent, needs-rebase

#26321 Color yellow buttons
  sass/custom/_landingpage.scss
  source/yellow/index.html
Labels: current

#26333 Fix spelling error in min_max
  source/_integrations/min_max.markdown
Labels: current

#26207 Add Reolink update entity
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent

#26342 Fix: Typo in airq.markdown
  source/_integrations/airq.markdown
Labels: current

#26343 Add Reolink C2 pro as supported
  source/_integrations/reolink.markdown
Labels: current

#26347 2023.3: Update KNX change description
  source/_posts/2023-03-01-release-20233.markdown
Labels: in-progress, has-parent, needs-rebase, rc

#25697 Allow override browse media in universal media player
  source/_integrations/universal.markdown
Labels: awaits-parent, next, has-parent

#25837 Samsung TV keeps asking for permission
  source/_integrations/samsungtv.markdown
Labels: current

#26363 Add ISY994 services to set and delete lock codes
  source/_integrations/isy994.markdown
Labels: next, has-parent

#26352 Update timer.markdown
  source/_integrations/timer.markdown
Labels: current

#26349 Clarify the example is below the sentence
  source/_docs/configuration/templating.markdown
Labels: next

#26375 Add DIGITUS DN-30210-1 to the CSR based dongle list
  source/_integrations/bluetooth.markdown
Labels: current
