Repository home-assistant/home-assistant.io, pull requests merged in 2024-10, with the labels that each got.

#34989 Update mikrotik.markdown
  source/_integrations/mikrotik.markdown
Labels: current

#34993 Cover integrations: Fix typo
  source/_integrations/cover.markdown
Labels: Hacktoberfest, current

#34995 Terminology: move devices before entities
  source/getting-started/concepts-terminology.markdown
Labels: Hacktoberfest, current

#34997 Dashboards: add step on adding new default db
  source/_includes/dashboard/edit_dashboard.md
  source/dashboards/dashboards.markdown
  source/getting-started/onboarding_dashboard.markdown
Labels: Hacktoberfest, current

#34994 Matter integration: fix manufacturer name
  source/_integrations/matter.markdown
Labels: Hacktoberfest, current

#34906 Add valve platform to Matter integration docs
  source/_integrations/matter.markdown
Labels: next, has-parent, parent-merged

#34990 Additions 2024.10 release notes
  source/_posts/2024-10-02-release-202410.markdown
  source/images/blog/2024-10/statistics-repair.jpg
Labels: Hacktoberfest, in-progress, needs-rebase, rc

#35003 Clarify appropriate return values for an endpoint
  source/_integrations/binary_sensor.rest.markdown
Labels: Hacktoberfest, current

#35004 Recommend Mobility Database over TransitFeeds for GTFS data
  source/_integrations/gtfs.markdown
Labels: Hacktoberfest, current

#35008 Add Reolink RLC-843A to list of supported models
  source/_integrations/reolink.markdown
Labels: Hacktoberfest, current

#35010 Update sidebar.markdown to correct badges support.
  source/_dashboards/sidebar.markdown
Labels: Hacktoberfest, current

#35011 Sidebar view: update
  source/_dashboards/sidebar.markdown
  source/images/dashboards/sidebar_view_move_card.png
  source/images/dashboards/view_edit_config.png
Labels: Hacktoberfest, current

#34999 Map card: add steps on changing home location, adding entities and zones
  source/_dashboards/map.markdown
  source/images/dashboards/map_card_config.png
Labels: Hacktoberfest, current

#35012 Add DD7006A Smart Home bridge as supported by Motion Blinds
  source/_integrations/motion_blinds.markdown
Labels: Hacktoberfest, in-progress, current

#35013 Remove documentation for the Google Domains integration
  source/_integrations/google_domains.markdown
  source/_redirects
Labels: Hacktoberfest, next, has-parent, parent-merged

#35017 Glossary: add YAML definition
  source/_data/glossary.yml
  source/_docs/automation/using_blueprints.markdown
  source/_docs/automation/yaml.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/configuration/secrets.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/scene.markdown
  source/_docs/scene/editor.markdown
  source/_docs/troubleshooting_general.markdown
  source/_includes/common-tasks/configuration_check.md
Labels: Hacktoberfest, current

#35018 Fix template syntax error
  source/_integrations/template.markdown
Labels: Hacktoberfest, in-progress, next, needs-rebase

#35022 Connect ZBT-1 issue and replacement blog
  source/_posts/2024-10-02-connect-zbt1-issue-and-replacement.markdown
  source/images/blog/2024-10-zbt1-issue/art.jpg
  source/images/blog/2024-10-zbt1-issue/zbt1-issue.jpg
Labels: Hacktoberfest, current

#35025 Fix wrong action in Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: Hacktoberfest, current

#35019 OWM: mention correct deprecation date for Onecall API 2.5
  source/_integrations/openweathermap.markdown
Labels: Hacktoberfest, current

#35035 Blog: add some YAML term refs
  source/_posts/2024-10-02-release-202410.markdown
Labels: Hacktoberfest, current

#35036 sections view: add dense placement option
  source/_dashboards/sections.markdown
Labels: Hacktoberfest, current

#35037 Connect ZBT-1: add FAQ on replacement program
  source/connectzbt1/index.html
Labels: Hacktoberfest, current

#35038 Add context for JMALLOC issues
  source/_includes/installation/container.md
Labels: Hacktoberfest, current

#35052 Fix dashboard heading YAML example
  source/_dashboards/heading.markdown
Labels: Hacktoberfest, current

#35023 Remove Spider integration
  source/_integrations/spider.markdown
  source/_redirects
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35066 Update traccar_server.markdown - Fix Broken Links
  source/_integrations/traccar_server.markdown
Labels: Hacktoberfest, current

#35057 Blueprints for template entities
  source/_data/glossary.yml
  source/_docs/blueprint.markdown
  source/_docs/blueprint/schema.markdown
  source/_integrations/template.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35070 Update gardena_bluetooth.markdown
  source/_integrations/gardena_bluetooth.markdown
Labels: Hacktoberfest, current

#35074 A couple small fixes for 'service' to 'action' renames in automations
  source/_docs/automation/trigger.markdown
  source/_docs/automation/yaml.markdown
Labels: Hacktoberfest, current

#35058 Update ibeacon.markdown - Fix Broken Links
  source/_integrations/ibeacon.markdown
Labels: Hacktoberfest, current

#35084 Clearify the use of the mqtt sensor `options` option
  source/_integrations/sensor.mqtt.markdown
Labels: Hacktoberfest, current, by-code-owner, integration: mqtt

#35097 Add deprecation notice for Teams connector
  source/_integrations/msteams.markdown
Labels: Hacktoberfest, current

#35102 Add documentation on local-only Unifi users
  source/_integrations/unifi.markdown
Labels: Hacktoberfest, current

#35091 Update unit of measurement in A. O. Smith docs
  source/_integrations/aosmith.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, parent-merged

#34662 Add climate platform to LG ThinQ integration
  source/_integrations/lg_thinq.markdown
Labels: in-progress, has-parent, needs-rebase, parent-merged

#35086 Add category To-do list and related links for Habitica integration
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, current

#35047 Add preset action to LinkPlay documentation
  source/_integrations/linkplay.md
Labels: Hacktoberfest, current

#35071 Update govee_ble.markdown
  source/_integrations/govee_ble.markdown
Labels: Hacktoberfest, current

#35064 Remove missing sensors from Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: Hacktoberfest, current

#35085 Add sensor descriptions in Habitica integration
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35069 Update color_extractor.markdown - Fix Broken Link
  source/_integrations/color_extractor.markdown
Labels: Hacktoberfest, current

#35068 Update eddystone_temperature.markdown
  source/_integrations/eddystone_temperature.markdown
Labels: Hacktoberfest, current

#35061 Remove broken link from edl21 documentation
  source/_integrations/edl21.markdown
Labels: Hacktoberfest, current

#35088 Add description for cast_skill action in Habitica integration
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35083 Add 'always use new connection' configuration option to Enphase Envoy docs
  source/_integrations/enphase_envoy.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35006 Add work area sensors for Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35115 Xiaomi Aquara: move lock docs to hub
  source/_integrations/lock.xiaomi_aqara.markdown
  source/_integrations/xiaomi_aqara.markdown
  source/_redirects
Labels: Hacktoberfest, current

#35114 fix: prevent linked doc headings from disappearing behind page header
  sass/homeassistant/_overrides.scss
Labels: Hacktoberfest, current

#35113 Xiaomi aquara hub 2 issues accessing api: make note more prominent
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35120 Xiaomi Aquara: move cover docs to hub page
  source/_integrations/cover.xiaomi_aqara.markdown
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35126 Add note on command template for binary sensor and sensor in command_line
  source/_integrations/command_line.markdown
Labels: Hacktoberfest, current

#34911 Add Grid status sensor to Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35125 Use note block in Systemmonitor
  source/_integrations/systemmonitor.markdown
Labels: Hacktoberfest, current

#35119 Xiaomi Aquara: move binary sensor content to hub page
  source/_integrations/binary_sensor.xiaomi_aqara.markdown
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35128 ZBT-1 blog additions
  source/_posts/2024-10-02-connect-zbt1-issue-and-replacement.markdown
  source/images/blog/2024-10-zbt1-issue/skyconnect-zbt1.png
Labels: Hacktoberfest, current

#35123 Update ring docs for in-home chime switch
  source/_integrations/ring.markdown
Labels: Hacktoberfest, current

#34640 Update Ambient Weather local integration documentation
  source/_integrations/ambient_station.markdown
Labels: current

#35137 Xiaomi move light to hub docs
  source/_integrations/light.xiaomi_aqara.markdown
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35141 Xiaomi Aqara: Move switch to hub docs
  source/_integrations/switch.xiaomi_aqara.markdown
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35134 Xiaomi Aquara hub: convert large table to list
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35138 Xiaomi Aquara: move sensor into hub docs
  source/_integrations/xiaomi_aqara.markdown
Labels: Hacktoberfest, current

#35148 Xiaomi Aqara: add missing redirects after docs page consolidation
  source/_redirects
Labels: Hacktoberfest, current

#35143 Xiaomi Miio: convert tables to lists to improve readability and display on mobile
  source/_integrations/xiaomi_miio.markdown
Labels: Hacktoberfest, current

#35135 Unifi: Convert table with long unbreakable term into list
  source/_integrations/unifiprotect.markdown
Labels: Hacktoberfest, current

#35151 Fix example
  source/_dashboards/heading.markdown
Labels: Hacktoberfest, current

#35157 RFLink: merge sensor into main docs
  source/_integrations/rflink.markdown
  source/_integrations/sensor.rflink.markdown
  source/_redirects
Labels: Hacktoberfest, current

#35155 RFLink: Merge light into main docs
  source/_integrations/light.rflink.markdown
  source/_integrations/rflink.markdown
  source/_redirects
Labels: Hacktoberfest, current

#35153 RFLink: move binary sensor into main docs
  source/_integrations/binary_sensor.rflink.markdown
  source/_integrations/rflink.markdown
  source/_redirects
Labels: Hacktoberfest, current

#35159 Put S3 Box 3 first in tutorial
  source/voice_control/s3_box_voice_assistant.markdown
Labels: Hacktoberfest, current

#35154 RFLink: merge cover into main docs
  source/_integrations/cover.rflink.markdown
  source/_integrations/rflink.markdown
  source/_redirects
Labels: Hacktoberfest, current

#35147 Xiaomi: merge camera and router pages
  source/_integrations/device_tracker.xiaomi.markdown
  source/_integrations/xiaomi.markdown
  source/_redirects
Labels: Hacktoberfest, current

#35163 Correct entity-filter.markdown
  source/_dashboards/entity-filter.markdown
Labels: Hacktoberfest, current

#34871 Add Jellyfin remote
  source/_integrations/jellyfin.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35152 Docs for 'Allow override entity_id in more-info action'
  source/dashboards/actions.markdown
Labels: Hacktoberfest, next, has-parent

#35164 Xiaomi: fix typos
  source/_integrations/rflink.markdown
Labels: Hacktoberfest, current

#34887 Add scene support to WMS WebControl pro
  source/_integrations/wmspro.markdown
Labels: next, has-parent, parent-merged

#35170 Add todo-list hide_completed option
  source/_dashboards/todo-list.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35180 2024.10.2
  _config.yml
  source/_posts/2024-10-02-release-202410.markdown
  source/changelogs/core-2024.10.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase, parent-merged

#35178 Update people to reflect missing users from blog posts
  source/_data/people.yml
  source/_includes/post/author.html
Labels: Hacktoberfest, current

#35197 Improve the documentation on the accepted states on `state_topic` for MQTT entities
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
Labels: Hacktoberfest, current, by-code-owner, integration: mqtt

#35202 Add switch for Shelly script
  source/_integrations/shelly.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35203 Fix template syntax in imap.markdown
  source/_integrations/imap.markdown
Labels: Hacktoberfest, current

#35131 Move entities from 'select' platform to 'switch' platform
  source/_integrations/lg_thinq.markdown
Labels: Hacktoberfest, in-progress, has-parent, needs-rebase, parent-merged

#35093 docs(renault): add pack information
  source/_integrations/renault.markdown
Labels: Hacktoberfest, current

#35222 Add polling times to Mealie integration
  source/_integrations/mealie.markdown
Labels: Hacktoberfest, current

#35221 Add polling interval details to Mastodon
  source/_integrations/mastodon.markdown
Labels: Hacktoberfest, current

#35219 Mention command_and_search model for Google Cloud STT
  source/_integrations/google_cloud.markdown
Labels: Hacktoberfest, current

#35238 Update Cambirdge Audio supported devices
  source/_integrations/cambridge_audio.markdown
Labels: Hacktoberfest, current

#35233 Update example in feedreader docs
  source/_integrations/feedreader.markdown
Labels: Hacktoberfest, current

#34624 Document missing `hue` and `sat` variables in MQTT Template Schema Light
  source/_integrations/light.mqtt.markdown
Labels: current

#35251 Add new WeHeat temperature sensors
  source/_integrations/weheat.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35265 Opening HTTP(s) port no longer needed
  source/_integrations/reolink.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35282 2024.10.3
  _config.yml
  source/_posts/2024-10-02-release-202410.markdown
  source/changelogs/core-2024.10.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase, parent-merged

#35284 Update mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: Hacktoberfest, current

#35281 Add SSL protocol to apache_kafka component
  source/_integrations/apache_kafka.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35053 Update modbus switch status verify
  source/_integrations/modbus.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#34872 Add select platform to LG ThinQ integration
  source/_integrations/lg_thinq.markdown
Labels: in-progress, has-parent, needs-rebase, parent-merged

#35288 Add S1255 to the list of known working nibe heatpumps
  source/_integrations/nibe_heatpump.markdown
Labels: Hacktoberfest, current

#35317 Onboarding: update screenshots
  source/getting-started/onboarding.markdown
  source/images/getting-started/onboarding_preparing_01_.png
  source/images/getting-started/onboarding_preparing_02.png
  source/images/getting-started/onboarding_username.png
  source/images/getting-started/username.png
Labels: Hacktoberfest, current

#35101 Add docs for Omada device sensors
  source/_integrations/tplink_omada.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35304 Add humidity to KNX climate
  source/_integrations/knx.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#34723 Add config flow to local_file
  source/_integrations/local_file.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35267 Remove documentation of entity_id camera action service template variable
  source/_integrations/camera.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35289 Add clarity on what the YAML keys actually mean
  source/more-info/local-media/setup-media.markdown
Labels: Hacktoberfest, current

#34266 Add HmIP-FALMOT-C12 valve sensors to HomematicIP Cloud docs
  source/_integrations/homematicip_cloud.markdown
Labels: next, has-parent, parent-merged

#34722 Document Airzone Cloud zone switch entities
  source/_integrations/airzone_cloud.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#34443 Document Airzone zone switch entities
  source/_integrations/airzone.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#29612 Add documentation for new ecobee.set_sensors_in_climate Service
  source/_integrations/ecobee.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35290 Update La Marzocco Documentation
  source/_integrations/lamarzocco.markdown
Labels: Hacktoberfest, current

#35335 Update tedee documentation
  source/_integrations/tedee.markdown
Labels: Hacktoberfest, current

#35118 Remove universal XZG Firmware under recommended adapters
  source/_integrations/zha.markdown
Labels: Hacktoberfest, in-progress, current, needs-rebase

#35342 Improve UniFi documentation
  source/_integrations/unifi.markdown
  source/images/integrations/unifi/user.png
Labels: Hacktoberfest, current

#35352 Fix typo in media extractor
  source/_integrations/media_extractor.markdown
Labels: Hacktoberfest, current

#35353 Polling interval: add definition
  source/common-tasks/general.markdown
Labels: Hacktoberfest, current

#35366 Glossary: add polling
  source/_data/glossary.yml
Labels: Hacktoberfest, current

#35368 Wake word collective blog
  source/_posts/2024-10-24-wake-word-collective.markdown
  source/images/blog/2024-10-wake-word-collective/art.jpg
  source/images/blog/2024-10-wake-word-collective/demo.gif
Labels: Hacktoberfest, current

#35372 Troubleshooting assist with local URL
  source/images/assist/local_url.png
  source/voice_control/troubleshooting.markdown
Labels: Hacktoberfest, current

#35371 Remove DHCP from awair
  source/_integrations/awair.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35329 Add Meter Pro support to SwitchBot
  source/_integrations/switchbot.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35369 Add config flow to Smarty
  source/_integrations/smarty.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#34884 Buttons for class-based skills in Habitica integration
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#31327 Add services docs for image entity
  source/_integrations/image.markdown
Labels: next, has-parent, parent-merged

#33624 Adds limited templates for time triggers
  source/_docs/automation/trigger.markdown
Labels: next, has-parent, parent-merged

#34919 Add Lektrico switches documentation
  source/_integrations/lektrico.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#33070 Add OSO Energy Service documentation
  source/_integrations/osoenergy.markdown
Labels: next, has-parent, parent-merged

#34220 Update docs for home-assistant/core#123427
  source/_docs/scripts.markdown
Labels: next, has-parent, parent-merged

#35196 restore play on roku docs
  source/_integrations/roku.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase, parent-merged

#35351 Document WebRTC configuration
  source/_integrations/homeassistant.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35218 Mention the legacy tts.google_cloud_say
  source/_integrations/google_cloud.markdown
Labels: Hacktoberfest, current

#35293 Overhaul AVM FRITZ!SmartHome docs
  source/_integrations/fritzbox.markdown
Labels: Hacktoberfest, current

#35145 Update weather.markdown
  source/_integrations/weather.markdown
Labels: Hacktoberfest, current

#35334 blebox: add integration documentation for blebox floodSensor devices
  source/_integrations/blebox.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#35377 Weather: differentiate between UI string and YAML key
  source/_integrations/weather.markdown
Labels: Hacktoberfest, current

#35336 blebox: add documentation for dacBoxD DC device integration
  source/_integrations/blebox.markdown
Labels: Hacktoberfest, current

#35337 blebox: update lightBox and lightBox PRO device documentation
  source/_integrations/blebox.markdown
Labels: Hacktoberfest, current

#35370 Assist: add steps to start on iPhone
  source/voice_control/apple.markdown
Labels: Hacktoberfest, current

#35129 Add device model for Refoss
  source/_integrations/refoss.markdown
Labels: Hacktoberfest, awaits-parent, in-progress, next, has-parent, parent-merged

#34273 Add docs for Schlage "Auto Lock Time"
  source/_integrations/schlage.markdown
Labels: next, has-parent, parent-merged

#35239 Add `entity_picture` property to mqtt entity platforms config options
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/event.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/image.mqtt.markdown
  source/_integrations/lawn_mower.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/notify.mqtt.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/text.mqtt.markdown
  source/_integrations/valve.mqtt.markdown
  source/_integrations/water_heater.mqtt.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged, by-code-owner, integration: mqtt

#35257 Remove obsolete 1 hour rain forecast partial support
  source/_integrations/meteo_france.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, needs-rebase, parent-merged

#35208 Add light support to WMS WebControl pro
  source/_integrations/wmspro.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#34938 Adds description for `List access` sensor in Bring integration
  source/_integrations/bring.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#34833 Add sensor platform to LG ThinQ integration
  source/_integrations/lg_thinq.markdown
Labels: in-progress, has-parent, needs-rebase, parent-merged

#35256 Add switch entity to Cambridge Audio
  source/_integrations/cambridge_audio.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, parent-merged

#35388 2024.10.4
  _config.yml
  source/_posts/2024-10-02-release-202410.markdown
  source/changelogs/core-2024.10.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#35327 Add blueprint/automation examples for Habitica
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, current

#35381 Make Google Assistant SDK docs fit in smaller screens
  source/_integrations/google_assistant_sdk.markdown
Labels: Hacktoberfest, current

#35380 Make a heading in Google Generative AI docs shorter to make it fit in smaller screens
  source/_integrations/google_generative_ai_conversation.markdown
Labels: Hacktoberfest, current

#35283 Fix documentation: update invalid example of venetian blind in `cover.mqtt.markdown`
  source/_integrations/cover.mqtt.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase
