Repository home-assistant/home-assistant.io, pull requests merged in 2024-03, with the labels that each got.

#31587 Add fan and lights support to Balboa Spa integration docs
  source/_integrations/balboa.markdown
Labels: next, has-parent, parent-merged

#31690 Dashboards: Fix typo
  source/dashboards/index.markdown
Labels: current

#31696 Add section about default dashboards
  source/_includes/asides/dashboards_navigation.html
  source/dashboards/dashboards.markdown
Labels: current

#31694 Calendar card: remove section to minimize redundancy
  source/_dashboards/calendar.markdown
Labels: current

#31693 Masonry: Add image illustrating the arrangement system
  source/_dashboards/masonry.markdown
  source/images/dashboards/masonry.png
Labels: current

#31691 Dashboards: add page on sections view
  source/_dashboards/sections.markdown
  source/_includes/asides/dashboards_navigation.html
Labels: next, has-parent

#31698 Add building block info for file_upload integration
  source/_integrations/file_upload.markdown
Labels: current

#31642 Add link to Daikin Developer Portal
  source/_integrations/daikin.markdown
Labels: current

#31699 Streamline terminology around panel and dashboard
  source/_docs/energy/faq.markdown
  source/dashboards/dashboards.markdown
Labels: current

#31491 Document grid import / export and energy dashboard use for Enphase Envoy.
  source/_integrations/enphase_envoy.markdown
Labels: new-feature, next, has-parent, parent-merged

#31658 Advanced configuration: add subtitles
  source/_docs/configuration/splitting_configuration.markdown
Labels: current

#31703 Assist: add examples of new builtin sentences
  source/voice_control/builtin_sentences.markdown
Labels: in-progress, next, needs-rebase

#31657 Update yolink supported device list
  source/_integrations/yolink.markdown
Labels: new-feature, next, has-parent, parent-merged

#31705 Move Ping binary sensor attributes to sensor entities
  source/_integrations/ping.markdown
Labels: new-feature, next, has-parent

#31719 Add Reolink package detection docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#31708 Add Reolink connection drop troubleshooting
  source/_integrations/reolink.markdown
Labels: current

#31721 Add Reolink PTZ patrol docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#31713 Add additional method to get telegram id
  source/_integrations/telegram.markdown
Labels: current

#31559 Document energy devices detail card
  source/_dashboards/energy.markdown
  source/images/dashboards/energy/devices-detail-graph.png
Labels: next, has-parent, parent-merged

#31609 Add date platform and improve other text of Vallox integration
  source/_integrations/vallox.markdown
Labels: new-feature, next, has-parent, parent-merged

#31715 backup: describe how to restore
  source/_integrations/backup.markdown
Labels: current

#31726 Matter on Android: add troubleshooting information
  source/_integrations/matter.markdown
Labels: current

#31729 TTS: add examples how this integration is used
  source/_integrations/tts.markdown
Labels: current

#31730 Remove redundancy
  source/_integrations/tts.markdown
Labels: current

#31495 Script - add and clarify using UI for Fields/variables
  source/_integrations/script.markdown
Labels: current

#31739 Update fan.markdown to fix wrong example automation
  source/_integrations/fan.markdown
Labels: current

#31740 Clarify on TTS how to use integrations that build on it
  source/_integrations/tts.markdown
Labels: current

#31741 Clarify google translate how to use preferred speak service
  source/_integrations/google_translate.markdown
Labels: current

#31707 Remove deprecated `color_mode` flag, adjust `brightness` description for MQTT json light
  source/_integrations/light.mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#31482 add is charging sensor docs
  source/_integrations/permobil.markdown
Labels: next, has-parent, parent-merged

#31742 Clarify Calendar and To-Do building block pages
  source/_integrations/calendar.markdown
  source/_integrations/todo.markdown
Labels: current

#31747 Update dashboard navigation
  source/_includes/asides/dashboards_navigation.html
Labels: current

#31569 Added button platform to microBees integration
  source/_integrations/microbees.markdown
Labels: next, has-parent, parent-merged

#31735 Document Lutron Homeworks config flow
  source/_integrations/homeworks.markdown
Labels: next, has-parent, parent-merged

#31734 Add service response documentation to System Bridge
  source/_integrations/system_bridge.markdown
Labels: next, has-parent, parent-merged

#31728 Airzone Cloud is now Cloud Push
  source/_integrations/airzone_cloud.markdown
Labels: awaits-parent, next, has-parent

#31731 Update energy.markdown for detail devices max_devices
  source/_dashboards/energy.markdown
Labels: next, has-parent, parent-merged

#31748 Remove start of command symbol in shell script
  source/_integrations/backup.markdown
Labels: in-progress, current, needs-rebase

#31125 Add sensors to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: next, has-parent, parent-merged

#29429 Update Hyperion documentation to include new effect sensor
  source/_integrations/hyperion.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, parent-merged

#31722 Add Reolink play quick reply message docs
  source/_integrations/reolink.markdown
Labels: new-feature, awaits-parent, next, has-parent

#27933 Add Aprilaire integration
  source/_integrations/aprilaire.markdown
Labels: next, has-parent, parent-merged

#31697 Document changes in integration_entities
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, next, has-parent

#31755 Add Voice content on the 2024.3 release notes
  source/_posts/2024-03-06-release-20243.markdown
  source/images/blog/2024-03/new-assist-commands.png
Labels: in-progress, needs-rebase, rc

#31595 Add Krispol as supported brand to Reolink
  source/_integrations/motion_blinds.markdown
Labels: next, has-parent, parent-merged

#31712 Issues jinja template
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#30356 Add Beaufort windspeed to sensor markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#31581 Add Comelit humidifier/dehumidifier info
  source/_integrations/comelit.markdown
Labels: in-progress, next, has-parent, parent-merged

#31780 Minor typo fix in SUPLA integration description
  source/_integrations/supla.markdown
Labels: current

#31774 update a couple blog links
  source/_posts/2022-12-20-year-of-voice.markdown
  source/_posts/2024-02-21-voice-chapter-6.markdown
Labels: current

#31785 Revert "Remove JuiceNet integration"
  .textlintrc.json
  CODEOWNERS
  source/_integrations/juicenet.markdown
  source/_redirects
Labels: next, has-parent

#31802 Fix spelling in iqvia
  source/_integrations/iqvia.markdown
Labels: current

#31793 Add tested device to huawei_lte
  source/_integrations/huawei_lte.markdown
Labels: current

#31832 Add Raspberry Pi 5 to DIY installation page, alongside 3 and 4
  source/installation/index.html
Labels: current

#31827 Add note about network access setting for roku
  source/_integrations/roku.markdown
Labels: current

#31579 seventeentrack update docs with config flow
  source/_integrations/seventeentrack.markdown
Labels: new-feature, awaits-parent, next, has-parent

#31844 Add comment to mqtt sensor last_reset_value_template that `state_class` option must be `total`
  source/_integrations/sensor.mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#31847 Simplify example templates History Stats
  source/_integrations/history_stats.markdown
Labels: current

#31809 Add state object detail to numeric state
  source/_docs/automation/trigger.markdown
Labels: current

#31816 Add A6 family code for DS2438 1-Wire sensor
  source/_integrations/onewire.markdown
Labels: next, has-parent, smash

#31851 Opower: Clarify some sensors aren't populated for new accounts
  source/_integrations/opower.markdown
Labels: current

#31794 Added a link to instructions for setting up the entity
  source/_docs/energy/individual-devices.markdown
Labels: current

#31852 Update pushover.markdown
  source/_integrations/pushover.markdown
Labels: current

#31854 Add procedure on adding cards
  source/dashboards/cards.markdown
  source/images/dashboards/dashboard_add-by-entity_02.png
  source/images/dashboards/dashboard_add-by-entity_04.png
Labels: current

#31792 Update sma.markdown
  source/_integrations/sma.markdown
Labels: current

#31764 Document homeworks binary_sensor entities
  source/_integrations/homeworks.markdown
Labels: next, has-parent, parent-merged

#31819 Add Enphase specific debug and diagnostic details
  source/_integrations/enphase_envoy.markdown
Labels: current

#31864 Update sections view
  source/_dashboards/sections.markdown
  source/images/dashboards/sections_view_add-card-or-section.png
Labels: current

#31867 Energy card: fix typo
  source/_dashboards/energy.markdown
Labels: current

#31750 Document homeworks button entity
  source/_integrations/homeworks.markdown
Labels: next, has-parent, parent-merged

#29739 Add processes services to System Bridge
  source/_integrations/system_bridge.markdown
Labels: next, has-parent, parent-merged

#31771 Add date to esphome platform list
  source/_integrations/esphome.markdown
Labels: awaits-parent, next, has-parent

#31878 2024.3.1
  _config.yml
  source/_posts/2024-03-06-release-20243.markdown
  source/changelogs/core-2024.3.markdown
Labels: blog, in-progress, current, has-parent, needs-rebase

#31877 Update govee_light_local.markdown
  source/_integrations/govee_light_local.markdown
Labels: current

#31598 Add docs for UniFi Protect remove_privacy_zone
  source/_integrations/unifiprotect.markdown
Labels: new-feature, awaits-parent, next, has-parent

#31885 allow aroma therapy slot selection
  source/_integrations/tolo.markdown
Labels: next, has-parent, parent-merged

#31883 Revert "Update govee_light_local.markdown"
  source/_integrations/govee_light_local.markdown
Labels: current

#31772 update global note for building block integrations
  source/_includes/integrations/building_block_integration.md
Labels: current

#31803 clarify notifications building block page
  source/_integrations/notify.markdown
Labels: current

#31892 Update voice_remote_local_assistant.markdown
  source/voice_control/voice_remote_local_assistant.markdown
Labels: current

#31891 Small rephrase of the building block integration fragment
  source/_includes/integrations/building_block_integration.md
Labels: current

#31888 Remove OpenCV integration
  source/_integrations/opencv.markdown
  source/_redirects
Labels: awaits-parent, next, has-parent, parent-merged

#31274 Add documentation for Ring Intercom
  source/_integrations/ring.markdown
Labels: next, has-parent, parent-merged

#31813 fix ecobee service data with wrong way to target all thermostats
  source/_integrations/ecobee.markdown
Labels: current

#31767 Add sensors to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#31901 Voice Assistant Contest winners announcement
  source/_posts/2024-16-03-voice-assistant-community-contest-winners-annoucement.markdown
Labels: current

#31893 Modbus, configuration without entities
  source/_integrations/modbus.markdown
Labels: next, has-parent, parent-merged, by-code-owner

#31619 Docs for WAN port connection control to TP-Link Omada gateways
  source/_integrations/tplink_omada.markdown
Labels: next, has-parent, parent-merged

#31900 Clarify Matter Android prerequisites
  source/_integrations/matter.markdown
Labels: in-progress, current, has-parent, needs-rebase

#31897 Fix minor grammatical errors in heatmiser
  source/_integrations/heatmiser.markdown
Labels: current

#31915 Update documentation for Aftership
  source/_integrations/aftership.markdown
Labels: current

#31907 Update opower.markdown - note on Seattle City Light cost data
  source/_integrations/opower.markdown
Labels: current

#31889 Document profiler.set_asyncio_debug service
  source/_integrations/profiler.markdown
Labels: next, has-parent, parent-merged

#31898 Update to Sunrise Condition graphic
  source/images/docs/scripts/sun-conditions.svg
Labels: current

#31855 Refer to 'Adding cards' procedure
  source/_includes/dashboard/edit_dashboard.md
  source/dashboards/index.markdown
Labels: current

#31876 Adding cards: Fix step order
  source/dashboards/cards.markdown
Labels: current

#31875 Add procedure on creating a new dashboard
  source/dashboards/dashboards.markdown
  source/dashboards/index.markdown
Labels: current

#31927 Terminology: streamline spelling of email
  source/_integrations/ecovacs.markdown
  source/_integrations/google_mail.markdown
  source/_integrations/html5.markdown
  source/_integrations/icloud.markdown
  source/_integrations/lifx_cloud.markdown
  source/_integrations/llamalab_automate.markdown
  source/_integrations/loqed.markdown
  source/_integrations/sendgrid.markdown
  source/_integrations/smtp.markdown
  source/_integrations/xiaomi_miio.markdown
Labels: current

#31480 Initial documentation for fyta integration
  source/_integrations/fyta.markdown
Labels: new-integration, next, has-parent, parent-merged

#30616 Update documentation to reflect modBusTTRegisters changes
  source/_integrations/modbus.markdown
Labels: in-progress, next, has-parent, parent-merged

#31931 Add section on wiping the data disk
  source/_includes/common-tasks/commandline.md
Labels: current

#31929 fixing trigger links at Troubleshooting automations page
  source/_docs/automation/troubleshooting.markdown
Labels: current

#31938 Add missing Vodafone Station categories
  source/_integrations/vodafone_station.markdown
Labels: current

#31936 Align Freebox integration
  source/_integrations/freebox.markdown
Labels: current

#31935 Add missing categories to Comelit
  source/_integrations/comelit.markdown
Labels: current

#31932 HA OS: add command on listing users from cli
  source/_docs/locked_out.md
  source/_includes/common-tasks/commandline.md
Labels: current

#31939 correct 404 link
  source/index.html
Labels: current

#31489 Add additional buttons to OctoPrint
  source/_integrations/octoprint.markdown
Labels: next, has-parent, parent-merged

#31343 Add documentation for Starlink Sleep configuration
  source/_integrations/starlink.markdown
Labels: next, has-parent, parent-merged

#31928 Improve explanation of state_value_template and add example
  source/_integrations/light.mqtt.markdown
Labels: current

#31943 Adding configflow documentation
  source/_integrations/downloader.markdown
Labels: in-progress, next, has-parent, parent-merged

#31912 Update water.markdown
  source/_docs/energy/water.markdown
Labels: current

#31946 Cards: Fix capitalization in titles
  source/_dashboards/conditional.markdown
  source/_dashboards/entities.markdown
  source/_dashboards/gauge.markdown
  source/_dashboards/picture.markdown
Labels: current

#31615 Add device_tracker platform for husqvarna_automower
  source/_integrations/husqvarna_automower.markdown
Labels: new-feature, awaits-parent, next, has-parent

#31948 To-do: add links between integrations and shopping list card
  source/_dashboards/shopping-list.markdown
  source/_integrations/local_todo.markdown
  source/_integrations/todo.markdown
  source/dashboards/dashboards.markdown
  source/getting-started/onboarding_dashboard.markdown
Labels: current

#31910 Add reference to new Room Audio Control
  source/_integrations/control4.markdown
Labels: next, has-parent, parent-merged

#31775 add notes about using and configuring SwitchBot entities
  source/_integrations/switchbot.markdown
Labels: current, smash

#31273 service-calls: added info that target values should be lower-cased
  source/_docs/scripts/service-calls.markdown
Labels: current

#31624 Add sensors to the Traccar Server documentation
  source/_integrations/traccar_server.markdown
  source/blueprints/integrations/traccar_server_device_enter_geofence.yaml
  source/blueprints/integrations/traccar_server_device_speed_limit.yaml
Labels: next, has-parent

#31958 Revert "Add sensors to the Traccar Server documentation"
  source/_integrations/traccar_server.markdown
  source/blueprints/integrations/traccar_server_device_enter_geofence.yaml
  source/blueprints/integrations/traccar_server_device_speed_limit.yaml
Labels: next

#31191 Add fan preset modes feature
  source/dashboards/features.markdown
  source/images/dashboards/features/fan_preset_modes.png
Labels: next, has-parent, parent-merged

#31209 Add Presets to Advantage Air
  source/_integrations/advantage_air.markdown
Labels: next, has-parent, parent-merged

#31450 Add new sensors to Tessie
  source/_integrations/tessie.markdown
Labels: next, has-parent, parent-merged

#31535 airzone_cloud: document Air Quality sensors
  source/_integrations/airzone_cloud.markdown
Labels: next, has-parent, parent-merged

#31636 Add event platform to rfxtrx docs
  source/_integrations/rfxtrx.markdown
Labels: new-feature, awaits-parent, next, has-parent, parent-merged

#31531 airzone_cloud: document Air Quality binary_sensor
  source/_integrations/airzone_cloud.markdown
Labels: next, has-parent, parent-merged

#26348 Add statistics keep_last_sample option
  source/_integrations/statistics.markdown
Labels: in-progress, next, has-parent, parent-merged

#30881 Adds sensor entity in Tessie
  source/_integrations/tessie.markdown
Labels: next, has-parent, parent-merged

#31961 Cards header footer: list related cards
  source/dashboards/header-footer.markdown
Labels: current

#31962 Card features: add links to related cards
  source/dashboards/features.markdown
Labels: current

#31963 Tile card: add links to actions and features
  source/_dashboards/tile.markdown
Labels: current

#31960 Scripts: add glossrefs and fix minor typos
  source/_docs/scripts.markdown
Labels: current

#31947 Cards: add categories and expand on introduction
  source/dashboards/cards.markdown
Labels: current, smash

#31967 Add related links to card features and themes
  source/_dashboards/humidifier.markdown
  source/_dashboards/thermostat.markdown
Labels: current

#31970 Cards: link to cards and themes
  source/_dashboards/alarm-panel.markdown
  source/_dashboards/area.markdown
  source/_dashboards/button.markdown
  source/_dashboards/calendar.markdown
  source/_dashboards/conditional.markdown
  source/_dashboards/energy.markdown
  source/_dashboards/entities.markdown
  source/_dashboards/entity.markdown
  source/_dashboards/gauge.markdown
  source/_dashboards/glance.markdown
  source/_dashboards/grid.markdown
  source/_dashboards/history-graph.markdown
  source/_dashboards/horizontal-stack.markdown
  source/_dashboards/iframe.markdown
  source/_dashboards/light.markdown
  source/_dashboards/logbook.markdown
  source/_dashboards/map.markdown
  source/_dashboards/markdown.markdown
  source/_dashboards/media-control.markdown
  source/_dashboards/picture-elements.markdown
  source/_dashboards/picture-entity.markdown
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
  source/_dashboards/plant-status.markdown
  source/_dashboards/sensor.markdown
  source/_dashboards/statistic.markdown
  source/_dashboards/statistics-graph.markdown
  source/_dashboards/tile.markdown
  source/_dashboards/vertical-stack.markdown
  source/_dashboards/weather-forecast.markdown
Labels: current

#31966 Distributors
  sass/custom/_landingpage.scss
  source/green/index.html
  source/green/script.js
  source/skyconnect/index.html
  source/yellow/index.html
Labels: current

#31953 Add time to esphome platform list
  source/_integrations/esphome.markdown
Labels: awaits-parent, next, has-parent

#31944 Add binary sensor platform to Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: next, has-parent, parent-merged

#31973 Remove Box Content Div from SkyConnect Order Dialog
  source/skyconnect/index.html
Labels: current

#31983 Document state.last_reported
  source/_docs/configuration/state_object.markdown
Labels: next, has-parent, parent-merged

#31984 List Google Assistant SDK in the Notifications category
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#31987 Add lamarzocco bluetooth docs
  source/_integrations/lamarzocco.markdown
Labels: next, has-parent, parent-merged

#31975 Add select platform to Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: awaits-parent, next, has-parent

#31902 Shelly add custom TCP port support
  source/_integrations/shelly.markdown
Labels: awaits-parent, next, has-parent

#31992 Add promo State of the Open Home '24
  source/images/frontpage/state-of-the-open-home-2024.png
  source/index.html
Labels: current

#31996 Update alpha_vantage.markdown
  source/_integrations/alpha_vantage.markdown
Labels: current

#31995 2024.3.2
  _config.yml
  source/_posts/2024-03-06-release-20243.markdown
  source/changelogs/core-2024.3.markdown
Labels: current, has-parent

#32004 2024.3.3
  _config.yml
  source/_posts/2024-03-06-release-20243.markdown
  source/changelogs/core-2024.3.markdown
Labels: current, has-parent

#31957 Add supported services for lutron caseta blinds
  source/_integrations/lutron_caseta.markdown
Labels: awaits-parent, next, has-parent

#31577 Added binary sensors to microBees Integration
  source/_integrations/microbees.markdown
Labels: awaits-parent, next, has-parent, parent-merged
