Repository home-assistant/home-assistant.io, pull requests merged in 2024-07, with the labels that each got.

#33498 Improve details on TechnoVE's auto-charge switch
  source/_integrations/technove.markdown
Labels: current

#33497 Fix AprilAire case
  source/_integrations/aprilaire.markdown
Labels: current

#33504 Fix header on ios
  sass/homeassistant/_overrides.scss
Labels: current

#33502 Fix green header
  sass/homeassistant/pages/_landingpage.scss
  source/green/styles.css
Labels: current

#33508 Thread credentials: add steps how to share on iPhone
  source/_integrations/thread.markdown
Labels: next, has-parent

#33505 Fix the category list font cutoff in Safari
  sass/homeassistant/_overrides.scss
Labels: current

#33506 Add ESP32-S3-BOX-3B as possible device
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#33501 Getting started, Advanced config: update
  source/_docs/backend/database.markdown
  source/_docs/configuration.markdown
  source/_includes/asides/getting_started_navigation.html
  source/getting-started/configuration.markdown
  source/getting-started/index.markdown
  source/getting-started/join-the-community.markdown
Labels: current

#33523 Expand 2024.7 release notes
  source/_posts/2024-07-03-release-20247.markdown
  source/images/blog/2024-07/resize-cards.jpg
Labels: in-progress, needs-rebase, rc

#33503 Beautify frontpage
  sass/homeassistant/_overrides.scss
  sass/homeassistant/homepage/_features.scss
  sass/homeassistant/homepage/_hero_unit.scss
  source/_includes/custom/features.html
  source/_includes/site/footer.html
  source/index.html
Labels: current

#33520 Add Beoconnect Core as compatible Bang & Olufsen device
  source/_integrations/bang_olufsen.markdown
Labels: in-progress, next, has-parent

#33529 Show demo only at 760+px
  sass/homeassistant/homepage/_hero_unit.scss
  source/_includes/site/hero_unit.html
  source/index.html
Labels: current

#33526 Update mealie integration docs with API Token location
  source/_integrations/mealie.markdown
Labels: in-progress, next, needs-rebase

#33535 Remove Aladdin connect docs
  source/_integrations/aladdin_connect.markdown
  source/_redirects
Labels: next, has-parent

#33531 Several small changes to the 2024.7 release notes
  source/_posts/2024-07-03-release-20247.markdown
  source/images/blog/2024-07/resize-cards.jpg
  source/images/blog/2024-07/resize-cards.png
Labels: in-progress, needs-rebase, rc

#33540 Blueprint take control: update image
  source/images/blueprints/blueprint_take_control.webp
Labels: next, parent-merged

#33537 Resizing cards: add steps on reverting size to default
  source/dashboards/cards.markdown
Labels: next, has-parent, parent-merged

#33550 RLC-830A Update reolink.markdown
  source/_integrations/reolink.markdown
Labels: current

#33559 Built-in sentences for timer: add video
  source/voice_control/builtin_sentences.markdown
Labels: current

#33560 Add Jekyll icon tag plugin
  plugins/icon.rb
  source/_posts/2024-07-03-release-20247.markdown
  source/dashboards/cards.markdown
Labels: current

#33562 Make icon plugin more strict
  plugins/icon.rb
  source/dashboards/cards.markdown
Labels: in-progress, current, needs-rebase

#33557 Add icons for three dots menu and cogwheel
  source/_docs/automation/troubleshooting.markdown
  source/_docs/configuration.markdown
  source/_docs/organizing/categories.markdown
  source/_docs/organizing/floors.markdown
  source/_docs/organizing/labels.markdown
  source/_docs/troubleshooting_general.markdown
  source/_includes/asides/about.html
  source/_includes/asides/categories.html
  source/_includes/asides/component_navigation.html
  source/_includes/asides/dashboards_navigation.html
  source/_includes/asides/docs_navigation.html
  source/_includes/asides/getting_started_navigation.html
  source/_includes/asides/help_navigation.html
  source/_includes/asides/recent_posts.html
  source/_includes/asides/voice_navigation.html
  source/_includes/blog/post/date.html
  source/_includes/common-tasks/backups.md
  source/_includes/common-tasks/beta_version.md
  source/_includes/common-tasks/data_disk.md
  source/_includes/common-tasks/define_custom_polling.md
  source/_includes/common-tasks/enable_entities.md
  source/_includes/common-tasks/update.md
  source/_includes/custom/features.html
  source/_includes/dashboard/edit_dashboard.md
  source/_includes/feedback.html
  source/_includes/installation/operating_system.md
  source/_includes/post/author.html
  source/_includes/post/sharing.html
  source/_includes/site/footer.html
  source/_includes/site/header.html
  source/_includes/site/sidebar.html
  source/_integrations/application_credentials.markdown
  source/_integrations/matter.markdown
  source/dashboards/dashboards.markdown
  source/getting-started/onboarding_dashboard.markdown
  source/index.html
  source/voice_control/android.markdown
  source/voice_control/troubleshooting.markdown
Labels: current

#33549 Add event entities to doorbird
  source/_integrations/doorbird.markdown
Labels: next, has-parent, parent-merged

#33553 Add support for event entities for the linked_motion_sensor
  source/_integrations/homekit.markdown
Labels: next, has-parent, parent-merged

#33571 Blueprint: style fixes
  source/_docs/automation/using_blueprints.markdown
Labels: current

#33570 Add select platform to Matter
  source/_integrations/matter.markdown
Labels: next, has-parent

#33567 Fix integrations category badge
  source/integrations/index.html
Labels: current

#33490 Add documentation for MINI Connected
  source/_integrations/mini_connected.markdown
Labels: next, has-parent, parent-merged

#33556 Take control of blueprint: update to reflect current SW
  source/_docs/automation/using_blueprints.markdown
  source/images/blueprints/blueprint_take_control.webp
Labels: current

#33576 Update HomeKit Bridge documentation to include 2024 US AQI PM2.5 cutoffs
  source/_integrations/homekit.markdown
Labels: next, has-parent

#33542 Fix green header for real
  source/green/styles.css
Labels: current, smash

#33380 Add Aprilaire humidifier
  source/_integrations/aprilaire.markdown
Labels: awaits-parent, next, has-parent

#32539 Add 2FA note to webmin documentation
  source/_integrations/webmin.markdown
Labels: Stale, current

#33555 Add documentation for TechnoVE max current number entity
  source/_integrations/technove.markdown
Labels: next, has-parent

#33578 Finetune animation for integrations
  sass/homeassistant/pages/_component_page.scss
Labels: current

#33579 2024.7.1
  _config.yml
  source/_posts/2024-07-03-release-20247.markdown
  source/changelogs/core-2024.7.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33516 Clear up space: rephrase to use numbered steps
  source/more-info/free-space.markdown
Labels: current

#33541 Fix-green-landing-page
  source/_layouts/default.html
  source/green/index.html
  source/green/styles.css
  source/index.html
Labels: current, smash

#33552 Update unifi.markdown
  source/_integrations/unifi.markdown
Labels: current, smash

#33003 Add energy sensor entities to Tessie
  source/_integrations/tessie.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#33584 Fix front page bug
  source/index.html
Labels: current

#33585 Add energy binary sensors to Tessie
  source/_integrations/tessie.markdown
Labels: next, has-parent

#33580 Add support for min mode in Netatmo public sensor
  source/_integrations/netatmo.markdown
Labels: next, has-parent, parent-merged

#33445 Add Energy Select platform to Tessie
  source/_integrations/tessie.markdown
Labels: in-progress, next, has-parent, parent-merged

#33586 Add energy number entities to Tessie
  source/_integrations/tessie.markdown
Labels: next, has-parent, parent-merged

#33589 Add energy switch entities to Tessie
  source/_integrations/tessie.markdown
Labels: awaits-parent, next, has-parent

#33590 Add link to damping documentation on Forecast.io
  source/_integrations/forecast_solar.markdown
Labels: current

#33591 Update service examples for HEOS integration
  source/_integrations/heos.markdown
Labels: current

#33583 Add support for Roborock Zeo
  source/_integrations/roborock.markdown
Labels: next, has-parent, parent-merged

#32241 Add json_attributes_path configuration for command_line sensor
  source/_integrations/command_line.markdown
Labels: next, has-parent, parent-merged

#33607 Remove hint to only use yaml config for generic_hygrostat
  source/_integrations/generic_hygrostat.markdown
Labels: current

#33602 Add support for august event entities
  source/_integrations/august.markdown
Labels: awaits-parent, next, has-parent

#33609 Remove modbus.restart / modbus.stop.
  source/_integrations/modbus.markdown
Labels: current

#33191 Describe new keep_alive field in ollama.markdown
  source/_integrations/ollama.markdown
Labels: awaits-parent, next, has-parent

#33615 Add note to config via UI
  source/_integrations/generic_thermostat.markdown
Labels: current

#33612 Add note to config via UI
  source/_integrations/generic_hygrostat.markdown
Labels: current

#33616 Add note to config via UI
  source/_integrations/template.markdown
Labels: current

#32489 Add documentation for Hydrawise valves
  source/_integrations/hydrawise.markdown
Labels: in-progress, next, has-parent

#33598 Add config flow to history_stats
  source/_integrations/history_stats.markdown
Labels: awaits-parent, next, has-parent

#33606 Add documentation for the mealie.get_mealplan service
  source/_integrations/mealie.markdown
Labels: awaits-parent, next, has-parent

#33618 Alert format for the need for default_config to configure UI in Template
  source/_integrations/template.markdown
Labels: current

#33600 Add event entity to Feedreader
  source/_integrations/feedreader.markdown
Labels: awaits-parent, next, has-parent

#33458 Add to-do platform to Habitica integration
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#33628 correct references to carbon_monoxide and carbon_dioxide device_class
  source/_integrations/homekit.markdown
Labels: current

#33620 Add button platform to habitica integration
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent

#33630 Update links to Twillo help pages
  source/_integrations/twilio_sms.markdown
Labels: current

#33622 Add switch platform to Habitica integration
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#33631 Add a note on HomeKit device
  source/_integrations/tradfri.markdown
Labels: current

#33626 Add madvr integration documentation
  source/_integrations/madvr.markdown
Labels: next, has-parent, parent-merged

#33632 Add documentation for the mealie.get_recipe service
  source/_integrations/mealie.markdown
Labels: awaits-parent, next, has-parent

#33642 Adds note about unit and device class for database size sensor
  source/_integrations/sql.markdown
Labels: current

#33623 Add sunroof to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: awaits-parent, in-progress, next, has-parent

#33645 Aligns information across Template helper platforms' documentation pages.
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/cover.template.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/light.template.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/template.markdown
  source/_integrations/vacuum.template.markdown
  source/_integrations/weather.template.markdown
Labels: current

#33651 Update whirlpool.markdown
  source/_integrations/whirlpool.markdown
Labels: current

#33491 Updated the alexa documentation to support the remote domain
  source/_integrations/alexa.smart_home.markdown
Labels: awaits-parent, in-progress, next, has-parent

#33656 Remove `topic_template` option for mqtt publish service
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent

#33648 Add icons for quality scale and classify IoT on the integration page
  source/_includes/asides/component_navigation.html
Labels: current

#33639 Add Mealie todo lists & me as code owner
  CODEOWNERS
  source/_integrations/mealie.markdown
Labels: next, has-parent, parent-merged

#33665 Add Feasycom FSC-BP106 to ibeacon
  source/_integrations/ibeacon.markdown
Labels: current

#33667 Add design.home-assistant.io to footer
  source/_includes/site/footer.html
Labels: current

#33674 2024.7.2
  _config.yml
  source/_posts/2024-07-03-release-20247.markdown
  source/changelogs/core-2024.7.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33666 Improve sexiness of the website
  source/images/merchandise/shirt-frontpage.jpg
  source/index.html
Labels: current

#33663 Update cisco_webex_teams.markdown
  source/_integrations/cisco_webex_teams.markdown
Labels: current

#33574 Update Russound RIO integration to reflect migration to config flow
  source/_integrations/russound_rio.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#33680 Add docs for Autarco integration
  source/_integrations/autarco.markdown
Labels: new-integration, next, has-parent, parent-merged

#33673 Update integration.markdown
  source/_integrations/integration.markdown
Labels: current

#33683 Document doorbird reset favorites button
  source/_integrations/doorbird.markdown
Labels: next, has-parent, parent-merged

#33668 Add config flow for image platform in Template
  source/_integrations/template.markdown
Labels: awaits-parent, next, has-parent

#33657 Add information about `boolean` virtual component for Shelly devices
  source/_integrations/shelly.markdown
Labels: awaits-parent, next, has-parent

#33659 feat: update madvr docs
  source/_integrations/madvr.markdown
Labels: next, has-parent, parent-merged

#33636 Add note to tedee about webhooks
  source/_integrations/tedee.markdown
Labels: current

#33654 Mealie import recipe service
  source/_integrations/mealie.markdown
Labels: next, has-parent, parent-merged

#33643 Add config flow for platform button in Template
  source/_integrations/template.markdown
Labels: in-progress, next, has-parent, parent-merged

#33662 Add documentation for new cooled seat control feature for Tessie integration
  source/_integrations/tessie.markdown
Labels: awaits-parent, next, has-parent

#30933 SimpleFIN Integration Docs
  source/_integrations/simplefin.markdown
Labels: in-progress, next, has-parent, parent-merged

#33688 Revert "Update androidtv_remote.markdown - zeroconf incorrect IP workaround"
  source/_integrations/androidtv_remote.markdown
Labels: in-progress, current, needs-rebase

#33679 Add multiple rows example for Google Sheets
  source/_integrations/google_sheets.markdown
Labels: in-progress, next, has-parent, smash

#33621 Add Broadlink time platform
  source/_integrations/broadlink.markdown
Labels: next, has-parent, parent-merged

#33685 Add israel rail documentation
  source/_integrations/israel_rail.markdown
Labels: awaits-parent, next, has-parent

#33689 Add sunroof to Tessie
  source/_integrations/tessie.markdown
Labels: awaits-parent, next, has-parent

#33697 Remove config table from israel rail docs
  source/_integrations/israel_rail.markdown
Labels: in-progress, next, needs-rebase

#33681 Add button group support
  source/_integrations/group.markdown
Labels: awaits-parent, next, has-parent

#33669 Add config flow for switch platform in Template
  source/_integrations/switch.template.markdown
Labels: awaits-parent, next, has-parent

#33641 docs: AndroidTV document how to fix device going unavailable
  source/_integrations/androidtv.markdown
Labels: current

#33678 Document doorbird automatic configuration
  source/_integrations/doorbird.markdown
Labels: awaits-parent, next, has-parent

#33686 Add information about `text` virtual component for Shelly devices
  source/_integrations/shelly.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#33752 linked to correct document netbeheer
  source/_integrations/dsmr.markdown
Labels: current

#33710 Add config flow for select platform in Template
  source/_integrations/template.markdown
Labels: next, has-parent, parent-merged

#33733 Remove yaml configuration example from GDACS integration
  source/_integrations/gdacs.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33750 Correct mqtt sensor info on state updates and add waring on use extra state attributes
  source/_integrations/sensor.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#33708 Add Broadlink select platform
  source/_integrations/broadlink.markdown
Labels: next, has-parent, parent-merged

#33712 Add documentation for lifx.effect_sky
  source/_integrations/lifx.markdown
Labels: in-progress, next, has-parent, parent-merged

#33716 Add Reolink Argus 3 Pro to list of tested devices
  source/_integrations/reolink.markdown
Labels: current

#33719 Add Smart Rollo (SIRO) as supported by Motion Blinds
  source/_integrations/motion_blinds.markdown
Labels: current

#33594 Add Enphase Envoy configuration option description.
  source/_integrations/enphase_envoy.markdown
Labels: current

#33757 improve tech note on Aeotec Z-Stick compatibilty in controllers.markdown
  source/_docs/z-wave/controllers.markdown
Labels: current

#33701 Add section on updating S3-BOX firmware
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#33737 Update roborock.markdown with example of service call to get_maps
  source/_integrations/roborock.markdown
Labels: current

#33706 Add inverter docs for Autarco integration
  source/_integrations/autarco.markdown
Labels: new-feature, next, has-parent, parent-merged

#33760 Update automation editor to reflect current SW
  source/_docs/automation/editor.markdown
  source/images/docs/automation-editor/add-trigger-to-automation.png
  source/images/docs/automation-editor/add_action.png
Labels: current

#33762 Automation troubleshooting: rename service to action
  source/_docs/automation/troubleshooting.markdown
Labels: next, has-parent

#33764 Minimal edit Correcting description of "passive" zone.markdown
  source/_integrations/zone.markdown
Labels: current

#33767 Add H5121/H5122/H5123/H5125/H5126 to govee-ble
  source/_integrations/govee_ble.markdown
Labels: awaits-parent, next, has-parent

#33770 Glossary: rephrase definitions of area
  source/_data/glossary.yml
Labels: next, has-parent

#33772 Glossary: rephrase 'domain'
  source/_data/glossary.yml
Labels: next, has-parent

#33773 Glossary: rephrase 'label'
  source/_data/glossary.yml
Labels: next, has-parent, parent-merged

#33759 Rename dsmr integration to be more generic
  source/_integrations/dsmr.markdown
Labels: awaits-parent, next, has-parent

#33775 service-calls-page: rename to 'perform action'
  source/_docs/scripts/service-calls.markdown
Labels: next, has-parent

#33776 Dev tools: rename 'service' to action
  source/_docs/tools/dev-tools.markdown
  source/images/screenshots/developer-tools.png
Labels: next, has-parent

#33777 Split Raspberry Pi getting started
  source/_includes/installation/container.md
  source/common-tasks/os.markdown
  source/images/installation/rpi_imager.png
  source/installation/index.html
  source/installation/raspberrypi-other.markdown
  source/installation/raspberrypi.markdown
Labels: current

#33761 Use the term Helper in the config flow instructions if the integration type is helper
  source/_includes/integrations/config_flow.md
Labels: current

#33778 Custom polling: rename service to action
  source/_includes/common-tasks/define_custom_polling.md
  source/images/screenshots/custom_polling_02.png
Labels: next, has-parent

#33779 Update comparison table
  source/installation/index.html
Labels: current

#33782 container: rename 'service' to 'action'
  source/_includes/installation/container.md
Labels: next, has-parent

#33783 remotes: rename 'service' to 'action'
  source/_integrations/remote.markdown
Labels: next, has-parent

#33601 A wider website and documentation navigation revamp
  _config.yml
  sass/homeassistant/_overrides.scss
  sass/homeassistant/_variables.scss
  sass/homeassistant/base/_global.scss
  sass/homeassistant/base/_navigation.scss
  sass/homeassistant/base/_sidebar.scss
  sass/homeassistant/homepage/_hero_unit.scss
  sass/homeassistant/pages/_component_page.scss
  sass/inuitcss/_defaults.scss
  source/_docs/scripts.markdown
  source/_docs/scripts/conditions.markdown
  source/_includes/asides/categories.html
  source/_includes/asides/dashboards_navigation.html
  source/_includes/asides/docs_navigation.html
  source/_includes/asides/docs_sitemap.html
  source/_includes/asides/getting_started_navigation.html
  source/_includes/asides/organizing_navigation.html
  source/_includes/asides/recent_categories.html
  source/_includes/asides/recent_posts.html
  source/_includes/asides/voice_navigation.html
  source/_includes/blog/archive_post.html
  source/_includes/blog/post/article.html
  source/_includes/site/header.html
  source/_includes/site/hero_unit.html
  source/_includes/site/left_sidebar.html
  source/_includes/site/sidebar.html
  source/_includes/site/vertical_nav.html
  source/_layouts/category_index.html
  source/_layouts/default.html
  source/_layouts/page.html
  source/_layouts/post.html
  source/blog/index.html
  source/docs/index.html
  source/docs/index.markdown
  source/getting-started/index.markdown
  source/help/reporting_issues.markdown
Labels: current

#33781 Rename Services to Actions in integrations: A
  source/_integrations/abode.markdown
  source/_integrations/adguard.markdown
  source/_integrations/ads.markdown
  source/_integrations/advantage_air.markdown
  source/_integrations/aftership.markdown
  source/_integrations/agent_dvr.markdown
  source/_integrations/airzone_cloud.markdown
  source/_integrations/alarm_control_panel.ifttt.markdown
  source/_integrations/alarm_control_panel.markdown
  source/_integrations/alarmdecoder.markdown
  source/_integrations/alexa.intent.markdown
  source/_integrations/alexa.smart_home.markdown
  source/_integrations/amcrest.markdown
  source/_integrations/androidtv.markdown
  source/_integrations/androidtv_remote.markdown
  source/_integrations/aosmith.markdown
  source/_integrations/apple_tv.markdown
  source/_integrations/apprise.markdown
  source/_integrations/atag.markdown
  source/_integrations/aurora.markdown
  source/_integrations/aws.markdown
  source/_integrations/azure_service_bus.markdown
Labels: in-progress, next, needs-rebase

#33784 Getting-started, automation: rename 'service' to 'action'
  source/getting-started/automation.markdown
Labels: next, has-parent

#33785 Rename Services to Actions in integrations: B
  source/_integrations/backup.markdown
  source/_integrations/bang_olufsen.markdown
  source/_integrations/blackbird.markdown
  source/_integrations/blink.markdown
  source/_integrations/bluesound.markdown
  source/_integrations/bluetooth_tracker.markdown
  source/_integrations/bmw_connected_drive.markdown
  source/_integrations/bond.markdown
  source/_integrations/braviatv.markdown
  source/_integrations/bring.markdown
  source/_integrations/broadlink.markdown
  source/_integrations/browser.markdown
  source/_integrations/button.markdown
  source/_integrations/button.mqtt.markdown
Labels: in-progress, next, needs-rebase

#33786 Button card: rename 'service' to 'action'
  source/_dashboards/button.markdown
Labels: next, has-parent

#33787 Picture cards: rename 'service' to 'action'
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
Labels: next, has-parent

#33789 scene: rename 'service' to 'action'
  source/_docs/scene.markdown
Labels: next, has-parent

#33793 Tweak installation text and link directly to installation
  source/_includes/installation/container.md
  source/_includes/installation/container/alternative.md
  source/_includes/site/header.html
  source/installation/alternative.markdown
Labels: current

#33790 scripts: rename 'service' to 'action'
  source/_docs/scripts.markdown
Labels: next, has-parent

#33791 Multi-factor authentication: rename 'service' to 'action'
  source/_docs/authentication/multi-factor-auth.markdown
Labels: next, has-parent

#33792 Action page: rename 'service' to 'action'
  source/_docs/automation/action.markdown
Labels: next, has-parent

#33794 Automation basics: rename 'service' to 'action'
  source/_docs/automation/basics.markdown
Labels: next, has-parent

#33795 automation services: rename 'service' to 'action'
  source/_docs/automation/services.markdown
Labels: next, has-parent

#33796 Bug fix: remove stale anchor to Balena Etcher section
  source/installation/raspberrypi.markdown
Labels: current

#33797 automation YAML: rename 'service' to 'action'
  source/_docs/automation/yaml.markdown
Labels: next, has-parent
