Repository home-assistant/home-assistant.io, pull requests merged in 2024-11, with the labels that each got.

#34336 Count sensor documentation improvements
  source/_integrations/history_stats.markdown
Labels: current

#35555 Green distributor: update link to SmarterHome
  source/green/index.html
Labels: current

#35556 Connect ZBT1: update distributor link
  source/connectzbt1/index.html
Labels: current

#35512 Use NFS proper name, consistent with settings dialog
  source/_includes/common-tasks/network_storage.md
Labels: Hacktoberfest, current, has-parent, parent-merged

#35479 Add boost switch to Smarty.markdown
  source/_integrations/smarty.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35538 Document Alexa account linking over port 443 is not mandatory
  source/_integrations/alexa.smart_home.markdown
Labels: current, by-code-owner, integration: alexa

#35503 Jewish calendar: Fix order of holidays provided according to the calendar
  source/_integrations/jewish_calendar.markdown
Labels: Hacktoberfest, current

#35533 Update todo-list.markdown (Syntax)
  source/_dashboards/todo-list.markdown
Labels: current

#35432 Another thing to check if sensor isn't listed
  source/more-info/statistics.markdown
Labels: Hacktoberfest, current

#35489 Add text-input class to integration search input
  sass/homeassistant/base/_global.scss
  source/integrations/index.html
Labels: Hacktoberfest, current

#35499 Add note on X devices being unupported
  source/_integrations/tado.markdown
Labels: Hacktoberfest, current

#35502 Assist on Android: add steps on starting from HA
  source/images/assist/wearos_assist_app.png
  source/voice_control/android.markdown
Labels: Hacktoberfest, current

#35563 Green - Add new distributor for Italy
  source/green/index.html
Labels: current

#35565 default value for `http.ip_ban_enabled` is `True`
  source/_integrations/http.markdown
Labels: current

#35559 Remove 'options for exemptions' where it doesnt belong
  source/_dashboards/glance.markdown
  source/_dashboards/picture-elements.markdown
  source/_dashboards/picture-glance.markdown
Labels: current

#35569 Update calendar.markdown
  source/_integrations/calendar.markdown
Labels: current

#35572 Correct the syntax for actions with intent script
  source/_integrations/intent_script.markdown
  source/voice_control/custom_sentences.markdown
Labels: current

#34998 Add go2rtc
  source/_integrations/default_config.markdown
  source/_integrations/go2rtc.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35580 Add info about go2rtc ports
  source/_integrations/go2rtc.markdown
Labels: next, has-parent, parent-merged

#35521 Add binary sensor platform to Habitica
  source/_integrations/habitica.markdown
Labels: next, has-parent

#35579 Small copy changes to 2024.11 notes
  source/_posts/2024-11-06-release-202411.markdown
Labels: in-progress, needs-rebase, rc

#35583 Mark sections view as default to reflect current version
  source/_dashboards/masonry.markdown
  source/_dashboards/sections.markdown
  source/_dashboards/sidebar.markdown
  source/_dashboards/vertical-stack.markdown
  source/dashboards/index.markdown
  source/dashboards/views.markdown
Labels: next, has-parent

#35584 Views: update screenshots to reflect current SW with sections as default
  source/_dashboards/masonry.markdown
  source/dashboards/views.markdown
  source/images/dashboards/dashboard_view_configuration_01.png
  source/images/dashboards/dashboard_view_configuration_03.png
Labels: next, has-parent

#35585 Sections view: add steps on migrating into sections view
  source/dashboards/views.markdown
Labels: next, has-parent

#35586 Document device_id for sentence trigger
  source/_docs/automation/templating.markdown
Labels: current

#34654 updating Knocki docs
  source/_integrations/knocki.markdown
Labels: current

#35597 Auth providers: fix path to user configuration page
  source/_docs/authentication/providers.markdown
Labels: current

#35599 Streamline username spelling. lowercase, no spaces
  source/_docs/authentication.markdown
  source/_docs/configuration/basic.markdown
  source/_integrations/person.markdown
Labels: current

#35596 Onboarding dashboard: add small note about sections view
  source/getting-started/onboarding_dashboard.markdown
Labels: next, has-parent

#35602 Small typo fixes and other changes
  source/_posts/2024-11-06-release-202411.markdown
Labels: in-progress, needs-rebase, rc

#35604 Migrate views: add screenshot
  source/dashboards/views.markdown
  source/images/dashboards/imported-cards.png
Labels: in-progress, next, has-parent

#35607 Fix youtube video in built-in sentences
  source/voice_control/builtin_sentences.markdown
Labels: current

#35608 Other small changes to 2024.11 notes
  source/_posts/2024-11-06-release-202411.markdown
Labels: in-progress, needs-rebase, rc

#35605 Cards: add precise mode
  source/dashboards/cards.markdown
  source/images/dashboards/card_resize.png
  source/images/dashboards/precise-mode-example.png
Labels: next, has-parent

#35610 Add diagnostic, image and update to glossary
  source/_data/glossary.yml
Labels: current

#35589 Overhaul AVM FRITZ!Box Tools docs
  source/_integrations/fritz.markdown
Labels: in-progress, current, has-parent, needs-rebase

#35618 Do not promote Google servers in docs
  source/_integrations/homeassistant.markdown
Labels: current

#35614 Improve list formatting in mqtt docs and sort third party tools list
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#35612 Diagnostics integration: fix typo
  source/_integrations/diagnostics.markdown
Labels: in-progress, current, needs-rebase

#35617 Update aftership.markdown
  source/_integrations/aftership.markdown
Labels: current

#35619 Glossary- diagnostics: tiny rephrase
  source/_data/glossary.yml
Labels: current

#35482 Add Switcher Lights support
  source/_integrations/switcher_kis.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35643 Update the detail page URLs for some devices.
  source/_integrations/lg_thinq.markdown
Labels: current

#35644 Clarify that filtered entities are excluded in Homekit Bridge by default
  source/_integrations/homekit.markdown
Labels: current

#35637 Add ms to duration units
  source/_integrations/sensor.markdown
Labels: current

#35630 Notify about missing pre-requisites for Wake On Lan
  source/_integrations/webostv.markdown
Labels: current

#35638 Suez water: simplify config flow
  source/_integrations/suez_water.markdown
Labels: next, has-parent, parent-merged

#35625 Add Nord Pool integration
  source/_integrations/nordpool.markdown
Labels: new-integration, awaits-parent, next, has-parent

#35659 Documentation: Update scene.markdown Configuration Variable
  source/_docs/scene.markdown
Labels: current

#35661 2024.11.1
  _config.yml
  source/_posts/2024-11-06-release-202411.markdown
  source/changelogs/core-2024.11.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#35660 Add reconfigure flow to Nord Pool
  source/_integrations/nordpool.markdown
Labels: next, has-parent, parent-merged

#35662 Add Yale Linus L2 to yale.markdown
  source/_integrations/yale.markdown
Labels: current

#35656 Add support for MW/GW/TW and GWh/TWh
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: in-progress, next, has-parent, parent-merged

#35658 Clarify `this` in templates
  source/_docs/configuration/templating.markdown
  source/_integrations/template.markdown
Labels: current

#35657 Suez water: add water price sensor
  source/_integrations/suez_water.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#35567 Add Chime vehicle ringtone docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35640 Add documentation on using Simplisafe secret alerts in triggers
  source/_integrations/simplisafe.markdown
Labels: current

#35595 Add Lektrico binary sensors documentation
  source/_integrations/lektrico.markdown
Labels: next, has-parent, parent-merged

#35670 Add description for stats sensors to Habitica
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#35672 Fix colons and trailing white-spaces in Habitica
  source/_integrations/habitica.markdown
Labels: current

#35573 Update nest.markdown to improve troubleshooting for *Something went wrong....* case
  source/_integrations/nest.markdown
Labels: current

#35447 Add device class for blood glucose concentration
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35531 Add quests actions to Habitica
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35678 Fix spelling inte template this variable use
  source/_integrations/template.markdown
Labels: in-progress, current, needs-rebase

#35676 Update stookwijzer.markdown
  source/_integrations/stookwijzer.markdown
Labels: current

#35674 Update tedee docs with encrypted token hint
  source/_integrations/tedee.markdown
Labels: current

#35162 Add signing instructions to Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, parent-merged

#35511 Add score task action to Habitica
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35544 Add DHCP discovery support to Palazzetti
  source/_integrations/palazzetti.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35527 Add reset filters timer button to Smarty .markdown
  source/_integrations/smarty.markdown
Labels: in-progress, next, has-parent, parent-merged

#35169 Update ring event stability documentation - for beta
  source/_integrations/ring.markdown
Labels: Hacktoberfest, in-progress, current, has-parent, needs-rebase

#35232 Remove documentation for deprecated action in Habitica
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35468 Update ecobee for auxiliary heat options
  source/_integrations/ecobee.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#34070 Update emulated_hue.markdown
  source/_integrations/emulated_hue.markdown
Labels: current

#35698 Add binary sensor platform to eq3btsmart
  source/_integrations/eq3btsmart.markdown
Labels: next, has-parent, parent-merged

#35711 Adding new devices to switchbot cloud integration
  source/_integrations/switchbot_cloud.markdown
Labels: next, has-parent, parent-merged

#35709 switchbot_cloud: Mark Lock Pro as supported
  source/_integrations/switchbot_cloud.markdown
Labels: current

#35714 Adding Rexel Energeasy in supported devices list
  source/_integrations/overkiz.markdown
Labels: current

#35717 Improve requirements for lambda region selection
  source/_integrations/alexa.smart_home.markdown
Labels: current

#35706 Add switch platform to eq3btsmart
  source/_integrations/eq3btsmart.markdown
Labels: next, has-parent, parent-merged

#35722 Mention alternative (deco) provisioning for tplink
  source/_integrations/tplink.markdown
Labels: current

#35746 Update dashboards.markdown
  source/dashboards/dashboards.markdown
Labels: current

#35763 Document the options to send retained MQTT discovery messages
  source/_integrations/mqtt.markdown
Labels: current

#35758 Remove returning to dock in Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35761 Update seventeentrack.markdown
  source/_integrations/seventeentrack.markdown
Labels: current

#35764 Improve eq3btsmart pairing explanation after new firmware release
  source/_integrations/eq3btsmart.markdown
Labels: current

#35760 Reolink firmware update docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35757 Update text on `this` in templates
  source/_integrations/template.markdown
Labels: current

#35721 Add number platform to eq3btsmart
  source/_integrations/eq3btsmart.markdown
Labels: next, has-parent, parent-merged

#35772 Roadmap-2024H2
  source/_posts/2024-11-14-roadmap-2024h2.markdown
  source/images/blog/2024-11-roadmap-2024h2/banner.jpg
  source/images/blog/2024-11-roadmap-2024h2/dashboard-casestudies.png
  source/images/blog/2024-11-roadmap-2024h2/ha-roadmap-2024h2.png
  source/images/blog/2024-11-roadmap-2024h2/voice-hardware-teaser.jpg
Labels: current

#28516 Add documentation for NASweb integration
  source/_integrations/nasweb.markdown
  source/images/integrations/nasweb/dashboard.png
  source/images/integrations/nasweb/modules.png
  source/images/integrations/nasweb/nasweb_scheme.png
  source/images/integrations/nasweb/users.png
Labels: next, has-parent, parent-merged

#35726 Added starline run sensor
  source/_integrations/starline.markdown
Labels: next, has-parent, parent-merged

#35635 Add documentation for acaia integration
  source/_integrations/acaia.markdown
Labels: new-integration, in-progress, next, has-parent, parent-merged

#35776 Correct dining_room spelling in templating attributes example
  source/_docs/configuration/templating.markdown
Labels: current

#34419 Create sky_remote.markdown
  source/_integrations/sky_remote.markdown
Labels: next, has-parent, parent-merged

#35733 Update Database documentation to reflect the deprecation of the entity_id column on states
  source/_docs/backend/database.markdown
Labels: current

#35510 Add transformation action to Habitica
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, awaits-parent, next, has-parent, parent-merged

#35754 Improve Onkyo documentation
  source/_integrations/onkyo.markdown
Labels: current

#35759 switcher add current temperature sensor to thermostat devices
  source/_integrations/switcher_kis.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#35777 2024.11.2
  _config.yml
  source/_posts/2024-11-06-release-202411.markdown
  source/changelogs/core-2024.11.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#35792 Remove stale Nest documentation
  source/_integrations/nest.markdown
Labels: current

#35812 Add Reolink RLN8-410 N7MB01 as compatible with battery camera's
  source/_integrations/reolink.markdown
Labels: current

#35752 Add sensor platform to acaia
  source/_integrations/acaia.markdown
Labels: in-progress, next, has-parent, parent-merged

#35775 Add documentation for acaia binary_sensor platform
  source/_integrations/acaia.markdown
Labels: in-progress, next, has-parent, parent-merged

#35817 Upload blog for GitHub Universe 2024
  source/_data/people.yml
  source/_posts/2024-11-18-event-wrapup-github-universe-24.markdown
  source/images/blog/2024-11-universe/art.jpg
  source/images/blog/2024-11-universe/booth.jpg
  source/images/blog/2024-11-universe/day-1-keynote.jpg
  source/images/blog/2024-11-universe/ha-keynote.jpg
  source/images/blog/2024-11-universe/meetup-audience.jpg
  source/images/blog/2024-11-universe/number-1.png
  source/images/blog/2024-11-universe/octoverse-contributors.png
  source/images/blog/2024-11-universe/postcard-badge.png
  source/images/blog/2024-11-universe/shiny.png
  source/images/blog/2024-11-universe/wonderfully-welcoming.png
Labels: current

#35816 Refactor integration removal include
  source/_includes/common-tasks/remove_device_service.md
  source/common-tasks/general.markdown
Labels: current

#35828 Add removal headline to lamarzocco
  source/_integrations/lamarzocco.markdown
Labels: current

#35811 Add µV as unit to sensor and number platform
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#35829 Fix missing YAML entry from ADS Cover
  source/_integrations/ads.markdown
Labels: current

#35834 Add buttons to sabnzbd and remove deprecated custom actions
  source/_integrations/sabnzbd.markdown
Labels: next, has-parent, parent-merged

#35832 signal_messenger: Mention how to receive from Signal running json-rpc
  source/_integrations/signal_messenger.markdown
Labels: current

#35804 Add description for reminders calendars in Habitica integration
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#35839 Update statistics.markdown
  source/_integrations/statistics.markdown
Labels: in-progress, current, has-parent, needs-rebase

#35865 Reolink high level description
  source/_integrations/reolink.markdown
Labels: current

#35864 Reolink sub-headings in troubleshooting
  source/_integrations/reolink.markdown
Labels: current

#35862 Clearify Reolink setup and prerequisites
  source/_integrations/reolink.markdown
Labels: current

#35732 Area square meters docs
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#35875 Document how to remove MQTT
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#35856 Add instructions for removing Cambridge Audio integration
  source/_integrations/cambridge_audio.markdown
Labels: current

#35881 Add instructions for removing Autarco integration
  source/_integrations/autarco.markdown
Labels: current

#35878 Add instructions for removing SFR Box integration
  source/_integrations/sfr_box.markdown
Labels: current

#35879 Add instructions for removing 1-wire integration
  source/_integrations/onewire.markdown
Labels: current

#35873 Add options flow docs to lamarzocco
  source/_integrations/lamarzocco.markdown
Labels: current

#35874 Add removal instructions and update frequency to tedee
  source/_integrations/tedee.markdown
Labels: current

#35730 Update integrations that are ManualTriggerEntity with template information
  source/_includes/integrations/using_templates.md
  source/_integrations/binary_sensor.rest.markdown
  source/_integrations/command_line.markdown
  source/_integrations/notify.rest.markdown
  source/_integrations/rest.markdown
  source/_integrations/scrape.markdown
  source/_integrations/sensor.rest.markdown
  source/_integrations/snmp.markdown
  source/_integrations/sql.markdown
  source/_integrations/switch.rest.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#35797 Add mL/s as a unit for volume_flow_rate sensor class
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35887 Add install parameters for Autarco integration
  source/_integrations/autarco.markdown
Labels: current

#35888 Update quality_scale.markdown
  source/_docs/quality_scale.markdown
Labels: current

#35846 Add number to sabnzbd and remove deprecated custom action
  source/_integrations/sabnzbd.markdown
Labels: next, has-parent

#35889 Add data update info for Autarco integration
  source/_integrations/autarco.markdown
Labels: current

#35860 Reolink clearify data updates
  source/_integrations/reolink.markdown
Labels: next, has-parent

#35890 Add Fully Kiosk removal instructions
  source/_integrations/fully_kiosk.markdown
Labels: current

#33903 Group and explain modbus climate entity settings
  source/_integrations/modbus.markdown
Labels: in-progress, current, has-parent, needs-rebase

#35642 Update luci.markdown
  source/_integrations/luci.markdown
Labels: current

#33456 Further ZHA guidelines for Zigbee RSSI and LQI values
  source/_integrations/zha.markdown
Labels: current

#35798 Add new sensors to the palazzetti integration
  source/_integrations/palazzetti.markdown
Labels: next, has-parent

#35863 Group Reolink entities under 'Supported functionality'
  source/_integrations/reolink.markdown
Labels: current

#33539 Update alternative.md
  source/_includes/installation/container/alternative.md
Labels: current

#35861 Add data update section to Cambridge Audio
  source/_integrations/cambridge_audio.markdown
Labels: current

#35382 blebox: add integration documentation for actionBox line of devices and Simon GO control line of devices
  source/_integrations/blebox.markdown
Labels: Hacktoberfest, current

#35876 Add instructions for removing Renault integration
  source/_integrations/renault.markdown
Labels: current

#35897 2024.11.3
  _config.yml
  source/_posts/2024-11-06-release-202411.markdown
  source/changelogs/core-2024.11.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#35898 Add instructions for removing Mastodon integration
  source/_integrations/mastodon.markdown
Labels: current

#35900 Add flow rate to acaia
  source/_integrations/acaia.markdown
Labels: next, has-parent, parent-merged

#35756 Add updated docs for Jewish calendar library update
  source/_integrations/jewish_calendar.markdown
Labels: next, has-parent, parent-merged

#35800 Added StarLine flex logic and panic buttons
  source/_integrations/starline.markdown
Labels: next, has-parent, parent-merged

#35339 Semantic Accessibility and SEO Improvements: Correct List Parent Tags and Heading Levels
  sass/homeassistant/_overrides.scss
  source/_includes/site/footer.html
  source/index.html
Labels: Hacktoberfest, current

#35903 Document Renault installation parameters
  source/_integrations/renault.markdown
Labels: current

#35905 Add removal instructions for IMAP integration
  source/_integrations/imap.markdown
Labels: current, has-parent, by-code-owner, integration: imap

#35907 Add installation parameters for Mastodon
  source/_integrations/mastodon.markdown
Labels: current
