Repository home-assistant/home-assistant.io, pull requests merged in 2024-02, with the labels that each got.

#31180 Remove plus from lupusec XT3
  source/_integrations/lupusec.markdown
Labels: in-progress, next, needs-rebase

#31181 Add notes to link between the two Traccar integrations
  source/_integrations/traccar.markdown
  source/_integrations/traccar_server.markdown
Labels: next, has-parent

#31183 Assist: update screenshots to reflect current SW
  source/images/assist/assist-assistants-page.png
  source/images/assist/assistants_ha_cloud.png
  source/images/assist/esp32-atom_silence_detection_01.png
  source/images/assist/wake_word_disable_on_atom_echo.png
  source/images/assist/wake_word_select_assistant.png
Labels: in-progress, next, needs-rebase

#31186 First draft of the voice feature on 2024.2
  source/_posts/2024-02-07-release-20242.markdown
  source/images/blog/2024-02/assist-custom-response-editor.png
  source/images/blog/2024-02/assist-custom-response.png
  source/images/blog/2024-02/assist-errors.png
Labels: rc

#31189 Fix typo in Advantage Air
  source/_integrations/advantage_air.markdown
Labels: current

#31190 Fix categories in Advantage Air
  source/_integrations/advantage_air.markdown
Labels: current

#31185 History panel: add screenshot and download function
  source/_integrations/history.markdown
  source/images/integrations/history/history-panel_export-data.png
  source/images/integrations/history/history-panel_including-long-term-storage.png
Labels: next

#31178 Add Duquesne Light virtual integration supported by opower
  source/_integrations/duquesne_light.markdown
Labels: awaits-parent, in-progress, next, has-parent

#31107 [add] details how StarLine integration works
  source/_integrations/starline.markdown
Labels: current

#31173 Add note about Blink live viewing feature
  source/_integrations/blink.markdown
Labels: current

#30599 Update moehlenhoff_alpha2.markdown
  source/_integrations/moehlenhoff_alpha2.markdown
Labels: current

#31200 Update influxdb.markdown
  source/_integrations/influxdb.markdown
Labels: current

#30217 Update Zigbee device limitation in zha.markdown
  source/_integrations/zha.markdown
Labels: current

#31203 Address brand filter review comments
  source/integrations/index.html
Labels: current

#31177 Add DQE to opower integration documentation
  source/_integrations/opower.markdown
Labels: in-progress, next, has-parent, parent-merged

#30472 Google Assistant SDK: Document steps to enable personal results
  source/_integrations/google_assistant_sdk.markdown
Labels: current

#31214 Update Elvia documentation to reflect that we fetch 3 years
  source/_integrations/elvia.markdown
Labels: next, has-parent

#31215 Change IoT class for Traccar Client
  source/_integrations/traccar.markdown
Labels: next, has-parent, parent-merged

#31208 make things clearer in proximity
  source/_integrations/proximity.markdown
Labels: in-progress, next, needs-rebase

#31220 Add docs for Qingping CO2 Temp RH
  source/_integrations/qingping.markdown
Labels: next, has-parent

#31096 Add speed lock to Tessie
  source/_integrations/tessie.markdown
Labels: next, has-parent

#31226 Add additional models to mopeka
  source/_integrations/mopeka.markdown
Labels: next, has-parent, parent-merged

#31225 Update mopeka to clarify the integration only supports LPG
  source/_integrations/mopeka.markdown
Labels: current

#31230 Add docs for SamSam integration
  source/_integrations/samsam.markdown
Labels: awaits-parent, next, has-parent

#31229 Add docs for ZonderGas integration
  source/_integrations/zondergas.markdown
Labels: next, has-parent, parent-merged

#31207 Add more context to the Traccar Server documentation
  .vscode/cSpell.json
  source/_integrations/traccar_server.markdown
  source/blueprints/integrations/traccar_server_device_enter_geofence.yaml
  source/blueprints/integrations/traccar_server_device_speed_limit.yaml
Labels: next, has-parent

#31231 Add AirNow Troubleshooting Instructions
  source/_integrations/airnow.markdown
Labels: current

#31232 Add WIFIShop.ro to the distributors list
  source/green/index.html
  source/skyconnect/index.html
Labels: current

#31212 Update tuya.markdown with instructions for new user code functionality
  source/_integrations/tuya.markdown
Labels: in-progress, next, needs-rebase

#31242 Update integration supported device model list
  source/_integrations/yolink.markdown
Labels: current

#31236 Add additional proximity sensors
  source/_integrations/proximity.markdown
Labels: next, has-parent, parent-merged

#31237 adjust proximity breaking change message
  source/_posts/2024-02-07-release-20242.markdown
Labels: has-parent, parent-merged, rc

#31227 Rewrite xiaomi-ble documentation
  source/_integrations/xiaomi_ble.markdown
Labels: next, has-parent, parent-merged

#31115 Update screenlogic.markdown
  source/_integrations/screenlogic.markdown
Labels: next, has-parent, parent-merged

#31140 Matter: restructure section on adding device
  source/_integrations/matter.markdown
Labels: current

#31250 Add new way to obtain the key to Yale Access Bluetooth
  source/_integrations/yalexs_ble.markdown
Labels: current

#31247 Assist: add steps on adding conversation response
  source/images/assist/assist_set-conversation-response.png
  source/images/assist/assist_set-conversation-response_02.png
  source/voice_control/assist_set-conversation-response.png
  source/voice_control/custom_sentences.markdown
Labels: in-progress, next, needs-rebase

#31134 Update for Powerview Gen3 support
  source/_integrations/hunterdouglas_powerview.markdown
Labels: next, has-parent, parent-merged

#30997 System Monitor process binary sensor
  source/_integrations/systemmonitor.markdown
Labels: next, has-parent, parent-merged

#31254 Add new supported models for A. O. Smith
  source/_integrations/aosmith.markdown
Labels: in-progress, next, has-parent, parent-merged

#31259 Add missing section and adjust grammar
  source/_integrations/elvia.markdown
Labels: next, has-parent

#31263 Matter: share device with other platform
  source/_integrations/matter.markdown
  source/images/integrations/matter/matter_share-device-with-other-platform.png
Labels: in-progress, next, has-parent

#31267 Matter: add device information
  source/_integrations/matter.markdown
  source/images/integrations/matter/matter_device-info.png
Labels: next, has-parent

#31255 Add tapo virtual integration
  source/_integrations/tplink_tapo.markdown
Labels: in-progress, next, has-parent

#31285 Move refs to documentaion on MQTT supported components to the config section
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#31271 Add update category to myuplink
  source/_integrations/myuplink.markdown
Labels: in-progress, next, has-parent, parent-merged

#31137 Update growatt_server.markdown
  source/_integrations/growatt_server.markdown
Labels: in-progress, next, has-parent

#31286 Wake word: add info that extra hardware is needed to use it
  source/voice_control/install_wake_word_add_on.markdown
Labels: current

#31287 Add mqtt sensor example processing epoch timestamps
  source/_integrations/sensor.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#31270 Matter: remove device from fabric
  source/_integrations/matter.markdown
  source/images/integrations/matter/matter-remove-from-network.png
Labels: next, has-parent

#31293 Add TBW-106UB Bluetooth adapter to High Performance adapters
  source/_integrations/bluetooth.markdown
Labels: current

#31308 Fix broken link to analytics integration
  source/_integrations/analytics_insights.markdown
Labels: current

#31265 Explain the custom polling
  source/_includes/common-tasks/define_custom_polling.md
  source/common-tasks/general.markdown
Labels: current

#31317 Thread: make HA first Thread network
  source/_integrations/thread.markdown
  source/images/integrations/thread/thread-preferred-network-ha-only.png
Labels: current

#31318 Add documentation for QR code selector
  plugins/configuration.rb
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/selector-qr-code.png
Labels: current

#31313 Fix February typo
  source/_posts/2024-02-07-release-20242.markdown
Labels: current

#31332 2024.2.1
  _config.yml
  source/_posts/2024-02-07-release-20242.markdown
  source/changelogs/core-2024.2.markdown
Labels: blog, current, has-parent

#31330 Document scan_interval support for RESTful switch
  source/_integrations/switch.rest.markdown
Labels: current

#31326 Describe to use entity rather than device for Enphase Custom poll interval
  source/_integrations/enphase_envoy.markdown
Labels: current

#31346 Update withings.markdown
  source/_integrations/withings.markdown
Labels: current

#31353 Fix Motionblinds brand name consistency
  source/_integrations/motion_blinds.markdown
Labels: current, has-parent

#31348 Revert "Document scan_interval support for RESTful switch"
  source/_integrations/switch.rest.markdown
Labels: in-progress, current, needs-rebase

#31381 Update reseller list of EnergyZero
  source/_integrations/energyzero.markdown
Labels: current

#31371 Add TP970 to thermopro
  source/_integrations/thermopro.markdown
Labels: next, has-parent, parent-merged

#31370 Update tod.markdown, correct daylight saving time name.
  source/_integrations/tod.markdown
Labels: current

#31363 Update switch.template.markdown
  source/_integrations/switch.template.markdown
Labels: current

#31379 Add Domadoo as a SkyConnect distributor
  source/skyconnect/index.html
Labels: current

#31385 Add a note specifying that the Elvia integration provides no entities
  source/_integrations/elvia.markdown
Labels: current

#31386 Add myuplink diagnostics to ha_platforms
  source/_integrations/myuplink.markdown
Labels: next, has-parent, parent-merged

#31388 Update voice video
  source/voice_control/index.markdown
Labels: current

#31390 Correct Rejseplanen documentation (fixes #31350)
  source/_integrations/rejseplanen.markdown
Labels: current

#31399 Minor typo fixes
  source/installation/macos.markdown
  source/installation/raspberrypi.markdown
  source/security/index.markdown
Labels: current

#31397 Clarrify update install on Tessie
  source/_integrations/tessie.markdown
Labels: in-progress, current, has-parent, needs-rebase

#30909 Add additional number entities to La Marzocco
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent

#31402 Mark hardware integration as enabled by default
  source/_integrations/hardware.markdown
Labels: current

#31400 External data disk: style tweaks
  source/_includes/common-tasks/data_disk.md
Labels: current

#31373 Fix Motionblinds brand name consistency in virtual integrations
  source/_integrations/amp_motorization.markdown
  source/_integrations/bliss_automation.markdown
  source/_integrations/bloc_blinds.markdown
  source/_integrations/brel_home.markdown
  source/_integrations/diaz.markdown
  source/_integrations/dooya.markdown
  source/_integrations/gaviota.markdown
  source/_integrations/havana_shade.markdown
  source/_integrations/hurrican_shutters_wholesale.markdown
  source/_integrations/inspired_shades.markdown
  source/_integrations/ismartwindow.markdown
  source/_integrations/martec.markdown
  source/_integrations/raven_rock_mfg.markdown
  source/_integrations/screenaway.markdown
  source/_integrations/smart_blinds.markdown
  source/_integrations/smart_home.markdown
  source/_integrations/uprise_smart_shades.markdown
Labels: in-progress, current

#31405 Thread: add HA Thread network when third-party Thread nw is present
  source/_integrations/thread.markdown
  source/images/integrations/thread/thread-google-br.png
  source/images/integrations/thread/thread-ha-and-google-br.png
  source/images/integrations/thread/thread-ha-preferred.png
  source/images/integrations/thread/thread-no-preferred-network-but-third-party-present.png
Labels: current

#31367 Add documentation for number in the Flexit Nordic integration
  source/_integrations/flexit_bacnet.markdown
Labels: next, has-parent, parent-merged

#26455 Add Velux config flow
  source/_integrations/velux.markdown
Labels: next, has-parent, parent-merged

#31419 Removed references to the Alexa web-based app
  source/_integrations/alexa.smart_home.markdown
Labels: current

#31420 Fix minor typos/punctuation, improve some phrasing
  source/_integrations/airnow.markdown
  source/_integrations/alert.markdown
  source/_integrations/ambiclimate.markdown
  source/_integrations/androidtv_remote.markdown
  source/_integrations/anthemav.markdown
  source/_integrations/aosmith.markdown
  source/_integrations/braviatv.markdown
  source/_integrations/caldav.markdown
  source/_integrations/doorbird.markdown
  source/_integrations/ecovacs.markdown
  source/_integrations/environment_canada.markdown
  source/_integrations/envisalink.markdown
Labels: current

#31355 Positioning terminology tooltip to be always fully visible
  sass/custom/_terminology_tooltip.scss
  source/_includes/javascripts/scripts.html
  source/javascripts/terminology_tooltip.js
Labels: current

#31413 integrations:sony_projector:Clarify need to allow host IP
  source/_integrations/sony_projector.markdown
Labels: current

#31369 Document `switch.pi_hole_FRIENDLYNAME`
  source/_integrations/pi_hole.markdown
Labels: current

#31339 Signal messenger: mention the 'mode' parameter
  source/_integrations/signal_messenger.markdown
Labels: current

#31323 Add documentation of state_translated jinja function
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#31424 pi-hole: implement review feedback
  source/_integrations/pi_hole.markdown
Labels: current

#31425 Docs aside nav: make troubleshooting titles more explicit
  source/_includes/asides/docs_navigation.html
Labels: current

#31428 Update grid.markdown
  source/_dashboards/grid.markdown
Labels: current

#31437 Add health category for Airthings
  source/_integrations/airthings.markdown
  source/_integrations/airthings_ble.markdown
Labels: current

#31443 Fix typo in logger.markdown
  source/_integrations/logger.markdown
Labels: current

#31445 Authentication: remove section on migrating from 0.77
  source/_docs/authentication.markdown
Labels: current

#31444 List of TBRs: add intro sentence
  source/_integrations/thread.markdown
Labels: current

#31448 Event entity definition: rephrase
  source/_integrations/event.markdown
  source/images/integrations/event/event_timestamp.png
Labels: current

#31451 Add Z-Wave Alliance blog
  source/_posts/2024-02-15-nabu-casa-joins-z-wave-alliance.markdown
  source/images/blog/2024-02-zwave/nabucasa-zwa.png
Labels: current

#31456 Misc typos and phrasing improvements
  source/_integrations/google_maps.markdown
  source/_integrations/group.markdown
  source/_integrations/homekit_controller.markdown
  source/_integrations/homewizard.markdown
  source/_integrations/hue.markdown
Labels: current

#31454 Update govee_light_local supported device list
  source/_integrations/govee_light_local.markdown
Labels: current

#31446 Ls339/datadog docs
  source/_integrations/datadog.markdown
Labels: current

#28912 Add toggle service to climate
  source/_integrations/climate.markdown
Labels: next, has-parent, parent-merged

#31465 Add Voice chapter 6 livestream blog
  source/_posts/2024-02-16-voice-chapter-6-livestream.markdown
  source/images/blog/2024-02-voice-chapter-6/banner.png
Labels: current

#31467 Misc spelling, wording improvements
  source/_integrations/accuweather.markdown
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/analytics.markdown
  source/_integrations/apprise.markdown
  source/_integrations/aurora_abb_powerone.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/drop_connect.markdown
  source/_integrations/elv.markdown
  source/_integrations/entur_public_transport.markdown
  source/_integrations/fireservicerota.markdown
  source/_integrations/fritz.markdown
  source/_integrations/frontend.markdown
Labels: current

#31462 Add switch to Renson integration
  source/_integrations/renson.markdown
Labels: next, has-parent, parent-merged

#31410 Document credentials update for Enphase Envoy
  source/_integrations/enphase_envoy.markdown
Labels: next, has-parent

#31394 Add myuplink binary sensor
  source/_integrations/myuplink.markdown
Labels: next, has-parent

#31493 Clearify that Reolink Visitor sensor are Doorbell presses
  source/_integrations/reolink.markdown
Labels: current

#31496 state_object: Context: keywords with backticks
  source/_docs/configuration/state_object.markdown
Labels: current

#31505 Fix Shelly website address
  source/_integrations/shelly.markdown
Labels: current

#31441 Update Yellow distributors list
  source/yellow/index.html
Labels: current

#31514 Google assistant integration: Remove duplicated sections and improve steps
  source/_integrations/google_assistant.markdown
Labels: current

#31510 Update dte_energy_bridge.markdown
  source/_integrations/dte_energy_bridge.markdown
Labels: current

#31520 Add note to Google Tasks that due time is not supported
  source/_integrations/google_tasks.markdown
Labels: current

#28817 Add documentation for the new Husqvarna Automower integration
  source/_integrations/husqvarna_automower.markdown
  source/images/integrations/husqvarna_automower/application_overview.png
  source/images/integrations/husqvarna_automower/connect_authentication_api.png
  source/images/integrations/husqvarna_automower/connect_automower_api.png
  source/images/integrations/husqvarna_automower/create_new_application.png
Labels: next, has-parent, parent-merged

#31533 Upgrade to ESP Web Tools to v10
  source/_posts/2021-06-16-power-up-your-esp-projects.markdown
  source/voice_control/s3_box_voice_assistant.markdown
  source/voice_control/thirteen-usd-voice-remote.markdown
Labels: current

#31513 S3-BOX: update installation tutorial to reflect current firmware
  source/_includes/asides/voice_navigation.html
  source/_includes/voice_assistant/install_esp_firmware.md
  source/images/assist/wake_word_engine_location.png
  source/voice_control/about_wake_word.markdown
  source/voice_control/s3-box-customize.markdown
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#31536 Assist: Update sections on adding entity aliases, adding alias for area
  source/images/assist/assist_aliases.png
  source/images/assist/assist_aliases_02.png
  source/voice_control/aliases.markdown
Labels: current

#31527 Bluetooth: Fix link to ESPHome bluetooth proxy documentation
  source/_integrations/bluetooth.markdown
Labels: current

#31538 Distribution
  source/green/index.html
  source/skyconnect/index.html
  source/yellow/index.html
Labels: current

#31529 Add more supported VeSync Vital devices
  source/_integrations/vesync.markdown
Labels: next, has-parent, parent-merged

#31511 Add SMLIGHT SLZB-07 to ZHA Discovery
  source/_integrations/zha.markdown
Labels: next, has-parent

#31519 Blog post for voice chapter 6
  source/_posts/2024-02-21-voice-chapter-6.markdown
  source/images/blog/2024-02-21-voice-chapter-6/alias.png
  source/images/blog/2024-02-21-voice-chapter-6/assist-custom-response-editor.png
  source/images/blog/2024-02-21-voice-chapter-6/challenge.png
  source/images/blog/2024-02-21-voice-chapter-6/debug_tool.png
  source/images/blog/2024-02-21-voice-chapter-6/error_messages.png
  source/images/blog/2024-02-21-voice-chapter-6/expose.png
  source/images/blog/2024-02-21-voice-chapter-6/ha-support.png
  source/images/blog/2024-02-21-voice-chapter-6/social.jpg
Labels: in-progress, current

#31547 Change firmware link to wake word for S3 BOX tutorial
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#31544 Fix information about SimpliSafe plans
  source/_integrations/simplisafe.markdown
Labels: current

#31545 Adjust heading levels in template sensor docs
  source/_integrations/template.markdown
Labels: current

#31524 Updated list of supported device models
  source/_integrations/yolink.markdown
Labels: current

#31526 Update weatherflow.markdown
  source/_integrations/weatherflow.markdown
Labels: in-progress, current, has-parent, needs-rebase

#31472 Add velocity and number information for powerview
  source/_integrations/hunterdouglas_powerview.markdown
Labels: next, has-parent, parent-merged

#31488 Update supported device list for Govee lights local
  source/_integrations/govee_light_local.markdown
Labels: next, has-parent, parent-merged

#30893 Add documentation for the La Marzocco calendar
  source/_integrations/lamarzocco.markdown
Labels: next, has-parent, parent-merged

#31551 Add custom integration explanation to Analytics insights
  source/_integrations/analytics_insights.markdown
Labels: current

#31476 Add myuplink switch platform
  source/_integrations/myuplink.markdown
Labels: in-progress, next, has-parent, parent-merged

#31554 S3-BOX-3: change on-device wake word procedure
  source/voice_control/s3-box-customize.markdown
Labels: current

#31556 Update Voice Ch6 blog
  source/_posts/2024-02-21-voice-chapter-6.markdown
Labels: current

#31558 Custom sentences: add more details to conversation response step
  source/_docs/automation/trigger.markdown
  source/voice_control/custom_sentences.markdown
Labels: current

#31564 added sensor platform to microBees Integration
  source/_integrations/microbees.markdown
Labels: next, has-parent

#31560 S3-BOX: installing and customizing microWakeWord
  source/images/assist/wake_word_engine_location.png
  source/voice_control/s3-box-customize.markdown
Labels: current

#31528 Add documentation for Husqvarna Automower switch
  source/_integrations/husqvarna_automower.markdown
Labels: next, has-parent, parent-merged

#31591 Add known issues section to Verisure
  source/_integrations/verisure.markdown
Labels: current

#31594 Add a note about shared pets to the Tractive documentation
  source/_integrations/tractive.markdown
Labels: current

#31596 Clearify Reolink camera streams
  source/_integrations/reolink.markdown
Labels: current

#31605 Change wording on sql integration
  source/_integrations/sql.markdown
Labels: current

#31427 Add information on recovery and safe mode
  source/_docs/troubleshooting_general.markdown
  source/_includes/asides/docs_navigation.html
  source/_integrations/recovery_mode.markdown
  source/images/docs/troubleshooting/recovery_mode_active.png
Labels: current

#31415 feat: add ECO temp to Generic Thermostat.
  source/_integrations/generic_thermostat.markdown
Labels: next, has-parent, parent-merged

#31570 Add myuplink number entity
  source/_integrations/myuplink.markdown
Labels: next, has-parent, parent-merged

#31506 Onboarding: use pencil icon to start editing the dashboard
  source/getting-started/onboarding_dashboard.markdown
Labels: current

#31625 Copying backup: clarify how to open backup dialog
  source/_includes/common-tasks/backups.md
Labels: current

#31466 Z-Wave controllers: add Razberry hat config for Pi 5
  source/_docs/z-wave/controllers.markdown
Labels: current

#31440 Raspberry Pi installation: update to include Raspberry Pi 5
  _config.yml
  source/images/installation/rpi-ha.gif
  source/images/installation/rpi-ha.webp
  source/images/installation/rpi_choose_next.png
  source/images/installation/rpi_imager_start.png
  source/installation/raspberrypi.markdown
Labels: current

#31628 Add Motionblinds virtual integration Krispol
  source/_integrations/krispol.markdown
Labels: next, has-parent, parent-merged

#31627 Add Motionblinds virtual integration Acomax
  source/_integrations/acomax.markdown
Labels: next, has-parent, parent-merged
