Repository home-assistant/home-assistant.io, pull requests merged in 2024-05, with the labels that each got.

#32549 2024.5: small fixes to text
  source/_posts/2024-05-01-release-20245.markdown
Labels: in-progress, needs-rebase, rc

#32551 Installation on RPi: add internet connection as prereq
  source/installation/raspberrypi.markdown
Labels: current

#32540 Add documentation for IMGW-PIB
  source/_integrations/imgw_pib.markdown
Labels: next, has-parent, parent-merged

#32556 Remove references to UniFi WLAN password sensor
  source/changelogs/core-2024.5.markdown
Labels: in-progress, current

#32465 Add cutting height for work areas to Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#32564 Revert "Remove references to UniFi WLAN password sensor"
  source/changelogs/core-2024.5.markdown
Labels: in-progress, current, needs-rebase

#32567 Add information about IMGW-PIB binary_sensor platform
  source/_integrations/imgw_pib.markdown
Labels: next, has-parent, parent-merged

#32552 HA OS installation: add note on internet access
  source/_includes/common-tasks/flashing_n2_otg.md
  source/_includes/installation/operating_system.md
Labels: current

#32576 Add title option to notify entity
  source/_integrations/notify.markdown
Labels: awaits-parent, next, has-parent

#32580 Update nina.markdown
  source/_integrations/nina.markdown
Labels: current

#32579 Update python_script.markdown
  source/_integrations/python_script.markdown
Labels: current

#32581 2024.5.1
  _config.yml
  source/_posts/2024-05-01-release-20245.markdown
  source/changelogs/core-2024.5.markdown
Labels: current, has-parent

#32488 Remove API Key instructions from Hydrawise docs
  source/_integrations/hydrawise.markdown
Labels: current, has-parent, parent-merged

#32584 Fix typo
  source/voice_control/s3-box-customize.markdown
Labels: current

#32597 Update emulated_roku.markdown
  source/_integrations/emulated_roku.markdown
Labels: current

#32591 Add troubleshooting to Yale Access Bluetooth
  source/_integrations/yalexs_ble.markdown
Labels: current

#32610 2024.5.2
  _config.yml
  source/_posts/2024-05-01-release-20245.markdown
  source/changelogs/core-2024.5.markdown
Labels: current, has-parent

#32575 Update list of supported devices for govee-light-local
  source/_integrations/govee_light_local.markdown
Labels: awaits-parent, next, has-parent

#32308 Update DNS IP regarding multiple IPs
  source/_integrations/dnsip.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#32619 Add glossentry for configuration.yaml file
  source/_data/glossary.yml
Labels: current

#32621 Snippet on reloading HA after configuration change
  source/_includes/integrations/reload_ha_after_config_inclusion.md
Labels: current

#32624 Fix reload include with configuration.yaml term
  sass/custom/_terminology_tooltip.scss
  source/_data/glossary.yml
  source/_includes/integrations/reload_ha_after_config_inclusion.md
  source/_includes/integrations/restart_ha_after_config_inclusion.md
Labels: current

#32626 Make statement to find new entities conditional
  source/_includes/integrations/restart_ha_after_config_inclusion.md
Labels: current

#32627 Add information to restart Home Assistant after adding the integratio…
  source/_integrations/acer_projector.markdown
  source/_integrations/actiontec.markdown
  source/_integrations/ads.markdown
  source/_integrations/alert.markdown
  source/_integrations/alpha_vantage.markdown
  source/_integrations/amazon_polly.markdown
  source/_integrations/amcrest.markdown
  source/_integrations/ampio.markdown
  source/_integrations/anel_pwrctrl.markdown
  source/_integrations/apprise.markdown
  source/_integrations/aprs.markdown
  source/_integrations/aqualogic.markdown
  source/_integrations/aquostv.markdown
  source/_integrations/arest.markdown
  source/_integrations/arris_tg2492lg.markdown
  source/_integrations/aruba.markdown
  source/_integrations/arwn.markdown
  source/_integrations/assist_pipeline.markdown
  source/_integrations/atome.markdown
  source/_integrations/avea.markdown
  source/_integrations/avion.markdown
  source/_integrations/aws.markdown
  source/_integrations/azure_service_bus.markdown
Labels: current

#32628 Snippet: restart after config change: add condition
  source/_includes/integrations/restart_ha_after_config_inclusion.md
Labels: current

#32629 restart HA after adding the integration to the configuration.yaml
  source/_integrations/baidu.markdown
  source/_integrations/bayesian.markdown
  source/_integrations/bbox.markdown
  source/_integrations/beewi_smartclim.markdown
  source/_integrations/bitcoin.markdown
  source/_integrations/bizkaibus.markdown
  source/_integrations/blackbird.markdown
  source/_integrations/blinksticklight.markdown
  source/_integrations/blockchain.markdown
  source/_integrations/bloomsky.markdown
  source/_integrations/bluesound.markdown
  source/_integrations/bluetooth.markdown
  source/_integrations/bluetooth_le_tracker.markdown
  source/_integrations/bluetooth_tracker.markdown
  source/_integrations/broadlink.markdown
  source/_integrations/browser.markdown
  source/_integrations/bt_home_hub_5.markdown
  source/_integrations/bt_smarthub.markdown
Labels: current

#32630 restart HA after adding the integration to the configuration.yaml file
  source/_integrations/caldav.markdown
  source/_integrations/channels.markdown
  source/_integrations/cisco_ios.markdown
  source/_integrations/cisco_mobility_express.markdown
  source/_integrations/cisco_webex_teams.markdown
  source/_integrations/citybikes.markdown
  source/_integrations/clementine.markdown
  source/_integrations/clickatell.markdown
  source/_integrations/clicksend.markdown
  source/_integrations/cmus.markdown
  source/_integrations/comed_hourly_pricing.markdown
  source/_integrations/command_line.markdown
  source/_integrations/compensation.markdown
  source/_integrations/concord232.markdown
  source/_integrations/cppm_tracker.markdown
  source/_integrations/cups.markdown
  source/_integrations/currencylayer.markdown
Labels: current

#32632 Snippet: fix variable
  source/_includes/integrations/restart_ha_after_config_inclusion.md
Labels: current

#32637 Fix date on community winners
  source/_posts/2024-03-16-voice-assistant-community-contest-winners-annoucement.markdown
Labels: current

#32640 Convert service data table to configuration_basic
  source/_integrations/update.markdown
Labels: current

#32642 Add blogpost about Z-Wave
  source/_posts/2024-05-08-zwave-is-not-dead.markdown
  source/images/blog/2024-05-zwave-is-not-dead/art.jpg
  source/images/blog/2024-05-zwave-is-not-dead/drzwave.jpeg
  source/images/blog/2024-05-zwave-is-not-dead/firmware.png
  source/images/blog/2024-05-zwave-is-not-dead/keynote.png
  source/images/blog/2024-05-zwave-is-not-dead/paulus-z-wave.jpeg
  source/images/blog/2024-05-zwave-is-not-dead/unplug.jpeg
Labels: current

#32645 l-integrations: restart HA after changing config
  source/_integrations/lacrosse.markdown
  source/_integrations/lannouncer.markdown
  source/_integrations/lifx_cloud.markdown
  source/_integrations/lightwave.markdown
  source/_integrations/limitlessled.markdown
  source/_integrations/linksys_smart.markdown
  source/_integrations/linode.markdown
  source/_integrations/linux_battery.markdown
  source/_integrations/llamalab_automate.markdown
  source/_integrations/local_file.markdown
  source/_integrations/logentries.markdown
  source/_integrations/london_air.markdown
  source/_integrations/london_underground.markdown
  source/_integrations/luci.markdown
  source/_integrations/lw12wifi.markdown
Labels: current

#32643 i-integrations: restart HA after changing config
  source/_integrations/iammeter.markdown
  source/_integrations/iglo.markdown
  source/_integrations/ign_sismologia.markdown
  source/_integrations/ihc.markdown
  source/_integrations/incomfort.markdown
  source/_integrations/influxdb.markdown
  source/_integrations/iperf3.markdown
  source/_integrations/irish_rail_transport.markdown
  source/_integrations/itach.markdown
  source/_integrations/itunes.markdown
  source/_integrations/izone.markdown
Labels: current

#31223 Change Anova to cloud push
  source/_integrations/anova.markdown
Labels: awaits-parent, next, has-parent

#32641 h-integrations: restart HA after changing config
  source/_integrations/harman_kardon_avr.markdown
  source/_integrations/haveibeenpwned.markdown
  source/_integrations/hddtemp.markdown
  source/_integrations/hikvisioncam.markdown
  source/_integrations/history_stats.markdown
  source/_integrations/hitron_coda.markdown
  source/_integrations/homematic.markdown
  source/_integrations/horizon.markdown
  source/_integrations/hp_ilo.markdown
  source/_integrations/html5.markdown
Labels: current

#32646 m-integrations 1/2: restart HA after changing config
  source/_integrations/manual.markdown
  source/_integrations/manual_mqtt.markdown
  source/_integrations/marytts.markdown
  source/_integrations/mastodon.markdown
  source/_integrations/matrix.markdown
  source/_integrations/maxcube.markdown
  source/_integrations/media_extractor.markdown
  source/_integrations/mediaroom.markdown
  source/_integrations/melissa.markdown
  source/_integrations/meraki.markdown
  source/_integrations/message_bird.markdown
  source/_integrations/mfi.markdown
  source/_integrations/microsoft.markdown
  source/_integrations/microsoft_face.markdown
  source/_integrations/microsoft_face_detect.markdown
  source/_integrations/microsoft_face_identify.markdown
Labels: current

#32651 n integrations 2/2: restart HA after changing config
  source/_integrations/nissan_leaf.markdown
  source/_integrations/nmbs.markdown
  source/_integrations/no_ip.markdown
  source/_integrations/noaa_tides.markdown
  source/_integrations/norway_air.markdown
  source/_integrations/notify_events.markdown
  source/_integrations/nsw_rural_fire_service_feed.markdown
  source/_integrations/nx584.markdown
Labels: current

#32649 m integrations 2/2: restart HA after changing config
  source/_integrations/mochad.markdown
  source/_integrations/modbus.markdown
  source/_integrations/mold_indicator.markdown
  source/_integrations/mpd.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/mqtt_eventstream.markdown
  source/_integrations/mqtt_json.markdown
  source/_integrations/mqtt_room.markdown
  source/_integrations/mqtt_statestream.markdown
  source/_integrations/mvglive.markdown
  source/_integrations/mycroft.markdown
  source/_integrations/mystrom.markdown
  source/_integrations/mythicbeastsdns.markdown
Labels: current

#32639 g-integrations: restart HA after changing config
  source/_integrations/garadget.markdown
  source/_integrations/gc100.markdown
  source/_integrations/generic_hygrostat.markdown
  source/_integrations/generic_thermostat.markdown
  source/_integrations/geo_rss_events.markdown
  source/_integrations/geofency.markdown
  source/_integrations/gitlab_ci.markdown
  source/_integrations/gitter.markdown
  source/_integrations/google_domains.markdown
  source/_integrations/google_maps.markdown
  source/_integrations/google_pubsub.markdown
  source/_integrations/google_wifi.markdown
  source/_integrations/graphite.markdown
  source/_integrations/greeneye_monitor.markdown
  source/_integrations/gstreamer.markdown
  source/_integrations/gtfs.markdown
Labels: current

#32659 Add screenshot from slides to Z-Wave blog post
  source/_posts/2024-05-08-zwave-is-not-dead.markdown
  source/images/blog/2024-05-zwave-is-not-dead/slide.png
Labels: current

#32658 Add mention of Open Home Foundation
  source/_includes/asides/about.html
  source/_includes/site/footer.html
Labels: current

#32636 f-integrations: restart HA after changing config
  source/_integrations/facebook.markdown
  source/_integrations/fail2ban.markdown
  source/_integrations/familyhub.markdown
  source/_integrations/feedreader.markdown
  source/_integrations/ffmpeg_motion.markdown
  source/_integrations/ffmpeg_noise.markdown
  source/_integrations/fido.markdown
  source/_integrations/file.markdown
  source/_integrations/filter.markdown
  source/_integrations/fints.markdown
  source/_integrations/fixer.markdown
  source/_integrations/fleetgo.markdown
  source/_integrations/flexit.markdown
  source/_integrations/flic.markdown
  source/_integrations/flock.markdown
  source/_integrations/flume.markdown
  source/_integrations/flux.markdown
  source/_integrations/fortios.markdown
  source/_integrations/foursquare.markdown
  source/_integrations/free_mobile.markdown
  source/_integrations/freedns.markdown
  source/_integrations/frontier_silicon.markdown
  source/_integrations/futurenow.markdown
Labels: current

#32635 e-integrations: Restart HA after adding the integration to the configuration.yaml
  source/_integrations/ebox.markdown
  source/_integrations/ebusd.markdown
  source/_integrations/ecoal_boiler.markdown
  source/_integrations/ecobee.markdown
  source/_integrations/eddystone_temperature.markdown
  source/_integrations/edimax.markdown
  source/_integrations/egardia.markdown
  source/_integrations/eliqonline.markdown
  source/_integrations/elkm1.markdown
  source/_integrations/elv.markdown
  source/_integrations/emby.markdown
  source/_integrations/emoncms.markdown
  source/_integrations/emoncms_history.markdown
  source/_integrations/emulated_hue.markdown
  source/_integrations/emulated_kasa.markdown
  source/_integrations/emulated_roku.markdown
  source/_integrations/enocean.markdown
  source/_integrations/entur_public_transport.markdown
  source/_integrations/envisalink.markdown
  source/_integrations/etherscan.markdown
  source/_integrations/eufy.markdown
  source/_integrations/everlights.markdown
  source/_integrations/evohome.markdown
Labels: current

#32650 n integrations 1/2: restart HA after changing config
  source/_integrations/nad.markdown
  source/_integrations/namecheapdns.markdown
  source/_integrations/nederlandse_spoorwegen.markdown
  source/_integrations/ness_alarm.markdown
  source/_integrations/netdata.markdown
  source/_integrations/netio.markdown
  source/_integrations/neurio_energy.markdown
  source/_integrations/niko_home_control.markdown
  source/_integrations/nilu.markdown
Labels: current

#32653 o-integrations: restart HA after changing config
  source/_integrations/oasa_telematics.markdown
  source/_integrations/oem.markdown
  source/_integrations/ohmconnect.markdown
  source/_integrations/ombi.markdown
  source/_integrations/onkyo.markdown
  source/_integrations/openalpr_cloud.markdown
  source/_integrations/openerz.markdown
  source/_integrations/openevse.markdown
  source/_integrations/openhardwaremonitor.markdown
  source/_integrations/opensensemap.markdown
  source/_integrations/opple.markdown
  source/_integrations/oru.markdown
  source/_integrations/osramlightify.markdown
  source/_integrations/otp.markdown
Labels: current

#32638 Restart snippet: add condition for generic ha domain
  source/_includes/integrations/restart_ha_after_config_inclusion.md
Labels: current

#32020 Add airgradient
  source/_integrations/airgradient.markdown
Labels: next, has-parent, parent-merged

#32644 j-k-integrations: restart HA after config change
  source/_integrations/jewish_calendar.markdown
  source/_integrations/joaoapps_join.markdown
  source/_integrations/kaiterra.markdown
  source/_integrations/kankun.markdown
  source/_integrations/keba.markdown
  source/_integrations/kef.markdown
  source/_integrations/keyboard_remote.markdown
  source/_integrations/kitchen_sink.markdown
  source/_integrations/kiwi.markdown
  source/_integrations/knx.markdown
  source/_integrations/kwb.markdown
Labels: current

#32633 d-integrations: restart HA after adding the integration to the configuration.yaml
  source/_integrations/danfoss_air.markdown
  source/_integrations/datadog.markdown
  source/_integrations/ddwrt.markdown
  source/_integrations/debugpy.markdown
  source/_integrations/delijn.markdown
  source/_integrations/demo.markdown
  source/_integrations/denon.markdown
  source/_integrations/device_sun_light_trigger.markdown
  source/_integrations/dialogflow.markdown
  source/_integrations/digital_ocean.markdown
  source/_integrations/discogs.markdown
  source/_integrations/dlib_face_detect.markdown
  source/_integrations/dlib_face_identify.markdown
  source/_integrations/doods.markdown
  source/_integrations/dovado.markdown
  source/_integrations/dte_energy_bridge.markdown
  source/_integrations/dublin_bus_transport.markdown
  source/_integrations/duckdns.markdown
  source/_integrations/dweet.markdown
Labels: current

#32669 Music-assistant-blog-edit
  source/_posts/2024-05-09-music-assistant-2.markdown
  source/images/blog/2024-05-music-assistant/art.jpg
  source/images/blog/2024-05-music-assistant/come-together.png
  source/images/blog/2024-05-music-assistant/fight-the-power.jpg
  source/images/blog/2024-05-music-assistant/freedom-of-choice.png
  source/images/blog/2024-05-music-assistant/how-it-works.jpg
  source/images/blog/2024-05-music-assistant/start-me-up.png
  source/images/blog/2024-05-music-assistant/we-are-family.png
Labels: current

#32656 Group sensor add stdev
  source/_integrations/group.markdown
Labels: next, has-parent, parent-merged

#32682 2024.5.3
  source/_posts/2024-05-01-release-20245.markdown
Labels: in-progress, current, has-parent, needs-rebase

#32593 Migrate file integration to config entry
  source/_integrations/file.markdown
Labels: next, has-parent, parent-merged

#32677 Add device class to Command line cover platform
  source/_integrations/command_line.markdown
Labels: next, has-parent, parent-merged

#32652 Resolve terminology links causing new table rows
  plugins/terminology_tooltip.rb
Labels: current

#32690 Update version info to 2024.5.3
  _config.yml
Labels: current

#32678 Add Energy Info sensors to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: awaits-parent, next, has-parent

#32698 Changes file legacy notify service migration to notify entity service
  source/_integrations/file.markdown
Labels: awaits-parent, next, has-parent

#29279 Added docs for Monzo integration
  source/_integrations/monzo.markdown
Labels: Hacktoberfest, in-progress, next, has-parent, parent-merged

#32717 Sonos - updates to play media content ids
  source/_integrations/sonos.markdown
Labels: current

#32723 Remove add to project CI Job
  .github/workflows/add_prs_to_project.yml
Labels: current

#32720 s-integrations-1: restart HA after changing config
  source/_integrations/saj.markdown
  source/_integrations/satel_integra.markdown
  source/_integrations/schluter.markdown
  source/_integrations/scrape.markdown
  source/_integrations/scsgate.markdown
  source/_integrations/sendgrid.markdown
  source/_integrations/serial.markdown
  source/_integrations/sesame.markdown
  source/_integrations/seven_segments.markdown
  source/_integrations/shodan.markdown
Labels: current

#32721 s-integrations-2: restart HA after changing config
  source/_integrations/sigfox.markdown
  source/_integrations/sighthound.markdown
  source/_integrations/signal_messenger.markdown
  source/_integrations/sinch.markdown
  source/_integrations/sky_hub.markdown
  source/_integrations/skybeacon.markdown
  source/_integrations/slide.markdown
  source/_integrations/smappee.markdown
  source/_integrations/solaredge_local.markdown
  source/_integrations/spaceapi.markdown
Labels: current

#32716 p-q-integrations: restart HA after changing config
  source/_integrations/panasonic_viera.markdown
  source/_integrations/pandora.markdown
  source/_integrations/panel_custom.markdown
  source/_integrations/pencom.markdown
  source/_integrations/picotts.markdown
  source/_integrations/pilight.markdown
  source/_integrations/pioneer.markdown
  source/_integrations/pjlink.markdown
  source/_integrations/plant.markdown
  source/_integrations/pocketcasts.markdown
  source/_integrations/point.markdown
  source/_integrations/prometheus.markdown
  source/_integrations/prowl.markdown
  source/_integrations/proxmoxve.markdown
  source/_integrations/proxy.markdown
  source/_integrations/pulseaudio_loopback.markdown
  source/_integrations/push.markdown
  source/_integrations/pushsafer.markdown
  source/_integrations/pyload.markdown
  source/_integrations/qld_bushfire.markdown
  source/_integrations/qrcode.markdown
  source/_integrations/quantum_gateway.markdown
  source/_integrations/qvr_pro.markdown
  source/_integrations/qwikswitch.markdown
Labels: current

#32718 r-integrations: restart HA after changing config
  source/_integrations/raincloud.markdown
  source/_integrations/raspyrfm.markdown
  source/_integrations/recswitch.markdown
  source/_integrations/reddit.markdown
  source/_integrations/rejseplanen.markdown
  source/_integrations/remember_the_milk.markdown
  source/_integrations/remote_rpi_gpio.markdown
  source/_integrations/rest_command.markdown
  source/_integrations/rflink.markdown
  source/_integrations/ripple.markdown
  source/_integrations/rmvtransport.markdown
  source/_integrations/rocketchat.markdown
  source/_integrations/route53.markdown
  source/_integrations/rpi_camera.markdown
  source/_integrations/rss_feed_template.markdown
  source/_integrations/rtorrent.markdown
  source/_integrations/russound_rio.markdown
  source/_integrations/russound_rnet.markdown
Labels: current

#32726 t-integrations: restart HA after changing config
  source/_integrations/tank_utility.markdown
  source/_integrations/tapsaff.markdown
  source/_integrations/tcp.markdown
  source/_integrations/ted5000.markdown
  source/_integrations/telegram.markdown
  source/_integrations/tellduslive.markdown
  source/_integrations/tellstick.markdown
  source/_integrations/telnet.markdown
  source/_integrations/temper.markdown
  source/_integrations/tensorflow.markdown
  source/_integrations/tfiac.markdown
Labels: current

#32728 Make it more obvious that old logo is old and add links to download new
  source/_posts/2023-09-17-a-refreshed-logo-for-home-assistant.markdown
  source/images/blog/2023-09-ha10/logo 2.png
Labels: current

#32742 Add car category to Tessie and Teslemetry
  source/_integrations/teslemetry.markdown
  source/_integrations/tessie.markdown
Labels: current

#32745 w-integrations: restart HA after changing config
  source/_integrations/w800rf32.markdown
  source/_integrations/wake_on_lan.markdown
  source/_integrations/waterfurnace.markdown
  source/_integrations/watson_iot.markdown
  source/_integrations/watson_tts.markdown
  source/_integrations/wirelesstag.markdown
  source/_integrations/worldclock.markdown
  source/_integrations/worldtidesinfo.markdown
  source/_integrations/worxlandroid.markdown
  source/_integrations/wsdot.markdown
Labels: current

#32746 x-integrations: restart HA after changing config
  source/_integrations/x10.markdown
  source/_integrations/xeoma.markdown
  source/_integrations/xiaomi_tv.markdown
  source/_integrations/xmpp.markdown
  source/_integrations/xs1.markdown
Labels: current

#32744 v-integrations: restart HA after changing config
  source/_integrations/vasttrafik.markdown
  source/_integrations/versasense.markdown
  source/_integrations/viaggiatreno.markdown
  source/_integrations/vivotek.markdown
  source/_integrations/vlc.markdown
  source/_integrations/voicerss.markdown
  source/_integrations/volkszaehler.markdown
  source/_integrations/vultr.markdown
Labels: current

#32749 a-integrations: add glossary reference to Configuration file
  source/_integrations/ads.markdown
  source/_integrations/alarm_control_panel.ifttt.markdown
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/alarm_control_panel.template.markdown
  source/_integrations/alexa.flash_briefings.markdown
  source/_integrations/alexa.intent.markdown
  source/_integrations/alexa.smart_home.markdown
  source/_integrations/aqualogic.markdown
  source/_integrations/arest.markdown
  source/_integrations/assist_pipeline.markdown
  source/_integrations/aten_pe.markdown
  source/_integrations/aws.markdown
  source/_integrations/azure_event_hub.markdown
Labels: current

#32747 y-z-integrations: restart HA after changing config
  source/_integrations/yamaha.markdown
  source/_integrations/yandex_transport.markdown
  source/_integrations/yandextts.markdown
  source/_integrations/yeelightsunflower.markdown
  source/_integrations/zabbix.markdown
  source/_integrations/zengge.markdown
  source/_integrations/ziggo_mediabox_xl.markdown
  source/_integrations/zoneminder.markdown
Labels: current

#32750 a-integrations: add glossary reference to Configuration file
  source/_integrations/bbox.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/binary_sensor.rest.markdown
  source/_integrations/blink.markdown
  source/_integrations/bloomsky.markdown
  source/_integrations/bluetooth.markdown
  source/_integrations/broadlink.markdown
  source/_integrations/brother.markdown
Labels: current

#30740 Add Knx telegram trigger documentation
  source/_integrations/knx.markdown
Labels: awaits-parent, next, has-parent

#32756 g-h-integrations: add glossary reference to config file
  source/_integrations/garadget.markdown
  source/_integrations/gc100.markdown
  source/_integrations/geniushub.markdown
  source/_integrations/google_assistant.markdown
  source/_integrations/google_cloud.markdown
  source/_integrations/greenwave.markdown
  source/_integrations/group.markdown
  source/_integrations/harmony.markdown
  source/_integrations/heatmiser.markdown
  source/_integrations/heos.markdown
  source/_integrations/hikvision.markdown
  source/_integrations/history_stats.markdown
  source/_integrations/homekit.markdown
  source/_integrations/homekit_controller.markdown
  source/_integrations/homematic.markdown
  source/_integrations/homematicip_cloud.markdown
  source/_integrations/hp_ilo.markdown
  source/_integrations/humidifier.mqtt.markdown
Labels: current

#32753 d-integrations: add glossary reference to configuration.yaml
  source/_integrations/decora_wifi.markdown
  source/_integrations/default_config.markdown
  source/_integrations/device_tracker.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_tracker.xiaomi.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/digital_ocean.markdown
  source/_integrations/dovado.markdown
  source/_integrations/dweet.markdown
  source/_integrations/dynalite.markdown
Labels: current

#32755 f-integrations: add glossary reference to config file
  source/_integrations/fail2ban.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/ffmpeg.markdown
  source/_integrations/file.markdown
  source/_integrations/fireservicerota.markdown
  source/_integrations/firmata.markdown
  source/_integrations/folder.markdown
  source/_integrations/foobot.markdown
  source/_integrations/foursquare.markdown
  source/_integrations/freedns.markdown
  source/_integrations/frontend.markdown
  source/_integrations/futurenow.markdown
Labels: current

#32754 e-integrations: add glossary reference to config file
  source/_integrations/egardia.markdown
  source/_integrations/elkm1.markdown
  source/_integrations/enocean.markdown
  source/_integrations/ephember.markdown
  source/_integrations/esphome.markdown
Labels: current

#32757 i-k-integrations: add glossary reference to config file
  source/_integrations/ifttt.markdown
  source/_integrations/image.mqtt.markdown
  source/_integrations/influxdb.markdown
  source/_integrations/input_boolean.markdown
  source/_integrations/input_button.markdown
  source/_integrations/input_datetime.markdown
  source/_integrations/input_number.markdown
  source/_integrations/input_select.markdown
  source/_integrations/input_text.markdown
  source/_integrations/integration.markdown
  source/_integrations/intellifire.markdown
  source/_integrations/intesishome.markdown
  source/_integrations/izone.markdown
  source/_integrations/joaoapps_join.markdown
  source/_integrations/keba.markdown
  source/_integrations/keyboard.markdown
  source/_integrations/kodi.markdown
Labels: current

#32758 l-integrations: add glossary reference to config file
  source/_integrations/lacrosse.markdown
  source/_integrations/lawn_mower.mqtt.markdown
  source/_integrations/lcn.markdown
  source/_integrations/lg_netcast.markdown
  source/_integrations/light.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/linode.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/lock.template.markdown
  source/_integrations/logger.markdown
  source/_integrations/lutron_caseta.markdown
Labels: current

#32760 n-integrations: add glossary reference to config file
  source/_integrations/nest.markdown
  source/_integrations/netdata.markdown
  source/_integrations/network.markdown
  source/_integrations/nfandroidtv.markdown
  source/_integrations/notify.rest.markdown
  source/_integrations/notify.tts.markdown
  source/_integrations/notify_events.markdown
  source/_integrations/nsw_fuel_station.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/nx584.markdown
Labels: current

#32759 m-integrations: add glossary reference to config file
  source/_integrations/matrix.markdown
  source/_integrations/media_source.markdown
  source/_integrations/meteoalarm.markdown
  source/_integrations/mfi.markdown
  source/_integrations/microsoft_face.markdown
  source/_integrations/min_max.markdown
  source/_integrations/minio.markdown
  source/_integrations/mochad.markdown
  source/_integrations/motioneye.markdown
  source/_integrations/msteams.markdown
  source/_integrations/my.markdown
  source/_integrations/mycroft.markdown
Labels: current

#32761 o-r-integrations: add glossary reference to config file
  source/_integrations/opensky.markdown
  source/_integrations/owntracks.markdown
  source/_integrations/person.markdown
  source/_integrations/pilight.markdown
  source/_integrations/proliphix.markdown
  source/_integrations/ps4.markdown
  source/_integrations/python_script.markdown
  source/_integrations/raincloud.markdown
  source/_integrations/random.markdown
  source/_integrations/recorder.markdown
  source/_integrations/remote_rpi_gpio.markdown
  source/_integrations/rflink.markdown
  source/_integrations/rfxtrx.markdown
  source/_integrations/ring.markdown
Labels: current

#32762 s-integrations: add glossary reference to config file
  source/_integrations/scene.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/schedule.markdown
  source/_integrations/scsgate.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/sensor.rest.markdown
  source/_integrations/serial_pm.markdown
  source/_integrations/seven_segments.markdown
  source/_integrations/shelly.markdown
  source/_integrations/simulated.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/sisyphus.markdown
  source/_integrations/smartthings.markdown
  source/_integrations/smarty.markdown
  source/_integrations/smtp.markdown
  source/_integrations/snips.markdown
  source/_integrations/sony_projector.markdown
  source/_integrations/sql.markdown
  source/_integrations/stream.markdown
  source/_integrations/supla.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/switch.rest.markdown
  source/_integrations/switch.template.markdown
  source/_integrations/switchmate.markdown
  source/_integrations/system_log.markdown
Labels: current

#32601 Migrate Tibber notify service
  source/_integrations/tibber.markdown
Labels: awaits-parent, next, has-parent

#32764 u-z-integrations: add glossary reference to config file
  source/_integrations/ubus.markdown
  source/_integrations/ue_smart_radio.markdown
  source/_integrations/uk_transport.markdown
  source/_integrations/unifi_direct.markdown
  source/_integrations/universal.markdown
  source/_integrations/upb.markdown
  source/_integrations/upc_connect.markdown
  source/_integrations/update.mqtt.markdown
  source/_integrations/usb.markdown
  source/_integrations/usgs_earthquakes_feed.markdown
  source/_integrations/utility_meter.markdown
  source/_integrations/uvc.markdown
  source/_integrations/valve.mqtt.markdown
  source/_integrations/vizio.markdown
  source/_integrations/vultr.markdown
  source/_integrations/w800rf32.markdown
  source/_integrations/wake_on_lan.markdown
  source/_integrations/water_heater.markdown
  source/_integrations/water_heater.mqtt.markdown
  source/_integrations/weather.template.markdown
  source/_integrations/wirelesstag.markdown
  source/_integrations/xbox.markdown
  source/_integrations/xiaomi_miio.markdown
  source/_integrations/zabbix.markdown
  source/_integrations/zestimate.markdown
  source/_integrations/zha.markdown
  source/_integrations/zhong_hong.markdown
  source/_integrations/zone.markdown
  source/_integrations/zoneminder.markdown
Labels: current

#32763 t-integrations: add glossary reference to config file
  source/_integrations/telegram_broadcast.markdown
  source/_integrations/telegram_polling.markdown
  source/_integrations/telegram_webhooks.markdown
  source/_integrations/tellstick.markdown
  source/_integrations/template.markdown
  source/_integrations/text.mqtt.markdown
  source/_integrations/thermoworks_smoke.markdown
  source/_integrations/thethingsnetwork.markdown
  source/_integrations/thingspeak.markdown
  source/_integrations/thinkingcleaner.markdown
  source/_integrations/thomson.markdown
  source/_integrations/threshold.markdown
  source/_integrations/tikteck.markdown
  source/_integrations/timer.markdown
  source/_integrations/tmb.markdown
  source/_integrations/tod.markdown
  source/_integrations/todoist.markdown
  source/_integrations/tomato.markdown
  source/_integrations/toon.markdown
  source/_integrations/torque.markdown
  source/_integrations/touchline.markdown
  source/_integrations/tplink_lte.markdown
  source/_integrations/tradfri.markdown
  source/_integrations/transport_nsw.markdown
  source/_integrations/travisci.markdown
  source/_integrations/trend.markdown
  source/_integrations/twilio.markdown
  source/_integrations/twilio_call.markdown
  source/_integrations/twilio_sms.markdown
  source/_integrations/twitter.markdown
Labels: current

#29297 Add Viam integration page
  source/_integrations/viam.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#32722 Updated Abode docs to point to jaraco.abode library
  source/_integrations/abode.markdown
Labels: current

#32767 Docs: add glossary ref to configuration.yaml term definition
  source/_docs/authentication/multi-factor-auth.markdown
  source/_docs/authentication/providers.markdown
  source/_docs/automation/editor.markdown
  source/_docs/automation/using_blueprints.markdown
  source/_docs/automation/yaml.markdown
  source/_docs/blueprint/tutorial.markdown
  source/_docs/configuration/packages.markdown
  source/_docs/configuration/secrets.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/configuration/troubleshooting.markdown
  source/_docs/energy/faq.markdown
  source/_docs/quality_scale.markdown
  source/_docs/tools/check_config.markdown
  source/_docs/tools/dev-tools.markdown
Labels: current

#30974 Opower integration support for multiple meters on single account
  source/_integrations/opower.markdown
Labels: next, has-parent, parent-merged

#32770 Add water meter to Youless intergration
  source/_integrations/youless.markdown
Labels: next, has-parent

#32777 Docs: add glossary term reference to config file
  source/_docs/authentication/providers.markdown
  source/_docs/configuration/basic.markdown
  source/_docs/configuration/customizing-devices.markdown
Labels: current

#32781 Remove empty integration type in remember the milk
  source/_integrations/remember_the_milk.markdown
Labels: current

#32780 Revert "Add Viam integration page"
  source/_integrations/viam.markdown
Labels: awaits-parent, next, has-parent

#32788 Configuration: style and typo fixes
  source/_docs/configuration.markdown
Labels: current

#32785 Tile card: add section on reordering features
  source/_dashboards/tile.markdown
Labels: current

#32789 Troubleshooting: restart in safe mode from cmd
  source/_docs/troubleshooting_general.markdown
  source/_includes/common-tasks/commandline.md
Labels: current, has-parent

#32786 Add HomeSeer SmartStick G8 to supported Z-Wave sticks
  source/_docs/z-wave/controllers.markdown
Labels: current

#32783 Revert "Opower integration support for multiple meters on single account"
  source/_integrations/opower.markdown
Labels: next, parent-merged

#32727 u-integrations: restart HA after changing config
  source/_integrations/ubus.markdown
  source/_integrations/ue_smart_radio.markdown
  source/_integrations/uk_transport.markdown
  source/_integrations/unifi_direct.markdown
  source/_integrations/unifiled.markdown
  source/_integrations/universal.markdown
  source/_integrations/upc_connect.markdown
  source/_integrations/usgs_earthquakes_feed.markdown
  source/_integrations/uvc.markdown
Labels: current

#32787 Update freedompro.markdown - Preliminary steps
  source/_integrations/freedompro.markdown
Labels: current

#32792 Fix links from includes
  source/_includes/feedback.html
  source/_includes/related.html
Labels: current

#32779 Added Automation example for the Radio Browser Intigration
  source/_integrations/radio_browser.markdown
Labels: current

#31193 Document new configuration options for air-Q integration
  source/_integrations/airq.markdown
Labels: in-progress, next, has-parent, parent-merged

#32790 File access: tweak procedure on installing terminal and ssh add-on
  source/_includes/common-tasks/commandline.md
  source/_includes/common-tasks/file_access.md
Labels: current

#32771 Allow templates for enabling conditions
  source/_docs/scripts/conditions.markdown
Labels: next, has-parent

#32772 Allow templates for enabling actions
  source/_docs/scripts.markdown
Labels: next, has-parent

#32605 Update Android TV Remote documentation that you can launch any app by its application ID/package name
  source/_integrations/androidtv_remote.markdown
Labels: next, has-parent

#31787 Add Webmin filesystem sensors
  source/_integrations/webmin.markdown
Labels: new-feature, awaits-parent, next, has-parent

#32737 Add select platform to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#30160 Added audio codec option for Jellyfin
  source/_integrations/jellyfin.markdown
Labels: next, has-parent, parent-merged

#32662 Allow templates for enabling automation triggers
  source/_docs/automation/trigger.markdown
Labels: next, has-parent, parent-merged

#32794 Add Reolink PIR entity docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#31566 Added climate platform to microBees integration
  source/_integrations/microbees.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#32689 Update list of supported languages
  source/_integrations/google_translate.markdown
Labels: next, has-parent, parent-merged

#32804 Fix markdown in note
  source/_integrations/thethingsnetwork.markdown
Labels: current

#32335 Add Meter, MeterPlus, and Outdoor Meter to SwitchBot Cloud Docs
  source/_integrations/switchbot_cloud.markdown
Labels: next, has-parent, parent-merged

#32808 Add back ha_integration_type for Remember The Milk
  source/_integrations/remember_the_milk.markdown
Labels: current

#32807 Add fallback for missing integration_type
  source/integrations.json
Labels: current

#32803 Add integration codeowners to sidebar
  source/_includes/asides/component_navigation.html
  source/integrations/index.html
Labels: current

#32809 Fix typo in Tedee doc
  source/_integrations/tedee.markdown
Labels: current

#32793 Add Reolink battery entity docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#31618 Add light platform to Linear
  source/_integrations/linear_garage_door.markdown
Labels: in-progress, next, has-parent, parent-merged

#28140 Add examples of how to use new Mastodon service functionality
  source/_integrations/mastodon.markdown
Labels: next, has-parent, parent-merged

#32806 Blueprint tutorial: Fix YAML example
  source/_docs/blueprint/tutorial.markdown
Labels: current

#32817 2024.5.4
  _config.yml
  source/_posts/2024-05-01-release-20245.markdown
  source/changelogs/core-2024.5.markdown
Labels: in-progress, current, has-parent, needs-rebase

#32829 Update zwave_js.markdown docs to make it more clear
  source/_integrations/zwave_js.markdown
Labels: current

#32823 Remove inaccurate Hydrawise documentation
  source/_integrations/hydrawise.markdown
Labels: current

#32827 Google Generative AI: Add a clarification on the google_generative_ai_conversation.generate_content
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#32832 Update frontier_silicon.markdown
  source/_integrations/frontier_silicon.markdown
Labels: current

#32835 Remove AngellusMortis as code-owner Unifi Protect
  CODEOWNERS
  source/_integrations/unifiprotect.markdown
Labels: in-progress, current, has-parent

#32570 Add information about new IMGW-PIB sensors
  source/_integrations/imgw_pib.markdown
Labels: next, has-parent, parent-merged

#32839 Update Google AI to allow HASS access
  source/_integrations/google_generative_ai_conversation.markdown
Labels: next, has-parent, parent-merged

#32096 Add integration docs for APsystems API
  source/_integrations/apsystems.markdown
Labels: next, has-parent

#32842 uptimerobot: note for people using new dashboard as default
  source/_integrations/uptimerobot.markdown
Labels: current

#32848 Google Generative AI: add pricing details
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#32774 Update example for using trigger.event.data.message due to syntax error
  source/_integrations/system_log.markdown
Labels: current

#32799 SkyConnect: update multiprotocol status faq item
  source/skyconnect/index.html
Labels: current

#32872 Fix duplicated text in SkyConnect FAQ
  source/skyconnect/index.html
Labels: current

#32782 Add data point type option to `knx.telegram` trigger
  source/_integrations/knx.markdown
Labels: awaits-parent, next, has-parent

#32841 Add value_template option to KNX expose
  source/_integrations/knx.markdown
Labels: next, has-parent

#32881 Blog post iOS 2024.5
  source/_posts/2024-05-22-companion-app-for-ios-20245-assist.markdown
  source/images/blog/2024-05-ios-assist/ios-og.jpg
  source/images/blog/2024-05-ios-assist/widgets.png
Labels: blog, current

#30110 Add config flow for LG Netcast
  source/_integrations/lg_netcast.markdown
Labels: in-progress, next, has-parent, parent-merged

#31228 Update docs for `Notifications for Android TV / Fire TV` for changes made to service data for icons and images
  source/_integrations/nfandroidtv.markdown
Labels: next, has-parent, parent-merged

#32884 2024.5 iOS blog post - Add extra request for feedback
  source/_posts/2024-05-22-companion-app-for-ios-20245-assist.markdown
Labels: blog, current

#31435 Add camera recording service to blink
  source/_integrations/blink.markdown
Labels: next, has-parent, parent-merged

#32062 Add service waze_travel_time.get_travel_times
  source/_integrations/waze_travel_time.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#32535 add (and multiply) filters documented (ref PR #109884)
  source/_docs/configuration/templating.markdown
Labels: in-progress, next, has-parent, parent-merged
