Repository home-assistant/home-assistant.io, pull requests merged in 2024-08, with the labels that each got.

#34054 tweak mold indicator wording
  source/_integrations/mold_indicator.markdown
Labels: current

#33865 Add Home Assistant Green on Amazon link to buy box
  source/green/index.html
Labels: current

#34068 Dashboard actions: Fix perform_action key
  source/dashboards/actions.markdown
Labels: in-progress, next, needs-rebase

#34069 Clean up messaging around Yellow distribution
  source/yellow/index.html
Labels: current

#34067 Uploading the Yellow lineup update blog and assets
  source/_posts/2024-08-01-streamlining-the-home-assistant-yellow-lineup.markdown
  source/images/blog/2024-08-yellow-lineup/art.jpg
  source/images/blog/2024-08-yellow-lineup/green-meets-yellow.jpg
Labels: current

#34064 YAML examples: rename 'service' to 'action'
  source/_dashboards/button.markdown
  source/_dashboards/entities.markdown
  source/_dashboards/picture-entity.markdown
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
  source/_includes/installation/container.md
Labels: next, has-parent, parent-merged

#34080 Use new mode values for KNX climate
  source/_integrations/knx.markdown
Labels: next, has-parent

#34056 Update history_stats.markdown to fix minor error
  source/_integrations/history_stats.markdown
Labels: current

#34091 Mealie example template fix
  source/_integrations/mealie.markdown
Labels: in-progress, next, needs-rebase

#34093 Fix minor typo in "Migrating an external data disk to another system" section
  source/_includes/common-tasks/data_disk.md
Labels: current

#33952 Add Anthropic integration
  source/_integrations/anthropic.markdown
Labels: next, has-parent, parent-merged

#34098 add more categories to WattTime integration
  source/_integrations/watttime.markdown
Labels: current

#34111 Add Marantz CINEMA 60 as supported
  source/_integrations/denonavr.markdown
Labels: current

#34102 Improve instructions and requirements for Alexa account linking
  source/_integrations/alexa.smart_home.markdown
Labels: current

#32322 Add elevenlabs integration docs
  source/_integrations/elevenlabs.markdown
Labels: new-integration, in-progress, next, has-parent, parent-merged

#34112 Add steps on viewing available disk space
  source/images/screenshots/storage_view_free-diskspace.png
  source/more-info/free-space.markdown
Labels: current

#34117 Add information about `model_id` to MQTT documentation
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/event.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/image.mqtt.markdown
  source/_integrations/lawn_mower.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/notify.mqtt.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/tag.mqtt.markdown
  source/_integrations/text.mqtt.markdown
  source/_integrations/update.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
  source/_integrations/valve.mqtt.markdown
  source/_integrations/water_heater.mqtt.markdown
Labels: awaits-parent, next, has-parent

#34116 Remove mention of the old library from Onkyo
  source/_integrations/onkyo.markdown
Labels: current

#34125 Terminology: entites: add screenshot
  source/getting-started/concepts-terminology.markdown
  source/images/getting-started/entities.png
Labels: current

#34121 Common tasks: reorder
  source/common-tasks/os.markdown
  source/common-tasks/supervised.markdown
Labels: current

#34115 installing an add-on repository: update
  source/_includes/common-tasks/third-party-addons.md
  source/images/hassio/screenshots/add-ons-community_example.png
  source/images/hassio/screenshots/adding_repositories.png
  source/images/hassio/screenshots/dashboard.png
Labels: current

#34129 Add-ons: language tweaks
  source/_includes/common-tasks/third-party-addons.md
Labels: current

#34113 Cleaning the database: rephrase
  source/more-info/free-space.markdown
Labels: current

#34110 Terminology, add-ons: update description
  source/getting-started/concepts-terminology.markdown
Labels: current

#34106 Docs: add edit icon
  source/_dashboards/sections.markdown
  source/_docs/organizing/areas.markdown
  source/_docs/organizing/labels.markdown
  source/_includes/dashboard/edit_dashboard.md
  source/_integrations/matter.markdown
Labels: current

#34105 Areas: Re-add screenshots
  source/images/organizing/area_assign_devices.png
  source/images/organizing/area_delete.png
Labels: current

#34089 Z-Wave: Reword firmware warnings, add Z-Station as recommended
  source/_docs/z-wave/controllers.markdown
Labels: current

#34119 Add text for KNX updates to release notes
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, needs-rebase, rc

#34134 [Bayesian] Better example, fixes #34120
  source/_integrations/bayesian.markdown
Labels: current

#34138 Correct link in the 2024.8 release notes
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, has-parent, needs-rebase, rc

#34103 Zone integration: update to reflect current SW
  source/_integrations/zone.markdown
  source/getting-started/onboarding.markdown
  source/images/integrations/zone/zone_edit_ui.png
Labels: current

#34142 Update release notes with additional detail on Ollama tools
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, needs-rebase, rc

#34146 Step-by-step on adding presence detection with phone
  source/getting-started/presence-detection.markdown
Labels: current

#34150 presence-detection: Fix link
  source/getting-started/presence-detection.markdown
Labels: current

#34151 Zones: add screenshot showing zones on a map
  source/_integrations/zone.markdown
Labels: current

#34153 Add steps on adding presence detection for other persons
  source/getting-started/presence-detection.markdown
Labels: current

#34157 Add another person to Home Assistant
  source/_docs/authentication.markdown
  source/_integrations/person.markdown
Labels: current

#34154 Small changes to 2024.08 release notes
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, needs-rebase, rc

#34163 Updated manifest.json reference in thirteen-usd-voice-remote
  source/voice_control/thirteen-usd-voice-remote.markdown
Labels: in-progress, current, needs-rebase

#34165 Add automation name example
  source/getting-started/automation.markdown
Labels: next, parent-merged

#34159 Small corrections to the 2024.08 release notes
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, needs-rebase, rc

#34162 Getting started: update Next steps
  source/getting-started/configuration.markdown
Labels: current

#34161 Yellow: remove zero setup, comes with HA preinstalled claim
  source/yellow/index.html
Labels: current

#34164 Presence detection: Add option to use smartwatch
  source/getting-started/presence-detection.markdown
Labels: current

#34170 Warn users about disabling 2FA for Exelon utilities
  source/_integrations/opower.markdown
Labels: current

#34172 Badge: add steps on adding a badge from UI
  source/dashboards/badges.markdown
  source/images/dashboards/badge_add.png
  source/images/dashboards/badge_configure.png
Labels: next, has-parent

#34173 adding card conditionally: also applies to badge
  source/dashboards/cards.markdown
Labels: next, has-parent

#34175 Customize columns: show created and modified
  source/_docs/organizing/tables.markdown
  source/images/organizing/customize_columns.webp
Labels: next, has-parent

#34176 picture cards: add person image support to release notes
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, has-parent, needs-rebase, rc

#34179 Fix mercury_nz release
  source/_integrations/mercury_nz.markdown
Labels: current

#34180 Fix mini_connected release
  source/_integrations/mini_connected.markdown
Labels: current

#34186 Improve Tessie docs
  source/_integrations/tessie.markdown
Labels: current

#34178 Update mastodon.markdown remove related
  source/_integrations/mastodon.markdown
Labels: current

#34083 Add docs for apsystems binary sensors
  source/_integrations/apsystems.markdown
Labels: in-progress, next, has-parent, parent-merged

#34187 S3-BOX: update firmware links
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#34188 M5Stack ATOM Echo: update firmware link
  source/voice_control/thirteen-usd-voice-remote.markdown
Labels: current

#34189 Fix URL in Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: current

#34192 Integrations: update screenshots
  source/images/getting-started/add_workday_integration.png
  source/images/getting-started/integrations.png
  source/images/getting-started/integrations_page_discovered.png
  source/images/getting-started/workday_select_integration.png
  source/images/getting-started/yaml-icon.png
Labels: current

#34193 Rename yaml icon to config file icon. update description
  source/getting-started/concepts-terminology.markdown
  source/images/getting-started/config-file_icon.png
Labels: current

#34198 Fix: update seventeentrack example card
  source/_integrations/seventeentrack.markdown
Labels: current

#34197 Matter device update: add screenshot
  source/_integrations/matter.markdown
  source/images/integrations/matter/matter_ota_message.png
Labels: current

#34196 Explain Reolink password character set limitiations
  source/_integrations/reolink.markdown
Labels: current

#34204 Fix/Adjust WLED documentation
  source/_integrations/wled.markdown
Labels: current

#34094 Improve documentation for IronOS integration
  source/_integrations/iron_os.markdown
Labels: in-progress, current

#34206 Upload of the Works with Home Assistant blog
  source/_posts/2024-08-08-works-with-home-assistant-becomes-part-ohf.markdown
  source/images/blog/2024-08-wwha-update/art.jpg
  source/images/blog/2024-08-wwha-update/wwha-badges.png
  source/images/blog/2024-08-wwha-update/wwha-company-logos.png
Labels: current

#34228 Fix documentation YAML example in androidtv_remote
  source/_integrations/androidtv_remote.markdown
Labels: current

#34214 Add Reolink doorbell white to supported list
  source/_integrations/reolink.markdown
Labels: current

#34229 Fix/adjust service -> action in notification groups
  source/_integrations/group.markdown
Labels: in-progress, current, has-parent, needs-rebase

#34235 Flux: Specify default values for start_time and stop_time
  source/_integrations/flux.markdown
Labels: current

#34236 2024.8.1
  _config.yml
  source/_posts/2024-08-07-release-20248.markdown
  source/changelogs/core-2024.8.markdown
Labels: in-progress, current, has-parent, needs-rebase

#34243 Add minimum firmware version information for Shelly (Gen3) virtual components
  source/_integrations/shelly.markdown
Labels: in-progress, current, has-parent, needs-rebase

#34131 Remove asterisk mailbox docs
  source/_docs/asterisk_mbox.markdown
  source/_redirects
Labels: next, has-parent, parent-merged

#34222 Add details of new sensors to Mastodon
  source/_integrations/mastodon.markdown
Labels: in-progress, next, has-parent, parent-merged

#34241 Add diagnostics platform to Mastodon
  source/_integrations/mastodon.markdown
Labels: next, has-parent, parent-merged

#34209 Update sensor.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: current

#34237 Clarify continuous mode is enabled by default in the Roomba integration
  source/_integrations/roomba.markdown
Labels: current

#34239 Fix typo in Android TV Remote integration YAML example, it's perform-action not perform_action
  source/_integrations/androidtv_remote.markdown
Labels: current

#34244 Update IMAP docs on use of App passwords and removed Microsoft support
  source/_integrations/imap.markdown
Labels: current

#34208 Link to all entities that is support in group
  source/_integrations/group.markdown
Labels: current

#34114 Add unique id to manual alarm
  source/_integrations/manual.markdown
Labels: next, has-parent

#34254 Rename service-calls file to perform-actions to align terminology
  source/_data/glossary.yml
  source/_docs/blueprint/tutorial.markdown
  source/_docs/scripts.markdown
  source/_docs/scripts/perform-actions.markdown
  source/_includes/asides/docs_sitemap.html
  source/_integrations/calendar.markdown
  source/_integrations/conversation.markdown
  source/_integrations/easyenergy.markdown
  source/_integrations/energyzero.markdown
  source/_integrations/google_generative_ai_conversation.markdown
  source/_integrations/motionblinds_ble.markdown
  source/_integrations/openai_conversation.markdown
  source/_integrations/python_script.markdown
  source/_integrations/qbittorrent.markdown
  source/_integrations/rest_command.markdown
  source/_integrations/shell_command.markdown
  source/_integrations/system_bridge.markdown
  source/_integrations/template.markdown
  source/_integrations/tibber.markdown
  source/_integrations/todo.markdown
  source/_integrations/waze_travel_time.markdown
  source/_integrations/weather.markdown
  source/_integrations/workday.markdown
  source/_redirects
Labels: current

#34167 Allow for user application implementations in Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: in-progress, next, has-parent, parent-merged

#34260 Cleanup MQTT legacy notify instruction using mqtt publish
  source/_integrations/mqtt.markdown
  source/images/screenshots/mqtt-notify-action.png
  source/images/screenshots/mqtt-notify.png
Labels: current

#33753 [homematicip_cloud] Add set_home_cooling_mode service
  source/_integrations/homematicip_cloud.markdown
Labels: next, has-parent, parent-merged

#34255 Add action to Swiss public transport
  source/_integrations/swiss_public_transport.markdown
Labels: next, has-parent, parent-merged

#34257 Cleanup mqtt publish action template option documentation
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#34262 Remove deprecated information from Swiss public transport
  source/_integrations/swiss_public_transport.markdown
Labels: in-progress, current, has-parent, needs-rebase

#34263 Assist: update ATOM Echo tutorial
  source/_includes/voice_assistant/install_esp_firmware.md
  source/images/assist/esp32-atom_silence_detection_01.png
  source/voice_control/thirteen-usd-voice-remote.markdown
Labels: current

#34264 Core installation: add step to check for correct python version
  source/_includes/installation/core.md
Labels: current

#34259 S3 box update screenshots and steps
  source/images/assist/s3-box-disable-screen.png
  source/images/assist/wake_word_disable.png
  source/images/assist/wake_word_engine_location.png
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#34265 Raspberri Pi installation: re-add links to HA image
  source/installation/raspberrypi.markdown
Labels: current

#34274 Correct Wake on LAN Button section
  source/_integrations/wake_on_lan.markdown
Labels: current

#34275 Add termref to configuration.yaml
  source/_integrations/bluetooth.markdown
  source/_integrations/config.markdown
  source/_integrations/device_tracker.markdown
  source/_integrations/dhcp.markdown
  source/_integrations/emulated_hue.markdown
  source/_integrations/fan.template.markdown
  source/_integrations/flux.markdown
  source/_integrations/frontend.markdown
  source/_integrations/generic_hygrostat.markdown
  source/_integrations/homeassistant.markdown
  source/_integrations/homeassistant_alerts.markdown
  source/_integrations/http.markdown
  source/_integrations/input_boolean.markdown
  source/_integrations/input_datetime.markdown
  source/_integrations/light.template.markdown
  source/_integrations/logbook.markdown
Labels: current

#34284 integration term def: change link to point to more detailed description
  source/_data/glossary.yml
Labels: current

#34234 Add update platform for AirGradient
  source/_integrations/airgradient.markdown
Labels: awaits-parent, next, has-parent

#34233 Add motion blinds favorite position docs
  source/_integrations/motion_blinds.markdown
Labels: awaits-parent, next, has-parent

#34294 Set quality scale to silver for Russound RIO
  source/_integrations/russound_rio.markdown
Labels: next, has-parent

#34299 Fixing a link on zha.markdown
  source/_integrations/zha.markdown
Labels: current

#34283 Glossary: add term 'custom integration'
  source/_data/glossary.yml
Labels: current

#33946 Add switch to chacon_dio integration
  source/_integrations/chacon_dio.markdown
Labels: awaits-parent, next, has-parent

#33721 Add config flow for platform number in Template
  source/_integrations/template.markdown
Labels: awaits-parent, next, has-parent

#34328 2024.8.2
  _config.yml
  source/_posts/2024-08-07-release-20248.markdown
  source/changelogs/core-2024.8.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33725 Update AquaCell docs to mention Harvey support
  source/_integrations/aquacell.markdown
Labels: awaits-parent, next, has-parent

#34351 Fix generic-x86-64 OS download URL
  source/_includes/installation/operating_system.md
Labels: current

#34333 Fix KNX telegram trigger data
  source/_integrations/knx.markdown
Labels: current

#34360 Add Aranet Radiation to supported devices
  source/_integrations/aranet.markdown
Labels: current

#34305 Rename KNX Climate preset modes according to specification
  source/_integrations/knx.markdown
Labels: next, has-parent, parent-merged

#34312 Document publishing raw data in mqtt command templates and publish action
  source/_docs/configuration/templating.markdown
  source/_integrations/mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#34314 Update badges.markdown
  source/dashboards/badges.markdown
Labels: current

#34304 Mention My integration in Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: current

#34310 Add time to `today_at()` functions in History Stats docs
  source/_integrations/history_stats.markdown
Labels: current

#34311 Add default value for `today_at()` to templating docs
  source/_docs/configuration/templating.markdown
Labels: current

#31192 Add documentation for the fujitsu_hvac integration
  source/_integrations/fujitsu_fglair.markdown
Labels: next, has-parent, parent-merged

#34200 Explain Apsystems entities in tables rather than lists
  source/_integrations/apsystems.markdown
Labels: awaits-parent, next, has-parent

#34003 Add Nice G.O. integration
  source/_integrations/nice_go.markdown
Labels: next, has-parent, parent-merged

#33974 Add ArtSound integration
  source/_integrations/artsound.markdown
Labels: next, has-parent, parent-merged

#34379 Raspberry Pi: rephrase A2 class requirement
  source/installation/raspberrypi.markdown
Labels: current

#34370 Add switch platform to Nice G.O.
  source/_integrations/nice_go.markdown
Labels: next, has-parent, parent-merged

#34373 Add Nice G.O. event platform
  source/_integrations/nice_go.markdown
Labels: next, has-parent, parent-merged

#33053 Add initial documentation for new SMLIGHT SLZB integration
  source/_integrations/smlight.markdown
Labels: new-integration, in-progress, next, has-parent, parent-merged

#34391 Backup: add link to backup procedure for Core and Container
  source/getting-started/configuration.markdown
Labels: current

#34390 Upload blog for HACS 2.0
  source/_posts/2024-08-21-hacs-the-best-way-to-share-community-made-projects.markdown
  source/images/blog/2024-08-hacs2/art.png
  source/images/blog/2024-08-hacs2/downloads.png
  source/images/blog/2024-08-hacs2/frontend.png
  source/images/blog/2024-08-hacs2/updates-repairs.png
Labels: current

#34293 Enable confirm error button in Husqvarna Automower by default
  source/_integrations/husqvarna_automower.markdown
Labels: next, has-parent, parent-merged

#34361 Add Aranet Radon Plus to supported devices
  source/_integrations/aranet.markdown
Labels: next, has-parent

#34395 Update blueprint schema documentation
  source/_docs/blueprint/schema.markdown
Labels: current

#34393 Fix opengraph in HACS blog
  source/_posts/2024-08-21-hacs-the-best-way-to-share-community-made-projects.markdown
Labels: current

#34346 Update tailscale.markdown
  source/_integrations/tailscale.markdown
Labels: current, has-parent

#34341 Allow setup of Mosquito Add-on in MQTT config flow
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, by-code-owner, integration: mqtt

#34398 Update URLs pointing to wrong domain
  source/_posts/2024-08-21-hacs-the-best-way-to-share-community-made-projects.markdown
Labels: current

#32871 Add reference to new DROP Alert product
  source/_integrations/drop_connect.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#34400 HACS blog: Fix typo
  source/_posts/2024-08-21-hacs-the-best-way-to-share-community-made-projects.markdown
Labels: current

#34152 Add `options` support to MQTT sensor
  source/_integrations/sensor.mqtt.markdown
Labels: awaits-parent, next, has-parent

#34431 Remove incorrect configuration from badges.markdown
  source/dashboards/badges.markdown
Labels: current

#34428 Update nws.markdown
  source/_integrations/nws.markdown
Labels: current

#34439 2024.8.3
  _config.yml
  source/_posts/2024-08-07-release-20248.markdown
Labels: in-progress, current, has-parent, needs-rebase

#34440 Fix 2024.8.3 patch release notes
  source/_posts/2024-08-07-release-20248.markdown
  source/changelogs/core-2024.8.markdown
Labels: current

#34335 Clarify when numeric state will update when other entities are used as limits
  source/_docs/automation/trigger.markdown
Labels: current

#34066 Update tellduslive.markdown
  source/_integrations/tellduslive.markdown
Labels: current

#34348 Amcrest: Change `action` back to `service`
  source/_integrations/amcrest.markdown
Labels: next

#34415 Document support for National Grid NY Upstate in Opower
  source/_integrations/opower.markdown
Labels: in-progress, next, has-parent, parent-merged

#34368 Addition of support of the homeassistant.update_entity action
  source/_integrations/chacon_dio.markdown
Labels: next, has-parent, parent-merged

#34355 Prometheus: Add alarm_control_panel metric
  source/_integrations/prometheus.markdown
Labels: next, has-parent, parent-merged

#34342 Add documentation and setup instructions for ista EcoTrend statistics
  source/_integrations/ista_ecotrend.markdown
Labels: next, has-parent, parent-merged

#34330 Adding Finance to SimpleFin Docs
  source/_integrations/simplefin.markdown
Labels: current

#34423 Auto reauth mqtt entry when the broker add-on is re-installed
  source/_integrations/mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#34448 Update Cast splash image
  source/images/cast/splash.png
Labels: current

#34446 Document shelly outbound websocket configuration may be auto configured
  source/_integrations/shelly.markdown
Labels: awaits-parent, next, has-parent

#34402 Clarify Linear Garage Door integration, notify of new integration coming soon
  source/_integrations/linear_garage_door.markdown
Labels: current

#34149 Add Reolink chime play action docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#34457 Clarify inputs in blueprint sections are flattened
  source/_docs/blueprint/schema.markdown
Labels: current
