Repository home-assistant/home-assistant.io, pull requests merged in 2024-06, with the labels that each got.

#33015 Fix intent_script example
  source/_integrations/intent_script.markdown
Labels: current

#33037 Fix link in switchbot.markdown
  source/_integrations/switchbot.markdown
Labels: current

#33009 Add two new options to intent_script
  source/_integrations/intent_script.markdown
Labels: next, has-parent, parent-merged

#33011 Fix link in roborock.markdown
  source/_integrations/roborock.markdown
Labels: current

#33043 Add information about the new sensor supported by Nettigo Air Monitor integration
  source/_integrations/nam.markdown
Labels: next, has-parent, parent-merged

#32193 Add Tag entities
  source/_integrations/tag.markdown
Labels: next, has-parent, parent-merged

#32997 Homeassistant integration: rephrase device class description
  source/_integrations/homeassistant.markdown
Labels: current

#33040 Migrate incomfort integration to config flow
  source/_integrations/incomfort.markdown
Labels: awaits-parent, next, has-parent

#33057 Add firmware note to Airgradient
  source/_integrations/airgradient.markdown
Labels: next, has-parent

#33059 Revert "Add device based MQTT auto discovery"
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/event.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/lawn_mower.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/text.mqtt.markdown
  source/_integrations/update.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
  source/_integrations/valve.mqtt.markdown
  source/_integrations/water_heater.mqtt.markdown
Labels: next, parent-merged

#32590 Add config flow to media extractor
  source/_integrations/media_extractor.markdown
Labels: next, has-parent, parent-merged

#33065 Update raspberrypi.markdown
  source/installation/raspberrypi.markdown
Labels: current

#32668 Add new sensors to V2C
  source/_integrations/v2c.markdown
Labels: in-progress, next, has-parent, parent-merged

#31453 Introduce new max_sub_interval config for integral sensor
  source/_integrations/integration.markdown
Labels: next, has-parent, parent-merged

#33062 Sonos - add additional docs for play_media
  source/_integrations/sonos.markdown
Labels: current

#33060 Add automation trigger enabled templates to 2024.6 release notes
  source/_posts/2024-06-05-release-20246.markdown
Labels: in-progress, has-parent, needs-rebase, rc

#33045 Update Status LED to Doorbell LED
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent

#21643 Azure data explorer
  source/_integrations/azure_data_explorer.markdown
Labels: cla-signed, in-progress, next, has-parent, parent-merged

#33058 Update panasonic_viera.markdown
  source/_integrations/panasonic_viera.markdown
Labels: current

#33073 Add mention of XML support to binary_sensor.rest integration
  source/_integrations/binary_sensor.rest.markdown
Labels: next, has-parent

#32178 Azure DevOps new build sensors
  source/_integrations/azure_devops.markdown
Labels: awaits-parent, next, has-parent

#32996 Documentation for ista EcoTrend integration
  source/_integrations/ista_ecotrend.markdown
Labels: new-integration, awaits-parent, next, has-parent, parent-merged

#31879 Bang & Olufsen add overlay/announce play_media documentation
  source/_integrations/bang_olufsen.markdown
Labels: in-progress, next, has-parent, parent-merged

#33081 Adding discovered KEY_MINUS to samsungtv.markdown
  source/_integrations/samsungtv.markdown
Labels: current

#33087 Add visibility config option for cards and sections
  source/_dashboards/sections.markdown
  source/dashboards/cards.markdown
Labels: next, has-parent, parent-merged

#33079 Views and sections view: update to reflect current software
  source/_dashboards/sections.markdown
  source/dashboards/views.markdown
  source/images/dashboards/dashboard_view_configuration_01.png
Labels: next, has-parent

#33088 Correct fan to switch
  source/_integrations/modbus.markdown
Labels: current

#33091 Add LLM explainer in the release notes 2024.6
  source/_posts/2024-06-05-release-20246.markdown
  source/images/blog/2024-06/llm-based-conversation-agent-config-flow.png
  source/images/blog/2024-06/llm-control-assistant.png
Labels: in-progress, needs-rebase, rc

#33093 Cards: add visibility
  source/dashboards/cards.markdown
Labels: next, has-parent, parent-merged

#33092 Fix broken links in homeassistant.markdown
  source/_integrations/homeassistant.markdown
Labels: current

#33094 Section visibility: add screenshot
  source/_dashboards/sections.markdown
  source/images/dashboards/section-visibility.png
Labels: next, has-parent, parent-merged

#33096 Picture cards: add image from UI
  source/_dashboards/picture-entity.markdown
  source/_dashboards/picture-glance.markdown
  source/_dashboards/picture.markdown
  source/_includes/dashboard/add_picture_to_card.md
Labels: next, has-parent, parent-merged

#33097 Card visibility: fix procedure
  source/dashboards/cards.markdown
  source/images/dashboards/add_card_from_device_page.png
  source/images/dashboards/add_card_from_device_page_02.png
Labels: next, has-parent, parent-merged

#33099 Update discord.markdown
  source/_integrations/discord.markdown
Labels: current

#29777 Remote platform documentation for AndroidTV
  source/_integrations/androidtv.markdown
Labels: next, has-parent, parent-merged

#33103 Replace VS Code by correct name, Studio Code Server
  source/_docs/configuration.markdown
  source/_docs/troubleshooting_general.markdown
Labels: current

#33109 Docs navigation: move dashboards to frontend section
  source/_includes/asides/docs_navigation.html
Labels: current

#33111 Adding SmartHome Australia to the list of Green distributors
  source/green/index.html
Labels: current

#33104 Optimize related include
  plugins/site_pages.rb
  source/_includes/related.html
Labels: current

#32664 Add documentation for Aquacell integration
  source/_integrations/aquacell.markdown
Labels: new-integration, awaits-parent, next, has-parent

#33125 Assist landline tutorial: add related topic
  source/voice_control/worlds-most-private-voice-assistant.markdown
Labels: current

#33110 Cards visibility: not available for nested cards
  source/dashboards/cards.markdown
Labels: current

#33126 Fix AirGradient name
  source/_integrations/airgradient.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33105 Conditional card: refer to visibility tab
  source/_dashboards/conditional.markdown
Labels: current

#33127 OpenAI integration: add related topics
  source/_integrations/openai_conversation.markdown
Labels: current

#33128 Assist pipelines: add termref
  source/voice_control/voice_remote_local_assistant.markdown
Labels: current

#33036 Add support for sensor to SwitchBot Hub2
  source/_integrations/switchbot.markdown
Labels: awaits-parent, next, has-parent

#32101 Weatherflow Icon mappings
  source/_integrations/weatherflow_cloud.markdown
Labels: awaits-parent, in-progress, next, has-parent

#33124 Google Generative AI integration: Add related topics
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#33136 local assistant: tweaks
  source/voice_control/voice_remote_local_assistant.markdown
Labels: current

#33134 Fix link
  source/voice_control/voice_remote_cloud_assistant.markdown
Labels: current

#33137 Expose to Assist: add step
  source/images/assist/assistant-expose-10.png
  source/voice_control/voice_remote_expose_devices.markdown
Labels: current

#33139 S3-Box tutorial: add step
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#33129 Add new AI blog
  source/_posts/2024-06-07-ai-agents-for-the-smart-home.markdown
  source/images/blog/2024-06-ai-agents-for-the-smart-home/01-assist.png
  source/images/blog/2024-06-ai-agents-for-the-smart-home/02-options.png
  source/images/blog/2024-06-ai-agents-for-the-smart-home/03-agents.png
  source/images/blog/2024-06-ai-agents-for-the-smart-home/04-setup.png
  source/images/blog/2024-06-ai-agents-for-the-smart-home/05-testing.png
  source/images/blog/2024-06-ai-agents-for-the-smart-home/06-expose.png
  source/images/blog/2024-06-ai-agents-for-the-smart-home/art.jpg
Labels: current

#33143 Correcting name on the AI Blog post
  source/_posts/2024-06-07-ai-agents-for-the-smart-home.markdown
Labels: current

#33140 Update screenshot and step to reflect current SW
  source/images/assist/wake_word_engine_location.png
  source/voice_control/s3_box_voice_assistant.markdown
Labels: current

#33123 Voice navigation, change title to AI, as it is not limited to OpenAI
  source/_includes/asides/voice_navigation.html
Labels: current

#33138 Update starlingbank.markdown for missing personal account linkage
  source/_integrations/starlingbank.markdown
Labels: current

#33144 2024.6.1
  _config.yml
  source/_posts/2024-06-05-release-20246.markdown
  source/changelogs/core-2024.6.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33071 Add Sleeping sensor docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#32995 Customizing entities: update procedure
  source/_docs/configuration/customizing-devices.markdown
  source/images/docs/configuration/customizing-entity-dialog.png
  source/images/docs/configuration/customizing-entity.png
  source/images/docs/configuration/edit_entity-id_in_automation.png
Labels: current

#33145 Correct wind to windy in weatherflow_cloud docs
  source/_integrations/weatherflow_cloud.markdown
Labels: in-progress, next, needs-rebase

#32565 Add documentation for the base64_decode filter
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#29857 Telegram threads support
  source/_integrations/telegram_bot.markdown
Labels: awaits-parent, in-progress, next, has-parent

#29622 Fix video going out of flow on mobile (creating horizontal scrolling)
  sass/custom/_paulus.scss
Labels: Hacktoberfest, current

#32598 Update jewish_calendar.markdown
  source/_integrations/jewish_calendar.markdown
Labels: awaits-parent, next, has-parent

#30873 Update honeywell docs
  source/_integrations/honeywell.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33153 Update seventeentrack.markdown to correct a wrong description
  source/_integrations/seventeentrack.markdown
Labels: current

#33075 Update Ecovacs documentation
  source/_integrations/ecovacs.markdown
Labels: next, has-parent, parent-merged

#33155 Adjust url for nibe document
  source/_integrations/nibe_heatpump.markdown
Labels: current

#33148 Document new arming_states in manual alarm control panel
  source/_integrations/manual.markdown
Labels: awaits-parent, next, has-parent

#32962 Add config flow to MPD
  source/_integrations/mpd.markdown
Labels: awaits-parent, next, has-parent

#33161 Add XZG firmware discovery to the ZHA integration documentation
  source/_integrations/zha.markdown
Labels: next, has-parent, parent-merged

#33163 Amazon polly codeowner
  source/_integrations/amazon_polly.markdown
Labels: in-progress, next, needs-rebase

#33164 Adjust text for Webmin breaking change in 2024.6 post
  source/_posts/2024-06-05-release-20246.markdown
Labels: current

#30964 Modernize JavaScript on integrations page
  source/integrations/index.html
Labels: current

#33168 Add Reolink Manual Record docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#33112 AI personality, Mario tutorial: update to reflect current SW
  source/images/assist/assistant-openai-mario-02.png
  source/images/assist/assistant-openai-mario-09.png
  source/images/assist/mario_rename.png
  source/voice_control/assist_create_open_ai_personality.markdown
Labels: current

#32965 Buttons: add more examples
  source/_dashboards/button.markdown
  source/images/dashboards/buttons_on_vertical_stack_card.png
Labels: current

#32791 Add Docs for template locks' code_format_template
  source/_integrations/lock.template.markdown
Labels: awaits-parent, next, has-parent

#33183 Expand the description of intent_script
  source/_integrations/intent_script.markdown
Labels: current

#33181 Add OSO Energy temperature sensor documentation
  source/_integrations/osoenergy.markdown
Labels: awaits-parent, next, has-parent

#32743 add price service to Tibber
  source/_integrations/tibber.markdown
Labels: awaits-parent, next, has-parent

#28869 Update and improve introduction in zha.markdown
  source/_integrations/zha.markdown
Labels: current, smash

#33190 Add Air Purifier ProH / ProH EU
  source/_integrations/xiaomi_miio.markdown
Labels: awaits-parent, in-progress, next, has-parent

#33200 2024.6.2
  _config.yml
  source/_posts/2024-06-05-release-20246.markdown
  source/changelogs/core-2024.6.markdown
Labels: in-progress, current, has-parent, needs-rebase

#33233 Recommend VirtIO SCSI as disk controller
  source/_includes/installation/operating_system.md
Labels: current, installation

#33192 Blog posts for roadmap 2024 H1!
  source/_posts/2024-06-12-roadmap-2024h1.markdown
  source/_posts/2024-06-12-roadmap-introduction.markdown
  source/images/blog/2024-06-roadmap-2024h1/banner.png
  source/images/blog/2024-06-roadmap-2024h1/ha-roadmap-2024h1.png
  source/images/blog/2024-06-roadmap-introduction/art.jpg
Labels: current

#33238 Fix broken links and rename roadmap to "Midyear 2024"
  source/_posts/2024-06-12-roadmap-2024h1.markdown
  source/_posts/2024-06-12-roadmap-introduction.markdown
  source/images/blog/2024-06-roadmap-2024h1/banner.png
Labels: current

#33236 Update azure_data_explorer.markdown
  source/_integrations/azure_data_explorer.markdown
Labels: current

#33239 Fix date formatting
  source/_posts/2024-05-08-zwave-is-not-dead.markdown
  source/_posts/2024-05-09-music-assistant-2.markdown
  source/_posts/2024-06-07-ai-agents-for-the-smart-home.markdown
Labels: current

#33216 Remove steam temp sensor for linea mini
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent

#33241 Improve Generic x86-64 Installation Documentation
  source/_includes/installation/operating_system.md
Labels: current

#33248 Fix opengraph image in roadmap blog
  source/_posts/2024-06-12-roadmap-introduction.markdown
Labels: current

#33202 Glossary: rename SkyConnect to Connect ZBT-1
  source/_data/glossary.yml
Labels: current

#33203 Hardware integration: rename SkyConnect to Connect ZBT-1
  source/_integrations/homeassistant_hardware.markdown
Labels: current

#33204 Skyconnect integration rename skyconnect
  source/_integrations/homeassistant_sky_connect.markdown
Labels: current

#33205 HomeKit integration: rename SkyConnect to Connect ZBT-1
  source/_integrations/homekit_controller.markdown
Labels: current

#33206 OTBR integration: rename SkyConnect to Connect ZBT-1
  source/_integrations/otbr.markdown
Labels: current

#33207 Thread integration: rename SkyConnect to Connect ZBT-1
  source/_integrations/thread.markdown
Labels: current

#33208 Docs navigation: rename SkyConnect to Connect ZBT-1
  source/_includes/asides/docs_navigation.html
Labels: current

#33209 Add redirect: rename SkyConnect to Connect ZBT-1
  source/_integrations/zha.markdown
  source/_redirects
Labels: in-progress, current, needs-rebase

#33210 Backups: rename SkyConnect to Connect ZBT-1
  source/_includes/common-tasks/backups.md
Labels: current

#33182 Rebrand SkyConnect landing page to Connect ZBT-1
  source/_posts/2023-02-08-state-of-matter-and-thread.markdown
  source/_redirects
  source/connectzbt1/index.html
  source/images/connectzbt1/connectzbt1-cover.jpg
  source/images/connectzbt1/connectzbt1_horizontal.png
  source/images/connectzbt1/connectzbt1_isometric.png
  source/images/connectzbt1/connectzbt1_square.jpg
  source/images/skyconnect/skyconnect-cover.png
  source/images/skyconnect/skyconnect_horizontal.png
  source/images/skyconnect/skyconnect_isometric.png
  source/images/skyconnect/skyconnect_square.jpg
Labels: current

#33251 Add blog on Home Assistant Connect ZBT-1
  source/_posts/2024-06-13-zbt1-annoucement.markdown
  source/images/blog/2024-06-ZBT1/art.jpg
  source/images/blog/2024-06-ZBT1/zbt1-packaging.jpg
Labels: current

#33270 Remove set default doorbell text service from unifiprotect
  source/_integrations/unifiprotect.markdown
Labels: next, has-parent

#33269 Change use of words in Workday
  source/_integrations/workday.markdown
Labels: current

#33272 Update ecobee.markdown
  source/_integrations/ecobee.markdown
Labels: current

#33275 Add work area sensor to Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: awaits-parent, next, has-parent

#33281 Add doc about deleting binary sensor via HTTP API
  source/_integrations/http.markdown
Labels: current

#33284 Clean up outdated/old school examples
  Rakefile
  _config.yml
  package.json
  source/_docs/configuration.markdown
  source/_docs/configuration/splitting_configuration.markdown
  source/_docs/frontend.markdown
  source/_examples/configuration_yaml_by_DrJohnT.markdown
  source/_examples/configuration_yaml_by_alok_saboo.markdown
  source/_examples/configuration_yaml_by_aneisch.markdown
  source/_examples/configuration_yaml_by_apocrathia.markdown
  source/_examples/configuration_yaml_by_carlo_costanzo.markdown
  source/_examples/configuration_yaml_by_cy1701.markdown
  source/_examples/configuration_yaml_by_dannytsang.markdown
  source/_examples/configuration_yaml_by_geekofweek.markdown
  source/_examples/configuration_yaml_by_jimpower.markdown
  source/_examples/configuration_yaml_by_jonathan_adams.markdown
  source/_examples/configuration_yaml_by_klaasnicolaas.markdown
  source/_examples/configuration_yaml_by_mcaminiti.markdown
  source/_examples/configuration_yaml_by_ntalekt.markdown
  source/_examples/configuration_yaml_by_omerome83.markdown
  source/_examples/configuration_yaml_by_shortbloke.markdown
  source/_examples/configuration_yaml_by_skalavala.markdown
  source/_examples/configuration_yaml_by_tinkerer.markdown
  source/_examples/configuration_yaml_by_ubhits.markdown
  source/_examples/google_maps_card.markdown
  source/_includes/site/header.html
  source/_posts/2016-02-20-community-highlights.markdown
  source/_redirects
  source/examples/index.markdown
Labels: current

#33285 2024.6.3
  _config.yml
  source/_posts/2024-06-05-release-20246.markdown
  source/changelogs/core-2024.6.markdown
Labels: in-progress, current, has-parent, needs-rebase

#32314 Documentation for device trackers in tplink_omada
  source/_integrations/tplink_omada.markdown
Labels: next, has-parent, parent-merged

#33288 Remove non existing name suggestion from file documentation
  source/_integrations/file.markdown
Labels: current, integration: file

#33294 Update thethingsnetwork.markdown
  source/_integrations/thethingsnetwork.markdown
Labels: current

#33082 Add docs for max output option for apsystems integration
  source/_integrations/apsystems.markdown
Labels: next, has-parent, parent-merged

#33305 Fix mosquitto_pub tool syntax in mqtt examples
  source/_integrations/mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: current

#33308 Remove Chipolo One Spot from iBeacon compatibility list
  source/_integrations/ibeacon.markdown
Labels: in-progress, current, needs-rebase

#33299 Remove information about the switch entity for Shelly Gas Valve
  source/_integrations/shelly.markdown
Labels: next, has-parent, parent-merged

#33298 Multiprotocol: change link to point to Thread support
  source/_integrations/homekit_controller.markdown
Labels: current

#33306 Add explicit setup step for opening HTTP/HTTPS port on reolink devices
  source/_integrations/reolink.markdown
Labels: current

#31989 Migration of La Marzocco to lmcloud v1.1
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent

#32868 Update solarlog.markdown to reflect change in library
  source/_integrations/solarlog.markdown
Labels: awaits-parent, next, has-parent

#33302 Add Tidal play_media documentation to Bang & Olufsen
  source/_integrations/bang_olufsen.markdown
Labels: awaits-parent, next, has-parent

#33317 Reporting issues: add to TOC, add related links
  source/_includes/asides/help_navigation.html
  source/help/reporting_issues.markdown
Labels: current

#33313 Add note about version info
  source/_includes/common-tasks/specific_version.md
  source/common-tasks/os.markdown
  source/common-tasks/supervised.markdown
Labels: current

#28895 Update ZHA section about Zigbee OTA
  source/_integrations/zha.markdown
Labels: in-progress, current, needs-rebase

#33307 Add button platform to Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: next, has-parent, parent-merged

#32152 DNS IP custom ports for IPv4 #113993
  source/_integrations/dnsip.markdown
Labels: next, has-parent, parent-merged

#33326 Update tessie.markdown - new Tesla fleet API
  source/_integrations/tessie.markdown
Labels: current

#33312 Changes to SMTP notifier documentation
  source/_integrations/smtp.markdown
Labels: current

#33031 Add config flow to One-Time Password (OTP) integration
  source/_integrations/otp.markdown
Labels: awaits-parent, next, has-parent

#32613 Add Refoss sensor platform
  source/_integrations/refoss.markdown
Labels: awaits-parent, in-progress, next, has-parent

#33187 SwitchBot Lock Pro is supported now
  source/_integrations/switchbot.markdown
Labels: in-progress, next, has-parent

#33322 Update Yale Access Bluetooth setup steps for Android
  source/_integrations/yalexs_ble.markdown
Labels: current, smash

#33331 Support battery powered Reolink cameras
  source/_integrations/reolink.markdown
Labels: current, smash

#33339 Change of location for mailing list
  source/_integrations/environment_canada.markdown
Labels: current

#33335 Move steps on locating config directory into separate topic
  source/_docs/configuration.markdown
Labels: current, smash

#33343 Docker compose: remove version
  source/_includes/installation/container.md
  source/_includes/installation/container/compose.md
Labels: current

#33264 Add Mealie documentation
  source/_integrations/mealie.markdown
Labels: next, has-parent, parent-merged

#33332 Add event platform to Nanoleaf
  source/_integrations/nanoleaf.markdown
Labels: awaits-parent, next, has-parent

#33320 OpenWeatherMap remove obsolete forecast sensors
  source/_integrations/openweathermap.markdown
Labels: awaits-parent, in-progress, next, has-parent

#32294 Add cod.m zigbee coordinator to zha docs
  source/_integrations/zha.markdown
Labels: next, has-parent, parent-merged

#33348 OpenWeatherMap: add related link to custom polling
  source/_integrations/openweathermap.markdown
Labels: current

#33346 Icons: add links to related topics
  source/_docs/frontend/icons.markdown
Labels: current

#33316 Add backflush sensor to lamarzocco
  source/_integrations/lamarzocco.markdown
Labels: next, has-parent, parent-merged

#33344 Add number platform to Matter
  source/_integrations/matter.markdown
Labels: awaits-parent, in-progress, next, has-parent

#29316 Document "Zigbee Groups" in ZHA integration
  source/_integrations/zha.markdown
Labels: Hacktoberfest, current, smash

#33314 Add documentation for new sensor (self-consumption)
  source/_integrations/solarlog.markdown
Labels: awaits-parent, in-progress, next, has-parent

#32602 Improve Android TV Remote docs
  source/_integrations/androidtv_remote.markdown
Labels: next, has-parent
