Repository home-assistant/home-assistant.io, pull requests merged in 2025-08, with the labels that each got.

#40226 Add note to 2025.8 release notes for new KNX group monitor
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, has-parent, needs-rebase, rc

#40231 Add automation example to Miele page
  source/_integrations/miele.markdown
Labels: in-progress, next, has-parent

#40252 Update release blog post related to airOS
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, needs-rebase, rc

#40259 Add jitter sensor to Ping integration
  source/_integrations/ping.markdown
Labels: next, has-parent, parent-merged

#40166 Add RM4C pro
  source/_integrations/broadlink.markdown
Labels: current

#40268 Update Ecovacs breaking change text for 2025.08
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, has-parent, rc

#39983 Update Telegram bot events
  source/_integrations/telegram_bot.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40267 Remove hidden voice-pe section
  source/voice-pe/index.html
  source/voice-pe/styles.css
Labels: current

#40272 Add Ring to the newly bronze integrations for 2025.8
  source/_posts/2025-08-06-release-20258.markdown
Labels: has-parent, rc

#40269 Update template section in RC notes
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, needs-rebase, rc

#40260 Reset cutting blade usage time in Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40274 Remove airOS wireless_mode sensor
  source/_integrations/airos.markdown
Labels: next, has-parent

#40276 Remove Mastodon deprecated note
  source/_integrations/mastodon.markdown
Labels: in-progress, current, needs-rebase

#40282 Fixed minor typo
  source/_integrations/input_datetime.markdown
Labels: current

#40275 Update command_line.markdown : replace find by grep
  source/_integrations/command_line.markdown
Labels: current

#40283 Update gree.markdown
  source/_integrations/gree.markdown
Labels: current

#40288 Update duplicate_os_installation.md
  source/more-info/unhealthy/duplicate_os_installation.md
Labels: current

#40289 Improve airOS documentation
  source/_integrations/airos.markdown
Labels: in-progress, next, parent-merged

#40299 Reduce Reolink fimware polling from 12h to 24h docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#40211 Update Opower for PG&E
  source/_integrations/opower.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40306 Changes to AI section of the 2025.8 release notes
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, needs-rebase, rc

#40307 Fix Ecovacs breaking change section in 2025.8
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, needs-rebase, rc

#40292 Replace link to avaliable standalone USB SD adapter
  source/installation/raspberrypi.markdown
Labels: current

#40313 Rename Discovergy to inexogy in release notes
  source/_posts/2025-08-06-release-20258.markdown
Labels: current

#40305 Terminology and compound modifier corrections
  source/_integrations/google_mail.markdown
Labels: current

#40314 Add support for Inkbird IAM-T2
  source/_integrations/inkbird.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40327 Update awair.markdown to include removal instructions
  source/_integrations/awair.markdown
Labels: current

#40316 Add dew point to Awair documentation
  source/_integrations/awair.markdown
Labels: in-progress, current, has-parent, needs-rebase

#40132 Document unsupported reason 'os_version'
  source/more-info/unsupported/os_version.markdown
Labels: awaits-parent, in-progress, current, has-parent

#40322 Document `layout: auto` for "energy-sankey" card
  source/_dashboards/energy.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40341 Add reported device to airOS
  source/_integrations/airos.markdown
Labels: current

#40329 Mention support for Southern Maryland Electric Cooperative (SMECO) in Opower
  source/_integrations/opower.markdown
Labels: current

#40291 Add ToGrill documentation
  source/_integrations/togrill.markdown
Labels: new-integration, awaits-parent, in-progress, next, has-parent, parent-merged

#40333 Added instructions to remove a badge
  source/dashboards/badges.markdown
  source/images/dashboards/edit_badge.png
  source/images/dashboards/edit_badge_menu.png
Labels: current

#40335 Added information if someone wants to change the weather location
  source/_integrations/openweathermap.markdown
Labels: current

#40334 Replaced Optional with Required in Climate Integration
  source/_integrations/climate.markdown
Labels: current

#40331 Added statement for no JS support in HTML block
  source/_dashboards/markdown.markdown
Labels: current

#40342 Clarify how and when to enter applicaion credentials in Miele integration
  source/_integrations/miele.markdown
Labels: current

#40242 Add binary_sensor to UISP airOS
  source/_integrations/airos.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39863 Add event platform to Husqvarna Automower
  source/_integrations/husqvarna_automower.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40353 Added link to Scene integration
  source/_docs/scene.markdown
Labels: current

#40355 Fix documentation turning on sauna Huum
  source/_integrations/huum.markdown
Labels: current

#40358 Allow stale action to write actions
  .github/workflows/stale.yml
Labels: in-progress, current, needs-rebase

#40347 Mention Mercury NZ Limited isn't working anymore in Opower
  source/_integrations/mercury_nz.markdown
  source/_integrations/opower.markdown
Labels: current

#40332 Removed YAML setup for Telegram bot in Telegram integration
  source/_integrations/telegram.markdown
Labels: current

#40315 update alexa_devices docs for new 2025.8 actoins
  source/_integrations/alexa_devices.markdown
Labels: current

#40366 Update solarlog documentation for new sensors
  source/_integrations/solarlog.markdown
Labels: in-progress, next, has-parent, needs-rebase, parent-merged

#40365 Add troubleshooting section for Volvo integration
  source/_integrations/volvo.markdown
Labels: current

#39876 Add media browsing to Russound RIO
  source/_integrations/russound_rio.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#40379 Update list of known devices
  source/_integrations/airos.markdown
Labels: current

#40387 add valve entity
  source/_integrations/tuya.markdown
Labels: next, has-parent

#40388 Z-Wave: fix link to installation instructions
  source/_integrations/zwave_js.markdown
Labels: current

#40375 Update intent_script.markdown to clarify use with custom sentences defined in yaml
  source/_integrations/intent_script.markdown
Labels: current

#39568 Update Snapcast to remove references to old join/unjoin actions
  source/_integrations/snapcast.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40397 Generic camera: replace dead link by YAML example
  source/_integrations/generic.markdown
Labels: current

#40398 Revert "Generic camera: replace dead link by YAML example"
  source/_integrations/generic.markdown
Labels: in-progress, current, needs-rebase

#40396 Document `not` and `location` conditions.
  source/_dashboards/conditional.markdown
Labels: next, has-parent

#40203 Add party-related entities to Habitica integration
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38465 Add Sleep as Android integration
  source/_integrations/sleep_as_android.markdown
Labels: new-integration, next, has-parent, parent-merged

#40412 Z-Wave reset adapter: add steps
  source/_integrations/zwave_js.markdown
Labels: current

#40423 Fix distributor wording and OpenGraph
  source/_data/products.yml
  source/images/connect/zwa-2/og.jpeg
Labels: current

#40424 Fix link I forgot to update
  source/connect/zwa-2/index.html
Labels: current

#40425 Disable livestream card temporarily
  source/_includes/custom/news.html
Labels: current

#40421 Update debug logging documentation
  source/_docs/configuration/troubleshooting.markdown
  source/images/docs/configuration/enable-debug-logging.png
Labels: current

#40429 Connect ZWA-2: fix link to documentation
  source/_data/product/connect/zwa-2/faq.yml
Labels: current

#40431 Z-Wave adapters: add Connect ZWA-2 to list of supported adapters
  source/_docs/z-wave/controllers.markdown
Labels: current

#40435 Fix using select all on mobile causing redirect
  sass/homeassistant/_overrides.scss
Labels: current

#40377 Extend UnitOfReactivePower with 'mvar'
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#40445 Add minimum height to prevent overlap
  sass/homeassistant/pages/connect/zwa-2/components/_long-range.scss
  source/stylesheets/homeassistant/pages/connect/zwa-2/index.css
Labels: current

#40446 docs(started): replace a dot with a comma
  source/getting-started/onboarding_dashboard.markdown
Labels: current

#40438 Z-Wave adding device: add steps
  source/_integrations/zwave_js.markdown
Labels: current

#40452 Add enphase envoy collar and combiner descriptions
  source/_integrations/enphase_envoy.markdown
  source/images/integrations/enphase_envoy/enphase_envoy_collar_and_ccc_data.png
Labels: next, has-parent, parent-merged

#40457 Remove "new product" message
  source/_data/products.yml
Labels: current

#40459 Update FAQ wording
  source/_data/product/connect/zwa-2/faq.yml
Labels: current

#40183 Update the api key permissions requirements in immich
  source/_integrations/immich.markdown
Labels: current

#40455 Add binary sensor to 1-Wire DS2405
  source/_integrations/onewire.markdown
Labels: next, has-parent, parent-merged

#40467 Add additional sensors for airOS
  source/_integrations/airos.markdown
Labels: in-progress, next, has-parent, parent-merged

#40273 Add binary sensor platform to qbus integration
  source/_integrations/qbus.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40453 Add Sonos speech enhancement select
  source/_integrations/sonos.markdown
Labels: next, has-parent, parent-merged

#40507 Z-Wave migration: hide device-specific prereqs
  source/_integrations/zwave_js.markdown
Labels: current

#40510 Updated the list of models supported by YoLink integration
  source/_integrations/yolink.markdown
Labels: next, has-parent, parent-merged

#40511 Voice: fix typo
  source/voice_control/voice_remote_cloud_assistant.markdown
  source/voice_control/voice_remote_local_assistant.markdown
Labels: current

#40473 Update todo-list.markdown
  source/_dashboards/todo-list.markdown
Labels: next, has-parent

#40403 Add fan-oscillate dashboard feature documentation
  source/dashboards/features.markdown
  source/images/dashboards/features/fan_oscillate.png
Labels: awaits-parent, next, has-parent

#40461 Add history chart card feature docs
  source/dashboards/features.markdown
  source/images/dashboards/features/history-chart-line.png
  source/images/dashboards/features/history-chart-timeline.png
Labels: awaits-parent, next, has-parent, parent-merged

#40518 Card clock no background docs
  source/_dashboards/clock.markdown
Labels: in-progress, next, has-parent, parent-merged

#40526 Home Assistant Cloud: add links to documentation
  source/_integrations/cloud.markdown
Labels: current

#40545 Add WWHA label to AirGradient
  source/_integrations/airgradient.markdown
Labels: current

#40550 Fix links in Squeezebox docs which are too long and cause incorrect formatting
  source/_integrations/squeezebox.markdown
Labels: current

#40551 2025.8.3
  _config.yml
  source/_posts/2025-08-06-release-20258.markdown
Labels: in-progress, current, has-parent, needs-rebase

#40546 Change scrolling bug fix implementation
  sass/homeassistant/_overrides.scss
Labels: current

#40537 Update ZWA-2 distributors
  source/_data/products.yml
Labels: current

#40553 Grammar fix in 'Primary and Accent color' section on Frontend page
  source/_integrations/frontend.markdown
Labels: current

#40570 2025-08-06-release-20258.markdown: Fix 2025.8.3 section
  source/_posts/2025-08-06-release-20258.markdown
Labels: current

#40555 Fix 2023 logo not updated
  source/help/trivia.markdown
Labels: current

#40567 List ZWA-2 again under recommended 800 series controllers
  source/_docs/z-wave/controllers.markdown
Labels: current

#40549 squeezebox.markdown: Shorten some link text
  source/_integrations/squeezebox.markdown
Labels: current

#40533 No URL available: replace term Remote UI
  source/more-info/no-url-available.markdown
Labels: current

#40531 remote access: replace term remote UI to be consistent
  source/_docs/configuration/remote.markdown
Labels: current

#40521 STT integration: add related topics …
  source/_integrations/stt.markdown
Labels: current

#40587 solar_only to pure_solar.
  source/_integrations/peblar.markdown
Labels: current

#40349 docs: add port control section to UniFi integration documentation
  source/_integrations/unifi.markdown
Labels: in-progress, next, has-parent

#40523 Add update platform to template integration
  source/_integrations/template.markdown
Labels: next, has-parent

#35705 Bayesian Config Flow
  source/_integrations/bayesian.markdown
Labels: next, has-parent, parent-merged

#40606 Add Reolink chime silent time docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#40449 Add binary sensors to Volvo integration
  source/_integrations/volvo.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40370 Add MQTT subentry support for alarm control panel
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40624 KNX: Support external scene activation recording
  source/_integrations/knx.markdown
Labels: next, has-parent, parent-merged

#40068 Re-add `aladdin_connect` integration documentation
  source/_integrations/aladdin_connect.markdown
  source/_redirects
Labels: next, has-parent, parent-merged

#40641 Add rage sensors to Habitca
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#40649 Rename manufacturer AVM to FRITZ! in FRITZ!Box Call Monitor integration
  source/_integrations/fritzbox_callmonitor.markdown
Labels: next, has-parent, parent-merged

#40647 Rename manufacturer AVM to FRITZ! in Fritz!Box Tools integration
  source/_integrations/fritz.markdown
Labels: in-progress, next, has-parent, parent-merged

#40648 Rename manufacturer AVM to FRITZ! in FRITZ! Smart Home
  source/_integrations/fritzbox.markdown
Labels: next, has-parent, parent-merged

#40651 Add mention of the additional minimum/maximum temperatures
  source/_integrations/togrill.markdown
Labels: next, has-parent, parent-merged

#40638 Clarification on vehicle sleep added
  source/_integrations/tesla_fleet.markdown
Labels: current

#40655 Remove duplicated slash in URL in Fritz!Box tools
  source/_integrations/fritz.markdown
Labels: next

#40658 Add Reolink Duo 3V PoE to tested models
  source/_integrations/reolink.markdown
Labels: current

#40660 Add `kVA` unit to apparent_power in number and sensor integration
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged
