Repository home-assistant/home-assistant.io, pull requests merged in 2025-03, with the labels that each got.

#37759 Document known limitations for Opower
  source/_integrations/opower.markdown
Labels: current

#37705 Add create_rewards action to Habitica
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37391 Introduce demo valve
  source/_integrations/demo.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#37700 Update Wallbox integration docs with solar charging
  source/_integrations/wallbox.markdown
Labels: next, has-parent, parent-merged

#37707 Add update_habit action to Habitica
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37773 Add FrankEver virtual integration docs
  source/_integrations/frankever.markdown
Labels: next, has-parent, parent-merged

#37772 Add LinkedGo virtual integration docs
  source/_integrations/linkedgo.markdown
Labels: next, has-parent, parent-merged

#37680 Update pyLoad configuration parameters
  source/_integrations/pyload.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36926 Add model_id to device filters
  source/_docs/blueprint/selectors.markdown
Labels: awaits-parent, next, has-parent

#37319 Reference mysleep$aver Switch in Advantage Air
  source/_integrations/advantage_air.markdown
Labels: awaits-parent, next, has-parent

#37484 Update balboa docs to include fault event entity
  source/_integrations/balboa.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37781 Document HEOS clear playlist behavior
  source/_integrations/heos.markdown
Labels: current

#37777 Add charging binary_sensor documentation
  source/_integrations/roborock.markdown
Labels: in-progress, next, has-parent, parent-merged

#37785 Add Support for 8 Aux Outputs For Ness Alarm
  source/_integrations/ness_alarm.markdown
Labels: next, has-parent, parent-merged

#37791 Add Apollo Automation documentation
  source/_integrations/apollo_automation.markdown
Labels: next, has-parent, parent-merged

#37797 Fix wrong statement on HERE paid plans
  source/_integrations/here_travel_time.markdown
Labels: current

#37776 Add create_habit action to Habitica
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37342 Add water heater and automation guide
  source/_integrations/lg_thinq.markdown
Labels: current, has-parent, parent-merged

#37715 Updated the Weheat data rate documentation
  source/_integrations/weheat.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37810 Remove beta flag from Matter integration
  source/_docs/energy/water.markdown
  source/_integrations/matter.markdown
Labels: next, has-parent

#37811 Music Assistant big update blog
  source/_posts/2025-03-05-music-assistants-next-big-hit.markdown
  source/images/blog/2025-03-music-assistant/art.jpg
  source/images/blog/2025-03-music-assistant/audio_path.png
  source/images/blog/2025-03-music-assistant/audiobooks.png
  source/images/blog/2025-03-music-assistant/continue.png
  source/images/blog/2025-03-music-assistant/eq.png
  source/images/blog/2025-03-music-assistant/spotify_connect.jpg
  source/images/blog/2025-03-music-assistant/voice_ma.jpg
Labels: current

#37814 Revert roborock scene documentation
  source/_integrations/roborock.markdown
Labels: next, has-parent

#37813 Add view header
  source/_dashboards/sections.markdown
  source/images/dashboards/sections_view_header_edit.png
  source/images/dashboards/sections_view_header_editor.png
Labels: next, has-parent, parent-merged

#37780 Update SmartThings documentation
  source/_integrations/smartthings.markdown
Labels: in-progress, next, needs-rebase

#37818 Replace Ecobee with Matter on featured integrations
  source/_integrations/ecobee.markdown
  source/_integrations/matter.markdown
Labels: in-progress, next, needs-rebase

#37815 SmartThings: style tweaks
  source/_integrations/smartthings.markdown
Labels: in-progress, next, needs-rebase

#37812 [islamic_prayer_times] Typofix Latatude -> Latitude
  source/_integrations/islamic_prayer_times.markdown
Labels: current

#37820 Fix note on inline features
  source/_posts/2025-03-05-release-20253.markdown
Labels: in-progress, needs-rebase, rc

#37819 [Steam Online] Update Instructions to find Steam ID
  source/_integrations/steam_online.markdown
Labels: current

#37824 Provide valid values in contour examples
  source/_integrations/microsoft.markdown
Labels: current

#37828 Glossary term service: remove link
  source/_data/glossary.yml
Labels: current

#37809 Document Enphase Envoy today energy not resetting to zero as known issue.
  source/_integrations/enphase_envoy.markdown
  source/images/integrations/enphase_envoy/enphase_envoy_production_non_zero_reset.png
  source/images/integrations/enphase_envoy/enphase_envoy_production_non_zero_reset_step_change.png
Labels: current

#37832 Tile card: update screenshot to reflect current software
  source/_dashboards/tile.markdown
  source/images/dashboards/tile_card.png
  source/images/dashboards/tile_card_tap_action.webp
Labels: current

#37831 Add IronOS v2.23 features to IronOS integration
  source/_integrations/iron_os.markdown
Labels: next, has-parent, parent-merged

#37833 Features: add steps on customizing features on a card
  source/dashboards/features.markdown
  source/images/dashboards/features/tile-card-feature-position.png
Labels: current

#37836 Add card: customize features, remove steps from tile card page
  source/_dashboards/tile.markdown
  source/_includes/dashboard/edit_dashboard.md
  source/dashboards/cards.markdown
Labels: current

#37837 Create sections view: add substeps
  source/_dashboards/sections.markdown
Labels: current

#37843 Minor fix to SmartThings sentence on blog post
  source/_posts/2025-03-05-release-20253.markdown
Labels: current

#37756 Homee: add select platform
  source/_integrations/homee.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37848 Update dashboard header footer: fixed link to dashboard/statistic
  source/dashboards/header-footer.markdown
Labels: current

#37844 Removes no-NO from the language picker + a-z sorting
  source/voice_control/index.markdown
Labels: current

#37817 Add documentation for Roborock buttons for routines
  source/_integrations/roborock.markdown
Labels: next, has-parent, parent-merged

#37861 2025.3.1
  _config.yml
  source/_posts/2025-03-05-release-20253.markdown
  source/changelogs/core-2025.3.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37856 Document how MQTT reports entity state updates
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#37858 Improve referrals to the device class documentation for MQTT entity platforms
  source/_integrations/cover.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/valve.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#37864 Add template function: shuffle
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#37801 Add `update_todo` action to Habitica
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#37800 Fix trigger example with hidden template
  source/_docs/automation/trigger.markdown
Labels: current

#37872 Add template function: typeof
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#37869 Add create_todo action to Habitica integration
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#37879 Add template function: flatten
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#37878 Add known WebDAV limitations
  source/_integrations/webdav.markdown
Labels: current

#37882 Add Ogemray virtual integration docs
  source/_integrations/ogemray.markdown
Labels: next, has-parent, parent-merged

#37888 Add 900 RPM option to washer spin speed options at Home Connect
  source/_integrations/home_connect.markdown
Labels: in-progress, current, has-parent

#37884 Add template functions: md5, sha1, sha256, sha512
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#37893 Add ITH-13-B and ITH-21-B models to inkbird
  source/_integrations/inkbird.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37000 Added documentation for igloohome lock/unlocking feature
  source/_integrations/igloohome.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37885 Update list of supported Govee lights
  source/_integrations/govee_light_local.markdown
Labels: in-progress, next, has-parent, parent-merged

#37803 Update climate automation guide to LG ThinQ.
  source/_integrations/lg_thinq.markdown
Labels: current

#37696 Clarify requirement for Yale Conexis L1
  source/_integrations/yalexs_ble.markdown
Labels: current

#37890 Add information about BH1750 to NAM documentation
  source/_integrations/nam.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37775 Anthropic conversation extended thinking support
  source/_integrations/anthropic.markdown
Labels: awaits-parent, next, has-parent

#37889 Added limitation to the documentation of python scripts.
  source/_integrations/python_script.markdown
Labels: current

#37897 Removed wrong quotes from govee light local
  source/_integrations/govee_light_local.markdown
Labels: next

#37895 Map card: update screenshot to reflect current SW
  source/_dashboards/map.markdown
  source/images/dashboards/map_card.png
  source/images/dashboards/map_card.webp
  source/images/dashboards/map_card_config.png
Labels: current

#37902 Uppercase distributor names to fix sorting
  plugins/filters.rb
  source/_data/products.yml
  source/_includes/custom/buy-dialog.html
Labels: current

#37900 OTBR: remove mention of multiprotocol as it is discontinued
  source/_integrations/otbr.markdown
Labels: current

#37907 Matter certification blog
  source/_posts/2025-03-10-matter-certification.markdown
  source/images/blog/2025-03-matter-certification/art.jpg
  source/images/blog/2025-03-matter-certification/ha-matter.png
  source/images/blog/2025-03-matter-certification/lab.jpg
  source/images/blog/2025-03-matter-certification/ohf-matter.png
Labels: current

#37891 Update philips_js.markdown
  source/_integrations/philips_js.markdown
Labels: current

#37835 Update GIOS docs to remove information about the measuring station ID
  source/_integrations/gios.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37823 Add modbus hvac action documentation
  source/_integrations/modbus.markdown
Labels: next, has-parent, parent-merged

#37917 2025.3.2
  _config.yml
  source/_posts/2025-03-05-release-20253.markdown
  source/changelogs/core-2025.3.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37507 Update Jewish calendar docs based on updated library
  source/_integrations/jewish_calendar.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37916 Document HEOS auto-failover feature
  source/_integrations/heos.markdown
Labels: next, has-parent, parent-merged

#37922 Add µs to duration device class for sensor and number components
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent

#37925 Add InkBird ITH-11-B model
  source/_integrations/inkbird.markdown
Labels: next, has-parent, parent-merged

#37918 Update nexia.markdown to document emergency heat switch
  source/_integrations/nexia.markdown
Labels: current

#37938 Add instructions to remove the AirGradient device
  source/_integrations/airgradient.markdown
Labels: current

#37939 Add installation parameters to AirGradient
  source/_integrations/airgradient.markdown
Labels: current

#37932 Add lawn mower support to HomeKit
  source/_integrations/homekit.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37957 Add 3 documentation rules to Vodafone Station
  source/_integrations/vodafone_station.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37956 Add 3 documentation rules to Comelit
  source/_integrations/comelit.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37969 Comelit: add subheadings
  source/_integrations/comelit.markdown
Labels: current

#37970 Vodafone: add subheadings
  source/_integrations/vodafone_station.markdown
Labels: current

#37792 Extract the ID from a BLE device using the PsExec tool from Microsoft
  source/_integrations/private_ble_device.markdown
Labels: current, second-opinion-wanted

#37963 add workaround to use spotify on sonos
  source/_integrations/spotify.markdown
Labels: current

#37978 Add yaml option to disable sandbox to iframe documentation
  source/_dashboards/iframe.markdown
Labels: next, has-parent, parent-merged

#37937 Add more context to AirGradient introduction
  source/_integrations/airgradient.markdown
Labels: current

#37473 Add initial support for MQTT subentries with notify platform support
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37980 Remove rel="noreferrer" from distributor links
  source/_includes/custom/buy-dialog.html
Labels: current

#37982 Pi day recipe
  source/images/pi-day/2025-raspberry-pi-recipe.pdf
Labels: current

#37912 Add update_daily action to Habitica integration
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#33644 Filters for integration page
  Gemfile.lock
  sass/homeassistant/pages/_component_page.scss
  source/integrations/index.html
Labels: current

#37994 Add Valve platform to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#37568 Add Remote calendar integration
  source/_integrations/remote_calendar.markdown
Labels: new-integration, next, has-parent, parent-merged

#38014 Add Binary Sensor to Snoo
  source/_integrations/snoo.markdown
Labels: in-progress, next, has-parent, parent-merged

#37987 Add select entity for Snoo
  source/_integrations/snoo.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37867 Add Homee binary sensor platform
  source/_integrations/homee.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38017 Update nibe_heatpump documentation - adding newer models
  source/_integrations/nibe_heatpump.markdown
Labels: next, has-parent, parent-merged

#38016 Add Switch to Snoo
  source/_integrations/snoo.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#38021 IPP integration has no quality scale
  source/_integrations/ipp.md
Labels: current

#37986 Add night light level select for fan
  source/_integrations/vesync.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37999 Fix mqtt light schema defaults, state_value_template description and unclear template docs references
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/device_trigger.mqtt.markdown
  source/_integrations/event.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/image.mqtt.markdown
  source/_integrations/lawn_mower.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/notify.mqtt.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/tag.mqtt.markdown
  source/_integrations/text.mqtt.markdown
  source/_integrations/update.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
  source/_integrations/valve.mqtt.markdown
  source/_integrations/water_heater.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#37920 Add Reolink smart ai binary sensors docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38003 ZHA: general docs refinement
  source/_integrations/zha.markdown
Labels: current

#38031 Add Domadoo for Yellow
  source/_data/products.yml
Labels: current

#38019 Update MCP server Assist API documentation for implicit stateless API
  source/_integrations/mcp_server.markdown
Labels: next, has-parent, parent-merged

#38037 Document HEOS browse feature
  source/_integrations/heos.markdown
Labels: next, has-parent

#34072 Feature/openai conversion service
  source/_integrations/openai_conversation.markdown
Labels: next, has-parent, parent-merged

#38041 Add events to Snoo
  source/_integrations/snoo.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#38039 Add day night state sensor docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38043 ZHA: Reformat several Troubleshooting sections and tips
  source/_integrations/zha.markdown
Labels: current

#38052 Change the blue accent of the integration filters to blueDark
  sass/homeassistant/pages/_component_page.scss
Labels: current

#38053 Reolink VLAN troubleshooting step
  source/_integrations/reolink.markdown
Labels: current

#38056 Add troubleshooting case to Home Connect about no programs
  source/_integrations/home_connect.markdown
Labels: current

#38060 Add current room sensor to Roborock
  source/_integrations/roborock.markdown
Labels: in-progress, next, has-parent, parent-merged

#38070 Use standard option flow include for Vodafone Station
  source/_integrations/vodafone_station.markdown
Labels: current, has-parent

#38071 Adjust TTS documentation about Google Cast issues
  source/_integrations/tts.markdown
Labels: current

#38077 Adjust TTS documentation about Google Cast issues
  source/_integrations/tts.markdown
Labels: in-progress, current, needs-rebase

#38072 Adjust documentation for the homeassistant integration
  source/_integrations/homeassistant.markdown
Labels: current

#38074 Correct google cast documentation
  source/_integrations/cast.markdown
Labels: current

#38038 Add Reolink Home Hub scene docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37995 Add remoteControlStatus to SmartThings
  source/_integrations/smartthings.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38081 Update vodafone_station.markdown with supported models
  source/_integrations/vodafone_station.markdown
Labels: current

#38083 Add quality scale to Vodafone Station documentation
  source/_integrations/vodafone_station.markdown
Labels: current

#38094 Add template function: combine
  source/_docs/configuration/templating.markdown
Labels: next, has-parent, parent-merged

#38097 Fix a typo in zha documentation
  source/_integrations/zha.markdown
Labels: current

#37996 Add kids lock to SmartThings
  source/_integrations/smartthings.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38115 Add event platform to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#38113 Add PM1.0 to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#36984 Update Sensibo integration documentation
  source/_integrations/sensibo.markdown
Labels: next, has-parent, parent-merged

#38120 Add update platform to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#38119 Update the link to the API docs
  source/_integrations/rocketchat.markdown
Labels: current

#38108 Z-Wave: update recommended SDK versions
  source/_docs/z-wave/controllers.markdown
Labels: current

#38122 2025.3.4
  _config.yml
  source/_posts/2025-03-05-release-20253.markdown
  source/changelogs/core-2025.3.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#38125 Add removal section and instructions to NUT
  source/_integrations/nut.markdown
Labels: current

#38128 Add 700 RPM option to Home Connect washer spin speed options
  source/_integrations/home_connect.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38129 Homogenize Home Connect documentation
  source/_integrations/home_connect.markdown
Labels: current

#38131 Add missing Home Connect chiller doors
  source/_integrations/home_connect.markdown
Labels: next, has-parent, parent-merged

#38130 Fix some Home Connect option keys
  source/_integrations/home_connect.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38143 Add button platform to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#38138 Add dryer wrinkle prevent switch to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#38135 Add select platform to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#38139 Add power binary sensor to SmartThings
  source/_integrations/smartthings.markdown
Labels: next, has-parent, parent-merged

#38140 Document new buttons platform and PDU dynamic outlet buttons in NUT
  source/_integrations/nut.markdown
Labels: next, has-parent, parent-merged

#38146 Document new switch platform and PDU dynamic outlet switches in NUT
  source/_integrations/nut.markdown
Labels: next, has-parent, parent-merged

#38118 Add number platform to SmartThings
  source/_integrations/smartthings.markdown
Labels: in-progress, next, has-parent, parent-merged

#38141 Document installation parameters for NUT
  source/_integrations/nut.markdown
Labels: current

#38136 Move quality scale to silver for Vodafone Station
  source/_integrations/vodafone_station.markdown
Labels: current

#38133 Add examples to Vodafone Station
  source/_integrations/vodafone_station.markdown
Labels: current
