Repository home-assistant/home-assistant.io, pull requests merged in 2025-05, with the labels that each got.

#38838 Improve Twente Milieu documentation
  source/_integrations/twentemilieu.markdown
Labels: current

#38841 Link partner badges in docs to right website
  source/_includes/asides/component_navigation.html
Labels: current

#38844 Update image with correct branding
  source/images/docs/energy/energy-overview.png
Labels: current

#38842 Extend the RDW documentation
  source/_integrations/rdw.markdown
Labels: current

#38843 Update wwha badge
  source/_includes/asides/component_navigation.html
  source/images/works_with/works-with-bluetooth.png
  source/images/works_with/works-with-cloud.png
  source/images/works_with/works-with-local.png
  source/images/works_with/works-with-matter.png
  source/images/works_with/works-with-zigbee.png
  source/images/works_with/works-with-zwave.png
  source/images/works_with/works-with.png
Labels: current

#38837 Add GitHub Copilot instructions
  .github/copilot-instructions.md
Labels: current

#38852 Add data update details for Shelly integration
  source/_integrations/shelly.markdown
Labels: current

#38867 light: Replace kelvin with color_temp_kelvin
  source/_integrations/light.markdown
Labels: current

#38868 Add hazard lights binary sensor to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: next, has-parent, parent-merged

#38869 Add valet mode to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: next, has-parent, parent-merged

#38426 Add switch platform to eheimdigital
  source/_integrations/eheimdigital.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36668 Add Zimi Cloud Controller Documentation
  .vscode/cSpell.json
  source/_integrations/zimi.markdown
Labels: next, has-parent, parent-merged

#38863 Make the network device tracking feature optional in AVM Fritz!Tools
  source/_integrations/fritz.markdown
Labels: next, has-parent, parent-merged

#38831 Display attribute of an entity in Gauge card
  source/_dashboards/gauge.markdown
Labels: in-progress, next, has-parent, parent-merged

#38862 Improve MQTT JSON light supported_color_modes option description
  source/_integrations/light.mqtt.markdown
Labels: current, has-parent, parent-merged, by-code-owner, integration: mqtt

#38879 Fix typo for `apctest` in Known limitations section of APCUPSD
  source/_integrations/apcupsd.markdown
Labels: current

#38832 Fix entity ID in automation example for APCUPSD
  source/_integrations/apcupsd.markdown
Labels: current

#38853 Add description for possible permission problems for HmIP-DLD in HomematicIP-Cloud integration
  source/_integrations/homematicip_cloud.markdown
Labels: current

#38876 Provide detailed functionality description for APCUPSD
  source/_integrations/apcupsd.markdown
Labels: current

#38830 Update vesync.markdown
  source/_integrations/vesync.markdown
Labels: next, has-parent, parent-merged

#38877 Update environment_canada.markdown
  source/_integrations/environment_canada.markdown
Labels: current

#38864 Google Assistant Integration: Use `SERVICE_ACCOUNT.json` in yaml snippet
  source/_integrations/google_assistant.markdown
Labels: current

#38865 Update command signing section of tesla-fleet document
  source/_integrations/tesla_fleet.markdown
Labels: current

#38860 Update history.markdown
  source/_integrations/history.markdown
Labels: current

#38872 Add last attempted automatic backup sensor
  source/_integrations/backup.markdown
Labels: next, has-parent, parent-merged

#38858 Update history-graph.markdown
  source/_dashboards/history-graph.markdown
Labels: current

#38848 Add links to Bluetooth panels to help troubleshooting
  source/_integrations/bluetooth.markdown
Labels: next, has-parent, parent-merged

#38890 Add my links to network browsers
  source/_integrations/dhcp.markdown
  source/_integrations/ssdp.markdown
  source/_integrations/zeroconf.markdown
Labels: next, has-parent

#38889 Update cover.markdown
  source/_integrations/cover.markdown
Labels: current

#38545 Add docs for switchbot circulator fan
  source/_integrations/switchbot.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38895 Areas: add links
  source/_dashboards/area.markdown
  source/_data/glossary.yml
Labels: current

#38896 Zimi: fix indent to fix build
  source/_integrations/zimi.markdown
Labels: next

#38861 Add MQTT binary_sensor subentry support
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38897 Blog: add links to related docs
  source/_posts/2025-04-02-release-20254.markdown
Labels: current

#38898 rename page 'mutliple dashboard' to 'dashboard types'
  source/_includes/asides/dashboards_navigation.html
  source/_includes/asides/docs_sitemap.html
  source/getting-started/onboarding_dashboard.markdown
Labels: current

#38221 Allow liter for gas sensor device class
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#38901 Glossary blueprint: add links
  source/_data/glossary.yml
Labels: current

#38903 Areas and floors: add links and glossary refs
  source/_data/glossary.yml
  source/_docs/organizing/areas.markdown
  source/_docs/organizing/floors.markdown
Labels: current

#38839 Improve Peblar documentation
  source/_integrations/peblar.markdown
Labels: current

#38904 Rename S3 to AWS_S3
  source/_integrations/aws_s3.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38908 Rename S3 integration also in the release blog
  source/_posts/2025-05-07-release-20255.markdown
Labels: in-progress, needs-rebase, rc

#38911 Rehlko integration updates
  source/_integrations/rehlko.markdown
Labels: in-progress, next, has-parent

#38915 Update basics.markdown
  source/_docs/automation/basics.markdown
Labels: current

#38916 Update action.markdown
  source/_docs/automation/action.markdown
Labels: current

#38880 Add switch entity
  source/_integrations/zimi.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38923 Small 2025.5 release notes fixes
  source/_posts/2025-05-07-release-20255.markdown
Labels: in-progress, needs-rebase, rc

#38926 Add note about support for Roborock
  source/_integrations/roborock.markdown
Labels: current

#38930 Add example for attribute "ratio", available on HA 2025.5
  source/_integrations/transmission.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38905 Zimi: Add fan details
  source/_integrations/zimi.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38952 Fix broken link in frontend.markdown
  source/_integrations/frontend.markdown
Labels: current

#38917 Add Left/Right temp request to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38109 Cambridge Audio add control bus text
  source/_integrations/cambridge_audio.markdown
Labels: awaits-parent, next, has-parent

#38954 2025.5.1
  _config.yml
  source/_posts/2025-05-07-release-20255.markdown
  source/changelogs/core-2025.5.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#38953 Upload Roadmap 2025 blog
  source/_posts/2025-05-09-roadmap-2025h1.markdown
  source/images/blog/2025-05-roadmap-2025h1/art.jpg
  source/images/blog/2025-05-roadmap-2025h1/collective-intelligence.jpg
  source/images/blog/2025-05-roadmap-2025h1/device-context.jpg
  source/images/blog/2025-05-roadmap-2025h1/devices-without-context.jpg
  source/images/blog/2025-05-roadmap-2025h1/roadmap-2025-cover.png
  source/images/blog/2025-05-roadmap-2025h1/roadmap-2025.png
  source/images/blog/2025-05-roadmap-2025h1/shared-wisdom.jpg
  source/images/blog/2025-05-roadmap-2025h1/working-together.png
Labels: current

#38699 Add fan platform to homee integration
  source/_integrations/homee.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38965 Add docs for switchbot vacuum
  source/_integrations/switchbot.markdown
Labels: next, has-parent, parent-merged

#38958 Clarify battery runtime definition in NUT
  source/_integrations/nut.markdown
Labels: current

#38969 Clarify the need of admin rights for Synology DSM integration
  source/_integrations/synology_dsm.markdown
Labels: current

#38976 Document enphase envoy lifetime energy value decrease issue.
  source/_integrations/enphase_envoy.markdown
  source/images/integrations/enphase_envoy/enphase_envoy_production_decrease.png
Labels: current

#38959 Fix automation example to conform to status message change in NUT
  source/_integrations/nut.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38962 Improvements for ntfy documentation
  source/_integrations/ntfy.markdown
Labels: current

#38319 KNX Cover entity configuration from UI
  source/_integrations/knx.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38350 Add docs for new switch platform for bosch alarm
  source/_integrations/bosch_alarm.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38974 Add `flo` to water management category
  source/_integrations/flo.markdown
Labels: current

#38949 Update MacOS installation steps (#38096)
  source/_includes/installation/operating_system.md
Labels: current

#38979 update terminology used for bosch_alarm switches
  source/_integrations/bosch_alarm.markdown
Labels: next, has-parent

#34690 squeezebox update entity docs
  source/_integrations/squeezebox.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38935 Update switchbot.markdown to add Ceiling Light support
  source/_integrations/switchbot.markdown
Labels: current

#38929 Add IAM policy and bucket setup guidance to AWS S3 integration documentation
  source/_integrations/aws_s3.markdown
Labels: current

#38986 Remove Nuki's WWHA badge for now
  source/_integrations/nuki_matter.markdown
Labels: current

#38990 Fix link to Piper automation tutorial
  source/voice_control/voice_remote_local_assistant.markdown
Labels: current

#38991 Add Prusa CORE One as a working device for the PrusaLink integration
  source/_integrations/prusalink.markdown
Labels: current

#38992 Clarify unique ID limitations in FAQ
  source/_faq/unique_id.markdown
Labels: current

#38993 Update AWS S3 integration documentation to clarify compatibility and …
  source/_integrations/aws_s3.markdown
Labels: current

#39008 Improve mobile hero image fetchpriority
  source/_includes/site/hero_unit.html
Labels: current

#39009 Update troubleshooting section for Miele integration
  source/_integrations/miele.markdown
Labels: current

#39012 Add new required scopes to Slack integration
  source/_integrations/slack.markdown
Labels: in-progress, current, has-parent, needs-rebase

#39019 Add new `cluster` option to map card
  source/_dashboards/map.markdown
Labels: next, has-parent, parent-merged

#37973 Document modbus light color temperature and brightness support
  source/_integrations/modbus.markdown
Labels: next, has-parent, parent-merged

#38857 Update WMS WebControl pro button and cover documentation
  source/_integrations/wmspro.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38825 Add buttons to blue current integration
  source/_integrations/blue_current.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39030 Add system LED brightness to eheimdigital
  source/_integrations/eheimdigital.markdown
Labels: next, has-parent, parent-merged

#39032 Add important note about modified resolution for Nord Pool
  source/_integrations/nordpool.markdown
Labels: current

#39006 Add explaining text for a couple of Miele sensors
  source/_integrations/miele.markdown
Labels: in-progress, next, has-parent

#38943 Add credits sensor to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38928 Add explaining text for Miele plate sensors
  source/_integrations/miele.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38888 Update nexia.markdown to explain RoomIQ sensor switches
  source/_integrations/nexia.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#38345 Add documentation for binary sensors in the bosch alarm integration
  source/_integrations/bosch_alarm.markdown
Labels: in-progress, next, has-parent, parent-merged

#38451 Add documentation for alarm state sensors for bosch_alarm
  source/_integrations/bosch_alarm.markdown
Labels: next, has-parent, parent-merged

#38997 Add modern style template fan
  source/_integrations/template.markdown
Labels: next, has-parent, parent-merged

#36472 Add Installer login, Add ManualCharge Switch
  source/_integrations/kostal_plenticore.markdown
Labels: next, has-parent, parent-merged

#38818 Add reactive energy
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#38906 Add sensor entity
  source/_integrations/zimi.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#39011 Add modern style templates to Alarm Control Panel platform
  source/_integrations/template.markdown
Labels: next, has-parent

#38998 Add modern template lock
  source/_integrations/template.markdown
Labels: next, has-parent

#39061 Update securing description HA Cloud
  source/_docs/configuration/securing.markdown
Labels: current

#39062 2025.5.2
  _config.yml
  source/_posts/2025-05-07-release-20255.markdown
  source/changelogs/core-2025.5.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#39065 Fix 2025.5.2 link
  source/_posts/2025-05-07-release-20255.markdown
Labels: current

#39077 Fix dead link in KNX documentation
  source/_integrations/knx.markdown
Labels: current

#37855 Add Homee alarm-control-panel platform
  source/_integrations/homee.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39078 Add immich integration
  source/_integrations/immich.markdown
Labels: next, has-parent, parent-merged

#39069 Add Kaiser Nienhaus virtual motionblinds integration docs
  source/_integrations/kaiser_nienhaus.markdown
  source/_integrations/motion_blinds.markdown
Labels: next, has-parent, parent-merged

#39059 Add select platform to eheimdigital
  source/_integrations/eheimdigital.markdown
Labels: next, has-parent, parent-merged

#39014 Add modern style to template vacuum
  source/_integrations/template.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38684 Update Wallbox integration docs with solar charging
  source/_integrations/wallbox.markdown
Labels: awaits-parent, next, has-parent

#39075 Update miele.markdown
  source/_integrations/miele.markdown
Labels: next, has-parent

#39021 Update Green terms
  source/green/index.html
  source/green/styles.css
  source/images/blog/2023-09-ha10/green-intro.png
  source/images/frontpage/green-frontpage.png
Labels: current

#39001 Update sma.markdown
  source/_integrations/sma.markdown
Labels: current

#39089 Add diagnostics platform to Immich
  source/_integrations/immich.markdown
Labels: next, has-parent, parent-merged

#36438 Add buttons for sleep timer to bluesound integration
  source/_integrations/bluesound.markdown
Labels: in-progress, next, has-parent, parent-merged

#39094 Remove alarm doc changes published prior to code PR for Squeezebox
  source/_integrations/squeezebox.markdown
Labels: in-progress, current, has-parent, needs-rebase

#39046 Apple TV use suspend command
  source/_integrations/apple_tv.markdown
Labels: current

#38907 Add cover entity
  source/_integrations/zimi.markdown
Labels: in-progress, next, has-parent, parent-merged

#39083 Add media source to Immich
  source/_integrations/immich.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38665 Add Probe Plus integration documentation
  source/_integrations/probe_plus.markdown
Labels: new-integration, awaits-parent, next, has-parent, parent-merged

#39106 Update HomeKit to include (input_)button support in switch types
  source/_integrations/homekit.markdown
Labels: current

#39093 Changed code owners for the blue current integration.
  source/_integrations/blue_current.markdown
Labels: next, has-parent, parent-merged

#39100 Add Core installation limitation to Fail2Ban integration
  source/_integrations/fail2ban.markdown
Labels: current

#39110 Probe Plus integration: fix release version
  source/_integrations/probe_plus.markdown
Labels: next

#38368 Add documentation for new services for bosch_alarm
  source/_integrations/bosch_alarm.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#39105 Add Wh/km unit for energy distance
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#39112 Removed unsupported device from Govee Light Local
  source/_integrations/govee_light_local.markdown
Labels: current

#39117 Rehlko add additional generator states
  source/_integrations/rehlko.markdown
Labels: current

#39123 Green docs: update links to point to support website instead of Green…
  source/_docs/locked_out.md
  source/_includes/asides/docs_sitemap.html
  source/_includes/asides/getting_started_navigation.html
  source/_includes/common-tasks/commandline.md
  source/_integrations/homeassistant_green.markdown
  source/getting-started/onboarding.markdown
  source/green/index.html
  source/installation/green.html
  source/installation/index.html
  source/installation/troubleshooting.markdown
Labels: current

#39122 Yellow docs: change links from yellow to support docs page
  source/_docs/locked_out.md
  source/_docs/z-wave/controllers.markdown
  source/_includes/asides/docs_sitemap.html
  source/_includes/asides/getting_started_navigation.html
  source/_includes/common-tasks/commandline.md
  source/_integrations/homeassistant_yellow.markdown
  source/_integrations/homekit_controller.markdown
  source/_integrations/otbr.markdown
  source/_integrations/thread.markdown
  source/_redirects
  source/getting-started/onboarding.markdown
  source/installation/index.html
  source/installation/troubleshooting.markdown
  source/installation/yellow.html
  source/more-info/free-space.markdown
  source/yellow/index.html
Labels: current

#39142 Update MQTT cover example to avoid confusion with discovery prefix
  source/_integrations/cover.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#39137 Add binary_sensor documentation for Rehlko
  source/_integrations/rehlko.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35954 Update documentation for metoffice to support migration to DataHub API
  source/_integrations/metoffice.markdown
Labels: next, has-parent, parent-merged

#39143 Add documentation for a new button for chargers to the Lektrico integration
  source/_integrations/lektrico.markdown
Labels: next, has-parent

#38829 Switchbot_cloud: Binary Sensor for Lock's door state and calibration
  source/_integrations/switchbot_cloud.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39155 HomeKit Bridge: Adding `h264_qsv` as viable `VIDEO_CODEC` to doc
  source/_integrations/homekit.markdown
Labels: next, has-parent

#39148 Add pending damage and pending quest items sensors to Habitica
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#39103 Add paperless_ngx docs
  source/_integrations/paperless_ngx.markdown
Labels: new-integration, next, has-parent, parent-merged

#39160 Glossary add-on: add alias
  source/_data/glossary.yml
Labels: current

#39161 update deprecation blog images
  source/images/blog/2025-05-deprecation/art.png
  source/images/blog/2025-05-deprecation/methods.png
Labels: current

#39163 Update KNX documentation for IQS (#39020)
  source/_integrations/knx.markdown
Labels: in-progress, next, needs-rebase

#39158 Glossary Core, Supervised: add note that installation methods are d…
  source/_data/glossary.yml
Labels: current

#38922 Add MQTT cover as entity platform on MQTT subentries
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39165 Yellow: remove links to PCB explorer
  source/_posts/2024-11-27-home-assistant-yellow-gets-cm5-support.markdown
  source/yellow/index.html
Labels: current

#39162 About installation methods: remove Core, Supervised
  source/installation/index.html
Labels: current

#39167 Glossary: remove links to installation methods
  source/_data/glossary.yml
Labels: in-progress, current, needs-rebase

#39115 Add concentration conversion support for mg/m³
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#39168 Add timezone note Nord Pool custom action
  source/_integrations/nordpool.markdown
Labels: current

#39179 X86-64: remove Core installation type
  source/installation/generic-x86-64.markdown
Labels: current

#39151 Add automatic backup event entity
  source/_integrations/backup.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39178 Configuration: remove mention of Core and Supervised
  source/_docs/configuration.markdown
Labels: current

#39173 Linux: remove Core and Supervised as installation methods
  source/installation/linux.markdown
Labels: current

#39177 Odroid: remove Core as installation method
  source/installation/odroid.markdown
Labels: current

#39176 Windows: remove Core installation method
  source/installation/windows.markdown
Labels: current

#39170 Add MQTT fan as entity platform on MQTT subentries
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged
