Repository home-assistant/home-assistant.io, pull requests merged in 2025-04, with the labels that each got.

#38298 Fix Blueprint example to include required domain key
  source/_docs/blueprint/schema.markdown
Labels: current

#38300 Fix incorrect Worx Landroid example configuration
  source/_integrations/worxlandroid.markdown
Labels: current

#38307 Fix clear existing brand filter when selecting a category
  source/integrations/index.html
Labels: current

#38308 Fix title for PrusaLink installation guide for MK2.5/MK3 with Raspberry Pi 3/4
  source/_integrations/prusalink.markdown
Labels: current

#38316 Move quality scale to platinum for Vodafone Station
  source/_integrations/vodafone_station.markdown
Labels: current

#38317 Thinq: remove section on HACS, as custom cards are outside scope of t…
  source/_integrations/lg_thinq.markdown
Labels: current

#38318 Thinq: remove documentation of workaround
  source/_integrations/lg_thinq.markdown
Labels: current

#38320 Fixes for 2025-04 release notes
  source/_posts/2025-04-02-release-20254.markdown
  source/images/blog/2025-04/areas-experimental-dialog.png
Labels: in-progress, needs-rebase, rc

#38322 Fix plurality of virtual integrations
  source/_posts/2025-04-02-release-20254.markdown
Labels: in-progress, needs-rebase, rc

#38326 Add eve brand
  source/_integrations/eve.markdown
Labels: next, has-parent, parent-merged

#38333 Update clock docs
  source/_dashboards/clock.markdown
  source/images/dashboards/clock_card_london.png
  source/images/dashboards/clock_card_new_york.png
Labels: in-progress, current

#38337 2025.4: fix link to IronOS integration
  source/_posts/2025-04-02-release-20254.markdown
Labels: current

#38332 Add modern configuration for template light and switch
  source/_integrations/template.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38329 Add hint about seafile WebDAV capabilitites
  source/_integrations/webdav.markdown
Labels: current

#38327 Lost encryption key: make steps clearer
  source/more-info/backup-emergency-kit.markdown
Labels: current

#38358 Backups: fix steps in download and deletion procedures
  source/_includes/common-tasks/backups.md
Labels: current

#38361 action backup.create: add limitations
  source/_integrations/backup.markdown
Labels: current

#38363 Added documentation for Google Search option
  source/_integrations/google_generative_ai_conversation.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#38353 Add documentation about bosch alarm diagnostics
  source/_integrations/bosch_alarm.markdown
Labels: in-progress, next, has-parent, parent-merged

#38380 Add troubleshooting to Comelit
  source/_integrations/comelit.markdown
Labels: current

#38379 Add use cases to Comelit
  source/_integrations/comelit.markdown
Labels: current

#38338 Update installation parameter descriptions to match strings for NUT
  source/_integrations/nut.markdown
Labels: current

#38386 2025.4.1
  _config.yml
  source/_posts/2025-04-02-release-20254.markdown
  source/changelogs/core-2025.4.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#38391 Add a workaround for using Google Search in Google Generative AI
  source/_integrations/google_generative_ai_conversation.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38381 Add examples to Comelit
  source/_integrations/comelit.markdown
Labels: current

#38400 Improve AVM FRITZ!Box Tools docs
  source/_integrations/fritz.markdown
Labels: current

#38383 Add 3 documentation rules to SamsungTV
  source/_integrations/samsungtv.markdown
Labels: current

#37539 Add sensor platform to eheimdigital
  source/_integrations/eheimdigital.markdown
Labels: next, has-parent, parent-merged

#38340 Add reconfigure flow documentation to NUT
  source/_integrations/nut.markdown
Labels: next, has-parent, parent-merged

#38375 add documentation for reauth flow for bosch_alarm
  source/_integrations/bosch_alarm.markdown
Labels: next, has-parent, parent-merged

#38408 Add link to "domains"
  source/_docs/blueprint/selectors.markdown
Labels: current

#38163 Document sensors and diagnostic sensors in NUT
  source/_integrations/nut.markdown
Labels: current

#38410 Add removal instructions for SMLIGHT
  source/_integrations/smlight.markdown
Labels: current

#38411 Add installation parameters for SMLIGHT integration
  source/_integrations/smlight.markdown
Labels: current

#38412 Document data updates for SMLIGHT
  source/_integrations/smlight.markdown
Labels: current

#38407 Initial QualityScale updates for Squeezebox doc
  source/_integrations/squeezebox.markdown
Labels: current

#38376 Add troubleshooting, data updates and known limitations to the bosch_alarm integration
  source/_integrations/bosch_alarm.markdown
Labels: current

#38419 Backup: rephrase create-automatic description
  source/_integrations/backup.markdown
Labels: current

#38424 Fix missing asterisk on sensor name in NUT
  source/_integrations/nut.markdown
Labels: current

#38421 Document RainBird limitations from new firmware update
  source/_integrations/rainbird.markdown
Labels: current

#38442 Add information about Home Connect program option entities
  source/_integrations/home_connect.markdown
Labels: current

#38347 Add documentation for sensor platform in bosch_alarm
  source/_integrations/bosch_alarm.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38449 Move omit in TOC markers in alexa smart_home docs before header
  source/_integrations/alexa.smart_home.markdown
Labels: current

#38446 Update eafm.md with working URLs to Environment gov.uk website
  source/_integrations/eafm.md
Labels: current

#38447 Add a note about the location of the event emitting function to the Shelly documentation
  source/_integrations/shelly.markdown
Labels: current, has-parent

#38420 Updates for Squeezebox integration doc for Gold Quality Scale
  source/_integrations/squeezebox.markdown
Labels: current

#38466 Extend UnitOfReactivePower with 'kvar'
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#38482 Fix release version for Remote Calendar integration
  source/_integrations/remote_calendar.markdown
Labels: current

#38268 Create new actions section and clarify CLI commands for NUT
  source/_integrations/nut.markdown
Labels: current

#38417 Update HomeKit docs for air purifiers
  source/_integrations/homekit.markdown
Labels: in-progress, next, has-parent, parent-merged

#38399 Document Airzone battery/signal thermostat sensors
  source/_integrations/airzone.markdown
Labels: in-progress, next, has-parent, parent-merged

#38357 Add docs for switchbot new integration roller shade and hubmini matter
  source/_integrations/switchbot.markdown
Labels: next, has-parent, parent-merged

#38484 Update alpha_vantage.markdown
  source/_integrations/alpha_vantage.markdown
Labels: current

#38481 Fix yaml in Google Generative AI
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#37990 Lowercase SERVICE_ACCOUNT.json extension
  source/_integrations/google_assistant.markdown
Labels: current

#38469 Address a few more quality scale rules for SMLIGHT
  source/_integrations/smlight.markdown
Labels: current

#38491 Add Eve to device names
  source/_integrations/eve.markdown
Labels: current

#38489 Remove extra asterisk from sensor definition in NUT
  source/_integrations/nut.markdown
Labels: current

#38485 Improve MQTT template docs on handling null values
  source/_docs/configuration/templating.markdown
  source/_integrations/sensor.mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#38488 Remove UPS Status section covered under sensors in NUT
  source/_integrations/nut.markdown
Labels: current

#38496 Update system_log.markdown: clarifications for "max_entries"
  source/_integrations/system_log.markdown
Labels: current

#38493 2025.4.2
  _config.yml
  source/_posts/2025-04-02-release-20254.markdown
  source/changelogs/core-2025.4.markdown
Labels: blog, in-progress, current, has-parent, needs-rebase, parent-merged

#38478 Add flash and transition feature flags for MQTT json light
  source/_integrations/light.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged, by-code-owner, integration: mqtt

#38389 Add automation example to NUT
  source/_integrations/nut.markdown
Labels: current

#37936 Sync AirGradient entities with the codebase
  source/_integrations/airgradient.markdown
Labels: current

#38497 Fix huawei_lte SSL cert example vs other words wording
  source/_integrations/huawei_lte.markdown
Labels: in-progress, current, needs-rebase

#38513 Clarify what OS:es are supported and not
  source/_includes/installation/supervised.md
Labels: current

#38487 Cleanup whirlpool integration docs
  source/_integrations/whirlpool.markdown
Labels: current

#38517 Add support for the IAM-T1 to inkbird
  source/_integrations/inkbird.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38509 Remove deprecated state attributes in TotalConnect
  source/_integrations/totalconnect.markdown
Labels: next, has-parent

#38503 Update daikin.markdown
  source/_integrations/daikin.markdown
Labels: current

#38524 Doc update for SpaceAPI support for v15 of that API
  source/_integrations/spaceapi.markdown
Labels: current

#38476 Add template function: device_name
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38468 Add Cloud Beeline and Mail.ru Cloud providers in WebDAV integration
  source/_integrations/webdav.markdown
Labels: current

#38313 Add note on flash endurance for APsystems integration
  source/_integrations/apsystems.markdown
Labels: current

#38390 Update kulersky.markdown
  source/_integrations/kulersky.markdown
Labels: next, has-parent, parent-merged

#37728 Weheat: Add flow entities
  source/_integrations/weheat.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38534 Don't mention Raspberry Pi 3 in list of download images
  _config.yml
  source/installation/raspberrypi.markdown
Labels: current

#38252 Instructions for deriving media-source:// from Media Browser URL
  source/_integrations/media_source.markdown
Labels: current

#37549 Update Google Calendar's scenario 2 instructions
  source/_includes/integrations/google_client_secret.md
Labels: current

#38508 Add recording packing time docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38536 Fix typo in matter docs
  source/_integrations/matter.markdown
Labels: current

#38522 Improve Nest troubleshooting readability
  source/_integrations/nest.markdown
Labels: current

#38541 Add integration removal documentation to APCUPSD
  source/_integrations/apcupsd.markdown
Labels: current

#38502 Move Example resources to Troubleshooting for easier readability of NUT
  source/_integrations/nut.markdown
Labels: current

#38504 Add number platform to eheimdigital
  source/_integrations/eheimdigital.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38555 Fix incorrect sensor type in Nord Pool
  source/_integrations/nordpool.markdown
Labels: current

#38560 Re-instate relative_time template method into docs
  source/_docs/configuration/templating.markdown
Labels: current

#38557 Clean up non working example from Edimax integration docs
  source/_integrations/edimax.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38561 Clarify Bluetooth Tracker integration is only available for Core installation types
  source/_integrations/bluetooth_tracker.markdown
Labels: in-progress, current, has-parent, needs-rebase

#38542 Add encryption clarification to onedrive
  source/_integrations/onedrive.markdown
Labels: current

#38554 Add find config entry tip to Nord Pool
  source/_integrations/nordpool.markdown
Labels: current

#38438 Add docs page for Miele integration
  source/_integrations/miele.markdown
Labels: new-integration, next, has-parent, parent-merged

#38558 Upload SOTOH blog
  source/_posts/2025-04-16-state-of-the-open-home-recap.markdown
  source/images/blog/2025-04-SOTOH/HA-community-day.jpg
  source/images/blog/2025-04-SOTOH/art.jpg
  source/images/blog/2025-04-SOTOH/closing.jpg
  source/images/blog/2025-04-SOTOH/hacs-ma.jpg
  source/images/blog/2025-04-SOTOH/mob-museum.jpg
  source/images/blog/2025-04-SOTOH/ohf-growth.jpg
  source/images/blog/2025-04-SOTOH/ohf-structure.jpg
  source/images/blog/2025-04-SOTOH/ohf-supporters.jpg
  source/images/blog/2025-04-SOTOH/ohf-survey.jpg
  source/images/blog/2025-04-SOTOH/runar.jpg
  source/images/blog/2025-04-SOTOH/values.jpg
  source/images/blog/2025-04-SOTOH/voice-ai.jpg
  source/images/blog/2025-04-SOTOH/wwha.jpg
Labels: current

#38573 Small blog updates
  source/_posts/2025-03-26-state-of-the-open-home-2025-announcement.markdown
  source/_posts/2025-04-02-release-20254.markdown
Labels: current

#38575 Clarify username/password for Control4
  source/_integrations/control4.markdown
Labels: current

#38574 Document and clarify upstream devices and hierachies
  source/_docs/energy/individual-devices.markdown
Labels: current

#38581 Add detailed TLS/SSL limitations for Ecowitt integration
  source/_integrations/ecowitt.markdown
Labels: current

#38582 Add compatible transceiver and tested smart meter to EDL21 documentation
  source/_integrations/edl21.markdown
Labels: current

#38583 Add Zoom USB Modem Model 3095 to modem_callerid compatibility list
  source/_integrations/modem_callerid.markdown
Labels: current

#38587 Update switchbot docs
  source/_integrations/switchbot.markdown
Labels: current

#38546 Update YoLink integration supported device list
  source/_integrations/yolink.markdown
Labels: current

#38594 Update homepage SOTOH cards
  source/_includes/custom/news.html
  source/images/frontpage/feature-sotoh2025.jpg
Labels: current

#38593 Adjusted incorrect information for switchbot docs
  source/_integrations/switchbot.markdown
Labels: current

#38597 Reolink WWHA blog
  source/_posts/2022-07-12-partner-program.markdown
  source/_posts/2022-07-27-leviton-partner.markdown
  source/_posts/2022-10-13-third-reality-partner.markdown
  source/_posts/2022-10-25-ultraloq-partner.markdown
  source/_posts/2022-10-27-jasco-partner.markdown
  source/_posts/2023-03-03-heltun-partner.markdown
  source/_posts/2023-04-11-homeseer-partner.markdown
  source/_posts/2023-12-07-homewizard-joins-works-with-home-assistant-program.markdown
  source/_posts/2024-08-08-works-with-home-assistant-becomes-part-ohf.markdown
  source/_posts/2024-09-03-aqara-joins-works-with-home-assistant.markdown
  source/_posts/2025-02-27-apollo-joins-wwha.markdown
  source/_posts/2025-03-27-motionblinds-joins-wwha.markdown
  source/_posts/2025-04-17-reolink-joins-works-with-home-assistant.markdown
  source/images/blog/2025-04-reolink/argus-track.webm
  source/images/blog/2025-04-reolink/art.jpg
Labels: current

#38401 Update lamarzocco docs for v2
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38490 Add fit mode to picture glance card
  source/_dashboards/picture-glance.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38606 Add WWHA for Reolink
  source/_integrations/reolink.markdown
Labels: in-progress, current, needs-rebase

#38604 Replace comma at the end of sentence in SOTOH post
  source/_posts/2025-04-16-state-of-the-open-home-recap.markdown
Labels: current

#38611 Add instructions for removing ESPHome integration
  source/_integrations/esphome.markdown
Labels: current

#38612 Document required manual inputs for ESPHome new entry config flow
  source/_integrations/esphome.markdown
Labels: current

#38613 Add supported devices and updating data section to ESPHome
  source/_integrations/esphome.markdown
Labels: current

#38618 Add known limitations section to ESPHome
  source/_integrations/esphome.markdown
Labels: current

#38616 Add use cases section to ESPHome
  source/_integrations/esphome.markdown
Labels: current

#38615 Add troubleshooting section to ESPHome
  source/_integrations/esphome.markdown
Labels: current

#38614 Add supported functionality to ESPHome
  source/_integrations/esphome.markdown
Labels: current

#38622 Explicitly document ESPHome options flow
  source/_integrations/esphome.markdown
Labels: current

#38626 Update http.markdown
  source/_integrations/http.markdown
Labels: current

#38388 Add known limitations to NUT
  source/_integrations/nut.markdown
Labels: current

#38623 Update ESPHome use cases to mention the Voice PE
  source/_integrations/esphome.markdown
Labels: current

#38631 Add firmware requirement for Gardena Irrigation Valve 9V
  source/_integrations/gardena_bluetooth.markdown
Labels: current

#38621 Mark Reolink WWHA models bold
  source/_integrations/reolink.markdown
Labels: current

#38610 Add find config entry tip to easyEnergy
  source/_integrations/easyenergy.markdown
Labels: current

#38609 Add find config entry tip to EnergyZero
  source/_integrations/energyzero.markdown
Labels: current

#38608 Improve Feedreader docs
  source/_data/glossary.yml
  source/_integrations/feedreader.markdown
Labels: current, has-parent

#38607 Added everblu-meters-esp8266/esp32 to water.markdown
  source/_docs/energy/water.markdown
Labels: current

#38600 Add websocket connectivity sensor to lamarzocco
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38632 2025.4.3
  _config.yml
  source/_posts/2025-04-02-release-20254.markdown
  source/changelogs/core-2025.4.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#38599 Add preextraction numbers for lamarzocco
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38598 Add lamarzocco sensors
  source/_integrations/lamarzocco.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38559 Remove legacy format exception for ESPHome entity naming
  source/_integrations/esphome.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38642 Fix DHCP typo
  source/_integrations/reolink.markdown
Labels: current

#38645 Fix link markdown in Nuki docs
  source/_integrations/nuki.markdown
Labels: current

#38661 Add last cleaning lamarzocco docs
  source/_integrations/lamarzocco.markdown
Labels: next, has-parent, parent-merged

#38639 Add 3 stars to description
  source/_integrations/jewish_calendar.markdown
Labels: current

#38662 Improve Tankerkoenig docs
  source/_integrations/tankerkoenig.markdown
Labels: current, has-parent

#38620 Add Reolink Lumus Pro to tested models
  source/_integrations/reolink.markdown
Labels: current

#38641 Update documentation for new local api config flow in Overkiz.
  source/_integrations/overkiz.markdown
Labels: next, has-parent

#38540 Add prerequsite to APCUPSD
  source/_integrations/apcupsd.markdown
Labels: current

#38658 Remove deprecated addon_update action call from Supervisor
  source/_integrations/hassio.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#38672 Added LeChacal AC hats for CT clamp
  source/_includes/energy/ct_clamp.md
Labels: current

#38673 Add troubleshooting section to ista EcoTrend
  source/_integrations/ista_ecotrend.markdown
Labels: current

#38323 Update Music Assistant documentation to the Gold Quality Level
  source/_integrations/music_assistant.markdown
Labels: current

#38674 Fix rendering problems on Music Assistant page
  source/_integrations/music_assistant.markdown
Labels: current

#38675 Removing the integration
  source/_integrations/acaia.markdown
  source/_integrations/airgradient.markdown
  source/_integrations/aquacell.markdown
  source/_integrations/bring.markdown
  source/_integrations/cookidoo.markdown
  source/_integrations/eheimdigital.markdown
  source/_integrations/electric_kiwi.markdown
  source/_integrations/enigma2.markdown
  source/_integrations/flick_electric.markdown
  source/_integrations/fronius.markdown
  source/_integrations/fyta.markdown
  source/_integrations/habitica.markdown
  source/_integrations/homewizard.markdown
  source/_integrations/husqvarna_automower.markdown
  source/_integrations/incomfort.markdown
  source/_integrations/iometer.markdown
  source/_integrations/ista_ecotrend.markdown
  source/_integrations/knx.markdown
  source/_integrations/lcn.markdown
  source/_integrations/letpot.markdown
  source/_integrations/mcp.markdown
  source/_integrations/mcp_server.markdown
  source/_integrations/nut.markdown
  source/_integrations/overseerr.markdown
  source/_integrations/powerfox.markdown
  source/_integrations/pyload.markdown
  source/_integrations/rainbird.markdown
  source/_integrations/reolink.markdown
  source/_integrations/slide_local.markdown
  source/_integrations/solarlog.markdown
  source/_integrations/suez_water.markdown
  source/_integrations/weheat.markdown
Labels: current

#38681 Revert "Update Wallbox integration docs with solar charging (#37700)"
  source/_integrations/wallbox.markdown
Labels: current

#38682 Revert "Update Wallbox integration docs with solar charging (#37700)"
  source/_integrations/wallbox.markdown
Labels: next

#38678 Add data-updates documention to Renault
  source/_integrations/renault.markdown
Labels: next, has-parent, parent-merged

#38689 Add troubleshooting section to Renault
  source/_integrations/renault.markdown
Labels: current

#36833 Add documentation for ntfy integration
  source/_integrations/ntfy.markdown
Labels: new-integration, next, has-parent, parent-merged
