Repository home-assistant/home-assistant.io, pull requests merged in 2025-09, with the labels that each got.

#40608 Add Reolink encoding docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#37416 Update mention of Starlink's energy, upload and download usages in docs
  source/_integrations/starlink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40595 Add documentation for the select entity
  source/_integrations/togrill.markdown
Labels: next, has-parent, parent-merged

#40519 Update netatmo.markdown
  source/_integrations/netatmo.markdown
Labels: current

#40642 Add quality scale to apcupsd integration
  source/_integrations/apcupsd.markdown
Labels: next, has-parent, parent-merged

#37941 Add docs for Libre Hardware Monitor integration
  source/_integrations/libre_hardware_monitor.markdown
Labels: new-integration, awaits-parent, next, has-parent, parent-merged

#40678 Remove vulcan integration docs
  CODEOWNERS
  source/_integrations/vulcan.markdown
  source/_redirects
Labels: in-progress, next, has-parent, parent-merged

#40695 Add Frient WWHA blog
  source/_posts/2025-09-02-frient-joins-works-with-home-assistant.markdown
  source/images/blog/2025-09-frient/art.webp
  source/images/blog/2025-09-frient/energy-usage-data.webp
Labels: current

#39516 Update supported hubs in fibaro integration
  source/_integrations/fibaro.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#40704 Update screenshot for 2025.9 release
  source/_posts/2025-09-03-release-20259.markdown
  source/images/blog/2025-09/disk-metrics.png
  source/images/blog/2025-09/home-dashboard-area.png
  source/images/blog/2025-09/home-dashboard-lights.png
  source/images/blog/2025-09/home-dashboard.png
  source/images/blog/2025-09/temp-home-dashboard-area.png
  source/images/blog/2025-09/temp-home-dashboard-lights.png
  source/images/blog/2025-09/temp-home-dashboard.png
  source/images/blog/2025-09/temp-tile-feature-button.png
  source/images/blog/2025-09/temp-tile-feature-fan-direction.png
  source/images/blog/2025-09/temp-tile-feature-fan-oscillation.png
  source/images/blog/2025-09/temp-tile-feature-history-chart.png
  source/images/blog/2025-09/temp-tile-feature-set-date.png
  source/images/blog/2025-09/temp-tile-feature-valve-controls.png
  source/images/blog/2025-09/tile-features-bar-gauge.png
  source/images/blog/2025-09/tile-features-button.png
  source/images/blog/2025-09/tile-features-date.png
  source/images/blog/2025-09/tile-features-fan.png
  source/images/blog/2025-09/tile-features-media-player.png
  source/images/blog/2025-09/tile-features-trend-graph.png
  source/images/blog/2025-09/tile-features-valve.png
Labels: in-progress, needs-rebase, rc

#40709 Update fan screenshot for 2025.9 release note
  source/images/blog/2025-09/tile-features-fan.png
Labels: in-progress, needs-rebase, rc

#40719 Clarify that Elite Floodlight WiFi needs mains power
  source/_integrations/reolink.markdown
Labels: current

#40737 Add data updates section in Android TV Remote
  source/_integrations/androidtv_remote.markdown
Labels: current

#40732 Add data updates section to ntfy integration
  source/_integrations/ntfy.markdown
Labels: current

#40688 Shelly: Rewording/rephrasing for consistency and readability
  source/_integrations/shelly.markdown
Labels: current

#40764 Add note on the need to restart after editing shell command
  source/_integrations/shell_command.markdown
Labels: current

#40789 Rename installation method to installation type
  source/_data/glossary.yml
  source/_docs/automation/using_blueprints.markdown
  source/_docs/configuration.markdown
  source/_docs/tools/hass.markdown
  source/_faq/ha-vs-hassio.markdown
  source/_includes/installation/container.md
  source/_integrations/go2rtc.markdown
  source/_integrations/lacrosse.markdown
  source/_redirects
  source/installation/index.html
Labels: in-progress, current, needs-rebase

#38725 Add `ntfy.publish` action to ntfy integration
  source/_integrations/ntfy.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#40795 Add AI category for integrations with AI Task
  source/_integrations/google_generative_ai_conversation.markdown
  source/_integrations/ollama.markdown
  source/_integrations/open_router.markdown
  source/_integrations/openai_conversation.markdown
Labels: current

#40797 fix typo in url
  source/_integrations/alexa_devices.markdown
Labels: current

#40749 Introduce `default_entity_id` to replace `object_id` for mqtt entity platforms
  source/_integrations/alarm_control_panel.mqtt.markdown
  source/_integrations/binary_sensor.mqtt.markdown
  source/_integrations/button.mqtt.markdown
  source/_integrations/camera.mqtt.markdown
  source/_integrations/climate.mqtt.markdown
  source/_integrations/cover.mqtt.markdown
  source/_integrations/device_tracker.mqtt.markdown
  source/_integrations/event.mqtt.markdown
  source/_integrations/fan.mqtt.markdown
  source/_integrations/humidifier.mqtt.markdown
  source/_integrations/image.mqtt.markdown
  source/_integrations/lawn_mower.mqtt.markdown
  source/_integrations/light.mqtt.markdown
  source/_integrations/lock.mqtt.markdown
  source/_integrations/mqtt.markdown
  source/_integrations/notify.mqtt.markdown
  source/_integrations/number.mqtt.markdown
  source/_integrations/scene.mqtt.markdown
  source/_integrations/select.mqtt.markdown
  source/_integrations/sensor.mqtt.markdown
  source/_integrations/siren.mqtt.markdown
  source/_integrations/switch.mqtt.markdown
  source/_integrations/text.mqtt.markdown
  source/_integrations/update.mqtt.markdown
  source/_integrations/vacuum.mqtt.markdown
  source/_integrations/valve.mqtt.markdown
  source/_integrations/water_heater.mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#40802 Update reolink.markdown
  source/_integrations/reolink.markdown
Labels: current

#40693 Add or update known issues for Enphase Envoy
  source/_integrations/enphase_envoy.markdown
Labels: current

#39268 Add Portainer docs
  source/_integrations/portainer.markdown
Labels: new-integration, awaits-parent, next, has-parent, parent-merged

#40850 2025.9.3
  _config.yml
  source/_posts/2025-09-03-release-20259.markdown
Labels: in-progress, current, has-parent, needs-rebase

#40846 Fix description of `multiple` field of Object selectors
  source/_docs/blueprint/selectors.markdown
Labels: current

#40863 add brave requirement to html5
  source/_integrations/html5.markdown
Labels: current

#40859 Govee light local update
  source/_integrations/govee_light_local.markdown
Labels: in-progress, next, has-parent, parent-merged

#39826 Update Nederlandse Spoorwegen integration documentation and improve c…
  source/_integrations/nederlandse_spoorwegen.markdown
Labels: next, has-parent, parent-merged

#40871 Add air purifier catalog index for switchbot integration
  source/_integrations/switchbot.markdown
Labels: current

#40877 Add sensors docs for switchbot integration
  source/_integrations/switchbot_cloud.markdown
Labels: in-progress, next, has-parent

#40874 Add Plug Mini EU and rgbicww lights docs for switchbot integration
  source/_integrations/switchbot.markdown
Labels: next, has-parent, parent-merged

#40889 fix outdated documentation for Velux KLF200 reboot
  source/_integrations/velux.markdown
Labels: current

#40872 Add relay switch 2pm doc for switchbot integration
  source/_integrations/switchbot.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37609 Adjust Satel Integra for config and subentry flow
  source/_integrations/satel_integra.markdown
Labels: next, has-parent, parent-merged

#40901 Add removal instructions to some integrations
  source/_integrations/nanoleaf.markdown
  source/_integrations/spotify.markdown
  source/_integrations/twitch.markdown
  source/_integrations/withings.markdown
  source/_integrations/youtube.markdown
Labels: current

#40899 Include authorization details for Reolink integration
  source/_integrations/reolink.markdown
Labels: current

#40820 Community page
  .gitignore
  Rakefile
  sass/homeassistant/pages/community/_base.scss
  sass/homeassistant/pages/community/_buttons.scss
  sass/homeassistant/pages/community/_event-card.scss
  sass/homeassistant/pages/community/_icon.scss
  sass/homeassistant/pages/community/_mixins.scss
  sass/homeassistant/pages/community/_photos.scss
  sass/homeassistant/pages/community/_stats.scss
  sass/homeassistant/pages/community/_variables.scss
  sass/homeassistant/pages/community/components/_faq.scss
  sass/homeassistant/pages/community/components/_global.scss
  sass/homeassistant/pages/community/components/_hero.scss
  sass/homeassistant/pages/community/components/_join.scss
  sass/homeassistant/pages/community/components/_meetups.scss
  sass/homeassistant/pages/community/components/_nav.scss
  sass/homeassistant/pages/community/components/_newsletter.scss
  sass/homeassistant/pages/community/index.scss
  source/_data/community-faq.yml
  source/_includes/custom/news.html
  source/_includes/site/footer.html
  source/_posts/2025-09-17-home-assistant-turns-12.markdown
  source/_redirects
  source/community/assets/_icons.html
  source/community/components/_faq.html
  source/community/components/_global.html
  source/community/components/_hero.html
  source/community/components/_join.html
  source/community/components/_meetups.html
  source/community/components/_nav.html
  source/community/components/_newsletter.html
  source/community/index.html
  source/images/blog/2025-09-12th-anniversary/art.webp
  source/images/blog/2025-09-12th-anniversary/contributors.webp
  source/images/community/berlin.webp
  source/images/community/columbus.webp
  source/images/community/hero-m.svg
  source/images/community/hero.svg
  source/images/community/og.jpeg
  source/images/community/utrecht.webp
  source/images/frontpage/community-card.webp
  source/images/frontpage/community-meetup.webp
  source/javascripts/dsap.es.js
Labels: current

#40892 Add mg/m³ as a valid UOM for sensor/number Carbon Monoxide device class
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: next, has-parent, parent-merged

#40906 Fix CO and CO2 descriptions
  source/_integrations/sensor.markdown
Labels: in-progress, next, needs-rebase

#40910 Add Reolink automation idea: PTZ timelaps
  source/_integrations/reolink.markdown
Labels: current

#36120 Add documentation for compit integration
  source/_integrations/compit.markdown
Labels: next, has-parent, parent-merged

#40924 Update documentation about Exelon subsidiaries
  source/_integrations/opower.markdown
Labels: next

#40930 Add power usage to system bridge sensors
  source/_integrations/system_bridge.markdown
Labels: next, has-parent, parent-merged

#40932 2025.9.4
  _config.yml
  source/_posts/2025-09-03-release-20259.markdown
  source/changelogs/core-2025.9.markdown
Labels: in-progress, current, has-parent, needs-rebase

#40944 Add Marantz NR1609 to tested list
  source/_integrations/denonavr.markdown
Labels: current

#40946 Update documentation about Exelon subsidiaries
  source/_integrations/opower.markdown
Labels: in-progress, current, needs-rebase

#40897 Add documentation for profiler.dump_sockets service
  source/_integrations/profiler.markdown
Labels: awaits-parent, next, has-parent

#40581 Add optional language to Mastodon post action
  source/_integrations/mastodon.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#40661 Document switch entity for add-ons
  source/_integrations/hassio.markdown
Labels: next, has-parent, parent-merged

#39146 Added start charge session action documentation for the blue current integration.
  source/_integrations/blue_current.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#41004 Thermostat card water_heater support
  source/_dashboards/thermostat.markdown
Labels: next, has-parent

#40994 Add collaboration badge to products
  sass/homeassistant/pages/connect/zwa-2/_base.scss
  sass/homeassistant/pages/connect/zwa-2/components/_buy.scss
  source/connect/zwa-2/components/_buy.html
  source/green/index.html
  source/green/styles.css
  source/images/collaboration/desktop-on-dark.png
  source/images/collaboration/desktop-on-light.png
  source/images/collaboration/mobile-on-dark.png
  source/images/collaboration/mobile-on-light.png
  source/images/voice-pe/vpe-overlay.webp
  source/stylesheets/homeassistant/pages/connect/zwa-2/index.css
  source/voice-pe/index.html
  source/voice-pe/styles.css
Labels: current

#40997 Update community events
  source/community/components/_hero.html
  source/community/components/_meetups.html
Labels: current

#41005 Add ntfy integration updates to 2025.10 release notes
  source/_posts/2025-10-01-release-202510.markdown
Labels: in-progress, needs-rebase, rc

#41000 Litter Robot integration: Add installation options
  source/_integrations/litterrobot.markdown
Labels: current

#40991 Add HMIP-WTH-1 to supported devices
  source/_integrations/homematicip_cloud.markdown
Labels: current

#40982 update enphase_envoy template example to split battery power
  source/_integrations/enphase_envoy.markdown
Labels: current

#41017 ZWA-2 FAQ Updates
  sass/homeassistant/pages/connect/zwa-2/components/_faq.scss
  source/_data/product/connect/zwa-2/faq.yml
  source/images/connect/zwa-2/latency.webp
Labels: current

#41019 Fix typo in templating documentation
  source/_docs/automation/templating.markdown
Labels: current

#41031 Improve troubleshooting in Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: current

#41024 Update lightwave.markdown
  source/_integrations/lightwave.markdown
Labels: current

#41035 docs: Fix typo in Hue integration documentation
  source/_integrations/hue.markdown
Labels: current

#40894 Add garage door opener doc for switchbot integration
  source/_integrations/switchbot.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#41038 Add ConBee thread enable link
  source/_integrations/thread.markdown
Labels: current

#41011 Make wording more clear for ekey bionyx and correct SFTP Storage link in 2025.10 release notes
  source/_posts/2025-10-01-release-202510.markdown
Labels: in-progress, needs-rebase, rc

#41044 Fix number of integrations that reached platinum
  source/_posts/2025-10-01-release-202510.markdown
Labels: in-progress, needs-rebase, rc

#40665 Update features.markdown
  source/dashboards/features.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#41051 Added autodiscover flag, known limitations and a troubleshoot item
  source/_integrations/pooldose.markdown
Labels: in-progress, next, needs-rebase

#41015 Bumps next community event
  source/community/components/_hero.html
  source/community/components/_meetups.html
Labels: current

#41067 Add Reolink AI bicycle detection docs
  source/_integrations/reolink.markdown
Labels: next, has-parent, parent-merged

#41068 Improve LetPot docs to better match template and fix heading inconsistency
  source/_integrations/letpot.markdown
Labels: in-progress, next, needs-rebase

#40916 Add Reolink floodlight event entities docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#41092 Clean up Aladdin Connect documentation
  source/_integrations/aladdin_connect.markdown
  source/images/integrations/aladdin_connect/oauth-screenshot.png
Labels: current

#41094 Add Level documentation
  source/_integrations/level.markdown
Labels: in-progress, next, has-parent, needs-rebase, parent-merged

#41093 Add Eltako documentation
  source/_integrations/eltako.markdown
Labels: in-progress, next, has-parent, needs-rebase, parent-merged

#40406 Add notify platform to Habitica
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged
