Repository home-assistant/home-assistant.io, pull requests merged in 2025-01, with the labels that each got.

#36642 Update sky_remote.markdown
  source/_integrations/sky_remote.markdown
Labels: current

#36623 Add number platform to Mill integration
  source/_integrations/mill.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36636 Fix minor typos in 2025.1 release notes
  source/_posts/2025-01-03-release-20251.markdown
Labels: in-progress, needs-rebase, rc

#35062 Add documentation for Bang & Olufsen button Event entites
  source/_integrations/bang_olufsen.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#36649 Voice PE: fix typo in audio codec. should be AIC3204
  source/voice-pe/index.html
Labels: current

#36567 Document operation modes for Twinkly integration
  source/_integrations/twinkly.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged, integration: twinkly

#36650 Update Mastodon permissions
  source/_integrations/mastodon.markdown
Labels: current

#36651 Backups
  source/_includes/common-tasks/backups.md
  source/_includes/common-tasks/network_storage.md
  source/images/screenshots/network-storage/backup_locations_all.png
  source/images/screenshots/network-storage/backup_select_local_default.png
  source/images/screenshots/network-storage/change_backup_dark.png
  source/images/screenshots/network-storage/change_backup_light.png
Labels: next, has-parent

#36654 Free space: add links to backup
  source/_includes/common-tasks/backups.md
  source/more-info/free-space.markdown
Labels: next, has-parent

#36655 Wipe data disk: update steps for CM4 and CM5
  source/_includes/common-tasks/commandline.md
Labels: current

#36663 Fix Tesla Fleet broken URL in 2025.1
  source/_posts/2025-01-03-release-20251.markdown
Labels: in-progress, needs-rebase, rc

#36661 Add switches to ohme
  source/_integrations/ohme.markdown
Labels: next, has-parent, parent-merged

#36673 wipe data disk: fix title, improve structure
  source/_includes/common-tasks/commandline.md
Labels: current

#36674 Change noteworthy tplink PR in 2025.1 release notes
  source/_posts/2025-01-03-release-20251.markdown
Labels: in-progress, needs-rebase, rc

#36679 Move backup to installation independent section of common tasks
  source/_docs/configuration.markdown
  source/_includes/common-tasks/data_disk.md
  source/_includes/common-tasks/specific_version.md
  source/_includes/common-tasks/update.md
  source/_integrations/backup.markdown
  source/_redirects
  source/common-tasks/container.markdown
  source/common-tasks/core.markdown
  source/common-tasks/general.markdown
  source/common-tasks/os.markdown
  source/common-tasks/supervised.markdown
  source/getting-started/configuration.markdown
  source/installation/index.html
Labels: next, has-parent

#36680 Small fixes to 2025.1
  source/_posts/2025-01-03-release-20251.markdown
Labels: in-progress, needs-rebase, rc

#36681 backup emergency kit: remove redundant procedures
  source/_includes/common-tasks/update.md
  source/more-info/backup-emergency-kit.markdown
Labels: next, has-parent

#36685 Update references to backup topics
  source/_includes/common-tasks/data_disk.md
  source/_integrations/backup.markdown
  source/common-tasks/os.markdown
  source/more-info/free-space.markdown
Labels: next, has-parent

#36612 Change transparancy in opacity in background view settings
  source/dashboards/views.markdown
Labels: in-progress, next, has-parent, parent-merged

#36683 Upload 3-2-1 backups blog
  source/_posts/2025-01-03-3-2-1-backup.markdown
  source/images/blog/2025-01-backups/art.jpg
  source/images/blog/2025-01-backups/backups.png
  source/images/blog/2025-01-backups/encrypt.png
  source/images/blog/2025-01-backups/locations.png
  source/images/blog/2025-01-backups/wizard.png
Labels: in-progress, needs-rebase, rc

#36687 Fix voice_control/best_practices formatting typo
  source/voice_control/best_practices.markdown
Labels: current

#36699 Updating: fix backup steps to reflect current SW
  source/_includes/common-tasks/update.md
  source/common-tasks/os.markdown
Labels: current

#36702 Navigation: move installation independent up
  source/_includes/asides/common_tasks_navigation.html
  source/_includes/asides/docs_sitemap.html
Labels: current

#36703 Backup emergency kit: add link to restore procedure
  source/more-info/backup-emergency-kit.markdown
Labels: current

#36583 Add HEOS configuration options documentation
  source/_integrations/heos.markdown
Labels: next, has-parent, parent-merged

#36596 Add image platform to Habitica integration
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#36724 Remove deprecated HEOS sign_in/out actions
  source/_integrations/heos.markdown
Labels: next, has-parent, parent-merged

#36732 Fix AND logic for selector filters
  source/_docs/blueprint/tutorial.markdown
Labels: current

#36741 Update denonavr.markdown to add compatible model
  source/_integrations/denonavr.markdown
Labels: current

#36229 Reolink rich notifications tutorial
  source/_integrations/reolink.markdown
  source/images/integrations/reolink/rich_notification__add_action.png
  source/images/integrations/reolink/rich_notification__add_trigger.png
  source/images/integrations/reolink/rich_notification__automations_and_scenes.png
  source/images/integrations/reolink/rich_notification__big_notification.jpg
  source/images/integrations/reolink/rich_notification__camera.png
  source/images/integrations/reolink/rich_notification__chose_entity.png
  source/images/integrations/reolink/rich_notification__cooldown_time_condition.png
  source/images/integrations/reolink/rich_notification__create_automation.png
  source/images/integrations/reolink/rich_notification__device_tracker_condition.png
  source/images/integrations/reolink/rich_notification__entity.png
  source/images/integrations/reolink/rich_notification__entity_select.png
  source/images/integrations/reolink/rich_notification__new_automation.png
  source/images/integrations/reolink/rich_notification__new_trigger.png
  source/images/integrations/reolink/rich_notification__notifications.png
  source/images/integrations/reolink/rich_notification__save.png
  source/images/integrations/reolink/rich_notification__screenshot_take_snapshot.png
  source/images/integrations/reolink/rich_notification__select_fluent_camera.png
  source/images/integrations/reolink/rich_notification__send_to_mobile.png
  source/images/integrations/reolink/rich_notification__send_to_mobile_button.png
  source/images/integrations/reolink/rich_notification__settings.png
  source/images/integrations/reolink/rich_notification__small_notification.jpg
  source/images/integrations/reolink/rich_notification__state.png
  source/images/integrations/reolink/rich_notification__state_select.png
  source/images/integrations/reolink/rich_notification__take_snapshot.png
Labels: current

#36111 Split out remove_device_service_steps
  source/_includes/integrations/remove_device_service.md
  source/_includes/integrations/remove_device_service_steps.md
  source/_integrations/reolink.markdown
Labels: current

#36745 Update the System monitor page
  source/_integrations/systemmonitor.markdown
Labels: current

#36753 Mention Hex in address: description
  source/_integrations/modbus.markdown
Labels: current

#36704 Enquote password in lock out example to aid with special chars
  source/_docs/locked_out.md
Labels: current

#36689 Remove horizontal swing from Sensibo select entities
  source/_integrations/sensibo.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36754 Add some example Hex addresses
  source/_integrations/modbus.markdown
Labels: current

#36757 Getting started: fix link to backup docs
  source/getting-started/onboarding.markdown
Labels: current

#36763 Fix incorrect information in nordpool
  source/_integrations/nordpool.markdown
Labels: current

#36758 Move data disk: remove screenshot
  source/_includes/common-tasks/data_disk.md
  source/images/screenshots/move-datadisk.png
Labels: current

#36771 Fix minor markdown leftover
  source/_integrations/notify.markdown
Labels: current

#36760 Add troubleshooting for user agreement for roborock
  source/_integrations/roborock.markdown
Labels: current

#36769 Improve MQTT update `in_progress` and `update_percentage` documentation
  source/_integrations/update.mqtt.markdown
Labels: current

#36725 Provide steps for Tesla Fleet API 2025 update.
  source/_integrations/tesla_fleet.markdown
Labels: current, integration: tesla_fleet

#36736 Add Get device mode capabilities action to Sensibo
  source/_integrations/sensibo.markdown
Labels: next, has-parent, parent-merged

#36756 Add `hide_create` for todo list card
  source/_dashboards/todo-list.markdown
Labels: next, has-parent, parent-merged

#36775 Update command signing instructions in Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: current

#36670 Update tesla_wall_connector.markdown
  source/_integrations/tesla_wall_connector.markdown
Labels: current

#36737 Suez_water: describe new way to find meter
  source/_integrations/suez_water.markdown
Labels: current, has-parent, parent-merged

#36778 Fix typos in Peblar documentation
  source/_integrations/peblar.markdown
Labels: current

#36777 Updated distributor list for Green and ZBT-1
  source/connectzbt1/index.html
  source/green/index.html
Labels: current

#36776 Fix typo in mqtt update docs
  source/_integrations/update.mqtt.markdown
Labels: current

#36742 Update energyzero.markdown
  source/_integrations/energyzero.markdown
Labels: current

#36790 Add total cleaning count to Roborock
  source/_integrations/roborock.markdown
Labels: next, has-parent, parent-merged

#36599 Palazzetti doc improvement
  source/_integrations/palazzetti.markdown
Labels: current

#36792 Add documentation for new sensors for fyta
  source/_integrations/fyta.markdown
Labels: next, has-parent, parent-merged

#36800 Add KNX integration removal instructions
  source/_integrations/knx.markdown
Labels: in-progress, current, has-parent, parent-merged

#36804 Add /voice redirect
  source/_redirects
Labels: current

#36796 Update KNX connection and secure documentation
  source/_integrations/knx.markdown
  source/images/integrations/knx/device_authentication_password.png
  source/images/integrations/knx/export_keyring_ets.png
  source/images/integrations/knx/knx_ets_authentication_code.png
  source/images/integrations/knx/knx_ets_backbone_key.png
  source/images/integrations/knx/knx_ets_dummy.png
  source/images/integrations/knx/knx_ets_tunnel.png
  source/images/integrations/knx/knx_ets_tunnel_password.png
  source/images/integrations/knx/user_password.png
Labels: current

#36766 Add documentation for binary sensors for fyta
  source/_integrations/fyta.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36807 Fixes font display issues
  source/connectzbt1/index.html
  source/yellow/index.html
Labels: current

#36784 Add actions to Music Assistant (#36469)
  source/_integrations/music_assistant.markdown
Labels: current

#36627 Replace broken "Copy Switch" example
  source/_integrations/switch.template.markdown
Labels: in-progress, current, needs-rebase

#36272 enphase envoy docs quality improvement phase 2
  source/_integrations/enphase_envoy.markdown
  source/images/integrations/enphase_envoy/enphase_envoy_acb_battery.png
  source/images/integrations/enphase_envoy/enphase_envoy_aggr_acb_iq_battery.png
  source/images/integrations/enphase_envoy/enphase_envoy_aggr_iq_battery.png
  source/images/integrations/enphase_envoy/enphase_envoy_consumption.png
  source/images/integrations/enphase_envoy/enphase_envoy_ct_model.png
  source/images/integrations/enphase_envoy/enphase_envoy_dry_contact.png
  source/images/integrations/enphase_envoy/enphase_envoy_encharge.png
  source/images/integrations/enphase_envoy/enphase_envoy_enpower.png
  source/images/integrations/enphase_envoy/enphase_envoy_inverter_device.png
  source/images/integrations/enphase_envoy/enphase_envoy_production_reset.png
  source/images/integrations/enphase_envoy/enphase_envoy_solar_production.png
Labels: current

#36816 Improve inexogy integration documentation
  source/_integrations/discovergy.markdown
Labels: current, has-parent

#36825 Update battery support of Reolink NVRs
  source/_integrations/reolink.markdown
Labels: current

#36770 Add LetPot integration
  source/_integrations/letpot.markdown
Labels: new-integration, next, has-parent, parent-merged

#36828 Add select platform to onewire
  source/_integrations/onewire.markdown
Labels: next, has-parent, parent-merged

#36805 Enable Statistics Graph card to integrate with Energy Dashboard
  source/_dashboards/statistics-graph.markdown
Labels: next, has-parent, parent-merged

#36537 Allow color_mode to be processed in Kelvin for MQTT basic light
  source/_integrations/light.mqtt.markdown
  source/_integrations/mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged, by-code-owner, integration: mqtt

#36782 Add iotty outlet docs (#36289)
  source/_integrations/iotty.markdown
Labels: current

#36540 StarLine running sensor renamed to ignition
  source/_integrations/starline.markdown
Labels: next, has-parent, parent-merged

#36832 Change timeline "now" position
  source/voice-pe/index.html
  source/voice-pe/styles.css
Labels: current

#36812 FGlair : Update documentation for new sensor, add known limitations
  source/_integrations/fujitsu_fglair.markdown
Labels: next, has-parent, parent-merged

#36837 2025.1.2
  _config.yml
  source/_posts/2025-01-03-release-20251.markdown
  source/changelogs/core-2025.1.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#36539 Allow color_mode to be processed in Kelvin for MQTT template light
  source/_integrations/light.mqtt.markdown
Labels: awaits-parent, next, has-parent, parent-merged, by-code-owner, integration: mqtt

#36836 Add removal instructions to LG webOS TV
  source/_integrations/webostv.markdown
Labels: current

#35923 Add config flow to NMBS
  source/_integrations/nmbs.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35784 Added documentation for new integration igloohome
  source/_integrations/igloohome.markdown
Labels: in-progress, next, has-parent, parent-merged

#36869 Update Weheat documentation for quality scale
  source/_integrations/weheat.markdown
Labels: current

#36843 Update docs for timer.change
  source/_integrations/timer.markdown
Labels: current

#36361 Switcher runner child lock support
  source/_integrations/switcher_kis.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#36898 Refer to AI personality instead of tailored to a brand
  source/voice_control/index.markdown
Labels: current

#36530 Changed ThinQ developer site
  source/_integrations/lg_thinq.markdown
Labels: current

#36890 Update SSDP page to add LG webOS TV
  source/_integrations/ssdp.markdown
Labels: current

#36889 Update scene.markdown
  source/_docs/scene.markdown
Labels: current

#36797 Twinkly devices may require an effect to enable control
  source/_integrations/twinkly.markdown
Labels: current

#36834 Add workaround note for Ituran
  source/_integrations/ituran.markdown
Labels: current

#36873 Make icon id more clear in Lametric
  source/_integrations/lametric.markdown
Labels: current

#36879 Collapse Bluetooth adapters with known issues
  source/_integrations/bluetooth.markdown
Labels: current

#36888 Align LG webOS TV docs with quality scale requirements
  source/_integrations/webostv.markdown
Labels: current

#36904 Installation methods overview: backup
  source/installation/index.html
Labels: current

#36878 Add kV and MV unit conversion for voltages
  source/_integrations/number.markdown
  source/_integrations/sensor.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36855 Velbus servicerework doc sync
  source/_integrations/velbus.markdown
Labels: next, has-parent, parent-merged

#36908 Add note for new users to SmartThings
  source/_integrations/smartthings.markdown
Labels: current

#36710 Remove deprecated sensors in Habitica
  source/_integrations/habitica.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36819 Document legacy setpoint handling for incomfort integration
  source/_integrations/incomfort.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: incomfort

#35210 Add description for Habitica get_tasks action.
  source/_integrations/habitica.markdown
Labels: Hacktoberfest, next, has-parent, parent-merged

#35245 Add documentation for hvac_on_value and hvac_off_value in Modbus clim…
  source/_integrations/modbus.markdown
Labels: next, has-parent, parent-merged

#36397 Split MQTT options and reconfigure flow
  source/_integrations/mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#36624 Draft request to update Vesyns humidifier documentation
  source/_integrations/vesync.markdown
Labels: next, has-parent, parent-merged

#36538 Allow color_mode to be processed in Kelvin for MQTT json light
  source/_integrations/light.mqtt.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: mqtt

#36577 Add documentation for Model Context Protocol Server integration
  source/_integrations/mcp_server.markdown
  source/images/integrations/mcp_server/claude-todo-list-control.png
Labels: in-progress, next, has-parent, parent-merged

#36917 Add troubleshooting part to LaMetric
  source/_integrations/lametric.markdown
Labels: awaits-parent, next, has-parent

#36927 Update documentation for piper TTS automation
  source/images/assist/media-message.png
  source/images/assist/select-entity.png
  source/images/assist/speak-action.png
  source/images/assist/tts_action.png
  source/images/assist/tts_enter_text.png
  source/images/assist/tts_select_media_player.png
  source/images/assist/tts_select_media_source.png
  source/images/assist/tts_select_piper.png
  source/voice_control/using_tts_in_automation.markdown
Labels: current

#36803 Improve quality of tplink docs
  source/_integrations/tplink.markdown
Labels: current

#36294 Request to implement documentation for a new Integration (Qbus)
  CODEOWNERS
  source/_integrations/qbus.markdown
Labels: next, has-parent, parent-merged

#36933 VPE links as potential next steps after basic Assist setup
  source/_includes/asides/docs_sitemap.html
  source/voice_control/android.markdown
  source/voice_control/apple.markdown
  source/voice_control/best_practices.markdown
  source/voice_control/expanding_assist.markdown
  source/voice_control/index.markdown
  source/voice_control/voice_remote_cloud_assistant.markdown
  source/voice_control/voice_remote_local_assistant.markdown
Labels: current

#36656 Add documentation for Policy-Based Routing switches
  source/_integrations/unifi.markdown
Labels: in-progress, next, has-parent, parent-merged

#36919 Add number platform
  source/_integrations/vesync.markdown
Labels: next, has-parent

#36938 add Onkyo to SSDP page
  source/_integrations/ssdp.markdown
Labels: current

#36942 Add Lutron Caseta to SSDP page
  source/_integrations/ssdp.markdown
Labels: current

#36949 Improve incomfort docs
  source/_integrations/incomfort.markdown
Labels: current, by-code-owner, integration: incomfort

#36951 Integration concept: fix list item
  source/getting-started/concepts-terminology.markdown
Labels: current

#36826 Palazzetti integration: Add fan speed 0 and silent mode
  source/_integrations/palazzetti.markdown
Labels: awaits-parent, next, has-parent

#35785 Add message_thread_id to telegram_text and telegram_command events
  source/_integrations/telegram_bot.markdown
Labels: in-progress, next, has-parent, parent-merged

#36954 Add better content types to examples
  source/_integrations/music_assistant.markdown
Labels: current

#36961 Document how the data is updated for the incomfort integration
  source/_integrations/incomfort.markdown
Labels: current

#36931 Update docs with info about the new LIFX paint_theme action
  source/_integrations/lifx.markdown
Labels: in-progress, next, has-parent, parent-merged

#36779 Add event entity to Overseerr
  source/_integrations/overseerr.markdown
Labels: next, has-parent, parent-merged

#36936 Update html5.markdown to add the silent parameter
  source/_integrations/html5.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#35904 Add Telegram Bot response message ID
  source/_integrations/telegram_bot.markdown
Labels: next, has-parent, parent-merged

#36844 Preserve integration category filter on noop keyup
  source/integrations/index.html
Labels: current

#36923 Update cgroup_version.markdown
  source/more-info/unsupported/cgroup_version.markdown
Labels: current

#36713 Remove information about removed IMGW-PIB integration entities
  source/_integrations/imgw_pib.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#36808 flux: document how the "mired" mode actually sets kelvin
  source/_integrations/flux.markdown
Labels: in-progress, current, has-parent, needs-rebase

#36880 Add inventory sensors to Habitica
  source/_integrations/habitica.markdown
Labels: next, has-parent, parent-merged

#36723 Add button to move netatmo cover to preferred position
  source/_integrations/netatmo.markdown
Labels: in-progress, next, has-parent, parent-merged

#36815 Add tip for obtaining the device_id
  source/_integrations/lcn.markdown
Labels: current

#36969 Fix mobile nav height
  sass/homeassistant/base/_navigation.scss
Labels: current

#36970 Fix table overflow and sizing
  sass/homeassistant/_overrides.scss
Labels: current

#36967 Improve iotty procucts naming to include model
  source/_integrations/iotty.markdown
Labels: current

#36950 Add support for Govee H5130 pressure sensor
  source/_integrations/govee_ble.markdown
Labels: next, has-parent, parent-merged

#36324 Document optional arguments for yolink "play on speaker hub" service
  source/_integrations/yolink.markdown
Labels: next, has-parent, parent-merged

#34943 Add Energy History to Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: next, has-parent, parent-merged

#36977 Add re-configuration flow to incomfort integration
  source/_integrations/incomfort.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: incomfort

#36996 Disable incomfort diagnostics sensors by default
  source/_integrations/incomfort.markdown
Labels: next, has-parent, parent-merged, by-code-owner, integration: incomfort

#37001 Update stiebel_eltron.markdown
  source/_integrations/stiebel_eltron.markdown
Labels: current

#36999 Add troubleshooting section
  source/_integrations/habitica.markdown
Labels: current

#36988 Add origin device tracker to Teslemetry
  source/_integrations/teslemetry.markdown
Labels: in-progress, next, has-parent, parent-merged

#36998 Update google_generative_ai_conversation.markdown
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#36989 `display_order` for to-do list card
  source/_dashboards/todo-list.markdown
Labels: next, has-parent, parent-merged

#36990 Add "remove integration" section for LCN
  source/_integrations/lcn.markdown
Labels: current

#36983 Update solax.markdown
  source/_integrations/solax.markdown
Labels: current

#36982 Add note that Plusnet Hub Two work with bt_smarthub integration
  source/_integrations/bt_smarthub.markdown
Labels: current

#37009 Add high level description to Nice G.O.
  source/_integrations/nice_go.markdown
Labels: current

#37010 Add removal instructions to Nice G.O.
  source/_integrations/nice_go.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37006 Make wording consistent
  source/_docs/configuration/state_object.markdown
Labels: current

#37005 Improve 'conditions' explanation
  source/_docs/automation/condition.markdown
Labels: current

#37008 Calaway add verified device
  source/_integrations/decora_wifi.markdown
Labels: current

#36821 Add known issue introduction
  source/_integrations/refoss.markdown
Labels: in-progress, next, has-parent, parent-merged
