Repository home-assistant/home-assistant.io, pull requests merged in 2025-06, with the labels that each got.

#39311 Remove core specific documentation from integrations
  source/_integrations/beewi_smartclim.markdown
  source/_integrations/energenie_power_sockets.markdown
  source/_integrations/matter.markdown
  source/_integrations/media_source.markdown
  source/_integrations/onvif.markdown
  source/_integrations/ps4.markdown
  source/_integrations/sql.markdown
  source/_integrations/zerproc.markdown
  source/_integrations/zwave_js.markdown
Labels: in-progress, next, needs-rebase

#39336 Add new SMLIGHT devices to supported device list
  source/_integrations/smlight.markdown
Labels: next, has-parent

#39273 Add binary solar_rising to sun
  source/_integrations/sun.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39371 Fix Green pricing typo
  source/green/index.html
Labels: current

#39374 Fix Met Éireann API document URL
  source/_integrations/met_eireann.markdown
Labels: current

#38535 Map card: add "unit" option
  source/_dashboards/map.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39375 Add ollama thinking docs
  source/_integrations/ollama.markdown
Labels: next, has-parent, parent-merged

#39318 Improve blueprint schema explanation
  source/_docs/blueprint/schema.markdown
Labels: current

#39360 Add homee reconfiguration flow
  source/_integrations/homee.markdown
Labels: next, has-parent, parent-merged

#39388 Fix legacy cover_template option names in template.markdown
  source/_integrations/template.markdown
Labels: current

#39409 Update lxc.markdown
  source/more-info/unsupported/lxc.markdown
Labels: current

#39425 Mention how often SQL sensors are updated
  source/_integrations/sql.markdown
Labels: current

#39415 Update troubleshooting.markdown - show details button
  source/installation/troubleshooting.markdown
Labels: current

#39445 Clarify KNX `respond_to_read`
  source/_integrations/knx.markdown
Labels: current

#39267 Update steps on updating to reflect the current software
  source/_includes/common-tasks/update.md
  source/common-tasks/os.markdown
Labels: current

#39429 Update polling interval for Powerfox integration
  source/_integrations/powerfox.markdown
Labels: next, has-parent

#39464 Expand AirGradient documentation
  source/_integrations/airgradient.markdown
Labels: current

#39471 Z-Wave device exclusion: add intro para
  source/_integrations/zwave_js.markdown
Labels: current

#39475 Z-Wave JS: remove from Home Assistant
  source/_integrations/zwave_js.markdown
Labels: current

#39477 Revert "Z-Wave: update steps on changing log levels to reflect current SW"
  source/_integrations/zwave_js.markdown
Labels: in-progress, current, needs-rebase

#39478 Replace community card
  source/_includes/custom/news.html
  source/images/frontpage/community-day-2025.webp
  source/images/frontpage/community-meetup.webp
Labels: current

#39484 Fix headings in polling interval section
  source/common-tasks/general.markdown
Labels: current

#39486 Change to Alexa devices
  source/_integrations/alexa_devices.markdown
Labels: next, has-parent

#39515 Improve Amazon Devices documentation
  source/_integrations/amazon_devices.markdown
Labels: in-progress, current, needs-rebase

#39517 Change compose.yml -> compose.yaml
  source/_includes/installation/container.md
Labels: current

#39511 Z-Wave factory reset controller: convert SW description into procedure
  source/_integrations/zwave_js.markdown
Labels: current

#39467 Z-Wave controllers: add related link to integration
  source/_docs/z-wave/controllers.markdown
Labels: current

#39525 Add Reolink infrared light brightness doc
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39534 2025.6.1
  _config.yml
  source/_posts/2025-06-11-release-20256.markdown
  source/changelogs/core-2025.6.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#39548 Sort and update template documentation.
  source/_integrations/template.markdown
Labels: current

#39440 Make Tesla Fleet documentation easier to follow
  source/_integrations/tesla_fleet.markdown
Labels: current

#39549 Add installation parameters for LCN
  source/_integrations/lcn.markdown
Labels: current

#39499 Z-Wave: set radio frequency region
  source/_integrations/zwave_js.markdown
Labels: current

#39544 Add verify ssl option to paperless-ngx docs
  source/_integrations/paperless_ngx.markdown
Labels: in-progress, next, has-parent, parent-merged

#39565 Add Reolink privacy mask switch docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39542 Significantly improve Tesla Fleet config flow
  source/_integrations/tesla_fleet.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#39582 Set Home Connect integration scale
  source/_integrations/home_connect.markdown
Labels: next, has-parent

#39592 Clarify open behaviour for tedee
  source/_integrations/tedee.markdown
Labels: current

#39598 Use common WWHA doc structure for Jasco
  source/_integrations/jasco.markdown
Labels: current

#39608 Template docs: update links to point to template docs page
  source/_integrations/alarm_control_panel.markdown
  source/_integrations/overkiz.markdown
  source/_integrations/switchbot.markdown
  source/_posts/2016-02-13-speedtest-bloomsky-splunk-and-garage-doors.markdown
  source/_redirects
Labels: current

#39618 Add extra content id option
  source/_integrations/music_assistant.markdown
Labels: current

#39620 Z-Wave Radio frequency override: align titles
  source/_integrations/zwave_js.markdown
Labels: current

#39630 Adjust feature request links in issue reporting
  .github/ISSUE_TEMPLATE/config.yml
  source/help/index.markdown
Labels: current

#39604 Document statistic selector
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/selector-statistic.png
Labels: next, has-parent, parent-merged

#39628 Add troubleshooting no entities to Onkyo
  source/_integrations/onkyo.markdown
Labels: current

#39640 AI task docs
  source/_integrations/ai_task.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39495 Customize entity: add step to revert entity ID to default
  source/_docs/configuration/customizing-devices.markdown
  source/images/docs/configuration/customizing-entity-dialog.png
  source/images/docs/configuration/customizing-entity.png
Labels: current

#39637 Adjust documentation for the redesigned area card
  source/_dashboards/area.markdown
  source/dashboards/features.markdown
  source/images/dashboards/area-card.png
  source/images/dashboards/area-cards.png
  source/images/dashboards/features/area_controls.png
Labels: awaits-parent, next, has-parent, parent-merged

#39535 Add documentation about HomeWizard battery group mode
  source/_integrations/homewizard.markdown
Labels: next, has-parent, parent-merged

#39661 Add categories to homee documentation
  source/_integrations/homee.markdown
Labels: current

#39665 fix typo in image reference from #31912
  source/_docs/energy/water.markdown
Labels: current

#39657 Add number entity to Russound RIO
  source/_integrations/russound_rio.markdown
Labels: next, has-parent, parent-merged

#39615 Add data availability note to Recorder's get_statistics action
  source/_integrations/recorder.markdown
Labels: current

#38961 Update templating.markdown
  source/_docs/automation/templating.markdown
Labels: current

#39586 Adding missing data property "hold_secs"
  source/_integrations/harmony.markdown
Labels: current

#39594 Add sensor platform to Alexa Devices
  source/_integrations/alexa_devices.markdown
Labels: next, has-parent, parent-merged

#39262 Caveat use of local commands when using LLMs
  source/_docs/automation/trigger.markdown
Labels: current

#39677 Add unique ID support to Trend integration YAML configuration
  source/_integrations/trend.markdown
Labels: next, has-parent, parent-merged

#39058 Add configuration parameters for bosch_alarm
  source/_integrations/bosch_alarm.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39632 Add trigger support for template alarm control panel, fan, lock, and vacuum
  source/_integrations/template.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#39633 Add label_description to template engine
  source/_docs/configuration/templating.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39540 Add Reolink Floodlight PoE/WiFi docs
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#39572 Add new entity descriptions for enphase inverter data
  source/_integrations/enphase_envoy.markdown
Labels: next, has-parent, parent-merged

#39654 Add documentation on how to setup kWh Meter in HomeWizard
  source/_integrations/homewizard.markdown
Labels: next, has-parent, parent-merged

#39553 Update alexa_devices.markdown
  source/_integrations/alexa_devices.markdown
Labels: current, integration: alexa_devices

#39687 2025.6.3
  _config.yml
  source/_posts/2025-06-11-release-20256.markdown
  source/changelogs/core-2025.6.markdown
Labels: in-progress, current, has-parent, needs-rebase

#39691 Revert "AI task docs"
  source/_integrations/ai_task.markdown
Labels: next

#39679 Community day 2025 wrap up blog
  source/_posts/2025-06-24-community-day-2025-wrap-up.markdown
  source/images/blog/2025-06-community-day-wrap-up/art.jpg
Labels: current

#39655 Add fields and multiple support to object selector
  source/_docs/blueprint/selectors.markdown
  source/images/blueprints/selector-object-schema.png
  source/images/blueprints/selector-object.png
Labels: awaits-parent, next, has-parent, parent-merged

#39690 Document `max_sub_interval` for `derivative`
  source/_integrations/derivative.markdown
Labels: next, has-parent, parent-merged

#39694 Add total cycles sensor to Litter-Robot
  source/_integrations/litterrobot.markdown
Labels: next, has-parent, parent-merged

#39703 Add description for new favorite button in Music Assistant
  source/_integrations/music_assistant.markdown
Labels: next, has-parent, parent-merged

#39686 Add cover platform to Qbus integration
  source/_integrations/qbus.markdown
Labels: in-progress, next, has-parent, parent-merged

#39701 Improve docs readability and adjust incorrect information for switchbot integration
  source/_integrations/switchbot.markdown
Labels: current

#39710 Add exclude entities params to area card
  source/_dashboards/area.markdown
Labels: next, has-parent, parent-merged

#39714 Installation methods: fix order
  source/installation/index.html
Labels: current

#39717 Fix missing word in Voice Chapter 10
  source/_posts/2025-06-25-voice-chapter-10.markdown
Labels: current

#39716 Replace broken XML to json conversion tool link
  source/_integrations/sensor.rest.markdown
Labels: current

#39705 Remove model from speak options in Google AI TTS
  source/_integrations/google_generative_ai_conversation.markdown
Labels: next, has-parent, parent-merged

#39722 Add humidifer and led for switchbot integration
  source/_integrations/switchbot.markdown
Labels: next, has-parent, parent-merged

#39723 Update: reformat mk for switchbot cloud
  source/_integrations/switchbot_cloud.markdown
Labels: current

#39728 Z-Wave controller reset: add prereq steps
  source/_integrations/zwave_js.markdown
Labels: current

#39731 Add SwitchBot WWHA for Bluetooth
  source/_integrations/switchbot.markdown
Labels: current

#39734 Add removal instructions for Sonos integration
  source/_integrations/sonos.markdown
Labels: current

#39738 Remove deprecated dweet integration
  source/_integrations/dweet.markdown
  source/_redirects
Labels: awaits-parent, next, has-parent, parent-merged

#39746 Fix typo in SwitchBot Matter docs
  source/_integrations/switchbot_matter.markdown
Labels: current

#39736 Rewrite Tesla Fleet changes
  source/_integrations/tesla_fleet.markdown
Labels: next, has-parent

#39735 Add Rehlko Kohler 30RCL to list of generators that work.
  source/_integrations/rehlko.markdown
Labels: current

#39643 Update database schema
  source/_docs/backend/database.markdown
Labels: current

#39518 Note to make clear that pihole >= 6.0 is not supported
  source/_integrations/pi_hole.markdown
Labels: current

#39288 Fix weather forecast lovelace card documentation
  source/_dashboards/weather-forecast.markdown
Labels: current

#39748 Add details for second screen to Tuya documentation
  source/_integrations/tuya.markdown
Labels: current

#39757 Fixed the cmps abbreviation
  source/_integrations/mqtt.markdown
Labels: current

#39762 Fix more incorrect MQTT device discovery abbreviations for `cmps`
  source/_integrations/mqtt.markdown
Labels: current, by-code-owner, integration: mqtt

#39761 Add a note that PG&E for Opower currently only works for old accounts
  source/_integrations/opower.markdown
Labels: current

#39764 Update light.markdown
  source/_dashboards/light.markdown
Labels: in-progress, current, has-parent, needs-rebase

#39771 Fix grammar in introduction of Sensor card docs
  source/_dashboards/sensor.markdown
Labels: current

#39770 Replace "your entity" with "an entity" in Tile card docs
  source/_dashboards/tile.markdown
Labels: current

#36734 Document zabbix publish_string_states config
  source/_integrations/zabbix.markdown
Labels: next, has-parent, parent-merged

#39607 Update alexa_devices.markdown
  source/_integrations/alexa_devices.markdown
Labels: current
