Repository home-assistant/home-assistant.io, pull requests merged in 2025-02, with the labels that each got.

#37241 Remove note that the free Gemini tier is not available in all regions
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#37242 Fix a reference to OpenAI in the Google Generative AI docs
  source/_integrations/google_generative_ai_conversation.markdown
Labels: current

#37189 Add information about pets to litterrobot
  source/_integrations/litterrobot.markdown
Labels: next, has-parent, parent-merged

#37228 Tag Google Drive integration as platinum in docs
  source/_integrations/google_drive.markdown
Labels: next

#37076 Document switch platform for LetPot integration
  source/_integrations/letpot.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#37082 Added documentation for hvac_onoff_coil (Enable Modbus Climate / HVAC on/off to use the coil instead of the registers)
  source/_integrations/modbus.markdown
Labels: next, has-parent, parent-merged

#37255 Add Linx virtual motionblinds integration docs
  source/_integrations/linx.markdown
Labels: next, has-parent, parent-merged

#37261 Add note about disabling Bluetooth adapters with poor performance
  source/_integrations/bluetooth.markdown
Labels: current

#37267 Update airthings_ble.markdown
  source/_integrations/airthings_ble.markdown
Labels: current

#37274 Add a note how to find backup location integrations in common tasks > backup
  source/_includes/common-tasks/backups.md
Labels: in-progress, next, needs-rebase

#37273 Add note about separator of backup path in Synology DSM
  source/_integrations/synology_dsm.markdown
Labels: in-progress, next, needs-rebase

#37218 Home Connect now adds entities automatically
  source/_integrations/home_connect.markdown
Labels: next, has-parent, parent-merged

#37278 Backup: add related topic to backup locations
  source/_integrations/backup.markdown
Labels: next, has-parent

#37280 Emergency kit: update steps to reflect current software
  source/more-info/backup-emergency-kit.markdown
Labels: in-progress, next, needs-rebase

#37253 Add Ublockout virtual integration docs
  source/_integrations/motion_blinds.markdown
  source/_integrations/ublockout.markdown
Labels: next, has-parent, parent-merged

#37257 Add Heicko virtual motionblinds integration docs
  source/_integrations/heicko.markdown
Labels: next, has-parent, parent-merged

#37279 Add information about Shelly BLU TRV and Gen4 devices
  source/_integrations/shelly.markdown
Labels: awaits-parent, next, has-parent

#37248 Update mcp server documentation with additional information
  source/_integrations/mcp_server.markdown
Labels: next, has-parent

#37239 Update Tradfri integration documentation to include Matter support
  source/_integrations/tradfri.markdown
Labels: current

#37252 Use /media/ folder instead of /config/www/ folder for Reolink rich notifications
  source/_integrations/reolink.markdown
Labels: current

#37251 Add Reolink "Auto pause rich notifications" tutorial
  source/_integrations/reolink.markdown
  source/images/integrations/reolink/auto_pause__automation_choose.png
  source/images/integrations/reolink/auto_pause__automation_select_first.png
  source/images/integrations/reolink/auto_pause__automation_start_timer.png
  source/images/integrations/reolink/auto_pause__automation_triggered_by.png
  source/images/integrations/reolink/auto_pause__automation_wait_for_trigger.png
  source/images/integrations/reolink/auto_pause__automation_when.png
  source/images/integrations/reolink/auto_pause__automation_when_timer.png
  source/images/integrations/reolink/auto_pause__condition.png
  source/images/integrations/reolink/auto_pause__dropdown.png
  source/images/integrations/reolink/auto_pause__overview.png
  source/images/integrations/reolink/auto_pause__result_when_running.png
  source/images/integrations/reolink/auto_pause__timer.png
Labels: current

#37232 Mention CSRF in Overseerr docs
  source/_integrations/overseerr.markdown
Labels: awaits-parent, next, has-parent

#37297 Add Pimoroni to Voice PE distributors list
  source/_data/products.yml
Labels: current

#37074 Add schedule.get_schedule action documentation
  source/_integrations/schedule.markdown
Labels: next, has-parent, parent-merged

#36343 Update starlink.markdown with details of new sensors
  source/_integrations/starlink.markdown
Labels: next, has-parent, parent-merged

#36992 Added documentation about the shelly.script_event event type
  source/_integrations/shelly.markdown
Labels: next, has-parent, parent-merged

#37298 Remove Thread under active development
  source/green/index.html
Labels: current

#37303 Update ubus wiki link
  source/_integrations/ubus.markdown
Labels: current

#37302 Statistics graph: update screenshots
  source/images/dashboards/statistics_graph_bar.png
  source/images/dashboards/statistics_graph_line.png
Labels: next, has-parent

#37289 Add important note to Synology DSM docs to not modify the backup files manually
  source/_integrations/synology_dsm.markdown
Labels: awaits-parent, in-progress, next, has-parent

#37304 Energy dashboard: update screenshots
  source/images/dashboards/energy/devices-detail-graph.png
  source/images/dashboards/energy/devices-graph.png
  source/images/dashboards/energy/gas-graph.png
  source/images/dashboards/energy/solar-graph.png
  source/images/dashboards/energy/usage-graph.png
Labels: next, has-parent

#36860 Add iometer integration documentation
  source/_integrations/iometer.markdown
Labels: in-progress, next, has-parent, parent-merged

#37300 Add note about enable-query and enable-status
  source/_integrations/minecraft_server.markdown
Labels: current

#37308 Swap 'p' and 'platform' in table of abbreviations to correct order.
  source/_integrations/mqtt.markdown
Labels: current

#37196 Fix template sensor types in documentation
  source/_integrations/template.markdown
Labels: current

#37311 Better explain the abilities of Cloud
  source/_integrations/cloud.markdown
Labels: current

#37312 Fix letter cutoff
  sass/homeassistant/aside/_buy_dialog.scss
Labels: current

#37313 Add Switchbot Remote to the list of supported devices
  source/_integrations/switchbot.markdown
Labels: next, has-parent, parent-merged

#37314 Small edits to the release notes
  source/_posts/2025-02-05-release-20252.markdown
Labels: in-progress, needs-rebase, rc

#37112 Update govee-light-local docs
  source/_integrations/govee_light_local.markdown
Labels: awaits-parent, in-progress, next, has-parent, parent-merged

#36608 Clarify hass availability and usage for Home Assistant Core users
  source/_docs/tools/hass.markdown
Labels: current

#37324 When downloading from backup page, backup is decrypted
  source/_includes/common-tasks/backups.md
Labels: current

#37323 History graph: update screenshots to reflect current SW
  source/images/dashboards/history_graph.png
  source/images/dashboards/history_graph_lines.png
Labels: current

#37325 Add new Reolink push callback info
  source/_integrations/reolink.markdown
Labels: current

#37326 Storing emergency kit: clarify steps
  source/more-info/backup-emergency-kit.markdown
Labels: current

#37329 Add Bluesky links, and add redirects for Bluesky and Mastodon
  source/_includes/site/footer.html
  source/_redirects
Labels: in-progress, current, has-parent, needs-rebase

#37335 Explain use of `collection_key` for energy cards
  source/_dashboards/energy.markdown
Labels: current

#37330 Update Shelly Bluetooth device requirements
  source/_integrations/bluetooth.markdown
Labels: current

#37337 Update statistics-graph.markdown - link collection_key documentation
  source/_dashboards/statistics-graph.markdown
Labels: current

#37117 Add IRK instructions for android
  source/_integrations/private_ble_device.markdown
Labels: current

#37086 Update openai_conversation.markdown
  source/_integrations/openai_conversation.markdown
Labels: current

#37004 Vesync Binary Sensor
  source/_integrations/vesync.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37338 Make `payload` attribute optional again for MQTT publish action
  source/_integrations/mqtt.markdown
Labels: next, has-parent, parent-merged

#37327 Add description of new sensor states in MotionMount integration
  source/_integrations/motionmount.md
Labels: next, has-parent

#37293 Update squeezebox.markdown
  source/_integrations/squeezebox.markdown
Labels: current

#37265 Update troubleshooting.markdown
  source/voice_control/troubleshooting.markdown
Labels: current

#37216 Add event platform to Bring integration
  source/_integrations/bring.markdown
Labels: next, has-parent, parent-merged

#37339 Replace still image example in generic camera
  source/_integrations/generic.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37348 Clarify hardware needs for flexit_bacnet
  source/_integrations/flexit_bacnet.markdown
Labels: current

#37353 2025.2.1
  _config.yml
  source/_posts/2025-02-05-release-20252.markdown
  source/changelogs/core-2025.2.markdown
Labels: blog, in-progress, current, has-parent, needs-rebase, parent-merged

#37360 Update onedrive docs
  source/_integrations/onedrive.markdown
Labels: current

#37363 Add Peblar charge switch
  source/_integrations/peblar.markdown
Labels: next, has-parent, parent-merged

#37372 Improve instructions for a custom app registration to onedrive
  source/_integrations/onedrive.markdown
  source/images/integrations/onedrive/onedrive-app-registration.png
Labels: current

#37286 add roborock scene support
  source/_integrations/roborock.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37371 Add info about multiple targets support for Slack integration
  source/_integrations/slack.markdown
Labels: current

#37276 Add media description to Mastodon post action
  source/_integrations/mastodon.markdown
Labels: in-progress, next, has-parent, parent-merged

#37381 Add documentation for message_thread_id data attribute for telegram notify integration
  source/_integrations/telegram.markdown
  source/_integrations/telegram_bot.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#37340 Improve Bring! integration documentation
  source/_integrations/bring.markdown
Labels: current

#37388 Improve `flick_electric` documentation
  source/_integrations/flick_electric.markdown
Labels: current

#37392 Add docs for fireplace mode
  source/_integrations/flexit_bacnet.markdown
Labels: next, has-parent, parent-merged

#37395 Update notification texts in Bring
  source/_integrations/bring.markdown
Labels: current

#37396 badge visibility: add link to available conditions
  source/_dashboards/conditional.markdown
  source/dashboards/badges.markdown
  source/dashboards/cards.markdown
Labels: current

#37398 Update season.markdown
  source/_integrations/season.markdown
Labels: current

#37397 Remove unused country code selection
  source/_includes/custom/buy-dialog.html
Labels: current

#37403 Update season.markdown
  source/_integrations/season.markdown
Labels: current

#37404 2025.2.2
  _config.yml
  source/_posts/2025-02-05-release-20252.markdown
  source/changelogs/core-2025.2.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#37410 Use consistent constant in Tesla Fleet
  source/_integrations/tesla_fleet.markdown
Labels: current

#37406 Example correction
  source/_integrations/foscam.markdown
Labels: current

#37405 Update shopping_list.markdown
  source/_integrations/shopping_list.markdown
Labels: current

#37413 motionEye: update tap action keywords in example
  source/_integrations/motioneye.markdown
Labels: current

#37419 Rpi imager: move link to image download into procedure
  source/installation/raspberrypi.markdown
Labels: current

#37424 Update timer.markdown; timer.cancel and timer.finish both work on active AND paused timers
  source/_integrations/timer.markdown
Labels: next, has-parent

#37096 Media player browse media action documentation
  source/_integrations/media_player.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37431 Fix small typo in Shelly docs
  source/_integrations/shelly.markdown
Labels: current

#37393 Add documentation for onedrive sensor platform.
  source/_integrations/onedrive.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37433 2025.2.3
  _config.yml
  source/_posts/2025-02-05-release-20252.markdown
  source/changelogs/core-2025.2.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#37435 Add configuration_basic, move Add integration button to the top
  source/_integrations/flexit_bacnet.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37436 Update Google Assistant integration to remove references to "Actions on Google Console"
  source/_integrations/google_assistant.markdown
Labels: current

#37332 Add night light brightness
  source/_integrations/vesync.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37449 Voice chapter 9 blog upload
  source/_posts/2025-02-13-voice-chapter-9-speech-to-phrase.markdown
  source/images/blog/2025-02-voice-chapter-9/art.jpg
  source/images/blog/2025-02-voice-chapter-9/green-pe.png
  source/images/blog/2025-02-voice-chapter-9/shared-history.png
  source/images/blog/2025-02-voice-chapter-9/stp-logo.jpg
Labels: current

#37454 Remove scan interval option from Synology DSM
  source/_integrations/synology_dsm.markdown
Labels: next, has-parent, parent-merged

#37442 Document Opower supports Burbank Water and Power (BWP)
  source/_integrations/opower.markdown
Labels: next, has-parent, parent-merged

#37444 Add missing backward-incompatible change remove missed remark on MQTT publish action templates
  source/_integrations/mqtt.markdown
  source/_posts/2025-02-05-release-20252.markdown
Labels: current, by-code-owner, integration: mqtt

#37441 Add information about data update frequency
  source/_integrations/flexit_bacnet.markdown
Labels: in-progress, current, has-parent, needs-rebase

#37456 Add Speech-to-Phrase add-on to Wyoming docs
  source/_integrations/wyoming.markdown
Labels: current

#37457 Update templating.markdown to include trigger.alias
  source/_docs/automation/templating.markdown
Labels: current

#37462 Make clear you need Ubuntu Desktop
  source/_includes/installation/operating_system.md
Labels: current

#37453 Document sensor platform for LetPot integration
  source/_integrations/letpot.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37463 2025.2.4
  _config.yml
  source/_posts/2025-02-05-release-20252.markdown
  source/changelogs/core-2025.2.markdown
Labels: in-progress, current, has-parent, needs-rebase, parent-merged

#31251 Add pglab documentation
  source/_integrations/pglab.markdown
Labels: new-integration, next, has-parent, parent-merged

#37409 Update balboa documentation for new time support
  source/_integrations/balboa.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37470 Document binary sensor platform for LetPot integration
  source/_integrations/letpot.markdown
Labels: next, has-parent, parent-merged

#37478 Fixes grammar
  source/_integrations/integration.markdown
Labels: current

#37474 Update packages.markdown
  source/_docs/configuration/packages.markdown
Labels: current

#37479 Update balboa docs to include switch entity for toggling filter cycle 2
  source/_integrations/balboa.markdown
Labels: next, has-parent, parent-merged

#37480 Note that Denon AVR-E300 works with denonavr
  source/_integrations/denonavr.markdown
Labels: current

#36896 Allow wifi switches on mesh repeaters in AVM Fritz!Box Tools
  source/_integrations/fritz.markdown
Labels: next, has-parent, parent-merged

#37447 Update qBittorrent docs for new sensors
  source/_integrations/qbittorrent.markdown
Labels: next, has-parent, parent-merged

#37468 Add `home_connect.set_program_and_options`
  source/_integrations/home_connect.markdown
Labels: next, has-parent, parent-merged

#37464 Clarify controller versions for Qbus integration (#37432)
  source/_integrations/qbus.markdown
Labels: current

#37489 Misc minor fixes for integrations
  source/_integrations/gstreamer.markdown
  source/_integrations/html5.markdown
  source/_integrations/hue.markdown
  source/_integrations/influxdb.markdown
  source/_integrations/islamic_prayer_times.markdown
  source/_integrations/light.mqtt.markdown
Labels: current

#37494 Doc update for Squeezebox Config Options
  source/_integrations/squeezebox.markdown
Labels: next, has-parent, parent-merged

#37492 Zha doc enhancements
  source/_integrations/zha.markdown
Labels: current

#37496 Revise ZHA troubleshooting and limitations sections
  source/_integrations/zha.markdown
Labels: current

#37497 Unify ZHA configuration section, include standard config_flow steps.
  source/_integrations/zha.markdown
Labels: current

#37401 Update number platform for ohme
  source/_integrations/ohme.markdown
Labels: in-progress, next, has-parent, needs-rebase, parent-merged

#37417 Amcrest integration: update tap action keywords
  source/_integrations/amcrest.markdown
Labels: current

#37415 document actions that trigger a 'shopping_list_updated ' event
  source/_integrations/shopping_list.markdown
Labels: in-progress, current, needs-rebase

#37509 Document that you need to set up the device with the app first
  source/_integrations/switcher_kis.markdown
Labels: current

#37512 Z-Wave: add required documentation on identify command
  source/_integrations/zwave_js.markdown
Labels: current

#37515 Add inline features position for tile card
  source/_dashboards/tile.markdown
Labels: in-progress, next, has-parent, parent-merged

#37495 Reolink h265 encoding troubleshooting
  source/_integrations/reolink.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37528 Matter Troubleshooting: add steps
  source/_integrations/matter.markdown
Labels: current

#37529 Add CVE-2025-25305
  source/security/index.markdown
Labels: current

#37530 Fix CVE-2025-25305 CVSS score
  source/security/index.markdown
Labels: current

#37517 Doc Update for Squeezebox Announce functionality
  source/_integrations/squeezebox.markdown
Labels: next, has-parent, parent-merged

#37534 Remove explicit platform list from media_player.shuffle_set action docs
  source/_integrations/media_player.markdown
Labels: current

#37533 Added Smart Guys as Australian Yellow distributor
  source/_data/products.yml
Labels: current

#37537 Add note that Govee 5074 models require active scans
  source/_integrations/govee_ble.markdown
Labels: current

#37536 Add HEOS media_player.group_volume_set documentation
  source/_integrations/heos.markdown
Labels: in-progress, next, has-parent, parent-merged, by-code-owner

#37535 Fixed broken example in intent_script.markdown
  source/_integrations/intent_script.markdown
Labels: current

#37550 Matter: merge duplicate troubleshooting sections
  source/_integrations/matter.markdown
Labels: current

#37551 Matter: rephrase to improve readability
  source/_integrations/matter.markdown
Labels: current

#37552 Note to try Android 12 or later for commissioning Matter devices
  source/_integrations/matter.markdown
Labels: current

#37553 Unable to commission: restructure to improve readability
  source/_integrations/matter.markdown
Labels: current

#37554 Move Bang & Olufsen Event entity documentation
  source/_integrations/bang_olufsen.markdown
Labels: current

#37558 Matter: troubleshoot 'device requires border router'
  source/_integrations/matter.markdown
Labels: current

#37560 Matter via Android: troubleshoot 'checking network connectivity'
  source/_integrations/matter.markdown
Labels: current

#37120 Adds Tado Child Lock switch information
  source/_integrations/tado.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37104 Improve schedule documentation
  source/_integrations/schedule.markdown
Labels: current

#37571 Add Trigger Selector example in Selectors Documentation
  source/_docs/blueprint/selectors.markdown
Labels: current

#37527 Mention MyTeslamate API Registration
  source/_integrations/tesla_fleet.markdown
Labels: current, integration: tesla_fleet

#37575 Add remove instructions for Home Connect
  source/_integrations/home_connect.markdown
Labels: current

#37519 Add LINAK virtual integration supported by Idasen Desk
  CODEOWNERS
  source/_integrations/linak.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37469 Delete Home Connect deprecated actions
  source/_integrations/home_connect.markdown
Labels: next, has-parent

#37264 Add VoIP configuration information
  source/_integrations/voip.markdown
Labels: awaits-parent, next, has-parent, parent-merged

#37573 Add HEOS group volume down/up actions docs
  source/_integrations/heos.markdown
Labels: next, has-parent, parent-merged

#37577 Add missing voice chapters
  source/_posts/2022-12-20-year-of-voice.markdown
Labels: current

#37541 Update environment_canada.markdown
  source/_integrations/environment_canada.markdown
Labels: next, has-parent

#37482 Update androidtv_remote.markdown
  source/_integrations/androidtv_remote.markdown
Labels: current
